### ISSUE TITLE
error in MacOS serria(10.12)

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#10]
I use brew to install miktex in Mac ,but when I type tex in cmd ,but there is no such command , and i type the mpm list, the error is 👍 
log4cxx: No appender could be found for logger (mpmcli).
log4cxx: Please initialize the log4cxx system properly.

**Comment by edocevoli** [comment]
This is the wrong issue tracker. Mac/Homebrew specific bugs should be reported here: https://github.com/MiKTeX/homebrew-miktex/issues
