### ISSUE TITLE
compile/typeset always fails.

### ISSUE THREAD

**Issue by DavidBWallace** [MiKTeX/miktex#1003]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

"MiKTeX installation report" i. e. the result of >initexmf --report> miktex-report.txt

https://miktex.org/howto/bug-report : The term 'https://miktex.org/howto/bug-report' is not recognized as the name of
a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At line:1 char:1
+ https://miktex.org/howto/bug-report
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (https://miktex.org/howto/bug-report:String) [], CommandNotFoundExceptio
   n
    + FullyQualifiedErrorId : CommandNotFoundException

HERE IS THE NEW ISSUE:

% Using TeXworks v6.6, attempts to compile/typeset the simple document below with the pdfLaTeX option fails.

\documentclass{article}
\begin{document}
Small is beautiful.
\end{document}

% the Console output: 

Sorry, but "C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\pdflatex.exe" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/David/AppData/Local/MiKTeX/2.9/miktex/log/pdflatex.log

You may want to visit the MiKTeX project page, if you need help.

% the corresponding pdflatex.log entry is: 

2021-12-18 13:49:40,844-0500 FATAL pdflatex - Bad parameter value.
2021-12-18 13:49:40,859-0500 FATAL pdflatex - Info: cfgname="font_mem_size"
2021-12-18 13:49:40,859-0500 FATAL pdflatex - Source: libraries\miktex\texandfriends\include\miktex\texandfriends\TeXApp.h
2021-12-18 13:49:40,859-0500 FATAL pdflatex - Line: 221

%  What is the fix? ? ? ?

**Comment by edocevoli** [comment]
Seems that `font_mem_size` is out of bounds. Make sure it's value is between 20000 and 147483647.
