### ISSUE TITLE
Compile/typeset always fails

### ISSUE THREAD

**Issue by DavidBWallace** [MiKTeX/miktex#1004]
% Using TeXworks v6.6, attempts to compile/typeset the simple document below with the pdfLaTeX option fails. Also always fails with other documents and other options.

\documentclass{article}
\begin{document}
Small is beautiful.
\end{document}

% the Console output:

Sorry, but "C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\pdflatex.exe" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

C:/Users/David/AppData/Local/MiKTeX/2.9/miktex/log/pdflatex.log

You may want to visit the MiKTeX project page, if you need help.

% the corresponding pdflatex.log entry is:

2021-12-18 13:49:40,844-0500 FATAL pdflatex - Bad parameter value.
2021-12-18 13:49:40,859-0500 FATAL pdflatex - Info: cfgname="font_mem_size"
2021-12-18 13:49:40,859-0500 FATAL pdflatex - Source: libraries\miktex\texandfriends\include\miktex\texandfriends\TeXApp.h
2021-12-18 13:49:40,859-0500 FATAL pdflatex - Line: 221

% What is the fix? ? ? ?

**Comment by edocevoli** [comment]
The fix was outlined in #1003. If you need help with your MiKTeX setup: please understand that this is not a help/support forum.

Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by edocevoli** [comment]
Dup of #1003
