### ISSUE TITLE
 update sever enhancement

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#101]
It seems that each time I try to update/install new packages, the MiKTeX update wizard will internally first connect to http://api.miktex.org/Repository.asmx.

Is it possible to skip this step?or just update like texlive method?because update server always offline. I am in China，it seems always cannot connect to api. miktex. org,It's really slow for me to connect internationally but would be much much faster since lots of mirrors within country are available.

Or is there any trick to use proxy only for this http://api.miktex.org/Repository.asmx URL but not mirrors I will connect to?

**Comment by edocevoli** [comment]
The `http://api.miktex.org/Repository.asmx` endpoint is deprecated/obsolete. Newer MiKTeX versions use the `https://api2.miktex.org` endpoint.

**Comment by qiuzhu** [comment]
3q，maybe only in China has this problem，but it really affect the experience of using miktex，for example，I always set the repo to tuna（one of China repo），but next time，it always disappear in repo list of miktex setting，so i have to switch back to other repo but downloading speed is very slow because of far from China. What can I do to improve this situation?
