### ISSUE TITLE
Link to Setup Utility does not work on https://miktex.org/announcement/miktex-setup-utility

### ISSUE THREAD

**Issue by TobiBS** [MiKTeX/miktex#1014]
- [X ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

The link to download the Setup Utility on https://miktex.org/announcement/miktex-setup-utility points to http://mirrors.ctan.org/systems/win32/miktex/setup/miktexsetup.zip however due to restructuring of the folders, the files are now found at http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x64/ or http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x86/ respectively.

**Comment by edocevoli** [comment]
Thank you, I have fixed the link.
