### ISSUE TITLE
bug of dvipdfm-x

### ISSUE THREAD

**Issue by ostaith** [MiKTeX/miktex#1015]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

for the `pdfparse.c` file in `dvipdfm-x`, the `static const char *valid_chars` in the function `parse_ident` missing `/`.

```
char *
parse_ident (const char **start, const char *end)
{
  static const char *valid_chars =
    "!\"#$&'*+,-.0123456789:;=?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\\^_`abcdefghijklmnopqrstuvwxyz|~";

  return parse_gen_ident(start, end, valid_chars);
}
```

should change to:
```
char *
parse_ident (const char **start, const char *end)
{
  static const char *valid_chars =
    "!\"#$&'*+,-./0123456789:;=?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\\^_`abcdefghijklmnopqrstuvwxyz|~";

  return parse_gen_ident(start, end, valid_chars);
}
```

because when I set StemV for TureType font (such simhei.ttf), the `fontmap` is:
`C:/Windows/Fonts/simhei.ttf/0/H/65536/0/0`
but because `valid_chars` don't include `/`, so I can't add:
`C:/Windows/Fonts/simhei.ttf/0/H/65536/0/0 Identity-H FangZhengFangSong-GBK-1.ttf -v 50` in `cid-x.map` to change SimHei's StemV.

I don't know the where is `dvipdfmx`'s repo, so I submit the issue here.

**Comment by edocevoli** [comment]
I was able to find the dvipdmx bug tracker with these keywords: dvipdfmx bug report. Please visit https://tug.org/dvipdfmx/
