### ISSUE TITLE
mthelp seems conflict with firefox on Macos

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#102]
I update the latest version 6650 of Miktex on Mac , and when I input `mthelp tcolorbox`
the messge shows:

>/bin/sh: firefox: command not found

**Comment by edocevoli** [comment]
Yes, I can confirm that this is a bug. Please note that `firefox` (the executable) usually cannot be started in a shell: The executable is buried deep inside an application bundle and not in the `PATH`.

The bug will be fixed in a future version.
