### ISSUE TITLE
build: can't connect to https://anorien.csc.warwick.ac.uk

### ISSUE THREAD

**Issue by aabacchus** [MiKTeX/miktex#1039]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Building the latest release 22.1:

```
curl: (28) Failed to connect to anorien.csc.warwick.ac.uk port 443 after 131769 ms: Operation timed out
make[2]: *** [CMakeFiles/gen-bootstrapping-files.dir/build.make:91: miktex-misc.tar.lzma] Error 28
make[1]: *** [CMakeFiles/Makefile2:3418: CMakeFiles/gen-bootstrapping-files.dir/all] Error 2
```

This has happened a few times with various targets from `CMakeFiles/gen-bootstrapping-files.dir/build.make`.

I have tried using several different networks and using VPNs etc but they all time out trying to connect to https://anorien.csc.warwick.ac.uk. Would it be possible for the required content to be provided either in the MiKTeX repo/tarball or proxied?

**Comment by aabacchus** [comment]
Yes, this downtime is probably temporary, but it would be nice for the build to be possible without a network connection - it looks like the stuff in `CMakeFiles/gen-bootstrapping-files.dir/build.make` is the only stuff that needs to be downloaded?

**Comment by edocevoli** [comment]
IIRC, a few files need to be downloaded. You can preselect a package repository by setting `MIKTEX_REPOSITORY`. For example

```sh
MIKTEX_REPOSITORY=https://mirror.physik.tu-berlin.de/pub/CTAN/systems/win32/miktex/tm/packages/ cmake .

```
