### ISSUE TITLE
MikTeX says somethin about "something wrong, try to switch to admin mode, and try to upgrade. Then I get an internal error.

### ISSUE THREAD

**Issue by Dirk2** [MiKTeX/miktex#1043]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
GENERAL MIKTEX INFORMATION
ReportDate: 2022-02-04 17:00:19
CurrentVersion: 21.12
SetupDate: 2022-02-04 16:18:00
SetupVersion: 2.9
Configuration: Regular
GitInfo: e557b95 / 2021-12-06 09:25:33
OS: Windows 10 Pro, 64-bit, build 19043
SharedSetup: yes
LinkTargetDirectory: D:\Program Files\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2022-02-04 16:59:32
LastUpdateAdmin: not yet
LastUpdateDbAdmin: 2022-02-04 16:59:32
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: d:\Program Files\MiKTeX 2.9
CommonInstall: d:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: 

ERROR DETAILS
Program: miktex-console_admin
Source: Libraries\MiKTeX\Core\Session\papersize.cpp:243
Error: C:\jenkins\workspace\miktex\windows\build\source\Libraries\MiKTeX\Core\Session\papersize.cpp:243: internal error

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
