### ISSUE TITLE
[Low Priority] Mirror assigned to wrong country mirror.mwt.me

### ISSUE THREAD

**Issue by mwt** [MiKTeX/miktex#1048]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

My CTAN mirror, [`mirror.mwt.me`](https://mirror.mwt.me/ctan/), is labeled as being in the UK within MiKTeX and on the [MiKTeX mirror page](https://miktex.org/pkg/repositories). However, it is actually in the US and is listed as a US mirror on [CTAN's site](https://ctan.org/mirrors?lang=en).

I don't know why this would happen. Perhaps there is some assumption made by the script that generates the list of mirrors.

**Comment by edocevoli** [comment]
According to this host it is in UK:

<img width="795" alt="Screenshot 2022-02-11 165725" src="https://user-images.githubusercontent.com/20090840/153624775-1939e8f5-0a87-4978-ae32-a8d7240dce66.png">

**Comment by mwt** [comment]
There does seem to be one incorrect geolocation database. Can you reclassify the mirror, or should I try to correct this with the database provider?

![IP Location Finder - Geolocation](https://user-images.githubusercontent.com/13644285/153632360-47eade98-083b-4d79-b6b6-5a469da0b5e3.png)

Do you use this [ipdata.co](https://ipdata.co/)? I can try to contact them. If I correct it with them, would it update in MiKTeX?

**Comment by edocevoli** [comment]
MiKTEX uses the maxmind database to determine the location. Maybe this will be fixed automatically in a future database update.

**Comment by mwt** [comment]
I do not have physical access, but the node has a faster ping from NYC than it does to London. I also don't pay for bandwidth to other nodes that are credibly in this datacenter.

Tricking me about the location of the datacenter would not be that easy and wouldn't really benefit the hosting company.

I instead suspect that this IP was assigned by Leaseweb to a UK service at some point before being assigned to me. This was probably a while ago because most databases show a US location.
