### ISSUE TITLE
Fatal pdflatex error on Linux: memory dump file could not be found.

### ISSUE THREAD

**Issue by andrewdbate** [MiKTeX/miktex#1053]
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I am running MiKTeX on elementary OS 6.1, which is a derivative of Ubuntu 20.04 LTS (it uses a different desktop environment).

I have a file `example.txt` with the following contents:
```
\documentclass{article}
\begin{document}
Hello World!
\end{document}
```

When I attempt to run `pdflatex` I always get the following error:
```
$ pdflatex example.tex 
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (MiKTeX 22.1) (preloaded format=pdflatex.fmt)
 restricted \write18 enabled.

Sorry, but pdflatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  /home/andrew/.miktex/texmfs/data/miktex/log/pdflatex.log
```

Here is the contents of the log:
```
$ cat /home/andrew/.miktex/texmfs/data/miktex/log/pdflatex.log
2022-02-15 16:28:10,085Z INFO  pdflatex - this process (417116) started by bash in directory /home/andrew/Documents/Tenancy/bugfix with command line: pdflatex example.tex
2022-02-15 16:28:10,085Z INFO  pdflatex - this is MiKTeX-PDFTEX 4.10.0 (1.40.24) (MiKTeX 22.1)
2022-02-15 16:28:10,085Z INFO  pdflatex - allowing known shell commands
2022-02-15 16:28:10,089Z INFO  pdflatex - going to create file: pdflatex.fmt
2022-02-15 16:28:10,123Z INFO  pdflatex.core - forking...
2022-02-15 16:28:10,397Z ERROR pdflatex - /usr/bin/miktex did not succeed; exitCode: 1
2022-02-15 16:28:10,397Z ERROR pdflatex - output:
2022-02-15 16:28:10,397Z ERROR pdflatex - 
Sorry, but: The executed process did not succeed.

2022-02-15 16:28:10,397Z FATAL pdflatex.core - The memory dump file could not be found.
2022-02-15 16:28:10,397Z FATAL pdflatex.core - Data: fileName="pdflatex.fmt"
2022-02-15 16:28:10,397Z FATAL pdflatex.core - Source: Libraries/MiKTeX/TeXAndFriends/texmfapp.cpp:717
2022-02-15 16:28:10,397Z FATAL pdflatex - The memory dump file could not be found.
2022-02-15 16:28:10,397Z FATAL pdflatex - Info: fileName="pdflatex.fmt"
2022-02-15 16:28:10,397Z FATAL pdflatex - Source: Libraries/MiKTeX/TeXAndFriends/texmfapp.cpp
2022-02-15 16:28:10,397Z FATAL pdflatex - Line: 717
2022-02-15 16:28:10,398Z INFO  pdflatex - this process (417116) finishes with exit code 1
```

Any advice for additional debugging steps?

I have given all possible permissions to `~/.miktex/` by running `chmod -R ugo=rwx ~/.miktex/` but this makes no difference (I get the same error).

Could it be because the memory dump file does not exist or could not be created? Or is this not relevant?

Strangely `xelatex` works just fine. It is only `pdflatex` that has the problem.

Attached is the MiKTeX installation report:
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/8072804/miktex-report.txt)

**Comment by andrewdbate** [comment]
When I was getting the above errors I was attempting to use MiKTeX with a system-wide installation.

**Here is a workaround for anyone facing the same issue:** choose user mode instead of system-wide configuration on the inital run of the MiKTeX console.

I removed the `miktex` package with `apt remove miktex` and then `apt autoremove`. I then removed the `~/.miktex` directory. I  also searched through the filesystem for all files with names containing `miktex` to make sure I left nothing behind. I then reinstalled with `apt install miktex`. On the first run of the MiKTeX console, I chose to install for the current user only. This setup works without problems and I am able to compile with both `pdftex` and `xelatex`.

I also separately attempted to reinstall and then choose a system-wide setup of MiKTeX on the first run of the MiKTeX console, and I got the same errors as reported above, so it seems that the above error can be reproduced when using a system-wide configuration.

**Comment by edocevoli** [comment]
Thank you. The first log snippet mentions the `miktex` utility:

```
2022-02-15 16:28:10,397Z ERROR pdflatex - /usr/bin/miktex did not succeed; exitCode: 1
```

So the next step, if this happens again, would be to inspect `miktex.log`.

**Comment by andrewdbate** [comment]
Thanks for your reply. Would it be possible to update https://miktex.org/howto/bug-report to include the directories on Linux where the `miktex.log` can be found?

I did try to follow the instructions, but section "1.4. MiKTeX history" is only described for Windows, so I assumed it was Windows-specific.

If I can, I will try to reproduce this and include the `miktek.log`. Thanks!

**Comment by manueldeprada** [comment]
Leaving this for the record. For me, the solution was

1. Add $HOME/bin to the PATH in bashrc. Restart.
2. from terminal, execute: `cd ~/.miktex/texmfs/install/miktex/config && miktex-makefmt --engine=pdftex --dest-name=pdflatex --no-dump pdflatex.ini`

**Comment by Janosch143** [comment]
> Leaving this for the record. For me, the solution was
> 
>     1. Add $HOME/bin to the PATH in bashrc. Restart.
> 
>     2. from terminal, execute: `cd ~/.miktex/texmfs/install/miktex/config && miktex-makefmt --engine=pdftex --dest-name=pdflatex --no-dump pdflatex.ini`

Thanks for this, it also solved this issue for me!

**Comment by markus-seidl** [comment]
For me the solution was to us Miktex-Console and Upgrade to the standard version.

**Comment by volodya-lombrozo** [comment]
I had the same issue, and the following steps helped me:
* Open MiKTeX Console.
* Click on the "Overview" tab.
* At the bottom, locate the "Upgrade" box.
* Click "Upgrade now."

This will upgrade the minimal TeX installation to a standard TeX installation
