### ISSUE TITLE
[feature request] add kpathsea.h header file

### ISSUE THREAD

**Issue by vtorri** [MiKTeX/miktex#1058]
Hello

would the devs consider adding kpathsea header files to the distribution for developpers who want to use kpathsea with MIKTeX (TexLive provides them) ?

thank you

**Comment by edocevoli** [comment]
MiKTeX provides `kpathsea.h`. After running CMake, you can find it here (relative to the build directory):

```
.\Libraries\MiKTeX\KPathSeaEmulation\include\kpathsea\kpathsea.h
```

**Comment by vtorri** [comment]
the Windows installer does not install it

**Comment by vtorri** [comment]
also, the Windows installer does not install the import lib for the kpathsea DLL
