### ISSUE TITLE
Poor resolution of generated files

### ISSUE THREAD

**Issue by DavidCBee** [MiKTeX/miktex#1064]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
The resolution of MiKTeX's DVI file/generated PDF/postscript is nowhere near as good as that in PCTex. Is there a solution to this somewhere? What I generate isn't as 'sharp' as I would really like it to be.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
