### ISSUE TITLE
Error: "The remote package repository is outdated. You have to choose another repository."

### ISSUE THREAD

**Issue by jnyhuis** [MiKTeX/miktex#1067]
When trying to update MiKTeX, I receive the error: "The remote package repository is outdated. You have to choose another repository."

I have tried updating from different repositories (all of the ones in the US and one in Canada), and all produce the same error message.

Based off of bug #27 (duplicate error), I manually deleted the registry keys and selected a fresh repo, resulting in the same error.

My guess is that the ctan upload failed last night and that is why a bad auth token is associated with today's repo.

Hopefully tomorrow's ctan upload will succeed?  Perhaps someone with insider knowledge of ctan will check it tomorrow?

Thanks in advance,
John N.
UW-Biostatistics: jnyhuis@uw.edu

**Comment by aggserp4** [comment]
Having the same issue here. I've tried a number of different repos and none of them work.

**Comment by LogCreative** [comment]
I've tried to use the option `<Random package repository on the Internet>`, it works from time to time. But it is not stable.

**Comment by edocevoli** [comment]
This is a temporary issue. Please try again tomorrow.

**Comment by jnyhuis** [comment]
Looks like it cleared up with last night's sync.  
Thanks!
-John N.
