### ISSUE TITLE
where to get MiKTeX distribution files

### ISSUE THREAD

**Issue by yashpalgoyal1304** [MiKTeX/miktex#1075]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

1. I have downloaded the "Net installer 64 bit" [setup-4.2-x64.exe] 
2. and it shows the option not only for "Download" but also to "Install (from local)" 
3. I tried "download", it got error "Transferred a partial file" and terminated. 
now i am left with 2 `.cab` (cabinet) files, and 42 `.LZMA` files downloaded. what to do with those?
4. And other than that, i cant figure out where to get the files for the latter option of install from local

```
An error occurred:
  source file: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp
  source line: 247
  message: Transferred a partial file
  info: code="18", url="https://mirror.yongbok.net/ctan/systems/win32/miktex/tm/packages/biber-windows-x64.tar.lzma"
```

![image](https://user-images.githubusercontent.com/19423063/158958706-65717c37-d64c-442d-bfe8-5438c336bafd.png)
![image](https://user-images.githubusercontent.com/19423063/158960087-4db510aa-0612-4600-a592-7fa8568f8bdb.png)

[setup-4.2-x64.exe]: https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/setup-4.2-x64.exe

**Comment by edocevoli** [comment]
This should be a temporary issue. Please try again.
