### ISSUE TITLE
Installation Stalls out at same point each time

### ISSUE THREAD

**Issue by JL-Doge** [MiKTeX/miktex#1076]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
![image](https://user-images.githubusercontent.com/79808868/159196296-e1168760-eb0f-4f6a-9694-a73ae6a5c0c9.png)

The installation stops working at this point every time.  I've attempted it 9x and it consistently stalls out at the same place.  I have tried manually changing the program files or changing to "read attribute only" based on forum advice but nothing is working.  Has anyone else encountered this?

I'm on Windows 10.  Thanks

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
