### ISSUE TITLE
Installation stalls out at same point

### ISSUE THREAD

**Issue by JL-Doge** [MiKTeX/miktex#1077]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
[Miktex logs.zip](https://github.com/MiKTeX/miktex/files/8319323/Miktex.logs.zip)
![miketex installation](https://user-images.githubusercontent.com/79808868/159366478-87897bcb-ae67-4041-b555-f15c1dfc00d1.png)

**Comment by edocevoli** [comment]
Click Next to continue.
