### ISSUE TITLE
spell check is gone

### ISSUE THREAD

**Issue by PlamenToby** [MiKTeX/miktex#1079]
- [X ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

After the latest update, there is no spell checker. Spelling -> shows a black dot.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
