### ISSUE TITLE
languages.ini entries are missing the patterns field

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#108]
The entries of german-x-2018-03-31 and ngerman-x-2018-03-31 are missing the pattern field:

~~~~~
[german-x-2018-03-31]
loader=dehypht-x-2018-03-31.tex
lefthyphenmin=2
righthyphenmin=2
synonyms=german-x-latest

[ngerman-x-2018-03-31]
loader=dehyphn-x-2018-03-31.tex
lefthyphenmin=2
righthyphenmin=2
synonyms=ngerman-x-latest
~~~~~

This means that in the generate language.dat.lua there are empty entries there (here only for ngerman-x-2018-03-31):

~~~~~
	['ngerman-x-2018-03-31'] = {
		loader='dehyphn-x-2018-03-31.tex',
		lefthyphenmin=2,
		righthyphenmin=2,
		synonyms={ 'ngerman-x-latest' },
		patterns='',
		hyphenation='',
	},
~~~~~

babel seems not to care, but polyglossia with lualatex don't like this: there is then not hyphenation at all if one use the language as can be tested with this document:

~~~~
\documentclass{article}
 \usepackage{polyglossia}
 \setdefaultlanguage[spelling=new,babelshorthands=true, latesthyphen=true]{german}

 \textwidth=1mm
 \begin{document}
 Apfelstern Apfelstern
 \end{document}
~~~~

In texlive 2018 the entries of language.dat.lua looks like this and polyglossia works fine:

~~~~
	['german-x-2018-03-31'] = {
		loader = 'dehypht-x-2018-03-31.tex',
		lefthyphenmin = 2,
		righthyphenmin = 2,
		synonyms = { 'german-x-latest' },
		patterns = 'hyph-de-1901.pat.txt',
		hyphenation = 'hyph-de-1901.hyp.txt',
	},
	['ngerman-x-2018-03-31'] = {
		loader = 'dehyphn-x-2018-03-31.tex',
		lefthyphenmin = 2,
		righthyphenmin = 2,
		synonyms = { 'ngerman-x-latest' },
		patterns = 'hyph-de-1996.pat.txt',
		hyphenation = 'hyph-de-1996.hyp.txt',
	},
~~~~~

I would suggest to add 

~~~~~
patterns=hyph-de-1996.pat.txt
hyphenation=hyph-de-1996.hyp.txt
~~~~~

to  [ngerman-x-2018-03-31] and the similar 

~~~~~
patterns=hyph-de-1901.pat.txt
hyphenation=hyph-de-1901.hyp.txt
~~~~~

to the [german-x-2018-03-31] entry in languages.ini

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.

**Comment by koppor** [comment]
I get following error output:

    hyphsubst.sty:227: Package hyphsubst Error: Unknown pattern `ngerman-x-latest'.

When using

```latex
\RequirePackage[ngerman=ngerman-x-latest]{hyphsubst}
```

I saw dehyph-exptl being updated two days ago: https://www.ctan.org/ctan-ann/id/mailman.4914.1614463637.2532.ctan-ann@ctan.org. Is this related or is this another mysterious issue?
