### ISSUE TITLE
Feature Request: please keep provide mpm --list / mpm --print-package-info

### ISSUE THREAD

**Issue by sunderme** [MiKTeX/miktex#1080]
texstudio uses the above two functions to determine what packages are installed and what style-files they provide. This is used to mark used packages not present in the system in the editor.
Both functions are declared as deprecated, so it would be much appreciated if they are either kept alive or an alternative way to determine the installed package base is provided.

**Comment by note286** [comment]
You should read [MiKTeX Manual](http://mirrors.ctan.org/systems/win32/miktex/doc/miktex.pdf). There are some description about install or update packagtes in page 49 and 50.

```
miktex packages info <package-id>
miktex packages install <package-id>
miktex packages update <package-id>
```

**Comment by Paebbels** [comment]
> You should read [MiKTeX Manual](http://mirrors.ctan.org/systems/win32/miktex/doc/miktex.pdf). There are some description about install or update packagtes in page 49 and 50.
> 
> ```
> miktex packages info <package-id>
> miktex packages install <package-id>
> miktex packages update <package-id>
> ```

@note286 your answer doesn't answer the question neither does the manual has an answer to the question. There seems to be no replacement to list installed packages.

**Comment by note286** [comment]
@Paebbels @sunderme I'm not a heavy user of MiKTeX. I think `mpm --print-package-info-info` can be replaced by `miktex packages info`. For `mpm --list`, I also didn't find the corresponding command in the manual, but since MiKTeX will automatically download the package, it doesn't seem to affect the use of TeXstudio?

If further answers are needed, it is suggested that the questioner reopen issue and wait for the author's reply, or consider asking questions at tex.se, which is more active.

**Comment by sunderme** [comment]
texstudio needs to know which are the available packages to offer better completion choices.
I read an internal miktex database for that as the commands are too slow.

**Comment by KillTheMule** [comment]
This change has silently broken the usage of miktex for quite some users of mine. Seems like no harm was really done, but I'd have appreciated an entry in the changelog.

That being said, I need to work around this, but I have a hard time finding out when exactly this was removed. Was it [these 3 commits](https://github.com/MiKTeX/miktex/search?q=refurbish+mpm&type=commits)? Which would mean the change was introduced in 22.3? Thanks for any help, and of course thanks for miktex :)
