### ISSUE TITLE
running with elevated privileges

### ISSUE THREAD

**Issue by fedemath** [MiKTeX/miktex#1081]
I have aa new laptop with Windows 11 Pro, and just installed MikTeX 22.3-x64 and WinEdt103-64. But every attempt to latex a basic tex fails. I attach the resulting log file.

I have first tried to install MikTeX as admin and WinEdt as private (which were both recommended). But then I tried all combinations:

MikTeX admin - WinEdt admin
MikTeX admin - WinEdt private
MikTeX private - WinEdt admin
MikTeX private - WinEdt private

Always get the same problem. Any suggestions?

[latex.log](https://github.com/MiKTeX/miktex/files/8395933/latex.log)

**Comment by edocevoli** [comment]
Sorry, I was not able to reproduce this. If the problem persists: run MiKTeX as a normal user (no elevated privileges).
