### ISSUE TITLE
Last Update with Miktex Console under Linux Mint 18.3 producing errors

### ISSUE THREAD

**Issue by wolf01ms** [MiKTeX/miktex#109]
The update with Miktex Console shows miktex-config-2.9 to be deleted because its obsolete. After deleting via update running pdflatex produces errors: some files (pdftex.ini and log4cxx.unx.xml) are missing and miktex trys to install them on-the-fly via miktex-config-2.9.

**Comment by RoyiAvital** [comment]
Is there an option to install MiKTeX in portable manner in Linux like in Windows?
Namely extract a `.tar` file into any folder.  
Then launch MiKTeX upon request by some executable which will allow programs to be aware of MiKTeX installation (For example, TeXStudio).

Another option would be a FlatPak of MiKTeX (Which works with the TeXStudio FlatPak).

**Comment by OctarineSorcerer** [comment]
Any update on this so far? MiKTeX is currently unusable for me on Mint due to this, as compilation doesn't complete. Even a fresh install produces this problem.

Clicking "Copy Info" on the "MiKTeX has encountered an internal error" dialog produces the following:

```
MiKTeX Problem Report
Message: MiKTeX encountered an internal error.
Data: 
Source: Libraries/MiKTeX/PackageManager/PackageManagerImpl.cpp
Line: 676
MiKTeX: 2.9
OS: Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64
Invokers: .../cinnamon-launch/cinnamon/texstudio
SystemAdmin: no
Root0: /home/dan/.miktex/texmfs/config
Root1: /home/dan/.miktex/texmfs/data
Root2: /home/dan/.miktex/texmfs/install
Root3: /home/dan/texmfs/config
Root4: /home/dan/texmfs/data
Root5: /home/dan/texmfs/install
UserInstall: /home/dan/.miktex/texmfs/install
UserConfig: /home/dan/.miktex/texmfs/config
UserData: /home/dan/.miktex/texmfs/data
CommonInstall: /home/dan/texmfs/install
CommonConfig: /home/dan/texmfs/config
CommonData: /home/dan/texmfs/data
```

I'm happy to do some further digging/testing if requested.

**Comment by edocevoli** [comment]
I think the the bug was fixed in the course of development so I would recommend that you reset
the MiKTeX installation to factory defaults.

1. start MiKTeX console
2. Click `Cleanup` to navigate to the cleanup page.
3. Click `Reset the TeX installation to factory defaults`
