### ISSUE TITLE
PDF image file is misplaced in xduts.

### ISSUE THREAD

**Issue by note286** [MiKTeX/miktex#1093]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I am the author of [CTAN: Package xduts](https://www.ctan.org/pkg/xduts). I'm glad xduts have contained in MiKTeX yesterday, but `xidian-text.pdf` and `xidian-logo.pdf` are not placed in the same directory as `xduugthesis.cls` in MiKTeX. It is mentioned in README of [note286/xduts: Xidian University TeX Suite](https://github.com/note286/xduts).

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
