### ISSUE TITLE
luafontfind broken after update.

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#1097]
I just updated the luafontfind file. It now produces this error when I run it:

C:\Users\gerar>luafindfont Georgia
We are using Lua 5.3
Looking for font "georgia"
...ocal\Programs\MiKTeX\scripts/luafindfont\luafindfont.lua:204: attempt to call a nil value (local 'str2')

System:
Edition	Windows 10 Pro 64 bit
Version	21H2
Installed on	‎12/‎8/‎2021
OS build	19044.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by edocevoli** [comment]
I think this is not a MiKTeX-specific bug.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).
