### ISSUE TITLE
Installing on Surface Pro i7 2017 causes random sleep problems

### ISSUE THREAD

**Issue by khalidmath** [MiKTeX/miktex#11]
After installing MikTex on the newest Surface Pro i7 2017 for all users, the system sleeps and shuts down randomly. I had to install just for the user after resetting the device for the device to work normally.

**Comment by edocevoli** [comment]
Thank you. You can change energy/power save settings in control panel. If the system shuts down, you should be able to turn it on again by pressing the upper right button.

**Comment by khalidmath** [comment]
You're welcome. Changing energy/power save settings in control panel doesn't fix this issue. And I've isolated the issue to installing MikTex for all users. Otherwise, the random sleep problem does not happen.

**Comment by khalidmath** [comment]
I don't understand why this issue is closed. Your proposed solution does not work.

**Comment by edocevoli** [comment]
I have closed the ticket because this is not a MiKTeX specific bug report.

**Comment by khalidmath** [comment]
This is specific to MikTex. It is causing problems on a system it supposedly supports...

If this isn't a miktex issue, what is it? Everything else I have runs fine on the Surface Pro.

Thank you for your time.

**Comment by khalidmath** [comment]
This is specific to MikTex. It is causing problems on a system it supposedly supports...

If this isn't a miktex issue, what is it? Everything else I have runs fine on the Surface Pro.

Thank you for your time.

**Comment by edocevoli** [comment]
If you really think that the issues are caused by MiKTeX: please proof it by attaching screenshots, log files, videos, what ever. Just saying that you have a problem is not a proper bug report.

I am glad to fix any bugs I can reproduce. But I cannot eliminate "Ghost" bugs.
