### ISSUE TITLE
MiKTex finish setup via comand line Mac

### ISSUE THREAD

**Issue by tcinbis** [MiKTeX/miktex#110]
Hey everybody,
we are trying to deploy the `MikTeX Console` Application for users. The problem we currently face is, that I couldn't find a way to start the _Finish setup_ via a post install script. 

Do any application start options via command line exists to execute the _Finish setup_ part?

**Comment by edocevoli** [comment]
On Linux, you can run

    miktexsetup finish

**Comment by tcinbis** [comment]
@edocevoli thank you very much!
