### ISSUE TITLE
MikTex and asymptote 2.79 => 2.80

### ISSUE THREAD

**Issue by jmj999** [MiKTeX/miktex#1101]
Hi,

The latest version of MikTex forces Asymptote version 2.79 which produces some bugs, especially with the plain_Label module.

Error with : pic.addBox(position,position,min(f),max(f));

Asymptote version 2.79 should be replaced by the latest verion of Asymptote : 2.80

Best regards
JMJ

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
