### ISSUE TITLE
error

### ISSUE THREAD

**Issue by layalachu** [MiKTeX/miktex#1103]
I face problem while checking updates on miktex console. please share a solution?
error report -GENERAL MIKTEX INFORMATION
ReportDate: 2022-05-09 23:21:41
CurrentVersion: 22.3
SetupDate: 2022-05-09 02:36:00
SetupVersion: 22.3
Configuration: Regular
GitInfo: https://github.com/MiKTeX/miktex/commit/c820fab6e67fc3ccef53ce5ee0571dc5a28d5d49 / 2022-03-13 20:15:59
OS: Windows 10 Enterprise, 64-bit, build 10240
SharedSetup: yes
LinkTargetDirectory: C:\Users\acer\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: not yet
LastUpdateAdmin: not yet
LastUpdateDbAdmin: not yet
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX
Root1: C:\Program Files\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
Invokers:

The following issues were detected:
1: major issue: So far, no MiKTeX administrator has checked for updates.

ERROR DETAILS
Program: miktex-console_admin
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:247
Error: Failure when receiving data from the peer
Details:
code: 56
url: https://api2.miktex.org/hello

**Comment by edocevoli** [comment]
Thank you. I was not able to reproduce the problem with the given information. Since there are no log files, it is not possible to work on this effectively.

Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
