### ISSUE TITLE
miktex-maketfm fail on  Windows

### ISSUE THREAD

**Issue by Bummibaer** [MiKTeX/miktex#1105]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I have installed on a Windows Domain Client the  22.3 miktex version.
I cannot compile any document.
The problem is 

> miktex-maketfm --verbose --debug cmr10
> downloading https://mirror.physik.tu-berlin.de/pub/CTAN/systems/win32/miktex/tm/packages/cm.tar.lzma...
> 0.11 MB, 8.21 Mbit/s
> Leider konnte das Paket cm nicht installiert werden.

With curl I can download the package, but after execution of the command, I don't find the package on my computer.

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/8685349/miktex-report.txt)
[user_log.zip](https://github.com/MiKTeX/miktex/files/8685371/user_log.zip)
[admin_log.zip](https://github.com/MiKTeX/miktex/files/8685378/admin_log.zip)

**Comment by edocevoli** [comment]
It seems that your MiKTeX setup is broken in some way. I would suggest that you refresh the file name database and the package database. You can use MiKTeX Console for these tasks.

**Comment by Bummibaer** [comment]
What's exactly is the file name database?
The package database is updated by mpm --update, right?

I've done so far:
> miktexsetup_standalone.exe download --quiet --local-package-repository=C:\ProgramData\MiKTeX\Repository --package-set=essential
> miktexsetup_standalone.exe install--quiet --local-package-repository=C:\ProgramData\MiKTeX\Repository --package-set=essential
> mpm.exe  --admin --quiet --upgrade --package-level=essential
> mpm.exe --admin --update --quiet

For test I did the following:
> mpm.exe --admin --verbose --upgrade --package-level=complete

I've downloaded the sourcecode. Where do I find the Module for miktex-maketfm? Can I increase the level of debug?

thanks
