### ISSUE TITLE
Support for Debian 11/Ubuntu 22.04

### ISSUE THREAD

**Issue by vitorsr** [MiKTeX/miktex#1111]
Hi Christian,

Is support for Debian 11 (current stable release) and Ubuntu 22.04 (latest LTS) planned?

Thanks for developing MiKTeX.

**Comment by qiancy98** [comment]
Hello.
I will be grateful if you can create the `jammy/` dictionary in `CTAN/systems/win32/miktex/setup/deb/dists/`.
I mean, I will be grateful if I can install MiKTeX in Ubuntu 22.04 from CTAN.

**Comment by edocevoli** [comment]
Packages for Debian 11 and Ubuntu 22.04 are now available.

**Comment by curran** [comment]
Hooray! Thank you so much.

**Comment by ggruening** [comment]
Maybe there is a signature problem? On Ubuntu 22.04, I got:

`
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://mirror.funkfreundelandshut.de/latex/systems
/win32/miktex/setup/deb jammy InRelease: The following signatures were invalid: EXPKEYSIG 277A7293F59E4889 MiKTeX Packager <packager@miktex.org>
W: Failed to fetch http://miktex.org/download/ubuntu/dists/jammy/InRelease  The following signatures were invalid: EXPKEYSIG 277A7293F59E4889 MiKTeX Packager <packager@miktex.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
`

My sources.list:
`deb [arch=amd64 signed-by=/usr/share/keyrings/miktex.gpg] http://miktex.org/download/ubuntu jammy universe`

The file miktex.gpg is created using this "modern way" (see https://www.digitalocean.com/community/tutorials/how-to-handle-apt-key-and-add-apt-repository-deprecation-using-gpg-to-add-external-repositories-on-ubuntu-22-04):

`
sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/miktex.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
`
Do I miss anything?

Thanks for the fantastic work! 

All the best
Gregor

**Comment by ggruening** [comment]
> The key has been expired a few days ago. I renewed it a couple of hours ago.

Perfect. It's working again.

**Comment by rafisics** [comment]
I am having this error while installing miktex on ubuntu 22.04:
```
W: http://miktex.org/download/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
N: Skipping acquire of configured file 'universe/binary-i386/Packages' as repository 'http://miktex.org/download/ubuntu jammy InRelease' doesn't support architecture 'i386'
```

**Comment by ggruening** [comment]
> I am having this error while installing miktex on ubuntu 22.04:
> 
> ```
> W: http://miktex.org/download/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
> N: Skipping acquire of configured file 'universe/binary-i386/Packages' as repository 'http://miktex.org/download/ubuntu jammy InRelease' doesn't support architecture 'i386'
> ```

You can try to store the key the "modern way" and naming the architecture explicitly. See [above](https://github.com/MiKTeX/miktex/issues/1111#issuecomment-1532829279).

**Comment by rafisics** [comment]
> You can try to store the key the "modern way" and naming the architecture explicitly. See [above](https://github.com/MiKTeX/miktex/issues/1111#issuecomment-1532829279).

This way?
```
sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/miktex.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/miktex.gpg] http://miktex.org/download/ubuntu focal universe" | sudo tee /etc/apt/sources.list.d/miktex.list
```

**Comment by SolNunes** [comment]
@
> 
> The file miktex.gpg is created using this "modern way" (see https://www.digitalocean.com/community/tutorials/how-to-handle-apt-key-and-add-apt-repository-deprecation-using-gpg-to-add-external-repositories-on-ubuntu-22-04):
> 
> `sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/miktex.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889` Do I miss anything?
> 


@ggruening  did this work for you?

**Comment by ggruening** [comment]
@SolNunes Yes, it worked.
