### ISSUE TITLE
[BUG]: wrong version number for miktex-dvisvgm-bin-x64-2.9

### ISSUE THREAD

**Issue by VincentTam** [MiKTeX/miktex#1112]
GUI says that I'm using package miktex-dvisvgm version: 2.13.3, but cmd outputs 2.11.1.

I've asked the dvisvgm's maintainer/owner at https://github.com/mgieseki/dvisvgm/issues/184, who referred me here.

![dvisvgm version number](https://user-images.githubusercontent.com/5748535/172232546-727a6aea-1fa4-4122-afaf-983fa2470396.png)

```
C:\Users\xxxx>dvisvgm -V1
dvisvgm 2.11.1
--------------
brotli:      1.0.9
clipper:     6.2.1
fontforge:   20160721
freetype:    2.10.3
Ghostscript: 9.25
kpathsea:    MiKTeX 22.3
potrace:     2.11.1
xxhash:      0.8.1
zlib:        1.2.11

C:\Users\xxxx>which dvisvgm
/c/Users/xxxx/AppData/Local/Programs/MiKTeX/miktex/bin/x64/dvisvgm

C:\Users\xxxx>
```

Attachments:
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/8848386/miktex-report.txt)
[initexmf.log](https://github.com/MiKTeX/miktex/files/8848412/initexmf.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/8848413/miktex-console.log)
[dvisvgm.log](https://github.com/MiKTeX/miktex/files/8848414/dvisvgm.log)
[latexmk.log](https://github.com/MiKTeX/miktex/files/8848415/latexmk.log)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/8848416/pdflatex.log)

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by muzimuzhi** [comment]
It seems miktex-dvisvgm is considered as a separate software based on dvisvgm and having its own version number. https://github.com/MiKTeX/miktex/commit/2b65100d0ce1bae59f809b5165ebe5b59eb55e63

**Comment by VincentTam** [comment]
> Changeset [2b65100](https://github.com/MiKTeX/miktex/commit/2b65100d0ce1bae59f809b5165ebe5b59eb55e63) updates MiKTeX's dvisvgm package to dvisvgm 2.13.3. However, dvisvgm's source file `version.h`, which defines variable `PROGRAM_VERSION`, doesn't seem to be considered here so that `dvisvgm --version` prints an old version number of a previous release.

@mgieseki so i'm actually using the latest version of dvisvgm?  i'm having https://github.com/mgieseki/dvisvgm/issues/158 with this MWE.  (The line `\addplot` is generated by my VS code LaTeX plugin, and I appended `\closedcycle` at the end for pattern filling.)

```tex
\documentclass[border=2pt]{standalone}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usetikzlibrary{patterns}
\begin{document}
\begin{tikzpicture}
    \begin{axis}
        \addplot [
            domain=-10:10,
            samples=70,
            color=blue,
            pattern=north east lines,
            ]
            {x^2 + 2*x + 1} \closedcycle;
        \addlegendentry{$x^2 + 2x + 1$}
        
    \end{axis}
\end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/5748535/174353197-603cd1f1-8fe5-4f96-a099-b89a03e39d67.png)

When I used

    dvisvgm -P -o foobar.svg 220617-fill

to change it to SVG from PDF, the curve is gone.  I attached the generated `foobar.svg` below FYI.

![foobar](https://user-images.githubusercontent.com/5748535/174353423-bf7d5753-8df1-42f7-bf89-879e23c975a4.svg)

**Comment by mgieseki** [comment]
I can't really tell what version and code base was used to build your dvisvgm binary. Issue https://github.com/mgieseki/dvisvgm/issues/158, however, occurred when converting DVI files to SVG. You seem to process a PDF file which is only partly supported by dvisvgm. If you create and convert a DVI file from your example, the resulting SVG should be fine. That's not related to MiKTeX, though. ;-)

**Comment by VincentTam** [comment]
Thanks for reply.  I got the fill pattern using your method, but lost the fonts.  I've created another issue for that in your repo.
