### ISSUE TITLE
miktex-makefmt: command not found

### ISSUE THREAD

**Issue by clemekay** [MiKTeX/miktex#1116]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
I'm using MiKTeX Console 4.6 on macOS Monterey 12.3.1. Not sure if it's relevant, but I am using a proxy to update. 

I believe the issue (maybe just one of a few issues?) is that, even after a few different un-installs and re-installs, the miktex-makefmt command isn't included in the installation. This issue occurs with any tex file I have, including the simplest possible example. When I attempt to run `pdflatex` I always get the following error:
```
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (MiKTeX 22.1) (preloaded format=pdflatex.fmt)
 restricted \write18 enabled.

Sorry, but pdflatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  /Users/kbcleme/Library/Application Support/MiKTeX/texmfs/data/miktex/log/pdflatex.log
```

The full `pdflatex.log` is included, but the first error is:
```2022-06-22 13:53:08,375-0600 INFO  pdflatex - this process (13901) started by bash in directory /Users/kbcleme/olsonanswinter2022 with command line: pdflatex OlsonANSWinter2022.tex
2022-06-22 13:53:08,375-0600 INFO  pdflatex - this is MiKTeX-PDFTEX 4.10.0 (1.40.24) (MiKTeX 22.1)
2022-06-22 13:53:08,375-0600 INFO  pdflatex - allowing known shell commands
2022-06-22 13:53:08,379-0600 INFO  pdflatex - going to create file: pdflatex.fmt
2022-06-22 13:53:08,393-0600 INFO  pdflatex.core - forking...
2022-06-22 13:53:08,744-0600 ERROR pdflatex - /Users/kbcleme/bin/miktex did not succeed; exitCode: 1
2022-06-22 13:53:08,744-0600 ERROR pdflatex - output:
2022-06-22 13:53:08,744-0600 ERROR pdflatex -
Sorry, but: The executed process did not succeed.
```

The full `miktex.log` is included. There are a few warnings, but the first error is
```
2022-06-22 13:53:08,740-0600 ERROR miktex - sub-process error output has been saved to '/Users/kbcleme/Library/Application Support/MiKTeX/texmfs/data/miktex/log/miktex-makefmt_2022-06-22-135308.out'
```

`miktex-makefmt_2022-06-22-135308.out` indicates that miktex-makefmt did not succeed:
```
Sorry, but miktex-makefmt did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  /Users/kbcleme/Library/Application Support/MiKTeX/texmfs/data/miktex/log/miktex-makefmt.log
```

The full `miktex-makefmt.log` is included. The first line is 
```2022-06-22 13:53:08,720-0600 INFO  miktex-makefmt - this process (13908) started by miktex in directory /Users/kbcleme/olsonanswinter2022 with command line: miktex-makefmt --engine=pdftex --dest-name=pdflatex --no-dump pdflatex.ini --disable-installer --miktex-disable-maintenance --miktex-disable-diagnose```

Since the process starts with a command, I tried that command on the command line, returning 
```-bash: miktex-makefmt: command not found```

After checking `$HOME/bin`, I confirmed that `miktex-makefmt` is not there, so I'm not sure where to go from here and appreciate any help!
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/8968364/miktex-report.txt)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/8968434/pdflatex.log)
[miktex.log](https://github.com/MiKTeX/miktex/files/8968439/miktex.log)
[miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/8968432/miktex-makefmt.log)

**Comment by edocevoli** [comment]
`miktex-makefmt` is an internal (hidden) utility. You cannot invoke it directly.

The actual error seems to be:

```
2022-06-22 13:53:08,720-0600 INFO  miktex-makefmt - this process (13908) started by miktex in directory /Users/kbcleme/olsonanswinter2022 with command line: miktex-makefmt --engine=pdftex --dest-name=pdflatex --no-dump pdflatex.ini --disable-installer --miktex-disable-maintenance --miktex-disable-diagnose
2022-06-22 13:53:08,720-0600 FATAL miktex-makefmt - The required TeX input file pdflatex.ini could not be found.
2022-06-22 13:53:08,721-0600 FATAL miktex-makefmt - The required TeX input file pdflatex.ini could not be found.
```

Try refreshing the file name database, then run `kpsewhich pdflatex.ini` in order to verify that `pdflatex.ini` exists.

**Comment by clemekay** [comment]
`kpsewhich pdflatex.ini` returned 
``` 
======================================================================
starting package maintenance...
installation directory: "/Users/kbcleme/Library/Application Support/MiKTeX/texmfs/install"
package repository: https://ctan.math.utah.edu/ctan/tex-archive/systems/win32/miktex/tm/packages/
package repository digest: b5774742ea2888e1892f2db7b171668e
going to download 1262 bytes
going to install 4 file(s) (1 package(s))
downloading https://ctan.math.utah.edu/ctan/tex-archive/systems/win32/miktex/tm/packages/miktex-latex.tar.lzma...
0.00 MB, 0.59 Mbit/s
extracting files from miktex-latex.tar.lzma...
======================================================================
/Users/kbcleme/Library/Application Support/MiKTeX/texmfs/install/tex/latex/00miktex/pdflatex.ini ```

So it didn't exist. `kpsewhich pdflatex.ini` now returns
```/Users/kbcleme/Library/Application Support/MiKTeX/texmfs/install/tex/latex/00miktex/pdflatex.ini ```

After refreshing the file name database again, pdflatex does not succeed. `miktex-makefmt.log` is included, but pdflatex.ini still cannot be found. 
[miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/8968962/miktex-makefmt.log)

**Comment by edocevoli** [comment]
`pdflatex.ini` can be found. Now it is `pdftex.cfg` which is missing. I wonder what happened to your MiKTeX setup. Seems that some essential files are missing...

**Comment by clemekay** [comment]
I was wondering the same thing, because I'm downloading and installing directly from the miktex website, and didn't have these issues when building it on a previous MacBook. Not sure if this would be relevant, but I am on a newer 2021 MacBook, so maybe the structure of things would've changed?

**Comment by clemekay** [comment]
I ran `kpsewhich pdftex.cfg` which did install it as well. `pdflatex filename.tex` just seems to infinitely hang now

**Comment by BizarrePenguin** [comment]
@clemekay Did you manage to solve the problem? I have the same issue and ran the commands suggested. Now I am stuck at pdflatex infinitely hanging too.

**Comment by clemekay** [comment]
I did not! I could not find anything explicitly wrong and did not know where to go next.

**Comment by BizarrePenguin** [comment]
I finally solved it for me by upgrading to a standard tex installation in Miktex instead of trying to use the “Just enough TeX” approach. Maybe there is something wrong with the system that would try to install every package on demand on macos?

Note, that I reinstalled MikTex after the infinitely hanging problem, had the issue from the beginning again (pdflatex.ini not found) and then, instead of running the commands suggested here, I upgraded the packages to a standard tex distribution in miktex console.

**Comment by usernameandme** [comment]
Thanks @BizarrePenguin After facing hang issue, I too upgraded to standard tex installation via console. After that when I try to run `pdflatex` it automatically downloaded a few missing packages which didn't happen earlier with minimal installation and pdf generation is successful.

**Comment by fabwu** [comment]
I had a similar issue with a missing `pdflatex.ini`. I solved it after a **reboot** and building the `pdflatex` format again (Settings -> Formats -> select pdflatex -> build format).
