### ISSUE TITLE
MikTeX build tangle.p fails

### ISSUE THREAD

**Issue by paolo-oliveri** [MiKTeX/miktex#1119]
Hello,
I am trying to compile MikTeX from source in different linux systems, most of them are Debian based.
I am encountering this issue during compilation:

    [...]
    [ 22%] Generating tangle.p, tangle.pool

    terminate called after throwing an instance of 'boost::locale::conv::invalid_charset_error'
      what():  Invalid or unsupported charset:utf-8.utf-8
    Aborted (core dumped)
    make[2]: *** [Programs/TeXAndFriends/Knuth/web/CMakeFiles/miktex-tangle.dir/build.make:87: Programs/TeXAndFriends/Knuth/web/tangle.p] Errore 134
    make[1]: *** [CMakeFiles/Makefile2:14459: Programs/TeXAndFriends/Knuth/web/CMakeFiles/miktex-tangle.dir/all] Error 2
    make: *** [Makefile:166: all] Error 2

I think that the issue is related to the machine localization, but I am not 100% sure.
Can you confirm me this and if you know if there is a workaround to continue the compilation process?
Thank you for developing MikTeX!!
Sincerely,
Paolo Oliveri
Edit: the problem is still there in a en_US localized Rocky Linux 8 machine. May the problem be related to the boost-locale library version?

**Comment by MoreOwO** [comment]
I'm having the same issue with the 23.5 on Arch linux
