### ISSUE TITLE
Faulty prepmx binary

### ISSUE THREAD

**Issue by schtandard** [MiKTeX/miktex#112]
The prepmx.exe file (the 64 bit version from the miktex-m-tx-bin-x64-2.9 package) does nor work. When I execute it, it freezes and Windows informs me that prepmx has stopped working and is being terminated.

The file from ctan (that is nearly twice as large) works fine.

**Comment by edocevoli** [comment]
Cannot reproduce your issue. Running `prepmx` yields:

````
==> This is M-Tx 0.63 (Music from TeXt) <7 January 2018>
Usage: prepmx [-bcfnhimtuvwDH0123456789] MTXFILE [TEXDIR] [STYLEFILE]
Try "prepmx -h" for more information.
````

**Comment by schtandard** [comment]
Maybe I should clarify: Running it on an actual file causes this behavior. (For example on [this example file](http://icking-music-archive.org/software/mtx/netsoos.mtx).)

**Comment by edocevoli** [comment]
Please learn how to write bug reports.

Added missing input file:
[netsoos.zip](https://github.com/MiKTeX/miktex/files/1907954/netsoos.zip)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
