### ISSUE TITLE
miketex installlation

### ISSUE THREAD

**Issue by chaitraraikar** [MiKTeX/miktex#1123]
i installed miketex maker 
got  to know it was not the compiler
so i uninstalled
again i installed tex maker then got to know its the support
now i have to install miketex but setup says the path file is not empty 
so installation not proceeding

what to do

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
