### ISSUE TITLE
platex build fail with tarticle class

### ISSUE THREAD

**Issue by ostaith** [MiKTeX/miktex#1129]
- [x] I have read and acknowledged this HOWTO article:  

hi edocevoli,
after i upgrade to miktex 22.7, now the platex format can build. but when i try this MWE with platex:
```
\documentclass{tarticle}
\begin{document}
で日本語を書きましょう！
\end{document}
```
it builds fail. the `platex.log` is, and the detailed build log also attached.
```
2022-07-19 21:57:57,574+0800 INFO  platex - this process (1660) started by cmd in directory E:\Project\ptex with command line: platex mwe
2022-07-19 21:57:57,603+0800 WARN  platex - security risk: running with elevated privileges
2022-07-19 21:57:57,605+0800 INFO  platex - this is MiKTeX-EPTEX 1.1.0 (220214) (MiKTeX 22.7)
2022-07-19 21:57:57,605+0800 INFO  platex - allowing known shell commands
2022-07-19 21:57:57,773+0800 FATAL platex - invalid UTF-8 byte sequence
2022-07-19 21:57:57,773+0800 INFO  platex - this process (1660) finishes with exit code 1
2022-07-19 21:57:57,773+0800 WARN  platex.core - still open: mwe.log
2022-07-19 21:57:57,773+0800 WARN  platex.core - still open: mwe.aux
```
but i try to build this MWE with texlive 2022, it build successfully.
i compare the `tarticle` in miktex and texlive 2022, they are same.

and if i replace the `tarticle` with `article`, the platex in miktex build also successfully:
```
\documentclass{article}
\begin{document}
で日本語を書きましょう！
\end{document}
```
so it means the platex can work, but can't work with `tarticle.cls`.
the log don't have more information that which file and which line have the `invalid UTF-8 byte sequence`, and why `invalid UTF-8 byte sequence`? because texlive 2022 build the MWE with UTF-8 also.

how to get more information to fix this issue?

i installed these package for using platex/uplatex:
```
japanese-otf
japanese-otf-uptex
ptex-base
ptex-fontmaps
ptex-fonts
ptex2pdf
platex-tools
platex
uptex-base
uptex-fonts
uplatex
zhmetrics-uptex
```

[build_log.txt](https://github.com/MiKTeX/miktex/files/9142056/build_log.txt)

**Comment by edocevoli** [comment]
Thank you. This is a console output error. Seems that 'tarticle' produces non-UTF-8 output. I will try to reproduce the issue.

**Comment by ostaith** [comment]
yes, i asked someone, the `tarticle.cls` encoding should be `iso-2022-jp`, other if open with utf8, the line 95 display not correct:
![image](https://user-images.githubusercontent.com/34862369/179979650-6f68c1ac-9eca-46bf-864b-389a1d2bc8c5.png)
so it means platex process `iso-2022-jp` encoding error.
and i do some other tests, found platex can't process `shift-jis` also.

**Comment by ostaith** [comment]
test1, `platex` build with `shift-jis` encoding package:
```
\documentclass{tarticle}
\usepackage[deluxe,expert]{otf}
\usepackage{furikana}
\begin{document}
\kana{牡丹色}{ぼたんいろ}
\end{document}
```

`furikana.sty` can download from [here](http://xymtex.com/fujitas2/texlatex/tategumi/furikana.sty).

the original `furikana.sty` encoding is `shift-jis`. if build with `shift-jis furikana.sty` with `platex`, the build log is:
```
E:\Project\ptex3>platex mwe
platex: security risk: running with elevated privileges
This is e-pTeX, Version 3.141592653-p4.0.0-220214-2.6 (utf8.euc) (MiKTeX 22.7) (preloaded format=platex.fmt)
 restricted \write18 enabled.
entering extended mode
(jcolor.tex
pLaTeX2e <2021-11-15> (based on LaTeX2e <2022-06-01> patch level 5)
L3 programming layer <2022-07-04> (D:\MiKTeX\tex/platex/base\tarticle.cls
Document Class: tarticle 2020/09/30 v1.8f Standard pLaTeX class
(D:\MiKTeX\tex/platex/base\tsize10.clo) (D:\MiKTeX\tex/platex/base\plext.sty))
(D:\MiKTeX\tex/platex/japanese-otf-uptex\otf.sty
(D:\MiKTeX\tex/latex/graphics\keyval.sty)
(D:\MiKTeX\tex/platex/japanese-otf-uptex\ajmacros.sty)) (furikana.sty
Option Style `furikana' (ver1.02) <August 22, 2000> [S. Fujita]
^^93^^a1^^93c^^e1^^c1^^8d^^ec^^81u^^93^^fc^^96^^e5^^81E^^8fc^^89^^a1^^95^^b6^^8
f^^91^^8fp^^81v^^8f^^8a^^8d^^da

! LaTeX Error: Invalid UTF-8 byte "8A.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.79 \setbox0=\hbox{^^8a
                        ^^bf}
?
```

**Comment by ostaith** [comment]
test2, `platex` build with `utf8` encoding package:
```
\documentclass{tarticle}
\usepackage[deluxe,expert]{otf}
\usepackage{furikana}
\begin{document}
\kana{牡丹色}{ぼたんいろ}
\end{document}
```

mwe.tex not change, but convert `furikana.sty` encoding to `utf8`:
1. `platex` crashed this time
2. the build log is:
```
E:\Project\ptex3>platex mwe
platex: security risk: running with elevated privileges
This is e-pTeX, Version 3.141592653-p4.0.0-220214-2.6 (utf8.euc) (MiKTeX 22.7) (preloaded format=platex.fmt)
 restricted \write18 enabled.
entering extended mode
(jcolor.tex
pLaTeX2e <2021-11-15> (based on LaTeX2e <2022-06-01> patch level 5)
L3 programming layer <2022-07-04> (D:\MiKTeX\tex/platex/base\tarticle.cls
Document Class: tarticle 2020/09/30 v1.8f Standard pLaTeX class
(D:\MiKTeX\tex/platex/base\tsize10.clo) (D:\MiKTeX\tex/platex/base\plext.sty))
(D:\MiKTeX\tex/platex/japanese-otf-uptex\otf.sty
(D:\MiKTeX\tex/latex/graphics\keyval.sty)
(D:\MiKTeX\tex/platex/japanese-otf-uptex\ajmacros.sty)) (furikana.sty
Option Style `furikana' (ver1.02) <August 22, 2000> [S. Fujita]
ƣ
```
i found it's this line issue the error:
![image](https://user-images.githubusercontent.com/34862369/179985023-349bce7d-3162-40d2-8c03-35254f5128d7.png)

**Comment by ostaith** [comment]
test3, build the `utf8` package, and remove the `\typeout` content:
```
\documentclass{tarticle}
\usepackage[deluxe,expert]{otf}
\usepackage{furikana}
\begin{document}
\kana{牡丹色}{ぼたんいろ}
\end{document}
```

now build successfully and get the pdf.

**Comment by ostaith** [comment]
test5, `uplatex` build the `utf8` package:
```
\documentclass{utarticle}
\usepackage[uplatex,deluxe,expert]{otf}
\usepackage{furikana}
\begin{document}
\kana{牡丹色}{ぼたんいろ}
\end{document}
```

convert the `furikana.sty` encoding to `utf8`, now `uplatex` build successfully.

**Comment by edocevoli** [comment]
Thank, I was able to reproduce/fix the issue. Please update.
