### ISSUE TITLE
Using cuneiform font "archaic"

### ISSUE THREAD

**Issue by wkittler** [MiKTeX/miktex#1133]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
I am trying to typeset cuneiform characters. I downloaded "archaic" in MikTex, but when I use the package, I get the Latex Error:
'archaic.sty' not found.
The same happens in Overleaf.
Any suggestions what I did wrong, or what I should change?

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
