### ISSUE TITLE
'source specials enabled' slow down

### ISSUE THREAD

**Issue by dowkeruk** [MiKTeX/miktex#1135]
I am running MikTex version 20.6.29 in Windows 10 and also version 22.7.25 in Windows 11 on a much faster machine which however compiles more slowly as the compiler spends a few seconds at the ` enabled source specials' point which is annoying. Version 20.6.29 does not seem to have this switch. Can I turn it off in version 22.7.25?. The command line is just tex.exe. I am using Texniccenter editor.

**Comment by edocevoli** [comment]
No, you cannot turn it off.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
