### ISSUE TITLE
updmap crash

### ISSUE THREAD

**Issue by ostaith** [MiKTeX/miktex#1138]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Miktex: 22.7
OS: Win 7 SP1 32bit

`updmap --help` can run successful. but other command crushed and generate dump file:
![image](https://user-images.githubusercontent.com/34862369/181300956-1aa88318-2df4-403e-8445-57ff7f86e188.png)
![image](https://user-images.githubusercontent.com/34862369/181302809-833fe4c3-2e76-4251-947e-f27e55128372.png)
sorry for chinese screen capture.

but in Win 10 64bit, it run successful:
![image](https://user-images.githubusercontent.com/34862369/181303398-2a4366c4-e018-42a2-80fe-51c50d8c521c.png)

and as i remember, Miktex 21.3 `updmap` can run successful in Win 7 SP1 32bit still.

I use `updmap` to update fndb and font map after i install some new packages and fonts, because I don't want to open `miktex-console_admin.exe`. I'm not sure I use `updmap` is correct or not.

**Comment by edocevoli** [comment]
Yes, `updmap fndb` crashes. This should be fixed.

Please note that the `updmap` usage is wrong. Just run `updmap`, without any arguments.

**Comment by edocevoli** [comment]
Changed the issue title because this is not really Windows 7 32-bit specific.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
