### ISSUE TITLE
Compile-Error after installation

### ISSUE THREAD

**Issue by ThomasFOC** [MiKTeX/miktex#114]
After providing the MiKTeX-distribution for other users via Matrix42 there is an issue after the installation on their systems:
When compiling a document for the first time the UAC of Windows 7 opens.
After accepting the UAC the compiling proceeds but stops with a broken pdfTeX:
![grafik](https://user-images.githubusercontent.com/38452519/38852665-05927c18-421b-11e8-812a-fd2672998210.png)
The console of the GUI (TeXstudio or TeXworks) produces the following log:
```
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\abc' on input line 69.
AED: lastpage setting LastPage
Overfull \vbox (19.10742pt too high) has occurred while \output is active
[3] (test.aux) )
(see the transcript file for additional information){C:/Program Files/MiKTeX 2.
9/fonts/enc/dvips/base/8r.enc}<C:/Program Files/MiKTeX 2.9/fonts/type1/bera/fvs
b8a.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/bera/fvsr8a.pfb>
Sorry, but "MiKTeX Compiler Driver" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/user/AppData/Local/MiKTeX/2.9/miktex/log/texify.log

You may want to visit the MiKTeX project page, if you need help.
```
The mentioned logfile:
```
INFO  texify - starting with command line: "C:\Program Files\MiKTeX 2.9\miktex\bin\x64\texify.exe" --pdf --synctex=1 --clean test.tex
FATAL texify - The process terminated due to an access violation.
FATAL texify - Info: fileName="C:\Program Files\MiKTeX 2.9\miktex\bin\x64\pdflatex.EXE"
FATAL texify - Source: Libraries\MiKTeX\Core\Process\win\winProcess.cpp
FATAL texify - Line: 435
```
After a second compilation-try the document is produced without problems.
When compiling other documents for the first time the error reappears one time.

**Comment by edocevoli** [comment]
Thank you for the report. I cannot reproduce the issue. I did the following:

1. Install MiKTeX
2. Run `pdflatex sample2e`

Everything is okay.

**Comment by ThomasFOC** [comment]
After some research I've tracked down the issue a bit.
The problem is the MiKTeX Package Manager. After `pdflatex.exe` is executed it tries to install new packages from a local package repository on a server (in our case `\\srv-01-dc2\MiKTeX`).
But to enter the MiKTeX Package Manager it needs the administator privileges.
After the UAC-Dialog the Manager installs the packages in the CommonRoots-Directory `C:\Program Files\MiKTeX`, which is not correct as `pdflatex.exe` is started in user mode.
The packages are correctly installed, but the `pdflatex.exe` fails like mentioned above.

Perhaps the windows crash report (report.wer) may help: 
[Report.txt](https://github.com/MiKTeX/miktex/files/1983923/Report.txt)

In the UAC-Dialog, which can't be screenshoted, there is a `CLASSID: {25E664C9-989C-4EDAA9A4-C9E45FB447D3}` which may help.

Can you help me, track down the issue? Are there any more informations I can provide to help you?
