### ISSUE TITLE
MikTex Installer: setup directory information is empty for shared install

### ISSUE THREAD

**Issue by GerardTromp** [MiKTeX/miktex#1143]
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Greetings!

Strange problem: Brand new installation on a fresh install of Windows 10. 
Whether using the Basic Installer(basic-miktex-22.7-x64.exe) or the Network Installer (setup-5.1-x64.exe), I end up with the following failure. 
![MikTexInstallerFailure](https://user-images.githubusercontent.com/25434893/182019614-47096cd2-8d84-474c-94ac-482472c58b28.png)

It appears that the shared installation is no longer possible at all, rather than being ill advised. [On that note, I have, until my hardware problem a number of days ago, administered a shared MikTex installation for at least 15 years (since about version 2.1/2.2), and never found it to be a problem.]

What could cause the installer from "forgetting" values that were entered in the prior steps? Is the options file not created, renamed (not setupwiz.opt) or in the wrong place (different directory)?

**Comment by edocevoli** [comment]
Yes, the options file is still supported and it works for me.
