### ISSUE TITLE
jfmutil run fail

### ISSUE THREAD

**Issue by ostaith** [MiKTeX/miktex#1145]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hi edocevoli,
the jfmutil also can't run:
```
D:\MiKTeX\fonts\vf\public\jlreq>D:\MiKTeX\miktex\bin\x64\jfmutil.exe vf2zvp -u --lenient ujlreq.vf
jfmutil: tftopl failed: __zrtx4000mwf1gvi.tfm
```

and in texlive, it can run and get the `.zvp` file:
```
D:\texlive\texmf-dist\fonts\vf\public\jlreq>D:\texlive\bin\win32\jfmutil.exe vf2zvp -u --lenient ujlreq.vf

D:\texlive\texmf-dist\fonts\vf\public\jlreq>
```
![image](https://user-images.githubusercontent.com/34862369/182916847-a3777519-cb96-4213-a058-e698ea02f736.png)

**Comment by ostaith** [comment]
please check the run logs.
[miktex.log.zip](https://github.com/MiKTeX/miktex/files/9269404/miktex.log.zip)

**Comment by edocevoli** [comment]
Thank you, jfmutil now runs. On my system, running `jfmutil.exe vf2zvp -u --lenient ujlreq.vf` yields:
```
jfmutil: illegal element in CHARSINTYPE: 12964
```
But I don't think that this is MiKTeX-specific.
