### ISSUE TITLE
Check for updates - error

### ISSUE THREAD

**Issue by Lindabba** [MiKTeX/miktex#1146]
Hello! I just installed "basic-miktex-22.7-x64.exe". At the first launch I get the message that I did not check for updates. Pressing the button 'Check for updates' results in error. Can you please help me to fix this issue ?
Here is the error report:

GENERAL MIKTEX INFORMATION
ReportDate: 2022-08-05 11:14:07
CurrentVersion: 22.7
SetupDate: 2022-08-05 10:51:00
SetupVersion: 22.7
Configuration: Regular
GitInfo: 07c2f18 / 2022-07-16 08:47:18
OS: Windows 10 Pro, 64-bit, build 22000
SharedSetup: no
LinkTargetDirectory: C:\Users\Linda\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
LastUpdateDb: not yet
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: C:\Users\Linda\AppData\Roaming\MiKTeX
Root1: C:\Users\Linda\AppData\Local\MiKTeX
Root2: C:\Users\Linda\AppData\Local\Programs\MiKTeX
UserInstall: C:\Users\Linda\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\Linda\AppData\Roaming\MiKTeX
UserData: C:\Users\Linda\AppData\Local\MiKTeX
Invokers: non-existing/explorer

The following issues were detected:
  1: major issue: So far, you have not checked for MiKTeX updates.

ERROR DETAILS
Program: miktex-console
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:247
Error: SSL connect error
Details: 
  code: 35
  url: https://api2.miktex.org/hello

Thank you in advance for your help.

Linda 

PS: I tried to add screen shot but "Something went really wrong, and we can't process that file"

**Comment by Lindabba** [comment]
It was due to restriction from IT. Another internet connection and its working fine now.

**Comment by edocevoli** [comment]
Glad to hear
