### ISSUE TITLE
miktex ( on linux ) vs sagetex

### ISSUE THREAD

**Issue by Fra1962** [MiKTeX/miktex#1149]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
I have a Manjaro  System where i have installed miktex. I use also sagemath and, when i try to install sagetex, manjaro try to install (with yay ):
`texlive-bin-2022.62885-1  texlive-core-2022.63035-1  sagetex-3.6-2
`
 the error occurs:
`errore: impossibile eseguire l'operazione richiesta (file in conflitto)
texlive-bin: /usr/share/man/man5/updmap.cfg.5.gz è già presente nel filesystem (appartiene a miktex)
Si sono verificati degli errori, nessun pacchetto è stato aggiornato.
 -> error installing repo packages
`
any idea ?

**Comment by edocevoli** [comment]
I have removed the updmap man page. It should work now.
