### ISSUE TITLE
Remote `markdown` package repository is outdated!

### ISSUE THREAD

**Issue by 1216892614** [MiKTeX/miktex#1150]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

# What Ive done?

- Use `miktex-console` on `openSUSE Leap 15.4`
- Use mirror `https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/`
- Try to install package `markdown`

# Error Info

- base

```
The remote package repository is outdated. You have to choose another repository.
```

- more

```
url="https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/"
```

**Comment by edocevoli** [comment]
I was not able to reproduce the issue.
