### ISSUE TITLE
Internal error when running "miktexsetup_standalone.exe --version"

### ISSUE THREAD

**Issue by jjolidon** [MiKTeX/miktex#1151]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hello all,

I get the following error
> miktexsetup_standalone: C:\jenkins\workspace\miktex\windows\build\source\Libraries\MiKTeX\Core\Utils\Utils.cpp:490: internal error

when I run

> C:\Full\Path\To\miktexsetup_standalone.exe --version

with the MiKTeX standalone installer version 4.2 as downloaded this day from the website.

May I request if this is a known issue and if there is a possible workaround?

Obviously no install report or execution logs because that happens even before I run the installer.

Thanks in advance,
Jérôme Jolidon

System: Windows 10 21H2
MiKTeX standalone installer 4.2 downloaded on 23.08.22
Source file: https://github.com/MiKTeX/miktex/blob/next/Libraries/MiKTeX/Core/Utils/Utils.cpp#L490

**Comment by edocevoli** [comment]
This has been fixed. The new version (5.1) will be available tomorrow.

**Comment by jjolidon** [comment]
Thanks!
