### ISSUE TITLE
Download install MikTex repository (basic and complete) failed

### ISSUE THREAD

**Issue by Be1000** [MiKTeX/miktex#1155]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

CMDLINE / Windows x64 :
miktexsetup_standalone.exe --verbose --local-package-repository=C:\temp\miktex --package-set=basic download

OUTPUT :
this is MiKTeX Setup Service 4.3 (MiKTeX 21.7)
starting downloader...
starting download...
repository: https://ctan.net/systems/win32/miktex/tm/packages/
download directory: C:\temp\miktex
visiting repository https://ctan.net/systems/win32/miktex/tm/packages/...
repository type: remote package repository
loading package repository manifest...
downloading https://ctan.net/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
**miktexsetup_standalone: SSL connect error**
**miktexsetup_standalone: Data: code="35", url**="https://ctan.net/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma"

SSL connect error from several Win10 x64 computers (august 2022)

**Comment by edocevoli** [comment]
Sorry, but I don't know how to fix this.
