### ISSUE TITLE
MikTex Installer and Command-line installer have got different versions (2022 vs 2021)

### ISSUE THREAD

**Issue by Be1000** [MiKTeX/miktex#1156]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Installer**
Date : 7/18/**2022**
File name: basic-miktex-22.7-x64.exe
Size : 132.71 MB

**Command line installer**
Date : 7/19/**2021**
File name: miktexsetup-4.2-x64.zip _<- MikTek 21.7_
Size: 2.47 MB

I would like to know when the new MikTex command-line version will be available ?

**Comment by edocevoli** [comment]
A new version will be made available in the course of bug fixing.
