### ISSUE TITLE
Different behavior between miktexsetup_standalone 4.2 and 5.1 (missing xelatex.exe)

### ISSUE THREAD

**Issue by jjolidon** [MiKTeX/miktex#1159]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hi there,

I switched to the miktexsetup_standalone 5.1 and found that the same commands did not result in the same output, specifically I'm missing the xelatex.exe file, which is used by Pandoc.

What I do:
```powershell
& "$installerPath" --local-package-repository="$cachedMikTexRepository" --package-set=basic download
& "$installerPath" --quiet --portable=$installationFolder --package-set=basic --local-package-repository "$cachedMikTexRepository" install
```

With 4.2, this results in having a "xelatex.exe" file in texmfs\install\miktex\bin\x64. With 5.1 this is not the case.

I am not sure if this is not an intended change of behavior, though, in which case perhaps Pandoc should change their code?

Sincerely,
Jérôme Jolidon

**Comment by jjolidon** [comment]
My [miktex-report.txt](https://github.com/MiKTeX/miktex/files/9451548/miktex-report.txt)

**Comment by wiciok** [comment]
Hi,
I am facing very similar issue (xelatex not found by Pandoc). 
From what I've found out, issue occurs only with miktexsetup_standalone installer (also 5.1). 
While using standard GUI installer (basic-miktex-22.7-x64.exe), xelatex binaries are present and Pandoc finds them correctly.

**Comment by hair-splitter** [comment]
I have the same problem. When installing MiKTeX with miktexsetup_standalone, there is no pdflatex.exe, lualatex.exe, xelatex.exe, latexmk.exe, etc. I think this is a serious problem. Especially the lack of latexmk.exe is annoying.

**Comment by IlonkaP** [comment]
I would guess this is the same issue I reported: #1183. I just didn't found this one. For me it is pdflatex.exe, that I was missing in particular. I would guess I have more missing items like @hair-splitter but I wouldn't know for sure and since I didn't need any of the other executables he mentioned I didn't notice.

This issue also sounds like it is about the same problem: #1188.
