### ISSUE TITLE
Cannot run on El Capitan

### ISSUE THREAD

**Issue by Behinder** [MiKTeX/miktex#116]
C'mon. I recently discovered that Mikex is on MAC!
Been using it many years ago on Windows.
On windows you can use it on all the old systems.
I am on El Capitan, what is REALLY Neccesarry in Sierra and High Sierra that prevent running Miktex on old systems where TexLive can run.

I don't really want to use Texlive because it cannot handle dependency problems in packages in which Miktex always was superior.

**Comment by edocevoli** [comment]
It should be possible to build MiKTeX on 10.11 and if you know how to set up a Travis-CI repository then you can build MiKTeX for El Capitan.

**Comment by Behinder** [comment]
Thanks I am gonna take a look. Is there any instruction for building Miktex?

**Comment by Behinder** [comment]
Ok I created  dmg package and it works flawlessly.
You may find it [here](https://www.dropbox.com/s/dyetiak88huek3l/miktex-2.9.6670-1-darwin-x86_64_ELCapitan.dmg?dl=0)

**Comment by edocevoli** [comment]
This will be fixed with [milestone 2.9.6730](https://github.com/MiKTeX/miktex/milestone/6).

**Comment by Behinder** [comment]
I built already dmg and shared it.
Great to see it working with new milestone :)
