### ISSUE TITLE
MiKTeX fails on iMac after last update

### ISSUE THREAD

**Issue by RVLTex** [MiKTeX/miktex#1160]
- [ X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

After installing the last update today, I can't compile. 
My .sty files are not found, some packages are not found (as cancel or enumitem) and the option for "aux directory" is not recognized.

[Report.txt](https://github.com/MiKTeX/miktex/files/9472220/Report.txt)

**Comment by edocevoli** [comment]
It works for me.
