### ISSUE TITLE
kanji-config-updmap-sys set font fail

### ISSUE THREAD

**Issue by ostaith** [MiKTeX/miktex#1165]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hi edocevoli,
`kanji-config-updmap-sys status` now run successfully.
but `kanji-config-updmap-sys --jis2004 kozuka-pr6n` still fail, pls check the following command log.
after run `kanji-config-updmap-sys --jis2004 kozuka-pr6n`, the `CURRENT family for ja` is still `haranoaji` but not `kozuka-pr6n`.
I have installed `KozMinPr6N` in system.

```
D:\MiKTeX\miktex\bin\x64>kanji-config-updmap-sys status
CURRENT family for ja: haranoaji (variant: -04)
Standby family : haranoaji
Standby family : ipa
Standby family : ipaex
Standby family : kozuka-pr6n
Standby family : ms

D:\MiKTeX\miktex\bin\x64>kanji-config-updmap-sys --jis2004 kozuka-pr6n
Setting up ... kozuka-pr6n for ja
Incorrect usage: -04: unknown option

D:\MiKTeX\miktex\bin\x64>kanji-config-updmap-sys status
CURRENT family for ja: haranoaji (variant: -04)
Standby family : haranoaji
Standby family : ipa
Standby family : ipaex
Standby family : kozuka-pr6n
Standby family : ms
```

you can check my command log in #1144, the `tex live` set font correctly:
```
...
D:\texlive\bin\win32>kanji-config-updmap-sys.exe status
CURRENT family for ja: kozuka-pr6n (variant: -04)
Standby family : haranoaji
Standby family : ipa
Standby family : ipaex
Standby family : kozuka-pr6n
Standby family : ms
Standby family : yu-win10
```

pls check the run log also:
[miktex.log.zip](https://github.com/MiKTeX/miktex/files/9484967/miktex.log.zip)

BTW, can you guide how to build the `kanji-config-updmap-sys.exe` from source code?
I try to build source code, but can't get `kanji-config-updmap-sys.exe`.

**Comment by ostaith** [comment]
after I build some TeX project, this issue fixed automatically, Maybe the issue is because of missing some packages. because I just reinstall MiKTeX then run the command.
And After I build some TeX project, some packages installed, then the command run successfully:
```
D:\MiKTeX\miktex\bin\x64>kanji-config-updmap-sys status
CURRENT family for ja: kozuka-pr6n (variant: -04)
Standby family : haranoaji
Standby family : ipa
Standby family : ipaex
Standby family : kozuka-pr6n
Standby family : ms

D:\MiKTeX\miktex\bin\x64>kanji-config-updmap-sys --jis2004 haranoaji
Setting up ... haranoaji for ja
Incorrect usage: -04: unknown option

D:\MiKTeX\miktex\bin\x64>kanji-config-updmap-sys status
CURRENT family for ja: haranoaji (variant: -04)
Standby family : haranoaji
Standby family : ipa
Standby family : ipaex
Standby family : kozuka-pr6n
Standby family : ms

D:\MiKTeX\miktex\bin\x64>kanji-config-updmap-sys --jis2004 kozuka-pr6n
Setting up ... kozuka-pr6n for ja
Incorrect usage: -04: unknown option

D:\MiKTeX\miktex\bin\x64>kanji-config-updmap-sys status
CURRENT family for ja: kozuka-pr6n (variant: -04)
Standby family : haranoaji
Standby family : ipa
Standby family : ipaex
Standby family : kozuka-pr6n
Standby family : ms
```
I'll try and report again. If it's really because of missing some packages, I'll close this issue. Sorry to trouble you.

**Comment by ostaith** [comment]
I test in another machine, it has same result:
If run `kanji-config-updmap-sys --jis2004 kozuka-pr6n` just after install MiKTeX, it will fail. But if I build some project, it can run successfully.

**Comment by edocevoli** [comment]
Great, thank you for the feedback
