### ISSUE TITLE
MikTex 2.9.6670 ps2pdf not working

### ISSUE THREAD

**Issue by AnotherCommonMan** [MiKTeX/miktex#117]
After compiling myfile.tex to get myfile.dvi file, then use dvips (which seems to work properly; dvips myfile -o myfile.dvi), then use 'ps2pdf myfile.ps myfile.pdf' and get the error:

Error: /undefined in ????
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval-
-   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   fa
lse   1   %stopped_push   2015   1   3   %oparray_pop   2014   1   3   %oparray_
pop   1998   1   3   %oparray_pop   1884   1   3   %oparray_pop   --nostringval-
-   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringv
al--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:986/1684(ro)(G)--   --dict:0/20(G)--   --dict:88/200(L)--   --dict:193
/300(L)--   --dict:67/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 382230
MiKTeX GPL Ghostscript 9.22: Unrecoverable error, exit code 1

But, if use pdflatex myfile.tex, all seems to work ok.

Any help appreciated.
Thanks

**Comment by edocevoli** [comment]
I cannot reproduce this issue. What I did:

1. Run `ps2pdf myfile.ps myfile.pdf`
2. Open `myfile.pdf`

Everything OK: 
[myfile.pdf](https://github.com/MiKTeX/miktex/files/1932627/myfile.pdf)

**Comment by AnotherCommonMan** [comment]
Tracked the problem down:

The error occurs when I use the 'fancyhdr' package and try to include a *.jpg in the header (see example LaTeX below). If there is no graphics included in the header, then 'ps2pdf' works without any problems, but as soon as the graphics is included in the header 'ps2pdf' fails (i.e. no pdf file is produced at all and above error occurs). When 'pdflatex' is used it 'works' because it just abandons the graphics in the header and produces a document without the graphics in the header.

This used to work without any problems in my previous version of MikTeX (pre-2016) i.e. used 'ps2pdf' and the graphics used to be displayed without any problems in the header.

Any ideas why it should fail now?

Many thanks (see below for example LaTeX)


e.g.

\documentclass{book}
\usepackage{fancyhdr}
\usepackage[dvips]{graphicx}


\pagestyle{fancy}

\lhead{\includegraphics[natwidth=1535,natheight=631,width=2cm,height=0.75cm]{mygraphics.jpg}}
% \lhead{} % Using this line instead of above line 'ps2pdf' works
\chead{}
\rhead{}
\lfoot{}
\cfoot{\thepage\ of \pageref{LastPage}}
\rfoot{}
\renewcommand{\headrulewidth}{0.5pt}
\renewcommand{\footrulewidth}{0.5pt}



\begin{document}

% Some LaTeX

\end{document}

**Comment by u-fischer** [comment]
dvips + ps2pdf can't handle jpg.  Perhaps you used dvipdfmx previously. 

(Side remark: with pdflatex you shouldn't use natwidth and natheight, see also https://github.com/latex3/latex2e/issues/21.)

**Comment by AnotherCommonMan** [comment]
Sorry for the delayed response. Thanks for the help.

But, I have recently tracked down a previous version of MikTeX and under this older version everything works *ok*:  the *.jpg is processed without any problem by ps2pdf (even a *.jpg in the fancyheader).

The question now is what has changed between this older version and the current version to stop this working.

Any help appreciated. Thanks.

**Comment by AnotherCommonMan** [comment]
The version of MikTeX  referred to above is MikTeX 2.9 with MikTeX Package Manager 2.9.4497.

Let me know if any other info would be helpful.

Thanks.

**Comment by u-fischer** [comment]
there once was a special dvips version which contained the bmeps library and could handle jpg. But it is no longer in miktex.
