### ISSUE TITLE
Portable installation error: Option --admin only makes sense for a shared MiKTeX setup

### ISSUE THREAD

**Issue by garch69** [MiKTeX/miktex#1179]
update(20220915)：

Firstly, thanks for your great efforts.  Would like to know how to run the installer un-elevated mentioned in the issue #375?  Does it mean that let UAC be the default setting?  If yes, the issue is still happened in my case.

However, after updating via miktex-console, the portable version seems to work as described.  I am just wondering whether the process of this installation is normal or not.  Thanks for your patience and consideration.

----------------
Error with portable installation 2022/09/13, basic-miktex-22.7-x64.exe.

Did I miss or misunderstand something in the installation of portable version?
The attached please find the complete setup log.  The excerpt is on the following below.

Your patience and assistance are greatly appreciated.

----------------
Creating portable setup...
63 [0x00003228] INFO initexmf null - this process (12556) finishes with exit code 0

miktex --admin --log-file=E:\00_libreOfficeP\0miktex\MiKTeXp\texmfs/install\miktex/config\uninst.log --disable-installer --verbose fndb remove:

Sorry, but: option --admin only makes sense for a shared MiKTeX setup
Warning: The executed process did not succeed.
Warning: The executed process did not succeed.
mpm --register-components --admin --verbose:

Sorry, but "MiKTeX Package Manager" did not succeed for the following reason:

  Option --admin only makes sense for a shared MiKTeX setup.
log4cxx: No appender could be found for logger (mpmcli).
log4cxx: Please initialize the log4cxx system properly.

An error occurred:
  source file: 
  source line: 0
  message: The executed process did not succeed.
  info: fileName="E:\00_libreOfficeP\0miktex\MiKTeXp\texmfs\install\miktex\bin\x64\mpm.exe", exitCode="1"

[setup-2022-09-15-10-16.log](https://github.com/MiKTeX/miktex/files/9571234/setup-2022-09-15-10-16.log)

**Comment by edocevoli** [comment]
Is the installer running with elevated privileges?

**Comment by garch69** [comment]
> Is the installer running with elevated privileges?

Appreciate the quick response.  After trying several times repeatedly, there is no error in the portable installation under no "run as administrator" circumstances.  The issue is solved.  Thanks again.

**Comment by DASTSAD** [comment]
I just downloaded he newest MikTeX basic-miktex-24.1-x64.exe. 

renaming and started with double click. 
same error:

`Sorry, but: option --admin only makes sense for a shared MiKTeX setup
Warning: The executed process did not succeed.
Warning: The executed process did not succeed.
mpm --register-components --admin --verbose:

Sorry, but "MiKTeX Package Manager" did not succeed for the following reason:

  Option --admin only makes sense for a shared MiKTeX setup.
log4cxx: No appender could be found for logger (mpmcli).
log4cxx: Please initialize the log4cxx system properly.`

I wander how to start it without admin rights now...
