### ISSUE TITLE
pdflatext.exe missing from Windows Net Installer 64

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#1187]
The " pdflatex.exe" file is missing from the "Windows net installer 64" file,  although "miktex-pdftex.exe" is present. This prevents TeXstudio from working and warns that no LaTeX distribution was found on the system.

miktex-report.txt

ReportDate: 2022-09-29 14:08:31
CurrentVersion: 22.8.28
SetupDate: 2022-09-29 11:29:00
SetupVersion: 22.8.28
Configuration: Regular
GitInfo: 0462c68 / 2022-08-26 16:06:35
OS: Windows 10.0.22000
SharedSetup: no
LinkTargetDirectory: C:\Users\gerar\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2022-09-29 11:31:20
LastUpdate: not yet
LastUpdateDb: 2022-09-29 11:31:06
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\gerar\AppData\Roaming\MiKTeX
Root1: C:\Users\gerar\AppData\Local\MiKTeX
Root2: C:\Users\gerar\AppData\Local\Programs\MiKTeX
UserInstall: C:\Users\gerar\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\gerar\AppData\Roaming\MiKTeX
UserData: C:\Users\gerar\AppData\Local\MiKTeX

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
