### ISSUE TITLE
"pdflatex.exe" missing from "Windows net installer 64"

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#1188]
Okay, we will try this again. The "pdflatex.exe" file is missing from the "Windows net installer 64". However, "miktex-pdftex.exe"  is present. This causes "TeXstudio" to issue a warning that no LaTeX distribution is available since it cannot locate the "pdflatex.exe" file. There are possibly other files missing, too; however, I can't determine that now.

Here is the miktex-report.txt

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/9678748/miktex-report.txt)

Somemore possible useful log files.

[initexmf.log](https://github.com/MiKTeX/miktex/files/9678756/initexmf.log)
[miktex.log](https://github.com/MiKTeX/miktex/files/9678757/miktex.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/9678758/miktex-console.log)
[mpmcli.log](https://github.com/MiKTeX/miktex/files/9678759/mpmcli.log)

The "C:\ProgramData\MiKTeX\miktex\log" does not exist.

Operating System:

Edition	Windows 11 Pro
Version	21H2
OS build	22000.978
Experience	Windows Feature Experience Pack 1000.22000.978.0
Processor	Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor

Please tell me precisely what you desire if this is not what you want.

**Comment by BeerStud** [comment]
I just received confirmation from another user that the **"Windows Net Installer"** does not generate a **"pdflatex.exe"** file. There may also be other files missing. The **"basic installer"** does generate the correct files. Whether this is confined to a Windows 11 PRO system has not been confirmed.

**Comment by edocevoli** [comment]
`pdftex.exe` is not a part of the distribution. It is created by the installer. Obviously something went wrong in the installation phase. Maybe you can find the setup log file (`setup-*.log`).

I will try to reproduce this next week.

**Comment by BeerStud** [comment]
I finally had a chance to do a clean install. The setup log is atached.
[setup-2022-10-08-12-05.log](https://github.com/MiKTeX/miktex/files/9739799/setup-2022-10-08-12-05.log)

**Comment by BeerStud** [comment]
I was just wondering if anyone has had a chance to look at the https://github.com/MiKTeX/miktex/files/9739799/setup-2022-10-08-12-05.log file yet? Something is not working correctly since it does not create the "pdflatex.exe" and possibly other files. I cannot confirm if it is limited to Windows 11 or not.

**Comment by edocevoli** [comment]
@BeerStud this is "in progress", i.e., a fix has been implemented.

**Comment by BeerStud** [comment]
I apologize, but I am not sure what that means. I just checked on the MiKTeX.org site, and the 64-bit net installer info displays this:

Date: 3/30/2022
File name: setup-5.1-x64.exe
Size: 24.33 MB
SHA-256: c7423d4993044db51422e16755b00dd99ac16605be190fc1c6cb2a2832fdea4d

Since the date is rather old, can I assume that the 64-bit Net Installer has not been updated yet? I do not want to waste all the time downloading and installing a product that will not work.

Thanks!

**Comment by edocevoli** [comment]
The fix has been implemented and is available for internal testing. The official release is pending.

**Comment by edocevoli** [comment]
This has been fixed now.
