### ISSUE TITLE
PGF Math Error with MikTex 2.9

### ISSUE THREAD

**Issue by gsilano** [MiKTeX/miktex#119]
I recently discovered that the new release of MikTex (2.9.6670) is not fully compatible with pgfplot, or something like that. In particular, when I tried to compile an already working tex file the error below appears:

Package PGF Math Error: Could not parse input 'pgfpme' as a floating point number, sorry. The unreadable part was near 'pgfpme'.. }

Does anyone know how to fix the problem?

**Comment by edocevoli** [comment]
I cannot reproduce this problem with your minimal test case. Please make sure that you have the latest MiKTeX updates and try again.

**Comment by gsilano** [comment]
I have the last release of MikTex. So, in order to help you to reproduce my problem in enclosed you find the my tex code.

[Issue_with_MikTex.zip](https://github.com/MiKTeX/miktex/files/1946262/Issue_with_MikTex.zip)

**Comment by u-fischer** [comment]
I can reproduce the problem. With 

~~~~~
\documentclass{article}     
\usepackage{pgfplots}

\begin{document}

\begin{tikzpicture}
\begin{axis}[]%\tracingmacros=1
\addplot3 file{graficiMatlab/traiettoriaAuto.txt};

\end{axis}
\end{tikzpicture}

\end{document}
~~~~

and the data file from the zip-file for gsilano.

I don't think that it is a package issue. In texlive there is no problem and imho the packages are identical. It looks more like a problem with the file reading: It works if I save the file (unchanged) under a new name. The hex editor shows then only one difference: in the failing case the last byte is 31, in the working case there is after the 31 an additional LF (0A).
