### ISSUE TITLE
I can't install MiKTeX in Ubuntu

### ISSUE THREAD

**Issue by etherewind** [MiKTeX/miktex#12]
Hi . I'm trying to install MiKTeX in Ubuntu. I run this on my console:
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
echo "deb http://miktex.org/download/ubuntu xenial universe" | sudo tee /etc/apt/sources.list.d/miktex.list
sudo apt-get update
`
And then
`sudo apt-get install miktex`

But the problem is that I don't know how to run the app to start writing. thanks

**Comment by edocevoli** [comment]
Which app do you want the start?

**Comment by edocevoli** [comment]
If I understand you correctly, you are searching for a TeX/LaTeX editor which allows you to run MiKTeX on your documents. Please note the current MiKTeX (for Linux( version only contains command-line utilities.

**Comment by etherewind** [comment]
Yes, that's my problem. Which one is nice?
