### ISSUE TITLE
Installation error in Ubuntu 18.04

### ISSUE THREAD

**Issue by ealmuina** [MiKTeX/miktex#120]
I'm getting the following error when I try `sudo apt install miktex` in Kubuntu 18.04:
```
The following packages have unmet dependencies:
 miktex : Depends: libcurl3 (>= 7.16.2) but it is not going to be installed
          Depends: libhunspell-1.3-0 (>= 1.3.3) but it is not installable
          Depends: libicu55 (>= 55.1-1~) but it is not installable
          Depends: libmpfr4 (>= 3.1.3) but it is not installable
          Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by edocevoli** [comment]
Ubuntu 18.04 is  not yet supported.

**Comment by gnuwin32** [comment]
After upgrading from 16.04 (so not a complete reinstall), MikTeX still worked. Apparently, the dependencies that edocevoli has reported as unmet, remained installed.

**Comment by u2berggeist** [comment]
Is there a way to install these dependencies separately? Seems like a simple enough thing to do...

**Comment by ealmuina** [comment]
@u2berggeist If you want you could manually grab the dependencies from https://packages.ubuntu.com/. There is a search section where you should specify the name of the package you want and the target distribution (use xenial since they aren't available in bionic). I haven't tried doing it this way, so tell me the outcome if you do it.

**Comment by edocevoli** [comment]
It is now possible to install MiKTeX on Ubuntu 18.04.

**Comment by Kohada-Koheiji** [comment]
I tried installing MiKTeX today and I got the same exact error.

**Comment by Kohada-Koheiji** [comment]
```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 miktex : Depends: libcurl4 (>= 7.16.2) but it is not installable
          Depends: libfontconfig1 (>= 2.12) but 2.11.94-0ubuntu2 is to be installed
          Depends: libicu60 (>= 60.1-1~) but it is not installable
          Depends: libmpfr6 (>= 3.1.3) but it is not installable
          Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by abedunah** [comment]
My miktex is still broken.  Help.

**Comment by OBrianbl** [comment]
I am having this same issue. Fresh Ubuntu 18.04...need this so I can work on my MS thesis. Any help?
