### ISSUE TITLE
Unable to download Net Installer 64-bit

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#1203]
I am unable to download the Net Install 64-bit file:

Date:10/18/2022
File name: setup-5.3.1+b8f430f-x64.exe
Size: 24.21 MB
SHA-256: 715ce060c416ff0887adbdbd23ca6513fdefc008b152b1e24af9785933aed727

When I click the download button, I receive a 404 Error message that the file is either moved or unavailable.

**Comment by mikeb-ah** [comment]
Workaround - use this mirror:
https://tug.ctan.org/systems/windows/miktex/setup/windows-x64/

**Comment by edocevoli** [comment]
Thank you, this has been fixed.
