### ISSUE TITLE
Error in MikTex while converting .ipynb to pdf.

### ISSUE THREAD

**Issue by nsrinivasan80** [MiKTeX/miktex#121]
installing package adjustbox triggered by tex\latex\adjustbox\adjustbox.sty
The remote package repository is outdated. You have to choose another repository.
2018-04-28 14:53:05,573-0400 FATAL xelatex - Info: ="url="ftp://ftp.fernuni-hagen.de/pub/mirrors/www.ctan.org/systems/win32/miktex/tm/packages/""

**Comment by nsrinivasan80** [comment]
Would deeply appreciate any help!

**Comment by edocevoli** [comment]
You have the option to choose another repository: Open MiKTeX Console and select another repository.
