### ISSUE TITLE
Maybe wrong translation?

### ISSUE THREAD

**Issue by balthild** [MiKTeX/miktex#1214]
https://github.com/MiKTeX/miktex/blob/12689e7f8de84e82802c1d8beab9130600f45081/Programs/MiKTeX/Console/Qt/translations/console_zh_CN.ts#L951

I've noticed that in the `zh_CN` translation, it says MiKTeX Console is a "freeware" (`免费`，free of charge). However, the copying page in the MiKTeX's website says 

> ... all software in the MiKTeX distribution is freely redistributable (libre, that is, not necessarily gratis)...

So I think it may be a wrong translation. The corrent translation should be `自由` rather than `免费`.

**Comment by edocevoli** [comment]
I think this has been fixed.
