### ISSUE TITLE
Switching to MiKTeX Console Administrator mode asks for elevation even if elevation is not required

### ISSUE THREAD

**Issue by tps800** [MiKTeX/miktex#1217]
On Windows assume some user "localdomain\localuser" and a MiKTeX install directory with acl set to "localdomain\localuser: Allow FullAccess".

Then why does MiKTeX-Console ask for Administrator credentials elevating this user? The user is granted full access to the installation directory already. Elevation would not be necessary for this user. The only question could be for allowance of changes to this directory if the user proceeds updating, configuring or installing. No need to elevate!

Could we have MiKTeX-Console check for such configurations and then stop elevating, just using this user to update, configure or install into this given directory?

BTW: this shall apply to any group the user is in and this group given necessary access to MiKTeX install directory.

**Comment by edocevoli** [comment]
Besides the installation directory, MiKTeX needs to access other resource (e.g., Windows Registry). It would be very cumbersome to check if the user has the privileges, hence the elevation prompt.
