### ISSUE TITLE
ps2pdf.exe fails silently

### ISSUE THREAD

**Issue by paultjevdh** [MiKTeX/miktex#1220]
Description:
When I run ps2pdf.exe on a latex sample file, it produces no output and exits with code -1

Steps to reproduce:
I first run the latex sample document sample2e.tex through latex and dvips:
```
cd %LOCALAPPDATA%\Programs\MiKTeX\tex\latex\base
latex sample2e.tex
dvips sample2e.dvi
```
dvi and ps files are generated.
I then run
`%LOCALAPPDATA%\Programs\MiKTeX\miktex\bin\x64\ps2pdf.exe sample2e.ps sample2e.pdf`
I expect to get a new file 'sample2e.pdf' , but I get nothing.
Reproduction of the issue is probably non-trivial. On my work computer I get the described behaviour. On my home computer everything works fine.
I already did a full reinstall of miktex to no avail.

I hope I can get some direction on how to debug this further.
Best regards,
Paul

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Attached files:
Installation report:
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/9964040/miktex-report.txt)
Log files:
[LOCALAPPDATAlog.zip](https://github.com/MiKTeX/miktex/files/9964042/LOCALAPPDATAlog.zip)

**Comment by u-fischer** [comment]
you shouldn't compile inside the texmf trees, they are typically protected.  Copy sample2e.tex to your document folder.

**Comment by paultjevdh** [comment]
I have installed Miktex in my user profile, ("this user only" installation) so the folder is not write protected. This is confirmed by the fact that the first two commands terminate successfully, and a dvi file and ps file are created in this directory.
Another argument is that the ps2pdf from the ghostscript installation on that machine also ran succesfully. 
Therefore file/folder protection does not seem to be the problem.
Paul

**Comment by u-fischer** [comment]
Did you test your argument by copying the sample.tex into your document folder and compiling there? Did it fail?

**Comment by paultjevdh** [comment]
Unfortunately that is no longer possible. I got a new work laptop last week. The old one is already wiped.
The new laptop does not reproduce the behaviour, even though I run the exact example above, in the same directory.
