### ISSUE TITLE
Corrupt package-manifests.ini file

### ISSUE THREAD

**Issue by ARockhill** [MiKTeX/miktex#1221]
I am no longer able to update my MiKTeX Console or load new packages.  When I attempt to I get the error shown below:
![image](https://user-images.githubusercontent.com/93292682/201488786-f41cfd68-505b-46ae-9cc3-1b765c5f58d9.png)

I took a look at the package-manifests.ini file, line 31405 and it appears as if the file has been cut off.
![image](https://user-images.githubusercontent.com/93292682/201489325-bc57c854-08e2-4e3e-b0b4-117efb24c8d2.png)

I've searched around and found issue #290 which documented a different corrupt entry and suggested the way the entry should look.  The user was able to manually edit the file and it seemed to work.  I've not been able to find anything close to what I see.  Is there a way to fix this without having to reset my configuration?  Can someone suggest what the whole biblatex entry in the manifests file should look like, and would that even solve the problem (I don't know if anything else was cut off as well).

I've attached the log files and the package-manifests.ini file, and the base latex file I was trying to compile when the issue became apparent.

Thanks for any help this community can provide.
Andy

[mictexLogFiles.zip](https://github.com/MiKTeX/miktex/files/9995664/mictexLogFiles.zip)
[package-manifests.zip](https://github.com/MiKTeX/miktex/files/9995671/package-manifests.zip)
[PWL_MDD_(working).zip](https://github.com/MiKTeX/miktex/files/9995672/PWL_MDD_.working.zip)

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
Sorry, but I cannot help you with this issue.
