### ISSUE TITLE
Miktex 22.10 problems with 'refstyle' in windows 11

### ISSUE THREAD

**Issue by dpsisi2022** [MiKTeX/miktex#1223]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
Although not used too often I am getting following error when \usepackage{refstyle} is used. Commenting it out gives uninterrupted compilation.

\AppData\Local\Programs\MiKTeX\tex/latex/refstyle\refstyl
e.cfg
! Argument of \eqref  has an extra }.
<inserted text> 
                \par 
l.526    lsttxt    = \RSlsttxt}

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
