### ISSUE TITLE
MiKTeX support for Fedora 37

### ISSUE THREAD

**Issue by vanlepthien** [MiKTeX/miktex#1224]
- [X ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
  
After upgrading to Fedora 37, miktex was flagged with a number of unresolved dependencies.
I deleted the existing install and attempted to reinstall from the existing miktex-fedora-36 repository (https://miktex.org/download/fedora/36/miktex.repo). There is no Fedora 37 repository.

sudo dnf install miktex

Last metadata expiration check: 0:16:28 ago on Tue 15 Nov 2022 11:54:47 PM MST.
Error: 
 Problem: conflicting requests
  - nothing provides libicui18n.so.69()(64bit) needed by miktex-22.8.28-1.fc36.x86_64
  - nothing provides libicuuc.so.69()(64bit) needed by miktex-22.8.28-1.fc36.x86_64
  - nothing provides libboost_locale.so.1.76.0()(64bit) needed by miktex-22.8.28-1.fc36.x86_64
  - nothing provides liblog4cxx.so.11()(64bit) needed by miktex-22.8.28-1.fc36.x86_64

(try to add '--skip-broken' to skip uninstallable packages)

The missing dependencies are either installed or available at a later release level.

The https://miktex.org/download page would also need to be updated.

**Comment by inarighas** [comment]
This seems resolved : https://miktex.org/download/fedora/37/miktex.repo
