### ISSUE TITLE
Missing MiKTeX220828-kpathsea.dll was not found.

### ISSUE THREAD

**Issue by eplain** [MiKTeX/miktex#1227]
- [ x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
Error Message:

pdftex.exe – System Error

The code execution cannot proceed because
MiKTeX220828-kpathsea.dll was not found. Reinstalling the program may fix this problem.

Same result with tex.exe

I have reinstalled MiKTeX with the same result
Test File:
%%
t
\bye

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.
You can try it again tomorrow. If the problem still exists: collect log files, screenshots etc.
Please read the guidelines:
https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md

Reminder: **Your job is to enable me to reproduce the problem.**
