### ISSUE TITLE
api2.miktex.org is unavailable

### ISSUE THREAD

**Issue by jameslamb** [MiKTeX/miktex#1228]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

For the past 24 hours or so, I've observed CI builds in a project I maintain failing with the following error.

> Setting up MiKTeX
miktexsetup_standalone: Timeout was reached
miktexsetup_standalone: Data: code="28", url="https://api2.miktex.org/hello"
Error: Process completed with exit code -1.

I tried that URL, and found that it's returning a 429.

```shell
curl -I https://api2.miktex.org/hello
```

```text
HTTP/1.1 429 Too Many Requests
Server: nginx/1.18.0 (Ubuntu)
Date: Wed, 23 Nov 2022 04:49:15 GMT
Connection: keep-alive
```

Is `api2.miktex.org` undergoing some maintenance right now? Is there a status page or some other place where I could learn more without opening an issue here?

## Reproducible Example

Using `miktexsetup-5.2.0-x64.zip` on a GitHub-hosted GitHub Actions runner, using the `windows-latest` environment.

Using the following powershell script

```pwsh
$env:CTAN_MIRROR = "https://ctan.math.illinois.edu/systems/win32/miktex"
$env:CTAN_PACKAGE_ARCHIVE = "$env:CTAN_MIRROR/tm/packages/"
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::ExtractToDirectory("miktexsetup-x64.zip", "miktex")
Write-Output "Setting up MiKTeX"
.\miktex\miktexsetup_standalone.exe --remote-package-repository="$env:CTAN_PACKAGE_ARCHIVE" --local-package-repository=./miktex/download --package-set=essential --quiet download ; Check-Output $?
```

## Notes for Reviewers

Thanks for your time and consideration.

**Comment by jameslamb** [comment]
This was the first request I'd made from this machine to that API in months (possibly years). I suspect the 429s aren't related to traffic from *me* but to the service generally being overloaded?

I just tried exactly one request this morning from a different machine, still got a 429.

Is it possible that `api2.miktex.org` is being DDOS'd? Is there a status page I could look at?

**Comment by edocevoli** [comment]
If you give me a timestamp, I can take a look into the log file.

**Comment by albert-github** [comment]
Looks like since a few days I'm running into a similar problem but based on GitHub Actions (see https://github.com/doxygen/doxygen/actions/runs/3534887466/jobs/5932282689#step:10:13), so I tried a different mirror but to no avail (see https://github.com/doxygen/doxygen/actions/runs/3539704245/jobs/5941917692).

I looked in the documentation of miktex_standalone (https://docs.miktex.org/manual/miktexsetup.html) but I didn't see a possibility to increase the timeout.

**Comment by jameslamb** [comment]
> If you give me a timestamp, I can take a look into the log file.

Sure! I just did the following a few moments ago. Added a unique `User-Agent` in the requests, to hopefully make it easier for you to filter down to my requests in the logs you're looking at.

Today, I'm getting 400s and 404s from those endpoints.

These requests were all issued from my home wifi over the public internet, so no corporate firewall, custom proxying, etc.

### 1. `GET /`

```shell
curl \
    -i \
    -X GET \
    -H "User-Agent: 155473a2-5f4a-4606-ac4f-6bfc763e49b3" \
    https://api2.miktex.org
```

```text
HTTP/1.1 404 Not Found
Server: nginx
Date: Thu, 24 Nov 2022 18:23:31 GMT
Content-Length: 0
Connection: keep-alive
```

### 2. `GET /hello`

```shell
curl \
    -i \
    -X GET \
    -H "User-Agent: 155473a2-5f4a-4606-ac4f-6bfc763e49b3" \
    https://api2.miktex.org/hello
```

```text
HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 24 Nov 2022 18:20:51 GMT
Transfer-Encoding: chunked
Connection: keep-alive

Bad request.
```

### 3. `HEAD /`

```shell
curl \
    -I \
    -H "User-Agent: 155473a2-5f4a-4606-ac4f-6bfc763e49b3" \
    https://api2.miktex.org
```

```text
HTTP/1.1 404 Not Found
Server: nginx
Date: Thu, 24 Nov 2022 18:24:04 GMT
Connection: keep-alive
```

### 4. `HEAD /hello`

```shell
curl \
    -I \
    -H "User-Agent: 155473a2-5f4a-4606-ac4f-6bfc763e49b3" \
    https://api2.miktex.org/hello
```

```text
HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 24 Nov 2022 18:24:47 GMT
Connection: keep-alive
```

**Comment by edocevoli** [comment]
Please note that `https://api2.miktex.org/hello` only supports the `POST` method. And if the posted data is not correct, you will get a 400. That said: it is expected behaviour that your `curl` invocations don't work.

**Comment by jameslamb** [comment]
> it is expected behaviour that your curl invocations don't work

I would be happy to try other requests or provide other information if you'd tell me what to do. I don't know what else to do with the error message `miktexsetup_standalone: Data: code="28", url="https://api2.miktex.org/hello"`. I don't know what that 28 means, or how else to approach debugging this.

**Comment by jameslamb** [comment]
> I need a timestamp in order to figure out what is going wrong

Here are some timestamps where I observed the errors reported in the initial post in this thread. Note that these are the timestamps of `mixtex_standalone.exe` raising a timeout exception, not the timestamps of *requests*. Even with `--verbose`, I'm not able to see when `mixtex_standalone.exe` made individual requests.

```text
Tue, 22 Nov 2022 06:44:37 GMT
Tue, 22 Nov 2022 06:45:10 GMT
Tue, 22 Nov 2022 06:45:25 GMT
Tue, 22 Nov 2022 06:45:25 GMT
Wed, 23 Nov 2022 01:26:16 GMT
Wed, 23 Nov 2022 01:27:01 GMT
Wed, 23 Nov 2022 01:30:48 GMT
Wed, 23 Nov 2022 01:31:28 GMT
Wed, 23 Nov 2022 01:40:34 GMT
Wed, 23 Nov 2022 01:41:36 GMT
Wed, 23 Nov 2022 01:43:06 GMT
Wed, 23 Nov 2022 01:45:43 GMT
Wed, 23 Nov 2022 05:23:05 GMT
Wed, 23 Nov 2022 05:23:52 GMT
Wed, 23 Nov 2022 05:24:16 GMT
Thu, 24 Nov 2022 01:26:19 GMT
Thu, 24 Nov 2022 01:26:20 GMT
Thu, 24 Nov 2022 01:26:50 GMT
Thu, 24 Nov 2022 01:30:05 GMT
Thu, 24 Nov 2022 03:32:57 GMT
Thu, 24 Nov 2022 03:33:40 GMT
Thu, 24 Nov 2022 03:34:59 GMT
Thu, 24 Nov 2022 03:37:23 GMT
Thu, 24 Nov 2022 04:28:12 GMT
Thu, 24 Nov 2022 04:33:18 GMT
Thu, 24 Nov 2022 04:28:25 GMT
Thu, 24 Nov 2022 04:32:47 GMT
```

**Comment by edocevoli** [comment]
- unfortunately, I have no logs older than 23/Nov/2022:15:35:48
- just ran `miktexsetup_standlone` on my machine and observed no error

**Comment by jameslamb** [comment]
> I have no logs older than 23/Nov/2022:15:35:48

I provided 12 timestamps that are more recent than that.

> just ran miktexsetup_standlone on my machine and observed no error

Alright, I've switched to a different LaTeX distribution on Windows for the project whose CI led me to initially open this issue. So sorry, but I'm not planning to spend any more time on this.

Thanks anyway, @edocevoli . Hopefully I was just unlucky, what I observed was something most other users won't face, and that this @albert-github finds a resolution in their project.

**Comment by edocevoli** [comment]
@albert-github I have closed this issue since `api2.miktex.org` is working as expected and I cannot reproduce the `miktexsetup_standalone` issue, i.e., this works for me:

```sh
miktexsetup_standalone.exe --remote-package-repository=https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/ --local-package-repository=./miktex/download --package-set=essential --quiet download
```
