### ISSUE TITLE
Error "The remote package repository is outdated" when trying to auto-install missing packages

### ISSUE THREAD

**Issue by n-kalosha** [MiKTeX/miktex#1229]
The PC had an older version of MikTeX installed, I uninstalled it before downloading and installing the latest basic MikTeX for Windows. Then I installed the cm-super package and updated the packages.

I am trying to compile a file that relies on some missing packages. If automatic installation of missing packages is enabled from a random internet repository, the first missing package is installed, and the installation of the next one errors out with "The remote package repository is outdated. You have to choose another repository". If I pick a specific repository, this error is returned immediately.
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/10086546/miktex-report.txt)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/10086551/pdflatex.log)

**Comment by Erkhyan** [comment]
I’m getting the same error on every repository I select manually.

**Comment by n-kalosha** [comment]
> I’m getting the same error on every repository I select manually.

I came up with a workaround... sort of: make a bat file that calls "pdflatex -interaction=nonstopmode file.tex" in an infinite loop, switch to random repositories, run the bat file and go have some tea. It's going to install one package every time pdflatex is run, so eventually it's going to install all of the missing packages.

**Comment by edocevoli** [comment]
This is usually a temporary problem. Please try again tomorrow.
