### ISSUE TITLE
How is that 'resolved'?

### ISSUE THREAD

**Issue by n-kalosha** [MiKTeX/miktex#1230]
The servers are up. They have the files. The packages get installed one at a time if a random repository is selected in the options. The bug is reproducible. Please figure out what it is and fix it.

        This is usually a temporary problem. Please try again tomorrow.

_Originally posted by @edocevoli in https://github.com/MiKTeX/miktex/issues/1229#issuecomment-1326801788_

**Comment by edocevoli** [comment]
I think this is not too hard to understand:

> Please try again tomorrow.
