### ISSUE TITLE
missing iccu72.dll breaks xelatex.exe

### ISSUE THREAD

**Issue by npapnet** [MiKTeX/miktex#1232]
I just upgraded to the latest version of Miktex and I am getting a message when I am trying to compile with xelatex that "the code execution cannot proceed because icuuc72.dll was not found".

<img width="312" alt="image" src="https://user-images.githubusercontent.com/8252313/203984234-231a2fd2-f8a6-498f-9c2f-16921bc6d2e4.png">

After some check I realised that the icuuc72.dll is part of the International Components of Unicode (ICU), which recently released version 72. I also found out that the "iccuc.dll" (and a few other relevant) comes with "miktex-bin-icu-x64". However, when I downloaded the latest lzma from a random repository, I found version "icuuc60.dll".

I need to know whether this is something other users are also experience? And whether there is a way to resolve this. E.g can I downgrade or select another version of the miktex-xetex?

I want to avoid  upgrade my other production machine because I need to prepare a set of presentations and I can't afford the potential setback. 
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/10092651/miktex-report.txt)

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by TimGreenshaw** [comment]
Same problem following upgrade of MikTeX on 25/11/22.
I can circumvent the problem by using pdfLaTeX instead of XeLaTeX. Might be worth a go if you need results before a fix is available!

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by npapnet** [comment]
Thank you. should I keep this open until I test it tomorrow?

**Comment by TimGreenshaw** [comment]
Many thanks for the rapid fix!


All the best,

                     Tim.
----------------------------------------------------------------------------------------------------------------------
Tim Greenshaw (he/him)
Oliver Lodge Laboratory                           Email ***@***.***
Liverpool University                                  Tel. +44 7973 24 7919
Liverpool L69 7ZE                                      Web http://hep.ph.liv.ac.uk/~green/home.html
ENGLAND
