### ISSUE TITLE
bug in newest luatex/luahbtex 

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#1234]
miktex just updated luatex und luahbtex from development id 7539 to development id 7548.

This version has a bug affecting math. E.g.

~~~~
\input luaotfload.sty
The incorrect variable is $x_1$.  
\end
~~~~

errors with 

~~~~
! \textfont-1 is undefined (character 49).
l.45 The incorrect variable is $x_1$
~~~~

The bug affects also LaTeX see https://tex.stackexchange.com/q/666423/2388.

A work around is to add `\variablefam=-1` and a patch seems to be in the working https://tug.org/pipermail/luatex/2022-November/007774.html

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
