### ISSUE TITLE
MiKTeX Portable, problem with USB Drive letters

### ISSUE THREAD

**Issue by Gaulix3** [MiKTeX/miktex#1235]
Hello,

I have been using MiKTeX portable on USB Drive for a long time. Before, I installed my personal .sty with all oh packages. But since the latest big update (end of MiKTeX 2.9), I'm trying to do this properly using my own TEXMF root directories. The problem is that when I use another computer, it often happens that the letter of the USB key changes. In MiKTeX Console, I notice that all the root directories adapt to the new letter, except my own TEXMF root directories.
I tried changing the path directly to the line "CommonRoots=D:/Logiciels/MiKTeX/texmfs/texmf_local" in the file "miktexstartup.ini" on MiKTeX>texmfs>install>miktex>config like this.
I tested "/Logiciels/...." and "~/Logiciels...". I could see the change in MikTeX Console, but the problem persists...

As a teacher, I change computers very frequently. Is there a solution for the letter to change automatically? Otherwise I'll have to put my .sty files back with the other packages... but that's a shame.

Thank you in advance and I'm sorry if my English is not great...

Gaulix3

**Comment by Gaulix3** [comment]
Hi,

I tested again with "/Logiciels..." (instead of "D:/Logiciels/..." and I can precise something : Its work (texmaker car produce pdf with my own .sty) BUT I can't refreshing FNDB. 
The refreshing FNDB creates the error "internal error" (Something went wrong while refreshing the fnbd. Details : internal error).

So, there is a clean solution?

Thanks in advance

Gaulix3

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
