### ISSUE TITLE
miktexsetup_standalone: Timeout was reached

### ISSUE THREAD

**Issue by simpleprovider** [MiKTeX/miktex#1237]
Hi guys, 

I also get this error for MikTex installation.
`miktexsetup_standalone: Timeout was reached
miktexsetup_standalone: Data: code="28", url="https://api2.miktex.org/hello"
`
I mention that from my laptop is working without any issue, but from Azure VM's in GWC we have this issue. Internet Enhanced Security is stopped.Also firewall is stopped. The problem start happening a few days ago. 

I saw that #1228  was closed and I could not comment anymore there.

Thanks.
Regards,

**Comment by edocevoli** [comment]
Thank you. I don't know what is going wrong and so it is not possible to fix the issue. A future version of the setup utility might provide more trace information.
