### ISSUE TITLE
Miktex silent installation without progress window

### ISSUE THREAD

**Issue by Archanak1** [MiKTeX/miktex#124]
Is there a way to silent install MiKTeX on Windows? I have tried --unattended --quite --silent nothing is working.

for ex - 
"...\basic-miktex-2.9.5872-x64.exe  --auto-install=yes --unattended --shared   --paper-size=Letter --user-install=C:\Program Files "/quite /silent

**Comment by edocevoli** [comment]
Duplicate of #94

**Comment by edocevoli** [comment]
You can use the setup utility for this purpose:

https://docs.miktex.org/manual/miktexsetup.html

**Comment by edocevoli** [comment]
Please read my comment above. You can use the setup utility to perform unattended/silent setups. If your have further questions:
http://lmgtfy.com/?q=miktex+silent+setup

**Comment by Archanak1** [comment]
I tried to use --quiet and I get below error message
![image](https://user-images.githubusercontent.com/38874962/39513791-1912956c-4e13-11e8-91bf-81cee86fc0c2.png)

**Comment by edocevoli** [comment]
That's because the setup wizard doesn't support `--quiet`. You don't want to use the setup wizard. You want to use the setup utility. Seems we're talking ourselves in circles,
