### ISSUE TITLE
miktexsetup_standalone: Timeout was reached (on Github Actions)

### ISSUE THREAD

**Issue by jmarrec** [MiKTeX/miktex#1240]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Following #1228 and #1237, I have the same issue, on github actions.

Can be seen here: https://github.com/NREL/EnergyPlus/actions/runs/3630450126/jobs/6143358066#step:4:63 and with the corresponding workflow file here: https://github.com/NREL/EnergyPlus/blob/fd98fb9eadad2f34f4d9a1c0be308ed8bf05324b/.github/workflows/documentation-windows.yml#L25-L39

I works fine locally on my development machine. Also started failing a few days ago.

@edocevoli May I please suggest to not lock the issue (I'm fine if you want to label it as won't fix though), so we have a place to discuss workarounds, reports, and potential investigations we could all help with without having to recreate fresh issues? This would put less burden on triage for you too. Thank you!

**Comment by jmarrec** [comment]
I running a test on Github Actions for Linux, Mac and Windows: `curl -I https://api2.miktex.org/hello`

The issue is really specific to the Windows runner:

https://github.com/jmarrec/test-Github-Actions/actions/runs/3639795576/jobs/6143631865

Mac and Linux both return this:

```
HTTP/1.1 400 Bad Request
Server: nginx
Date: Wed, 07 Dec 2022 14:25:59 GMT
Connection: keep-alive
```

Windows on the other hand fails with the timeout issue:

```
   0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
curl: (28) Failed to connect to api2.miktex.org port 443 after 21126 ms: Timed out
Error: Process completed with exit code 28.
```

**Comment by jmarrec** [comment]
New test with `curl -v`, not more info: https://github.com/jmarrec/test-Github-Actions/actions/runs/3639934144/jobs/6143941400

**Comment by jmarrec** [comment]
I reported it to Github Actions on https://github.com/actions/runner-images/issues/6712 too.

**Comment by edocevoli** [comment]
Thank you. I am not able to reproduce this with my setup (local Windows machine). That said, I cannot provide a fix.
