### ISSUE TITLE
SSL connect error, checking for updates fail, package installation fail, https://api2.miktex.org/hello inaccessible

### ISSUE THREAD

**Issue by Kadir321** [MiKTeX/miktex#1242]
I cannot check for updates. I cannot install packages.
error: SSL connect error
code:35
URL:  https://api2.miktex.org/hello
Even from the browser, I can not access https://api2.miktex.org/hello
How can I install packages? please help.
Kadir

**Comment by Kadir321** [comment]
error code=35   URL: https://api2.miktex.org/hello

**Comment by edocevoli** [comment]
Duplicate of #1241
