### ISSUE TITLE
miktex console: update error: The requested package is unknown.

### ISSUE THREAD

**Issue by doc-steam** [MiKTeX/miktex#1248]
After Installation miktex console shows an error indicating that "ltxbase" is an unknown package. Subsequently all other action run into internal errors. Unfortunately there is no usable error message available.

GENERAL MIKTEX INFORMATION
ReportDate: 2022-12-14 16:02:43
CurrentVersion: 22.12
SetupDate: 2022-12-14 15:53:00
SetupVersion: 2.9
Configuration: Regular
GitInfo: 2ea1802 / 2022-12-12 11:46:03
OS: Windows 10.0.19044
SharedSetup: no
LinkTargetDirectory: C:\Users\xxx\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: C:\Users\xxx\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\xxx\AppData\Local\MiKTeX\2.9
UserInstall: C:\Users\xxx\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\xxx\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\xxx\AppData\Local\MiKTeX\2.9
Invokers: non-existing/explorer

The following issues were detected:
  1: major issue: Bis jetzt haben Sie noch nicht nach MiKTeX-Updates gesucht.

ERROR DETAILS
Program: miktex-console
Source: Libraries\MiKTeX\PackageManager\PackageDataStore.cpp:403
Error: The requested package is unknown.
Details: 
  name: ltxbase

**Comment by edocevoli** [comment]
I was not able to reproduce this.
