### ISSUE TITLE
TeX capacity exceeded somewhere between MiKTeX 22.8 and 22.12

### ISSUE THREAD

**Issue by aendie** [MiKTeX/miktex#1259]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I just noticed a new "TeX capacity exceeded" error that I never had in the past years up to an including MiKTeX 22.8. 

I performed a new installation on a new laptop (with MiKTeX 22.12) and I was unable to increase the required memory in pdflatex.ini to solve the problem. Previously (before and including MiKTeX 22.8) I used `extra_mem_top = 1000000`. Now (with MiKTeX 22.12) even `extra_mem_top = 9000000` didn't solve the problem.

Just to check .... my PC with MiKTeX 22.8 worked using `extra_mem_top = 1000000`. I then updated all files in MiKTeX Console -> Updates and it failed just a moment later. I only have a tex file + log file for the failed case:

[0sf-v2r-py3.zip](https://github.com/MiKTeX/miktex-packaging/files/10347674/0sf-v2r-py3.zip)

Your support would be very much appreciated.

**P.S.** The attached tex file worked flawless since at least `basic-miktex-2.9.6942-x64.exe` in January 2019

**UPDATE** My old laptop still had MiKTeX 22.8 so here is the tex file + log file for how it should work (with `extra_mem_top = 1000000`):

[withMiKTeX_22.8.zip](https://github.com/MiKTeX/miktex-packaging/files/10352450/withMiKTeX_22.8.zip)

Note that both '.tex' files in the ZIPs above are identical.
It might be helpful to be able to download older versions of MiKTeX... I could have isolated where it broke.

The line `3000000 words of memory out of 3000000` with MiKTeX 22.12 compared to `3063066 words of memory out of 3506648` with MiKTeX 22.8 suggests to me that the `extra_mem_top` statement was somehow ignored.

**Comment by edocevoli** [comment]
I was not able to reproduce your issue. This works for me:

```
echo extra_mem_top = 1000000 > "%APPDATA%\MiKTeX\miktex\config\pdflatex.ini"
initexmf -u
pdflatex "Inc(A4).tex"
```

gives

```
Output written on Inc(A4).pdf (23 pages, 490393 bytes).
Transcript written on Inc(A4).log.
```
