### ISSUE TITLE
Error while make 

### ISSUE THREAD

**Issue by joreb** [MiKTeX/miktex#126]
![screenshot from 2018-05-02 12-47-05](https://user-images.githubusercontent.com/37866574/39510344-0f66533e-4e07-11e8-8a59-44d1b62efc11.png)
 while make error at 96% help cant seems to fix it via reinstall of requisites 

thank you for your time

**Comment by joreb** [comment]
oh sorry my bad
ubuntu bionic
Gcc , g++, Cmake

**Comment by edocevoli** [comment]
Ubuntu 18.04 is not yet supported. We are working on it...
