### ISSUE TITLE
Can't install on OpenSUSE - requires hunspell 1.6

### ISSUE THREAD

**Issue by james-wash** [MiKTeX/miktex#1273]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I've recently started using openSUSE instead of Windows and wanted to install MikTex, but I can't install it from the repository. When I run zypper ve in terminal, it says this:

Problem: nothing provides 'libhunspell-1.6.so.0()(64bit)' needed by the to be installed miktex-22.12-1.x86_64

So, MikTex technically hasn't installed yet because I don't have that library. openSUSE comes with hunspell 1.7 and I haven't seen any way to downgrade to 1.6 or any ways to download hunspell 1.6 in the package manager. A similar problem #301 was reported for Fedora 30 and was fixed, is there a way to fix this as well?

**Comment by edocevoli** [comment]
I think this has been fixed.
