### ISSUE TITLE
MiKTeX generated latexmk.exe fails to be executed as a subprocess on Windows 11

### ISSUE THREAD

**Issue by t4rf9** [MiKTeX/miktex#1278]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

The following JavaScript code fails for MiKTeX generated latexmk.exe but works for TeXLive generated latexmk.exe:
```javascript
var cs = require('cross-spawn');

let command = 'latexmk';
let args = ['-v'];
let options = { cwd: 'c:\\test', detached: true, shell: false };

let proc = cs.spawn(command, args, options);

let output = '';
proc.on('close', function (code) {
    console.log('exit code: ' + code);
    console.log();
    console.log(output);
});
```
Steps to run the code:
- Save them in a file, say `c:\test\main.js`
- Then run from CMD or PowerShell: `node c:\test\main.js` (nodejs version: 19.5.0)

Error information noticed:
- It produces an exit code of 3221226505.
- Nothing comes to stdout and stderr.
- In latexmk.log, nothing is added, which indicates that the execution of latexmk.exe did not succeed.
- No matter what command line arguments are set (changing `let args = ['-v']` to `let args = ['-c']` or `let args = []` or whatever), the above behaviors do not change.

Only after setting `shell: true` or setting `detached: false` for `options` can the script run successfully.

I suppose the problem lies in how MiKTeX generated latexmk.exe, which I can't find in any document.

## Installation Report

```
ReportDate: 2023-02-02 19:52:16
CurrentVersion: 23.1
SetupDate: 2023-01-31 23:12:00
SetupVersion: 22.10
Configuration: Regular
GitInfo: c4b7afe / 2023-01-28 10:49:06
OS: Windows 10.0.22621
SharedSetup: no
LinkTargetDirectory: C:\Users\qwert\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2023-02-02 19:14:21
LastUpdate: 2023-01-31 23:22:08
LastUpdateDb: 2023-02-02 19:14:20
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\qwert\AppData\Roaming\MiKTeX
Root1: C:\Users\qwert\AppData\Local\MiKTeX
Root2: C:\Users\qwert\AppData\Local\Programs\MiKTeX
UserInstall: C:\Users\qwert\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\qwert\AppData\Roaming\MiKTeX
UserData: C:\Users\qwert\AppData\Local\MiKTeX
```

**Comment by edocevoli** [comment]
Thank you. If you run MiKTeX programs in a detached process, you have to enable or turn off the integrated package manager. Otherwise, MiKTeX tries to open the confirmation window (asking for permission to install missing packages) and this fails if the process is detached. Hope this helps.
