### ISSUE TITLE
Starting miktex console as administrator is not detected

### ISSUE THREAD

**Issue by paultjevdh** [MiKTeX/miktex#128]

**Comment by paultjevdh** [comment]
Hi,
I like to start certain programs that need it, directly in administrator mode. When I do this for the miktex console it still needs to be restarted as administrator to activate the options. Apparently the console does not check if it has administrator priviliges. 
Best regards,
Paul

**Comment by edocevoli** [comment]
Thank you for the repost. This has been fixed now.

**Comment by edocevoli** [comment]
Unfortunately, this change seems to have a bad side-effect: if you turn off UAC, then MiKTeX Console is always started elevated. You then don't have the option to run it in user mode, if the auto-admin enhancement is in effect. I will undo this enhancement.

Please note that MiKTeX Console understands the `--admin` option. You can use it to start in admin mode.

**Comment by donovaly** [comment]
> if you turn off UAC, then MiKTeX Console is always started elevated. You then don't have the option to run it in user mode, if the auto-admin enhancement is in effect.

What about this?: MPM is by default start with admin privileges and you see the welcome screen you see currently when starting with user privileges. But this time the screen offers you to restart in user mode. So admin users needing MPM to run only with user privileges could then so this.

**Comment by edocevoli** [comment]
Good idea. Surprisingly it's not easily possible to downgrade a user session. There is no "run as user" option in Windows.

**Comment by edocevoli** [comment]
Actually, command-line utilities like `mpm` and `initexmf` should not present an elevation prompt. This will be fixed (see milestone).

**Comment by donovaly** [comment]
> Surprisingly it's not easily possible to downgrade a user session.

But at the moment MPM does. So why can't bne the default
- start MPM with UAC off
- if gthe admin wants to work in User mode, close MPM, turnung on UAC and restarting MPM

I also wonder who needs only user permissions when being logged in as admin. I mean the sense of an admin account is to administer and therefore the majority of programs start with admin permissions when executed by a user with admin permissions.

**Comment by michelow** [comment]
Just installed the latest x64 version (2.9.6942) and am having the same issue. Does not matter whether I choose run as administrator when starting the MiKTeX Console from the (Win10 Enterprise) start menu, start it normally and then click Restart as Administrator from the console, or try running from the command line using miktex-console-admin.exe --admin. In all cases I get a brief spinning circle on my cursor and then nothing.

Here is what Event Viewer shows (Information event):
1337214775514606972 
   4 
   APPCRASH 
   Not available 
   0 
   miktex-console_admin.exe 
   2.9.6972.0 
   5c558176 
   ucrtbase.dll 
   10.0.16299.522 
   cb7c3790 
   c00000fd 
   000000000000e406 
    
    
   \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3910.tmp.dmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3C9C.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3CAA.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3CCA.tmp.txt 
   C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_miktex-console_a_ecbecb10f7a78e1d42f61c2f583715e54a4a8_5ec3f60d_119640b1 
    
   0 
   5121ae9a-beae-4d85-8427-397b2c3cc871 
   268435456 
   2b9978a6dbc5b836428ebdc0e2f3ad7c
