### ISSUE TITLE
! pdflatex: security risk: running with elevated privileges

### ISSUE THREAD

**Issue by arya18mak** [MiKTeX/miktex#1280]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
! Sorry, but C:\PROGRA~1\MiKTeX\miktex\bin\x64\pdflatex.exe did not succeed.

! The log file hopefully contains the information to get MiKTeX going again:

!   C:\Users\ARYA MAKWANA\AppData\Local\MiKTeX\miktex\log\pdflatex.log

Error: LaTeX failed to compile homework_0.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See homework_0.log for more info.
Execution halted

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
