### ISSUE TITLE
when trying to compile a pdf in r studio: -Error running C:/PROGRA~1/MiKTeX/miktex/bin/x64/pdflatex.exe (exit code -1073740791)

### ISSUE THREAD

**Issue by ciernyd** [MiKTeX/miktex#1284]
when trying to compile a pdf in r studio: -Error running C:/PROGRA~1/MiKTeX/miktex/bin/x64/pdflatex.exe (exit code -1073740791)

any clues what could this be? Tried literally everything,

thanks

error message from R Studio:

Writing to file Testfile.tex
Processing code chunks with options ...
1 : keep.source term verbatim (Testfile.Rnw:6)

You can now run (pdf)latex on 'Testfile.tex'
Running pdflatex.exe on Testfile.tex...failed
Error running C:/PROGRA~1/MiKTeX/miktex/bin/x64/pdflatex.exe (exit code -1073740791)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
