### ISSUE TITLE
MikTex install breaks on installing updates

### ISSUE THREAD

**Issue by RonBOakes** [MiKTeX/miktex#1285]
### Discussed in https://github.com/MiKTeX/miktex/discussions/1279

<div type='discussions-op-text'>

<sup>Originally posted by **wolfhound42** February  4, 2023</sup>
I'm running Windows 10.0.19044.2486.
I deleted my old MikTex installation because it got corrupted. I cleared (I believe) all the entries from the Registry.

I've downloaded and installed a new single-user version. When I try to run the console to update packages, it gets about 8% and then just stops (Task manager shows the process is suspended). When I look in the MikTex\miktex\bin\x64 directory, I see one of the dlls has been renamed: MikTex221000-bzip2.dll.(old).
![image](https://user-images.githubusercontent.com/124470628/216791871-9187d63a-0504-4b84-b92f-ec184622539e.png)

I've reinstalling run the update process several times, but don't know what's happening. Any suggestions for how to fix this would be welcome! Thanks!
</div>

**Comment by edocevoli** [comment]
I was not able to reproduce the problem. What I did:
1. install MiKTeX - OK
2. start the update process - OK
3. check log files: no errors - OK
