### ISSUE TITLE
Evince not working with MikTeX installed

### ISSUE THREAD

**Issue by gnuwin32** [MiKTeX/miktex#129]
The Ubuntu document viewer Evince does not work anymore when MikTeX has been installed on 18.04. Using gdb and strace shows Evince reads all files in /etc/fonts/config.d, but it has no permission to read  09-miktex.conf, which points to /var/lib/miktex-texmf/fontconfig/config/localfonts.conf, From dmesg, it appears that this is because Evince is protected by AppArmor. 
There are two solutions: 
1) Give Evince permission by adding a line "/var/lib/miktex-texmf/fontconfig/config/** r," (without the quotes, but including the comma) to /etc/apparmor.d/local/usr.bin.evince
2) Move localfonts.conf to  /etc/fonts/conf.avail, and link 09-miktex.conf to that file.
It would be preferable if the MikTeX console would take care of this.

**Comment by saeedark** [comment]
Give Evince permission by adding a line "/var/lib/miktex-texmf/fontconfig/config/** r," (without the quotes, but including the comma) to /etc/apparmor.d/local/usr.bin.evince

not working in my case

**Comment by supersonicsensei** [comment]
> The Ubuntu document viewer Evince does not work anymore when MikTeX has been installed on 18.04. Using gdb and strace shows Evince reads all files in /etc/fonts/config.d, but it has no permission to read 09-miktex.conf, which points to /var/lib/miktex-texmf/fontconfig/config/localfonts.conf, From dmesg, it appears that this is because Evince is protected by AppArmor.
> There are two solutions:
> 
> 1. Give Evince permission by adding a line "/var/lib/miktex-texmf/fontconfig/config/** r," (without the quotes, but including the comma) to /etc/apparmor.d/local/usr.bin.evince
> 2. Move localfonts.conf to  /etc/fonts/conf.avail, and link 09-miktex.conf to that file.
>    It would be preferable if the MikTeX console would take care of this.

Hey can elaborate where is this localfonts.conf? and how to link 09-miktex.conf?

**Comment by KeesZeelenberg** [comment]
- localfonts.conf is in /var/lib/miktex-texmf/fontconfig/config
- In a terminal, do: ln -s /var/lib/miktex-texmf/fontconfig/config /etc/fonts/conf.d/09-miktex.conf

**Comment by cprior** [comment]
The apparmor solution worked for me but I also had to reload the service with
`sudo service apparmor reload`.

In `/etc/apparmor.d/local/usr.bin.evince` there was just this above mentioned single line added, nothing else:

```
$ cat /etc/apparmor.d/local/usr.bin.evince
  /var/lib/miktex-texmf/fontconfig/config/** r,
$
```

**Comment by smwright** [comment]
None of these are working for me.
