### ISSUE TITLE
Can't update MikTex

### ISSUE THREAD

**Issue by githubksg241** [MiKTeX/miktex#1291]
Please help, I know the real reason but I can't solve this problem alone.
Here is the information about
code="6", url="https://mirror.datacenter.by/pub/mirrors/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma"
 where in MikTex preferences I have to change the mirror address!

- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
Thank you for the report. Please note that this is not support forum, i.e., this is not the right place to seek help. Sorry.
