### ISSUE TITLE
user data on network drive cannot be handled by log4cxx

### ISSUE THREAD

**Issue by MarkosMitsos** [MiKTeX/miktex#1292]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I install MiKTeX for many years now with user config, install and data pointing to %APPDATA%.
%APPDATA% is defined as the (logical) network drive F:\Windows\AppData that (physically) maps to a share specific to the user
I need the network drive because data on C: are deleted from the server after log-off.

Up until Version 4.0 (pr.ini: date=1607807470 version=7651) that worked fine.
Now, two years later I try to install 5.2.0 (pr.in: date=1675794816 version=8438).

To simplify analysis, I used package-set=essential, at the end I need complete, (s. att.).
[MiKTeXsetup.txt](https://github.com/MiKTeX/miktex/files/10783697/MiKTeXsetup.txt)
[MiKTeXupdate.txt](https://github.com/MiKTeX/miktex/files/10783698/MiKTeXupdate.txt)

After installation in the admin context, admin and user reports look fine (s. att.).
[report_admin.txt](https://github.com/MiKTeX/miktex/files/10783532/report_admin.txt)
[report_user_initial.txt](https://github.com/MiKTeX/miktex/files/10783533/report_user_initial.txt)

Refreshing fndb via
miktex fndb refresh
returns code 0, but the user becomes unusable (s. att.).
[miktex_after_refresh.log](https://github.com/MiKTeX/miktex/files/10783531/miktex_after_refresh.log)
[error_after_refresh.txt](https://github.com/MiKTeX/miktex/files/10783530/error_after_refresh.txt)

After deleting all user data, configuriging fontmaps via
miktex fontmaps configure
produces an explizit error and the user becomes unusable (s. att.).
[miktex_after_configure.log](https://github.com/MiKTeX/miktex/files/10783605/miktex_after_configure.log)
[error_after_configure.txt](https://github.com/MiKTeX/miktex/files/10783603/error_after_configure.txt)

When I install via %LOCALAPPDATA%, so that user data land on C: the initialisation of the user works fine.
That fore I suspect a problem in
miktex-log4cxx-bin-x64-2.9.tar.lzma
either an incompatibilty of the new log4cxx version with network drives or a bug on the MiKTeX side.

To check this I tried:

1) putting the older package (version 4.0) into the sources of 5.2.0, but installation fails, because the signature does not fit.

2) updating the 5.20 version downwards to 4.0 via
C:\temp\Test_essential>miktex --admin packages update --repository C:\temp\Test_essential\packages_log4cxx_4.0 miktex-log4cxx-bin-x64-2.9
Package "miktex-log4cxx-bin-x64-2.9" is up to date.
in the admin context but my request is denied.

3) removing the package (to then install the older one)
C:\temp\Test_essential>miktex --admin packages remove miktex-log4cxx-bin-x64-2.9
Removing package ...

Sorry, but: The executed process did not succeed.
but then the installation as such becomes unusable

Is this a MiKTeX bug?
What can I do to be able to put user data on the network again?

**Comment by edocevoli** [comment]
Thank you for the report. Unfortunately I was not able to reproduce the problem. And since you haven't attach the log files, it is not possible to investigate further.
