### ISSUE TITLE
cannot access full PATH with `lualatex --shell-escape`

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex#1293]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

It seems I can't access the full PATH when compiling with `lualatex --shell-escape` under MiKTeX on Windows 10. Rather I can only access `...\miktex\bin\x64\`. I've confirmed this issue on two different computers with Windows 10. This problem does not occur when using pdflatex or xelatex, nor does it occur with lualatex under texlive on Ubuntu.

To reproduce, compare the tmp.txt from compiling
```latex
\documentclass{article}
\usepackage{shellesc}

\begin{document}

\makeatletter 
\ShellEscape{echo \@percentchar PATH\@percentchar > tmp.txt}
\makeatother

\end{document}
```
with `lualatex --shell-escape` versus `pdflatex --shell-escape`. The former produces
```
C:\Users\saint\AppData\Local\Programs\MiKTeX\miktex\bin\x64\
```
while the latter gives my full PATH:
```
C:\Users\saint\AppData\Roaming\ActiveState\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Users\saint\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\saint\AppData\Local\Programs\Python\Python311\;C:\Users\saint\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\saint\AppData\Local\Programs\Python\Python310\;C:\Users\saint\AppData\Local\activestate\StateTool\release\bin;C:\Users\saint\AppData\Local\activestate\cache\bin;C:\Users\saint\AppData\Local\ActiveState\StateTool\release;C:\Users\saint\AppData\Local\Microsoft\WindowsApps;C:\Users\saint\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Users\saint\AppData\Local\GitHubDesktop\bin
```
Here is my miktex report: [miktex-report.txt](https://github.com/MiKTeX/miktex/files/10796777/miktex-report.txt)

**Comment by edocevoli** [comment]
It works for me.

[test.log](https://github.com/MiKTeX/miktex/files/10797267/test.log)
[tmp.txt](https://github.com/MiKTeX/miktex/files/10797268/tmp.txt)
