### ISSUE TITLE
Cannot install Miktek on Windows

### ISSUE THREAD

**Issue by LeaDeleris** [MiKTeX/miktex#13]
I have Windows 7 (64-bit) and have downloaded 
basic-miktex-2.9.6361-x64.exe today

When I run it, it does not complete the installation.
Below is the end of the logfile 

------------------------

extracting files from zapfding.cab...
extracting files from zerohyph.tar.lzma...
updating package definition directory ("C:\Program Files\MiKTeX 2.9\tpm\packages")...
installed 3127 package definition files
visiting repository C:\Users\IBM_AD~1\AppData\Local\Temp\mik40008...
repository type: local package repository
loading lightweight database...
"C:\Program Files\MiKTeX 2.9\miktex/bin/x64\initexmf.exe" --common-install="C:\Program Files\MiKTeX 2.9" --set-config-value=[Core]SharedSetup=1 --admin --log-file="C:\Program Files\MiKTeX 2.9\miktex/config\uninst.log" --verbose:
log4cxx: No appender could be found for logger (initexmf).
log4cxx: Please initialize the log4cxx system properly.

Sorry, but "MiKTeX Configuration Utility" did not succeed.

You may want to visit the MiKTeX project page, if you need help.

An error occurred:
  source file: Libraries\MiKTeX\Core\Process\Process.cpp
  source line: 159
  message: The executed process did not succeed.
  info: fileName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\initexmf.exe", arguments="--common-install="C:\Program Files\MiKTeX 2.9" --set-config-value=[Core]SharedSetup=1 --admin --log-file="C:\Program Files\MiKTeX 2.9\miktex/config\uninst.log" --verbose", exitCode="1"

------

**Comment by edocevoli** [comment]
Thank you. Because I was not able to reproduce the problem: Please collect all relevant log files. You should find the log files here:

    C:\ProgramData\MiKTeX\2.9\miktex\log

**Comment by LeaDeleris** [comment]
Dear  Christian,
 
Attached is the log file.
Also Miktek shows up in the program menu but when I try to do an update, I get the following error message:

 
And when I go for Settings I get this one

 
 
(If that's helpful)
 
Léa
 
Léa DelerisResearch Staff Member
Manager of the Decision Science, AI & NLP GroupAI Lead for IBM Research - Ireland
IBM Research AI
 
http://researcher.ibm.com/person/ie-lea.deleris
 
IBM Research - Ireland LabDamastown Industrial EstateMulhuddart, Dublin 15IBM Ireland Limited registered in Ireland under company number 16226.Registered Office: IBM House, Shelbourne Rd., Ballsbridge, Dublin 4 
 
 
----- Original message -----From: Christian Schenk <notifications@github.com>To: MiKTeX/miktex <miktex@noreply.github.com>Cc: LeaDeleris <lea.deleris@ie.ibm.com>, Author <author@noreply.github.com>Subject: Re: [MiKTeX/miktex] Cannot install Miktek on Windows (#13)Date: Fri, Sep 29, 2017 12:07 PM 
Thank you. Because I was not able to reproduce the problem: Please collect all relevant log files. You should find the log files here:
C:\ProgramData\MiKTeX\2.9\miktex\log

**Comment by edocevoli** [comment]
Léa, please note that attachments cannot be sent by email. Please visit the issue page.

**Comment by LeaDeleris** [comment]
[setup-2017-09-29-11-42.log](https://github.com/MiKTeX/miktex/files/1346473/setup-2017-09-29-11-42.log)

**Comment by edocevoli** [comment]
Thank you, but I need the other log files too.

**Comment by LeaDeleris** [comment]
The only other file that I have is in 
C:\Program Files\MiKTeX 2.9\miktex\config\win
and is called log4cxx.win.xml 

content is
-------------------------



<?xml version="1.0" encoding="UTF-8" ?>

<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">

  <appender name="RollingLogFile" class="org.apache.log4j.RollingFileAppender">
    <param name="file" value="${MIKTEX_LOG_DIR}/${MIKTEX_LOG_NAME}.log" />
    <param name="append" value="true" />
    <param name="MaxFileSize" value="1MB" />
    <param name="MaxBackupIndex" value="10" />
    <param name="Threshold" value="INFO" />
    <layout class="org.apache.log4j.PatternLayout">
      <param name="ConversionPattern" value="%d{yyyy-MM-dd HH:mm:ss,SSSZ} %-5p %c{2} - %m%n" />
    </layout>
  </appender>

  <appender name="DebugView" class="org.apache.log4j.OutputDebugStringAppender">
    <param name="Threshold" value="TRACE" />
    <layout class="org.apache.log4j.PatternLayout">
      <param name="ConversionPattern" value="%-5p %c{2} - %m%n" />
    </layout>
  </appender>

  <root>
    <level value="INFO" />
    <appender-ref ref="RollingLogFile" />
    <appender-ref ref="DebugView" />
  </root>

  <logger name="trace">
    <level value="TRACE" />
  </logger>

</log4j:configuration>
---------------

I cannot find any other log files.

![capture](https://user-images.githubusercontent.com/17316166/31048239-33a289dc-a611-11e7-91e2-4261a1e4f49c.PNG)

**Comment by edocevoli** [comment]
Sorry, here is the location of the log files:

    C:\ProgramData\MiKTeX\2.9\miktex\log

This directory should exist and it should contain some log files.

**Comment by LeaDeleris** [comment]
Indeed. Sorry it took me time to find that. The folder is hidden it seems.
[fc-cache_admin.log](https://github.com/MiKTeX/miktex/files/1347012/fc-cache_admin.log)
[mkfntmap_admin.log](https://github.com/MiKTeX/miktex/files/1347013/mkfntmap_admin.log)

**Comment by LeaDeleris** [comment]
Also, When I try to run an update (through the Windows menu that was installed despite the installation being unsuccessful) I get the following message:
![capture](https://user-images.githubusercontent.com/17316166/31118848-ce5243e8-a826-11e7-8def-c7b342ee6f1e.PNG)
