### ISSUE TITLE
After update biber does no longer correctly process multi-letter initials

### ISSUE THREAD

**Issue by CraLam** [MiKTeX/miktex#130]
After I have updated to the latest version of MikTeX, the entries of my bib-file that contain authors with  initials that consist of multiple characters are no longer processed correctly. 
pdflatex generates an error  that boils down to the fact that a superfluous } is generated in the .bbl file.
Compiling the attached .tex file should replicate  the problem.
[test.txt](https://github.com/MiKTeX/miktex/files/2001204/test.txt)

**Comment by edocevoli** [comment]
This is not a MiKTeX-specific bug and so cannot be fixed by me.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).

**Comment by CraLam** [comment]
Thanks for your prompt response. How do I make sure the maintainers get aware of this bug?

**Comment by moewew** [comment]
This is a known issue, but it can probably not be fixed, see https://github.com/plk/biber/issues/215
