### ISSUE TITLE
I can't solve the TeX capacity exceeded fault, sorry [main memory size=3000000], after jan 2022 update.

### ISSUE THREAD

**Issue by JetherReis** [MiKTeX/miktex#1303]
### Discussed in https://github.com/MiKTeX/miktex/discussions/1029

<div type='discussions-op-text'>

<sup>Originally posted by **JetherReis** January 19, 2022</sup>
In the last MikTex update I made, the TeXnicCenter program that I use together with MikTex stopped working, and after several attempts, including deletion and reinstallation of both programs, the program started working again, however many of my files have many figures generated by packages based on Tikz, the error "**TeX capacity exceeded, sorry [main memory size=3000000]**" appeared again.

In previous times, whenever this error occurred I used the following procedure from the DOS command console:

initexmf --edit-config-file=latex

Including the following lines in the file:

main_memory=50000000
hash_extra=2150000
pool_size=4250000

After saving the file, use the command:

initexmf --dump=latex

Repeating these commands for --edit-config-file=pdflatex and --edit-config-file=xelatex.

But this time, I got the following result:

"Microsoft Windows [version 10.0.19042.1415]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Jether>initexmf --edit-config-file=latex

C:\Users\Jether>initexmf --edit-config-file=pdflatex

C:\Users\Jether>initexmf --edit-config-file=xelatex

C:\Users\Jether>initexmf --dump=latex

Sorry, but "MiKTeX Configuration Utility" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:"

As I have exhausted my resources, I would like to know if someone can help me solve this problem.</div>

**Comment by edocevoli** [comment]
Thank you. Please check the log files. This should give you some indications and you should to be able to fix the issue.

**Comment by ColMaxSchwarz** [comment]
Hi all, 
I'm afraid, I have the same or a similar issue. 
My latex files had been compiling on an older MikTex version without any issue after I have increased the main memory to 20000000. 

I cannot increase the memory anymore by 

initexmf --edit-config-file=latex
initexmf --dump=latex

The log files says the following: 
2023-04-27 19:06:41,682+0200 ERROR initexmf - sub-process error output has been saved to 'C:\Users\Colin\AppData\Local\MiKTeX\miktex\log\miktex_2023-04-27-190641.out'
2023-04-27 19:06:41,682+0200 FATAL initexmf - The executed process did not succeed.
2023-04-27 19:06:41,682+0200 FATAL initexmf - Info: fileName="C:\Program Files\MiKTeX\miktex\bin\x64\miktex-makefmt.exe", exitCode="1"
2023-04-27 19:06:41,682+0200 FATAL initexmf - Source: 
2023-04-27 19:06:41,682+0200 FATAL initexmf - Line: 0
2023-04-27 19:06:41,683+0200 INFO  initexmf - this process (14320) finishes with exit code 1

The second log-file contains: 
Building format 'pdflatex' with engine 'pdftex'...

Sorry, but: The executed process did not succeed.
                           


Is there any advise how to get this running once again?

Best regards
Colin
