### ISSUE TITLE
tftopl and MikTeX : information for characters shifted by one?

### ISSUE THREAD

**Issue by Papy93-23** [MiKTeX/miktex#1305]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I have run TFtoPL from MikTeX 23.1 on the TFM file  "cmr10.tfm"  and I got
strange results, it looks like character names are shifted by one,
for example:

(CHARACTER O 100
   (CHARWD R 0.876988)
   (CHARHT R 0.694445)
   )
(CHARACTER C @
   (CHARWD R 0.84326)
   (CHARHT R 0.683334)
   (COMMENT
      (KRN C s R -0.030755)
      (KRN C B R -0.030755)
      (KRN C N R -0.030755)
      (KRN C F R -0.030755)
      (KRN C T R -0.030755)
      (KRN C P R -0.030755)
      (KRN C S R -0.092263)
      (KRN C X R -0.092263)
      (KRN C U R -0.123016)
      (KRN C V R -0.123016)
      )
   )
(CHARACTER C A
   (CHARWD R 0.798616)
   (CHARHT R 0.683334)
   )

as far as I know,  (CHARACTER O 100
is already '@';
and further down, 'm' is not wider then 'l' :

(CHARACTER C l
   (CHARWD R 0.938497)
   (CHARHT R 0.430555)
   (COMMENT
      (KRN C s R -0.030755)
      (KRN C t R -0.030755)
      (KRN C a R -0.030755)
      (KRN C x R -0.030755)
      (KRN C u R -0.030755)
      (KRN C v R -0.030755)
      )
   )
(CHARACTER C m
   (CHARWD R 0.630956)
   (CHARHT R 0.430555)
   (COMMENT
      (KRN C s R -0.030755)
      (KRN C t R -0.030755)
      (KRN C a R -0.030755)
      (KRN C x R -0.030755)
      (KRN C u R -0.030755)
      (KRN C v R -0.030755)
      )
   )

It looks that the information for 'm' is given in  "(CHARACTER C l "

Has anyone seen this already?

Bernie.

**Comment by Papy93-23** [comment]
Actually I run TFtoPL on both  "cmr10"  and  "cmr7",
and the figures I gave are with  "cmr7".
With  "cmr10" I got similar problems.

**Comment by u-fischer** [comment]
I can confirm the bug. 

I ran `tftopl cmr7.tfm cmr7.pl` and in various places in the `.pl`  there are character shifts. It already starts at the begin:

~~~~
(FAMILY BLQ)
(FACE O 360)
(CODINGSCHEME SDW SDWS)
~~~~

In TeXlive  you would get

~~~~
(FAMILY CMR)
(FACE O 360)
(CODINGSCHEME TEX TEXT)
~~~~

**Comment by edocevoli** [comment]
This has been fixed
