### ISSUE TITLE
Installer hangs

### ISSUE THREAD

**Issue by dpwilt** [MiKTeX/miktex#1308]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Thanks for a great piece of software!  I tried to update my Windows 10 MikTeX installation today and had the installer hang at "Update in progress... 12% (installing: miktex-config-2.9)".  I killed the program, did a complete uninstall including removing registry entries, then tried a fresh install.  It installed OK but asked me to update (it also issued an error message, something to do with MiKTeX can't start).  Again, it hung at the same point "Update in progress... 8% (installing: miktex-config-2.9)".  Windows did a massive update for security vulnerabilities today - could that be related?

Many thanks again, Dan

**Comment by edocevoli** [comment]
Thank you. I was not able to reproduce the bug with the given info. Therefore it is not possible to provide a fix.

**Comment by dpwilt** [comment]
My apologies!  It appears it is a problem with an overly aggressive virus scanner (Acronis).  After temporarily disabling the scanner I was able to install/update without issues.  Best regards, Dan
