### ISSUE TITLE
package-set option fails with MiKTeX 22.10 Basic executable

### ISSUE THREAD

**Issue by mverouden** [MiKTeX/miktex#1309]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hi Chistian,

While packaging MiKTeX 22.10 for the Software Center at Wageningen University & Research I came across some unexpected behavior. My `setupwiz.opt` file used to contain the following options:
```
--auto-install=yes ^
--package-set=basic ^
--paper-size=A4 ^
--shared ^
--unattended ^
--user-install="C:\ProgramData\MiKTeX"
```
However, with `basic-miktex-22.10-x64.exe` the option `--package-set=basic ^` fails and just displays the available options. I do not know, whether you are aware of this. I have thoroughly searched open and closed issues.

In case you are aware of it, sorry to have bothered you with the above.

As always with kindest regards and lots of thanks and appreciation for your work,
Maikel

**Comment by edocevoli** [comment]
I can confirm that this option has been removed. I have to investigate whether this happened by accident.

**Comment by mverouden** [comment]
Hi Christian,

Hereby, the confirmation that in `basic-miktex-23.4-x64.exe` the problem has been resolved. I will use this version for the Software Center of Wageningen University & Research.

Thanks a lot for fixing it so quickly!

Regards,
Maikel
