### ISSUE TITLE
pdflatex can't work regularly when compiling the acm template

### ISSUE THREAD

**Issue by peiyaoooo** [MiKTeX/miktex#131]
when I compile the ACM Conference template tex , the error exists that pdflatex.exe stops working.
According the suggestion from the Internet, I update the mikTex. But it doesn't work， either.

This is the error report:
> 应用程序时间戳:	4e9c327a
  故障模块名称:	MiKTeX209-core.dll
  故障模块版本:	2.9.4389.0
  故障模块时间戳:	4f16f9cd
  异常代码:	c0000005
  异常偏移:	0008aa14
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

and tex.log cuts off at some line.But I can't find where is the error.

Can someone help me? Thank you very much!

**Comment by edocevoli** [comment]
I cannot reproduce this. What I did:

1. Get `prepare.tex` and `body.eps` (see [testcase.zip](https://github.com/MiKTeX/miktex/files/2005146/testcase.zip))
2. Run `pdflatex prepare.tex`
3. Enjoy `prepare.pdf`
