### ISSUE TITLE
Failing to update miktex-config-2.9

### ISSUE THREAD

**Issue by Relevartt** [MiKTeX/miktex#1312]
Every time I try to update MiKTeX from a fresh install, with or without administrator privileges, it gets suspended at the miktex-config-2.9 point. This has been going on for months and I really need to use latex now so I will unfortunately have to find another way.
<img width="797" alt="Screenshot 2023-04-08 100841" src="https://user-images.githubusercontent.com/97558206/230711154-e0ca96b3-158d-4151-85f0-fd7a79ea239a.png">
<img width="224" alt="Screenshot 2023-04-08 100910" src="https://user-images.githubusercontent.com/97558206/230711158-a6a8fe8c-fab4-42ee-b6f1-7080b44fddc3.png">

[miktex installing log.txt](https://github.com/MiKTeX/miktex/files/11182807/miktex.installing.log.txt)

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.
You can try it again tomorrow. If the problem still exists: collect log files, screenshots etc.
Please read the guidelines:
https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md

Reminder: **Your job is to enable me to reproduce the problem.**
