### ISSUE TITLE
Please add some instruction on hyphenation pattern installation

### ISSUE THREAD

**Issue by CastleStar14654** [MiKTeX/miktex#1313]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

The Linux or macOS "Just enough TeX" version of MiKTeX do not come with the hyphenation packages (e.g. `knuth-lib` for US English or `hyph-utf8` for a lot of other languages), and therefore the hyphenation would not work out-of-box.

There have been a many *nix users who want to use MiKTeX struggling on this, including [this TeX - LaTeX Stack Exchange post](https://tex.stackexchange.com/questions/587012/hyphenation-never-working), #605, and me. The solution is quite simple, however: just installing the corresponding package as listed in **Settings > Languages** of MiKTeX Console (and then `initexmf --mklangs`, though this step seems unnecessary, but I have not tried skipping it), as pointed out in [another TeX - LaTeX Stack Exchange post](https://tex.stackexchange.com/questions/452572/miktex-hyphenation-not-working-on-macos-there-is-no-hyphenation).

I wonder whether you could add a one-line instruction of this in the documentation or at the download page for Linux and macOS.

**Comment by ptrindade96** [comment]
Hi! Just had the same problem on Ubuntu. I was going crazy trying to figure it out. I have a working installation on another computer, but I installed it long ago and didn't remember what I did. This solution worked for me, I would recommend following @CastleStar14654's suggestion and either adding a note to the installation instructions or make this packages part of the core set of packages installed when doing the setup. Best regards!

**Comment by SoongJr** [comment]
This, a hundred times this! Had to rage-quit one day and come back after a couple days with a fresh attempt at googling my issue and finally found an article that mentioned MiKTeX not coming with hyphen patterns at all ☹ (I'm using the `miktex/miktex:essential` docker image, and I do consider hyphenation essential... But OK 😆)

Thank you for the pointers, even though the issue has been ignored.

Maybe MiKTeX should complain that language hasn't been properly configured, the same way it'll complain if packages have never been updated.

Or yeah, document the need to do this, e.g. [specifically for the docker image](https://miktex.org/howto/miktex-docker)
