### ISSUE TITLE
multicol with arabic works fine in texlive  but broke in some miktex

### ISSUE THREAD

**Issue by hpvd** [MiKTeX/miktex#1315]
- [x ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
  
  
When combining multicol with arabic, I got a broken document, after the second run.
Reporting this to babel see https://github.com/latex3/babel/issues/233
because there were some similar problems already solved with a babel update (https://github.com/latex3/babel/issues/228)
@jbezos told me he could not reproduce it with Texlive.
@u-fischer couldn't reproduce it in her Miktex installation either,
but @jbezos hinted there may be a problem in Miktex:

> perhaps there is misconfiguration in MikTeX (which is loading a bblopts.cfg almost 20 years old!).

Since I have this problem
- on two different windows machines (W10 and W11),
- with latest miktex and
- using texworks and
- could not remember about having done any customizations in Miktex,
 
I would like to ask if you may have a look/have an idea about this?

The Example Code:

```
\listfiles
\documentclass[a4paper]{book}

\usepackage{multicol}
\usepackage{lipsum}
%\usepackage{linebreaker} %was first seen with linebreakre enabeled
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{english}
\babelprovide[import]{arabic}

\babelfont[english]{rm}{arial}
\babelfont[arabic]{rm}{Amiri}


\begin{document}

\begin{multicols}{3}
    \lipsum[1-6]

    \begin{otherlanguage}{arabic}
        لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
        نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
        يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
        السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
        الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
        ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.\par
    \end{otherlanguage}
\end{multicols}

\end{document}
```

The Result:
![2023-04-08_20h47_42](https://user-images.githubusercontent.com/5681880/231105418-3ce98ba6-9d5d-4675-8d8e-7f797da0704b.png)

The Logfile:
can be found here https://github.com/latex3/babel/issues/233#issuecomment-1500959299

**Comment by hpvd** [comment]
maybe just
- a quick check if it works for you
- a comment on jbezos comment regarding `MikTeX  is loading a bblopts.cfg almost 20 years old`
would be sufficient,

If both is fine on your side, I would first try a complete fresh installation on my machine.

Many thanks!

**Comment by u-fischer** [comment]
As said, I can't reproduce it. The bblopts.cfg is not a problem: I load since many times an empty local version, but even without that I can't reproduce the problem. My system loads zerohyph.tex as patterns for arabic, but disabling that doesn't break anything.

I can only think that you perhaps changed linebreaker, so deinstall and reinstall the package.

**Comment by hpvd** [comment]
thanks for feedback. I can reproduce it without linebreaker.
After the first run it looks fine. The second run breaks it.
If par in the arabic part is included, the arabic part looks broken
without par the arabic part "disappear" (but can be c and p from acrobat)
![2023-04-11_11h43_28](https://user-images.githubusercontent.com/5681880/231122233-2995aa39-525c-47b1-83ec-055d0e7e069c.png)



ok seems to be broken on my site only.

**Comment by hpvd** [comment]
thanks @u-fischer 
You pointed in the right direction...

the result is strange:
- without linebreaker there is only one sign visible
- with linebreaker everything is visible

independent of the number of runs
see
![2023-04-11_13h34_41](https://user-images.githubusercontent.com/5681880/231151417-516b5d88-6aa3-459f-ad48-c60529f07d6c.png)

**Comment by hpvd** [comment]
code:
```
\listfiles
\documentclass[a4paper]{book}

\usepackage{multicol}
\usepackage{lipsum}
\usepackage{linebreaker}
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{english}
\babelprovide[import]{arabic}

\babelfont[english]{rm}{texgyreheros}
\babelfont[arabic]{rm}{Amiri}


\begin{document}

\begin{multicols}{3}
    \lipsum[1-6]

    \begin{otherlanguage}{arabic}
        لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
        نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
        يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
        السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
        الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
        ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.
    \end{otherlanguage}
\end{multicols}

\end{document}
```

**Comment by hpvd** [comment]
only at the very beginning of arabic it still looks a little wired...
But this looks like another topic...
