### ISSUE TITLE
Please considering adding support for Apache Log4cxx 1.0.0

### ISSUE THREAD

**Issue by popjdh** [MiKTeX/miktex#1316]
The release version of Apache Log4cxx has been updated from 0.13.0 to 1.0.0 . Compiling with a new version of log4cxx in a Linux environment will result in compilation errors. This is very unfriendly to archLinux that adopts rolling updates.

**Comment by zhmylove** [comment]
Agree, we have to introduce dirty hack in order to link against new version on log4cxx

**Comment by zhmylove** [comment]
@edocevoli It'd be nice if you pay some attention here. thanks :)

**Comment by edocevoli** [comment]
This has been done.
