### ISSUE TITLE
On Linux several executables are installed as a copy of `/usr/bin/miktex` instead of a symlink

### ISSUE THREAD

**Issue by CastleStar14654** [MiKTeX/miktex#1317]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

On Linux, four executables in `~/bin`, `mktexlsr`, `texhash`, `texlinks`, and `updmap`, are installed as a copy of `/usr/bin/miktex`, instead of a symlink, **and is not executable by default due to copying**. I wonder if it is by design or by mistake, because I tried manually replacing them as symlinks of  `/usr/bin/miktex`, and they work fine.

**Comment by edocevoli** [comment]
done

**Comment by CastleStar14654** [comment]
Cheers

**Comment by CastleStar14654** [comment]
@edocevoli I find that your solution is to make the copy process copy the executive bit as well. However, since these four executables are still installed as a copy, when I update the MiKTeX using package manager like `apt`, other installed symbolic links are updated since they are only links, ***but these four copied executables won't.*** They will keep being the original version.
