### ISSUE TITLE
Windows Download no longer possible

### ISSUE THREAD

**Issue by Juggern4ut** [MiKTeX/miktex#1318]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

It appears that the Links to download MikTex for Windows no longer work and redirect to a 404 Page.

**Comment by manuelfuenmayor** [comment]
Confirmed. I'm having the same issue.

**Comment by jxc876** [comment]
The link on the main webpage also appears broken for me, 

`basic-miktex-23.4-x64.exe` seems unreachable, for now I was able to get this one:

* https://ctan.math.utah.edu/ctan/tex-archive/systems/win32/miktex/setup/windows-x64/basic-miktex-22.10-x64.exe

**Comment by Juggern4ut** [comment]
Workaround: If you need a version now but don't want to rely on a different and maybe suspicious page, you can also use the wayback machine.

**Comment by ldtr-dev** [comment]
Yes, I can't download MikTex for Windows neither

**Comment by alexn-s** [comment]
having the same issue.

**Comment by magneticflux-** [comment]
Some mirrors are working now:
- https://mirrors.mit.edu/CTAN/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe
- https://ctan.math.illinois.edu/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe
- https://mirror.math.princeton.edu/pub/CTAN/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe
- https://mirrors.rit.edu/CTAN/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe

**Comment by rashil2000** [comment]
Updated the manifests with the mit.edu mirrors: https://github.com/ScoopInstaller/Main/commit/cecb4a688b64a880a0f8330f6fbbea55aa5e19db

**Comment by mverouden** [comment]
Download has propagated on the CTAN Mirrors and is available now. Try [https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe](https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe) or pick another mirror on https://ctan.org/mirrors
