### ISSUE TITLE
ltxmisc does not contain varwidth and parskip anymore

### ISSUE THREAD

**Issue by thorade** [MiKTeX/miktex#132]
Not sure if this is the right place to report, apologies if not (and where would the right place be?).

After installing MiKTeX on a fresh Windows 10 and compiling a big document for the first time, a lot of packages are missing, among them varwidth.sty and parskip.sty. MiKTeX then installs ltxmisc, probably because they were once included there.
The fix was to manually install varwidth and parskip.

**Comment by edocevoli** [comment]
You are right: `ltxmisc`, `varwidth` and `parskip` are packages which can be installed with the help of the package manager.

**Comment by thorade** [comment]
Not sure if I understand your answer. It seems the dependencies are wrong and should be fixed!?

It works for me now, but the next person will run into the same issue: once a document uses parskip MiKTeX will install ltxmisc, but it should install parskip.

**Comment by edocevoli** [comment]
Which dependencies? Packages will be installed on-the-fly, if they are missing.

**Comment by thorade** [comment]
Yes, but if parskip is missing MiKTeX is installing ltxmisc.
If varwidth is missing, MiKTex is installing ltxmisc.
Not sure why, or if it is my setup, but that is what happened.

**Comment by edocevoli** [comment]
Seems you are working with an out-of-date package database.

**Comment by thorade** [comment]
I updated the package database, and I switched the remote repositores, but the same happened.
Still, if this is not reproducible anywhere, it was probably my setup.
