### ISSUE TITLE
Issue with downloading MikTex

### ISSUE THREAD

**Issue by aasir22** [MiKTeX/miktex#1322]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I tried to download MikTex but it shows The requested URL /ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe was not found on this server. How can I download the  MikTex

**Comment by cscnk52** [comment]
Same as #1318

**Comment by mverouden** [comment]
Download has propagated on the CTAN Mirrors and is available now. Try [https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe](https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe)
