### ISSUE TITLE
Public key for installation has expired

### ISSUE THREAD

**Issue by sbs-jms** [MiKTeX/miktex#1327]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

`gpg --fingerprint 277A7293F59E4889`

> pub   rsa2048 2017-06-23 [SC] [expired: 2023-04-29]
> D6BC 2435 65B2 087B C3F8  97C9 277A 7293 F59E 4889
> uid           [ expired] MiKTeX Packager <packager@miktex.org>

**Comment by edocevoli** [comment]
The key has been renewed
