### ISSUE TITLE
MiKTeX 23.4 fails to add packages on-the-fly

### ISSUE THREAD

**Issue by mverouden** [MiKTeX/miktex#1329]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Dear Christian,

While testing the packaged version of MiKTeX 23.4 for the Software Center of Wageningen University & Research I came across a problem. After installation MiKTeX 23.4 fails to add packages on-the-fly. I have tested this using TeXstudio with a regular LaTeX file, as well as from RStudio while making a pdf from R Markdown (which requires a TeX installation).

I was using a clean installation of Windows 10, to make sure there were no other interferences. To make sure the problem lies in MiKTeX 23.4, I have installed MiKTeX 22.10. MiKTeX 22.10 does not suffer from this problem. I worked around issue  #1309, which you fixed in version 23.4, by excluding `--package-set=basic ^` from the `setupwiz.opt` file in order to install MiKTeX 22.10.

With kindest regards and appreciation for your work and MiKTeX,
Maikel

**Comment by edocevoli** [comment]
I was not able to reproduce this with the given info.
