### ISSUE TITLE
eptex missing `\suppress...` primitives

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex#1333]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

MiKTeX's version of eptex is up to date, however it is not recognizing the somewhat recently added primitives `\suppresslongerror`, `\suppressoutererror`, and `\suppressmathparerror`. Compiling the following with eptex gives "undefined" for each.
```tex
\meaning\suppresslongerror
\meaning\suppressoutererror
\meaning\suppressmathparerror

\bye
```
The same document with TeXlive's eptex shows their names as expected for primitives. This file should contain their code: [miktex/Programs/TeXAndFriends/texjp/eptex/source/suppresserrors.ch](https://github.com/MiKTeX/miktex/blob/next/Programs/TeXAndFriends/texjp/eptex/source/suppresserrors.ch)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
