### ISSUE TITLE
Windows Installer Required for 23.5

### ISSUE THREAD

**Issue by cbrieger** [MiKTeX/miktex#1339]
- [ X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

#1338 Was just closed with the resolution that the software can be updated once installed. This is not an option for instances in a corporate environment that require installers to go through packaging. We are unable to accept updates via the software itself. When will a windows installer for 23.5 be made available in order to address the security vulnerabilities with earlier releases?

**Comment by edocevoli** [comment]
> When will a windows installer for 23.5 be made available in order to address the security vulnerabilities with earlier releases?

This hasn't been decided yet. I would say this year. But please hold your breath 😃

(I am glad to answer questions. But please note that this is not a support forum. The main theme is: bugs)
