### ISSUE TITLE
MiKTeX setup fails with API error 126

### ISSUE THREAD

**Issue by TobiBS** [MiKTeX/miktex#134]
During installation miktexsetup.exe fails with:

```
Windows API error 126: The specified module could not be found.
Data: dllName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core.dll"
```

I found nothing on the web, what could solve this issue or where its from, only others having the question, no solution:

- https://sourceforge.net/p/miktex/mailman/message/12310714/
- http://miktex.10937.n7.nabble.com/Update-and-Install-Problem-API-Error-126-td1380.html

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.

**Comment by TobiBS** [comment]
What information do you need? The problem happens during installation as described at https://miktex.org/howto/deploy-miktex

**Comment by edocevoli** [comment]
I don't know what information I need. If you cannot help me to reproduce the bug, I cannot fix it.

You might want to take a look here:
https://www.google.de/search?q=How+to+Write+a+Bug+Report

**Comment by edocevoli** [comment]
Please note that there are two variants of `miktexsetup.exe`:

1. the integrated version installed with MiKTeX
2. the stand-alone version available: http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x64/miktexsetup.zip

You have to use the stand-alone variant.

**Comment by TobiBS** [comment]
OK, I tried to grab all information that I thought is useful:

MiKTeXsetup version used is: `MiKTeX Setup Utility (MiKTeX 2.9.6300 64-bit)`
It is used in conjunction with repository version `6457` via a script written in PowerShell. Windows version used is `Microsoft Windows NT 10.0.15063.0`

The command used for installation is `"$directory\Miktex\miktexsetup.exe" --quiet --shared --modify-path --local-package-repository="$directory\Miktex\Packages" --package-set=complete install`

MiKTeXsetup copies all files as expected, but before `%PATH%` is populated and before taskbar icons are created. Manually adding MiKTeX to path allows complete usage of LaTeX via command line or TeXstudio.

The installation script used worked on 800 Windows 7 and Windows 10 computers already without any issue, therefore I have no idea where this issue originates from. I also can not reproduce this issue on another computer. On the given machine deleting MikTeX folder content and restarting the script always results in the error message initially mentioned.

Does that help to investigate, or shall we provide more specific information?
