### ISSUE TITLE
MiKTeX portable FNDB uses full paths

### ISSUE THREAD

**Issue by rushi1986** [MiKTeX/miktex#135]
I am not sure if this is a bug or if this is deliberate but every time I use MiKTeX portable on a new computer, I have to open up the console and run refresh fndb. 

I use

X:\...\MiKTeXPortable\CustomCLS

as my local texmf tree and the portable installation is in

X:\...\MiKTeXPortable\texmfs

When I dug in deeper, I saw that the texmf.fndb file (X:\...\MIKTeXPortable\texmfs\install\miktex\data\le\texmf.fndb)

had the full path stored in it instead of path relative to the LaTeX binaries.

Is having to run refresh fndb every time I use my portable MiKTeX on a new computer the intended behavior or is this a bug?

Thanks,

-Rushi

**Comment by edocevoli** [comment]
I don't think this is a bug.
