### ISSUE TITLE
Resetting miktex deletes the whole installation folder

### ISSUE THREAD

**Issue by signed-log** [MiKTeX/miktex#1351]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I had installed MiKTeX inside a folder `~/.local/bin` (system : openSUSE Leap 15.4, installed by RPM), but then decided to uninstall, to accomplish this I used the `Restore to default` option in Cleanup

At my surprise, it straight up deleted the folder it was installed in

It absolutely shouldn't do that, especially if it isn't empty. It should only delete the executables and let the folder intact

**Comment by edocevoli** [comment]
Thank you for the report. I tried to reproduce this issue. Unfortunately without success.
