### ISSUE TITLE
Lua io.popen() doesn't  work with :write and :close

### ISSUE THREAD

**Issue by josephwright** [MiKTeX/miktex#1352]
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

In the MiKTeX, running `texlua` with input
```lua
io.popen("echo","w"):write("y"):close()
```
yields the error
```
 attempt to index a nil value
```

In TeX Live, the same construct is fine. Removing either the 'payload' of `write` (using an empty string) or removing the `close` resolves the error, but of course then isn't what is wanted.

----
Initially reported against `l3build`: https://github.com/latex3/l3build/issues/303

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
