### ISSUE TITLE
default pdfversion of pdflatex and miktex-epstopdf differ

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#1354]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

By default `pdflatex` (and probably also the other engines) produce a PDF 1.5 in miktex.  `miktex-epstopdf` on the other side converts eps-files to PDF 1.7. This means that every eps that is converted on the fly gives a warning in the log that the version of the included graphic is too high: 

~~~~
pdfTeX warning: pdflatex-dev.exe (file ./testeps-eps-converted-to.pdf): PDF inc
lusion: found PDF version <1.7>, but at most version <1.5> allowed
~~~~

~~~~
\documentclass{article}

\usepackage{graphicx}

\begin{document}
\includegraphics{testeps} %arbitrary eps that must be converted

\end{document}
~~~~

TeXlive creates PDF 1.5. in both cases but personally I think PDF 1.7. for both would be fine.

**Comment by edocevoli** [comment]
miktex-epstodpf now parses `pdftex.cfg` and passes the PDF minor version to Ghostscript.
