### ISSUE TITLE
Fix "auto expansion is only possible with scalable  fonts." on Linux

### ISSUE THREAD

**Issue by koppor** [MiKTeX/miktex#1355]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I have following LaTeX file (`example-expansion.tex`):

```latex
\documentclass{IEEEtran}
\usepackage[expansion=alltext]{microtype}
\usepackage{siunitx}
\begin{document}
Numbers \SI{100}{\km\per\hour},
\LaTeX{} (and math mode):
$100 \frac{\mathit{km}}{h}$.
\SI{5}{\percent}.
\end{document}
```

At compiling, the following output is generated:

```
! pdfTeX error (font expansion): auto expansion is only possible with scalable 
fonts.
```

I am installing MiKTeX on Linux using the following commands:

```sh
sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/miktex.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/miktex.gpg] https://miktex.org/download/ubuntu jammy universe" | sudo tee /etc/apt/sources.list.d/miktex.list
sudo apt-get update -y -q
sudo apt-get install -qq -y --no-install-recommends miktex
miktexsetup finish
initexmf --set-config-value=[MPM]AutoInstall=1
miktex packages update-package-database
miktex packages update
miktex packages install cm-super
miktex fndb refresh
updmap
```

Then, I do `pdflatex example-expansion.tex`.

Note that when switching to `article` class or removing some text does not lead to an error any more.

The full example is at https://github.com/koppor/mwe-miktex -> `example-expansion.tex` and the [check workflow](https://github.com/koppor/mwe-miktex/actions/workflows/check.yml)

**Comment by edocevoli** [comment]
This is not a MiKTeX-specific bug and so cannot be fixed by me.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).
