### ISSUE TITLE
Ubuntu 16.04: no hyphenation with polyglossia and XeLaTeX

### ISSUE THREAD

**Issue by dariok** [MiKTeX/miktex#136]
I cannot get hyphenation to work with XeLaTeX and `polyglossia` on Ubuntu 16.04 in a single user installation.
I have completely removed and reinstalled miktex twice today. Initially, in the Console, all languages were checked and none had anything under “installed”. I ran “Refresh file name database”, rebuilt XeLaTeX, unchecked all languages (except English, which cannot be unchecked), rebuilt, checked german, rebuilt. 

However, polyglossia will not load any hyphenation as the following MWE shows:

    \documentclass[paper=a5]{scrbook}
    \usepackage{polyglossia}
    \setdefaultlanguage[variant=new]{german}
    \listfiles
    \begin{document}
        Hallo! Dies ist ein Test mit einem Gewaltiglangkettenwortversuchsteststring...
    \end{document}

[test.log](https://github.com/MiKTeX/miktex/files/2044675/test.log)
![screenshot from 2018-05-28 12-09-02](https://user-images.githubusercontent.com/1765292/40610156-8105eda0-6271-11e8-93b8-e8136f7056ae.png)
![screenshot from 2018-05-28 12-08-52](https://user-images.githubusercontent.com/1765292/40610158-82e7b518-6271-11e8-8696-65bac6b14dff.png)
[hyph-utf8.files.txt](https://github.com/MiKTeX/miktex/files/2044677/hyph-utf8.files.txt)

Any help is appreciated. Thanks, --D

**Comment by edocevoli** [comment]
Thank you for the report. Please try this work-around:

    initexmf --mklangs
    initexmf -u
    initexmf --dump=xelatex

**Comment by dariok** [comment]
Thanks, with this workaround, I get all hyphenation as expected.
