### ISSUE TITLE
Error: the file name database is damaged

### ISSUE THREAD

**Issue by Cambio01** [MiKTeX/miktex#1363]
Good evening,

after the download of some updates failed, MikTex stopped working and showed me the following error: "the file name database is damaged".  I tried to delete and reinstall the program but it does not solve the issue.  the MikTex help link tells me to do the following:

"Delete the file name database files:

del "%LOCALAPPDATA%\MiKTeX\2.9\miktex\data\le\*.fndb-5"
del "%LOCALAPPDATA%\MiKTeX\2.9\miktex\data\le\*.fndb-5.log"
del "%PROGRAMDATA%\MiKTeX\2.9\miktex\data\le\*.fndb-5"
del "%PROGRAMDATA%\MiKTeX\2.9\miktex\data\le\*.fndb-5.log"
Recreate the file name database:

initexmf -u
initexmf --admin -u"

Could you please explain to me in simple terms how to do that? Because I cannot run the MikTex console right now and I was not able to find and delete the mentioned files.

Thank you in advance

**Comment by koppor** [comment]
What do you see if you execute following steps:

1. Press <kbd>Win</kbd>+<kbd>R</kbd>
2. Insert `%LOCALAPPDATA%\MiKTeX`
3. Press <kbd>Enter</kbd>
4. In case you see a folder `2.9`, then double click on it.
5. In case you see a folder `miktex` then double click on it.
6. In case you see a folder `data`, then double click on it.
7. Do you see files beginning with `le`?
8. If yes, delete them

Please let us know at which step you are failing.
