### ISSUE TITLE
User-only installation cannot check for updates during installation

### ISSUE THREAD

**Issue by koppor** [MiKTeX/miktex#1364]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

1. Start a [Windows Sandbox](https://learn.microsoft.com/de-de/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview)
2. Download MiKTeX Basic Installer
3. Start MiKTeX Basic Installer
4. Accept Terms and Conditions
5. Choose "Install only for me"\
    ![image](https://github.com/MiKTeX/miktex/assets/1366654/000f1161-b92f-4993-98d3-b6f6be1e26bd)
6. Keep proposed directory
7. A4 paper + install packages on the fly: yes
9. "Weiter", then "Start"
10. MiKTeX installs
11. Click on "Weiter"
12. Leave "Check for updates know" checked\
    ![image](https://github.com/MiKTeX/miktex/assets/1366654/bcfa95a9-e212-4ed7-97cb-408ffdae0234)
13. Click on "Weiter"
14. Click on "Close"
15. After some seconds, MiKTeX displays "Something went wrong"\
    ![image](https://github.com/MiKTeX/miktex/assets/1366654/0ea05d75-8869-44e6-9f0d-04550bf19ab9)
16. The shown details are "Administrator mode cannot be enabled (makes no sense) because this
is not a shared MiFTeX setup."\
    ![image](https://github.com/MiKTeX/miktex/assets/1366654/f4caf413-8758-45fc-a57f-96c8bf70ccca)

Expected behavior: MiKTeX runs update check in non-admin mode.

**Comment by edocevoli** [comment]
Please attach any log files you have. Will reopen this issue, if more information was provided.

**Comment by koppor** [comment]
Side note: If I go to "Copy Info" at the following dialog, the following content is in the clipboard:

    GENERAL MIKTEX INFORMATION

![image](https://github.com/MiKTeX/miktex/assets/1366654/8d8c5ed2-eddc-418c-8323-616b9f122408)

**Comment by edocevoli** [comment]
Thank you, this has been fixed now.
