### ISSUE TITLE
miktex "latest" docker image: pdflatex: error while loading shared libraries: libQt5Core.so.5 cannot open shared object file

### ISSUE THREAD

**Issue by TomChatt2** [MiKTeX/miktex#1370]
When attempting to use the Docker image miktex/miktex:latest (uploaded to Docker Hub on 10 July 2021, still "latest" as of 30 Aug 2023) on an RHEL 7.9 VM, when attempting to run the image per the instructions, it gives an error about a missing shared library:

> docker run -ti --rm ... miktex/miktex pdflatex main.tex
> pdflatex: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

I tried going in to the Docker image and running `ldd` on pdflatex, which gives the same indication that libQt5Core.so.5 is not found. That's very puzzling, as I do see libQt5Core.so.5 in /lib/x86_64-linux-gnu, and `ldd` is finding a bunch of other libraries in that same directory.

A Google search on similar issues surfaced the suggestion to try running the `strip` command:
> sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

It's beyond my understanding what that command is doing, but it would harmless to try inside a docker image. Unfortunately, the `strip` command is not available inside the miktex image, and we run in a disconnected corporate environment without ready access to the Internet, so trying to unminimize the image or do an `apt` install to get `strip` was not an available option for us.

This pretty much stops us in our tracks from using the miktex/miktex image. If that "strip" command really does remove something from the libQt5Core lib that isn't needed for running pdflatex but causes compatibility problems with some environments, perhaps a miktex image can be provided with libQt5Core already so stripped.

**Comment by koppor** [comment]
Based on that `Dockerfile`, I build "my own": https://github.com/koppor/mwe-miktex/blob/main/Dockerfile. Currently not available on Dockerhub, because I assume that users can "just" copy and paste the setup for themselves. I would be willing to start maintaining a Docker image if someone joins forces. -- Until then, I would like to highlight that there is a maintained TeX Live Docker image of the [Island of TeX](https://gitlab.com/islandoftex/images/texlive#tex-live-docker-image). In case switchting away from MiKTeX is an option.

**Comment by edocevoli** [comment]
Thank you, new Docker images are now available:

- miktex/miktex:essential (essential variant)
- miktex/miktex:basic (basic variant)

**Comment by TomChatt2** [comment]
Hi Christian,

I just tried the new “basic” and “essential” images (23.10) and for me they still have the same error as before:

pdflatex: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

Had you been able to recreate the error for yourself on the previous version? What did you do to try to fix it?

Thanks,
TC
__________________________________________________________________________________________________________________
  tom “tc” chatt  (he/him)   |    arrowhead system team architect    |    ngsp/pgsd    |    310.813.7270    |    O4/1292B   |   Redondo Beach, CA

From: Christian Schenk ***@***.***>
Sent: Friday, October 6, 2023 3:49 AM
To: MiKTeX/miktex ***@***.***>
Cc: Chatt, Tom [US] (SP) ***@***.***>; Author ***@***.***>
Subject: EXT :Re: [MiKTeX/miktex] miktex "latest" docker image: pdflatex: error while loading shared libraries: libQt5Core.so.5 cannot open shared object file (Issue #1370)


Closed #1370<https://github.com/MiKTeX/miktex/issues/1370> as completed.

**Comment by edocevoli** [comment]
No, I was not able to reproduce the issue. Please note: there is no MiKTeX Docker image for RHEL 7.
