### ISSUE TITLE
MikTex console already running Error

### ISSUE THREAD

**Issue by Alex42363** [MiKTeX/miktex#1371]
I freshly installed the MikTex console on a Windows 11 and tried to open the program as usual via the search function. After clicking "open" a notification pops up saying "MikTex console already running". Since it was my first attempt to open the program it clearly cannot be running already. If I try to open the program with admin priviledges, I get the same notification. When I open my Task Manager to close Miktex in order to properly open it again, it is unvisible and thus not closable. It is also impossible to uninstall the program. Thus, I used the REVO Uninstaller to circumvent the problem. After uninstalling the program and reinstalling it, I am still trapped with the same problem. What can I do to open the console?

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
