### ISSUE TITLE
Problem installing on Rocky Linux 9.2

### ISSUE THREAD

**Issue by leonardo-lena** [MiKTeX/miktex#1375]
Fresh install of Rocky Linux 9.2, tried installing MikTex by copy-pasting the commands given in the site, but I get this error.

Last metadata expiration check: 0:00:05 ago on Thu 14 Sep 2023 20:59:50 CEST.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides liblog4cxx.so.11()(64bit) needed by miktex-22.8.28-1.fc34.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

I tried adding --nobest first and --skip-broken second but neither seem to work.

**Comment by edocevoli** [comment]
Thank you, this has been fixed now.
