### ISSUE TITLE
Refresh Font File error on FreeBSD 13.2

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#1377]
This is a fresh installation of a FreeBSD 13.2-RELEASE-p3 GENERIC amd64 machine. When attempting to run "Refresh Font Files" from the "Tasks" menu, I receive an error message:

savedOutput="/home/gerard/.miktex/texmfs/data/miktex/log/initexmf_2023-09-20-141811.out", fileName="/usr/local/bin/initexmf", exitCode="1"
[miktex-console.log](https://github.com/MiKTeX/miktex/files/12676369/miktex-console.log)
[initexmf.log](https://github.com/MiKTeX/miktex/files/12676401/initexmf.log)

**Comment by edocevoli** [comment]
sorry, but freebsd is not yet supported
