### ISSUE TITLE
TexStudio unable to compile program due to MikTeX problem

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#1378]
FreeBSD  13.2-RELEASE-ps GENERIC amd64

TexStudio can not run a file that works perfectly on my Windows 11 system. It appears to be a MikTeX problem.

Process started: lualatex -synctex=1 -interaction=nonstopmode "texstudio_KNIasS".tex
[findtexmf.log](https://github.com/MiKTeX/miktex/files/12685738/findtexmf.log)
[initexmf.log](https://github.com/MiKTeX/miktex/files/12685739/initexmf.log)
[miktex-kpsewhich.log](https://github.com/MiKTeX/miktex/files/12685740/miktex-kpsewhich.log)
[miktex-luahbtex.log](https://github.com/MiKTeX/miktex/files/12685741/miktex-luahbtex.log)
[miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/12685742/miktex-makefmt.log)
[miktex-maketfm.log](https://github.com/MiKTeX/miktex/files/12685743/miktex-maketfm.log)
[miktex-pdftex.log](https://github.com/MiKTeX/miktex/files/12685744/miktex-pdftex.log)

Sorry, but /home/gerard/bin/lualatex did not succeed.
The log file hopefully contains the information to get MiKTeX going again: /home/gerard/.miktex/texmfs/data/miktex/log/miktex-luahbtex.log
__cxa_thread_call_dtors: dtr 0x7003b0 from unloaded dso, skipping __cxa_thread_call_dtors: dtr 0x7003b0 from unloaded dso, skipping __cxa_thread_call_dtors: dtr 0x82fd19350 from unloaded dso, skipping
Process exited with error(s)

**Comment by edocevoli** [comment]
Sorry, but freebsd is not yet supported.
