### ISSUE TITLE
Artifacts in the preview

### ISSUE THREAD

**Issue by PlamenToby** [MiKTeX/miktex#1379]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Some bold fonts and some graphics appear with double lines/aliased in the previewer. I am using a 4K monitor, Windows scaling set at 200%. It used to be fine until a few weeks ago.

On the attached screenshot, the vertical curve should be solid, and the "3" in Figure 3 has a double line.

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/12714978/miktex-report.txt)
![Screenshot 2023-09-25 082659](https://github.com/MiKTeX/miktex/assets/40969067/a2870db8-4eb3-41d0-8edc-8d62ac4aa814)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
