### ISSUE TITLE
Support for Debian 12 (bookworm)

### ISSUE THREAD

**Issue by stefan-steffens** [MiKTeX/miktex#1383]
Hi Christian,

Is support for Debian 12 planned?

When trying to install it using the bullseye repository using below steps I'm stuck with errors:

$ echo "deb [signed-by=/usr/share/keyrings/miktex-keyring.asc] http://miktex.org/download/debian bullseye universe" | sudo tee /etc/apt/sources.list.d/miktex.list

$ sudo apt-get update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]                                                       
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease                                                                                
Hit:5 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                
Hit:6 https://downloads.1password.com/linux/debian/amd64 stable InRelease                                                                
Get:7 http://security.debian.org/debian-security bookworm-security/main Sources [43.5 kB]
Get:8 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [63.3 kB]
Get:4 https://markov.htwsaar.de/tex-archive/systems/win32/miktex/setup/deb bullseye InRelease [2,042 B]
Get:9 https://markov.htwsaar.de/tex-archive/systems/win32/miktex/setup/deb bullseye/universe amd64 Packages [1,998 B]
Fetched 159 kB in 6s (28.7 kB/s)      
Reading package lists... Done

$ sudo apt install miktex
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 miktex : Depends: libicu67 (>= 67.1-1~) but it is not installable
          Depends: liblog4cxx11 (>= 0.11.0) but it is not installable
          Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

Thanks for developing MiKTeX.

**Comment by edocevoli** [comment]
Thank you, the Debian 12 package is now available:

```sh
echo "deb [signed-by=/usr/share/keyrings/miktex-keyring.asc] https://miktex.org/download/debian bookworm universe" | sudo tee /etc/apt/sources.list.d/miktex.list
```
