### ISSUE TITLE
MiKTeX encountered an internal error!

### ISSUE THREAD

**Issue by bansky0** [MiKTeX/miktex#1384]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hi , I have try to uograde MikTeX but everytime I installed and I get the following issue.

GENERAL MIKTEX INFORMATION
Date: 2023-10-01 02:54:50
MiKTeX: 2.9.7420
GitInfo: f24bf02 / 2020-05-11 19:14:29
OS: Windows 10 Pro, 64-bit, build 19045
SharedSetup: no
LinkTargetDirectory: C:\Users\User\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
LastUpdateDb: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\User\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\User\AppData\Local\MiKTeX\2.9
Root2: C:\Users\User\AppData\Local\Programs\MiKTeX
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\User\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\User\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\User\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: non-existing/explorer

The following issues were detected:
  1: major issue: So far, you have not checked for MiKTeX updates.

ERROR DETAILS
Program: C:\Users\User\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe
Source: Libraries\MiKTeX\PackageManager\RestRemoteService.cpp:245
Error: MiKTeX encountered an internal error.

**Comment by edocevoli** [comment]
MiKTeX 2.9 is not supported anymore
