### ISSUE TITLE
hitex format outdated

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex#1386]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The [hitex](https://ctan.org/pkg/hitex) format in MiKTeX is out of date. TeXlive has version 2.0 while MiKTeX has version 1.4. I'm not entirely sure about this, but it may be the reason compiling
```latex
\documentclass{article}
\begin{document}
some text
\end{document}
```
with `hilatex` fails.

**Comment by edocevoli** [comment]
This has been done.
