### ISSUE TITLE
Perltex does not work

### ISSUE THREAD

**Issue by yuriy12375** [MiKTeX/miktex#1388]
Hello, 
I try to complile the file by the command line: "perltex --nosafe file.tex"

\documentclass{article}
\usepackage[english]{babel}
\usepackage{perltex}
\perlnewcommand\coom{print 'ddddd';}
\begin{document}
\coom      
\end{document}

And the log file is:

![image](https://github.com/MiKTeX/miktex/assets/147672839/520b4a67-91bb-412b-8633-419d945c1e71)

Help please.

**Comment by edocevoli** [comment]
Sorry, I can't help you with this.
