### ISSUE TITLE
The file `autosp.tar.lzma` is not available at the following URL: https://mirror.foobar.to/CTAN/systems/win32/miktex/tm/packages/

### ISSUE THREAD

**Issue by mutti2324** [MiKTeX/miktex#1391]
**Description**
I ran the `setup-5.6.1+3f4a6a7-x64.exe` (MikTeX Net Installer) on my PC (Windows 10 Pro) in an attempt to download the complete MikTeX distribution from the source https://mirror.foobar.to/CTAN/systems/win32/miktex/tm/packages/ (Version: 14-Oct-2023). Unfortunately, the following Error occur:
```
downloading https://mirror.foobar.to/CTAN/systems/win32/miktex/tm/packages/autosp.tar.lzma (expecting 271445 bytes)...

An error occurred:
  source file: 
  source line: 0
  message: Requested resource not found.
  info: url="https://mirror.foobar.to/CTAN/systems/win32/miktex/tm/packages/autosp.tar.lzma"
```

**Issue:**
The file `autosp.tar.lzma` is not available at the following URL: https://mirror.foobar.to/CTAN/systems/win32/miktex/tm/packages/.

**Comment by ivankokan** [comment]
Same here.

**Comment by julienvidal-isae** [comment]
I'm having the same issue. 

Just want to had that something similar probably already happened at least twice in the last few month. But it was resolved before I could do any troubleshooting.

**Comment by TB98SF** [comment]
Same issue here

**Comment by LukasK07** [comment]
same issue here
