### ISSUE TITLE
Error running latex2man

### ISSUE THREAD

**Issue by albert-github** [MiKTeX/miktex#140]
I was trying `latex2man _formulas.tex  _formulas.man` and I got the message:
```
basename: extra operand '2.9\\scripts\\latex2man\\latex2man'
Try 'basename --help' for more information.
Terminating on signal SIGINT(2)

```
also when running with the full path (`"C:\Program Files\MiKTeX 2.9\miktex\bin\x64\latex2man.exe" _formulas.tex  _formulas.man`) I get this error message.

Looking into the file: `C:\Program Files\MiKTeX 2.9\\scripts\\latex2man\\latex2man` on line 26 I see:
```$CMD=`basename $0`; chop ($CMD);```
I think this should be:
```$CMD=`basename "$0"`; chop ($CMD);```

**Comment by edocevoli** [comment]
Please report this bug to the latex2man developer team.

This is not a MiKTeX-specific bug and so cannot be fixed by me.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).

**Comment by albert-github** [comment]
A bug report has been send to the maintainer and it has been fixed and the fix has also been send to CTAN.
