### ISSUE TITLE
MiKTeX support for Fedora 39

### ISSUE THREAD

**Issue by vanlepthien** [MiKTeX/miktex#1401]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

After installation of Fedora 39, MiKTex 38 cannot be installed:

$ sudo dnf install miktex
MiKTeX Fedora 38                                                                                                              3.1 kB/s | 2.9 kB     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides libboost_chrono.so.1.78.0()(64bit) needed by miktex-23.10-1.fc38.x86_64 from miktex-fedora-38
  - nothing provides libboost_locale.so.1.78.0()(64bit) needed by miktex-23.10-1.fc38.x86_64 from miktex-fedora-38
  - nothing provides libboost_system.so.1.78.0()(64bit) needed by miktex-23.10-1.fc38.x86_64 from miktex-fedora-38
  - nothing provides libboost_thread.so.1.78.0()(64bit) needed by miktex-23.10-1.fc38.x86_64 from miktex-fedora-38
  - nothing provides liblog4cxx.so.13()(64bit) needed by miktex-23.10-1.fc38.x86_64 from miktex-fedora-38
  - nothing provides libboost_chrono.so.1.78.0()(64bit) needed by miktex-23.9.24-1.fc38.x86_64 from miktex-fedora-38
  - nothing provides libboost_locale.so.1.78.0()(64bit) needed by miktex-23.9.24-1.fc38.x86_64 from miktex-fedora-38
  - nothing provides libboost_system.so.1.78.0()(64bit) needed by miktex-23.9.24-1.fc38.x86_64 from miktex-fedora-38
  - nothing provides libboost_thread.so.1.78.0()(64bit) needed by miktex-23.9.24-1.fc38.x86_64 from miktex-fedora-38
  - nothing provides liblog4cxx.so.13()(64bit) needed by miktex-23.9.24-1.fc38.x86_64 from miktex-fedora-38

Fedora 39 has updated the following software levels:

- libboost_\*.so.1.78.0 -> libboost_\*.so.1.81.0
- liblog4cxx.so.13 -> liblog4cxx.so.15

Please provide an update for Fedora 39.

**Comment by elomwarren** [comment]
Same issue here
![image](https://github.com/MiKTeX/miktex/assets/74142086/33fe67a2-44ee-444b-af92-77b010a219ae)

**Comment by mahtlinux** [comment]
Same issue. I can't even unisntall it
Last time I use it directly. I will use texlive instead or miktex in a container.
![miktex](https://github.com/MiKTeX/miktex/assets/13526603/c1a848c9-157f-41bb-b5b9-8a644e3537cc)

**Comment by edocevoli** [comment]
This has been fixed

**Comment by egyres** [comment]
Thanks
