### ISSUE TITLE
Building for arm64 not working

### ISSUE THREAD

**Issue by Behinder** [MiKTeX/miktex#1402]
I installed all prequsisties including qt511 and it does not work - cmake goes fine but make gives errors
````
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [sandbox/miktex/bin/darwin-arm64/libmiktex-ui-Qt.4.2.0.dylib] Error 1
make[1]: *** [Libraries/MiKTeX/UI/Qt/CMakeFiles/miktex-ui-Qt.dir/all] Error 2
make: *** [all] Error 2
````

Annoying error as it does not show where it happen and I cannot see where make has the output log.
My suggestion for todo list is:

1.  drop openssl1 support in favour for 3
2. updating to qt6 requires resignation from qtscript

I am not an expert in QT - it always fell a bit clunky. Can version for Macos use native mac UI ? - After all it is required only for Settings package and Package Manager.

**Comment by edocevoli** [comment]
Sorry, but I cannot help you here because I currently don't have access to an arm64 mac.

**Comment by Behinder** [comment]
I have access, how can i help you?

śr., 15 lis 2023 o 12:45 Christian Schenk ***@***.***>
napisał(a):
