### ISSUE TITLE
How to update miktex packages through mirror site without accessing api2.miktex.org?

### ISSUE THREAD

**Issue by Zghebn** [MiKTeX/miktex#1406]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hi, it's seens that `api2.miktex.org` is down, and I tried to update packages with repository set:
```
miktex packages update --repository https://mirrors.bfsu.edu.cn/CTAN/systems/win32/miktex/tm/packages
```
But the program still visit `api2.miktex.org`, and if no response was given, the update failed.

Is there a way to update without checking with `api2.miktex.org`?

**Comment by jibnew** [comment]
I have the same problem, is there any progress on this?
