### ISSUE TITLE
Silent Uninstallation of Miktex

### ISSUE THREAD

**Issue by vickywijek** [MiKTeX/miktex#141]
I have been able to silently install Mixtex however silent uninstallation has not been successful.

As suggested on the internet I have downloaded miktexsetup from the Miktex site however it does not seem to support uninstall either.

Please help.

**Comment by edocevoli** [comment]
Cannot reproduce this. What I did:

1) Install MiKTeX
2) Uninstall MiKTeX by running `miktexsetup uninstall` which was installed in step 1)

**Comment by vickywijek** [comment]
Running miktexsetup uninstall gave me the following error :-

miktexsetup.exe: Windows API error 2: The system cannot find the file specified.
miktexsetup.exe: Data: fileName="initexmf.exe"

**Comment by DammittJim** [comment]
> Running miktexsetup uninstall gave me the following error :-
> 
> miktexsetup.exe: Windows API error 2: The system cannot find the file specified.
> miktexsetup.exe: Data: fileName="initexmf.exe"

I am also getting this error when trying to silently uninstall. Is there a solution to this?
