### ISSUE TITLE
MacOS Sonoma - Cannot Add New TEXMF root directory

### ISSUE THREAD

**Issue by terrypanda** [MiKTeX/miktex#1411]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Have just wiped my mac to try this on clean installation; can confirm that MiKTeX will stall on MacOS Sonoma when adding a new TEXMF directory and then times out.

**Comment by edocevoli** [comment]
sorry, with the given info it is not possible to work on this issue
