### ISSUE TITLE
Broken `miktexsetup_standalone`?

### ISSUE THREAD

**Issue by tps800** [MiKTeX/miktex#1412]
MiKTeXSetup-Standalone does not create a local repository nor download anything. The command, as adviced at https://miktex.org/howto/local-repository just starts, then does nothing:

MikTeXSetup-Standalone was downloaded from https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/miktexsetup-5.5.0+1763023-x64.zip with
```
wget https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/miktexsetup-5.5.0+1763023-x64.zip
```

then unpacked using `7z.exe`:
```
7z x miktexsetup-5.5.0+1763023-x64.zip
```

Next step was calling `miktexsetup_standalone.exe`:
```
miktexsetup_standalone ^
  --verbose ^
  --local-package-repository=X:\Software\MiKTeX\Repo ^
  --package-set=complete ^
  download
```

Then trying with
```
miktexsetup_standalone ^
  --version
```

does not output anything. It just starts, then terminates.

**Comment by tps800** [comment]
May it be, MiKTeXSetup-standalone.exe does _require_ cmd.exe and does not run executed from PowerShell?

**Comment by edocevoli** [comment]
It looks like the start of the program is not allowed. I am afraid, this is nothing I can fix remotely.

**Comment by tps800** [comment]
> It looks like the start of the program is not allowed. I am afraid, this is nothing I can fix remotely.
This is definitely not the case. Looks like `MiKTeXSetup-standalone.exe` requires `cmd.exe` interaction, failing if this is not available, when it is started without `cmd.exe` running it. It indeed works if you start `cmd.exe`to execute `MiKTeXSetup-standalone.exe`.

Could be something to mention within the examples on how to call it.
