### ISSUE TITLE
installing miktex via a personal http repository

### ISSUE THREAD

**Issue by benoitruggi** [MiKTeX/miktex#1413]
Hello, 

I have created a repository on a Debian vm. I created an HTTP page to access the remote so that the repository is accessible from a browser via http://my_ip/miktex

However, when I try to install miktex using the command :
miktexsetup_standalone --verbose --remote-package-repository=http://******/miktex  --shared=yes --user-config="%APPDATA%\MiKTeX" --user-data="%userprofile%\AppData\local\MiKTeX" --user-install="%APPDATA%\MiKTeX" install

The result is:
this is MiKTeX Setup Service 5.5 (MiKTeX 23.4)
miktexsetup_standalone: Not a package repository.
miktexsetup_standalone: Data: repository="C:\Users\****\Downloads\MiKTeX"

 if I use --local-package-repository instead of --remote-package-repository : 

I get stuck on : 
this is the installer for MiKTeX 5.5 (MiKTeX 23.4)
Starting the installer...
Loading package database...

If I tried to create a new local repository on Windows using my Linux repository with the :
miktexsetup_standalone.exe  --verbose --remote-package-repository=http://********/miktex  --local-package-repository=C:\miktex-repository --package-set=complete download

The result is : 
this is MiKTeX Setup Service 5.5 (MiKTeX 23.4)
starting downloader...
miktexsetup_standalone: The remote package repository is not registered. You have to choose another repository.
miktexsetup_standalone: Data: url="http://********/miktex"

My goal is to have only one repository to update (the Linux one).
And to be able to silently install Miktex on all my machines from this Linux repository.

Could you help me?

**Comment by edocevoli** [comment]
sorry, but custom repositories are currently not supported
