### ISSUE TITLE
Unsupported Protocol

### ISSUE THREAD

**Issue by Vanadyel** [MiKTeX/miktex#142]
Hello there,

Am using miktex-update_admin.exe

Happens again, supposedly like this bug https://sourceforge.net/p/miktex/bugs/2609/

![image](https://user-images.githubusercontent.com/40146128/41203511-4b5f0396-6cd8-11e8-9d69-e2ffd720d162.png)

I can update like 5 packages and then it crashes.

> MiKTeX Update Wizard Report
>
> Version: 2.9.4913
> Date: Sunday, June 10, 2018
> Time: 17:49:12
> starting package maintenance...
> 
> installation directory: "C:\Program Files\MiKTeX 2.9"
> 
> package repository: http://mirror.ctan.org/systems/win32/miktex/tm/packages/
> 
> lightweight database digest: 03c57783cf4167b527f693ea6f6d82fe
> 
> going to download 96954048 bytes
> 
> going to install 3049 file(s) (99 package(s))
> 
> going to remove 1291 file(s) (42 package(s))
> 
> unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core-PS.dll
> 
> unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core.dll
> 
> unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-packagemanager-PS.dll
> 
> unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-packagemanager.dll
> 
> downloading http://mirror.ctan.org/systems/win32/miktex/tm/packages/amscls.tar.lzma...
> 
> 1261301 bytes, 2332.84 KB/Sec
> 
> extracting files from amscls.tar.lzma...
> 
> downloading http://mirror.ctan.org/systems/win32/miktex/tm/packages/amsmath.tar.lzma...
> 
> 2411376 bytes, 3773.81 KB/Sec
> 
> extracting files from amsmath.tar.lzma...
> 
> downloading http://mirror.ctan.org/systems/win32/miktex/tm/packages/babel.tar.lzma...
> 
> 1385423 bytes, 5684.67 KB/Sec
> 
> extracting files from babel.tar.lzma...
> 
> downloading http://mirror.ctan.org/systems/win32/miktex/tm/packages/bidi.tar.lzma...
> 
> 3919686 bytes, 3905.94 KB/Sec
> 
> extracting files from bidi.tar.lzma...
> 
> downloading http://mirror.ctan.org/systems/win32/miktex/tm/packages/carlisle.tar.lzma...
> 
> 85303 bytes, 785.88 KB/Sec
> 
> extracting files from carlisle.tar.lzma...
> 
> downloading http://mirror.ctan.org/systems/win32/miktex/tm/packages/cm.tar.lzma...
> 
> 
> Error: Unsupported protocol
> 
>

**Comment by edocevoli** [comment]
You are using an old and unsupported version of the update wizard.
