### ISSUE TITLE
xelatex.exe missing icuuc74.dll 

### ISSUE THREAD

**Issue by bpcw** [MiKTeX/miktex#1421]
After today's MiKTeX update, I face a similar issue as in https://github.com/MiKTeX/miktex/issues/1232:

I just upgraded to the latest version of MiKTeX and I am getting a message when I am trying to compile with xelatex that "the code execution cannot proceed because icuuc74.dll was not found".

initexmf --report: [miktex-report.txt](https://github.com/MiKTeX/miktex/files/13784663/miktex-report.txt)

Is this a problem with my installation, or did the issue just come back?

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by bpcw** [comment]
Thanks for the quick response!

**Comment by Armur73** [comment]
Hi, any solution if i need to work today? Update in MikTex Console have nothing new.

**Comment by WolfgangRichter** [comment]
I downloaded icu4c-74_2-Win64-MSVC2019.zip from https://github.com/unicode-org/icu/releases/tag/release-74-2 and put the three icu**74.dll files into MiKTeX\miktex\bin\x64. After this xelatex works again.
