### ISSUE TITLE
Reduce the install size

### ISSUE THREAD

**Issue by jsmith173** [MiKTeX/miktex#1424]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I'm using MiKTeX portable but my install directory size is very big (~933MB). How could I reduce the install size? Which files can I delete? I'm using 'texify' only.

System: Windows 11

**Comment by edocevoli** [comment]
You can use the [setup utility](https://miktex.org/announcement/miktex-setup-utility) to download/install the essential package set.
