### ISSUE TITLE
What are the '.exe' dependencies of texify.exe?

### ISSUE THREAD

**Issue by jsmith173** [MiKTeX/miktex#1425]
Thanks for your previous support.
I have installed the 'essential' packages but my installed directory is still too big so I'd like to delete all not neccessary exe files in the x64 binary directory.
My question what are the exe dependencies of texify.exe? The help file says it depends on miktex-tex and miktex-pdftex. I tried to keep only this exe files but texify not working this way.

**Comment by edocevoli** [comment]
Sorry, I don't know.
