### ISSUE TITLE
tex.exe and --synctex

### ISSUE THREAD

**Issue by cooch17** [MiKTeX/miktex#1427]
The following was just sent out on the WinEdt discussion list by the developer/maintainer of WinEdt. I'm posting his 'query' (bug report?) here:

"It has come to my attention that in the recent versions of MiKTeX plain TeX (tex.exe) does not allow –synctex switch. It is OK in TeX Live and it was fine with older versions of MiKTeX.  
Does any TeX guru know if this is a glitch in MiKTeX distribution or is this a permanent feature?

The default macro will have to be modified or else the compilation fails. Let’s hope it will be fixed…"

**Comment by edocevoli** [comment]
Indeed, the classic (Knuth) `tex` engine does not support extensions like synctex.
