### ISSUE TITLE
Problems regarding execution through luatex (faulty 1.17.1 ?) -- impossible to set version number ?

### ISSUE THREAD

**Issue by arthurnardy** [MiKTeX/miktex#1429]
Good morning,

Documentation generation of our project went broken during christmas holidays.

No source code on our side was modified, neither was access right of the executer. But MiKTeX version went up (23.10.12 => 23.12) and included a new luatex version (1.17.0 => 1.17.1).

The error is the following : 
> This is LuaHBTeX, Version 1.17.1 (MiKTeX 23.12)
>  restricted system commands enabled.
> LaTeX2e <2023-11-01>
> L3 programming layer <2024-01-04>
> NotSpecified: (:) [], RemoteException
> lualatex: file not writable for security reasons: C:/Program Files/MiKTeX//m_t_x_t_e_s_t.tmp
> 
> 
> luaotfload | load : FATAL ERROR
> luaotfload | load :   ├ù Failed to load "fontloader" module "basics-gen".
> luaotfload | load :   ├ù Error message:
> luaotfload | load :     ├ù "...m Files/MiKTeX/tex/luatex/luaotfload/luaotfload-init.lua:301: system : no writeable cache path, quiting".
> 
> stack traceback:
>         ...rogram Files/MiKTeX/tex/luatex/luaotfload/luaotfload.lua:200: in local 'load_fontloader_module'
>         ...m Files/MiKTeX/tex/luatex/luaotfload/luaotfload-init.lua:303: in upvalue 'init_main'
>         ...m Files/MiKTeX/tex/luatex/luaotfload/luaotfload-init.lua:590: in function 'luaotfload-init.lua'
>         ...rogram Files/MiKTeX/tex/luatex/luaotfload/luaotfload.lua:322: in field 'main'
>         [\directlua]:1: in main chunk
> 
> ...m Files/MiKTeX/tex/luatex/luaotfload/luaotfload-init.lua:301: system : no wr
> iteable cache path, quiting
> stack traceback:
>         [C]: in function 'error'
>         ...m Files/MiKTeX/tex/luatex/luaotfload/luaotfload-init.lua:301: in function '
> os.exit'
>         ...rogram Files/MiKTeX/tex/luatex/luaotfload/luaotfload.lua:203: in local 'loa
> d_fontloader_module'
>         ...m Files/MiKTeX/tex/luatex/luaotfload/luaotfload-init.lua:303: in upvalue 'i
> nit_main'
>         ...m Files/MiKTeX/tex/luatex/luaotfload/luaotfload-init.lua:590: in function '
> luaotfload-init.lua'
>         ...rogram Files/MiKTeX/tex/luatex/luaotfload/luaotfload.lua:322: in field 'mai
> n'
>         [\directlua]:1: in main chunk.
> <everyjob> ...ring \\def\string \\encodingdefault{OT1}')end }
>                                                   \let \f@encoding \encoding...
> 

But also : 
> Missing character: There is no a (U+0061) in font nullfont!
> Missing character: There is no g (U+0067) in font nullfont!
> Missing character: There is no e (U+0065) in font nullfont!
> Missing character: There is no b (U+0062) in font nullfont!
> Missing character: There is no o (U+006F) in font nullfont!
> Missing character: There is no o (U+006F) in font nullfont!
> Missing character: There is no s (U+0073) in font nullfont!
> Missing character: There is no t (U+0074) in font nullfont!
> Missing character: There is no e (U+0065) in font nullfont!
> etc 

What I understand is : luatex is not able anymore to generate or access a database of font to be used in what is printed out and is therefore not able anymore to proceed further.

Some refresh commands I identified online did not help :
> miktex --admin --enable-installer --verbose fndb refresh
> luaotfload-tool.exe --update --force --verbose

`initexmf --report `
> ReportDate: 2024-01-10 11:25:53
> CurrentVersion: 23.12
> SetupDate: 2024-01-09 17:18:00
> SetupVersion: 23.12
> Configuration: Regular
> GitInfo: 853af38 / 2023-12-27 10:40:32
> OS: Windows 10.0.19045
> SharedSetup: yes
> LinkTargetDirectory: C:\Program Files\MiKTeX\miktex\bin\x64
> PathOkay: yes
> LastUpdateCheckAdmin: 2024-01-10 11:19:59
> LastUpdateAdmin: not yet
> LastUpdateDbAdmin: 2024-01-10 11:19:59
> SystemAdmin: yes
> RootPrivileges: yes
> AdminMode: no
> Root0: C:\Program Files\MiKTeX\
> Root1: C:\ProgramData\MiKTeX
> UserInstall: C:\Program Files\MiKTeX\
> UserConfig: C:\Program Files\MiKTeX\
> UserData: C:\Program Files\MiKTeX\
> CommonInstall: C:\Program Files\MiKTeX\
> CommonConfig: C:\ProgramData\MiKTeX
> CommonData: C:\ProgramData\MiKTeX

I attached all the logs I may have : 
- [initexmf.log](https://github.com/MiKTeX/miktex/files/13886451/initexmf.log)
- [lualatex.log](https://github.com/MiKTeX/miktex/files/13886452/lualatex.log)
- [miktex-hbf2gf.log](https://github.com/MiKTeX/miktex/files/13886453/miktex-hbf2gf.log)
- [miktex-maketfm.log](https://github.com/MiKTeX/miktex/files/13886454/miktex-maketfm.log)
- [miktex-makemf.log](https://github.com/MiKTeX/miktex/files/13886455/miktex-makemf.log)
- [miktex.log](https://github.com/MiKTeX/miktex/files/13886456/miktex.log)
- [miktex-luahbtex.log](https://github.com/MiKTeX/miktex/files/13886457/miktex-luahbtex.log)
- [miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/13886458/miktex-makefmt.log)
- [miktex-fc-cache.log](https://github.com/MiKTeX/miktex/files/13886459/miktex-fc-cache.log)
- [luaotfload-tool.log](https://github.com/MiKTeX/miktex/files/13886460/luaotfload-tool.log)
- [miktex-console.log](https://github.com/MiKTeX/miktex/files/13886461/miktex-console.log)

[I looked for the changelog of the latest luatex version, but we only have a changelog for the version 1.17.0, not the 1.17.1. No trace of what was modified in this version or why. 
](https://gitlab.lisn.upsaclay.fr/texlive/luatex/-/blob/master/source/texk/web2c/luatexdir/NEWS)

A quick short-term solution is to have the n-1 version installed, but I did not find the proper way to set a fix version of MiKTeX and its dependencies. Sounds like the miktex update or upgrade methods were designed to always stick to the latest version in any case.

What could I do to unblock the situation ?

Thank you in advance !

- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
You are running luatex with elevated privileges; It should work if you run luatex in user-mode. Hope this helps

**Comment by arthurnardy** [comment]
Thank you for your answer, sadly I do not see the point in this "user-mode" solution.

We MUST execute this workflow as administrator in a powershell on the machine we are targeting. We are not given any choice here. 

Despite this "running with elevated privileges" red flag we have ever seen, everything was just going fine. How the fact we use a shared installation and execute our workflow as admin mode has to do with the error ?

Furthermore, for the sake of investigation, we did another miktex install on another computer without shared installation and being only in a local directory with a random personna, and the same error pops up, with the same log. The only thing changing are the relative paths 
> lualatex:` file not writable for security reasons: C:/Users/%user%/MiKTeX/m_t_x_t_e_s_t.tmp

Is there any solution to set the miktex distribution to version n-1 (23.10.12) ? If it rolling back from 1 version does not solve, at least it gives us further hints on where the problem may lie.
