### ISSUE TITLE
MiKTeX portable creates start menu entries

### ISSUE THREAD

**Issue by craue** [MiKTeX/miktex#143]
Although MiKTeX portable is meant to "[leave no traces on the host computer](https://miktex.org/portable)", start menu entries are created while installing or updating packages. If I manually remove them, they get recreated on the next update.

![miktex-start-menu-entries](https://user-images.githubusercontent.com/800119/41277625-06d469d6-6e28-11e8-9757-5e0fa387608f.png)

**Comment by georgerbr** [comment]
It also creates an entry in Add or Remove Programs:

![miktexportableentry](https://user-images.githubusercontent.com/4930759/41561972-a858f3aa-7321-11e8-8d88-3f0349dbb2b4.png)

**Comment by edocevoli** [comment]
@georgerbr: this will also be fixed.

**Comment by edocevoli** [comment]
This will be fixed with [milestone 2.9.6730](https://github.com/MiKTeX/miktex/milestone/6).

**Comment by craue** [comment]
Great, thank you.
