### ISSUE TITLE
provide TexWorks launcher on linux 

### ISSUE THREAD

**Issue by hemu312** [MiKTeX/miktex#1433]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Currently, There is no TexWorks launcher in applications(on linux). So we need to either launch it from from commandline or from miktex console.
Please provide TexWorks launcher in application menu, so lauching texworks can be straight forwork. 
It can be done providing .desktop file in ~/.local/share/applications or /usr/share/applications.

**Comment by jkbhu85** [comment]
Please, can somebody take a look at this?
