### ISSUE TITLE
pkexec not found although installed (Linux, MiKTeX 23.12)

### ISSUE THREAD

**Issue by mhdry** [MiKTeX/miktex#1436]
I compiled and installed MiKTeX version 23.12, using the source code archive from the GitHub release page. Upon running `miktex-console`  as a normal (unprivileged) user in order to finish the setup, I can't perform a shared install. The error message reads:

```
No graphical sudo frontend is available.
Please install 'pkexec', 'kdesu' (KDE) or 'gksu' (Gnome).
Alternatively, you can enter 'sudo [...]
```

My system is using the XFCE desktop environment. However, `pkexec` is present and works fine with other applications:

```
$ which pkexec
/usr/bin/pkexec
```

Manually invoking `sudo miktex-console` will run fine, of course, but at the moment there seems to be no way to elevate privileges in the GUI when started as a normal user.

- [X] I have read and acknowledged this HOWTO article:
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
Thank you for the report. Because I cannot reproduce the defect, and since the provided info is insufficient, I cannot work on this effectively.

**Comment by mhdry** [comment]
Your response reads "works for me, therefore goodbye". Together with immediately closing this issue, that's a rather rude response. How unfortunate.

The information I provided is **everything** `miktex-console` provides. The only thing I am to blame for is that I forgot to mention that I compiled MiKTex using

```
$ cmake -DCMAKE_INSTALL_PREFIX=/opt/miktex [...]
```

which should make my problem reproducible. Maybe you can look into this again?
