### ISSUE TITLE
miktex-qt5-bin-x64 not cleanly removed?

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#1437]
I updated miktex today. If I rerun the update manager it claims that there is a pending update for `miktex-qt5-bin-x64`  as it must be repaired

![image](https://github.com/MiKTeX/miktex/assets/4047173/2f2392d2-e950-478c-b422-f7a144fba135)

From the file size (compared to miktex-qt6 which imho is new) and the content of the package miktex-qt5 it looks as if the package was not removed cleanly:

![image](https://github.com/MiKTeX/miktex/assets/4047173/8bbb1276-1ca4-4da4-ad74-5c4898894544)

![image](https://github.com/MiKTeX/miktex/assets/4047173/a78c84e9-b895-4b8f-aa94-c0a54685c963)

**Comment by jake-bobowski** [comment]
Same issue here.

**Comment by edocevoli** [comment]
Should be okay now: the repair now works.
