### ISSUE TITLE
The package definition file could not be parsed

### ISSUE THREAD

**Issue by Mr4erkes** [MiKTeX/miktex#144]
MiKTeX Problem Report
Message: The package definition file could not be parsed.
Data: path="C:\Users\User\AppData\Local\Temp\mik22472\cellprops.tpm", column="1124", line="2"
Source: Libraries\MiKTeX\PackageManager\TpmParser.cpp
Line: 330
MiKTeX: 2.9
OS: Windows 8.1 Pro, 64-bit, build 9600
Invokers: explorer
SystemAdmin: yes
PowerUser: no
Root0: C:\Users\User\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\User\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\User\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\User\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\User\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

the file **cellprops.tpm** contains 
`...<TPM:Copyright owner="Julien "_FrnchFrgg_" Rivaud" year="2018"/>...`

**Comment by edocevoli** [comment]
Please note that this is the wrong place to report packaging issues.

**Comment by edocevoli** [comment]
This will be fixed with one of the next updates.

**Comment by egorpugin** [comment]
See https://gitlab.com/frnchfrgg-latex/cellprops/issues/1
