### ISSUE TITLE
/root/Programs/TeXAndFriends/Knuth/web/tangle.p:1: parse error before `�'

### ISSUE THREAD

**Issue by flowchartsman** [MiKTeX/miktex#1440]
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I ran into this error attempting to compile for aarch64. Prior reports have been told it's [not supported](https://github.com/MiKTeX/miktex/issues/1409), but I was wondering if we might be able to get a bit more information? What is failing here that makes this not work? This has been causing the [FreeBSD port to fail ](https://www.mail-archive.com/freebsd-pkg-fallout@freebsd.org/msg2267475.html) for who knows how long, so it's clearly a [longstanding issue](https://github.com/MiKTeX/miktex/issues/1148).

I have found several versions of tangle.p online [here, for example](https://ftp.jaist.ac.jp/pub/CTAN/systems/knuth/local/web/), that are at least readable, however the one generated during my installation was gibberish and detected by filemagic as `ISO-8859 text`, if that helps. Mostly I'm just curious if anyone has a lead on what's going wrong. Clearly `tangle.p` is corrupt for some reason.

<img width="1168" alt="image" src="https://github.com/MiKTeX/miktex/assets/926884/a9925d9e-9e12-4008-a30f-e9e354415094">

This step that is generating the corrupt output appears to be:
```
cd /miktex/build/Programs/TeXAndFriends/Knuth/web && ../../../../sandbox/miktex/bin/linux-aarch64/inittangle /miktex/source/Programs/TeXAndFriends/Knuth/web/source/tangle.web /miktex/source/Programs/TeXAndFriends/Knuth/web/miktex-tangle.ch /miktex/build/Programs/TeXAndFriends/Knuth/web/tangle.p /miktex/build/Programs/TeXAndFriends/Knuth/web/tangle.pool
```

**Comment by edocevoli** [comment]
`tangle.p` is an essential part, i.e., you should try to fix the build issue.

**Comment by sumitd2** [comment]
@flowchartsman Were you able to resolve this? Thanks.

**Comment by aDramaQueen** [comment]
I just ran into this today. This is an encoding problem.
For reasons (?!?) the generated Pascal files from the `.web` files are not ASCII any longer on arm64 systems. `c4p` can't handle this, and throws this error.

For example this is for the `dvicopy.p` but this is the same for other Pascal files as well:

**arm64 (not working):**
curie@my-machine:~/miktex-25.4/build$ file Programs/DviWare/dvicopy/dvicopy.p
Programs/DviWare/dvicopy/dvicopy.p: ISO-8859 text

**x86_64 (works):**
bor@my-other-machine:~/miktex-25.4/build$ file Programs/DviWare/dvicopy/dvicopy.p
Programs/DviWare/dvicopy/dvicopy.p: ASCII text

I see 2 solutions here:
- rewrite `c4p` that it may handle ISO-8859 (this is beyond my knowledge)
- compile the pascal files on a x86_64 system and copy & paste them on to the arm64 system. Additionally you must tinker around with several `CMakeLists.txt` files to prevent overwriting the "good" files (sadly a simple re-encoding from iso-8859 to ascii did not work for me...)

**Comment by sumitd2** [comment]
This worked for us on 25.3:
```
diff --git a/BuildUtilities/c4p/CMakeLists.txt b/BuildUtilities/c4p/CMakeLists.txt
index d0e3aaeaf..352ca1557 100644
--- a/BuildUtilities/c4p/CMakeLists.txt
+++ b/BuildUtilities/c4p/CMakeLists.txt
@@ -7,6 +7,10 @@
 ## without modifications, as long as this notice is preserved.
 
 set(MIKTEX_CURRENT_FOLDER "${MIKTEX_IDE_BUILD_UTILITIES_FOLDER}")
+if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(powerpc|ppc)64le")
+  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsigned-char")
+  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsigned-char")
+endif ()
 
 include_directories(BEFORE
     ${CMAKE_CURRENT_BINARY_DIR}
diff --git a/Programs/TeXAndFriends/Knuth/web/CMakeLists.txt b/Programs/TeXAndFriends/Knuth/web/CMakeLists.txt
index c57156256..9cff69e2d 100644
--- a/Programs/TeXAndFriends/Knuth/web/CMakeLists.txt
+++ b/Programs/TeXAndFriends/Knuth/web/CMakeLists.txt
@@ -7,6 +7,10 @@
 ## without modifications, as long as this notice is preserved.
 
 set(MIKTEX_CURRENT_FOLDER "${MIKTEX_IDE_KNUTH_FOLDER}/web")
+if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(powerpc|ppc)64le")
+  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsigned-char")
+  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsigned-char")
+endif ()
 
 include_directories(BEFORE
     ${CMAKE_CURRENT_BINARY_DIR}
```

**Comment by aDramaQueen** [comment]
Holy moly..., that actually worked!

I had to add my CPU architecture: `CMAKE_SYSTEM_PROCESSOR MATCHES "^(powerpc|ppc)64le|aarch64"`

But beyond that, really nice! Thank you, good sir.

This should definitly be a PR. I spent the entiere day yesterday & had to sacrifice a goat to the dark gods to find this issue. No one will see this, and this may potentially helpful to others.
