### ISSUE TITLE
spell checker is missing

### ISSUE THREAD

**Issue by Burdzy77** [MiKTeX/miktex#1448]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I downloaded and installed Miktex. The spellchecker is missing. In my previous installations (years ago) spellchecker was installed automatically. Is this a bug or do I have to install the spellchecker via a separate procedure?

**Comment by edocevoli** [comment]
I am not sure I understand the issue. What program do you use? Please help me to reproduce the issue.

Closing the issue for now.

**Comment by Burdzy77** [comment]
Detailed description of the problem:
1. I installed Miktex on my new laptop (Win 11) using the installer on this [page](https://miktex.org/download).
2. TeXworks is one of the elements of the system installed on my laptop.
3. When I go to the tab "Edit" and then "Spelling", all I see is "None".
4. When I go to "Edit", then "Preferences", then to the tab "Editor" and "Spell-check language", all I can see is "None".
5. When I open Miktex console and then click on "Packages", the spellchecker "hunspell" is not listed.

**Comment by edocevoli** [comment]
this has been fixed
