### ISSUE TITLE
Why did I set cmake -B... /tex CMAKE_INSTALL_PREFIX='opt/miktex' WITH_UI_QT=ON, but there is still no graphical interface, so what does QT do?

### ISSUE THREAD

**Issue by c61292558** [MiKTeX/miktex#1452]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Why did I set cmake -B... /tex CMAKE_INSTALL_PREFIX='opt/miktex' WITH_UI_QT=ON, but there is still no graphical interface, so what does QT do?

OS：LINUX DEEPIN V23

.
└── usr
    └── local
        ├── bin
        │   ├── cfg
        │   ├── cjklatex
        │   ├── findtexmf
        │   ├── gsf2pk
        │   ├── initexmf
        │   ├── md5walk
        │   ├── miktex
        │   ├── miktex-afm2tfm
        │   ├── miktex-autosp
        │   ├── miktex-axohelp
        │   ├── miktex-bg5conv
        │   ├── miktex-bibsort
        │   ├── miktex-bibtex
        │   ├── miktex-bibtex8
        │   ├── miktex-bibtexu
        │   ├── miktex-cef5conv
        │   ├── miktex-cefconv
        │   ├── miktex-cefsconv
        │   ├── miktex-cfftot1
        │   ├── miktex-chktex
        │   ├── miktex-console
        │   ├── miktex-ctangle
        │   ├── miktex-ctwill
        │   ├── miktex-ctwill-refsort
        │   ├── miktex-ctwill-twinx
        │   ├── miktex-cweave
        │   ├── miktex-devnag
        │   ├── miktex-dvicopy
        │   ├── miktex-dvipdfmx
        │   ├── miktex-dvipdft
        │   ├── miktex-dvipng
        │   ├── miktex-dvips
        │   ├── miktex-dvisvgm
        │   ├── miktex-dvitype
        │   ├── miktex-epsffit
        │   ├── miktex-epstopdf
        │   ├── miktex-eptex
        │   ├── miktex-euptex
        │   ├── miktex-extconv
        │   ├── miktex-fribidixetex
        │   ├── miktex-gftodvi
        │   ├── miktex-gftopk
        │   ├── miktex-gftype
        │   ├── miktex-gregorio
        │   ├── miktex-hbf2gf
        │   ├── miktex-hishrink
        │   ├── miktex-histretch
        │   ├── miktex-hitex
        │   ├── miktex-kpsewhich
        │   ├── miktex-lacheck
        │   ├── miktex-lua
        │   ├── miktex-luac
        │   ├── miktex-luahbtex
        │   ├── miktex-luatex
        │   ├── miktex-makebase
        │   ├── miktex-makefmt
        │   ├── miktex-makeindex
        │   ├── miktex-makemf
        │   ├── miktex-makepk
        │   ├── miktex-maketfm
        │   ├── miktex-mf
        │   ├── miktex-mft
        │   ├── miktex-mkocp
        │   ├── miktex-mmafm
        │   ├── miktex-mmpfb
        │   ├── miktex-mpost
        │   ├── miktex-odvicopy
        │   ├── miktex-ofm2opl
        │   ├── miktex-opl2ofm
        │   ├── miktex-otfinfo
        │   ├── miktex-otftotfm
        │   ├── miktex-otp2ocp
        │   ├── miktex-outocp
        │   ├── miktex-ovf2ovp
        │   ├── miktex-ovp2ovf
        │   ├── miktex-patgen
        │   ├── miktex-pdfattach
        │   ├── miktex-pdfdetach
        │   ├── miktex-pdffonts
        │   ├── miktex-pdfimages
        │   ├── miktex-pdfinfo
        │   ├── miktex-pdfseparate
        │   ├── miktex-pdftex
        │   ├── miktex-pdftocairo
        │   ├── miktex-pdftohtml
        │   ├── miktex-pdftoppm
        │   ├── miktex-pdftops
        │   ├── miktex-pdftosrc
        │   ├── miktex-pdftotext
        │   ├── miktex-pdfunite
        │   ├── miktex-pk2bm
        │   ├── miktex-pltotf
        │   ├── miktex-pmxab
        │   ├── miktex-pooltype
        │   ├── miktex-prepmx
        │   ├── miktex-ps2pk
        │   ├── miktex-psbook
        │   ├── miktex-psnup
        │   ├── miktex-psresize
        │   ├── miktex-psselect
        │   ├── miktex-pstops
        │   ├── miktex-rebar
        │   ├── miktex-rungs
        │   ├── miktex-scor2prt
        │   ├── miktexsetup
        │   ├── miktex-sjisconv
        │   ├── miktex-synctex
        │   ├── miktex-t1dotlessj
        │   ├── miktex-t1lint
        │   ├── miktex-t1rawafm
        │   ├── miktex-t1reencode
        │   ├── miktex-t1testpage
        │   ├── miktex-t4ht
        │   ├── miktex-tangle
        │   ├── miktex-testwebapp
        │   ├── miktex-tex
        │   ├── miktex-tex2aspc
        │   ├── miktex-tex4ht
        │   ├── miktex-texworks
        │   ├── miktex-tftopl
        │   ├── miktex-tie
        │   ├── miktex-ttf2afm
        │   ├── miktex-ttf2pk
        │   ├── miktex-ttf2tfm
        │   ├── miktex-ttftotype42
        │   ├── miktex-upbibtex
        │   ├── miktex-updvitype
        │   ├── miktex-upmendex
        │   ├── miktex-uppltotf
        │   ├── miktex-uptftopl
        │   ├── miktex-vftovp
        │   ├── miktex-vptovf
        │   ├── miktex-weave
        │   ├── miktex-xetex
        │   ├── miktex-xml2pmx
        │   ├── mpc
        │   ├── mpm
        │   ├── mthelp
        │   ├── padout
        │   ├── tdsutil
        │   └── texify
        ├── lib
        │   ├── libmetapost-backends-static.a
        │   ├── libmetapost-core-static.a
        │   ├── libmetapost-extramath-static.a
        │   ├── libmetapost-util-static.a
        │   ├── libmiktex-app.so -> libmiktex-app.so.6
        │   ├── libmiktex-app.so.4.8.0
        │   ├── libmiktex-app.so.6 -> libmiktex-app.so.4.8.0
        │   ├── libmiktex-core.so -> libmiktex-core.so.30
        │   ├── libmiktex-core.so.30 -> libmiktex-core.so.4.23.0
        │   ├── libmiktex-core.so.4.23.0
        │   ├── libmiktex-extractor.so -> libmiktex-extractor.so.2
        │   ├── libmiktex-extractor.so.2 -> libmiktex-extractor.so.4.1.0
        │   ├── libmiktex-extractor.so.4.1.0
        │   ├── libmiktex-fmt.so -> libmiktex-fmt.so.4
        │   ├── libmiktex-fmt.so.4 -> libmiktex-fmt.so.4.3.0
        │   ├── libmiktex-fmt.so.4.3.0
        │   ├── libmiktex-kpathsea.so -> libmiktex-kpathsea.so.5
        │   ├── libmiktex-kpathsea.so.4.3.0
        │   ├── libmiktex-kpathsea.so.5 -> libmiktex-kpathsea.so.4.3.0
        │   ├── libmiktex-loc.so -> libmiktex-loc.so.1
        │   ├── libmiktex-loc.so.1 -> libmiktex-loc.so.1.0.0
        │   ├── libmiktex-loc.so.1.0.0
        │   ├── libmiktex-lua53.so -> libmiktex-lua53.so.1
        │   ├── libmiktex-lua53.so.1 -> libmiktex-lua53.so.4.1.1
        │   ├── libmiktex-lua53.so.4.1.1
        │   ├── libmiktex-md5.so -> libmiktex-md5.so.4.0.0
        │   ├── libmiktex-md5.so.4.0.0 -> libmiktex-md5.so.4.0.0.0.1
        │   ├── libmiktex-md5.so.4.0.0.0.1
        │   ├── libmiktex-metapost.so
        │   ├── libmiktex-packagemanager.so -> libmiktex-packagemanager.so.11
        │   ├── libmiktex-packagemanager.so.11 -> libmiktex-packagemanager.so.4.10.0
        │   ├── libmiktex-packagemanager.so.4.10.0
        │   ├── libmiktex-poppler-Qt.so -> libmiktex-poppler-Qt.so.4
        │   ├── libmiktex-poppler-Qt.so.4 -> libmiktex-poppler-Qt.so.4.1.0
        │   ├── libmiktex-poppler-Qt.so.4.1.0
        │   ├── libmiktex-poppler.so -> libmiktex-poppler.so.4
        │   ├── libmiktex-poppler.so.4 -> libmiktex-poppler.so.4.1.0
        │   ├── libmiktex-poppler.so.4.1.0
        │   ├── libmiktex-ptexenc.so -> libmiktex-ptexenc.so.3
        │   ├── libmiktex-ptexenc.so.1.7.0
        │   ├── libmiktex-ptexenc.so.3 -> libmiktex-ptexenc.so.1.7.0
        │   ├── libmiktex-res.so -> libmiktex-res.so.1
        │   ├── libmiktex-res.so.1 -> libmiktex-res.so.1.0.0
        │   ├── libmiktex-res.so.1.0.0
        │   ├── libmiktex-setup.so -> libmiktex-setup.so.6
        │   ├── libmiktex-setup.so.5.5.0
        │   ├── libmiktex-setup.so.6 -> libmiktex-setup.so.5.5.0
        │   ├── libmiktex-teckit.so -> libmiktex-teckit.so.2
        │   ├── libmiktex-teckit.so.2 -> libmiktex-teckit.so.4.0.0
        │   ├── libmiktex-teckit.so.4.0.0
        │   ├── libmiktex-texmf.so -> libmiktex-texmf.so.8
        │   ├── libmiktex-texmf.so.4.8.0
        │   ├── libmiktex-texmf.so.8 -> libmiktex-texmf.so.4.8.0
        │   ├── libmiktex-trace.so -> libmiktex-trace.so.5
        │   ├── libmiktex-trace.so.4.0.0
        │   ├── libmiktex-trace.so.5 -> libmiktex-trace.so.4.0.0
        │   ├── libmiktex-ui-Qt.so -> libmiktex-ui-Qt.so.2
        │   ├── libmiktex-ui-Qt.so.2 -> libmiktex-ui-Qt.so.4.3.0
        │   ├── libmiktex-ui-Qt.so.4.3.0
        │   ├── libmiktex-util.so -> libmiktex-util.so.5
        │   ├── libmiktex-util.so.4.3.0
        │   ├── libmiktex-util.so.5 -> libmiktex-util.so.4.3.0
        │   ├── libmiktex-web2c.so -> libmiktex-web2c.so.2
        │   ├── libmiktex-web2c.so.2 -> libmiktex-web2c.so.4.2.0
        │   └── libmiktex-web2c.so.4.2.0
        ├── libexec
        │   └── miktex
        └── share
            ├── applications
            ├── man
            ├── miktex-texmf
            ├── pixmaps
            └── polkit-1

**Comment by edocevoli** [comment]
Qt is cross-platform software for creating graphical user interfaces.

**Comment by c61292558** [comment]
> Qt is cross-platform software for creating graphical user interfaces.

I know, but what's the role in this project?
The miktex programs I compiled were just console programs.
How to compile qt graphical interface program in miktex project?
