### ISSUE TITLE
Problem with the french option of babel

### ISSUE THREAD

**Issue by drjaramillo** [MiKTeX/miktex#146]
I’m having a problem with a fresh MikTeX 2.9.6637 installation when using the french option of babel. 
This latex file:

```
\documentclass[11pt, a4paper]{article}
\usepackage[french]{babel}
\usepackage[utf8]{inputenc}
\begin{document} 
Text
\end{document}
```
Shows a window with the message “MiKTeX encountered an internal error” and then another window appears with the message “The required file tex\latex\frenchle\french.ldf is missing. It’s a part of the following package: frenchle”

I don’t know why this appears, the french option of babel should call the babel-french package of Daniel Flipo and not the deprecated frenchle package. As frenchle is deprecated I understand that is no longer present in the distribution but I don’t understand why MiKTeX tries to look for this package. 

I don’t know either how to solve this problem.

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information. Please update your installation and try again.

**Comment by drjaramillo** [comment]
I have already updated the installation, that’s why I write “a fresh MikTeX 2.9.6637 installation”. What other information do you need?

**Comment by edocevoli** [comment]
https://miktex.org/faq/
