### ISSUE TITLE
Error: "FATAL pdflatex.core - Function: fread"

### ISSUE THREAD

**Issue by sam-161** [MiKTeX/miktex#1460]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hi,

I installed TeXStudio and MiKTeX the other day and did an update on MiKTeX today. Creating the pdf worked fine for a few times, but suddenly it stopped working. This is the error message I am getting:
>Sorry, but pdflatex.exe did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\xxx\AppData\Local\MiKTeX\miktex\log\pdflatex.log
Process exited with error(s)

The mentioned log contains the following:

>2024-03-13 16:56:13,635+0100 INFO  pdflatex - this process (4600) started by texstudio in directory C:\Users\... - Report with command line: pdflatex.exe -synctex=1 -interaction=nonstopmode Hauptdokument.tex
> 2024-03-13 16:56:13,635+0100 INFO  pdflatex - running on Windows 10.0.22631
> 2024-03-13 16:56:13,638+0100 INFO  pdflatex - this is MiKTeX-PDFTEX 4.19.0 (1.40.26) (MiKTeX 24.3)
> 2024-03-13 16:56:13,644+0100 INFO  pdflatex - allowing known shell commands
> 2024-03-13 16:56:20,251+0100 FATAL pdflatex.core - Invalid argument
> 2024-03-13 16:56:20,251+0100 FATAL pdflatex.core - Function: fread
> 2024-03-13 16:56:20,251+0100 FATAL pdflatex.core - Result: 22
> 2024-03-13 16:56:20,251+0100 FATAL pdflatex.core - Data: <no data>
> 2024-03-13 16:56:20,251+0100 FATAL pdflatex.core - Source: Libraries\MiKTeX\TeXAndFriends\inputline.cpp:82
> 2024-03-13 16:56:20,251+0100 FATAL pdflatex - Invalid argument
> 2024-03-13 16:56:20,251+0100 FATAL pdflatex - Info: 
> 2024-03-13 16:56:20,251+0100 FATAL pdflatex - Source: Libraries\MiKTeX\TeXAndFriends\inputline.cpp
> 2024-03-13 16:56:20,251+0100 FATAL pdflatex - Line: 82
> 2024-03-13 16:56:20,253+0100 INFO  pdflatex - this process (4600) finishes with exit code 1
> 2024-03-13 16:56:20,254+0100 WARN  pdflatex.core - still open: Hauptdokument.aux
> 2024-03-13 16:56:20,255+0100 WARN  pdflatex.core - still open: Hauptdokument.nlo
> 2024-03-13 16:56:20,255+0100 WARN  pdflatex.core - still open: Hauptdokument.pdf
> 2024-03-13 16:56:20,255+0100 WARN  pdflatex.core - still open: Hauptdokument.toc
> 2024-03-13 16:56:20,255+0100 WARN  pdflatex.core - still open: Hauptdokument.out
> 2024-03-13 16:56:20,255+0100 WARN  pdflatex.core - still open: Hauptdokument.tex
> 2024-03-13 16:56:20,255+0100 WARN  pdflatex.core - still open: Hauptdokument.log

Can anybody help with this? I would think that this is somehow related to the function "fread", but I couldn't find anything about it.

Edit: Some readibility things. Also, please let me know what other logs are needed, then I will add them

**Comment by edocevoli** [comment]
I was not able to reproduce the issue.
