### ISSUE TITLE
Issue with function fread

### ISSUE THREAD

**Issue by sam-161** [MiKTeX/miktex#1463]
I was not able to reproduce the issue.

_Originally posted by @edocevoli in https://github.com/MiKTeX/miktex/issues/1460#issuecomment-2002401830_
            

Hi,
unfortunately I was not able to reply in the original issue, as it was closed. I am not surprised this was not possible to reproduce, I do not know what caused the issue. It would be great if I could get some support however, maybe some information on the function or so. I am happy to provide information if asked for.
Best,
Sam

**Comment by edocevoli** [comment]
Sorry, but this is an issue specific to your system: For some reason, the input file cannot be read. I am afraid I cannot help you with this.
