### ISSUE TITLE
spell checker is missing 

### ISSUE THREAD

**Issue by Burdzy77** [MiKTeX/miktex#1466]
- [ x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Please reopen "spell checker is missing #1448".
I uninstalled MikTex and installed it again.
The issue persists exactly as described in #1448

**Comment by edocevoli** [comment]
Nope, it works:

![Screenshot 2024-03-18 194739](https://github.com/MiKTeX/miktex/assets/20090840/7c6bd9f1-c93c-4af6-a3b0-41b21c6d6e2d)
