### ISSUE TITLE
spell checker is missing (re #1466)

### ISSUE THREAD

**Issue by Burdzy77** [MiKTeX/miktex#1467]
- [ x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I am writing regarding "spell checker is missing" #1466
The spellchecker is not working for me after the reinstallation of MikTex. I guess that
neither Win 11 nor the MikTex console properly uninstalled the old version of MikTex.
I have noticed that after uninstallation some MikTex directories were remaining.
What is the best way to make sure that the new installation is clean
and the old settings do not prevent me from using the spellchecker?

**Comment by edocevoli** [comment]
Honestly, I don't know how to clean your setup. Sorry, I am afraid I cannot help you with this. Feel free to add additional comments. But please note that I am not watching this issue once it is closed.
