### ISSUE TITLE
miktex-console cannot be launched due to Qt platform plugin issue

### ISSUE THREAD

**Issue by haimingz** [MiKTeX/miktex#1469]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I just installed the latest miktex on my Linux desktop according to the [official instructions](https://miktex.org/download).

Then it seems the miktex-console can not be launched. The error message is as follows:

```bash
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

I am using pop! os 22.04

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/14703123/miktex-report.txt)

**Comment by CastleStar14654** [comment]
Seems to be the problem of 24.3. Install 23.12 should be OK.

**Comment by OlivierTourmente** [comment]
Hello, 

I have a similar problem, since yesterday at least the Miktex console does not appear when I click on the icon (Ubuntu 22.04). I looked on the Miktex webiste but they seems to propose only the latest version. How can I go back to an older version ? 

Thanks

**Comment by CastleStar14654** [comment]
> Hello,
> 
> I have a similar problem, since yesterday at least the Miktex console does not appear when I click on the icon (Ubuntu 22.04). I looked on the Miktex webiste but they seems to propose only the latest version. How can I go back to an older version ?
> 
> Thanks

`sudo apt install miktex=23.12-jammy1`

**Comment by OlivierTourmente** [comment]
> > Hello,
> > I have a similar problem, since yesterday at least the Miktex console does not appear when I click on the icon (Ubuntu 22.04). I looked on the Miktex webiste but they seems to propose only the latest version. How can I go back to an older version ?
> > Thanks
> 
> `sudo apt install miktex=23.12-jammy1`

That works ! 

Many thanks !

**Comment by haimingz** [comment]
> > Hello,
> > I have a similar problem, since yesterday at least the Miktex console does not appear when I click on the icon (Ubuntu 22.04). I looked on the Miktex webiste but they seems to propose only the latest version. How can I go back to an older version ?
> > Thanks
> 
> `sudo apt install miktex=23.12-jammy1`

That solves my problem. Thanks!

**Comment by CastleStar14654** [comment]
Hi, I've just found that install `qt6-wayland` could fix the problem of v24.3 @haimingz  @OlivierTourmente

**Comment by chdebernardi** [comment]
sudo apt-get install qt6-qpa-plugins 

after qt6-wayland and it's works for me

**Comment by CastleStar14654** [comment]
> sudo apt-get install qt6-qpa-plugins
> 
> after qt6-wayland and it's works for me

Thanks! It works for my desktop, too.

**Comment by xfgt** [comment]
Thank you too people, you helped me as well!

**Comment by emalizia** [comment]
Hi.
A similar problem is on Windows 10 as well. I've just updated miktex via the console. The only package that was going to be substituted was miktek-qt something (it was noted on the console that the package needed to be "repaired"). After the update, the console does not start any longer, and I cannot even uninstal miktex, because when I attempt to do it I get the same problem with the qt plugin.

**Comment by asimard1** [comment]
> sudo apt-get install qt6-qpa-plugins

This made everything work thank you <3
