### ISSUE TITLE
Cannot compile files with "~" in the path name

### ISSUE THREAD

**Issue by paddlix** [MiKTeX/miktex#1471]
Dear ladies and gentlemen,

I'm using MikTex with macOS. Unfortunately I wanted to compile files which are located in the iCloud Drive, which's file path contains the "\~" symbol, due to apple's folder structure.

For simpler reproduction, just do the following:
1. Create a new folder, which's name contains the "\~" symbol (e.g. "My\~LaTeX\~Folder").
2. Inside that folder, create a valid LaTeX file (or use the attached "latex.txt" file).
3. Open the console and change the working directory to NOT be the one where the LaTeX file is located (e.g. use "/").
4. Run "pdflatex <...>/My\~LaTeX\~Folder/latex.txt".

The Problem also occurs when the LaTeX file's name itself contains the "\~" symbol (e.g. "lat\~ex.txt").

System information:
- macOS Sonoma 14.1
- m1 Pro macbook pro
- [miktex-report.txt](https://github.com/MiKTeX/miktex/files/14742489/miktex-report.txt)

Log: [texput.log](https://github.com/MiKTeX/miktex/files/14742597/texput.log)
LaTeX file: [latex.txt](https://github.com/MiKTeX/miktex/files/14742622/latex.txt)

**Comment by u-fischer** [comment]
> 3\. Open the console and change the working directory to NOT be the one where the LaTeX file is located (e.g. use "/").

Unrelated to the issue but you normally shouldn't do that. It can break relativ input pathes in your document. And if you use a root folder or some other folder with restrictions it can even happen that auxiliary files can't be correctly written.  I always start every compilation from the document folder.
