### ISSUE TITLE
Bug in pdflatex.exe (as opposed to miktex-pdftex -undump=pdflatex): missing line in PDF

### ISSUE THREAD

**Issue by nhabedi** [MiKTeX/miktex#1474]
I could finally isolate a small test case for a problem that I've had for years but that was hard to reproduce with a few lines.  The issue is that `miktex-pdftex.exe -undump=pdflatex test.tex` and `pdflatex.exe test.tex` produce different PDFs from the same source file and the one produced by the latter is faulty - there's a line missing.  The attached ZIP file [MWE.zip](https://github.com/MiKTeX/miktex/files/14893132/MWE.zip) contains the test case, the two different outputs, the two log files and information about my setup (MikTeX 2.9 on Windows 10, updated yesterday).

Just to make sure: This is not a viewer issue.  The line is missing in SumatraPDF, Acrobat Reader, and other viewers and the PDF files are actually different.  The relevant difference looks like this:

    [(Erst)-250(im)-250(20.)-250(Jahrhundert)-250(kam)-250(die)-250(v)8(olle)-250(W)60(ahrheit)-250(ans)-250(Licht.)-250(Die)]

    [(Erst)]TJ -32626.8 0 Td [(im)-250(20.)-250(Jahrhundert)-250(kam)-250(die)-250(v)8(olle)-250(W)60(ahrheit)-250(ans)-250(Licht.)-250(Die)]

For related information, see also [this question](https://tex.stackexchange.com/questions/714907/text-disappearing-in-miktex) at Stack Exchange.

**Comment by edocevoli** [comment]
I cannot reproduce this. Both PDFs seem to be identical in my eyes.
Your log files show that you are using different memory settings:
```
592261 words of font info for 70 fonts, out of 2000000 for 9000
```
vs
```
592261 words of font info for 70 fonts, out of 8000000 for 9000
```

[test_miktex-pdftex.pdf](https://github.com/MiKTeX/miktex/files/14893258/test_miktex-pdftex.pdf)
[test_pdflatex.pdf](https://github.com/MiKTeX/miktex/files/14893259/test_pdflatex.pdf)

**Comment by nhabedi** [comment]
Digging through my old e-mails, maybe I found the culprit.  Years ago, I did this (following some advice from someone I forgot):

    initexmf --edit-config-file pdflatex

Add this to the file and save it:

    pool_size=5000000
    main_memory=6000000
    extra_mem_bot=2000000
    font_mem_size=2000000

Then run this:

    initexmf --dump=pdflatex

With these settings, I get the error.  If I repeat the process with an empty config file, the error is gone.
