### ISSUE TITLE
MiKTeX support for Fedora 40

### ISSUE THREAD

**Issue by LuisMi1245** [MiKTeX/miktex#1481]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

`$ sudo dnf install miktex`

Last metadata expiration check performed 0:00:07, 23 abr 2024 15:16:00.
Error: 
 Problem: conflicting requests
  - nothing provides libboost_locale.so.1.81.0()(64bit) needed by miktex-23.12-1.fc39.x86_64 from miktex-fedora-39
  - nothing provides libboost_chrono.so.1.81.0()(64bit) needed by miktex-23.12-1.fc39.x86_64 from miktex-fedora-39
  - nothing provides libboost_thread.so.1.81.0()(64bit) needed by miktex-23.12-1.fc39.x86_64 from miktex-fedora-39
  - nothing provides libboost_locale.so.1.81.0()(64bit) needed by miktex-24.3-1.fc39.x86_64 from miktex-fedora-39
  - nothing provides libboost_chrono.so.1.81.0()(64bit) needed by miktex-24.3-1.fc39.x86_64 from miktex-fedora-39
  - nothing provides libboost_thread.so.1.81.0()(64bit) needed by miktex-24.3-1.fc39.x86_64 from miktex-fedora-39
(try adding '--skip-broken' to discard packages that can't be installed)

Fedora 40 has updated the following software levels:

libboost_*.so.1.81.0 -> libboost_*.so.1.83.0

Please provide an update for Fedora 40.

**Comment by scorpionTaj** [comment]
We Want Is as soon as you can  ⬆️ 🚀
