### ISSUE TITLE
QT plugin could not be initialized

### ISSUE THREAD

**Issue by pere73** [MiKTeX/miktex#1487]
This issue is also described [here](https://github.com/MiKTeX/miktex/issues/1469), but for Linux. It appears on Windows as well.

I have updated successfully to the last MikTeX version 24.4 (Portable Version). However, if I now call up the MikTeX console, the following error message appears:

![2024-04-30 06 55 16](https://github.com/MiKTeX/miktex/assets/60961817/316b495b-b67c-44bc-b76e-3de9ca5484d5)

The error appears on Windows 11 (with latest updates) as well as on Windows 10.

I can reproduce the error:

- Restoring to version 24.3.31 --> Starting the MikTeX-console works --> GUI appears
- Perform the update via the GUI --> Ok
- Starting the MikTeX-console again after the update  --> above mentioned error

**Comment by edocevoli** [comment]
Thank you. I was not able to reproduce this. Since there are no log files, I cannot work on this issue effectively.
