### ISSUE TITLE
miktex-console failed to start  because no Qt platform plugin could be initialized. 

### ISSUE THREAD

**Issue by marcohernandez-git** [MiKTeX/miktex#1489]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
I updated MikTex today, and now the miktex-console fails to start and I get an error windows with the message "application failed to start  because no Qt platform plugin could be initialized,..". MikTex works, just the miktex-console fails to start after the update. I submit the miktex-report and logs. 
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/15160716/miktex-report.txt)
[log.zip](https://github.com/MiKTeX/miktex/files/15160720/log.zip)

**Comment by tfrank1971** [comment]
same for me (#1488)

**Comment by edocevoli** [comment]
Maybe another Qt6 installation is in the way. Please open a command prompt and enter

```
set PATH=%USERPROFILE%\AppData\Local\Programs\MiKTeX\miktex\bin\x64;%PATH%
miktex-console.exe
```

**Comment by edocevoli** [comment]
Please also try this workaround: https://github.com/MiKTeX/miktex/issues/1486#issuecomment-2084843465

**Comment by tfrank1971** [comment]
ok, confirmed, it works. 
Thanks!

**Comment by marcohernandez-git** [comment]
Yes, the workaround works. 
Thank you very much.

**Comment by twahz** [comment]
Same problem, don't know how to fix it at the moment

**Comment by twahz** [comment]
Go to this website
[](https://ctan.net/systems/win32/miktex/tm/packages/)
download miktex-qt6-bin-x64.tar.lzma
Unzip and copy to the appropriate folder

**Comment by creator1creeper1** [comment]
I just encountered this issue. The workaround from #1486 of running `miktex --admin packages update` worked for me. I don't understand why this has been closed though.

**Comment by egorpugin** [comment]
Same error.

**Comment by koppor** [comment]
After an update using the UI, I had this issue. The fix stated at the comment works:

```cmd
c:\>miktex  packages update
Installing package fancyhdr...
Installing package hyperref...
Installing package hyperref__doc...
Installing package latexindent...
Installing package lni...
Installing package luaxml...
Installing package markdown...
Installing package markdown__doc...
Installing package miktex-qt6-bin-x64...
Installing package moderncv...
Installing package moloch...
Installing package reledmac...
Installing package tcolorbox...
```

**Comment by mucahitkayadan** [comment]
> Go to this [(https://ctan.net/systems/win32/miktex/tm/packages/)](https://ctan.net/systems/win32/miktex/tm/packages/) download miktex-qt6-bin-x64.tar.lzma Unzip and copy to the appropriate folder

It opened the UI but gave an error (it was a general error) then I checked and installed updates again, and it disappeared.

**Comment by Rossbert** [comment]
> I just encountered this issue. The workaround from [#1486](https://github.com/MiKTeX/miktex/issues/1486) of running `miktex --admin packages update` worked for me. I don't understand why this has been closed though.

This worked for me

**Comment by nhacki** [comment]
> I just encountered this issue. The workaround from [#1486](https://github.com/MiKTeX/miktex/issues/1486) of running `miktex --admin packages update` worked for me. I don't understand why this has been closed though.

I just had the same issue while trying to open the MikTex console and this solution worked for me. The "cmd update all MikTex packages" solution to be precise.

**Comment by yzut-ydv** [comment]
> miktex --admin packages update

this one also worked for me, without the "--admin" part, because I only installed Miktek for one user.
