### ISSUE TITLE
miktex cannot find fonts after upgrading

### ISSUE THREAD

**Issue by MMMMMoris** [MiKTeX/miktex#1493]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
I use a file called ctex-fontset-adobe2.def to define the fonts I have been using, and use 
```tex
\LoadClass[
    fontset=adobe2, % custom font adobe2
    openany,
    zihao=-4
]{ctexbook}
```
to declare that adobe2 will be the fontset.
Everything works fine until I upgrade my miktex and its package along to the latest version (24.4, miktex console version 4.12).
My tex files can never be compiled successfully ever again, with this error ending up in my terminal
```log
! Package fontspec Error:
(fontspec)                The font "AdobeHeitiStd-Regular" cannot be found;
(fontspec)                this may be but usually is not a fontspec bug.
(fontspec)                Either there is a typo in the font name/file, the
(fontspec)                font is not installed (correctly), or there is a
(fontspec)                bug in the underlying font loading engine
(fontspec)                (XeTeX/luaotfload).

For immediate help type H <return>.
 ...

l.38 \makeUndergraduateCover
```
Just right before I upgrade miktex, there are no any errors.
After upgrading, it tells me that it cannot find a font, which is exactly in the path I have defined in ctex-fontset-adobe2.def.
Here is how it looks
```tex
\ProvidesExplFile{ctex-fontset-adobe2.def}
  {\ExplFileDate}{2.5.6}{\ExplFileDescription}
\setCJKmainfont  { AdobeSongStd-Light.otf }
  [
    Path=./fonts/,
    BoldFont   = AdobeHeitiStd-Regular.otf,
    ItalicFont = AdobeKaitiStd-Regular.otf
  ]
```
I didn't even make a change to my source code, this error just bumped up and wastes me a lot of time.
I cannot find a solution. Is this a bug or there are something new that I have to setup?

**Comment by MMMMMoris** [comment]
Output of `initexmf --report> miktex-report.txt`
```log
ReportDate: 2024-05-08 01:12:52
CurrentVersion: 24.4
SetupDate: 2024-03-26 12:25:00
SetupVersion: 24.1
Configuration: Regular
GitInfo: e3580c6 / 2024-04-27 18:01:25
OS: Windows 10.0.22631
SharedSetup: no
LinkTargetDirectory: C:\Users\admin\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2024-05-07 23:54:38
LastUpdate: 2024-05-07 23:56:57
LastUpdateDb: 2024-05-07 23:54:35
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\admin\AppData\Roaming\MiKTeX
Root1: C:\Users\admin\AppData\Local\MiKTeX
Root2: C:\Users\admin\AppData\Local\Programs\MiKTeX
UserInstall: C:\Users\admin\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\admin\AppData\Roaming\MiKTeX
UserData: C:\Users\admin\AppData\Local\MiKTeX
```
Here is miktex-maketfm.log
[miktex-maketfm.log](https://github.com/MiKTeX/miktex/files/15238818/miktex-maketfm.log)

**Comment by edocevoli** [comment]
This is not a MiKTeX-specific bug. Please wait, until the bug is fixed elsewhere.
