### ISSUE TITLE
Typo in dialogue Package information/Files window

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex#150]
The 'Package information' window has a typo in the 'Files' tab. The second title is missing a 't' and reads 'Documentaion'.

To reproduce
1. Open the MikTeX Console
2. Choose User mode
3. Go to *Packages*
4. Right click on any package and select 'Package information'
5. Go to 'Files' in the window that just popped up

MikTeX Console 2.9.6703.

![documentaion](https://user-images.githubusercontent.com/6755835/41806670-dcb62c18-76c2-11e8-8074-2732371770f8.PNG)

**Comment by edocevoli** [comment]
This will be fixed with [milestone 2.9.6730](https://github.com/MiKTeX/miktex/milestone/6).
