### ISSUE TITLE
MiKTeX and its packages can't be downloaded from my country unless I use a VPN

### ISSUE THREAD

**Issue by HusseinBaraja** [MiKTeX/miktex#1505]
- [ x ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
  I encountered an issue while following the Manim installation guide for Windows from the Manim Community documentation. The problem happened when I tried downloading and installing MiKTeX and its packages.

**Steps to Reproduce:**

1. Open the official download page for MiKTeX.
2. Download the windows version of MiKTeX from my location in Kuwait.
4. The webpage loads for a while (around 45s), then displays "The connection has timed out."
5. Attempt to download MiKTeX using alternative methods such as Winget and Chocolatey. This results in various errors.
6. Use a VPN to change the IP address from Kuwait to the USA.
7. Retry the download after enabling a VPN, then the download completes successfully.
8. Inside MiKTeX: attempt to install the "preview" package.
9. The package installation fails unless the VPN is enabled.

**Expected Result:** MiKTeX and its packages should download and install without requiring a VPN.

**Actual Result:** Downloads and installations fail unless a VPN is used to change the IP address.

It appears that the issue is related to my location (Kuwait). I would like to know if there are any solutions to this problem that do not involve using a VPN, as I am currently using a free trial VPN and do not wish to subscribe to a paid service.

Thx a lot, and have a nice day/night.
Note: Sorry if the issue format is not correct, I'm new and I tried my best to follow the how to bug report guide

**Comment by hasan-alj88** [comment]
I have the same problem, in addtion I cant use VPN in my Microsoft Surface so I get connection timeout every time.
Should I raise new Issue?
