### ISSUE TITLE
New Error Message

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#152]
The following error message was issued when I was updating. I am not sure what, if anything, to do.

MiKTeX Problem Report
Message: The executed process did not succeed.
Data: fileName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\initexmf.exe", exitCode="1"
Source: Libraries\MiKTeX\Core\Process\Process.cpp
Line: 177
MiKTeX: 2.9
OS: Windows 10 Pro, 64-bit, build 17134
Invokers: non-existing
SystemAdmin: yes
PowerUser: no
Root0: C:\Users\Gerard\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Gerard\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Gerard\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Gerard\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Gerard\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.
You can try it again tomorrow. If the problem still exists: collect log files, screenshots etc.
Reminder: Your job is to enable me to reproduce the problem.
