### ISSUE TITLE
Definitive solution for the ugly rendering of TeXworks: updating libraries

### ISSUE THREAD

**Issue by SSebastiano** [MiKTeX/miktex#1520]
Bug description: yet is evident the bad rendering with TeXworks v. 0.6.9.(https://raw.githubusercontent.com/TeXworks/texworks/release-0.6.9/NEWS).

Steps to reproduce the problem:

**Compiling an any .tex file with TeXworks 0.6.9. I have an ugly output with the preview of TeXworks**

Expected behavior:
Correct visualization.

General information:
TeXworks version: 0.6.9.
TeXworks obtained from: MikTeX of 2024-08-06
Operating system: Windows 10

Additional information: To see the website at link https://tex.stackexchange.com/questions/707606/ugly-rendering-of-the-output-visualization-of-texworks. I add also the question no solved #1037; it has been closed without resolve the problem. Here the following issue in this link: https://github.com/TeXworks/texworks/issues/1056.

**Comment by edocevoli** [comment]
Thank you. The issue description is a little vague. If you mean the poppler library: MiKTeX includes the latest major poppler version: 24.

**Comment by SSebastiano** [comment]
@edocevoli (related @tbackdahl  @stloeffler@jacobgellman)  You're welcome. Why my issue has been closed? The problem of the preview of TeXworks yet is visible. You can see that the image not has a good rendering (see the image).
![Immagine](https://github.com/user-attachments/assets/91e95af3-b1df-41ef-9a9a-dc4faf883eb3)

Related: https://github.com/TeXworks/texworks/issues/1056, https://github.com/TeXworks/texworks/issues/1037, https://github.com/MiKTeX/miktex/issues/1435,

**Comment by jacobgellman** [comment]
I agree, the rendering issue raised by @SSebastiano still persisted for me. I had to downgrade to an earlier version of TeXWorks (version 0.6.7).
