### ISSUE TITLE
MikteX Console and TeXworks suddenly change theme after updating (Windows-specific)

### ISSUE THREAD

**Issue by abhi-deshpande** [MiKTeX/miktex#1523]
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Issue :**
On fresh installations on Windows OS, when an update to all packages is performed, both the MikTeX Console and TeXworks app change their theme to dark mode, if system's theme is set to dark. This may be due to the Qt theme engine(>=6.5) running with the default `-style windows` flag. But, as these dark themes are not much polished, I prefer to use regular light one. Unfortunately, there is no option for changing theme/mode in both of these programs.

**Expected Behaviour :**
This is not really an unexpected behaviour, but implementing an option to change theme/mode would be more helpful.

**Current Workaround :**
Currently, I have edited the shortcuts to get light mode. To do this -
1. Go to start menu > MiKTeK Console OR TeXworks
2. Right Click > Open file location
3. Right Click on shortcut > Properties
4. Add `-style windowsvista` to Target path
5. Apply & OK

**Comment by Gyarmiago** [comment]
I have the exact same problem right now. I tried to update miktex but it switches to dark theme anytime I download it again.
