### ISSUE TITLE
Debian: Although PATH is set, miktex does not find it

### ISSUE THREAD

**Issue by scheini1972** [MiKTeX/miktex#1525]
I installed miktex on Debian 12 and wanted to use it systemwide. However , allthough I set the PATH correctly /opt/Miktex/bin, Miktex is still saying I do have a PATH Problem. 

I do have the texlive-package from Debian installed.

Miktex-console tells me this
2024-08-31 06:34:57,538+0200 INFO  miktex-console.core - forking...
2024-08-31 06:34:57,548+0200 ERROR miktex-console.core - Something is wrong with the PATH:
2024-08-31 06:34:57,549+0200 ERROR miktex-console.core - /usr/sbin:/usr/bin:/sbin:/bin:/root/bin

Path is set for root and user to PATH="/opt/Miktex/bin:$PATH"

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
[miktex-report.txt](https://github.com/user-attachments/files/16823494/miktex-report.txt)

**Comment by edocevoli** [comment]
As shown in the log, `/opt/Miktex/bin` is not in the path.

**Comment by scheini1972** [comment]
I know it's not shown in the report log. But the Path is clear set for User and Root in /etc/profile and in each user .bashrc. 
Exactly this is the issue.

**Comment by scheini1972** [comment]
Please see comment

--
✉: ***@***.******@***.***>
☏: +49 (8272) 803 111
📱: +49 (1515) 37 97 811
________________________________
Von: Christian Schenk ***@***.***>
Gesendet: Saturday, August 31, 2024 11:29:24 AM
An: MiKTeX/miktex ***@***.***>
Cc: Dieter Scheinkönig ***@***.***>; Author ***@***.***>
Betreff: Re: [MiKTeX/miktex] Debian: Although PATH is set, miktex does not find it (Issue #1525)


Closed #1525<https://github.com/MiKTeX/miktex/issues/1525> as completed.
