### ISSUE TITLE
Donnloading Miktex in Saudi Arabia is not possible 

### ISSUE THREAD

**Issue by almohrrami** [MiKTeX/miktex#1527]
dear all
downloading Miktex in Saudi Arabia is impossible. The downloaded software originates from Iran (ctan.yazd.ac.ir). Please find a way for the people in Saudi Arabia to download from different sources.

**Comment by almohrrami** [comment]
is there a way to download Miktex from a different source than ctan.yazd.ac.ir

**Comment by SpecialCharacter** [comment]
Settings > parcel download > change


Am 03.09.2024 um 21:38 schrieb almohrrami:

**Comment by almohrrami** [comment]
this is the link that shows in the bar when downloading Miktex in Saudi Arabia

https://ctan.yazd.ac.ir/systems/win32/miktex/setup/windows-x64/basic-miktex-24.1-x64.exe

as you see: (ctan.yazd.ac.ir) from Iran
and we cannot download anything from Iran in Saudi Arabia
Please find me a solution

**Comment by almohrrami** [comment]
this is the link that shows in the bar when downloading Miktex in Saudi Arabia

https://ctan.yazd.ac.ir/systems/win32/miktex/setup/windows-x64/basic-miktex-24.1-x64.exe

as you see : (ctan.yazd.ac.ir) from Iran
and we cannot download anything from Iran in Saudi Arabia
Please find me a solution

**Comment by SpecialCharacter** [comment]
And

https://miktex.org/download

does not function?


Am 04.09.2024 um 00:41 schrieb almohrrami:
