### ISSUE TITLE
'tikzGnuPlotpgf-plot.table'

### ISSUE THREAD

**Issue by leanhdung1994** [MiKTeX/miktex#1535]
I have a tikz tex file

    \documentclass[10pt,a5paper]{report}
    \usepackage[x11names,table]{xcolor}
    \usepackage{tikz}
    \usetikzlibrary{math,calc,arrows.meta}
    \pagestyle{empty}
    \begin{document}
        \begin{tikzpicture}[domain=-4:4,>=Latex,x=10.mm,y=1.mm,thick]\scriptsize
            \draw[semithick,->] ([xshift=-10pt]-4, 0) -- ([xshift=10pt] 4, 0) node[right] {$x$};
            \draw[semithick,->] ([yshift=-1pt] 0, -10) -- ([yshift=10pt] 0, 40);
    
            \draw[Firebrick1!80,thick] ([shift={(10pt,10pt)}] 0,40) -- ++(5mm,0) node[right] {\color{black} $y = p(x)$};
            \draw[SteelBlue1,thick,dashed] ([shift={(10pt,0pt)}] 0,40) -- ++(5mm,0) node[right] {\color{black} $y = p'(x)/3$};
            
            \draw[Firebrick1!80,thick,range=-10:40,samples=150]
                plot function{1.*x**4-13.*x**2+36.};
            \draw[SteelBlue1,thick,range=-10:40,samples=100,dashed]
                plot function{(4.*x**3-26.*x)/3.};
    
            \foreach \i in {-4,-2,...,4} \draw (\i,3pt) -- (\i,-3pt)
                node[below,inner sep=2,fill=white,fill opacity=.8,text opacity=1] {\scriptsize$\i$};
            \foreach \i in {-4,-3,...,4} \draw (\i,2pt) -- (\i,-2pt);
            \foreach \i in {-10,0,...,40} \draw (3pt,\i) -- (-3pt,\i)
                node[left,inner sep=2,fill=white,fill opacity=.8,text opacity=1] {\scriptsize$\i$};
            \foreach \i in {-5,5,...,35} \draw (-2pt,\i) -- (2pt,\i);
            \draw node[above left] at (-1.47196,12.5278) {$W_1$}
                node[above right] at (1.47196,12.5278) {$W_2$};
            \filldraw (-1.47196,12.5278) circle(1pt) (1.47196,12.5278) circle(1pt);
        \end{tikzpicture}
    \end{document} 

In Overleaf, this file is compiled without any error nor warning:

[![enter image description here][1]][1]

However, when I use MikTeX to compile it on my laptop, I get

[![enter image description here][2]][2]

and two warnings:

    Package pgf Warning: Plot data file `tikz.pgf-plot.table' not found. on input line 15.
    
    Package pgf Warning: Plot data file `tikz.pgf-plot.table' not found. on input line 17.

My friend also encounters the same problem with MikTeX. Could you elaborate on this issue?

  [1]: https://i.sstatic.net/M67H8nSp.png
  [2]: https://i.sstatic.net/iVWPpoPj.png

**Comment by cpierquet** [comment]
Are you compiling with `shell-escape` (I think gnuplot require this option) ?

Without `shell-escape` :
![image](https://github.com/user-attachments/assets/eab49790-9e91-4ebe-8e5d-57e2a29fa473)

With `shell-escape` enable :
![image](https://github.com/user-attachments/assets/5ddac3a9-6815-4842-a768-fd5966c5c8f1)
