### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by MPV65** [MiKTeX/miktex#154]
Having reinstalled MikTex so that I can download packages, I now get the following message when trying to open some tex documents:

A problem occured while laying out the loaded document in the editor. This is caused by an issue in the underlying Qt framework and can cause TeXworks to crash under certain circumstances.

Suggested work-arounds are given, such as turning line numbering on and off but the message persists. I have seen the same problem on other TeX forums, where it has been closed without answer as it is MikTex specific.

What is a Qt framework?

Also, under the new installation, no log files are produced whilst compiling, so I could not check these for clues.

**Comment by edocevoli** [comment]
I was not reproduce your issue. What I did:

1. Open `mydocument.tex` with TeX works
2. Everything looks okay.

**Comment by MPV65** [comment]
The problem is intermittent - it occurs for some documents and not for others.

**Comment by MPV65** [comment]
Please reopen this issue as it has not been resolved.
