### ISSUE TITLE
broken mirror (ctan.yazd.ac.ir)

### ISSUE THREAD

**Issue by FsFsmk** [MiKTeX/miktex#1543]
The mirror which I am getting redirected to when I try to download anything is timing out

```
ping ctan.yazd.ac.ir -n 1

Pinging ctan.yazd.ac.ir [185.96.240.128] with 32 bytes of data:
Request timed out.

Ping statistics for 185.96.240.128:
    Packets: Sent = 1, Received = 0, Lost = 1 (100% loss),
 ```

I am not sure how the mirror chosen right now but I am guessing it is based on the closest location for lowest latency, well shouldn't it check if the repository is up to begin with?

similar issues that were closed abruptly #1513 #1483 

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
All I can say is that it works for me. Please note that the CTAN team maintains the mirror list. It's not MiKTeX-specific.

**Comment by FsFsmk** [comment]
Just tried with a VPN and it worked, it is probably just blocked here for some reason, still technically speaking you should be able to ping it and if you lose packets then change the mirror
I don't mind opening a PR if I knew which part of the code it is (and to be frank I don't want to bother to read through the codebase since I already got the build)
