### ISSUE TITLE
Build is failing with a curl 404 error

### ISSUE THREAD

**Issue by melosomelo** [MiKTeX/miktex#1545]
I am not able to locally build MiKTeX due to a curl 404 error. I'm using Arch Linux, which I updated just this monday. This is also impacting the [AUR package](https://aur.archlinux.org/packages/miktex), which I tried to install previously. Build output below:

```
[  0%] Generating miktex-zzdb1-2.9.tar.lzma
curl: (22) The requested URL returned error: 404
make[2]: *** [CMakeFiles/gen-bootstrapping-files.dir/build.make:95: miktex-zzdb1-2.9.tar.lzma] Error 22
make[1]: *** [CMakeFiles/Makefile2:4023: CMakeFiles/gen-bootstrapping-files.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

The broken URL seems to be http://ctan.org/tex-archive/systems/win32/miktex/tm/packages//miktex-zzdb3-2.9.tar.lzma. Seems a bit weird to me since it's a win32 URL, and I'm running on Linux. Perhaps I'm missing something? 

Any help is much appreciated. Thanks in advance.

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
This is the package database file. You must make sure that the download succeeds.
