### ISSUE TITLE
Massive pause/lag/freeze just after compilation finishes

### ISSUE THREAD

**Issue by DT-one** [MiKTeX/miktex#1552]
I recently updated the MikTex portable installation I have been using for some time, it was updated from a version released some time in 2023.

First, I had an error related to a missing Qt plugin. That was OK, a google search revealed running an update command in the command line was a fix, which worked fine.

But, once I had MikTex and texworks compiling again, I thought it had crashed. There is this really long pause after compilation completes. I really cannot work out what it is. It has only happened after the update.

I installed a fresh copy of MikTex portable, by downloading the latest installer. The Qt issue didn't arise, but the lag/freeze issue persists. Trying to find an installer for an older version to see if I can revert

This happens even with small documents.

Sorry I cant provide any more information, I really don't have much to go on here. It just pauses for up to a minute every time!

**Comment by DT-one** [comment]
OK Found an old installer on my machine. Reverted back to MikTeX 22.10 Portable and TexWorks V0.6.7, reinstalled required LaTeX packages during compile, and now the freeze/lag is totally gone.

I will be continuing to try new versions of MikTeX from time to time, but will not use them if this lag is still there, Will keep the problem install in case you need me any more information.

Oh its Windows10 64bit, heaps of RAM, 11th gen Intel if that makes a difference.

**Comment by edocevoli** [comment]
> Sorry I cant provide any more information, 

OK

**Comment by DT-one** [comment]
> OK

Uh - Why mark this complete?
The thing freezes - What else can I say?

 Ive found the problem in two installs, I've confirmed a different version doesn't do it, I've kept the old install there to test. What else can I do?
