### ISSUE TITLE
MiKTeX cannot retrieve attributes for the directory

### ISSUE THREAD

**Issue by batuhanyklmz** [MiKTeX/miktex#1563]
Hello,

I use windows 11 

I did fresh setup for miktex but it doesnt work anymore. I was already using it however now i receive this message.

MiKTeX cannot retrieve attributes for the directory 'C:\Users\batuh\AppData\Local\Programs\Python\Python310\Scripts\pip.exe\'.

Could you help me with that?
![image_2024-12-11_170642651](https://github.com/user-attachments/assets/0d722c13-e0f6-4a5d-be31-0d362624a40f)

**Comment by batuhanyklmz** [comment]
[mixtex error.zip](https://github.com/user-attachments/files/18098920/mixtex.error.zip)

**Comment by JGM78** [comment]
I have exactly the same issue:
! Sorry, but C:\Users\[...]\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe did not succeed for the following reason:
! MiKTeX cannot retrieve attributes for the directory 'C:\Program Files\RStudio\resources\app\bin\rpostback.exe\'.

**Comment by JGM78** [comment]
Did you find a solution to this problem?

**Comment by batuhanyklmz** [comment]
> Did you find a solution to this problem?

Hello, I delete all the application with all the extensions manually, and I download again. It works

**Comment by yasante7** [comment]
> I have similar problem, try checking your enviourment. maybe you put and exe in in it, it must contains only directory, not exe

Checking env worked for me
