### ISSUE TITLE
latexmk does not work on fedora, unless perl-cpan in installed manually via dnf

### ISSUE THREAD

**Issue by LaserTee** [MiKTeX/miktex#1567]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Running latexmk on fedora 41 without installing perl-cpan will result in the following error:

```
Can't locate File/Copy.pm in @INC (you may need to install the File::Copy module) (@INC entries checked: /home/jawa/.miktex/texmfs/install/scripts/latexmk/ /usr/local/lib64/perl5/5.40 /usr/local/share/perl5/5.40 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/jawa/.miktex/texmfs/install/scripts/latexmk/latexmk.pl line 56.
BEGIN failed--compilation aborted at /home/jawa/.miktex/texmfs/install/scripts/latexmk/latexmk.pl line 56.
```

Installing the perl-File-Copy package from dnf solves this error message, but you will get essentially the same error this time complaining about the Time::HiRes module missing.

Installing the perl-cpan package, i.e. running `sudo dnf install perl-cpan`, seems to fix this issue.

[miktex-report.txt](https://github.com/user-attachments/files/18140728/miktex-report.txt)

**Comment by edocevoli** [comment]
The Perl infrastructure is not a MiKTeX issue; I don't know what you want me to fix.
