### ISSUE TITLE
Win Portable: Additional TEXMF Roots Restricted to 1 by console

### ISSUE THREAD

**Issue by KXzeno** [MiKTeX/miktex#1568]
### Installation Report:
```txt
initexmf: security risk: running with elevated privileges
ReportDate: 2024-12-15 17:59:35
CurrentVersion: 24.4
SetupDate: 2024-12-15 11:36:00
SetupVersion: 24.1
Configuration: Portable
GitInfo: e3580c6 / 2024-04-27 18:01:25
OS: Windows 10.0.19045
SharedSetup: no
LinkTargetDirectory: E:\Amidship\adk\dist\mintex\miktex-portable\texmfs\install\miktex\bin\x64
PathOkay: no
LastUpdateCheck: 2024-12-15 17:27:21
LastUpdate: 2024-12-15 17:45:10
LastUpdateDb: 2024-12-15 17:27:13
SystemAdmin: yes
RootPrivileges: yes
AdminMode: no
Root0: E:\Amidship\adk\dist\mintex\miktex-portable\texmfs\config
Root1: E:\Amidship\adk\dist\mintex\miktex-portable\texmfs\data
Root2: E:\Amidship\adk\dist\mintex\miktex-portable\texmfs\install
Root3: E:\Amidship\adk\localtexmf
UserInstall: E:\Amidship\adk\dist\mintex\miktex-portable\texmfs\install
UserConfig: E:\Amidship\adk\dist\mintex\miktex-portable\texmfs\config
UserData: E:\Amidship\adk\dist\mintex\miktex-portable\texmfs\data
```

### Description
Using the MiKTeX Console provided by the Windows portable distribution allows only 1 additional TEXMF root to be added, excluding the predefined config, data, and installation paths. Adding any more would overwrite the newest TEXMF root.

### Reproduction:
1. Follow portable installation guide (Windows)
2. Checked for updates then restarted console
3. Append TEXMF root `some/root` via console
4. Append TEXMF root `some/other/root` via console

#### Expected Behavior
Both paths are added to listed TEXMF root directories

#### Actual Behavior
Root `E:\Amidship\adk\localtexmf` (`some/root`) is replaced with `E:\Amidship\other\mytexmf` (`some/other/root`)
    
### Temporary Workaround:
Modify `miktexstartup.ini` to allow multiple roots:
```
;;; MiKTeX startup information

[Auto]
Config=Portable

[Paths]
CommonRoots=E:/Amidship/adk/localtexmf;E:/Amidship/other/mytexmf

[Setup]
Version=24.1
```

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
I was not able to reproduce this.
