### ISSUE TITLE
tools package - “Installed file does not exist”

### ISSUE THREAD

**Issue by basseur** [MiKTeX/miktex#157]
After updating all the packages in my MiKTeX 2.9 installation (the last update was 03/2018), the compilation of a document that apparently uses the `tools` package does not work anymore.
The mpm reinstalls the already installed package, then a fatal error occurs (excerpt from _pdflatex.log_):

>2018-07-05 14:00:55,106+0200 FATAL pdflatex - The installed file does not exist.
>2018-07-05 14:00:55,106+0200 FATAL pdflatex - Info: fileName="C:\Program Files (x86)\MiKTeX 2.9\tex\latex\tools\\.tex"
>2018-07-05 14:00:55,106+0200 FATAL pdflatex - Source: Libraries\MiKTeX\Core\Session\findfile.cpp
>2018-07-05 14:00:55,106+0200 FATAL pdflatex - Line: 55
>2018-07-05 14:00:55,107+0200 INFO  pdflatex - finishing with exit code 1

The respective folder is not empty and contains 41 files (which I am not gonna list).
I have tried removing the tools package and reinstalling it myself to no avail.

I write and compile my documents in TeXstudio 2.12.8 using latexmk as my default compiler with the following command:

    latexmk.exe -r latexmkrc -synctex=1 -interaction=nonstopmode -shell-escape -pdf -pdflatex="pdflatex %%O %%S" %

This has been working fine up until the update.

What can I do? 

PS: I fear, this might be the wrong place to ask this kind of question. If so, please advise me as to where I should turn to and I will remove the question myself.

**Comment by edocevoli** [comment]
This seems to be a packaging error (not an issue which can be solved by modifying the MiKTeX source code).

**Comment by edocevoli** [comment]
I have added the missing `.tex` file. Tomorrow: please update MiKTeX.
