### ISSUE TITLE
internal error if I try to update MiKTeX: 2.9.7050

### ISSUE THREAD

**Issue by WimKlim** [MiKTeX/miktex#1570]
I get :

2024-12-17 19:32:07,332+0100 INFO  main - starting: MiKTeX Console 2.9.7076 (MiKTeX 2.9.7050 64-bit)
2024-12-17 19:32:29,489+0100 INFO  mainwindow - checking for updates...
2024-12-17 19:32:31,460+0100 ERROR mainwindow - Libraries\MiKTeX\PackageManager\RestRemoteService.cpp:245: MiKTeX encountered an internal error.()

Furthermore I don't see any Remote Package Repositories.

Infos :

Date: 2024-12-17 19:36:52
MiKTeX: 2.9.7050
OS: Windows 10 Pro, 64-bit, build 19045
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: not yet
LastUpdateAdmin: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: D:\Users\Stefan\AppData\Roaming\MiKTeX\2.9
Root1: D:\Users\Stefan\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: D:\Users\Stefan\AppData\Roaming\MiKTeX\2.9
UserConfig: D:\Users\Stefan\AppData\Roaming\MiKTeX\2.9
UserData: D:\Users\Stefan\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

Warning: the following problems were detected:
  1: Never checked for system-wide updates.

**Comment by edocevoli** [comment]
Sorry, MiKTeX 2.9 is not supported anymore.
