### ISSUE TITLE
MikTex software, can't check for updates

### ISSUE THREAD

**Issue by Dito572** [MiKTeX/miktex#1575]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report),

I have problem with updates. I installed the software and then when I am clicking Check for updates I get the error message:

GENERAL MIKTEX INFORMATION
ReportDate: 2024-12-26 23:30:22
CurrentVersion: 24.1
SetupDate: 2024-12-26 23:23:00
SetupVersion: 24.1
Configuration: Regular
GitInfo: 7b52272 / 2024-01-27 12:26:15
OS: Windows 10.0.22631
SharedSetup: no
LinkTargetDirectory: C:\Users\GSSHOP.GE\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
LastUpdateDb: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\GSSHOP.GE\AppData\Roaming\MiKTeX
Root1: C:\Users\GSSHOP.GE\AppData\Local\MiKTeX
Root2: C:\Users\GSSHOP.GE\AppData\Local\Programs\MiKTeX
UserInstall: C:\Users\GSSHOP.GE\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\GSSHOP.GE\AppData\Roaming\MiKTeX
UserData: C:\Users\GSSHOP.GE\AppData\Local\MiKTeX
Invokers: non-existing/explorer

The following issues were detected:
  1: major issue: So far, you have not checked for MiKTeX updates.

ERROR DETAILS
Program: miktex-console
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:247
Error: Timeout was reached
Details: 
  code: 28
  url: https://ctan.yazd.ac.ir/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma

**Comment by husayt** [comment]
hi, may i check how did you sort this out eventually?
