### ISSUE TITLE
error reading the configuration file

### ISSUE THREAD

**Issue by Ferdinand86** [MiKTeX/miktex#16]
Hi. 

I recently installed MikTeX 2.9 on a new notebook running Windwos 10 Education. Whenever I try to update my packages or to use the .*dvi-output of WinEdt the following error message appears:

A MiKTeX configuration file could not be loaded.
file="C:\Users\Max Köpple\AppData\Roaming\MiKTeX\2.9\miktex\config\mpm.ini (or yap.ini)", line="0",
error="error reading the configuration file"

Does anyone know a possible solution to this problem? Might the reason be the use of german umlaut characters? Strangely, I'm using the same user name (Max Köpple) on my worker machine, but here I'm using Windows 7 + MikTeX 2..8.

Best regards,

Max

**Comment by edocevoli** [comment]
Thank you. I cannot reproduce the issue. Can you provide more information? For example, the MiKTeX log files in

    %LOCALAPPDATA%\miktex\2.9\miktex\log

might be useful.

At the moment, your problem description does not help me to fix the issue.

**Comment by Ferdinand86** [comment]
Guten Morgen Herr Schenk,

 

vielen Dank, dass Sie sich dem Problem annehmen. Nach meinen letzten Erkenntnissen treten die beschriebenen Fehlermeldungen beim Aufruf der dvi-Ausgabe (texify, WinEdt) sowie beim Aufrufen von MikTeX Update (in der Nicht-Admin-Version) auf. Interessanterweise funktioniert die dvi-Ausgabe nach Neuinstallation genau einmal und danach nicht mehr. Habe auch schon mal den entsprechenden Roaming-Ordner gelöscht, danach ging yap wieder genau einmal. Schicke Ihnen zwei Bilder sowie den entsprechenden log-Ordner im zip-Format.

Außerdem ist mir aufgefallen, dass die Grafik der yap/dvi-Ausgabe (Buttons, Leisten etc, vgl. auch Fehlermeldung.) unter Windows10 unscharf ist. Weiß allerdings nicht ob das ein Problem von WinEdt oder MikTeX ist.

 

Beste Grüße aus Karlsruhe,

 

Max Köpple

 

 

Gesendet: Donnerstag, 05. Oktober 2017 um 17:20 Uhr
Von: "Christian Schenk" <notifications@github.com>
An: MiKTeX/miktex <miktex@noreply.github.com>
Cc: Ferdinand86 <max.koepple@web.de>, Author <author@noreply.github.com>
Betreff: Re: [MiKTeX/miktex] error reading the configuration file (#16)


Thank you. I cannot reproduce the issue. Can you provide more information? For example, the MiKTeX log files in

%LOCALAPPDATA%\miktex\2.9\miktex\log


might be useful.

At the moment, your problem description does not help me to fix the issue.

**Comment by Ferdinand86** [comment]
Please excuse my inquiry. Does closed mean you could fix the issue? Or is my problem too user-specific and still not reproducible?

Max



Gesendet: Freitag, 06. Oktober 2017 um 21:39 Uhr
Von: "Christian Schenk" <notifications@github.com>
An: MiKTeX/miktex <miktex@noreply.github.com>
Cc: Ferdinand86 <max.koepple@web.de>, Author <author@noreply.github.com>
Betreff: Re: [MiKTeX/miktex] error reading the configuration file (#16)


Closed #16.

**Comment by Ferdinand86** [comment]
Before I reinstall Windows overhasty.. might you be so kind and answer me if the problem is user- or possibly program-specific?

**Comment by edocevoli** [comment]
Thank you. So this is the issue:

If the update wizard is started in non-admin mode, then it fails (a configuration file could not be loaded).

I will fix this.

**Comment by Ferdinand86** [comment]
Thank you too!! As mentioned above the same problem appears when using the *.dvi-output-option more than once after reinstallation..

**Comment by edocevoli** [comment]
Can you attach the configuration files, please? The paths are:

    C:\Users\Max Köpple\AppData\Roaming\MiKTeX\2.9\miktex\config\mpm.ini
    C:\Users\Max Köpple\AppData\Roaming\MiKTeX\2.9\miktex\config\yap.ini

**Comment by edocevoli** [comment]
You don't need to attach the log files because I can now reproduce the problem. A fix will be made available at the end of the month

**Comment by Ferdinand86** [comment]
This sounds great. Thank you a lot!

**Comment by Ferdinand86** [comment]
In the meanwhile I reinstalled Windows using a short user name without special characters. Now everything seems to work as it should. However, I noticed that the graphics of Yap is poor and not sharp. Obviously, you can solve it by changing the compatibility options (see picture + link attached).

https://www.heise.de/newsticker/meldung/c-t-Tipp-der-Woche-Umgang-mit-hoher-Aufloesung-im-Creators-Update-3697426.html

<img width="276" alt="yap" src="https://user-images.githubusercontent.com/32491352/32142286-4fe9894e-bc94-11e7-98f0-1a9745245c33.PNG">

**Comment by edocevoli** [comment]
Thank you, this has been fixed. You can run the updater now.
