### ISSUE TITLE
xelatex: -disable-installer is not propagated to miktex-makemf

### ISSUE THREAD

**Issue by KOLANICH** [MiKTeX/miktex#161]
1. run xelatex with `-disable-installer` against some file trigerring installation of fonts
2. see a dialog box asking for a permission to install the package.

In my case I have tried to use xelatex with 
```tex
\documentclass[letterpaper,14pt]{article}

%xelatex shit
\usepackage{fontspec}
\usepackage{unicode-math}

\setmainfont{Ubuntu}
\setromanfont{DejaVu Serif}
\setsansfont{DejaVu Sans}
\setmonofont{Fira Code}
%\setmathfont{Cambria Math}
\setmathfont{STIX Math}

\defaultfontfeatures{Mapping=tex-text}
\usepackage{xunicode}
\usepackage{xltxtra}
\usepackage{polyglossia}
\setmainlanguage{english} 

\begin{document}
aaaaaaaaaaaaaaaa
\end{document}
```
on Windows 7 with fonts mentioned installed into the system.

If I use Cambria Math as font it doesn't trigger the install. If I use STIX Math it triggers installation of `othello` by triggering `miktex-maketfm -v OT`.

**Comment by edocevoli** [comment]
This will be fixed with [milestone 2.9.6800](https://github.com/MiKTeX/miktex/milestone/7).
