### ISSUE TITLE
I installed MiKTeX under win10 and the path of the bin directory is set with wrong slashes:  C:\Users\me\AppData\Local\Programs\MiKTeX 2.9\miktex/bin/x64

### ISSUE THREAD

**Issue by annne** [MiKTeX/miktex#163]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [ ] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions
2. input files which are necessary to reproduce the bug
3. your observations (command output, screenshots, ...)
4. relevant log file snippets

**Comment by annne** [comment]
@edocevoli  Why is it invalid? I need a solution to this problem. There is no way to edit this path, it is set by MiKTeX...

**Comment by edocevoli** [comment]
This is an invalid report:
- You haven't checked the log files
- You didn't provide the required information
