### ISSUE TITLE
I installed basic-miktex-2.9.6753-x64.exe on my windows 10 computer - It creates wrong paths

### ISSUE THREAD

**Issue by annne** [MiKTeX/miktex#164]
I installed basic-miktex-2.9.6753-x64.exe on my windows 10 computer. I cannot update packages or anything else, because the paths for the bin directory etc. contain wrong slashes. I get the following error:    
   
MiKTeX Problem Report
Message: Windows API error 2: Das System kann die angegebene Datei nicht finden.

Data: commandLine="mpm --register-components --verbose", fileName="C:\Users\me\AppData\Local\Programs\MiKTeX 2.9\miktex/bin/x64\mpm.exe"
Source: Libraries\MiKTeX\Core\Process\win\winProcess.cpp
Line: 292
MiKTeX: 2.9
OS: Windows 10 Home, 64-bit, build 17134
Invokers: non-existing/explorer
SystemAdmin: no
PowerUser: no
Root0: C:\Users\me\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\me\AppData\Local\MiKTeX\2.9
Root2: C:\Users\me\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\me\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\me\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\me\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

[initexmf.log](https://github.com/MiKTeX/miktex/files/2201001/initexmf.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/2201002/miktex-console.log)
[miktex-fc-cache.log](https://github.com/MiKTeX/miktex/files/2201003/miktex-fc-cache.log)
[mkfntmap.log](https://github.com/MiKTeX/miktex/files/2201004/mkfntmap.log)
[mpmcli.log](https://github.com/MiKTeX/miktex/files/2201005/mpmcli.log)
[pdftex.log](https://github.com/MiKTeX/miktex/files/2201006/pdftex.log)

I could not find a way to edit these paths.

**Comment by edocevoli** [comment]
The path looks okay. `/` is a valid path separator.

I am not able to reproduce the bug. You haven't specified the reproduction steps.

**Comment by annne** [comment]
I only installed it and tried running the package update as well as "Refresh name data base" - In both cases I get  "Some went wrong"  with the error message. I am sorry, but I don't know, which information else I could provide. 
I downloaded the current 64bit-win version, executed the setup and tried to work with it.

But in all cases, I get an error due to the path - the executables are not found. (E.g. when working with TexStudio - I added a screen shot)  - the pdflatex.exe is actually available under C:\Program Files\MiKTeX 2.9\miktex\bin\x64

MiKTeX itself shows a Path Issue right from the beginning - But I did not find an option to solve that.
In the Link "Howto: modifyPath" it is only described for Mac ...    

![pathissuemiktex](https://user-images.githubusercontent.com/26672586/42815782-b26d981a-89c8-11e8-9d96-f6ddf409712f.JPG)
![errorintexstudio](https://user-images.githubusercontent.com/26672586/42815785-b5d6da7a-89c8-11e8-975a-072d55afd5ee.JPG)

Thank you so much.

**Comment by edocevoli** [comment]
This is my bin path:
![binpath](https://user-images.githubusercontent.com/20090840/42816128-0b16e632-89ca-11e8-9ab6-d53146978e58.png)

So I don't think that this is an issue.

**Comment by edocevoli** [comment]
It seems that the bin directory hasn't been added to `PATH` (see your first MiKTeX console screenshot).

I would recommend that you check  the `PATH` variable and make sure that it contains

`C:\Users\me\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64`

(Here you have to use the classic directory separator `\`.)

Then you can try to run this command:

```
pdflatex sample2e
````

**Comment by annne** [comment]
I checked the path variable - the desired path is there.

pdflatex sample2e gives an error:
![sample2e](https://user-images.githubusercontent.com/26672586/42817199-ab102a74-89cd-11e8-8224-6f219791444a.JPG)

**Comment by edocevoli** [comment]
`pdflatex` tries to open a file which is in use. Please terminate other MiKTeX-related programs (MiKTeX Console, TeXstudio) and try again.

**Comment by annne** [comment]
Now, this is the remaining problem:

[pdflatex.log](https://github.com/MiKTeX/miktex/files/2202129/pdflatex.log)

**Comment by edocevoli** [comment]
Are running `pdflatex` with elevated privileges?

**Comment by SpecialCharacter** [comment]
I have the same issue.

Tried it with elevated privileges. Now it says "error in external 
program pdflatex".

With normal privileges it just converted to .pdf, but the .pdf was never 
shown.

Bernd


Am 17.07.2018 um 20:56 schrieb Christian Schenk:

**Comment by edocevoli** [comment]
I would recommend that you uninstall MiKTeX and then do a clean install as user. Don't install as admin.
