### ISSUE TITLE
Installing MiKTex via Command Line

### ISSUE THREAD

**Issue by CLIENTSW4** [MiKTeX/miktex#168]
Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

Hello, I am attempting to install MikTex and TexStudio via the Ghost Solutions Suite (command line install) to some lab computers at our institution.

First, I used the `--verbose --local-package-repository=C:\temp\miktex --package-set=complete download` to extract /download the full thing to `\ad\express$\Software\Computer Science Software\MiKTeX\2.9.6672-x64`

Here is my script:

```
net use g: "\\ad\express$\Software\Computer Science Software"
"g:\MiKTeX\2.9.6672-x64\miktexsetup.exe" --local-package-repository="g:\MiKTeX\2.9.6672-x64" --shared --package-set=complete install
net use g: /Delete
```

I have also tried avoiding mapping the network drive (when we do not map, that sometimes causes issues:

```
"\\ad\express$\Software\Computer Science Software\MiKTeX\2.9.6672-x64\miktexsetup.exe" --local-package-repository="\\ad\express$\Software\Computer Science Software\MiKTeX\2.9.6672-x64" --shared --package-set=complete install
```

I get this error when running the command on its own:
![Imgur](https://i.imgur.com/KXgAVLV.png)

When I run CMD as admin: 
![Imgur](https://i.imgur.com/wKDT5eP.png)

What am I missing to install this via Command Line?

**Comment by edocevoli** [comment]
Please use option `--trace` to create debug messages. The messages can be captured with DebugView:

https://docs.microsoft.com/en-us/sysinternals/downloads/debugview

**Comment by CLIENTSW4** [comment]
Hello,

Here is the log file generated: https://pastebin.com/raw/nTf114MQ

![Imgur](https://i.imgur.com/r5LDFhc.png)

**Comment by edocevoli** [comment]
Thank you. This is not the complete trace. You should save the complete trace log (not a screenshot).

Nevertheless: it seems that you are trying to set up a shared MiKTeX installation. Running the tool as administrator should solve your problem.

If you still have issues: please give enough information so that other individuals are able to reproduce your problem:

- step-by-step reproduction instructions; a single batch file would be optimal
- all log file snippets (not screenshots of a partial log view)

**Comment by CLIENTSW4** [comment]
Hello,

I am not sure what you mean by "a shared MiKTeX installation" We are installing FROM a shared location, but each computer is to receive its own independent install to its C drive.

That log screenshot and pastebin link was everything created by DebugView. 

What do you mean by "the tool"? Do you mean Command Prompt as admin? When I do that, I get the same error as stated above when running as admin. I have attatched the entire log again as a .LOG file.

[CBLT050L91661L.LOG](https://github.com/MiKTeX/miktex/files/2219589/CBLT050L91661L.LOG)

I also am unsure of what you mean by "a single batch file would be optimal" does this mean to put the command inside of a batch file, and running that as an admin?

Thanks.

**Comment by edocevoli** [comment]
Sorry. you are right: I do not fully understand your issue. That's why I encouraged you to provide step-by-step reproduction instructions. A recipe.

**Comment by edocevoli** [comment]
It is normal non-admin step 4 fails. Your DebugView trace reflects non-admin step 4. i.e., you should produce another DebugView trace: please run DebugView and step 4 as admin.

**Comment by CLIENTSW4** [comment]
Here is the DebugView for running CMD as admin in step 4

[Step4CMDAsAdmin.LOG](https://github.com/MiKTeX/miktex/files/2219705/Step4CMDAsAdmin.LOG)

**Comment by edocevoli** [comment]
Thank you. I was able to reproduce the bug. The `$` in the share makes the installer fail.
