### ISSUE TITLE
MikTeX Portable: Perl scripts like latexdiff and latexindent are not executed

### ISSUE THREAD

**Issue by Heinrich2057** [MiKTeX/miktex#170]
Under Windows 10 with an actual MiKTeX Protable version i tried to run the tools latexdiff and latexindent and i received the following error messages:

--------------------- Begin Error Messages form cmd-Window --------------------------------
E:\TeX\MikTeX>latexdiff
latexdiff: The script engine could not be found.
latexdiff: Data: scriptEngine="perl.exe"

E:\TeX\MikTeX>latexindent
latexindent: The script engine could not be found.
latexindent: Data: scriptEngine="perl.exe"

--------------------- End   Error Messages form cmd-Window --------------------------------

Please can this be analysed and fixed!

**Comment by edocevoli** [comment]
These scripts are executed by `perl.exe`. Seems that your `PATH` needs an adjustment.

**Comment by Heinrich2057** [comment]
Hallo Herr Schenk,

ich denke es ist nicht ausreichend nur den "Path" zu "perl.exe" zu
korrigieren. Denn in den Unterverzeichnissen zu MikTeX Portable findet man
nicht die ausführbare Datei "perl.exe".

Im Verzeichnis "D:\TeX\MiKTeX\texmfs\install\miktex\bin" habe ich jedoch
die ausführbare Datei "perltex.exe" mit der Grösse 44KB gefunden,

Handelt es sich hierbei  um "perl.exe". Reicht es aus  "perltex.exe" in
"perl.tex" um zu benennen?

Im Pfad ist dieses Verzeichnis enthalten:
"PATH=D:\TeX\MiKTeX\texmfs\install\miktex/bin; ..."

Danke und viele Grüße

Uwe Christmann


2018-07-27 19:01 GMT+02:00 Christian Schenk <notifications@github.com>:

**Comment by edocevoli** [comment]
`perl.exe` is not a part of the MiKTeX distribution. You have to install Perl on your target system if you want to execute Perl scripts like `latexdiff`.

By the way: I strongly recommend that you write your comments in English.
