### ISSUE TITLE
installation fails on windows 7

### ISSUE THREAD

**Issue by trencyclopedia** [MiKTeX/miktex#171]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [ ] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [ ] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions
2. input files which are necessary to reproduce the bug
3. your observations (command output, screenshots, ...)
4. relevant log file snippets

I was trying to install the following package on my windows 7
File name: | basic-miktex-2.9.6753-x64.exe
Size: | 192.03 MB
SHA-256: | 07837a9d0135d26706ef31c47e1932aa00dc18e996e5b35eac437cbfa4959ccf
  | Download

but I got a bug like this:
![image](https://user-images.githubusercontent.com/17362306/43446097-4c811c44-94a8-11e8-8e08-2bccba9c56c2.png)

The system information of my PC is like this:
![image](https://user-images.githubusercontent.com/17362306/43446221-8e92ce2a-94a8-11e8-9f70-3f3109f1ae6c.png)

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.
You can try it again tomorrow. If the problem still exists: collect log files, screenshots etc.
Reminder: Your job is to enable me to reproduce the problem.

**Comment by trencyclopedia** [comment]
A few more information about the problem: 

1. output information in the MiKTeX Setup Wizard:

initializing setup service...
starting installer...
Loading package database...
starting package maintenance...
installation directory: "C:\Program Files\MiKTeX 2.9"
package repository: C:\Users\zhai65\AppData\Local\Temp\mik10129
visiting repository C:\Users\zhai65\AppData\Local\Temp\mik10129...
repository type: local package repository
loading lightweight database...
lightweight database digest: b0545706fa706b64cc77217d98c169a9
going to install 10913 file(s) (215 package(s))
extracting files from ae.tar.lzma...
extracting files from amscls.tar.lzma...
extracting files from amsfonts.tar.lzma...
extracting files from amsmath.tar.lzma...
extracting files from asymptote.tar.lzma...
extracting files from avantgar.cab...
extracting files from babel.tar.lzma...
extracting files from babel-english.tar.lzma...
extracting files from babel-french.tar.lzma...
extracting files from babel-german.tar.lzma...
extracting files from babel-spanish.tar.lzma...
extracting files from bibtex.tar.lzma...
extracting files from bibtex8bit.tar.lzma...
extracting files from bibtex8bit-polish.tar.lzma...
extracting files from bidi.tar.lzma...
extracting files from bookman.cab...
extracting files from carlisle.tar.lzma...
extracting files from cbcoptic.tar.lzma...
extracting files from chktex.tar.lzma...
extracting files from cm.tar.lzma...
extracting files from courier.tar.lzma...
extracting files from cweb.tar.lzma...
extracting files from cyrillic.tar.lzma...
extracting files from dehyph.tar.lzma...
extracting files from dehyph-exptl.tar.lzma...
extracting files from dvipdfmx.tar.lzma...
extracting files from dvips.tar.lzma...
extracting files from ec.tar.lzma...
extracting files from elhyphen.tar.lzma...
extracting files from enctex.tar.lzma...
extracting files from etex.tar.lzma...
extracting files from etex-pkg.tar.lzma...
extracting files from euenc.tar.lzma...
extracting files from eurosym.tar.lzma...
extracting files from float.tar.lzma...
extracting files from fontconfig.tar.lzma...
extracting files from fontname.tar.lzma...
extracting files from fontspec.tar.lzma...
extracting files from geometry.tar.lzma...
extracting files from ghostscript.tar.lzma...
extracting files from graphics.tar.lzma...
extracting files from graphics-cfg.tar.lzma...
extracting files from graphics-def.tar.lzma...
extracting files from gsftopk.tar.lzma...
extracting files from helvetic.cab...
extracting files from hyperref.tar.lzma...
extracting files from hyph-utf8.tar.lzma...
extracting files from ifxetex.tar.lzma...
extracting files from jknappen.tar.lzma...
extracting files from knuth-lib.tar.lzma...
extracting files from knuth-local.tar.lzma...
extracting files from latex-fonts.tar.lzma...
extracting files from lm.tar.lzma...
extracting files from ltxbase.tar.lzma...
extracting files from ltxmisc.tar.lzma...
extracting files from lua-alt-getopt.tar.lzma...
extracting files from luainputenc.tar.lzma...
extracting files from lualibs.tar.lzma...
extracting files from luamplib.tar.lzma...
extracting files from luaotfload.tar.lzma...
extracting files from luatexbase.tar.lzma...
extracting files from luatextra.tar.lzma...
extracting files from makeindex.tar.lzma...
extracting files from metafont.tar.lzma...
extracting files from metapost.tar.lzma...
extracting files from mflogo.tar.lzma...
extracting files from mflogo-font.tar.lzma...
extracting files from mfware.tar.lzma...
extracting files from miktex-arctrl-bin-x64-2.9.tar.lzma...
extracting files from miktex-asymptote-bin-x64-2.9.tar.lzma...
extracting files from miktex-autosp-bin-x64-2.9.tar.lzma...
extracting files from miktex-axohelp-bin-x64-2.9.tar.lzma...
extracting files from miktex-bibarts-bin-x64.tar.lzma...
extracting files from miktex-biber-bin-x64.tar.lzma...
extracting files from miktex-bibtex-bin-x64-2.9.tar.lzma...
extracting files from miktex-bibtex8bit-bin-x64-2.9.tar.lzma...
extracting files from miktex-bzip2-bin-x64-2.9.tar.lzma...
extracting files from miktex-cairo-bin-x64-2.9.tar.lzma...
extracting files from miktex-chktex-bin-x64-2.9.tar.lzma...
extracting files from miktex-cjkutils-bin-x64-2.9.tar.lzma...
extracting files from miktex-config-2.9.tar.lzma...
extracting files from miktex-console-bin-x64-2.9.tar.lzma...
extracting files from miktex-curl-bin-x64-2.9.tar.lzma...
extracting files from miktex-cweb-bin-x64-2.9.tar.lzma...
extracting files from miktex-devnag-bin-x64-2.9.tar.lzma...
extracting files from miktex-dict-english.tar.lzma...
extracting files from miktex-dict-french.tar.lzma...
extracting files from miktex-dict-german.tar.lzma...
extracting files from miktex-doc-2.9.tar.lzma...
extracting files from miktex-dvicopy-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvipdfmx.tar.lzma...
extracting files from miktex-dvipdfmx-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvipng-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvips.tar.lzma...
extracting files from miktex-dvips-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvisvgm-bin-x64-2.9.tar.lzma...
extracting files from miktex-epstopdf-bin-x64-2.9.tar.lzma...
extracting files from miktex-etex.tar.lzma...
extracting files from miktex-expat-bin-x64-2.9.tar.lzma...
extracting files from miktex-findtexmf-bin-x64-2.9.tar.lzma...
extracting files from miktex-fontconfig.tar.lzma...
extracting files from miktex-fontconfig-bin-x64-2.9.tar.lzma...
extracting files from miktex-fonts-bin-x64-2.9.tar.lzma...
extracting files from miktex-freeglut-bin-x64-2.9.tar.lzma...
extracting files from miktex-freetype2-bin-x64-2.9.tar.lzma...
extracting files from miktex-fribidixetex-bin-x64-2.9.tar.lzma...
extracting files from miktex-gd-bin-x64-2.9.tar.lzma...
extracting files from miktex-ghostscript-bin-x64.tar.lzma...
extracting files from miktex-graphite2-bin-x64-2.9.tar.lzma...
extracting files from miktex-gregorio-bin-x64-2.9.tar.lzma...
extracting files from miktex-gsf2pk-bin-x64-2.9.tar.lzma...
extracting files from miktex-harfbuzz-bin-x64-2.9.tar.lzma...
extracting files from miktex-hunspell-bin-x64-2.9.tar.lzma...
extracting files from miktex-icu-bin-x64.tar.lzma...
extracting files from miktex-int-bin-x64-2.9.tar.lzma...
extracting files from miktex-jpeg-bin-x64-2.9.tar.lzma...
extracting files from miktex-kpathsea-bin-x64-2.9.tar.lzma...
extracting files from miktex-lacheck-bin-x64-2.9.tar.lzma...
extracting files from miktex-latex.tar.lzma...
extracting files from miktex-libressl-bin-x64-2.9.tar.lzma...
extracting files from miktex-log4cxx-bin-x64-2.9.tar.lzma...
extracting files from miktex-lua52-bin-x64-2.9.tar.lzma...
extracting files from miktex-lua53-bin-x64-2.9.tar.lzma...
extracting files from miktex-luatex.tar.lzma...
extracting files from miktex-luatex-bin-x64-2.9.tar.lzma...
extracting files from miktex-lzma-bin-x64-2.9.tar.lzma...
extracting files from miktex-m-tx-bin-x64-2.9.tar.lzma...
extracting files from miktex-makeindex-bin-x64-2.9.tar.lzma...
extracting files from miktex-md5-bin-x64-2.9.tar.lzma...
extracting files from miktex-metafont.tar.lzma...
extracting files from miktex-metafont-bin-x64-2.9.tar.lzma...
extracting files from miktex-metapost.tar.lzma...
extracting files from miktex-metapost-bin-x64-2.9.tar.lzma...
extracting files from miktex-mfware-bin-x64-2.9.tar.lzma...
extracting files from miktex-misc.tar.lzma...
extracting files from miktex-mkfntmap-bin-x64-2.9.tar.lzma...
extracting files from miktex-mktex-bin-x64-2.9.tar.lzma...
extracting files from miktex-mo-bin-x64-2.9.tar.lzma...
extracting files from miktex-mpfr-bin-x64-2.9.tar.lzma...
extracting files from miktex-mpmcli-bin-x64-2.9.tar.lzma...
extracting files from miktex-mspack-bin-x64-2.9.tar.lzma...
extracting files from miktex-mthelp-bin-x64-2.9.tar.lzma...
extracting files from miktex-mtprint-bin-x64-2.9.tar.lzma...
extracting files from miktex-omega.tar.lzma...
extracting files from miktex-omega-bin-x64-2.9.tar.lzma...
extracting files from miktex-pdftex.tar.lzma...
extracting files from miktex-pdftex-bin-x64-2.9.tar.lzma...
extracting files from miktex-pixman-bin-x64-2.9.tar.lzma...
extracting files from miktex-pmx-bin-x64-2.9.tar.lzma...
extracting files from miktex-png-bin-x64-2.9.tar.lzma...
extracting files from miktex-poppler-bin-x64-2.9.tar.lzma...
extracting files from miktex-popt-bin-x64-2.9.tar.lzma...
extracting files from miktex-posix-bin-x64-2.9.tar.lzma...
extracting files from miktex-potrace-bin-x64-2.9.tar.lzma...
extracting files from miktex-ps2pk-bin-x64-2.9.tar.lzma...
extracting files from miktex-psutils-bin-x64-2.9.tar.lzma...
extracting files from miktex-qt5-bin-x64.tar.lzma...
extracting files from miktex-runtime-bin-x64-2.9.tar.lzma...
extracting files from miktex-tdsutil-bin-x64-2.9.tar.lzma...
extracting files from miktex-teckit-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex.tar.lzma...
extracting files from miktex-tex-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex2xindy-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex4ht.tar.lzma...
extracting files from miktex-tex4ht-bin-x64-2.9.tar.lzma...
extracting files from miktex-texify-bin-x64-2.9.tar.lzma...
extracting files from miktex-texinfo.tar.lzma...
extracting files from miktex-texware-bin-x64-2.9.tar.lzma...
extracting files from miktex-texworks-bin-x64-2.9.tar.lzma...
extracting files from miktex-ttf2pk2-bin-x64-2.9.tar.lzma...
extracting files from miktex-ucrt-bin-x64.tar.lzma...
extracting files from miktex-uriparser-bin-x64-2.9.tar.lzma...
extracting files from miktex-vc140-bin-x64.tar.lzma...
extracting files from miktex-web-bin-x64-2.9.tar.lzma...
extracting files from miktex-xetex.tar.lzma...
extracting files from miktex-xetex-bin-x64-2.9.tar.lzma...
extracting files from miktex-xindy-bin-x64.tar.lzma...
extracting files from miktex-yap-bin-x64-2.9.tar.lzma...
extracting files from miktex-zip-bin-x64.tar.lzma...
extracting files from miktex-zlib-bin-x64-2.9.tar.lzma...
extracting files from miktex-zzip-bin-x64-2.9.tar.lzma...
extracting files from multirow.tar.lzma...
extracting files from ncntrsbk.cab...
extracting files from oberdiek.tar.lzma...
extracting files from palatino.cab...
extracting files from pdftex.tar.lzma...
extracting files from plain.tar.lzma...
extracting files from polyglossia.tar.lzma...
extracting files from poppler.tar.lzma...
extracting files from pslatex.tar.lzma...
extracting files from psnfss.cab...
extracting files from pstricks.tar.lzma...
extracting files from psutils.tar.lzma...
extracting files from rsfs.tar.lzma...
extracting files from ruhyphen.tar.lzma...
extracting files from tetex.tar.lzma...
extracting files from tex-ini-files.tar.lzma...
extracting files from texinfo.tar.lzma...
extracting files from thumbpdf.tar.lzma...
extracting files from times.cab...
extracting files from tools.tar.lzma...
extracting files from ttf2pk.tar.lzma...
extracting files from ukrhyph.tar.lzma...
extracting files from unicode-data.tar.lzma...
extracting files from utopia.cab...
extracting files from xetex.tar.lzma...
extracting files from xgreek.tar.lzma...
extracting files from xindy.tar.lzma...
extracting files from xkeyval.tar.lzma...
extracting files from xltxtra.tar.lzma...
extracting files from xunicode.tar.lzma...
extracting files from xypic.tar.lzma...
extracting files from zapfchan.cab...
extracting files from zapfding.cab...
extracting files from zerohyph.tar.lzma...
updating package definition directory ("C:\Program Files\MiKTeX 2.9\tpm\packages")...
installed 3350 package definition files
visiting repository C:\Users\zhai65\AppData\Local\Temp\mik10129...
repository type: local package repository
loading lightweight database...
Registering root directories... Operating on the shared (system-wide) MiKTeX setup configuring fontconfig\config\fonts.conf  Sorry, but "MiKTeX Package Manager" did not succeed.  The log file hopefully contains the information to get MiKTeX going again:    C:/ProgramData/MiKTeX/2.9/miktex/log/mpmcli_admin.log  You may want to visit the MiKTeX project page, if you need help. 
Error: The executed process did not succeed.
![image](https://user-images.githubusercontent.com/17362306/43457689-ed809ef2-94c7-11e8-86dc-9539ace06389.png)


2. contents in the log file:
2018-07-31 13:38:44,806+0200 INFO  mpmcli - starting: mpmcli 2.9.6727 (MiKTeX 2.9.6730 64-bit)
2018-07-31 13:38:44,806+0200 INFO  mpmcli - Operating on the shared (system-wide) MiKTeX setup
2018-07-31 13:38:44,807+0200 INFO  mpmcli - configuring fontconfig\config\fonts.conf
2018-07-31 13:38:44,834+0200 FATAL mpmcli - Windows API error 5: Access is denied.

2018-07-31 13:38:44,834+0200 FATAL mpmcli - Info: fileName="C:\ProgramData\MiKTeX\2.9\fontconfig\config\fonts.conf", attributes="8225"
2018-07-31 13:38:44,834+0200 FATAL mpmcli - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
2018-07-31 13:38:44,834+0200 FATAL mpmcli - Line: 169

3. comments:
The same problem persists when intalling it either as an admin or a user

**Comment by trencyclopedia** [comment]
Updates:
Below are the complete contents in the log file outputted by the setup wizard after the installation fails: 

initializing setup service...
starting installer...
Loading package database...
starting package maintenance...
installation directory: "C:\Program Files\MiKTeX 2.9"
package repository: C:\Users\zhai65\AppData\Local\Temp\mik10129
visiting repository C:\Users\zhai65\AppData\Local\Temp\mik10129...
repository type: local package repository
loading lightweight database...
lightweight database digest: b0545706fa706b64cc77217d98c169a9
going to install 10913 file(s) (215 package(s))
extracting files from ae.tar.lzma...
extracting files from amscls.tar.lzma...
extracting files from amsfonts.tar.lzma...
extracting files from amsmath.tar.lzma...
extracting files from asymptote.tar.lzma...
extracting files from avantgar.cab...
extracting files from babel.tar.lzma...
extracting files from babel-english.tar.lzma...
extracting files from babel-french.tar.lzma...
extracting files from babel-german.tar.lzma...
extracting files from babel-spanish.tar.lzma...
extracting files from bibtex.tar.lzma...
extracting files from bibtex8bit.tar.lzma...
extracting files from bibtex8bit-polish.tar.lzma...
extracting files from bidi.tar.lzma...
extracting files from bookman.cab...
extracting files from carlisle.tar.lzma...
extracting files from cbcoptic.tar.lzma...
extracting files from chktex.tar.lzma...
extracting files from cm.tar.lzma...
extracting files from courier.tar.lzma...
extracting files from cweb.tar.lzma...
extracting files from cyrillic.tar.lzma...
extracting files from dehyph.tar.lzma...
extracting files from dehyph-exptl.tar.lzma...
extracting files from dvipdfmx.tar.lzma...
extracting files from dvips.tar.lzma...
extracting files from ec.tar.lzma...
extracting files from elhyphen.tar.lzma...
extracting files from enctex.tar.lzma...
extracting files from etex.tar.lzma...
extracting files from etex-pkg.tar.lzma...
extracting files from euenc.tar.lzma...
extracting files from eurosym.tar.lzma...
extracting files from float.tar.lzma...
extracting files from fontconfig.tar.lzma...
extracting files from fontname.tar.lzma...
extracting files from fontspec.tar.lzma...
extracting files from geometry.tar.lzma...
extracting files from ghostscript.tar.lzma...
extracting files from graphics.tar.lzma...
extracting files from graphics-cfg.tar.lzma...
extracting files from graphics-def.tar.lzma...
extracting files from gsftopk.tar.lzma...
extracting files from helvetic.cab...
extracting files from hyperref.tar.lzma...
extracting files from hyph-utf8.tar.lzma...
extracting files from ifxetex.tar.lzma...
extracting files from jknappen.tar.lzma...
extracting files from knuth-lib.tar.lzma...
extracting files from knuth-local.tar.lzma...
extracting files from latex-fonts.tar.lzma...
extracting files from lm.tar.lzma...
extracting files from ltxbase.tar.lzma...
extracting files from ltxmisc.tar.lzma...
extracting files from lua-alt-getopt.tar.lzma...
extracting files from luainputenc.tar.lzma...
extracting files from lualibs.tar.lzma...
extracting files from luamplib.tar.lzma...
extracting files from luaotfload.tar.lzma...
extracting files from luatexbase.tar.lzma...
extracting files from luatextra.tar.lzma...
extracting files from makeindex.tar.lzma...
extracting files from metafont.tar.lzma...
extracting files from metapost.tar.lzma...
extracting files from mflogo.tar.lzma...
extracting files from mflogo-font.tar.lzma...
extracting files from mfware.tar.lzma...
extracting files from miktex-arctrl-bin-x64-2.9.tar.lzma...
extracting files from miktex-asymptote-bin-x64-2.9.tar.lzma...
extracting files from miktex-autosp-bin-x64-2.9.tar.lzma...
extracting files from miktex-axohelp-bin-x64-2.9.tar.lzma...
extracting files from miktex-bibarts-bin-x64.tar.lzma...
extracting files from miktex-biber-bin-x64.tar.lzma...
extracting files from miktex-bibtex-bin-x64-2.9.tar.lzma...
extracting files from miktex-bibtex8bit-bin-x64-2.9.tar.lzma...
extracting files from miktex-bzip2-bin-x64-2.9.tar.lzma...
extracting files from miktex-cairo-bin-x64-2.9.tar.lzma...
extracting files from miktex-chktex-bin-x64-2.9.tar.lzma...
extracting files from miktex-cjkutils-bin-x64-2.9.tar.lzma...
extracting files from miktex-config-2.9.tar.lzma...
extracting files from miktex-console-bin-x64-2.9.tar.lzma...
extracting files from miktex-curl-bin-x64-2.9.tar.lzma...
extracting files from miktex-cweb-bin-x64-2.9.tar.lzma...
extracting files from miktex-devnag-bin-x64-2.9.tar.lzma...
extracting files from miktex-dict-english.tar.lzma...
extracting files from miktex-dict-french.tar.lzma...
extracting files from miktex-dict-german.tar.lzma...
extracting files from miktex-doc-2.9.tar.lzma...
extracting files from miktex-dvicopy-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvipdfmx.tar.lzma...
extracting files from miktex-dvipdfmx-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvipng-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvips.tar.lzma...
extracting files from miktex-dvips-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvisvgm-bin-x64-2.9.tar.lzma...
extracting files from miktex-epstopdf-bin-x64-2.9.tar.lzma...
extracting files from miktex-etex.tar.lzma...
extracting files from miktex-expat-bin-x64-2.9.tar.lzma...
extracting files from miktex-findtexmf-bin-x64-2.9.tar.lzma...
extracting files from miktex-fontconfig.tar.lzma...
extracting files from miktex-fontconfig-bin-x64-2.9.tar.lzma...
extracting files from miktex-fonts-bin-x64-2.9.tar.lzma...
extracting files from miktex-freeglut-bin-x64-2.9.tar.lzma...
extracting files from miktex-freetype2-bin-x64-2.9.tar.lzma...
extracting files from miktex-fribidixetex-bin-x64-2.9.tar.lzma...
extracting files from miktex-gd-bin-x64-2.9.tar.lzma...
extracting files from miktex-ghostscript-bin-x64.tar.lzma...
extracting files from miktex-graphite2-bin-x64-2.9.tar.lzma...
extracting files from miktex-gregorio-bin-x64-2.9.tar.lzma...
extracting files from miktex-gsf2pk-bin-x64-2.9.tar.lzma...
extracting files from miktex-harfbuzz-bin-x64-2.9.tar.lzma...
extracting files from miktex-hunspell-bin-x64-2.9.tar.lzma...
extracting files from miktex-icu-bin-x64.tar.lzma...
extracting files from miktex-int-bin-x64-2.9.tar.lzma...
extracting files from miktex-jpeg-bin-x64-2.9.tar.lzma...
extracting files from miktex-kpathsea-bin-x64-2.9.tar.lzma...
extracting files from miktex-lacheck-bin-x64-2.9.tar.lzma...
extracting files from miktex-latex.tar.lzma...
extracting files from miktex-libressl-bin-x64-2.9.tar.lzma...
extracting files from miktex-log4cxx-bin-x64-2.9.tar.lzma...
extracting files from miktex-lua52-bin-x64-2.9.tar.lzma...
extracting files from miktex-lua53-bin-x64-2.9.tar.lzma...
extracting files from miktex-luatex.tar.lzma...
extracting files from miktex-luatex-bin-x64-2.9.tar.lzma...
extracting files from miktex-lzma-bin-x64-2.9.tar.lzma...
extracting files from miktex-m-tx-bin-x64-2.9.tar.lzma...
extracting files from miktex-makeindex-bin-x64-2.9.tar.lzma...
extracting files from miktex-md5-bin-x64-2.9.tar.lzma...
extracting files from miktex-metafont.tar.lzma...
extracting files from miktex-metafont-bin-x64-2.9.tar.lzma...
extracting files from miktex-metapost.tar.lzma...
extracting files from miktex-metapost-bin-x64-2.9.tar.lzma...
extracting files from miktex-mfware-bin-x64-2.9.tar.lzma...
extracting files from miktex-misc.tar.lzma...
extracting files from miktex-mkfntmap-bin-x64-2.9.tar.lzma...
extracting files from miktex-mktex-bin-x64-2.9.tar.lzma...
extracting files from miktex-mo-bin-x64-2.9.tar.lzma...
extracting files from miktex-mpfr-bin-x64-2.9.tar.lzma...
extracting files from miktex-mpmcli-bin-x64-2.9.tar.lzma...
extracting files from miktex-mspack-bin-x64-2.9.tar.lzma...
extracting files from miktex-mthelp-bin-x64-2.9.tar.lzma...
extracting files from miktex-mtprint-bin-x64-2.9.tar.lzma...
extracting files from miktex-omega.tar.lzma...
extracting files from miktex-omega-bin-x64-2.9.tar.lzma...
extracting files from miktex-pdftex.tar.lzma...
extracting files from miktex-pdftex-bin-x64-2.9.tar.lzma...
extracting files from miktex-pixman-bin-x64-2.9.tar.lzma...
extracting files from miktex-pmx-bin-x64-2.9.tar.lzma...
extracting files from miktex-png-bin-x64-2.9.tar.lzma...
extracting files from miktex-poppler-bin-x64-2.9.tar.lzma...
extracting files from miktex-popt-bin-x64-2.9.tar.lzma...
extracting files from miktex-posix-bin-x64-2.9.tar.lzma...
extracting files from miktex-potrace-bin-x64-2.9.tar.lzma...
extracting files from miktex-ps2pk-bin-x64-2.9.tar.lzma...
extracting files from miktex-psutils-bin-x64-2.9.tar.lzma...
extracting files from miktex-qt5-bin-x64.tar.lzma...
extracting files from miktex-runtime-bin-x64-2.9.tar.lzma...
extracting files from miktex-tdsutil-bin-x64-2.9.tar.lzma...
extracting files from miktex-teckit-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex.tar.lzma...
extracting files from miktex-tex-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex2xindy-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex4ht.tar.lzma...
extracting files from miktex-tex4ht-bin-x64-2.9.tar.lzma...
extracting files from miktex-texify-bin-x64-2.9.tar.lzma...
extracting files from miktex-texinfo.tar.lzma...
extracting files from miktex-texware-bin-x64-2.9.tar.lzma...
extracting files from miktex-texworks-bin-x64-2.9.tar.lzma...
extracting files from miktex-ttf2pk2-bin-x64-2.9.tar.lzma...
extracting files from miktex-ucrt-bin-x64.tar.lzma...
extracting files from miktex-uriparser-bin-x64-2.9.tar.lzma...
extracting files from miktex-vc140-bin-x64.tar.lzma...
extracting files from miktex-web-bin-x64-2.9.tar.lzma...
extracting files from miktex-xetex.tar.lzma...
extracting files from miktex-xetex-bin-x64-2.9.tar.lzma...
extracting files from miktex-xindy-bin-x64.tar.lzma...
extracting files from miktex-yap-bin-x64-2.9.tar.lzma...
extracting files from miktex-zip-bin-x64.tar.lzma...
extracting files from miktex-zlib-bin-x64-2.9.tar.lzma...
extracting files from miktex-zzip-bin-x64-2.9.tar.lzma...
extracting files from multirow.tar.lzma...
extracting files from ncntrsbk.cab...
extracting files from oberdiek.tar.lzma...
extracting files from palatino.cab...
extracting files from pdftex.tar.lzma...
extracting files from plain.tar.lzma...
extracting files from polyglossia.tar.lzma...
extracting files from poppler.tar.lzma...
extracting files from pslatex.tar.lzma...
extracting files from psnfss.cab...
extracting files from pstricks.tar.lzma...
extracting files from psutils.tar.lzma...
extracting files from rsfs.tar.lzma...
extracting files from ruhyphen.tar.lzma...
extracting files from tetex.tar.lzma...
extracting files from tex-ini-files.tar.lzma...
extracting files from texinfo.tar.lzma...
extracting files from thumbpdf.tar.lzma...
extracting files from times.cab...
extracting files from tools.tar.lzma...
extracting files from ttf2pk.tar.lzma...
extracting files from ukrhyph.tar.lzma...
extracting files from unicode-data.tar.lzma...
extracting files from utopia.cab...
extracting files from xetex.tar.lzma...
extracting files from xgreek.tar.lzma...
extracting files from xindy.tar.lzma...
extracting files from xkeyval.tar.lzma...
extracting files from xltxtra.tar.lzma...
extracting files from xunicode.tar.lzma...
extracting files from xypic.tar.lzma...
extracting files from zapfchan.cab...
extracting files from zapfding.cab...
extracting files from zerohyph.tar.lzma...
updating package definition directory ("C:\Program Files\MiKTeX 2.9\tpm\packages")...
installed 3350 package definition files
visiting repository C:\Users\zhai65\AppData\Local\Temp\mik10129...
repository type: local package repository
loading lightweight database...
initexmf "--common-install=C:\Program Files\MiKTeX 2.9" --set-config-value=[Core]SharedSetup=1 --admin "--log-file=C:\Program Files\MiKTeX 2.9\miktex/config\uninst.log" --disable-installer --verbose:
Registering root directories...
initexmf --rmfndb --admin "--log-file=C:\Program Files\MiKTeX 2.9\miktex/config\uninst.log" --disable-installer --verbose:
mpm --register-components --admin --verbose:
Operating on the shared (system-wide) MiKTeX setup
configuring fontconfig\config\fonts.conf

Sorry, but "MiKTeX Package Manager" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/ProgramData/MiKTeX/2.9/miktex/log/mpmcli_admin.log

You may want to visit the MiKTeX project page, if you need help.

An error occurred:
  source file: Libraries\MiKTeX\Core\Process\Process.cpp
  source line: 177
  message: The executed process did not succeed.
  info: fileName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\mpm.exe", exitCode="1"

**Comment by edocevoli** [comment]
The installer wants to set the readonly attribute of `C:\ProgramData\MiKTeX\2.9\fontconfig\config\fonts.conf`. This does not succeed because a third party is blocking the file.
