### ISSUE TITLE
Install error on Windows 10

### ISSUE THREAD

**Issue by tlilburn** [MiKTeX/miktex#172]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [ ] I am reporting a bug others will be able to reproduce
- [ ] I have installed the latest MiKTeX updates
- [ ] I have checked the MiKTeX log files

Running Windows 10 Enterprise version 1709 on a Lenovo laptop, Intel i5-8350U CPU, 8 GB RAM
Downloaded basic-miktex-2.9.6753-x64
Ran install as admin, personal install, paper size = letter
All packages download
Installation fails, log file reads:

installed 3350 package definition files
visiting repository C:\Users\tlr\AppData\Local\Temp\mik85598...
repository type: local package repository
loading lightweight database...
initexmf "--user-install=C:\Users\tlr\AppData\Local\Programs\MiKTeX 2.9" "--common-install=C:\Program Files\MiKTeX 2.9" --set-config-value=[Core]SharedSetup=0 "--log-file=C:\Users\tlr\AppData\Local\Programs\MiKTeX 2.9\miktex/config\uninst.log" --disable-installer --verbose:
Windows API error 122: The data area passed to a system call is too small.

Info: 
Source: Libraries\MiKTeX\Core\Process\win\winProcess.cpp
Line: 608

Sorry, but "MiKTeX Configuration Utility" did not succeed.

You may want to visit the MiKTeX project page, if you need help.

An error occurred:
  source file: Libraries\MiKTeX\Core\Process\Process.cpp
  source line: 177
  message: The executed process did not succeed.
  info: fileName="C:\Users\tlr\AppData\Local\Programs\MiKTeX 2.9\miktex/bin/x64\initexmf.exe", exitCode="1"

**Comment by edocevoli** [comment]
Thank you, I was not able to reproduce the bug on my computer. So it's not possible to fix the bug.

What you can try: reboot your system, disable virus scanners, close all unnecessary applications.
