### ISSUE TITLE
New fontspec-Package 2.6i is needed

### ISSUE THREAD

**Issue by Matthiasss** [MiKTeX/miktex#173]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

The bug in Fontspec 2.6h is known and Will have fixed it in 2.6i available on CTAN. But I cant it use for MikTeX, the package is needed. 

Thank you and regards,
Matthias

**Comment by edocevoli** [comment]
This is not the right issue tracker for these kinds of problems. Please visit https://miktex.org/help, for details.

**Comment by Matthiasss** [comment]
Excuse me, was my fault.
