### ISSUE TITLE
bibtex8 could not handle _absolute_ windows paths

### ISSUE THREAD

**Issue by Pfiffikus** [MiKTeX/miktex#178]
Running bibtex8, i.e. 
```
This is 8-bit Big BibTeX version 0.99d
Implementation:  Microsoft(R) C/C++ for Win32
Release version: 3.71 (18 mar 2013)
```
```
bibtex8 -d all "P:\test.aux"
```
fails with
```
D-I/O: open_ip_file: trying to open `P:/test.aux' ...
D-I/O: open_op_file: trying to open `P:\test.blg' ...
open_op_file: error opening `P:\test.blg'
I couldn't open file name `P:\test.blg'
```
while
```
bibtex8 -d all miktex-portable-2.9.6753\test.aux
```
runs smoothly from console.

**Comment by edocevoli** [comment]
No log files, no input files...

**Comment by Pfiffikus** [comment]
> No log files, no input files ...

yes, log file could NOT be written ... and _any_ input would show that result!

But for the sake of order check yourself if the attachment helps!
[bibtex8.zip](https://github.com/MiKTeX/miktex/files/2305150/bibtex8.zip)

**Comment by edocevoli** [comment]
Thank you. I was able to reproduce it.

As it turns out, this is a feature (not a bug): by default, absolute file writes are not allowed (for security reasons). It is possible to change this behavior this by setting `[Core]AllowUnsafeOutputFiles=t`. But I do not recommend it.

**Comment by edocevoli** [comment]
Indeed. The next MiKTeX version shows a message like this:

    bibtex8: file not writable for security reasons: P:\test.blg
