### ISSUE TITLE
MiKTeX destroys system $env:PATH if it doesn't find itself there

### ISSUE THREAD

**Issue by bazzilic** [MiKTeX/miktex#18]
## Steps to reproduce
1. Remove path to MiKTeX from the system path variable
2. Take note of the current state of the system path variable
3. Launch "Update MiKTeX (Admin)"
4. When prompted to repair MiKTeX installation ("The system doesn't know the path to MiKTeX executables"), agree to repair

### Expected results:
Path to MiKTeX bin folder is added to the end of the system path variable

### Actual results:
The system path variable now has just _one_ path - the path to MikTeX bin folder, everything else is gone

### Versions
MiKTeX - latest version. Here's the output of `miktex-latex -version`:

```
MiKTeX-pdfTeX 2.9.6362 (1.40.18) (MiKTeX 2.9.6400 64-bit)
Copyright (C) 1982 D. E. Knuth, (C) 1996-2016 Han The Thanh
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.54.1; using libcurl/7.54.1 WinSSL
compiled with expat version 2.2; using expat_2.2.0
compiled with jpeg version 9.2
compiled with liblzma version 50020032; using 50020032
compiled with libpng version 1.6.30; using 1.6.30
compiled with libressl version LibreSSL 2.5.3; using LibreSSL 2.5.3
compiled with MiKTeX Application Framework version 2.6416; using 2.6416
compiled with MiKTeX Core version 2.6413; using 2.6464
compiled with MiKTeX Archive Extractor version 1.6300; using 1.6300
compiled with MiKTeX Package Manager version 1.6403; using 1.6447
compiled with poppler version 0.55.0
compiled with uriparser version 0.8.4
compiled with zlib version 1.2.11; using 1.2.11
```

Windows 10 x64 with all the latest updates.

**Comment by edocevoli** [comment]
I was not able to reproduce this. After running the update wizard (as admin), the MiKTeX bin directory was at the end of the system `PATH`. Seems that your `PATH` value contains unusual entries which cause MiKTeX to reset it. I would recommend that you export the user/system `PATH` values to a `.reg` files for further inspection.

**Comment by bazzilic** [comment]
Hmm, I can't reproduce it now as well. It happened the other day on my other computer, will check there tonight.

**Comment by MohannadNaj** [comment]
This happened to me as well.

I'm using windows 10 pro (64-bit), On 26-December-2017 I downloaded the binary basic installer [basic-miktex-2.9.6520-x64.exe (196,291 KB)](https://miktex.org/download/ctan/systems/win32/miktex/setup/basic-miktex-2.9.6520-x64.exe).

**I was installing miktex for the first time**, and I was asked if I should add it to path, didn't expect it will be added as the only one :|

![screenshot](https://i.imgur.com/cVC4m5Y.png)
