### ISSUE TITLE
Unable to  compile after last update

### ISSUE THREAD

**Issue by Alfonsib** [MiKTeX/miktex#183]
I've updated MiKTeX this morning (25/8).The update ended in an error message, but MiKTeX Update said everything was updated. However, when I tried to compile a very short file, I had again an error message in a popup window, saying something (very long and cryptic) couldn't be found in MiKTeX209-core.dll.
Closing this window, a second popup window informed that PDFLaTeX returned Exit Code (3221225785).

What can be done? Thanks in advance for your help.
B. Alfonsi

**Comment by edocevoli** [comment]
I cannot reproduce this, i.e., this works for me: 

> I tried to compile a very short file
