### ISSUE TITLE
Update causes error

### ISSUE THREAD

**Issue by majohhhhhhh** [MiKTeX/miktex#184]
Update of my MikTeX caused this error:
![grafik](https://user-images.githubusercontent.com/42744996/44668498-da6ab580-aa1d-11e8-85f8-b498d6ab451a.png)

![grafik](https://user-images.githubusercontent.com/42744996/44668515-eeaeb280-aa1d-11e8-90c9-00cec571884e.png)
System: Windows 7

thank you

**Comment by edocevoli** [comment]
Thank your for your report. I tried to reproduce the issue:

1. Download and run `basic-miktex-2.9.6753-x64.exe`
2. Start MiKTeX Console
3. Check for updates
4. Install updates

No issues, i.e. it works for me.
