### ISSUE TITLE
Problems after reinstallation of MikTex

### ISSUE THREAD

**Issue by Olchi69** [MiKTeX/miktex#186]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [ x] I am reporting a bug others will be able to reproduce
- [ ] I have installed the latest MiKTeX updates
- [x ] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions
2. input files which are necessary to reproduce the bug
3. your observations (command output, screenshots, ...)
4. relevant log file snippets

I haven't installed the  latest updates because the miktex console doesn't install them. 

After problems with miktex, I re-installed it, but now apart form the aforementioned problem, I get the following log-File: 
Command Line:   latex.exe --src --interaction=errorstopmode --synctex=-1 "Funktionen.tex"
Startup Folder: D:\fhh\AngewandteMathematik\Analysis1\Skript

ERROR: Windows API error 87: Falscher Parameter.

ERROR: Info: path="C:\Users\dippel\AppData\Local\MiKTeX\2.9\miktex/data/le\df2c24cb21984fa85003c1ecc818ff83.fndb"
ERROR: Source: Libraries\MiKTeX\Core\MemoryMappedFile\win\winMemoryMappedFile.cpp
ERROR: Line: 83

Sorry, but latex.exe did not succeed.

You may want to visit the MiKTeX project page, if you need help.

_____________________________________________________________________

 LaTeX Compilation Report (Pages: 0)

 Errors: 0   Warnings: 0   Bad Boxes: 0
_____________________________________________________________________

**Comment by edocevoli** [comment]
You have to install the latest MiKTeX updates. Try it with `mpm --update`.

Please read the guidelines:
https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md
