### ISSUE TITLE
Windows 7 admin installation: updating process buggy

### ISSUE THREAD

**Issue by GuyHedelin** [MiKTeX/miktex#187]
When I updated to the new MikTeX the process ended with an error:

![errorupdatemiktex](https://user-images.githubusercontent.com/33807971/44786272-dfea0c00-ab93-11e8-800f-078fab69882c.PNG)

I tried to deinstall MikTeX to reinstall from scratch but I got this error and couldn't deinstall:

![errordeinstall](https://user-images.githubusercontent.com/33807971/44786323-09a33300-ab94-11e8-9267-8981ff64f26e.PNG)

I tried to install it as a portable and update but same problem. With an installation as private (not for all users) and update same problem.

I run windows 7 x64 and MikTeX x64.

**Comment by edocevoli** [comment]
Thank you for writing the report. It is not yet clear what you did. Please attach all relevant log files. Also necessary: a step-by-step reproduction recipe.

**Comment by GuyHedelin** [comment]
Hi Christian,

I have no long the logs because I araised all hte directories before I reinstalled MikTeX from scratch with the basic installer (the last version is from june). I can describe the steps have made to update:

1 - I ran the console
2 - I chose "update" in the list left
3 - I clicked "check for update"
4 - there was a list of 93 updates (a lot required)
5 - I clicked update now
6 - at the end there was the first message of my report
7 - I clicked ok in the message
8 - after that I couldn't compile any file even a simple hello world.

I reinstalled MikTeX for all users and it ran fine until I updated.
Then I reinstalled MikTeX just for me and it ran fine until I updated.
I installed MikTeX as portable and it ran fine until I updated.

So at last I reinstalled MikTeX for all users and didn't update.

If the portable version can be installed without disturbing my installation for all users I can do it and update to send you the logs.

It seems there is something with the Miktex209-core.dll but I don't know what.


----- Mail original -----
De: "Christian Schenk" <notifications@github.com>
À: "MiKTeX/miktex" <miktex@noreply.github.com>
Cc: "GuyHedelin" <guy.hedelin@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mercredi 29 Août 2018 14:17:04
Objet: Re: [MiKTeX/miktex] updating process buggy (#187)



Thank you for writing the report. It is not yet clear what you did. Please attach all relevant log files. Also necessary: a step-by-step reproduction recipe.

**Comment by edocevoli** [comment]
There is a new version (2.9.6813) of the installer available. This fixes it.

If you still have issues: Please collect the MiKTeX log files.

**Comment by edocevoli** [comment]
By the way: I cannot reproduce the bug on Windows 10 machines. So this seems to be an Windows 7 specific issue.

**Comment by GuyHedelin** [comment]
It can be because on TeXexchange the other people having had this problem are all on windows 7. I will install the new version with the installer. Do I have to deinstall the version of june before?

----- Mail original -----
De: "Christian Schenk" <notifications@github.com>
À: "MiKTeX/miktex" <miktex@noreply.github.com>
Cc: "GuyHedelin" <guy.hedelin@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 30 Août 2018 10:57:43
Objet: Re: [MiKTeX/miktex] updating process buggy (#187)



By the way: I cannot reproduce the bug on Windows 10 machines. So this seems to be an Windows 7 specific issue.

**Comment by edocevoli** [comment]
Yes, you must wipe the old version. If the uninstaller is not working, you can do it manually by:

1. remove all TEXMF root directories
2. remove MiKTeX.org registry keys: `HKEY_LOCAL_MACHINE\Software\MiKTeX.org`, `HKEY_CURRENT_USER\Software\MiKTeX.org`

**Comment by GuyHedelin** [comment]
I did deinstalled MikTeX using the console. The registry keys have been deleted but the roots are not completly deleted (MikTex 2.9/miktex/bin is not deleted but emptied).

----- Mail original -----
De: "Christian Schenk" <notifications@github.com>
À: "MiKTeX/miktex" <miktex@noreply.github.com>
Cc: "GuyHedelin" <guy.hedelin@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 30 Août 2018 11:15:27
Objet: Re: [MiKTeX/miktex] updating process buggy (#187)



Yes, you must wipe the old version. If the uninstaller is not working, you can do it manually by: 

    1. remove all TEXMF root directories 
    2. remove MiKTeX.org registry keys: HKEY_LOCAL_MACHINE\Software\MiKTeX.org , HKEY_CURRENT_USER\Software\MiKTeX.org

**Comment by GuyHedelin** [comment]
I installed the new version with the setup and all is fine yet. Vielen Dank. I just had to delete manually the root in program files (cf. my last email) otherwise the setup don't run.

----- Mail original -----
De: "Christian Schenk" <notifications@github.com>
À: "MiKTeX/miktex" <miktex@noreply.github.com>
Cc: "GuyHedelin" <guy.hedelin@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 30 Août 2018 11:15:27
Objet: Re: [MiKTeX/miktex] updating process buggy (#187)



Yes, you must wipe the old version. If the uninstaller is not working, you can do it manually by: 

    1. remove all TEXMF root directories 
    2. remove MiKTeX.org registry keys: HKEY_LOCAL_MACHINE\Software\MiKTeX.org , HKEY_CURRENT_USER\Software\MiKTeX.org

**Comment by edocevoli** [comment]
I was able to reproduce the issue on a Windows 7 machine. But it only occurs when you install for all users. The default (non-admin, private) setup option works.

**Comment by edocevoli** [comment]
When this error (`The specified procedure could not be found`) occurs: you can repair the MiKTeX installation by running:

    initexmf --admin --update-fndb
    initexmf --admin --mklinks --force

This unbends program files like `pdflatex.exe`.

**Comment by majohhhhhhh** [comment]
Thank you, this procedure solves the problem.

**Comment by GuyHedelin** [comment]
Actually I also installed MikTex as private and the update went wrong as for all users, even the portable version had a problem. It is perhaps only by me because I read that others proposed to install it as private and it worked for them.

----- Mail original -----
De: "Christian Schenk" <notifications@github.com>
À: "MiKTeX/miktex" <miktex@noreply.github.com>
Cc: "GuyHedelin" <guy.hedelin@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 30 Août 2018 14:19:41
Objet: Re: [MiKTeX/miktex] updating process buggy (#187)



I was able to reproduce the issue on a Windows 7 machine. But it only occurs when you install for all users. The default (non-admin, private) setup option works.

**Comment by motib** [comment]
I updated to 6813 and installed for "me only". When I tried compiling a book that uses about a dozen packages, it updated one package and then crashed on the next one. I ran again and the same thing happened. So I had to run pdflatex about a dozen times to get everything updated.

**Comment by dillasyx** [comment]
I'm on the newest version, tried the workarounds and still get the error when trying to update.

**Comment by elfsoft2000** [comment]
Note the use of /bin/ in the pathname, rather than \bin\.  My error report (closed too quickly) and another person's problems all seem to be related to the use of foreward slashes.

**Comment by Omcsesz** [comment]
I also have the same error on my system.
