### ISSUE TITLE
don't update to luatex 1.08 directly - incompatible with current luaotfload

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#189]
luatex 1.08 has been released yesterday. This luatex version is not compatible with the luaotfload currently on ctan so even simple lualatex documents don't compile (see e.g. https://tex.stackexchange.com/questions/448832/problems-with-luatex-1-08-even-on-a-very-simple-document).

It will take a  bit time until a new luaotfload gets to ctan, so I suggest that you wait with the update to luatex 1.08.

**Comment by u-fischer** [comment]
I have uploaded a new luaotfload and a new lualibs  to CTAN.  Both packages have been also tested LuaTeX, Version 1.09.0 and seems to work fine.  So an update should be possible when the packages are in the tex systems.

**Comment by edocevoli** [comment]
LuaTeX 1.09 is now available as a MiKTeX binary.
