### ISSUE TITLE
option --user-install of MiKTeX setup utility is ignored

### ISSUE THREAD

**Issue by MarkosMitsos** [MiKTeX/miktex#19]
we deploy MiKTeX for all user via the setup utility using (... is an appropriate path)
"...\miktexsetup.exe" install
--common-roots="H:\LaTeX\packages etc\texmf"
--local-package-repository="...\packages"
--modify-path=yes
--package-set=complete
--quiet
--shared=yes
--use-registry=yes
--user-config="<APPDATA>\MiKTeX\2.9\conf_inst"
--user-data="<APPDATA>\MiKTeX\2.9\data"
--user-install="<APPDATA>\MiKTeX\2.9\conf_inst"
--user-roots="<APPDATA>\LaTeX\packages etc\texmf"

The installation works very well, except that the --user-install option is ignored.
No corresponding registry key is created and Settings shows that ="<APPDATA>\MiKTeX\2.9" is used instead (probably an internal standard?).
We also tried separating the Install and Config folders but without success.

**Comment by edocevoli** [comment]
This has been fixed with in the latest version of the setup utility.
