### ISSUE TITLE
Optimal package update?

### ISSUE THREAD

**Issue by Friedrich2** [MiKTeX/miktex#190]
In my daily use, one of the most boring exercise is updating the packages. This task needs some time, which I could spend better. Being bored, I thougt about the update process. How is it done in the MikTeX Package Manager? My **idea** was that there are two sets:

- one (named A, size n) with all installed packages (and their version as property)
- and one (named B, size m) with all packages (in their newest version) on the server. 

The task is then to find the complement (with regard to A) of the biggest common subset (BCS). Due to the comparatively small size of A, we have to solve only the BCS problem.
### List complexity assumption
linear access time, but iterator advance of k steps in O(k).

### Thought
Is this done by simply asking, wether every element of set A is in set B (in o(n*m)) or are the (which shall be compared) two sets sorted (both lists could be kept sorted), such that a comparison could be much faster (O(n + m))?

### Example
First strategy:
A: Package Z, Package Y, Package X
B: Package A, Package B, ..., Package Z
Asking wether Z is in B: 26 comparisons.
Asking wether Y is in B: 25 comparisons.
Asking wether Z is in B: 24 Comparisons
--> about 3 * 26 comparisons.      (O(m*n))

Second strategy: (A sorted previously)
A: Package X, Package Y, Package Z
B: like above.
Asking wether X in B: 24 comparisons (save position 24).
Asking wether Y in B: Y (by sorting) guaranteed to be after X at position 24 --> one comparison.
Asking wether Z in B: Z (by sorting) guaranteed to be after Y --> one comparison.
Total: 24 + 1 + 1 comparisons.       (in O(m + n) (even in O(m) since n < m)).

### Question
Thus, my question is: Is the first strategy (naive approach) implemented and if yes, would it make sense (from an optimisation perspective) to implement another one (like the second strategy, LCS problem)? Or do I have false assumptions concerning the list complexity?

The implementation of the second strategy should be a relatively small task (keep lists always sorted, advance using iterator). Due to a big and long-lasting project, I do not have enough time (and not enough knowledge) to implement it myself.

**Comment by edocevoli** [comment]
Thank you for your question. The update mechanism works as follows:

1. download of the package database from a remote host
2. check each installed package against the downloaded package database
3. if a newer version is available: put the package into the list
4. present the list
5. install selected updates
