### ISSUE TITLE
Add -max-print-line and friends to LuaLaTeX CLI

### ISSUE THREAD

**Issue by niklasholm** [MiKTeX/miktex#192]
pdfLaTeX and XeLaTeX command line interfaces has these options `-max-print-line`, `-error-line` and `-half-error-line` which I found very helpful att improving terminal output. It would be nice if those could be used with LuaLaTeX's CLI as well.

**Comment by sharadhr** [comment]
Is there any chance this could be reopened and fixed? The newlines generated by the LuaTeX output being forced to 80 columns cause a lot of issues for warning and error parsers in several editors/TeX IDEs like TeXStudio and VS Code LaTeX Workshop, amongst others. 

I wouldn't mind opening a branch and PR, if necessary.
