### ISSUE TITLE
Add option to change directory for binaries (Linux)

### ISSUE THREAD

**Issue by niklasholm** [MiKTeX/miktex#195]
Whether you install system-wide or user-locally, having the binary directory paths hard-coded to `/usr/local/bin` and `~/bin` respectively is very inconvenient for advanced users who like to keep stuff separate for various reason. For example, having a dedicated bindir for miktex binaries would make coexistence with other latex distributions much easier. Please add an option to `miktexsetup` and whatever else needs changing so that we can install the binaries wherever we want to.

**Comment by arrowd** [comment]
I'm almost finished a port for FreeBSD and I also need this feature.

**Comment by edocevoli** [comment]
My plan is to implement this feature in the [near future](https://github.com/MiKTeX/miktex/milestone/11).

**Comment by edocevoli** [comment]
Thank you. This has been fixed now. You can change the location of the link target directory in MiKTeX Console or by executing `initexmf`:

System-wide:

```
initexmf --set-config-value=[Core]CommonLinkTargetDirectory=/path/to/bin/directory
```

Private install:

```
initexmf --set-config-value=[Core]UserLinkTargetDirectory=/path/to/bin/directory
```

**Comment by mistune** [comment]
Hello @edocevoli , how do we go about doing this during installation?
