### ISSUE TITLE
Miktex Console update fails

### ISSUE THREAD

**Issue by wojoeraf** [MiKTeX/miktex#196]
Trying to update packages with Miktex Console. Fails.
Miktex Version: 2.9.6809

**Clipboard:**
MiKTeX: 2.9
OS: Windows 7 Professional, 64-bit, Service Pack 1, build 7601
SharedSetup: no
PathOkay: yes
SystemAdmin: no
RootPrivileges: no
Root0: C:\Users\rzadmin\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\rzadmin\AppData\Local\MiKTeX\2.9
Root2: C:\Users\rzadmin\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\rzadmin\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\rzadmin\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\rzadmin\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: cmd

**Error message:**
Windows API error 2: Das System kann die angegebene Datei nicht finden.
commandLine="mpm --register-components --verbose", fileName="C:\Users\rzadmin\AppData\Local\Programs\MiKTeX 2.9\miktex/bin/x64\mpm.exe"

The german error message says that the system isn't able to find the file given in the command. So it is, there is no mpm.exe in the defined folder.

**Comment by edocevoli** [comment]
Seems that the file has been deleted. You should be able to fix this by running the update again. If the issue persists: please attach the log files and create a directory listing of `C:\Users\rzadmin\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64`,
