### ISSUE TITLE
Parsing of Biber output

### ISSUE THREAD

**Issue by Friedrich2** [MiKTeX/miktex#197]
Assumption: Most of the MiKTeX users are harness biber to make bibliographies easily. It's some kind of standard program. This command line tool has very useful output, which is often overlooked, because it is hidden somewhere in the logfile (e. g. when using build skripts).

I propose to parse the output of biber in the same way into the nice "Errors, warning badboxes" view as the output of the common latex compilers like pdfTeX or XeLaTeX.

I assume that this parsing function is currently offered by using regular expressions.
In order to implement this, the regexes should be supplemented with something like "INFO - *", "WARN - *" and the error message line format. It should be relatively easy to undertake for someone with a good knowledge where the parsing happens.

Thus, extensive scrolling of big logfiles can be prevented and the probality is higher that the user does regard biber's output messages.

**Comment by edocevoli** [comment]
I assume we are talking about `texify` (the MiKTeX compiler driver) and you suggest that `texify` runs `biber` (instead of `bibtex`) and then parses the log files?

**Comment by Friedrich2** [comment]
Yes. I am interested to look at this issue, but do not have the time now. Perhaps in a few months. Thank you for giving me a hint that texify is  responsible!
