### ISSUE TITLE
FATAL xelatex - No space left on device

### ISSUE THREAD

**Issue by wlos** [MiKTeX/miktex#198]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

I try to use MiKTex to make a pdf file from the project [hithesis ](https://github.com/dustincys/hithesis).
I have installed the latest MiKTex on win 10 v 1803.
When I input the command `xelatex .\main.tex`, part of the results are shown as follow.
> Sorry, but "C:\MiKTeX 2.9\miktex\bin\x64\xelatex.exe" did not succeed.
> The log file hopefully contains the information to get MiKTeX going again:
> C:\Users\WL\AppData\Local\MiKTeX\2.9\miktex\log\xelatex.log
> xdvipdfmx:fatal: File ended prematurely
> Output file removed.

xelatex.log :

> 2018-09-22 23:55:36,594+0800 INFO  xelatex - starting with command line: "C:\MiKTeX 2.9\miktex\bin\x64\xelatex.exe" .\main.tex
> 2018-09-22 23:55:36,603+0800 INFO  xelatex - allowing known shell commands
> 2018-09-22 23:55:36,604+0800 INFO  xelatex - enabling input (output) from (to) processes
> 2018-09-22 23:55:42,625+0800 FATAL xelatex - No space left on device
> 2018-09-22 23:55:42,625+0800 FATAL xelatex - Info: 
> 2018-09-22 23:55:42,625+0800 FATAL xelatex - Source: libraries\miktex\texandfriends\include\miktex\c4p\C4P.h
> 2018-09-22 23:55:42,625+0800 FATAL xelatex - Line: 477
> 2018-09-22 23:55:42,635+0800 INFO  xelatex - finishing with exit code 1

But the command `xelatex .\main.tex` can be successfully run with texlive 2018 on ubuntu 14.04.
Can someone help explain what caused this error?

**Comment by edocevoli** [comment]
It is not possible to help you, unless you provide a minimal test case.

**Comment by wlos** [comment]
I just want to know what caused this error.  Please provide some ideas for solving this problem.

**Comment by edocevoli** [comment]
Sorry, but I don't yet know what caused the error.

**Comment by ZeroKill1024** [comment]
i reproduce this issue if the file named in chinese and connect with '-' , e.g 测试-副本.tex

**Comment by edocevoli** [comment]
Works for me:

1. open Windows Terminal (Preview) version 0.8.10261.0
1. `chcp 65001`
1. `pdflatex 测试-副本.tex`

Result:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 2.9.7300 64-bit)
entering extended mode
(测试-副本.tex
LaTeX2e <2020-02-02>
L3 programming layer <2020-02-03>
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"))
("C:\Program Files\MiKTeX 2.9\tex/latex/l3backend\l3backend-pdfmode.def")
(测试-副本.aux) [1{C:/Users/xxx/AppData/Local/MiKTeX/2.9/pdftex/config/
pdftex.map}] (测试-副本.aux) )<C:/Program Files/MiKTeX 2.9/fonts/type1/publ
ic/amsfonts/cm/cmr10.pfb>
Output written on 测试-副本.pdf (1 page, 12438 bytes).
Transcript written on 测试-副本.log.
```
