### ISSUE TITLE
miktex searches the whole file system if grffile is used

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#199]
Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

The following needs an eps-file, (bild3.eps) in the current folder, for which no pdflatex compatible variant exists (neither bild3.pdf, nor bild3.jpg etc).

Then run pdflatex on this document:
~~~~
\documentclass{article}
\usepackage{grffile}
\begin{document}

\includegraphics{bild3}

\end{document}
~~~~

At the first compilation this will create <./bild3-eps-converted-to.pdf>. 

At the next compilation miktex will make a *long* pause at the includegraphics command. 

In the trace I can see thousands of line like this:

~~~~
[20220] [MiKTeX] TRACE pdflatex.core - accessing file D:\MiKTeX2.9\tex/generic\babel\locale\mfe\bild3.pdf.tex: NOK 
~~~~

So miktex is searching everywhere for bild3.pdf.tex before using bild3-eps-converted-to.pdf.

Using graphicx instead of grffile works fine. In texlive there is no problem.

**Comment by edocevoli** [comment]
I think it makes a difference if you don't turn on tracing.

Slow:

```
pdflatex --trace=access test.tex
```

Not so slow:

```
pdflatex --trace=access test.tex
```

**Comment by u-fischer** [comment]
I turned tracing on to investigate the problem (which was reported to me, so it is not only my machine), but had the problem already without it.  I digged a bit further: grffile uses \pdffilesize to test if a file exists (it is empty if not), and if a file doesn't exist this is very slow on miktex:

~~~~
\documentclass{book}
\begin{document}
\showoutput \tracingmacros=1

\typeout{xxxxxxxxxxxxxxxxxxxxx} %here pause ....

\edef\blub{\pdffilesize{dontexist-image.pdf}}\show\blub

\typeout{yyyyyyyyyyyyyyyyyy}   % here no pause

\edef\blub{\pdffilesize{example-image.pdf}}\show\blub

\typeout{zzzzzzzzzzzzzzzzzzzzz}

\end{document}
~~~~

in texlive both parts take the same (short) time.  As with grffile pdftex looks for a number of non-existing files (pdf, png etc) this sums up.

**Comment by edocevoli** [comment]
MiKTeX always search the disk, even if a file name database exists. TeX Live has the nice `!!` feature (in `texmf.cnf`), which prevents "disk pounding". I will take a look at the TeX Live implementation.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
