### ISSUE TITLE
JPG-Images are not shown in Texworks 64-bit preview

### ISSUE THREAD

**Issue by ulrich1a** [MiKTeX/miktex#2]
Steps to reproduce the problem:

    - Create a document with the package graphicx
    - includegraphics with a jpg-file
    - compile the document

Expected output: A preview with the jpg-file displayed

Actual output: A preview with a blank white rectangle instead

TeXworks version: 0.6.2
TeXworks obtained from: MikTeX 2.9.6350 64-bit [r.7.ecce17, 29.04.2017
Operating system: Windows 10, 64bit

Please provide any additional information below:
Everything was ok with Texworks 0.6.1 in Windows 7 32-bit.
The created PDF with the 64-bit version has the image, so it is a previewer problem.
Other image-types like png and pdf do work as expected.
It seems to be a specific problem of the windows 64-bit version.
Here is a minimum working example, that expose the problem in the 64-bit-version.
[mwe.zip](https://github.com/MiKTeX/miktex/files/1280995/mwe.zip)

**Comment by edocevoli** [comment]
Please: don't write bug reports against outdated software.

**Comment by edocevoli** [comment]
![capture](https://user-images.githubusercontent.com/20090840/30130379-2e9ff26a-9349-11e7-8dd5-4ee21e615f64.PNG)
