### ISSUE TITLE
pdfLaTeX crashes on file inclusion

### ISSUE THREAD

**Issue by projekter** [MiKTeX/miktex#20]
After the update to the experimental version of today (`Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6481 NEXT 64-bit)`), the inclusion of a PDF that always worked before results in a crash of pdfLaTeX. LuaLaTeX compiles without issues. The version I used before was perhaps a month old or so and worked fine for both compilers.

I analyzed my PDF with Acrobat and no syntax errors were found. Slight modifications or conversions to PDF/X that _do not alter the visual appearance_ lead to the same error. Conversions to older PDF/X formats or to PDF/A that _remove the smoothness_ from the shadow lead to a successful compilation. However, since it worked before, I think pdfLaTeX should support the PDF as it currently is.
```LaTeX
   \documentclass{article}
   \usepackage{graphicx}
   \begin{document}
      \includegraphics{Warning.pdf}
   \end{document}
```
[Warning.pdf](https://github.com/MiKTeX/miktex/files/1382902/Warning.pdf)

**Comment by edocevoli** [comment]
When you say pdflatex crashed, you mean that the program terminates without an error message?

**Comment by projekter** [comment]
Exactly. When it tries to include the PDF, pdfLaTeX as the application crashes ("does not work any more"-message from Windows and the application is gone). That's why I report the issue here and not e.g. to the people of the `graphicx` package.

Am 13.10.2017 22:44 schrieb Christian Schenk <notifications@github.com>:When you say pdflatex crashed, you mean that the program terminates without an error message?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MiKTeX/miktex","title":"MiKTeX/miktex","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MiKTeX/miktex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@edocevoli in #20: When you say pdflatex crashed, you mean that the program terminates without an error message?"}],"action":{"name":"View Issue","url":"https://github.com/MiKTeX/miktex/issues/20#issuecomment-336562692"}}}

**Comment by edocevoli** [comment]
Thank you for reporting the issue. I have fixed the bug and the NEXT repository contains the fixed version.
