### ISSUE TITLE
Windows installation error when the installation directory includes non-ASCII characters

### ISSUE THREAD

**Issue by ajriesgo** [MiKTeX/miktex#203]
The issue I have come across is exactly the same one as was mentioned earlier this year in a Tex StackExchange question: https://tex.stackexchange.com/q/425789. Basically, right now I am using a computer with windows 10 where I log in with the user name "Ángel" (note the accented "Á"). When I tried installing MiKTeX 2.9.6813 here today, the installation program suggested the path "C:\Users\Ángel\AppData\Local\Programs\MiKTeX 2.9", which I accepted. The installation eventually fails with a message "Conversion from UTF-8 byte sequence to wide character string did not succeed".

I have checked that the issue can be reproduced by specifying any path with non-ASCII characters. The steps are:

1. Run the installation program for Windows for MiKTeX 2.9.6813
2. When the installation directory is suggested, enter "C:\Ángel" with an accented "Á" (I expect any other path with at least a non-ASCII character would also lead to the same error).
3. After a few minutes, the installation fails with the error "Conversion from UTF-8 byte sequence to wide character string did not succeed".

I attach the log file generated when I reproduced the issue following the above steps.
[setup-2018-10-02-17-51.log](https://github.com/MiKTeX/miktex/files/2438640/setup-2018-10-02-17-51.log)

**Comment by edocevoli** [comment]
Thank you. Please, can you check the log directory (`"%LOCALAPPDATA%\MiKTeX\2.9\miktex\log"`) for the other log files.

**Comment by ajriesgo** [comment]
Hi, I'm afraid I don't know what "the other log files" are. I've found no *.log files in that directory other than the one I attached (setup-2018-10-02-17-51.log).

**Comment by edocevoli** [comment]
Don't worry. It seems that the log files are not yet there. In the meantime I was able to reproduce the bug. I will make available a fixed installer asap.

**Comment by edocevoli** [comment]
The new installer is now available. It's now possible to install to `C:\Ángel`.

**Comment by ajriesgo** [comment]
Wow! That was quick :)
