### ISSUE TITLE
store log-files of "build format" runs 

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#206]
Could the last logs of the format builds be stored in e.g. `...\AppData\Local\MiKTeX\2.9\miktex\log` (or a subfolder)? That would make it easier to investigate format build failures. Currently I can only find the various miktex logs which says that the format creation failed.

**Comment by edocevoli** [comment]
By the way, if something goes wrong, the screen output of `makefmt` is stored in a `.out` file.

**Comment by edocevoli** [comment]
This has been fixed with MiKTeX 20.10: log files created during format creation are now kept forever. The file name template is:
`miktex/log/makefmt/FORMAT/YYYY-MM-DD-HH-MM-SS`
