### ISSUE TITLE
Arch Linux packages

### ISSUE THREAD

**Issue by edocevoli** [MiKTeX/miktex#207]
_Cloned from MiKTeX/miktex-packaging#53 by @iojeda_

I was wondering if you guys can create the install packages for Arch Linux.
Thanks

**Comment by ccat3z** [comment]
I created PKGBUILD for miktex and submitted it on [AUR miktex-git](https://aur.archlinux.org/packages/miktex-git/).

**Comment by sunqi1993** [comment]
@ccat3z  I have tried that PKGBUILD, It can build successful but miktex-* like cmd doesn't work and run into segment fault
