### ISSUE TITLE
 MikTeX console doesn't work

### ISSUE THREAD

**Issue by rnietoc** [MiKTeX/miktex#208]
When I update some files with the console, the following message appears:

MiKTeX Problem Report
Message: Windows API error 127: No se encontró el proceso especificado.

Data: dllName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core.dll"
Source: Libraries\MiKTeX\Core\win\DllProc.cpp
Line: 62
MiKTeX: 2.9
OS: Windows 7 Professional, 64-bit, Service Pack 1, build 7601
Invokers: explorer
SystemAdmin: yes
PowerUser: no
Root0: C:\Users\Rafa\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Rafa\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Rafa\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Rafa\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Rafa\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

And afterwards the console cease to work, and so do LaTeX. As far as I can see, the problem is the "/" in the path

**Comment by edocevoli** [comment]
Please attach all log files (`...\miktex\log`).
