### ISSUE TITLE
Linux Mint 19 Install Problems (with solution!)

### ISSUE THREAD

**Issue by alexandermichels** [MiKTeX/miktex#209]
I have been using MikTex on LinuxMint for a while with no problems, but after upgrading to Linux Mint 19, I was not longer able to install it. I am following the steps on the [Install MiKTeX for Linux](https://miktex.org/howto/install-miktex-unx) page. 

> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
echo "deb http://miktex.org/download/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list
sudo apt-get update
sudo apt-get install miktex

It gives the error:

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 miktex : Depends: libhunspell-1.3-0 (>= 1.3.3) but it is not installable
          Depends: libicu55 (>= 55.1-1~) but it is not installable
          Depends: libmpfr4 (>= 3.1.3) but it is not installable
          Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
E: Unable to correct problems, you have held broken packages.

I've tried searching the packages in apt (the root names so "libhunspell" rather than "libhunspell-1.3-0") and installed the most recent candidates I could find, but things still didn't work. I have done an update and dist-upgrade. I also tried cleaning things and starting over using this sequence:

> sudo apt-get remove miktex
sudo apt-get purge miktex
sudo apt-get autoclean

and I've run

> sudo dpkg --configure -a

but I keep getting the same error, even if I use the "-f" flag with install.

I ended up finding the solution [here](https://askubuntu.com/questions/741410/skipping-acquire-of-configured-file-main-binary-i386-packages-as-repository-x). You need to set "/etc/apt/sources.list.d./miktex.list" to:

> deb [arch=amd64] http://miktex.org/download/ubuntu bionic universe

Hope this helps others if they have issues and you may want to change the installation instructions, but I'm not an expert in Ubuntu or apt, so who knows. Thank you so much for all of your work either way, I love MiKTeX!

**Comment by TobiasPleyer** [comment]
I encountered a similar issue:

> $ echo "deb http://miktex.org/download/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list
> $ sudo apt-get update
> Hit:1 http://ftp.uni-stuttgart.de/ubuntu bionic InRelease
> Ign:3 http://ftp-stud.hs-esslingen.de/pub/Mirrors/packages.linuxmint.com tina InRelease                                                                                                     
> Hit:4 http://ftp.uni-stuttgart.de/ubuntu bionic-updates InRelease                                                                                                                           
> Hit:5 http://ftp.uni-stuttgart.de/ubuntu bionic-backports InRelease                                                                                                                         
> Hit:6 http://archive.canonical.com/ubuntu bionic InRelease                                                                                                                                  
> Hit:7 http://ftp-stud.hs-esslingen.de/pub/Mirrors/packages.linuxmint.com tina Release                                                                                                       
> Hit:8 https://updates.signal.org/desktop/apt xenial InRelease                                                                                                                               
> Ign:9 https://apache.bintray.com/couchdb-deb bionic InRelease                                                                                                                    
> Get:10 https://apache.bintray.com/couchdb-deb bionic Release [1.840 B]                                                                                              
> Get:2 https://ctan.mirror.norbert-ruehl.de/systems/win32/miktex/setup/deb bionic InRelease [2.034 B]             
> Hit:11 http://security.ubuntu.com/ubuntu bionic-security InRelease                                               
> Get:14 https://ctan.mirror.norbert-ruehl.de/systems/win32/miktex/setup/deb bionic/universe amd64 Packages [2.190 B]
> Fetched 6.064 B in 1s (8.903 B/s)                                
> Reading package lists... Done
> N: Skipping acquire of configured file 'universe/binary-i386/Packages' as repository 'http://miktex.org/download/ubuntu bionic InRelease' doesn't support architecture 'i386'

Applying the above fix mentioned by @alexandermichels solves the issue fome too:

> $ echo "deb [arch=amd64] http://miktex.org/download/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list
> $ sudo apt-get update
> Hit:1 http://ftp.uni-stuttgart.de/ubuntu bionic InRelease
> Ign:3 http://ftp-stud.hs-esslingen.de/pub/Mirrors/packages.linuxmint.com tina InRelease                                                                                                     
> Hit:4 http://ftp.uni-stuttgart.de/ubuntu bionic-updates InRelease                                                                                                                           
> Hit:5 http://ftp.uni-stuttgart.de/ubuntu bionic-backports InRelease                                                                                                                         
> Hit:6 http://ftp-stud.hs-esslingen.de/pub/Mirrors/packages.linuxmint.com tina Release                                                                                                       
> Hit:7 http://archive.canonical.com/ubuntu bionic InRelease                                                                                                                                  
> Hit:8 https://updates.signal.org/desktop/apt xenial InRelease                                                                                                                               
> Ign:9 https://apache.bintray.com/couchdb-deb bionic InRelease                                                                                                                               
> Get:10 https://apache.bintray.com/couchdb-deb bionic Release [1.840 B]                                                                                                     
> Hit:2 https://ctan.net/systems/win32/miktex/setup/deb bionic InRelease                                                        
> Hit:11 http://security.ubuntu.com/ubuntu bionic-security InRelease       
> Fetched 1.840 B in 1s (2.977 B/s)                  
> Reading package lists... Done

**Comment by TobiasPleyer** [comment]
I think this should be mentioned on [the download page](https://miktex.org/download)
