### ISSUE TITLE
MiKTeX on Fedora 26

### ISSUE THREAD

**Issue by yasmin2623** [MiKTeX/miktex#21]
Hi please can you help me with installing MiKTex on Fedora 26 ? The changes I have made in the tutorial for Linux are not working so I am not sure whether I am doing it right (for example sudo apt-key should be sudo yum or dnf install? How to replace adv?)

**Comment by edocevoli** [comment]
Please note that only Ubuntu 16.04 (and derivates) is supported at the moment. RPM based Linux distributions will be supported later (see [here](https://miktex.org/kb/roadmap-2-9)).
