### ISSUE TITLE
Error in installing updates

### ISSUE THREAD

**Issue by guocuozuoduo** [MiKTeX/miktex#211]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [ ] I have installed the latest MiKTeX updates (not possible, due to the error detailed here)
- [x] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions

   1. Install a new copy of MiKTeX 2.9.6850
   2. Proceed as directed to check for updates on completion
   3. 214 updates are available, all with action "remove"
   4. Select "update now"

2. input files which are necessary to reproduce the bug
None
3. your observations (command output, screenshots, ...)
   1. Error report: Windows API Error 2: The system cannot find the file specified.
   Details:
`commandLine="mpm --register-components --verbose", fileName="C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\miktex/bin/x64\mpm.exe"`
   2. On a second check for updates, only 4 updates are listed, all with action "install" and "update not possible in user mode". (It was also not possible to "restart as administrator".)
   3. After exiting miktex-console, it cannot be opened again, due to most of the files in the directory `C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64`, now having the file extension `*.(old)`.
4. relevant log file snippets
[miktex-console.log](https://github.com/MiKTeX/miktex/files/2499711/miktex-console.log)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/2499707/miktex-report.txt)

**Comment by edocevoli** [comment]
Seems that you have a leftover MiKTeX admin installation. Cleaning the leftovers and installing MiKTeX in user-mode should fix it. If you still have problems: please attach all `.log`/`.out` files.
