### ISSUE TITLE
Add global administrator option

### ISSUE THREAD

**Issue by burgealex** [MiKTeX/miktex#212]
**Problem statement:**
Right now, the user must specify --admin and --miktex-admin when running miktex tools and scripts on the command line if in an elevated command prompt.  It is up to package developers to ensure the undocumented miktex-admin flows down to all miktex tools and executables.  In some system configurations, using a user level command line is unavoidable.  Dealing with this is clumsy, error prone, and requires a lot of coordination with package developers that may not ever use an elevated command prompt.

**Examples:**
- pdfcrop : calls pdftex without --miktex-admin.  Result is that it may not work at all because pdftex can call initexmf without --admin.  Additionally, there is file contention if pdfcrop is part of a multithreaded build script.
- lwarp : calls pdftex, pdfcrop, pdfseparate, pdfcairo, pdftotext, lualatex, makeindex etc all without --miktex-admin flag.  Result is that there can be hundreds of warnings, errors, and file contention during the build.  Calls may fail entirely if they invoke initexmf.
- Various other miktex tools and plugins have the same behavior.

**My request:**
Do something like add option to miktex.ini that automatically adds --miktex-admin to all miktex program calls without user specification on the command line.

Thanks for the consideration!

**Comment by burgealex** [comment]
One other thing to take a look at as part of this is pdftex->initexmf->miktex-makefmt.  ( see attached file )

[logfile.txt](https://github.com/MiKTeX/miktex/files/2511610/logfile.txt)

I would expect adding a flag would fix the warning and most likely the error.  It seems like initexmf might be passing down the wrong admin flag to miktex-makefmt.  ( I'm not an expert though so I'm not sure )

Thanks again for taking a look!

**Comment by edocevoli** [comment]
It seems that `miktex-makefmt` is not passing the `--miktex-admin` option to `miktex-pdftex`. This is a bug.

**Comment by edocevoli** [comment]
There is a new configuration value which allows to turn on the auto-admin feature:

```
[Core]       
;; Automatically turn on administrator mode for elevated MiKTeX programs
;; in a shared setup.
AutoAdmin = ?
```

You can run

```
initexmf --set-config-value [Core]AutoAdmin=t
```

to set the configuration value.

**Comment by edocevoli** [comment]
No, there will be no installer for this version.
