### ISSUE TITLE
Fonts not rendered in inbuilt TeXworks PDF viewer

### ISSUE THREAD

**Issue by RuixiZhang42** [MiKTeX/miktex#214]
Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

**The following is copied and pasted from my original question on TeX.SX: [Fandol fonts not rendered in TeXworks PDF viewer](https://tex.stackexchange.com/q/456764)**. This issue had been reproduced by KJO who also provided an answer. KJO pointed out that a different Qt version is used, causing the problem.

---

I&nbsp;am using TeXworks bundled in the MiKTeX distribution and the [Fan­dol Simplified Chinese font family](https://ctan.org/pkg/fandol) (available in TeX Live and MiKTeX). However, the Fan­dol font is not rendered in the TeXworks PDF viewer.

[![TeXworks][1]][1]

My OS is Windows&nbsp;8 and the newest(-ish) version of `poppler-data` is present:

[![poppler][2]][2]

On the other hand, Adobe Acrobat Reader DC *is* able to render the generated PDF file.

[![adobe][3]][3]

Here is the `FandolTest.tex` file MWE:

    % !TeX program = XeLaTeX
    \documentclass{article}
    \usepackage{fontspec}
    \setmainfont{FandolSong-Regular}
    \begin{document}
    \textsf{English} English 中文 English \textsf{English}
    \end{document}

  [1]: https://i.stack.imgur.com/6V03y.png
  [2]: https://i.stack.imgur.com/Mz3J9.png
  [3]: https://i.stack.imgur.com/OFpGU.png

**Comment by edocevoli** [comment]
Please attach the PDF file.

**Comment by RuixiZhang42** [comment]
@edocevoli Thank you for the response! Here is the generated PDF file:
[FandolTest.pdf](https://github.com/MiKTeX/miktex/files/2522218/FandolTest.pdf)

It is worth mentioning that when viewing this file on the PDF viewer from the [portable release of TeXworks&nbsp;0.6.2](https://github.com/TeXworks/texworks/releases) the font is also rendered correctly.

**Comment by ivankokan** [comment]
All fonts are embedded in PDF, so this was a viewer issue.
![image](https://user-images.githubusercontent.com/1058211/93687285-e8844680-fabc-11ea-92a0-0d4847545297.png)
