### ISSUE TITLE
Warwick exe Mirror SSL cert not supported

### ISSUE THREAD

**Issue by LittleJohnD** [MiKTeX/miktex#215]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [X ] I am reporting a bug others will be able to reproduce
- [N/A] I have installed the latest MiKTeX updates
- [N/A] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions
2. input files which are necessary to reproduce the bug
3. your observations (command output, screenshots, ...)
4. relevant log file snippets

While not a software bug this seemed the most appropriate place to put it.

The hosting the mirror within Warick Uni at ![Mirrorsite](anorien.csc.warwick.ac.uk) is using a certificate that is not supported by chrome.

![image](https://user-images.githubusercontent.com/1190193/47988639-ade8af00-e0da-11e8-86aa-3f6abf4c4475.png)

**Comment by edocevoli** [comment]
Thank you for the info. Please choose another mirror.
