### ISSUE TITLE
Miktex console no longer runs as administrator after an update

### ISSUE THREAD

**Issue by paultjevdh** [MiKTeX/miktex#216]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

Hi,
As described in issue 128, I had a problem to run miktex console as administrator. Now that this issue is fixed, I would like this to be persistent, however after each update, no matter which minor package, the menu shortcut has lost the 'run as administrator property'. I consider this a bug and not a feature request since an existing feature (detect run as administrator, see issue 128) stops working after an update of something not directly related.

Step-by-step:
- set the menu shortcut for miktex console to run as administrator (select open file location from the context menu and then access the shortcut properties from windows explorer.
- run miktex console from the start menu. You should get a UAC dialog.
- check for updates, this now requires no "restart as administrator" since we're already running as administrator.
- if no updates are available, wait a few days until they are
- When updates are available, apply them. 
- close and restrt miktex console. 
- now you get no UAC dialog and you have to restart miktex console as administrator to be able to check for updates.

Desired behaviour: after an update rus as administrator property should be preserved (possible exception: update of the console itself)
Another fix could be to have the updater/installer to set the shortcut property to run as administrator by default. 
Best regards,
Paul

**Comment by edocevoli** [comment]
Please

- create installation report (`Diagnose` / `Open in text editor...`)
- attach all log files

The ticket will be reopened when the info is available.

**Comment by paultjevdh** [comment]
Hi
Today it happened again, see screenshot for installed packages:

![image](https://user-images.githubusercontent.com/21358521/48052864-6ed55f00-e1a9-11e8-8407-5c7733d1e43b.png)
After installation, console starts as below:
![image](https://user-images.githubusercontent.com/21358521/48053152-4306a900-e1aa-11e8-9e47-52716d54e5e9.png)
So run as administrator is inactive again, as demonstrated in the screenshot below
![image](https://user-images.githubusercontent.com/21358521/48053237-7c3f1900-e1aa-11e8-9fff-381d95ad4a97.png)

Installation report: [miktex-report.txt](https://github.com/MiKTeX/miktex/files/2552280/miktex-report.txt)

All log files: [log.zip](https://github.com/MiKTeX/miktex/files/2552291/log.zip)

Best regards,
Paul
