### ISSUE TITLE
Network setting edition not updated after an issue

### ISSUE THREAD

**Issue by suzizecat** [MiKTeX/miktex#218]
Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

# Reproducing

This was done on a fresh install under Windows 7, using `basic-miktex-2.9.6850-x64.exe` in user-only mode (no admin).
However, I think that it should work just as the same if you don't have any proxy setup.

1. Open MiKTeX Console (non-admin)
2. In "Updates" or "Parckage" click on the "Change" button (to change the location of the update repo)
3. Go in "Connection Settings"
4.Select "Use a Proxy" and input something which *won't* work (add : at the end of the adress, or forgot to select authentication if required)
5. Validate your input and go next.
6. Discard any error message, you should not see any server (which is normal)
7. Go back with the arrow at the top left corner.
8. Fix your settings
9. Go next.

You should still not be able to see any server.
However, if you use the exact same (good) settings from the start, everything will work as expected.
To see any server, you need to cancel the wizard, and go from step 2. without making mistakes in your settings.

Best regards,
Julien FAUCHER

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
