### ISSUE TITLE
miktex is noticably slower than texlive

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#22]
Since some time I noticed a pause when miktex reads expl3-code.tex and now made some measurement. with `Measure-Command {pdflatex test-utf8}` in a powershell. 

test-utf8 is this document:

~~~~~
\listfiles
\documentclass{article}
\usepackage{expl3}
\begin{document}
abc
\end{document}
~~~~~

The results are around 1.2 seconds with texlive 2017 and 3.4 seconds with miktex.  I also compared a rather longish and complex lualatex document and the numbers are similar: 30 seconds with texlive, 75-80 with miktex. 

I didn't check yet with a process monitor for clues, but in a trace I saw that miktex is looking for every file twice in all the fndb. 

I made the test on a current windows 10. The miktex is up-to-date (normal, not next). It is not a complete installation and on-the-fly is active (deactivating it didn't change the time). I do have quite a number of local roots but these are active for both tex systems. 

The measurements were triggered by a question on tex.sx which mentioned the slow loading of expl3-code.tex: https://tex.stackexchange.com/questions/396838/while-compiling-expl3-code-tex-takes-more-time-than-the-others

**Comment by edocevoli** [comment]
I cannot see a big difference:

```
PS C:\Trash> Measure-Command {pdflatex test-utf8.tex}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 850
Ticks             : 8505037
TotalDays         : 9.84379282407407E-06
TotalHours        : 0.000236251027777778
TotalMinutes      : 0.0141750616666667
TotalSeconds      : 0.8505037
TotalMilliseconds : 850.5037
```

versus

```
PS C:\Trash> Measure-Command {C:\texlive\2017\bin\win32\pdflatex.exe test-utf8.tex}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 880
Ticks             : 8807255
TotalDays         : 1.01935821759259E-05
TotalHours        : 0.000244645972222222
TotalMinutes      : 0.0146787583333333
TotalSeconds      : 0.8807255
TotalMilliseconds : 880.7255
```

**Comment by u-fischer** [comment]
I now tried with miktex next and also remove all my additional roots and the difference is still there. I looked a bit with the process monitor at the events. One obvious difference is that miktex runs over 2000 registry queries (RegOpen/RegQuery/RegClose) while in texlive I see only 250. Could this be the bottleneck in my system?

**Comment by edocevoli** [comment]
Can you see what registry keys are queried?

**Comment by u-fischer** [comment]
Sure I could export the events and sent them. There a quite a lot of this type:

~~~~
20:33:16,9011687	pdflatex.exe	10352	RegOpenKey	HKU\S-1-5-21-1301275454-2604396161-3022068263-1004\Software\MiKTeX.org\MiKTeX\2.9\Core.FileTypes.fmt	NAME NOT FOUND	Desired Access: Read
~~~~

The ending of the path varies but they always comes in bunches, e.g. around 20 `Core.FileTypes.fmt` and then `Core.FileTypes.tfm` and then `Core.FileTypes.vf`. 

But after looking at the times I have some doubt that here is the problem.  Actually it looks as if the actual reading of files like e.g. expl3-code.tex is slower. I copied the file to the current folder so that both access the same file but nevertheless texlive seems to load it twice as fast. 

Btw: I forgot: this is still a 32-bit miktex (I never had to reinstall miktex in all the years ...). But imho texlive is 32 bit too.

**Comment by edocevoli** [comment]
If file reading is the bottleneck: MiKTeX uses thread-safe read operations. Thread-safe reads are slower than their non-thread-safe counterparts.

@a-kakuto: it would be interesting to learn if TeX Live uses single-threaded reads (e.g., `_getc_nolock` instead of classic `getc`). In this case I would switch to single-threaded reads as well. Thank you!

**Comment by a-kakuto** [comment]
Dear Christian,

> it would be interesting to learn if TeX Live uses
> single-threaded reads (e.g., _getc_nolock instead
> of classic getc).

I'm using classic getc. In the old days, I was using very
old compiler. The resulting binaries were small and fast.
I'm not using MiKTeX, but I believe that the recent TeX Live
binaries on Windows are comparable with those in MiKTeX
in speed, and they are not noticeably faster than MiKTeX.

Thank you,
Akira

**Comment by u-fischer** [comment]
I made a few tests with pdftex and also with dvi mode:

~~~
\newcount\X
\X=10000

blub
\loop
%\input A      %Test 1
blbl\endgraf  %Test 3 
\advance \X by -1
\unless\ifnum \X<0
\repeat
\bye

% Inputs of A (empty file, only \endinput)

% 1000   TL   1.1 Mik  2.8
% 10000  TL   3   Mik  6
% 100000 TL 140   Mik 80

% Inputs of A (one paragraph) 

% 1000   TL   1.2 Mik  2.8    dvi: TL 0.8   Mik: 0.75
% 10000  TL   3.5 Mik  6.9    dvi: TL 3.2   Mik: 5
% 100000 TL 120   Mik 79      dvi: TL 177   Mik: 104


% Empty loop

% 1000     TL 1   Mik 2.2    dvi: TL 0.68  Mik: 0.32
% 10000    TL 1   Mik 2.2
% 100000   TL 1.1 Mik 2.3
% 1000000  TL 1.8 Mik 2.7
% 10000000 TL 8.9 Mik 7

% paragraphs

% 1000     TL 1   Mik 2.2   
% 10000    TL 1.1 Mik 2.3   dvi: TL 0.8    Mik:0.32
% 100000   TL 1.8 Mik 3
% 1000000  TL 9   Mik 7
~~~

As one can see in dvi mode there is no problem. Miktex is even quite often faster. This is also the case with my starting latex example: The times are then TL0.8, Mik 1.2. I will try to get some times from other miktex users. And perhaps I will install a 64bit version to compare with this too.

**Comment by a-kakuto** [comment]
Dear Ulrike,

> And perhaps I will install a 64bit version to
> compare with this too.

64bit binaries for TeX Live are in
CTAN/systems/win32/w32tex/TLW64/
They are not tested well.
Please read 00README.TLW64 carefully.
I expect that speed is comparable with MiKTeX 64bit:
Sometimes slower or sometimes faster.

Thanks,
Akira

**Comment by edocevoli** [comment]
I was able to reproduce the performance issue and I feel confident that I can widen the bottleneck.

You were right: it isn't the file reading. But when `expl3-code.tex ` is loaded, a lot of memory allocations happen and there was an issue which I have fixed with commit #65b259b.

**Comment by u-fischer** [comment]
Ah. memory allocation sounds like the right track. I just came across this example of a loop where the compilation time drops by 5 seconds if one enlarges the definitions text:

~~~~
\newcount\X
\X=100000

blub
\loop
%\expandafter\def\csname test_xxx\the\X_tl\endcsname{bbbl} %7.5sec
\expandafter\def\csname test_xxx\the\X_tl\endcsname{bbblbbbbbbbbbbbbbbbbbbbbb bbbbbbbbbbbb}% 2.2 sec
\advance \X by -1
\unless\ifnum \X<0
\repeat
\bye
~~~~

Texlive isn't very fast for this example (6.2 seconds) but it takes the same time for both variants.

**Comment by edocevoli** [comment]
Testing with the latest LuaTeX (MiKTeX 2.9.6500): I have measured command execution times of your last test file(s). There is no significant drop/increase.
