### ISSUE TITLE
MikTex TexWorks on Mac not displaying any text. 

### ISSUE THREAD

**Issue by twadepsvita** [MiKTeX/miktex#220]
Please fill out one of the templates on: https://github.com/MiKTeX/miktex/issues/new/choose

**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [ x] I am reporting a bug others will be able to reproduce
- [ x] I have installed the latest MiKTeX updates
- [ x] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions

I installed MixTex using the dmg on the website.

I installed all plugins.

I opened TexWorks and started typing.

I tried installing a clean copy of MikTex, even though the copy I was using was installed yesterday, but the issue remained.

2. input files which are necessary to reproduce the bug

I haven't got any files, but here are the log file details.

MiKTeX: 2.9
OS: Darwin 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
SharedSetup: no
PathOkay: no
SystemAdmin: no
RootPrivileges: no
Root0: /Users/thomas/Library/Application Support/MiKTeX/texmfs/config
Root1: /Users/thomas/Library/Application Support/MiKTeX/texmfs/data
Root2: /Users/thomas/Library/Application Support/MiKTeX/texmfs/install
Root3: /Library/Application Support/MiKTeX/texmfs/config
Root4: /Library/Application Support/MiKTeX/texmfs/data
Root5: /Library/Application Support/MiKTeX/texmfs/install
UserInstall: /Users/thomas/Library/Application Support/MiKTeX/texmfs/install
UserConfig: /Users/thomas/Library/Application Support/MiKTeX/texmfs/config
UserData: /Users/thomas/Library/Application Support/MiKTeX/texmfs/data
CommonInstall: /Library/Application Support/MiKTeX/texmfs/install
CommonConfig: /Library/Application Support/MiKTeX/texmfs/config
CommonData: /Library/Application Support/MiKTeX/texmfs/data

3. your observations (command output, screenshots, ...)

Here is a video of the issue in action.

https://youtu.be/0kPNjwEidI0

4. relevant log file snippets

I have posted them above.

**Comment by twadepsvita** [comment]
I've just down some quick checking and it appears to work if I open TexWorks whilst my Mac is in Light mode, but it repeats the issue if I open TexWorks in Dark Mode.

**Comment by edocevoli** [comment]
Thank you for the report. This has been fixed now.
