### ISSUE TITLE
Running MiKTeX commands in parallel fails

### ISSUE THREAD

**Issue by Sharken03** [MiKTeX/miktex#222]
Checklist:
- [X] I am reporting a bug others will be able to reproduce
- [X] I have installed the latest MiKTeX updates
- [X] I have checked the MiKTeX log files

**Step-by-step reproduction instructions**
On a Windows machine do the following:
Create a minimal temp.tex file.
Install DbgView and start DbgView.
Set trace flags like this: setx MIKTEX_TRACE "access,core,mmap"
Run texify.exe:
texify.exe --batch --pdf --tex-option=-halt-on-error temp.tex 

DbgView will now show something like this:
![dbgviewoutput](https://user-images.githubusercontent.com/37798154/48781675-c365f780-ecdc-11e8-8590-4a15fcef42e7.png)

Running multiple instances of Texify.exe will eventually lead to an access denied error like this:
[Errorlog.txt](https://github.com/MiKTeX/miktex/files/2600246/Errorlog.txt)

The root cause seem to be that MiKTeX by default writes to a common file, and having more than one instance of Texify.exe doing this will lead to an error.

A workaround is to mark the Data folder as read-only, which the code in winMemoryMappedFile.cpp will respect.
It would be a lot better if the design was changed, so that multiple instances of MiKTeX commands can be run.

**Comment by edocevoli** [comment]
I think this is has been fixed with one the latest updates.
