### ISSUE TITLE
Error occurs duing first update after installation (repeated).

### ISSUE THREAD

**Issue by elfsoft2000** [MiKTeX/miktex#224]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [ ] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions
2. input files which are necessary to reproduce the bug
3. your observations (command output, screenshots, ...)
4. relevant log file snippets

**Comment by elfsoft2000** [comment]
Windows API error 127: The specified procedure could not be found.

dllName="C:\Program Files (x86)\MiKTeX 2.9\miktex/bin\MiKTeX209-core.dll"

MiKTeX: 2.9
OS: Windows 7 Home Premium, 64-bit, Service Pack 1, build 7601
SharedSetup: yes
PathOkay: yes
SystemAdmin: yes
RootPrivileges: yes
Root0: C:\Users\John\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\John\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files (x86)\MiKTeX 2.9
UserInstall: C:\Users\John\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\John\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\John\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files (x86)\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: explorer

**Comment by elfsoft2000** [comment]
The error was generated by the console.  MikTeX itself behaves oddly, either giving "missing .idx file" errors on no errors and no output.

**Comment by edocevoli** [comment]
Seems that you have a mix of old/new MiKTeX installations. Removing all MiKTeX traces from your system and then installing the latest version should work

**Comment by elfsoft2000** [comment]
After searching the registry for pathnames using MiKTeX I found an entry using Program Files (x86) which I modified.  Now the error message reads

Windows API error 127: The specified procedure could not be found.

dllName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core.dll"

MiKTeX: 2.9
OS: Windows 7 Home Premium, 64-bit, Service Pack 1, build 7601
SharedSetup: yes
PathOkay: yes
SystemAdmin: yes
RootPrivileges: yes
Root0: C:\Users\John\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\John\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\John\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\John\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\John\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: cmd

**Comment by elfsoft2000** [comment]
Do you think it could be due to the foreward slashes instead of backslashes?

**Comment by elfsoft2000** [comment]
Using windows explorer I verified that C:\Program Files\MiKTeX 2.9\miktex\bin\x64\MiKTeX209-core.dll does exist.  I searched the registry for /bin/ and found nothing.
