### ISSUE TITLE
Console uninstall does not remove everything

### ISSUE THREAD

**Issue by elfsoft2000** [MiKTeX/miktex#225]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [ ] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions
2. input files which are necessary to reproduce the bug
3. your observations (command output, screenshots, ...)
4. relevant log file snippets

**Comment by elfsoft2000** [comment]
In my previous bug report, I was told that I had a mixture of old and new installs.  So I ran MikTeX console uninstall (again), deleted the MikTeX folders, (again). ran the install (again) and got the same error.  So how does one remove all traces of previous installations?

Windows API error 127: The specified procedure could not be found.

dllName="C:\Program Files (x86)\MiKTeX 2.9\miktex/bin\MiKTeX209-core.dll"

MiKTeX: 2.9
OS: Windows 7 Home Premium, 64-bit, Service Pack 1, build 7601
SharedSetup: yes
PathOkay: yes
SystemAdmin: yes
RootPrivileges: yes
Root0: C:\Users\John\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\John\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files (x86)\MiKTeX 2.9
UserInstall: C:\Users\John\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\John\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\John\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files (x86)\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: explorer

There is no C:\Program Files (x86)\MiKTeX 2.9 folder.  Root3 should be C:\Program Files\MiKTeX 2.9 but I  don't know how to fix it.

**Comment by edocevoli** [comment]
You have to remove MiKTeX by hand:

```
rmdir /S /Q "C:\Users\John\AppData\Roaming\MiKTeX\2.9"
rmdir /S /Q "C:\Users\John\AppData\Local\MiKTeX\2.9"
rmdir /S /Q "C:\ProgramData\MiKTeX\2.9"
rmdir /S /Q "C:\Program Files (x86)\MiKTeX 2.9"
```

You also have to delete the registry keys:

- `HKEY_LOCAL_MACHINE\SOFTWARE\MiKTeX.org\MiKTeX\2.9`
- `HKEY_CURRENT_USER\Software\MiKTeX.org\MiKTeX\2.9`

**Comment by elfsoft2000** [comment]
I ran uninstall first to see what was being removed automatically.  All the folders except "C:\Program Files\MiKTeX 2.9" were already gone, and (using regedit) I couldn't find the registry keys to be deleted (or anything involving MikTeX).  I got as far as HKEY_LOCAL_MACHINE\SOFTWARE\ and HKEY_CURRENT_USER\Software\\.

**Comment by elfsoft2000** [comment]
Using the "Find..." facility of regedit I did find three registry keys using MikTeX (under Classes).  Going to try to reinstall now.

**Comment by elfsoft2000** [comment]
Nope.  Same error.

**Comment by elfsoft2000** [comment]
I searched the registry for every pathname including MikTeX and found nothing involving Program Files (x86).

**Comment by veromies** [comment]
I am having the same problem:
1. Uninstallation done as per  edocevoli's instructions.
2. A fresh installation (v 2.9.6850-x64) without errors.
3. 96 updates found.
4. Update (in the console) proceeds to give "Update in progress... we're almost done" gives an error message:
miktex-console.exe - Entry Point Not Found
(x) The procedure entry point
?Start@StopWatch@Trace@MiKTeX@@SA?AV?$unique_ptr@VStopWatch@Trace@MiKTeX@@U?$default_delete@VStopWatch@Trace@MiKTeX@@@std@@@@@PEAVTraceStream@23@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@5@1@Z could not be located in the dynamic link library MiKTeX209-trace.dll. 
5. The console gives an error report with the details:

Windows API error 127: The specified procedure could not be found.

dllName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core.dll"

6. I try to uninstall, getting a similar Entry Point Not Found error.
7. The console claims (incorrectly) uninstallation as succesful.

Diagnose-report:
MiKTeX: 2.9
OS: Windows 7 Home Premium, 64-bit, Service Pack 1, build 7601
SharedSetup: yes
PathOkay: yes
SystemAdmin: yes
RootPrivileges: yes
Root0: C:\Users\vero\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\vero\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\vero\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\vero\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\vero\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by elfsoft2000** [comment]
You can always just delete the  " C:\Program Files\MiKTeX 2.9" folder and reinstall, but that is (probably) how I wound up with bad registry keys.  BTW, I don't think they pay any attention to "Closed" reports.

**Comment by veromies** [comment]
Good to know, elfsoft2000.

I found some help and workarounds from issue 187: https://github.com/MiKTeX/miktex/issues/187. For me, installing only for me and using some commands after error messages helped.
