### ISSUE TITLE
xetex does not look for local user's font folder

### ISSUE THREAD

**Issue by kia999** [MiKTeX/miktex#226]
Most recent version of Windows 10 installs fonts to user's local font folder (in my case: C:\Users\KIA\AppData\Local\Microsoft\Windows\Fonts) but xelatex does not find fonts in this folder. I bypassed this problem manually by moving installed fonts from C:\Users\KIA\AppData\Local\Microsoft\Windows\Fonts to C:\Windows\fonts.

**Comment by edocevoli** [comment]
This has been fixed.
