### ISSUE TITLE
Download fails with a network error

### ISSUE THREAD

**Issue by Boomvang** [MiKTeX/miktex#227]
Download fails with a network error
Hello, I'm trying to download MiKteK for Windows. It seems to get a megabyte or so (different amounts each time) and then fails with a network error.
I have tried with my computer on two different networks (University, home) and also with another computer on the home network.

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.
You can try it again tomorrow. If the problem still exists: collect log files, screenshots etc.
Please read the guidelines:
https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md

Reminder: **Your job is to enable me to reproduce the problem.**
