### ISSUE TITLE
Windows 7 console using /bin/ instead of \bin\

### ISSUE THREAD

**Issue by elfsoft2000** [MiKTeX/miktex#228]
**Please note: we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide all the required information.**

Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

Please replace this section with the required information:
1. step-by-step reproduction instructions
2. input files which are necessary to reproduce the bug
3. your observations (command output, screenshots, ...)
4. relevant log file snippets

**Comment by elfsoft2000** [comment]
If you check your other bug reports you will find several issues involving this problem.

**Comment by edocevoli** [comment]
Thank you. We will take care of this.
