### ISSUE TITLE
Modern cv template not working on miktex.

### ISSUE THREAD

**Issue by ay111** [MiKTeX/miktex#229]
Please fill out one of the templates on: https://github.com/MiKTeX/miktex/issues/new/choose
I contacted texstudio page, they the issue is with miktex installation. I hope to hear from you.
This is the message  I got after building modern cv template in texstudio:

Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "texstudio_cS9076".tex

Sorry, but miktex-makemf did not succeed. The log file hopefully contains the information to get MiKTeX going again: C

:\Users\ADETONA\AppData\Local\MiKTeX\2.9\miktex\log\miktex-makem

f.log

Sorry, but miktex-makepk did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\ADETONA\AppData\Local\MiKTeX\2.9\miktex\log\miktex-makepk.log

Process exited with error(s)

Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "texstudio_cS9076".tex

Sorry, but miktex-makemf did not succeed. The log file hope

fully contains the information to get MiKTeX going again: C:\Users\ADETONA\AppData\Local\MiKTeX\2.9\miktex\log\miktex-makem

f.log

Sorry, but miktex-makepk did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\ADETONA\AppData\Local\MiKTeX\2.9\miktex\log\miktex-makepk.log

Process exited with error(s)

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.
You can try it again tomorrow. If the problem still exists: collect log files, screenshots etc.
Please read the guidelines:
https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md

Reminder: **Your job is to enable me to reproduce the problem.**
