### ISSUE TITLE
pdfcrop: The script could not be found. 

### ISSUE THREAD

**Issue by MaxKuh** [MiKTeX/miktex#23]
Same issue as "#2080 pdfcrop: The Perl script could not be found. " since last update of Miktex.

When calling pdfcrop.exe one get's the following error:
pdfcrop: The script could not be found.
pdfcrop: Data: ScriptEngine="perl", name="pdfcrop", path="scripts/pdfcrop/pdfcrop.pl"

Actually pdfcrop.pl is located in
scripts/pdfcrop/perl
whereas it is assumed to be in 
scripts/pdfcrop/
.

Everything worked fine before the last update.

**Comment by edocevoli** [comment]
Thank you. Please note that this issue tracker is for bugs which can be fixed in source code but not for packaging issues.
