### ISSUE TITLE
Make --file-line-error affect warnings

### ISSUE THREAD

**Issue by kbauer** [MiKTeX/miktex#230]
Currently, the option `--file-line-error` causes only errors to be printed in a c-style "file:line:message" format.

It would be useful for this behavior to be extended to
- Warnings (`\ClassWarning`, `\ClassWarningNoLine`, `\PackageWarning`, `\PackageWarningNoLine`, or the low-level `\@warning`).
- Overfull/underful hbox warnings (hardcoded?).

Fixing warnings can be an important step for fixing a document before final submission or printing. Editors like TeXstudio try to help with this, but for multi-file documents correctly locating the origin is hit-and-miss.

The `--file-line-error` flag has the potential of fixing this problem for errors, though its utility is currently hindered by #181. However, warnings are not affected at all right now.

Currently, TeX Live behaves the same in this respect. (Tested with `pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018/Cygwin)`). 

## MWE

Running `pdflatex --interaction=nonstopmode --file-line-error x.tex` on the file 

```
\documentclass[12pt]{article}
\usepackage[scale=0.9,a5paper]{geometry}
\begin{document}
Hello world.
\ThisIsNotAKnownCommand
$ This~is~some~seriously~overful~box. This~is~some~seriously~overful~box. This~is~some~seriously~overful~box. This~is~some~seriously~overful~box. This~is~some~seriously~overful~box.  $
\PackageWarning{Test}{Warning test text}
\end{document}
```

gives the console output (truncated to the relevant parts)

```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6800 64-bit)
entering extended mode
(x.tex
[...]
x.tex:5: Undefined control sequence

Package Test Warning: Warning test text on input line 7.

Overfull \hbox (622.4843pt too wide) in paragraph at lines 4--8
[]\OT1/cmr/m/n/12 Hello world. $\OML/cmm/m/it/12 This []is []some []seriously [
]overful []box:This []is []some []seriously []overful []box:This []is []some []
seriously []overful []box:This []is []some []seriously []overful []box:This []i
s []some []seriously []overful []box:$
[...]  )
[...]
```

**Comment by edocevoli** [comment]
I am afraid that high-level primitives like `\ClassWarning` cannot be handled at the TeX engine level. I would recommend that you post your request also to the TL mailing list.

**Comment by kbauer** [comment]
> I am afraid that high-level primitives like `\ClassWarning` cannot be handled at the TeX engine level. I would recommend that you post your request also to the TL mailing list.

What about box warnings? As far as I know, these are hardcoded and cannot be handled in any way on the scripting level, just like "undefined command sequence" errors cannot.
