### ISSUE TITLE
Miktex update error Version 2.9

### ISSUE THREAD

**Issue by ah1977** [MiKTeX/miktex#234]
Hello,

I have downloaded and updatet the actual binary miktex version on 20. december 2018. during a compile my document, a biber error was created. The version of biber and biblatex are not correspond within.
I wandted update my miktex installation, but a error was created. The programm could not found a "Procedure Einsprungpunkt". I searched on the net, and I think the problem was solved (I found a issure on August 2018) but today in december i have the same problem.
I don't found a update log file

**Comment by edocevoli** [comment]
Thank you, but it seems that this is not a MiKTeX issue, i.e., it works well with the minimal working example.
