### ISSUE TITLE
cannot install MikTex 2.9 on Windows 10 Pro N (64 bit)

### ISSUE THREAD

**Issue by olebu87** [MiKTeX/miktex#236]
Please fill out one of the templates on: https://github.com/MiKTeX/miktex/issues/new/choose
I had to uninstall MikTex, because it stopped working properly. Then I failed to install MikTex 2.9 on Windows 10 Pro N (64 bit). The message was: This app can't run on your PC. To find a version for your PC, check with the software publisher.

**Comment by edocevoli** [comment]
Thank you for the info.
