### ISSUE TITLE
Windows theme changed

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex#237]
Checklist:
- [x] I am reporting a bug others will be able to reproduce
- [x] I have installed the latest MiKTeX updates
- [x] I have checked the MiKTeX log files

After I installed the last batch of updates (only containing `miktex-qt5-bin-x64` on my machine) two days ago all MikTeX-related programmes show up in a Windows-98-like classic theme (cf. https://de.wikipedia.org/wiki/Datei:Windows_98_Second_Edition_deutscher_Screenshot.tif), while earlier the theme was different (cf. https://miktex.org/howto/miktex-console).

I'm running a fully updated MikTeX 2.9 x64 (as of this morning) on Windows 10 (1803).

The steps to reproduce are simple: Open up any MikTeX programme (TeXworks, the Console, ...) and see the Win 98 look.

Below is a screenshot of my MikTeX Console window taken this morning

![classictheme](https://user-images.githubusercontent.com/6755835/50507132-6e0bcb80-0a7c-11e9-84a9-ad60aa89c892.png)

a screenshot of my MikTeX Console from a while ago can be found in https://tex.stackexchange.com/a/55473/35864, I just reproduce one image here

![earlier console screenshot](https://i.stack.imgur.com/GMTbE.png)

I am not aware of any changes to the theme of programmes other than MikTeX-related ones on my machine and I am not aware of consciously modifying any theme settings.

If possible I would like to get the old theme back. Of course an option to switch between the themes would also be a lovely feature.

The MikTeX log files don't seem to contain anything interesting on a first inspection, but I'm happy to upload files of interest if need be.

**Comment by edocevoli** [comment]
This seems to be a system-specific issue. On my workstation (Windows 10 Pro) the UI is OK.
Do you have Qt5 installed in other places?

**Comment by Jimvy** [comment]
Hello,
I'm also experiencing this "issue". After installing MiKTeX (just 40 minutes ago, from the `basic-miktex-2.9.6850-x64.exe` installer, W10 Home 1809 freshly reinstalled), the UI was fine, modern-looking (as in the second screenshot of @moewew ) and the Console suggested installing packages updates. After updating and after restarting the MiKTeX Console, the Windows 98 style showed up.
The package repository used was "a randomly chosen" package repository, and of course the system won't allow me to update again.

**Comment by moewew** [comment]
Great. Looking forward to testing that.

In the meantime I did some digging on my system.

The last Windows update was 2018-12-21 way before the new behaviour emerged, so I'm excluding that as an issue.

I do have several qt5 `.dll`s on my system (in the MS OneDrive directory and for Wireshark, LyX, RStudio, ...) but all of these have change dates from days if not weeks or months before the issue appeared. Their last date of access as reported by Windows in the file properties dialogue is also from before the issue appeared. On the other hand the `qt5Core.dll` from MikTeX shows recent access. My system is set up with the MikTeX directories at the beginning of PATH, so that `where qt5Core.dll` points to the MikTeX version.

**Comment by moewew** [comment]
This morning's update restored the old look. Thank you.
