### ISSUE TITLE
Installation and update fails with Windows API error 127 ("/" instead of "\"?)

### ISSUE THREAD

**Issue by matzl** [MiKTeX/miktex#238]
When installing MiKTeX (32 or 64 bit) on Windows 7 (64 bit), after running the first update of packages, a windows API error 127 occurs (MiKTeX209-core.dll couldn't be called), probably because the path includes a Linux path separator "/" instead of a Windows path separator "\\".

Not sure about that but [this StackExchange Thread](https://tex.stackexchange.com/questions/460831/miktex-update-from-basic-install-2-9-6850-fails-with-fatal-error?newreg=69f00ec6b55b4745a9d907a4da2e60b1) suggests that this is a duplicate of [Issue #187](https://github.com/MiKTeX/miktex/issues/187) ?

Reproduction using Windows 7 Home Premium SP1 64 bit (most likely works with any Windows or at least Windows 7):
1. download the latest MiKTeX installer (2.9.6850 in my case as of 03.01.19)
2. run the installer, at the end let the update checkbox enabled
3. update runs and stops with an error:

> Windows API error 127: Die angegebene Prozedur wurde nicht gefunden.
> dllName="C:\Program Files (x86)\MiKTeX 2.9\miktex/bin\MiKTeX209-core.dll"

which in English is probably something like

> Windows API error 127: The specified procedure could not be found.
> dllName="C:\Program Files (x86)\MiKTeX 2.9\miktex/bin\MiKTeX209-core.dll"

Sorry, I didn't try the StackExchange workaround since in the meantime I decided to deinstall MiKTeX and use TeX Live or maybe even better Word (I'm having problems over problems for 3 hours now after using latex every now and then for 6 years).
Peace out.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by matzl** [comment]
I did? What point did I miss?

Am 3. Januar 2019 10:13:44 MEZ schrieb Christian Schenk <notifications@github.com>:

**Comment by edocevoli** [comment]
This ticket was closed because the issue is not reproducible.
Since no log files were provided (which a
