### ISSUE TITLE
64-bit MiKTeX Console Admin on Windows 10 exits without doing anything

### ISSUE THREAD

**Issue by AlanGillespie** [MiKTeX/miktex#239]
64-bit MiKTeX Console Admin on Windows 10 exits immediately without even displaying the UI.
I've tried reinstalling, but that doesn't seem to help.

A 32-bit user mode installation seems to be OK though. Can anyone suggest anything?

The log from the 64-bit version is below, although it probably won't be much help:

2019-01-04 13:53:53,495Z INFO  main - starting: MiKTeX Console 2.9.6941 (MiKTeX 2.9.6930 64-bit)
2019-01-04 13:54:01,045Z INFO  main - finishing with exit code 0

Thanks,
--Alan G.

**Comment by edocevoli** [comment]
- Have you tried to start the non-admin variant?
- Have you checked the other log files?

You can do live trace as follows:
1. download and start DbgView from Microsoft: [https://docs.microsoft.com/en-us/sysinternals/downloads/debugview](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview)
2. open a command-promt window as Administrator and enter these commands:
```
set MIKTEX_TRACE=error,config,process
miktex-console
```

**Comment by AlanGillespie** [comment]
The non-admin variant starts and happily displays a list of updates, with DbgView capturing the following:

[12872] [MiKTeX] INFO  main - starting: MiKTeX Console 2.9.6941 (MiKTeX 2.9.6930 64-bit) 
[12872] [MiKTeX] INFO  mainwindow - checking for updates... 
[12872] [MiKTeX] INFO  mainwindow - downloading https://anorien.csc.warwick.ac.uk/mirrors/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma... 
[12872] [MiKTeX] INFO  mainwindow - 0.99 MB, 13.88 Mbit/s 
[12872] [MiKTeX] INFO  mainwindow - updating package manifests (C:\Users\agillesp\AppData\Roaming\MiKTeX\2.9\miktex/config\package-manifests.ini)... 
[12872] [MiKTeX] INFO  mainwindow - installed 3383 package manifests 
[12872] [MiKTeX] INFO  mainwindow - visiting repository https://anorien.csc.warwick.ac.uk/mirrors/CTAN/systems/win32/miktex/tm/packages/... 
[12872] [MiKTeX] INFO  mainwindow - repository type: remote package repository 
[12872] [MiKTeX] INFO  mainwindow - loading package repository manifest... 
[12872] [MiKTeX] INFO  mainwindow - downloading https://anorien.csc.warwick.ac.uk/mirrors/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma... 
[12872] [MiKTeX] INFO  mainwindow - 0.18 MB, 12.89 Mbit/s 
[12872] [MiKTeX] INFO  mainwindow - package repository digest: eeb3e5e66406550a7902c80fd376b65b 
[12872] [MiKTeX] INFO  mainwindow - found 7 updates 
[12872] [MiKTeX] INFO  main - finishing with exit code 0 

The admin variant gives no more information that I had already:

[13096] [MiKTeX] INFO  main - starting: MiKTeX Console 2.9.6941 (MiKTeX 2.9.6930 64-bit) 
[13096] [MiKTeX] INFO  main - finishing with exit code 0 

All of this is exactly as contained in miktex-console.log, with no other log files produced.

Windows Event Viewer logs the following application error:

Error 04/01/2019 16:04:30 Application Error 1000  (100)

Log Name:      Application
Source:        Application Error
Date:          04/01/2019 16:04:30
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      agillesp.eu.qualcomm.com
Description:
Faulting application name: miktex-console_admin.exe, version: 2.9.6941.0, time stamp: 0x5c2cafab
Faulting module name: ucrtbase.dll, version: 10.0.17134.319, time stamp: 0x40b70dec
Exception code: 0xc00000fd
Fault offset: 0x00000000000082f0
Faulting process ID: 0x12ac
Faulting application start time: 0x01d4a4472c7f2b9b
Faulting application path: C:\Program Files\MiKTeX 2.9\miktex\bin\x64\miktex-console_admin.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report ID: c07bfe2b-528f-4095-9749-f9cac7ae1439
Faulting package full name: 
Faulting package-relative application ID:

**Comment by AlanGillespie** [comment]
Other MiKTeX components seem to work fine - I can edit and compile LaTeX documents for example.
I just can't update.

**Comment by edocevoli** [comment]
Thank you. Please note that you have posted `miktex-console.log` which his is the log file of the non-admin variant. Have you checked the admin log file? You should find it here:

```
C:\ProgramData\MiKTeX\2.9\miktex\log\miktex-console_admin.log
```

**Comment by edocevoli** [comment]
Please, can you provide the installation reports for the admin and non-admin variants. You can create them as follows:

Run `initexmf --report> nonadmin-report.txt` in a non-elevated command prompt window.

Run `initexmf --admin --report> admin-report.txt` in an elevated command prompt window.

**Comment by AlanGillespie** [comment]
The mpm command appears to have updated OK. Log files are attached in case they are useful.

[initexmf_admin.log](https://github.com/MiKTeX/miktex/files/2727691/initexmf_admin.log)
[miktex-fc-cache_admin.log](https://github.com/MiKTeX/miktex/files/2727692/miktex-fc-cache_admin.log)
[mkfntmap_admin.log](https://github.com/MiKTeX/miktex/files/2727693/mkfntmap_admin.log)
[mpmcli_admin.log](https://github.com/MiKTeX/miktex/files/2727694/mpmcli_admin.log)

The admin and nonadmin installation reports you asked for as also attached:

[admin-report.txt](https://github.com/MiKTeX/miktex/files/2727742/admin-report.txt)
[nonadmin-report.txt](https://github.com/MiKTeX/miktex/files/2727743/nonadmin-report.txt)

**Comment by PeterHeidrich** [comment]
Dear MikTex admins,
I simply wanted to share my experiences.  I have an up-to-date Windows 10 64-Bit system.  Until about Christmas updates using the windows miktex admin tool was fine.  Then, around Christmas, miktex-update did no longer start after the last update.  I un-installed Miktex completely.  I tried to re-install MikTeX, the last attempt with the installroutine from 4th January.  However ... the windows admin tool (miktex-config, miktex-update, etc) still do not start.  Hence I have no MikTeX running right now, because I could not configure the newly installed MikTeX installation.
Best regards, Peter.

**Comment by den43** [comment]
I have the same issue. How do I update via the command line in Windows to fix the issue?

**Comment by llvs** [comment]
I can also confirm the bug. Console starts in user mode, immediately exits (or rather does not show up at all) in admin mode.
Win10 v1803, Installed for all users, Changed install location to C:\MikTeX29

**Comment by edocevoli** [comment]
It is possible to directly start MiKTeX Console in admin mode:

```
miktex-console_admin.exe --admin
```

**Comment by llvs** [comment]
I know but this yields the same result. It does not open a window. Nothing happens apart from a short switch to a hourglass/donut mouse cursor. In the task manager it can be seen that WerFault.exe is also called very shortly.
The event management shows (German Windows):
```
Name der fehlerhaften Anwendung: miktex-console_admin.exe, Version: 2.9.6941.0, Zeitstempel: 0x5c2cafab
Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.17134.471, Zeitstempel: 0x7e614c22
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x0000000000019226
ID des fehlerhaften Prozesses: 0x1d38
Startzeit der fehlerhaften Anwendung: 0x01d4b94a3dd19625
Pfad der fehlerhaften Anwendung: C:\MiKTeX29\miktex\bin\x64\miktex-console_admin.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\ntdll.dll
Berichtskennung: f244c576-c88f-48ca-ad81-1e6756329f86
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

**Comment by edocevoli** [comment]
2.9.6941.0 is not the current version. I would recommend that you update your installation. Maybe this fixes the issue in your case.

**Comment by llvs** [comment]
OK, updated via mpm but still no joy. Interestingly the fault is not always at the same dll. Here I can show you three different culprits on three runs:

```
Name der fehlerhaften Anwendung: miktex-console_admin.exe, Version: 2.9.6968.0, Zeitstempel: 0x5c50b4a2
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.17134.319, Zeitstempel: 0x40b70dec
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x00000000000089f3
ID des fehlerhaften Prozesses: 0x2acc
Startzeit der fehlerhaften Anwendung: 0x01d4b952cb6fad10
Pfad der fehlerhaften Anwendung: C:\MiKTeX29\miktex\bin\x64\miktex-console_admin.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\ucrtbase.dll
Berichtskennung: 691a4211-d071-42d8-981c-fff972f4de9f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

```
Name der fehlerhaften Anwendung: miktex-console_admin.exe, Version: 2.9.6968.0, Zeitstempel: 0x5c50b4a2
Name des fehlerhaften Moduls: MSVCP140.dll, Version: 14.11.25325.0, Zeitstempel: 0x592738ac
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x0000000000035d04
ID des fehlerhaften Prozesses: 0x2700
Startzeit der fehlerhaften Anwendung: 0x01d4b952bb5dd847
Pfad der fehlerhaften Anwendung: C:\MiKTeX29\miktex\bin\x64\miktex-console_admin.exe
Pfad des fehlerhaften Moduls: C:\MiKTeX29\miktex\bin\x64\MSVCP140.dll
Berichtskennung: 4821d56a-b256-4e8e-9822-2cfee208152a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

```
Name der fehlerhaften Anwendung: miktex-console_admin.exe, Version: 2.9.6968.0, Zeitstempel: 0x5c50b4a2
Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.17134.471, Zeitstempel: 0x7e614c22
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x0000000000019dc1
ID des fehlerhaften Prozesses: 0x2de0
Startzeit der fehlerhaften Anwendung: 0x01d4b952b2d459e0
Pfad der fehlerhaften Anwendung: C:\MiKTeX29\miktex\bin\x64\miktex-console_admin.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\ntdll.dll
Berichtskennung: 25a3c25b-3ae1-4d8d-a6ee-9d7fa1d2270f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

**Comment by MB-MRM** [comment]
Hi all,
I updated from a quite old MikTeX yesterday. First off all, the start menu entries have not been changed to console, like other users also reported. This is not the problem.
However, I also have the issue with the console in admin mode not opening, and I installed MikTeX for all users...
However, the workaround above also does not work for me, there is also an error (from the log file the command line referred me to):
`2019-02-03 14:46:37,339+0100 FATAL mpmcli - Info: ="path="C:\ProgramData\MiKTeX\2.9\miktex/data/le\5c9c2effd97adbeacc8bf220bf73149c.fndb-5", modeString="wb""
2019-02-03 14:46:37,339+0100 FATAL mpmcli - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
2019-02-03 14:46:37,339+0100 FATAL mpmcli - Line: 551
2019-02-03 17:24:28,458+0100 INFO  mpmcli - starting: mpmcli 2.9.6888 (MiKTeX 2.9.6960 64-bit)
2019-02-03 17:24:28,459+0100 INFO  mpmcli - Operating on the shared (system-wide) MiKTeX setup
2019-02-03 17:24:51,558+0100 FATAL mpmcli - Windows API error 1224: Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar.`

I already tried to re-install MikTex, but same behaviour. Anyone any idea how I could get this running?

Thanks!

**Comment by stakvik** [comment]
Hi, I'm having a similar problem on Windows 8. Some time around mid January miktex-console stopped working.

I'm running the miktex-console.exe, but the GUI don't open (actually nothing happens at all).

I tried to reinstall miktex, but to no avail. 

My issue is that I need to set up an additional root to a local repository (for a few shared internal company latex packages). I'm pretty sure I can add the path through "miktexsetup", but I haven't gotten it to work yet. Any help on a workaround would be perfect.

What I've tried so far is this:
miktexsetup --user-roots="D:\Dropbox (CompanyName)\02 Library\Templates\Latex\Packages"
which returns "miktexsetup: Nothing to do?"

Are there any method to see what directories are added to the root?

I'm running MiKTeX Setup Utility 2.9.6942

Again, any help would be appreciated

**Comment by rstahn** [comment]
I experience the same crashes of the MikTex console in admin mode using the latest version with Windows 10 1803 (Enterprise):

    Name der fehlerhaften Anwendung: miktex-console_admin.exe, Version: 2.9.6972.0, Zeitstempel: 0x5c558176
    Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.17134.376, Zeitstempel: 0x60d78cf9
    Ausnahmecode: 0xc00000fd
    Fehleroffset: 0x0000000000012f28
    ID des fehlerhaften Prozesses: 0x2958
    Startzeit der fehlerhaften Anwendung: 0x01d4c2bd2eeb98d1
    Pfad der fehlerhaften Anwendung: C:\Program Files\MiKTeX 2.9\miktex\bin\x64\miktex-console_admin.exe
    Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\ntdll.dll
    Berichtskennung: 2fc1e4f0-d2e2-48bc-a08f-660cb696ee3a
    Vollständiger Name des fehlerhaften Pakets: 
    Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by Elektrik1** [comment]
Same crash here, already tried clean reinstall, various cases launching as admin - it simply does not show up. Error:
```
Faulting application name: miktex-console_admin.exe, version: 2.9.6972.0, time stamp: 0x5c558176
Faulting module name: ucrtbase.dll, version: 10.0.17763.1, time stamp: 0x309241e0
Exception code: 0xc00000fd
Fault offset: 0x000000000000a579
Faulting process id: 0x8
Faulting application start time: 0x01d4c325d353f755
Faulting application path: D:\MiKTeX 2.9\miktex\bin\x64\miktex-console_admin.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 73876092-c362-4032-8131-1749f04757dc
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by michelow** [comment]
Just installed the latest x64 version (2.9.6942) and am having the same issue. Does not matter whether I choose run as administrator when starting the MiKTeX Console from the (Win10 Enterprise) start menu, start it normally and then click Restart as Administrator from the console, or try running from the command line using miktex-console-admin.exe --admin. In all cases I get a brief spinning circle on my cursor and then nothing.

There is no file miktex-console_admin.log in the C:\ProgramData\MiKTeX\2.9\miktex\log directory - only the installation related logs that all show Exit Code 0's for the install.

I ran the initexmf command as Christian suggested and it showed the following:

Date: 2019-02-14 10:53:23
MiKTeX: 2.9.6960
OS: Windows 10 Enterprise, 64-bit, build 16299
SharedSetup: yes
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\MiKTeX
CommonInstall: C:\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

Warning: the following problems were detected:
  1: not yet checked for updates
  2: installation is not up-to-date

- - - - - - 
Here is what Event Viewer shows (Information event):
1337214775514606972
4
APPCRASH
Not available
0
miktex-console_admin.exe
2.9.6972.0
5c558176
ucrtbase.dll
10.0.16299.522
cb7c3790
c00000fd
000000000000e406

\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3910.tmp.dmp \?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3C9C.tmp.WERInternalMetadata.xml \?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3CAA.tmp.csv \?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3CCA.tmp.txt
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_miktex-console_a_ecbecb10f7a78e1d42f61c2f583715e54a4a8_5ec3f60d_119640b1

0
5121ae9a-beae-4d85-8427-397b2c3cc871
268435456
2b9978a6dbc5b836428ebdc0e2f3ad7c

**Comment by llvs** [comment]
Quick update: No changes with 6972: Can be MSVCP140.dll, ucrtbase.dll or ntdll.dll.
Path is C:\MiKTeX29\miktex\bin\x64\miktex-console_admin.exe
Network is a corporate network with proxy. I succeed only with mpm on the command line, setting the ALL_PROXY variable before I can update.

```
Name der fehlerhaften Anwendung: miktex-console_admin.exe, Version: 2.9.6972.0, Zeitstempel: 0x5c558176
Name des fehlerhaften Moduls: MSVCP140.dll, Version: 14.11.25325.0, Zeitstempel: 0x592738ac
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x00000000000176af
ID des fehlerhaften Prozesses: 0x1f10
Startzeit der fehlerhaften Anwendung: 0x01d4c904a5b48865
Pfad der fehlerhaften Anwendung: C:\MiKTeX29\miktex\bin\x64\miktex-console_admin.exe
Pfad des fehlerhaften Moduls: C:\MiKTeX29\miktex\bin\x64\MSVCP140.dll
Berichtskennung: 6cd0da12-7c8c-4bf1-b7f7-9374adfdcae1
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

```
Name der fehlerhaften Anwendung: miktex-console_admin.exe, Version: 2.9.6972.0, Zeitstempel: 0x5c558176
Name des fehlerhaften Moduls: ucrtbase.dll, Version: 10.0.17134.319, Zeitstempel: 0x40b70dec
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x00000000000089f3
ID des fehlerhaften Prozesses: 0x18a4
Startzeit der fehlerhaften Anwendung: 0x01d4c9048d551c1b
Pfad der fehlerhaften Anwendung: C:\MiKTeX29\miktex\bin\x64\miktex-console_admin.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\ucrtbase.dll
Berichtskennung: 71fe21d1-8097-47a2-8db8-b623249d5f5a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```
```
Name der fehlerhaften Anwendung: miktex-console.exe, Version: 2.9.6972.0, Zeitstempel: 0x5c5581a8
Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.17134.471, Zeitstempel: 0x7e614c22
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x0000000000019226
ID des fehlerhaften Prozesses: 0x1f1c
Startzeit der fehlerhaften Anwendung: 0x01d4c9048a30f4a0
Pfad der fehlerhaften Anwendung: C:\MiKTeX29\miktex\bin\x64\miktex-console.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\ntdll.dll
Berichtskennung: 57722b18-a4b7-4ae3-ba5a-946f001b0204
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

**Comment by DigNative** [comment]
I am experiencing exactly the same issue, but on Windows 7:

```
Faulting application name: miktex-console_admin.exe, version: 2.9.6972.0, time stamp: 0x5c558176
Faulting module name: ntdll.dll, version: 6.1.7601.24335, time stamp: 0x5c268115
Exception code: 0xc00000fd
Fault offset: 0x00000000000d30a5
Faulting process id: 0x19b8
Faulting application start time: 0x01d4c9ced0c27309
Faulting application path: C:\apps\MiKTeX-2.9\miktex\bin\x64\miktex-console_admin.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 0ef30a99-35c2-11e9-87c8-005056c00008
```

**Comment by llvs** [comment]
My gut feeling is that it has to do with the non-standard install path posing problems for necessary admin rights.

**Comment by DigNative** [comment]
I have multiple systems all with the install path at `C:\apps\MiKTeX-2.9`. For some of them the MiKTeX Console works in admin mode, for some of them not.

**Comment by wref** [comment]
I've hit this issue with multiple computers no, all with a standard installation path. Today I noticed that with a default install on a Windows 10 computer I could launch the MiKTeX Console in Admin mode, but only when logged in as a local account. With a domain account it failed.

As a test I created a non-admin local account, ran MiKTeX Console, chose to go to Admin mode, and when asked to authenticate as a administrator tried both a local administrator and a domain administrator. In both cases it worked, so it seems in my case it was not the authentication process per se but who was logged in. I don't know if that's any help!

**Comment by llvs** [comment]
Interesting. Here, it is also a domain account which however has local admin privileges.
Could the others observing that behaviour please share, whether they have a domain account or not.

**Comment by MB-MRM** [comment]
I can confirm that I also encounter this issue with a domain account with local admin privileges.

Can anyone tell my why my comment above (24h ago) has been deleted by MikTex?

**Comment by istvank** [comment]
I also confirm that I have the issue with a domain account with local admin privileges.

@MB-MRM I subscribed to emails about this thread and can't find any comment from you from 24h ago in my emails.

**Comment by MB-MRM** [comment]
Sorry, this was a typo. I meant 24 days ago. I corrected the comment.

**Comment by edocevoli** [comment]
Thank you all. I cannot  reproduce the bug at the moment but I will add more logging to the relevant code parts, i.e., the next release update (in April) may give better diagnostics. I will reopen the ticket then (or maybe its't better to create a new one).

**Comment by edocevoli** [comment]
MiKTeX Console now logs more message to the DebugView log. So please:

1. Update MiKTeX: `mpm --admin --update`
2. Start [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview)
3. Make sure that option `Win32 PIDs` is enabled (checked)
4. Start MiKTeX Console and switch to admin mode
5. If MiKTeX Console crashes again, save the DebugView log to a file `File | Save as...`

Please: only comment here if you can make new information (e.g., a DebugView log) available. "Me too" comments make it hard too find significant information.

**Comment by istvank** [comment]
I don't know if this is the kind of message you wanna hear (no "me too", though!) but the issue is resolved for me now. No more crash. Thank you!

**Comment by llvs** [comment]
Same here, switch to admin mode works now. Thank you!

**Comment by stakvik** [comment]
I seem to have the same issues as before. I added two log files, one when I run "miktex-console.exe" and one where I run "miktex-console-admin.exe". 

Note that I have installed miktex on my local user, not as an admin. 

I hope the log files can help solve the problem. Personally, I find it very frustrating not to be able to open mixtex console.

[miktex_error_log_admin.LOG](https://github.com/MiKTeX/miktex/files/3007028/miktex_error_log_admin.LOG)
[miktex_error_log.LOG](https://github.com/MiKTeX/miktex/files/3007029/miktex_error_log.LOG)

**Comment by pfedan** [comment]
After `mpm --admin --update`, switching to admin mode works here too (as a domain user).

**Comment by edocevoli** [comment]
@stakvik, thank you. I think the latest version (2019-04-02) finally fixes your issue.

**Comment by stakvik** [comment]
@edocevoli, Thank you! You are right, now it works!
