### ISSUE TITLE
Build on Raspberry Pi 3 B+ FAILED !

### ISSUE THREAD

**Issue by zhaowei19920524** [MiKTeX/miktex#240]
Situation:
- Hardware: Raspberry Pi 3 Model B+ (1.4GHz 64-bit quad-core ARMv8 CPU (BCM2837B0))
- Operate System: Raspbian Stretch

`uname -a`
Linux zhaowei-RPi3BPlus 4.14.90-v7+ #1183 SMP Fri Dec 21 14:03:50 GMT 2018 armv7l GNU/Linux

- Software:

gcc:
`gcc -v`
"
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8.2.0/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: /home/pi/Downloads/objdir/../gcc-8.2.0/configure --enable-languages=c,c++,fortran,go --prefix=/usr --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --with-system-zlib --enable-gtk-cairo --with-arch-directory=arm --with-target-system-zlib --enable-multiarch --disable-sjlj-exceptions --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.2.0 (GCC)
"

g++:
` g++ -v`
"
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8.2.0/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: /home/pi/Downloads/objdir/../gcc-8.2.0/configure --enable-languages=c,c++,fortran,go --prefix=/usr --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --with-system-zlib --enable-gtk-cairo --with-arch-directory=arm --with-target-system-zlib --enable-multiarch --disable-sjlj-exceptions --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.2.0 (GCC)
"

build command:
`wget https://github.com/MiKTeX/miktex/archive/2.9.6880.tar.gz`
`tar xf 2.9.6880.tar.gz`
`cd miktex-2.9.6880/`
`mkdir build`
`cd build/`
`cmake ..`
`make`

observations: (Too long, please see pastebin)
https://pastebin.com/WB1sPsi9

The error is the last few lines:
"
This is TANGLE, Version 4.5 (MiKTeX 2.9.6880)
*1*10*21*36*48*64*80*97*109*146*163*218*290*331*455*467*472
Writing the output file.....500.....1000.....1500.....2000.....2500...
Done.
(No errors were found.)
[ 23%] Generating bibtex.cc, bibtex.h.intermediate, bibtexdefs.h
/home/pi/Downloads/miktex-2.9.6880/build/Programs/Bibliography/bibtex/bibtex.p:1: parse error before `▒'
Programs/Bibliography/bibtex/CMakeFiles/bibtex.dir/build.make:66: recipe for target 'Programs/Bibliography/bibtex/bibtex.cc' failed
make[2]: *** [Programs/Bibliography/bibtex/bibtex.cc] Error 1
CMakeFiles/Makefile2:1488: recipe for target 'Programs/Bibliography/bibtex/CMakeFiles/bibtex.dir/all' failed
make[1]: *** [Programs/Bibliography/bibtex/CMakeFiles/bibtex.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error [2]
"

Some analysis:
Raspbian, the operate system of Raspberry Pi, has two versions (https://www.raspberrypi.org/downloads/):
(1) ARM version: for Raspberry Pi. There are errors when make
(2) x86 version: I installed on my Intel Core i7 laptop. Everything is fine.

**Comment by zhaowei19920524** [comment]
This is the screenshot:
![miktex_make_error](https://user-images.githubusercontent.com/11030936/50701234-1c82b400-101b-11e9-9e79-b31a35622e49.png)

**Comment by zhaowei19920524** [comment]
This is related files:
[bibtex.zip](https://github.com/MiKTeX/miktex/files/2727920/bibtex.zip)

**Comment by edocevoli** [comment]
Thank you. Sorry, but since this platform is currently not supported, we cannot help you here.
