### ISSUE TITLE
Acknowledgments Section Replaced by "To Robert, for the bagels and explaining CMYK and color spaces"

### ISSUE THREAD

**Issue by GalacticStarfish** [MiKTeX/miktex#243]
If you create an LaTeX document with an acknowledgements section like so:
```
\section{Acknowledgments}
Thank you Mickey Mouse. 
```
The acknowledgments section will be replaced by:

> To Robert, for the bagels and explaining CMYK and color spaces

**Comment by edocevoli** [comment]
This is not a MiKTeX-specific bug and so cannot be fixed by me.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).
