### ISSUE TITLE
miktexsetup peer certificate error

### ISSUE THREAD

**Issue by MCM-Math** [MiKTeX/miktex#245]
I'm trying to set up a local package repo in my new workspace, but I get the error "miktexsetup: Peer certificates cannot be authenticated with given CA certificates".  I didn't have this error in the previous work environment.  Is there a workaround?  Keep in mind that my access is not administrative.

**Comment by edocevoli** [comment]
I would recommend that you choose a remote package repository which is working for you. Try `miktexsetup --help`.

**Comment by MCM-Math** [comment]
I don't have one that works.

**Comment by MCM-Math** [comment]
How can I find one?

**Comment by edocevoli** [comment]
This seems to be a duplicate of #118

**Comment by edocevoli** [comment]
Duplicate of #118

**Comment by MCM-Math** [comment]
I run into the same error when I try to list the available repositories.

**Comment by MCM-Math** [comment]
> Duplicate of #118

No it is not, as I am not even able to install MiKTeX in the new workspace.  Please actually read threads before assuming.
