### ISSUE TITLE
MikTex installation on OSX 10.14.2 (Mojave)

### ISSUE THREAD

**Issue by yiorgb** [MiKTeX/miktex#246]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

After installing MikTeX on /usr/local/bin  I get the following error. 

```
ERROR: collate_byname<char>::collate_byname failed to construct for 

Sorry, but latex did not succeed.
libc++abi.dylib: terminating with uncaught exception of type MiKTeX::Core::MiKTeXException: MiKTeX encountered an internal error.
Abort trap: 6
```

Install report from `/var/log/miktex` seems indicate that something is off with `PathOkay` but `/usr/local/bin` is in my path settings. 
```
Date: 2019-01-14 05:07:03
MiKTeX: 2.9.6930
OS: Darwin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
SharedSetup: yes
PathOkay: no
LastUpdateCheck: 2019-01-14 05:05:48
LastUpdate: 2019-01-14 05:05:23
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: /Library/Application Support/MiKTeX/texmfs/config
Root1: /Library/Application Support/MiKTeX/texmfs/data
Root2: /Library/Application Support/MiKTeX/texmfs/install
CommonInstall: /Library/Application Support/MiKTeX/texmfs/install
CommonConfig: /Library/Application Support/MiKTeX/texmfs/config
CommonData: /Library/Application Support/MiKTeX/texmfs/data
```

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.
You can try it again tomorrow. If the problem still exists: collect log files, screenshots etc.

Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by libingict** [comment]
I have the same problem. My os is OSX mojave. I used the admin install mode.

> log4cxx: setFile(/Users/xxx/Library/Application Support/MiKTeX/texmfs/data/miktex/log/pdflatex.log,true) call failed.
> log4cxx: IO Exception : status code = 13
> log4cxx: No output stream or file set for the appender named [RollingLogFile].
> This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7050)
> Please type the name of your input file.
> **main.tex
> 
> Sorry, but pdflatex did not succeed.
> 
> The log file hopefully contains the information to get MiKTeX going again:
> 
>  /Users/xxx/Library/Application Support/MiKTeX/texmfs/data/miktex/log/pdflatex.log

There is no output log file in the above folder. Does anyone have the solution to this problem?

**Comment by zhuojw10** [comment]
> I have the same problem. My os is OSX mojave. I used the admin install mode.
> 
> > log4cxx: setFile(/Users/xxx/Library/Application Support/MiKTeX/texmfs/data/miktex/log/pdflatex.log,true) call failed.
> > log4cxx: IO Exception : status code = 13
> > log4cxx: No output stream or file set for the appender named [RollingLogFile].
> > This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7050)
> > Please type the name of your input file.
> > **main.tex
> > Sorry, but pdflatex did not succeed.
> > The log file hopefully contains the information to get MiKTeX going again:
> > /Users/xxx/Library/Application Support/MiKTeX/texmfs/data/miktex/log/pdflatex.log
> 
> There is no output log file in the above folder. Does anyone have the solution to this problem?

I also have the same problem, @libingict do you solve this problem now?

**Comment by Aathish04** [comment]
> > I have the same problem. My os is OSX mojave. I used the admin install mode.
> > > log4cxx: setFile(/Users/xxx/Library/Application Support/MiKTeX/texmfs/data/miktex/log/pdflatex.log,true) call failed.
> > > log4cxx: IO Exception : status code = 13
> > > log4cxx: No output stream or file set for the appender named [RollingLogFile].
> > > This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7050)
> > > Please type the name of your input file.
> > > **main.tex
> > > Sorry, but pdflatex did not succeed.
> > > The log file hopefully contains the information to get MiKTeX going again:
> > > /Users/xxx/Library/Application Support/MiKTeX/texmfs/data/miktex/log/pdflatex.log
> > 
> > 
> > There is no output log file in the above folder. Does anyone have the solution to this problem?
> 
> I also have the same problem, @libingict do you solve this problem now?

I solved it (just about) using trial and error. 
If you installed it via admin mode, and you're calling LaTeX from the terminal, you have to run the command with sudo. 
The problem seems to be linked with a bug(? not sure actually, might just be an error on my part), that causes log4cxx to improperly parse file path's with spaces anywhere in the path (for MacOS users this is probably "Application Support" (notice the space between the words).
Also, not sure why running with sudo fixes this ;)
