### ISSUE TITLE
tex4ht support

### ISSUE THREAD

**Issue by michal-h21** [MiKTeX/miktex#25]
Hi, I am one of `tex4ht` developers. I noticed that version included Miktex is quite old, we still release new version from time to time. The updates go directly to TeX Live, they are pulled from the source repository. 

I understand that it isn't really good solution for you to pull the changes from TL, so what would be a best way we could make the changes available for pulling to Miktex? We are not prepared for updating tex4ht on CTAN yet, but we might be able to provide a zip file with suitable structure. 

There are several types of files:

- we most often update the .4ht files, which are all included in one directory and there isn't really a issue when they are updated

- there is then tex4ht.env file, which has different versions for Windows and Unix. I think Miktex provides it's own version, which will be different from our version because of different directory paths and maybe some binaries. We updated the file recently for the SVG support, so it would be good to synchronize the versions somehow. It might be quite difficult.

- the font support .4hf and .htf files. They were updated recently as well, but I hope there shouldn't be any issues in import.

- the binaries. I think the version on Windows (both in Miktex and TL) haven't been updated for several years? There haven't been any updates apart from some small fixes in the last years anyway, so I guess that it doesn't matter so much.

So apart from the `tex4ht.env` file, I hope there shouldn't be big a issues in the upgrade.

One last thing, there are some commands which have different names in TL and Miktex. The one I found is Ghostscript, which can be invoked using `rungs` in TL, but as `mgs` in Miktex. Do you think it would be possible to add some alias for `rungs` in Miktex? Or do you have other idea how to ideally solve this issue?

**Comment by edocevoli** [comment]
There are currently three tex4ht packages in the MiKTeX distribution:

1. `miktex-tex4ht-bin-2.9` (`miktex-tex4ht-bin-2.9-x64`) contains the binaries
2. `miktex-tex4ht` contains `tex4ht.env` (two variants for Windows/Linux)
3. `tex4ht` contains the rest of thex tex4ht system

I usually update the three packages

- when the yearly TeX Live is released
- when tex4ht is uploaded to CTAN
- when I'm notified (email, issue ticket)

Regarding issues: this repository contains the source code for building the MiKTeX binaries. There is another repository: https://github.com/MiKTeX/miktex-packaging which should be used for packaging `miktex-tex4ht` and `tex4ht`.

**Comment by michal-h21** [comment]
Thank you for a quick response and sorry for selecting the wrong repository. I was directed her because I discussed the different naming of the included Ghostscript  interpreter in TL and Miktex. 

So it seems that `miktex-tex4ht-bin-2.9` doesn't need an update and the main difference between `tex4ht.env` included in Miktex and the current version is that `dvipng` and `dvisvgm` are used for image conversion:

```
G.png
%echo "dbg: got to dvi to png via (dvipng)"
Gdvipng -T tight -D 144 -bg Transparent -pp %%2:%%2 %%1 -o %%3
G.gif
Gdvipng -T tight -D 144 -bg Transparent -gif -pp %%2:%%2 %%1 -o %%3
G.svg
Gdvisvgm -n -p %%2 -c 1.4,1.4 -s %%1 > %%3  
G.
Gdvipng -T tight -D 144 -bg Transparent -pp %%2:%%2 %%1 -o %%3
```
The other changes seems to be caused only by different paths and binary names.

So if I prepare a zip file in the TDS structure containing only stuff in `tex4ht` package, would it be ideal for you?

**Comment by edocevoli** [comment]
Right, `miktex-tex4ht-bin-2.9` doesn't need an update.

MiKTeX does not include `rungs` yet. If you think that it makes sense, I could create a link between `rungs` and `mgs`.

Today I have updated the other two packages. They should now be in sync with TL:

http://tug.org/svn/texlive/trunk/Master/texmf-dist/tex4ht 
http://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/generic/tex4ht

**Comment by michal-h21** [comment]
Thank you for the update. I will try to create a workflow for CTAN updates. It would be best for everybody, even if we include only the .4ht and font files, without binaries or the .env files.

> MiKTeX does not include rungs yet. If you think that it makes sense, I could create a link between rungs and mgs.

It would be really great, because we request Ghostscript from TeX. I don't think it is possible to detect if the compilation happens under Miktex or TL and request the correct script.

**Comment by edocevoli** [comment]
`rungs` is now available.
