### ISSUE TITLE
Error when installing miktex basic-miktex-2.9.6942-x64 for All Users

### ISSUE THREAD

**Issue by michaeljcampbell** [MiKTeX/miktex#251]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am running windows 10, with a single admin user account.  I run the Miktex install program as administrator and receive the error:

        Option --admin only makes sense for a shared MiKTeX setup.

The log file is below:

initializing setup service...
starting installer...
Loading package database...
starting package maintenance...
installation directory: "C:\Program Files\MiKTeX 2.9"
package repository: C:\Users\Mike\AppData\Local\Temp\mik73756
visiting repository C:\Users\Mike\AppData\Local\Temp\mik73756...
repository type: local package repository
loading package repository manifest...
package repository digest: eeb3e5e66406550a7902c80fd376b65b
going to install 10766 file(s) (214 package(s))
extracting files from ae.tar.lzma...
extracting files from amscls.tar.lzma...
extracting files from amsfonts.tar.lzma...
extracting files from amsmath.tar.lzma...
extracting files from asymptote.tar.lzma...
extracting files from avantgar.cab...
extracting files from babel.tar.lzma...
extracting files from babel-english.tar.lzma...
extracting files from babel-french.tar.lzma...
extracting files from babel-german.tar.lzma...
extracting files from babel-spanish.tar.lzma...
extracting files from bibtex.tar.lzma...
extracting files from bibtex8bit.tar.lzma...
extracting files from bibtex8bit-polish.tar.lzma...
extracting files from bidi.tar.lzma...
extracting files from bookman.cab...
extracting files from carlisle.tar.lzma...
extracting files from cbcoptic.tar.lzma...
extracting files from chktex.tar.lzma...
extracting files from cm.tar.lzma...
extracting files from courier.tar.lzma...
extracting files from cweb.tar.lzma...
extracting files from cyrillic.tar.lzma...
extracting files from dehyph.tar.lzma...
extracting files from dehyph-exptl.tar.lzma...
extracting files from dvipdfmx.tar.lzma...
extracting files from dvips.tar.lzma...
extracting files from ec.tar.lzma...
extracting files from elhyphen.tar.lzma...
extracting files from enctex.tar.lzma...
extracting files from etex.tar.lzma...
extracting files from etex-pkg.tar.lzma...
extracting files from euenc.tar.lzma...
extracting files from eurosym.tar.lzma...
extracting files from float.tar.lzma...
extracting files from fontconfig.tar.lzma...
extracting files from fontname.tar.lzma...
extracting files from fontspec.tar.lzma...
extracting files from geometry.tar.lzma...
extracting files from ghostscript.tar.lzma...
extracting files from graphics.tar.lzma...
extracting files from graphics-cfg.tar.lzma...
extracting files from graphics-def.tar.lzma...
extracting files from gsftopk.tar.lzma...
extracting files from helvetic.cab...
extracting files from hyperref.tar.lzma...
extracting files from hyph-utf8.tar.lzma...
extracting files from ifxetex.tar.lzma...
extracting files from jknappen.tar.lzma...
extracting files from knuth-lib.tar.lzma...
extracting files from knuth-local.tar.lzma...
extracting files from latex-fonts.tar.lzma...
extracting files from lm.tar.lzma...
extracting files from ltxbase.tar.lzma...
extracting files from ltxmisc.tar.lzma...
extracting files from lua-alt-getopt.tar.lzma...
extracting files from luainputenc.tar.lzma...
extracting files from lualibs.tar.lzma...
extracting files from luamplib.tar.lzma...
extracting files from luaotfload.tar.lzma...
extracting files from luatexbase.tar.lzma...
extracting files from luatextra.tar.lzma...
extracting files from makeindex.tar.lzma...
extracting files from metafont.tar.lzma...
extracting files from metapost.tar.lzma...
extracting files from mflogo.tar.lzma...
extracting files from mflogo-font.tar.lzma...
extracting files from mfware.tar.lzma...
extracting files from miktex-arctrl-bin-x64-2.9.tar.lzma...
extracting files from miktex-asymptote-bin-x64-2.9.tar.lzma...
extracting files from miktex-autosp-bin-x64-2.9.tar.lzma...
extracting files from miktex-axohelp-bin-x64-2.9.tar.lzma...
extracting files from miktex-bibarts-bin-x64.tar.lzma...
extracting files from miktex-biber-bin-x64.tar.lzma...
extracting files from miktex-bibtex-bin-x64-2.9.tar.lzma...
extracting files from miktex-bibtex8bit-bin-x64-2.9.tar.lzma...
extracting files from miktex-bzip2-bin-x64-2.9.tar.lzma...
extracting files from miktex-cairo-bin-x64-2.9.tar.lzma...
extracting files from miktex-chktex-bin-x64-2.9.tar.lzma...
extracting files from miktex-cjkutils-bin-x64-2.9.tar.lzma...
extracting files from miktex-config-2.9.tar.lzma...
extracting files from miktex-console-bin-x64-2.9.tar.lzma...
extracting files from miktex-curl-bin-x64-2.9.tar.lzma...
extracting files from miktex-cweb-bin-x64-2.9.tar.lzma...
extracting files from miktex-devnag-bin-x64-2.9.tar.lzma...
extracting files from miktex-dict-english.tar.lzma...
extracting files from miktex-dict-french.tar.lzma...
extracting files from miktex-dict-german.tar.lzma...
extracting files from miktex-doc-2.9.tar.lzma...
extracting files from miktex-dvicopy-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvipdfmx.tar.lzma...
extracting files from miktex-dvipdfmx-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvipng-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvips.tar.lzma...
extracting files from miktex-dvips-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvisvgm-bin-x64-2.9.tar.lzma...
extracting files from miktex-epstopdf-bin-x64-2.9.tar.lzma...
extracting files from miktex-etex.tar.lzma...
extracting files from miktex-expat-bin-x64-2.9.tar.lzma...
extracting files from miktex-findtexmf-bin-x64-2.9.tar.lzma...
extracting files from miktex-fmt-bin-x64-2.9.tar.lzma...
extracting files from miktex-fontconfig.tar.lzma...
extracting files from miktex-fontconfig-bin-x64-2.9.tar.lzma...
extracting files from miktex-fonts-bin-x64-2.9.tar.lzma...
extracting files from miktex-freeglut-bin-x64-2.9.tar.lzma...
extracting files from miktex-freetype2-bin-x64-2.9.tar.lzma...
extracting files from miktex-fribidixetex-bin-x64-2.9.tar.lzma...
extracting files from miktex-gd-bin-x64-2.9.tar.lzma...
extracting files from miktex-ghostscript-bin-x64.tar.lzma...
extracting files from miktex-graphite2-bin-x64-2.9.tar.lzma...
extracting files from miktex-gregorio-bin-x64-2.9.tar.lzma...
extracting files from miktex-gsf2pk-bin-x64-2.9.tar.lzma...
extracting files from miktex-harfbuzz-bin-x64-2.9.tar.lzma...
extracting files from miktex-hunspell-bin-x64-2.9.tar.lzma...
extracting files from miktex-icu-bin-x64.tar.lzma...
extracting files from miktex-jpeg-bin-x64-2.9.tar.lzma...
extracting files from miktex-kpathsea-bin-x64-2.9.tar.lzma...
extracting files from miktex-lacheck-bin-x64-2.9.tar.lzma...
extracting files from miktex-latex.tar.lzma...
extracting files from miktex-libressl-bin-x64-2.9.tar.lzma...
extracting files from miktex-log4cxx-bin-x64-2.9.tar.lzma...
extracting files from miktex-lua52-bin-x64-2.9.tar.lzma...
extracting files from miktex-lua53-bin-x64-2.9.tar.lzma...
extracting files from miktex-luatex.tar.lzma...
extracting files from miktex-luatex-bin-x64-2.9.tar.lzma...
extracting files from miktex-lzma-bin-x64-2.9.tar.lzma...
extracting files from miktex-m-tx-bin-x64-2.9.tar.lzma...
extracting files from miktex-makeindex-bin-x64-2.9.tar.lzma...
extracting files from miktex-md5-bin-x64-2.9.tar.lzma...
extracting files from miktex-metafont.tar.lzma...
extracting files from miktex-metafont-bin-x64-2.9.tar.lzma...
extracting files from miktex-metapost.tar.lzma...
extracting files from miktex-metapost-bin-x64-2.9.tar.lzma...
extracting files from miktex-mfware-bin-x64-2.9.tar.lzma...
extracting files from miktex-misc.tar.lzma...
extracting files from miktex-mkfntmap-bin-x64-2.9.tar.lzma...
extracting files from miktex-mktex-bin-x64-2.9.tar.lzma...
extracting files from miktex-mo-bin-x64-2.9.tar.lzma...
extracting files from miktex-mpfr-bin-x64-2.9.tar.lzma...
extracting files from miktex-mpmcli-bin-x64-2.9.tar.lzma...
extracting files from miktex-mspack-bin-x64-2.9.tar.lzma...
extracting files from miktex-mthelp-bin-x64-2.9.tar.lzma...
extracting files from miktex-mtprint-bin-x64-2.9.tar.lzma...
extracting files from miktex-omega.tar.lzma...
extracting files from miktex-omega-bin-x64-2.9.tar.lzma...
extracting files from miktex-pdftex.tar.lzma...
extracting files from miktex-pdftex-bin-x64-2.9.tar.lzma...
extracting files from miktex-pixman-bin-x64-2.9.tar.lzma...
extracting files from miktex-pmx-bin-x64-2.9.tar.lzma...
extracting files from miktex-png-bin-x64-2.9.tar.lzma...
extracting files from miktex-poppler-bin-x64-2.9.tar.lzma...
extracting files from miktex-popt-bin-x64-2.9.tar.lzma...
extracting files from miktex-posix-bin-x64-2.9.tar.lzma...
extracting files from miktex-ps2pk-bin-x64-2.9.tar.lzma...
extracting files from miktex-psutils-bin-x64-2.9.tar.lzma...
extracting files from miktex-qt5-bin-x64.tar.lzma...
extracting files from miktex-runtime-bin-x64-2.9.tar.lzma...
extracting files from miktex-tdsutil-bin-x64-2.9.tar.lzma...
extracting files from miktex-teckit-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex.tar.lzma...
extracting files from miktex-tex-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex2xindy-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex4ht.tar.lzma...
extracting files from miktex-tex4ht-bin-x64-2.9.tar.lzma...
extracting files from miktex-texify-bin-x64-2.9.tar.lzma...
extracting files from miktex-texinfo.tar.lzma...
extracting files from miktex-texware-bin-x64-2.9.tar.lzma...
extracting files from miktex-texworks-bin-x64-2.9.tar.lzma...
extracting files from miktex-ttf2pk2-bin-x64-2.9.tar.lzma...
extracting files from miktex-ucrt-bin-x64.tar.lzma...
extracting files from miktex-uriparser-bin-x64-2.9.tar.lzma...
extracting files from miktex-vc140-bin-x64.tar.lzma...
extracting files from miktex-web-bin-x64-2.9.tar.lzma...
extracting files from miktex-xetex.tar.lzma...
extracting files from miktex-xetex-bin-x64-2.9.tar.lzma...
extracting files from miktex-xindy-bin-x64.tar.lzma...
extracting files from miktex-yap-bin-x64-2.9.tar.lzma...
extracting files from miktex-zip-bin-x64.tar.lzma...
extracting files from miktex-zlib-bin-x64-2.9.tar.lzma...
extracting files from miktex-zzip-bin-x64-2.9.tar.lzma...
extracting files from multirow.tar.lzma...
extracting files from ncntrsbk.cab...
extracting files from oberdiek.tar.lzma...
extracting files from palatino.cab...
extracting files from pdftex.tar.lzma...
extracting files from plain.tar.lzma...
extracting files from polyglossia.tar.lzma...
extracting files from poppler.tar.lzma...
extracting files from pslatex.tar.lzma...
extracting files from psnfss.cab...
extracting files from pstricks.tar.lzma...
extracting files from psutils.tar.lzma...
extracting files from rsfs.tar.lzma...
extracting files from ruhyphen.tar.lzma...
extracting files from tetex.tar.lzma...
extracting files from tex-ini-files.tar.lzma...
extracting files from texinfo.tar.lzma...
extracting files from thumbpdf.tar.lzma...
extracting files from times.cab...
extracting files from tools.tar.lzma...
extracting files from ttf2pk.tar.lzma...
extracting files from ukrhyph.tar.lzma...
extracting files from unicode-data.tar.lzma...
extracting files from utopia.cab...
extracting files from xetex.tar.lzma...
extracting files from xgreek.tar.lzma...
extracting files from xindy.tar.lzma...
extracting files from xkeyval.tar.lzma...
extracting files from xltxtra.tar.lzma...
extracting files from xunicode.tar.lzma...
extracting files from xypic.tar.lzma...
extracting files from zapfchan.cab...
extracting files from zapfding.cab...
extracting files from zerohyph.tar.lzma...
updating package manifests ("C:\Program Files\MiKTeX 2.9\miktex/config\package-manifests.ini")...
installed 3437 package manifests
visiting repository C:\Users\Mike\AppData\Local\Temp\mik73756...
repository type: local package repository
loading package repository manifest...
initexmf "--common-install=C:\Program Files\MiKTeX 2.9" --set-config-value=[Core]SharedSetup=1 --admin "--log-file=C:\Program Files\MiKTeX 2.9\miktex/config\uninst.log" --disable-installer --verbose:
Option --admin only makes sense for a shared MiKTeX setup.

Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:

  Option --admin only makes sense for a shared MiKTeX setup.

An error occurred:
  source file: 
  source line: 0
  message: The executed process did not succeed.
  info: fileName="C:\Program Files\MiKTeX 2.9\miktex\bin\x64\initexmf.exe", exitCode="1"

**Comment by edocevoli** [comment]
Thank you for the report. Unfortunately, it seems that it is not possible to run MiKTeX on your system.
