### ISSUE TITLE
Issue with installing miktex on linux Mint 19

### ISSUE THREAD

**Issue by simo94445** [MiKTeX/miktex#252]
I followed the instructions on the official website, but was met with an error.
There's the following error when trying to install MiKTex from your repo:

Err:1 https://ftp.rrze.uni-erlangen.de/ctan/systems/win32/miktex/setup/deb bionic/universe amd64 miktex amd64 2.9.6930-bionic1
  Certificate verification failed: The certificate is NOT trusted. The received OCSP status response is invalid.  Could not handshake: Error in the certificate verification. [IP: 131.188.12.211 443]
E: Failed to fetch https://ftp.rrze.uni-erlangen.de/ctan/systems/win32/miktex/setup/deb/pool/universe/m/miktex/miktex_2.9.6930-bionic1_amd64.deb  Certificate verification failed: The certificate is NOT trusted. The received OCSP status response is invalid.  Could not handshake: Error in the certificate verification. [IP: 131.188.12.211 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by edocevoli** [comment]
You have the option to specify another mirror. So instead of getting the deb from another mirror. So instead of

```
echo "deb http://miktex.org/download/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list
```

you can run this:

```
export CTAN_BASE_URL=http://mirrors.sjtug.sjtu.edu.cn/ctan
echo "deb ${CTAN_BASE_URL}/systems/win32/miktex/setup/deb bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list
```

For a list of valid CTAN mirrors, visit https://ctan.org/mirrors.

**Comment by simo94445** [comment]
@edocevoli that worked fine, thank you
