### ISSUE TITLE
biber: missing on Ubuntu and Mac

### ISSUE THREAD

**Issue by yordiak** [MiKTeX/miktex#254]
Hello, 
I decided to give a try on MikTex's  ubuntu version (Ubuntu 16.04 64bit). However, I experience the following problem: biber program is missing!
 
I tried to install it using  `sudo mpm --admin --install=biber` command, but I get the following error:

> Sorry, but "MiKTeX Package Manager" did not succeed.
> The log file hopefully contains the information to get MiKTeX going again:
> /var/log/miktex/mpmcli_admin.log
> You may want to visit the MiKTeX project page, if you need help.

How can I overcome this problem?

PS: A relative problem is that I cannot launch Miktex package manager (mpm) as well. The command `sudo mpm --admin` generates an error:

> Sorry, but "MiKTeX Package Manager" did not succeed for the following reason:
> Could not restart in windowed mode.
> The log file hopefully contains the information to get MiKTeX going again:
>  /var/log/miktex/mpmcli_admin.log
> You may want to visit the MiKTeX project page, if you need help.

**Comment by edocevoli** [comment]
The executable is now included:

- `biber-darwin-x86_64`
- `biber-linux-x86_64`

Running `biber` triggers the installer if the package is not yet installed.

**Comment by itzsimpl** [comment]
Installing the `biber-darwin-x86_64` package manually, does not make `biber` executable.

    -rw-r--r--  1 root  admin  20005438  1 Mar 22:30 /Library/Application Support/MiKTeX/texmfs/install/biber/bin/darwin-x86_64/biber

In addition in `/usr/local/bin` does not contain a symbolic link to `biber`.

**Comment by edocevoli** [comment]
You should not install it manually.

You can create the link by running `initexmf --admin --mklinks`. This will also set the executable bit.
