### ISSUE TITLE
native Asymptote adaptive OpenGL-based 3D-renderer  doesn't work

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#26]
asymptote contains a native renderer for 3D-objects. When I compile the following example (it is from the gallery of asymptote) on texlive with `asy -V asytest.asy`  this renderer opens after the compilation and shows the object. 

~~~~
import settings;
outformat="";
render=-1;
import three;

size(100);

path3 g=(1,0,0)..(0,1,0)..(-1,0,0)..(0,-1,0)..cycle;
draw(g);
draw(O--Z,red+dashed,Arrow3);
draw(((-1,-1,0)--(1,-1,0)--(1,1,0)--(-1,1,0)--cycle));
dot(g,red);
~~~~

With miktex (a current miktex/next) I get this error message:

~~~~~
C:\Users\XXXX\Documents\tests>asy -V asytest3.asy
C:\Users\XXXX\MikTeX/asymptote/three.asy: 2905.13: runtime: to support onscreen rendering, please install glut library, run ./configure, and recompile
~~~~~

Changing the output format to pdf with `outformat="pdf";` works fine: the file is then opened in the adobe reader. 

I found an old tex.sx question with the same error on linux: https://tex.stackexchange.com/questions/135841/asymptote-default-renderer-problem-after-upgrading-to-tex-live-2013 and a bug report https://sourceforge.net/p/asymptote/discussion/409349/thread/c60c13ab/.

**Comment by edocevoli** [comment]
OpenGL support isn't currently implemented in the native MiKTeX port of asymptote. I will take a look if I can enable it, but I have doubts whether it will work. The Asymptote source code is very Linux-centric and not very portable.

If you must/want use the OpenGL renderer, I would suggest that you use the Cygwin port made available by the Asympote developers: http://asymptote.sourceforge.net/binaries.html. I think this is the binary which has been "incorporated" into the TeX Live distribution for Windows.

**Comment by u-fischer** [comment]
Thanks, I will pass the message on (it came from this tex.sx question: https://tex.stackexchange.com/questions/398421/miktex-how-to-install-glut-library-on-windows.)

**Comment by edocevoli** [comment]
I have integrated the OpenGL renderer, i.e., running `asy -V asytest.asy` now opens a simple OpenGL viewer.
