### ISSUE TITLE
Miktex console and miktex taskbar icon

### ISSUE THREAD

**Issue by phpdistiller** [MiKTeX/miktex#260]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hi
It's more a question than an issue. Maybe an improvement.
I'm on Windows.
It's possible to launch Miktex console without opening the icon in the taskbar ?

Thanks

**Comment by BeerStud** [comment]
Well, I guess you could start it from the command line:

"C:\Program Files\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe"
