### ISSUE TITLE
MPM crashes with --require=@

### ISSUE THREAD

**Issue by donovaly** [MiKTeX/miktex#263]
- log in as admin on Windows
- uninstall e.g. the package "georgian"
- use thhis text file:
[Packages.txt](https://github.com/MiKTeX/miktex/files/2849650/Packages.txt)
- shift-right-click in the Windows file explorer on the folder of the Packages.txt file and choose "open a console here"
- open a console and execute this command:
mpm.exe --admin --verbose --require=@Packages.txt

result: crash after some seconds of waiting

In the log file I see:

2019-02-11 02:37:51,511+0100 INFO  mpmcli - starting: mpmcli 2.9.6888 (MiKTeX 2.9.6960)
2019-02-11 02:37:51,511+0100 INFO  mpmcli - Operating on the shared (system-wide) MiKTeX setup
2019-02-11 02:37:52,135+0100 FATAL mpmcli - Cannot start MiKTeX package manager.
2019-02-11 02:37:52,135+0100 FATAL mpmcli - Info: hr="Die Klasse ist nicht f�r die Unterst�tzung der Aktivierung mit erh�hten Rechten konfiguriert.

But I have admin permissions, the MikTeX diagnose says:
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
see below.
 
I did not call cmd explicitly to assure special admin permissions for it. Even if this is necessary, MiKTeX must not crash but issue an error.

MiKTeX: 2.9.6960
OS: Windows 7 Professional, 64-bit, Service Pack 1, build 7601
SharedSetup: yes
PathOkay: yes
LastUpdateCheck: 2019-02-11 00:45:41
LastUpdate: 2019-02-10 21:54:59
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files (x86)\MiKTeX 2.9
CommonInstall: C:\Program Files (x86)\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by edocevoli** [comment]
Please check the output of:

```
initexmf --admin --show-config-value [MPM]ForceLocalServer
```

**Comment by donovaly** [comment]
This gives me in the console only:
`initexmf: warning: Option --admin may require administrator privileges`

In the initexmf.log I see:
`
9-02-11 22:46:44,831+0100 INFO  initexmf - starting: MiKTeX Configuration Utility 2.9.6964 (MiKTeX 2.9.6960)
2019-02-11 22:46:44,831+0100 INFO  initexmf - Operating on the shared (system-wide) MiKTeX setup
2019-02-11 22:46:44,831+0100 INFO  initexmf - starting with command line: initexmf --admin --show-config-value [MPM]ForceLocalServer
2019-02-11 22:46:44,862+0100 INFO  initexmf - finishing with exit code 0
`

A side note:
When I log in as admin in Windows and start programs they are normally run with admin privileges (e.g. installers etc). But when I start the MPM console GUI it asks me if I want to restart it in admin mode. But I am already the admin as the MiKTeX diagnose tells me.
OK, as admin I can also run progs in user mode but why should I want this by default? I log in as admin because I have to administer things (most cases do something accecting all users of the PC) therefore when starting MPM as admin, it should by default run with admin privilegs.

Or do I have a thinko here?

**Comment by edocevoli** [comment]
> But when I start the MPM console GUI it asks me if I want to restart it in admin mode.

This the new behavior (see #128).

**Comment by donovaly** [comment]
> Yes, this is the new behavior (see #128).

Thanks for the pointer, I commented there.

However, what about the crash? Can I help you more by getting more info somehow about the crash?

**Comment by edocevoli** [comment]
Thank you, I think I have enough info. This will be fixed.

**Comment by edocevoli** [comment]
This has been fixed now, i.e., mpm will not crash.

**Comment by donovaly** [comment]
Thank you
