### ISSUE TITLE
MiKTeX failed to test file existence for /dev/null, on macOS and Linux

### ISSUE THREAD

**Issue by Liam0205** [MiKTeX/miktex#264]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

As mentioned by @fylimas in https://github.com/MiKTeX/miktex/issues/77#issuecomment-463052998, MiKTeX failed to test OS on macOS and Linux. The origin of the problem rooted in the failure of a file existence test: `/dev/null`.

Both CTeX (CTeX-org/ctex-kit#340 and CTeX-org/ctex-kit#313) and `ifplatform` consider Windows if `/dev/null` doesn't exist. However, MiKTeX always gives `False` by the following test, on macOS and Linux, which cause problems:

```tex
\ExplSyntaxOn
\file_if_exist:nTF { /dev/null } { True } { False }
\ExplSyntaxOff
```

Please consider to check and fix it. Thanks!

----

MWE: 

```tex
% macOS High Sierra 10.13
% MiKTeX 2.9.6637
% CTeX 2.4.14
% xelatex --shell-escape mwe.tex
\documentclass{article}
\usepackage{ifplatform}
\usepackage[fontset=none]{ctex}

\begin{document}

ifplatform test:\\
\ifshellescape shell escape on\else shell escape off\fi\\
\IfFileExists{/dev/null}{dev null exists}{dev null not exists}\\
\ifwindows windows true \else windows false \fi

\ExplSyntaxOn
\LaTeX3 ~ test: \\
\file_if_exist:nTF { /dev/null } { dev ~ null ~ exists } { dev ~ null ~ not ~ exists } \\
\file_if_exist:nTF { /Library/Fonts/Songti.ttc } { Library ~ Fonts ~ Songti ~ exists } { Library ~ Fonts ~ Songti  ~ not ~ exists } \\
\ctex_detected_platform:
g_ctex_fontset_tl: ~ \g__ctex_fontset_tl \\
\ExplSyntaxOff

\end{document}
```

Result:

> ifplatform test:
shell escape on
dev null not exists
windows true
LATEX3 test:
dev null not exists
Library Fonts Songti exists
g_ctex_fontset_tl: windows

**Comment by Liam0205** [comment]
c.c. @LeoLiu @qinglee @wenbosheng

**Comment by edocevoli** [comment]
Thank you for the report. This has been fixed now.
