### ISSUE TITLE
Problem installation MikTex $PATH

### ISSUE THREAD

**Issue by Giakke10** [MiKTeX/miktex#266]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by Giakke10** [comment]
Good evening,

i have tried to install MiKTeX on MAC but when is already installed this figure come out. (attached file 1)
Then i try to press private installation and this error come out: attached file 2.

I have tried to solve the problem but this error come out: attached file 3.

I hope you can help me.

Thank you very much.

Matteo Giacomelli
1.png





2.pngù3.png

**Comment by Giakke10** [comment]
<img width="785" alt="1" src="https://user-images.githubusercontent.com/47634233/52790320-8ce31300-3066-11e9-8689-0df461726a0d.png">
<img width="1015" alt="3" src="https://user-images.githubusercontent.com/47634233/52790321-8ce31300-3066-11e9-85fa-bc266ba88ab4.png">
<img width="450" alt="2" src="https://user-images.githubusercontent.com/47634233/52790322-8ce31300-3066-11e9-86c8-7821672b55fd.png">

**Comment by edocevoli** [comment]
Thank you. You have the option to reset your installation to factory defaults (on the `Cleanup` page).
