### ISSUE TITLE
Miktex SSL Connect Error

### ISSUE THREAD

**Issue by AhmedKhattak** [MiKTeX/miktex#269]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I try to update packages via miktex console and get the following error

GENERAL MIKTEX INFORMATION
Date: 2019-02-19 23:35:11
MiKTeX: 2.9.6930
OS: Windows 10 Pro, 64-bit, build 17134
SharedSetup: yes
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files\MiKTeX 2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: non-existing/cmd

Warning: the following problems were detected:
  1: not yet checked for updates
  2: installation is not up-to-date

ERROR DETAILS
Program: C:\Program Files\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:264
Error: SSL connect error
Details: 
  code: 35
  url: https://ctan.um.ac.ir/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma

Visiting the url
https://ctan.um.ac.ir/systems/win32/miktex/tm/packages/

On any browser i open the link it says the site is not secure
![image](https://user-images.githubusercontent.com/15248863/53038904-a7225400-349f-11e9-9013-be5949a054fd.png)

![image](https://user-images.githubusercontent.com/15248863/53038970-d042e480-349f-11e9-8847-e7df75fda2a2.png)

How do i update and use miktex ?

**Comment by edocevoli** [comment]
I would recommend that you you use another repository.
