### ISSUE TITLE
The remote package repository is outdated

### ISSUE THREAD

**Issue by fbrazdik** [MiKTeX/miktex#27]
## My check list

- can not update, using the actual installer

## What I tried to do

I tried to update from internet repositories

## What I expected to happen
Install package

## What happened instead
Received following problem on many repositories:

MiKTeX Problem Report
Message: The remote package repository is outdated. You have to choose another repository.
Data: url="http://ftp.cvut.cz/tex-archive/systems/win32/miktex/tm/packages/"
Source: Libraries\MiKTeX\PackageManager\RestRemoteService.cpp
Line: 275
MiKTeX: 2.9
OS: Windows 7 Professional, 64-bit, Service Pack 1, build 7601
Invokers: explorer
SystemAdmin: no
PowerUser: no
Root0: C:\Users\U04044\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\U04044\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: c:\MiKTeX
UserInstall: C:\Users\U04044\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\U04044\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\U04044\AppData\Local\MiKTeX\2.9
CommonInstall: c:\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by egorpugin** [comment]
Same for me.

**Comment by edocevoli** [comment]
I am afraid that all repositories are currently out-of-date because the last CTAN upload was unsuccessful. The next CTAN upload is scheduled, ETA is 20171031T0600 (UTC).

**Comment by MaartenVL** [comment]
I'm also having this issue. Today I re-installed MikTex, since I was having some Issues.

**Comment by rodazuero** [comment]
Reporting same issue.

**Comment by slash020** [comment]
I'm also having this issue (Win 10)

**Comment by amaranPather** [comment]
I'm having this issue as well, regardless of the repository I attempt to connect to. (Win 10 version 1709)

**Comment by RogerLo0327** [comment]
Yes, I also have this issue. I am in Taiwan.
All four repository in Taiwan are out of dated.  Tested by my 2 windows PC.

**Comment by MicroStone** [comment]
Also have this problem in china shanghai win 10 PC using campus network with trying many repositories in different areas.

**Comment by MaartenVL** [comment]
It's working again for me now.

**Comment by mjhalwa** [comment]
i am using windows 10 and MiKTeX 2.9. I experience the same issue today. I already updated all packages and (twice), but I am unable to install new packages due to "outdated repository"

**Comment by DrTwonky** [comment]
Same problem here with MiKTeX 2.9, basic 64bit installer 6520 on Win10. This issue should be reopened.

**Comment by alexhalbi** [comment]
Happened to me too today, deleting the Registry key did not help, I chose ``ctan.math.illinouis.edu`` this server seems to be updated.

It would be great if you could choose to try out multiple package repos if one is outdated. Kind of a fallback to search for an updated server, so you do not need to manually try all the servers until one works.

**Comment by RubyShnol** [comment]
This is embarrassing. Reopen the issue. The solutions with the registry do not work.

**Comment by pfbuxton** [comment]
I too am presently getting this issue 8/Jan/2018.

**Comment by AbdullahXO** [comment]
Having the same issue with Windows 10 64bit
and with a new, clean installation of MiKTEX version 2.9.6520.

**Comment by MatSpecInf** [comment]
Same problem

**Comment by JamesTCurran** [comment]
Same issue here.

**Comment by karvek** [comment]
I managed to update MiKTEX to 2.9.6515 and the current packages as alexhalbi suggested but no chances to add new packages due to "outdated repository".

**Comment by akivaTLI** [comment]
same issure here with win7 64bit and miktex ver. 2.9.6515

**Comment by moigagoo** [comment]
I don't have the registry entry mentioned above (using portable MiKTeX), so even if this workaround works, I can't use it :-(

**Comment by Chrislan07** [comment]
sam issue here

**Comment by etherewind** [comment]
Same issue for me

**Comment by OpeTree** [comment]
Running MikTex version 2.9. Having the same issue of "remote package repository is outdated".

**Comment by senniraf** [comment]
I'm using Windows 10 and I'm having the same issue

**Comment by Cotton76** [comment]
I have the same issue. regedit workaround do not work for me!
windows 7 pro + MikTex version 2.9

**Comment by alexhalbi** [comment]
If you need new packages immediately you can just randomly try mirrors that's what I did to "resolve" this. But the registry fix does not seem to work anymore... Maybe a problem with the mirrors?

**Comment by affischer** [comment]
https://github.com/MiKTeX/miktex/issues/49 <- probably same issue. Apparently temporary

**Comment by knnyrotimi** [comment]
I am having an issue with updating my Miktex version 2.9. Its keep showing up "The remote package repository is outdated. You have to choose another repository. url=hhtp://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/"

Can anyone hellp with this.

Thanks

**Comment by kaatrin** [comment]
I am having this issue too.

**Comment by adrianprochaska** [comment]
I am having troubles adding packages and synchronizing the repository, too.

**Comment by shuangz25** [comment]
I am having the same issue, and deleting HKEY_LOCAL_MACHINE\SOFTWARE\MiKTeX.org\MiKTeX\2.9\MPM does not work.

**Comment by brunoggregorio** [comment]
Same issue here with miktex 2.9 and win10 64bit

**Comment by howardlau1999** [comment]
Same issue in China now on Windows 10 64-bit with MiKTex 2.9. All repos dates are 2018/1/9.

**Comment by haidangbosco** [comment]
Same issue with miktex 2.9 and win1064bit

**Comment by DawnGnius** [comment]
Same issue with miktex 2.9.6630 and win10 64bit.
typing in powershell(admin): 
`    mpm.exe --admin --set-repository="http://mirrors.zju.edu.cn/CTAN/systems/win32/miktex/tm/packages/"`

URL is chosen randomly, and it seems solved.

**Comment by DrTwonky** [comment]
I noticed that the reg key in question may appear at different locations. Plz try to delete them all:

`reg delete HKLM\Software\WOW6432Node\MiKTeX.org\MiKTeX\2.9\MPM /f /v AuthTokenNotValidAfter`, 
`reg delete HKLM\Software\MiKTeX.org\MiKTeX\2.9\MPM /f /v AuthTokenNotValidAfter`, 
`reg delete HKLM\Software\MiKTeX.org\MiKTeX\2.9\MPM /f /v AuthTokenNotValidAfter`.

**Comment by jevad** [comment]
Why is this marked as closed?
