### ISSUE TITLE
texify outputs "MiKTeX encountered an internal error" when using -aux-directory with --tex-option

### ISSUE THREAD

**Issue by Herohtar** [MiKTeX/miktex#270]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am using MiKTeX on Windows 10 and am trying to specify a separate aux file directory when running `texify` by using the following command:
```
texify --pdf --engine=xetex --synctex=1 --tex-option="-aux-directory=auxfiles" .\test.tex
```

However, this command immediately fails with the following output:
```
ERROR: MiKTeX encountered an internal error.
ERROR: Info:
ERROR: Source: Libraries\MiKTeX\Core\Session/SessionImpl.h
ERROR: Line: 640

Sorry, but "MiKTeX Compiler Driver" did not succeed.
```

Running just `texify --pdf --engine=xetex --synctex=1 .\test.tex` completes with no issues, so the problem seems to be related to the `--tex-option` switch.

However, I am able to pass other options successfully, for example, `texify --pdf --engine=xetex --synctex=1 --tex-option="-interaction=nonstopmode" .\test.tex`. So it seems the issue is specifically with `--tex-option="-aux-directory=auxfiles"`.

### Report
```
Date: 2019-02-21 19:42:29
MiKTeX: 2.9.6960
OS: Windows 10 Pro, 64-bit, build 17763
SharedSetup: yes
PathOkay: yes
LastUpdateCheck: 2019-02-21 19:29:50
LastUpdate: 2019-02-21 19:35:43
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files\MiKTeX 2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```

**Comment by edocevoli** [comment]
Indeed, `TeX option "--aux-directory" is not supported.` This is by design.

Currently these TeX options are rejected:

- `aux-directory`
- `job-name`
- `output-directory`

**Comment by Herohtar** [comment]
What is the reason for those options not being supported? Could support be added? If not, perhaps the output should have a more helpful error message. Also, the documentation does not mention anything about options being restricted.
