### ISSUE TITLE
TEXMFHOME is empty on Windows

### ISSUE THREAD

**Issue by egraff** [MiKTeX/miktex#272]
After updating from version 2.9.6813 to version 2.9.6942, running
```
kpsewhich --var-value TEXMFHOME
```
no longer works on Windows. It's returning an empty value, instead of e.g. the UserInstall path.
Is this change intended?

**Comment by edocevoli** [comment]
`TEXMFHOME` should expand to the user-defined TEXMF roots including `~/texmf`.

**Comment by edocevoli** [comment]
`kpsewhich --var-value TEXMFHOME` now returns the user defined TEXMF root directories.

**Comment by egraff** [comment]
After installing the latest MiKTeX 2.9.7000 version (I have version 1.12.14 of the miktex-kpathsea-bin-x64-2.9 package, packaged on 17 March 2019), I'm still seeing the issue that TEXMFHOME is empty by default (it used to contain the user install directory `%appdata%\MiKTeX\2.9` folder where user packages are installed).

However, now it looks like TEXMFHOME will expand to any _additional_ TEXMF root directories that the user adds, if such are explicitly added.

It still causes me some headache that TEXMFHOME no longer expands to the user install directory, and is empty by default, since I have install scripts for my LaTeX packages (not published to CTAN) that try to install these into TEXMFHOME. Again, is this change intended, since it breaks previous behaviour? Alternatively, is there any other way to get hold of the user install path?

**Comment by edocevoli** [comment]
Yes, `TEXMFHOME` expands to the root directories defined by the user, i.e., it is initially empty.

The user installation directory is managed solely by the MiKTeX programs. It's location is platform dependent and there is currently no way to find it with `kpsewhich`.

**Comment by egraff** [comment]
I see, thanks for your answer!

Just to clarify, does this mean that the previous behaviour, where `kpsewhich --var-value TEXMFHOME` used to return the path to the user installation directory, was not intended?

**Comment by koppor** [comment]
To make it "compatible" to TeX Live, following command is required (using `cmd.exe`)

    initexmf --user-roots="%USERPROFILE%/texmf"

(Taken from @egraff - thank you for sharing the code)

For me, following command worked in GitHub actions:

    initexmf --user-roots="c:/texmf"
