### ISSUE TITLE
Vista not running latest miktex console or texworks

### ISSUE THREAD

**Issue by GitHubRulesOK** [MiKTeX/miktex#273]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

step-by-step reproduction instructions: 
take a portable copy of recently updated miktex to a vista 64 device running either texworks or console create failure message
confirmed that an install of 2.9.6751 will work correctly as expected (posibly later is ok)
texworks.exe 2.9.6730 works
Installed basic 2.9.6821 console works
Texworks 2.9.6840 Texworks loads OK

input files which are necessary to reproduce the bug
any attempt to run after install from miktex-portable-2.9.6942.exe (posibly earlier)
texworks.exe or miktex console.exe will not run (most others will)

your observations: command output, screenshots

**Comment by GitHubRulesOK** [comment]
Sorry git hub does not permit me to upload images from vista compatible browsers GRRR! I have enough problems getting them uploaded from Win10 unlessI  using inbuilt edge  dam nanny state of afairs.

**Comment by GitHubRulesOK** [comment]
Sorry git hub does not permit me to upload images from vista compatible browsers GRRR! I have enough problems getting them uploaded from Win10 unless I am using inbuilt edge dam nanny state of afairs.

**Comment by edocevoli** [comment]
Thank you. It seems that it is not possible to install/use MiKTeX on your Windows computer. Maybe this will be fixed in a future release.
