### ISSUE TITLE
MikTex don't creat auxiliars files, consequently don't compile [TexMaker][Windows10] 

### ISSUE THREAD

**Issue by kelvinba** [MiKTeX/miktex#277]
Dude, WTF, @MikTex and @edocevoli just close my topic not even doing any question?! WTF?! Reposting! >:(

Hello there!

I used TexMaker with MikTex in my notebook two years ago, more or less, and it was functional, I think OS was Windows 8. I passed a time without use it, now I need to use it again, so I checked for updates and updated my TexMaker for 5.0.3 and MikTex for 2.9.6942, and I don't know why my codes don't compile anymore, in fact the program isn't doing none of those auxiliaries files necessaries for compiling procedure, like .aux .bbl .blg .dvi .lof .log .lot .out .toc .synctex.gz, and finale, .pdf itself, and I'm not finding solutions for this on google, help me, please :)

In my girlfriend's notebook a code ran ok, but don't compile in mine and she sent me screens of all the process in the folder... 

[aula1.txt](https://github.com/MiKTeX/miktex/files/2948007/aula1.txt)
[estilo.txt](https://github.com/MiKTeX/miktex/files/2948008/estilo.txt)

On image 1, you see the folder with files aula1.tex and estilo.sty. on my girlfriend's notebook.
![imagem 1](https://user-images.githubusercontent.com/35895153/54065069-fe435b00-41f9-11e9-8687-24f83b7a1584.jpg)

On image 2, you see the .PDF who compiled with no problems, on my girlfriend's notebook.
![imagem 2](https://user-images.githubusercontent.com/35895153/54065070-fedbf180-41f9-11e9-8d70-4e1442334339.jpg)

On image 3, you see the folder with files aula1.tex and estilo.sty. and auxiliaries files, on my girlfriend's notebook.
![imagem 3](https://user-images.githubusercontent.com/35895153/54065071-fedbf180-41f9-11e9-90a0-0639fed9fd40.jpg)

On image 4, you see the error who appear on MY computer when I press "See PDF" button and open Acrobat Reader. The message can be translated how "There was an error opening this document. This file can not be found."
![imagem 4](https://user-images.githubusercontent.com/35895153/54065072-fedbf180-41f9-11e9-8688-960adc4cfd62.png)

On image 5, you see the folder with files aula1.tex and estilo.sty. and NONE auxiliaries files at all.
![imagem 5](https://user-images.githubusercontent.com/35895153/54065073-fedbf180-41f9-11e9-8968-37303d7fd806.png)

PLEASE, IF NEED SOMETHING ELSE, ASK ME, DON'T JUST CLOSE IT.

**Comment by edocevoli** [comment]
Thank you. I am afraid that this is not the correct place to report this issue: it's no a MiKTeX bug.

**Comment by kelvinba** [comment]
So what it is?!

**Comment by kelvinba** [comment]
Where I should post?

**Comment by edocevoli** [comment]
I don't really know. You can try the following:

1. Uninstall MiKTeX from your computer
2. Install another TeX system
3. See if this solves your problem

If this does not help:

1. Uninstall Texmaker
2. Install another TeX editor
3. See if this solves your problem

Hope this helps.
