### ISSUE TITLE
Latest GregorioTeX update did not include updated binary

### ISSUE THREAD

**Issue by rpspringuel** [MiKTeX/miktex#279]
The latest GregorioTeX update (to 5.2.0) grabbed all the TeX files (from CTAN, I assume, as I just uploaded them there a couple of days ago) but did not update the executable (it's still on 5.1.1).  The 5.2 series TeX files will not work with a 5.1 series executable.  Any time the major or minor version number changes in the GregorioTeX project, the executable must be updated as well.  We only upload such updates to CTAN during the TeX Live pretest period (which is going on now).

**Comment by edocevoli** [comment]
Thank you. The latest MiKTeX update installs version 5.2.0.
