### ISSUE TITLE
mgs: 64-bit version is included to win32 setup

### ISSUE THREAD

**Issue by spectorsky** [MiKTeX/miktex#28]
# Bug report

Recently (some weeks ago) I updated MiKTeX on PC with win32. However, dvipdfmx is loosing all eps picturea, and the reason (as I see) in 'not win32' mgs. When I try to launch mgs.exe (in miktex\bin directory) the message like 'mgs is not a valid win32 application' is popped up.

## My check list

- [yes ] latest package versions are installed
- [ yes] MiKTeX log files are attached
- [ not seen] the bug can be reproduced by anybody (necessary input files are attached)

## What I tried to do
Launch mgs.exe (in miktex\bin directory)

## What I expected to happen
Open the program window 
## What happened instead
The message like 'mgs is not a valid win32 application' is popped up.

# Request for enhancment
I think, the proper mgs.exe should be placed in win32 setup

_please remove this section if this is not a request for enhancement_

**Comment by edocevoli** [comment]
Why do you think that this is a 64-bit binary?

For comparison, here is the signature of the `mgs.exe` binary (32-bit):

    Size: 200704
    SHA-256: 463471b484efb2e2177ca50fbaa75b736c4e99308a6237b2e440e349f7a8750d

What Windows version is in use?

**Comment by spectorsky** [comment]
Yes, I think it is win64 application, see attach. Other programs run 
well, e.g. latex.exe, initexmf.exe, so on, but I haven't try all of them.
Size of mgs.exe is 200704, but I don't know how obtain the signature. 
The size is exactly as you says, so it seems to be win32, doesn't it? 
But what is about the message that it is not valid win32 application?
OS on this computer is Windows XP. I know that it is rather old system, 
but it suffices for other miktex programs, and everything worked before 
the latest update.

Thanks for trying help

**Comment by edocevoli** [comment]
But the ghostscript package hasn't been touched for a year.

By the way, the error message (not a valid win32 application) can also mean: "the program was designed for a different version of Windows".

**Comment by edocevoli** [comment]
`mgs.exe` runs on 32-bit Windows 7. So it seems to be an XP related issue.

**Comment by edocevoli** [comment]
Please note that Windows XP is not a supported platform for MiKTeX. That means: I cannot fix Windows XP specific bugs.
