### ISSUE TITLE
Biber and biblatex incompatible

### ISSUE THREAD

**Issue by kaba2** [MiKTeX/miktex#282]
Biber and biblatex versions are incompatible in the current MikTeX installation.

* Install the latest MikTeX from stratch.
* Update all packages from MikTeX console.
* Build the following trivial document:

    \documentclass[a4paper, 12pt]{article}
    \usepackage{biblatex}
    
    \begin{document}
    asdasd
    \end{document}

Result:

    Latexmk: applying rule 'biber test'...
    INFO - This is Biber 2.12
    INFO - Logfile is 'test.blg'
    INFO - Reading 'test.bcf'
    ERROR - Error: Found biblatex control file version 3.3, expected version 3.5.
    This means that your biber (2.12) and biblatex (3.7) versions are incompatible.
    See compat matrix in biblatex or biber PDF documentation.

**Comment by edocevoli** [comment]
Thank you. I cannot reproduce this with your test case.Seems that you have not really updated your installation because MiKTeX installs biblatex 3.12.

**Comment by edocevoli** [comment]
If, after updating MiKTeX, you still have a problem:

1. Please attach all log files
2. Run `initexmf --report` and attach the output.
3. Run `initexmf --report --admin` and attach the output.

**Comment by kaba2** [comment]
The problem was solved after another round of uninstalling and installing. 

Before uninstallation MikTeX console showed that biblatex package was in fact not installed at all, yet there was a biblatex.sty with version 3.7 at C:\Users\Kaba\AppData\Roaming\MiKTeX\2.9\tex\latex\biblatex, and that was being picked up (although the installation was single-user). Weird, but perhaps these were files that were somehow left from an older all-user installation.
