### ISSUE TITLE
console manager failed to start

### ISSUE THREAD

**Issue by samira91** [MiKTeX/miktex#283]
I try to open my console manager in Mike tex  , but it failed , this is the error that he show me file
"C:\MiKTeX 2.9\miktex/config\package-manifests.ini", line="194129", error="invalid value definition"

 thank you for helping

**Comment by edocevoli** [comment]
This is a known issue. Please check the issue tracker.

**Comment by edocevoli** [comment]
Duplicate of #239

**Comment by ridhima20759** [comment]
i found this error while compiling my document
file="C:\Program Files\MiKTeX 2.9\miktex/config\package-manifests.ini", line="188216", error="invalid value definition"
and line number 188216 is: pro/SourceSerifPro-ExtraLight-tosf-sc-ot1.tfm

how to deal with it please reply

**Comment by edocevoli** [comment]
Please see #290 for a possible workaround.
