### ISSUE TITLE
<< BIB file not found by BibTeX >>

### ISSUE THREAD

**Issue by icamps** [MiKTeX/miktex#286]
Hi,

Today I downloaded the latest MikTeX version for Windows (2.9.7000, 64bits), added my own folders with styles (sty, cls and bst) and bibliography database files bib in the MikTeX console AND refreshed the filename database.

Then, the `bibtex` returns that it did not find my bib file.

The structures of the added folders is:
For styles:
`D:\Camps\Latex\tex\`
with several subfolders corresponding to different styles.

For BibTeX related files:
`D:\Camps\Latex\bibtex\`
with two subfolders, for `bib` and `bst` (inside the `bst` folder are several folders grouped according the style source.

My older MikTeX installation (2.9) works ok.

Any ideas?

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Sorry, no ideas. It works for me. Since I know nothing about your MiKTeX setup, it's not possible to work on this issue. Have you read the contribution guidelines?
