### ISSUE TITLE
Portable Edition updates packages only partially

### ISSUE THREAD

**Issue by georgerbr** [MiKTeX/miktex#288]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I ran into the same issue reported on [tex.stackexchange.com](https://tex.stackexchange.com/questions/483748/miktex-updates-packages-only-partially):
_When I requested recently MiKTeX console to update my installation (portable version on Win10) I noticed that not all packages that have been updated in the package database are recognized to be updated. Latest examples are babel, fira, l3kernel._

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
