### ISSUE TITLE
A MiKTeX configuration file could not be loaded.

### ISSUE THREAD

**Issue by utopia6** [MiKTeX/miktex#290]
I get this error when I click on Update or Packages, and MiKTeX will crash if I click on Packages.

```
GENERAL MIKTEX INFORMATION
Date: 2019-04-14 16:16:01
MiKTeX: 2.9.6980
OS: Linux 4.12.14-lp150.12.48-default #1 SMP Tue Feb 12 14:01:48 UTC 2019 (268f014) x86_64
SharedSetup: no
PathOkay: yes
LastUpdateCheck: 2019-04-13 17:10:37
LastUpdate: 2019-04-13 17:10:44
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: /home/user/.miktex/texmfs/config
Root1: /home/user/.miktex/texmfs/data
Root2: /home/user/.miktex/texmfs/install
Root3: /var/lib/miktex-texmf
Root4: /var/cache/miktex-texmf
Root5: /usr/local/share/miktex-texmf
UserInstall: /home/user/.miktex/texmfs/install
UserConfig: /home/user/.miktex/texmfs/config
UserData: /home/user/.miktex/texmfs/data
CommonInstall: /usr/local/share/miktex-texmf
CommonConfig: /var/lib/miktex-texmf
CommonData: /var/cache/miktex-texmf
Invokers: .../systemd/xfsettingsd/xfce4-appfinder

ERROR DETAILS
Program: miktex-console
Source: Libraries/MiKTeX/Core/Cfg/Cfg.cpp:1058
Error: A MiKTeX configuration file could not be loaded.
Details: 
  error: invalid value definition
  file: /home/user/.miktex/texmfs/install/miktex/config/package-manifests.ini
  line: 207304
```

The error message is the same as I get from `initexmf --report` that you can see here:

```
A MiKTeX configuration file could not be loaded.
Info: error="invalid value definition", file="/home/user/.miktex/texmfs/install/miktex/config/package-manifests.ini", line="207304"
Source: Libraries/MiKTeX/Core/Cfg/Cfg.cpp
Line: 1058

Sorry, but "MiKTeX Configuration Utility" did not succeed.
```

I found package-manifests.ini and line 207304 is:
`fonts/tfm/zhmetrics/uniyou/uniyouslfa.tfm`

However, that .tfm file does not exist in the uniyou folder, which is empty. In fact, all the zhmetrics subfolders are empty.

Here are some log files, let me know if you need anything else...
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/3077441/miktex-report.txt)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/3077442/miktex-console.log)

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Seems that `package-manifests.ini` is corrupted. The line should be:

```
run[]=texmf/fonts/tfm/zhmetrics/uniyou/uniyouslfa.tfm
```

**Comment by utopia6** [comment]
Thanks for the response.

At the top of the .ini file, it says not to edit it directly. Ignoring that warning and correcting line 207304 to what you posted (and matching the style of the following lines in the file as well) fixed the issue.

I can update and install packages, everything seems fine. Thanks edocevoli!


> Seems that `package-manifests.ini` is corrupted. The line should be:
> 
> ```
> run[]=texmf/fonts/tfm/zhmetrics/uniyou/uniyouslfa.tfm
> ```

**Comment by jess848** [comment]
I have the very same problem, except for the line where the error takes place which is line="169364"

The line in the .ini file is:
run[]=texmf/fonts/tfm/impallari/quattrocento/Quattrocento-BoldItalic-tlf-t1--base.tfm

**Comment by mathphd** [comment]
ERROR DETAILS
Program: miktex-maketfm
Source: Libraries\MiKTeX\Core\Cfg\Cfg.cpp:1052
Error: A MiKTeX configuration file could not be loaded.
Details: 
  file: C:\Users\....\MiKTeX 2.9\miktex/config\package-manifests.ini
  line: 93269
  error: invalid value definition

**Comment by utopia6** [comment]
Nice degree. 300K starting, right?

**Comment by ashthespy** [comment]
Have a similar issue, but at a different line:
```
A MiKTeX configuration file could not be loaded.
file="C:\Program Files\MiKTeX 2.9\miktex/config\package-manifests.ini",
line="24521", error="invalid value definition"
```

```
────────┬────────────────────────────────────────────────────────
        │ File: .\package-manifests.ini
────────┼────────────────────────────────────────────────────────
24515   │ run[]=texmf/tex/latex/biblatex/cbx/verbose-trad2.cbx
24516   │ run[]=texmf/tex/latex/biblatex/cbx/verbose-trad3.cbx
24517   │ run[]=texmf/tex/latex/biblatex/cbx/verbose.cbx
24518   │ run[]=texmf/tex/latex/biblatex/lbx/american.lbx
24519   │ run[]=texmf/tex/latex/biblatex/lbx/australian.lbx
24520   │ run[]=texmf/tex/latex/biblatex/lbx/austrian.lbx
24521   │ runx-abnt.pdf
24522   │ doc[]=texmf/doc/latex/biblatex-abnt/README.md
24523   │ docSize=326001
24524   │ licenseType=lppl1.3c
24525   │ run[]=texmf/tex/latex/biblatex-abnt/bbx/abnt-ibid.bbx
```

What should it look like?

**Comment by evensure** [comment]
So, my problem #490 was closed but still persists. Can someone help me here, please?

**Comment by edocevoli** [comment]
Please work around by editing `package-manifests.ini`:

1. goto to the bad line
1. modify the line

**Comment by evensure** [comment]
Arbitrarily modify the affected line? If not, where can I find how it's supposed to look like?

**Comment by utopia6** [comment]
Please post lines 174940 to 174960 of your package-manifests.ini
According to your error post, line 174950 is corrupt.
Sometimes you can infer the correct structure by looking at nearby lines.

**Comment by sparkplay84** [comment]
> 
> 
> Arbitrarily modify the affected line? If not, where can I find how it's supposed to look like?

I had a problem with line number X. So I searched for the line.
 e.g. run[]=texmf/bibtex/bib/biblatex/biblatex-examples.bib
was written as biblatex-examples.bib. Once I modified it with the whole structure of run[]=texmf/bibtex/bib/biblatex/ it ran OK and I could update it.

So basically biblatex-examples.bib
becomes
run[]=texmf/bibtex/bib/biblatex/biblatex-examples.bib

Check the structure in the adjacent lines and then it should be a relatively easy fix.
Hope that helps!

**Comment by SpecialAgentF** [comment]
Hey, 
I got the same error today on a different line, but when I looked at that line in package-manifests.ini, I don't have any idea how to fix it. (So I don't know how the "correct" line should be.)

My error is at line 163175 according to the Error Report.

```
run[]=texmf/tex/latex/varwidth/varwidth.sty
run[]=texmf/tpm/packages/varwidth.tpm
runSize=14447
source[]=texmf/source/varwidth-src.tar.bz2
sourceSize=902
timePackaged=1317202002
title=A variable-width minipage
version=0.92
lain TeX). classif2 – Biological classification tables. The package defines an environment classif that simplifies the process of typesetting classification tables. dline – Double line on the left of text. drcaps – Simple dropped capitals. The package offers simple macros for dropped capitals, in a couple of forms. etiketka – Class for typesetting business-card-sized information (including business cards). flower – Typesetting lists of flower formulas. isyntax – Interactively check LaTeX file syntax. numerus – Spell numbers in Russian words. punct – Within italicized text, punctuation is still straight, this is typographically more aesthetic. qqru – Universal quotation marks, for Russian and English. It is able also to convert uniform typewriter "quotes" into left or right typographic quotes. rusnat – Bibliography style file, now deprecated. sltables – Simplified tables for LaTeX. These macros develop the concepts of the stables, which are designed to offer table macros whose use is "as simple as one might hope". Some would claim that LaTeX's built-in table specifications are as simple as one might hope, but this package offers many short-cuts and optimization of the mechanisms of tables. starfn – Stars as footnote marks. textfrac – Simple slanted fractions.
digest=8ca7b3d32cea87d607231570e2acefb2
displayName=shipunov
doc[]=texmf/doc/latex/shipunov/add2-ex.pdf
doc[]=texmf/doc/latex/shipunov/add2-ex.tex
doc[]=texmf/doc/latex/shipunov/altverse-ex-en.pdf
doc[]=texmf/doc/latex/shipunov/altverse-ex-en.tex
```

Yes, this bunch of text is line 163175. Everything from "lain TeX)." to "fractions."

I hope, someone can help me... Thanks in advance!

**Comment by evensure** [comment]
@SpecialAgentF I didn't get any help here. In the end I believe that it was a full Uninstall and new install of miktex that saved me
