### ISSUE TITLE
MikTeX portable does not update packages

### ISSUE THREAD

**Issue by tfran1971** [MiKTeX/miktex#291]
MiKTeX  (portable under WIN) console (2.9.7015) indicates 2 packages to be updated (screenshot #1). These are apparently only system files. However, according to the package database, at least 2 other packages (elegantbook, texpos) should be recognized as updatable (screenshot #2). To update the packages I have to check and sort the package list in MiKTex console and uninstall / install updatable packages "by hand". This is tedious and has been observed repeatedly during the last weeks. 

![bild](https://user-images.githubusercontent.com/49730104/56311983-83058b00-614f-11e9-9ff9-ca3c0729f0b6.PNG)

![bild2](https://user-images.githubusercontent.com/49730104/56311997-87ca3f00-614f-11e9-8301-3f94ae58d68b.PNG)

problem still exits: see file attachments

**Comment by edocevoli** [comment]
I cannot reproduce this, i.e., it is possible to fix your issue.

If you still have a problem updating MiKTeX: Please attach

1. contents of the log directory `F:\MiKTeXPortableOLD\texmfs\data\miktex\log`
2. `F:\MiKTeXPortableOLD\texmfs\install\miktex\config\mpm.ini`
3. `F:\MiKTeXPortableOLD\texmfs\install\miktex\config\package-manifests.ini`
4. `F:\MiKTeXPortableOLD\texmfs\install\miktex\config\packages.ini`

**Comment by tfran1971** [comment]
[LOGFILE.txt](https://github.com/MiKTeX/miktex/files/3121897/LOGFILE.txt)

**Comment by tfran1971** [comment]
[mpm.pdf](https://github.com/MiKTeX/miktex/files/3121937/mpm.pdf)

**Comment by tfran1971** [comment]
[mpm.txt](https://github.com/MiKTeX/miktex/files/3121970/mpm.txt)
[package-manifests.txt](https://github.com/MiKTeX/miktex/files/3121971/package-manifests.txt)
[packages.txt](https://github.com/MiKTeX/miktex/files/3121975/packages.txt)

**Comment by tfran1971** [comment]
Thanks. The problem still exists. I added the respective files in txt format.

Von: Christian Schenk
Gesendet: 19 April 2019 11:22
An: MiKTeX/miktex
Cc: tfran1971; Author
Betreff: Re: [MiKTeX/miktex] MikTeX portable does not update packages (#291)

I cannot reproduce this, i.e., it is possible to fix your issue.
If you still have a problem updating MiKTeX: Please attach
1. contents of the log directory F:\MiKTeXPortableOLD\texmfs\data\miktex\log
2. F:\MiKTeXPortableOLD\texmfs\install\miktex\config\mpm.ini
3. F:\MiKTeXPortableOLD\texmfs\install\miktex\config\package-manifests.ini
4. F:\MiKTeXPortableOLD\texmfs\install\miktex\config\packages.ini

**Comment by edocevoli** [comment]
I was now able to reproduce the problem. A fix will be made available soon.

**Comment by tfran1971** [comment]
Thanks. That is very kind of you. I was almost out of hope: Even the new installer available for download since end of May does show this behaviour.
Schöne Pfingsten
TF

Von: Christian Schenk
Gesendet: 09 June 2019 10:17
An: MiKTeX/miktex
Cc: tfran1971; Author
Betreff: Re: [MiKTeX/miktex] MikTeX portable does not update packages (#291)

I was now able to reproduce the problem. A fix will be made available soon.

**Comment by edocevoli** [comment]
With tomorrows update, a fix for the broken package handling will be available. To repair a Portable MiKTeX installation:

1. start MiKTeX Console and run the updater (this will "repair" the MiKTeX packages)
1. remove `...\texmfs\install\miktex\config\package-manifests.ini`
1. start MiKTeX Console and run the updater

This solves the issue on my system.
