### ISSUE TITLE
Why latex does not tell me which command is undefined?

### ISSUE THREAD

**Issue by evandrocoan** [MiKTeX/miktex#292]
https://tex.stackexchange.com/questions/485830/why-latex-does-not-tell-me-which-command-is-undefined?noredirect=1#comment1228734_485830

May be a duplicate of (https://github.com/MiKTeX/miktex/issues/181 Make file-line-error more talkative)?

**Comment by edocevoli** [comment]
Yes, this is a duplicate.

**Comment by edocevoli** [comment]
Duplicate of #181
