### ISSUE TITLE
Bundles old vulnerable copy of uriparser 0.8.6, please update

### ISSUE THREAD

**Issue by hartwork** [MiKTeX/miktex#293]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

----

Hi,

it came to my attention that you bundle vulnerable uriparser 0.8.6 here. Please consider updating to [version 0.9.3](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.3). Thank you!

Best, Sebastian

**Comment by edocevoli** [comment]
This will be fixed with [milestone 2.9.7050](https://github.com/MiKTeX/miktex/milestone/15).

**Comment by hartwork** [comment]
Thank you!
