### ISSUE TITLE
Yap (2.9.6914) Windows 10 issue with dvi-files having long paths and/or filenames

### ISSUE THREAD

**Issue by Tayvele** [MiKTeX/miktex#295]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

1. The issue is that if the tex-file has a sufficiently long path and name, the dvi-file will not be displayed by Yap (2.9.6914) and the report copied below accessible via a pop-up window. If the dvi-file is subject to a shorter path and name, it will display fine. In borth cases, dvips works fine for the dvi-file and the resulting ps-file displays as expected.

With the new release of Yap (2.9.6914) I receive the following report:

MiKTeX Problem Report
Message: The page could not be rendered.
Data: 
Source: Libraries\MiKTeX\Dvi\DviPage.cpp
Line: 754
MiKTeX: 2.9.7000
OS: Windows 10 Home, 64-bit, build 17763
Invokers: explorer
SystemAdmin: no
Root0: C:\Users\Anders\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Anders\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\TeX\localtexmf
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Anders\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Anders\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Anders\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

2. An example tex-file is:

\documentclass{article}
\begin{document}
\section{Report}
Just some text.
\end{document}

Run it with latex and open the dvi file.

3. initexmf --report yields:

Date: 2019-04-26 12:48:31
MiKTeX: 2.9.7000
OS: Windows 10 Home, 64-bit, build 17763
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2019-04-25 09:11:56
LastUpdateAdmin: 2019-04-25 09:19:12
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\Anders\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Anders\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\TeX\localtexmf
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Anders\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Anders\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Anders\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

4. See 2.

5. The log-file when the tex-file is called "AlwaysLookOnTheBrightSideOfLife-ASortaBiography.tex" and located in "C:\TeX\TeXDocuments\McAdam-Warne\2018.04.20-RealTimeDensityForecastingDSGEModels-McAdam.Warne-DGR\Testfolderwithlongname" is:

This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7000 64-bit) (preloaded format=latex 2019.3.21)  26 APR 2019 12:55
entering extended mode
**./AlwaysLookOnTheBrightSideOfLife-ASortaBiography.tex
(AlwaysLookOnTheBrightSideOfLife-ASortaBiography.tex
LaTeX2e <2018-12-01>
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"
File: size10.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
)
\c@part=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(AlwaysLookOnTheBrightSideOfLife-ASortaBiography.aux)
\openout1 = `AlwaysLookOnTheBrightSideOfLife-ASortaBiography.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 13.
LaTeX Font Info:    ... okay on input line 13.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 13.
LaTeX Font Info:    ... okay on input line 13.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 13.
LaTeX Font Info:    ... okay on input line 13.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 13.
LaTeX Font Info:    ... okay on input line 13.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 13.
LaTeX Font Info:    ... okay on input line 13.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 13.
LaTeX Font Info:    ... okay on input line 13.
 [1

]
(AlwaysLookOnTheBrightSideOfLife-ASortaBiography.aux) ) 
Here is how much of TeX's memory you used:
 206 strings out of 492957
 3014 string characters out of 3135885
 59124 words of memory out of 3000000
 4184 multiletter control sequences out of 15000+200000
 4245 words of font info for 16 fonts, out of 3000000 for 9000
 1141 hyphenation exceptions out of 8191
 23i,4n,18p,169b,109s stack positions out of 5000i,500n,10000p,200000b,50000s

Output written on AlwaysLookOnTheBrightSideOfLife-ASortaBiography.dvi (1 page, 
304 bytes).

**Comment by edocevoli** [comment]
I did this:

```
mkdir C:\TeX\TeXDocuments\McAdam-Warne\2018.04.20-RealTimeDensityForecastingDSGEModels-McAdam.Warne-DGR\Testfolderwithlongname

```

Copy your test file to ` C:\TeX\TeXDocuments\McAdam-Warne\2018...derwithlongname`

```
cd C:\TeX\TeXDocuments\McAdam-Warne\2018.04.20-RealTimeDensityForecastingDSGEModels-McAdam.Warne-DGR\Testfolderwithlongname
latex AlwaysLookOnTheBrightSideOfLife-ASortaBiography.tex
yap AlwaysLookOnTheBrightSideOfLife-ASortaBiography.dvi
```

No problem. Bug not reproducible.
