### ISSUE TITLE
Different epstopdf/mgs behavior on two systems

### ISSUE THREAD

**Issue by ivankokan** [MiKTeX/miktex#296]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hi, I have been trying to convert some EPS graphic files to PDF in order to resolve well-known issue of non-embedded Helvetica font within MATLAB graphic files which must be submitted to IEEE.

Running `epstopdf -n file.eps` on two different systems produced the same:
`mgs.exe -q -sDEVICE=pdfwrite -dSAFER -dAutoRotatePages=/None -sOutputFile=.\file.pdf - -c quit`
...and I expected that the PDF result will have embedded fonts (the default according to http://tug.org/epstopdf/epstopdf.html).

But, actually running `epstopdf file.eps` produced PDF with embedded fonts on my up-to-date MiKTeX 64-bit system:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7000 64-bit) (preloaded format=pdflatex 2019.4.9)
```
```
Date: 2019-04-26 13:03:27
MiKTeX: 2.9.7000
OS: Windows 10 Enterprise, 64-bit, build 16299
SharedSetup: no
LinkTargetDirectory: C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\user\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\user\AppData\Local\MiKTeX\2.9
Root2: C:\Users\user\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\user\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\user\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\user\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

```
...while it did not on friend's system (more information pending):
```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.6960) (preloaded format=pdflatex 2019.3.5)
```

(The information about pdfTeX might be indirectly related to epstopdf/MiKTeX, and I suspect the difference between 32-bit and 64-bit installation might be the root cause?)

Considering that running
`epstopdf --gsopt=-dMaxSubsetPct=100 --gsopt=-dSubsetFonts=true --gsopt=-dEmbedAllFonts=true file.eps
`
produced the embedded Helvetica, and running
`epstopdf --gsopt=-dMaxSubsetPct=100 --gsopt=-dSubsetFonts=true --gsopt=-dEmbedAllFonts=false file.eps
`
did not embed Helvetica (both on my system), I hoped that explicitly running
`epstopdf --gsopt=-dMaxSubsetPct=100 --gsopt=-dSubsetFonts=true --gsopt=-dEmbedAllFonts=true file.eps
`
on friend's system will produce embedded Helvetica. But unfortunately, it did not.

Any thoughts?

**Comment by edocevoli** [comment]
If I understand you correctly:

2.9.7000 works
2.9.6960 doesn't work

Seems like this has been fixed in the course of development.

**Comment by ivankokan** [comment]
> If I understand you correctly:
> 
> 2.9.7000 works
> 2.9.6960 doesn't work
> 
> Seems like this has been fixed in the course of development.

I do not have any proof the issue was resolved with newer version. I guess such changes must be traceable here?

**Comment by ivankokan** [comment]
Hi again.

Considering that 2.9.6960 dates in Feb 2019, and checking whole history of `epstopdf.cpp` (https://github.com/MiKTeX/miktex/commits/master/Programs/MiKTeX/epstopdf/epstopdf.cpp) I conclude that no issue-related changes were done there.

Since no explicit `-dMaxSubsetPct`, `dSubsetFonts`, `dEmbedAllFonts` were set there, there must be some difference in `mgs.exe` behavior between 2.9.6960 (32-bit) and 2.9.7000 (64-bit). Where can I find the history of its source code?

Can someone else reproduce this issue? Maybe it's not about the version, but the difference between MiKTeX 32-bit and 64-bit systems.

Kind regards, Ivan

**Comment by ivankokan** [comment]
Hi @edocevoli,

Here is the thorough analysis done on several systems.

The goal: convert the EPS file to PDF using `epstopdf` so that fonts become embedded.
Test file (rename it to `file.eps`): [file_change_extension_to_eps.pdf](https://github.com/MiKTeX/miktex/files/3139759/file_change_extension_to_eps.pdf)

Two tests:
1. the default behavior (expected to embed fonts according to `epstopdf` manual): `epstopdf file.eps --outfile="file_default.pdf"`
2. explicit request for embedding fonts: `epstopdf --gsopt=-dMaxSubsetPct=100 --gsopt=-dSubsetFonts=true --gsopt=-dEmbedAllFonts=true file.eps --outfile="file_explicit.pdf"`

### System 1
```
Date: 2019-05-02 12:41:45
MiKTeX: 2.9.7000
OS: Windows 7 Enterprise, 64-bit, Service Pack 1, build 7601
SharedSetup: no
LinkTargetDirectory: C:\Users\user1\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\user1\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\user1\AppData\Local\MiKTeX\2.9
Root2: C:\Users\user1\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\user1\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\user1\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\user1\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```
```
MD5 hash of mgs.exe:
3cfec14f477169ba5446f606bdde319a
```
Both tests were successful.

### System 2
```
Date: 2019-05-02 12:49:52
MiKTeX: 2.9.7000
OS: Windows 10 Enterprise, 64-bit, build 16299
SharedSetup: no
LinkTargetDirectory: C:\Users\user2\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\user2\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\user2\AppData\Local\MiKTeX\2.9
Root2: C:\Users\user2\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\user2\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\user2\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\user2\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```
```
MD5 hash of mgs.exe:
3cfec14f477169ba5446f606bdde319a
```
Both tests were successful.

### System 3
**before MiKTeX upgrade**
```
Date: 2019-05-02 10:06:32
MiKTeX: 2.9.6880
OS: Windows 10 Pro, 64-bit, build 17763
SharedSetup: no
PathOkay: yes
LastUpdateCheck: 2018-11-16 12:58:49
LastUpdate: not yet
SystemAdmin: no
RootPrivileges: no
Root0: C:\Users\user3\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\user3\AppData\Local\MiKTeX\2.9
Root2: C:\Users\user3\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\user3\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\user3\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\user3\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

Warning: the following problems were detected:
  1: installation is not up-to-date
```
Both tests were successful.

**after MiKTeX upgrade**
```
Date: 2019-05-02 10:11:20
MiKTeX: 2.9.7000
OS: Windows 10 Pro, 64-bit, build 17763
SharedSetup: no
LinkTargetDirectory: C:\Users\user3\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\user3\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\user3\AppData\Local\MiKTeX\2.9
Root2: C:\Users\user3\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\user3\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\user3\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\user3\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```
Both tests were successful.

### System 4
**before MiKTeX upgrade**
```
Date: 2019-05-01 13:24:08
MiKTeX: 2.9.6930
OS: Windows 7 Professional, 32-bit, Service Pack 1, build 7601
SharedSetup: yes
PathOkay: yes
LastUpdateCheck: 2019-01-06 01:31:52
LastUpdate: not yet
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files\MiKTeX 2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

Warning: the following problems were detected:
  1: installation is not up-to-date
```
```
MD5 hash of mgs.exe:
5e047e7359c7a741debab7fb4d761b0e
```
Both tests were not successful, fonts were not embedded.

**after MiKTeX upgrade**
```
Date: 2019-05-02 21:56:04
MiKTeX: 2.9.7000
OS: Windows 7 Professional, 32-bit, Service Pack 1, build 7601
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin
PathOkay: yes
LastUpdateCheckAdmin: 2019-05-02 21:55:36
LastUpdateAdmin: 2019-05-02 21:42:26
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files\MiKTeX 2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```
```
MD5 hash of mgs.exe:
5e047e7359c7a741debab7fb4d761b0e
```
Both tests were not successful, fonts were not embedded.

Considering all the above, something is fishy within 32-bit MiKTeX and I think this issue should be reopened.

Kind regards, Ivan

**Comment by ivankokan** [comment]
More information...

I tried to run `epstopdf` on System 2 using `mgs.exe` taken from System 4. As expected, I got the following error:
```
Can't load Ghostscript DLL
Can't load DLL, LoadLibrary error code 126
```

Kind regards, Ivan

**Comment by ivankokan** [comment]
Hi @edocevoli,

I tested again on System 2 (Win 10 64-bit having MiKTeX 64-bit installed) using `mgs.exe` and `mgsdll32.dll` taken from System 4 (Win 7 32-bit having MiKTeX 34-bit installed), temporarily replacing original `mgs.exe` in `C:\Users\user2\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64`.

Surprisingly, test was successful - fonts were embedded.

Please let me know if I can provide even more information in order to resolve the issue.

Kind regards, Ivan

**Comment by ivankokan** [comment]
According to the accepted answer here (https://stackoverflow.com/questions/41205112/ghostscript-stubbornly-refuses-to-embed-fonts/56004130#56004130), it actually seems that Courier, Helvetica and others should not be embedded by default. How come they get embedded by default on 64-bit system?

**Comment by ivankokan** [comment]
Hi. Based on
https://github.com/MiKTeX/miktex/issues/339#issuecomment-511202791
should #339 not be opened (or at least appropriately labeled for the future)?
