### ISSUE TITLE
MiKTex freezes

### ISSUE THREAD

**Issue by Jes3284** [MiKTeX/miktex#299]
I have encountert a problem (WIN 10 Pro), where MiKTeX after opening 20sec later freezes and doesn't do anything. For that reason also Texmaker stops working, when in use. 
After the first istallation everything worked fine, but now the programm has this bug. Even after several installations with reboots, with admin right and without, i can't get it to run. The consolelog, doesn't show anything, just that i startet the programm. Furthermore the Programm does not tell windows, that it does no longer work and it does not use more performence, it just freezes. 

[miktex-console.log](https://github.com/MiKTeX/miktex/files/3124843/miktex-console.log)

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.
You can try it again tomorrow.
