### ISSUE TITLE
Cannot install miktex 

### ISSUE THREAD

**Issue by fan22101** [MiKTeX/miktex#3]
[setup-2017-09-06-13-47.txt](https://github.com/MiKTeX/miktex/files/1282157/setup-2017-09-06-13-47.txt)

The version is 6361-x64
I attached the log file below

**Comment by edocevoli** [comment]
The actual error is logged here:

    %LOCALAPPDATA%\MiKTeX\2.9\MiKTeX\log\initexmf_admin.log

**Comment by edocevoli** [comment]
I have not enough info to work effectively on this issue.
