### ISSUE TITLE
%%~ in tex4ht.env expands to the wrong path on single user installations

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#30]
texh4ht.env contains in various places pathes like this:

           "%%~/tex4ht/bin/tex4ht.jar"

`%%~`  should  expand to the main TeXMF root (see also this old bug report: https://sourceforge.net/p/miktex/bugs/2322/). 

I have miktex installed in single user mode in D:\MiKTeX2.9, but if I run `mk4ht oolatex test.tex` on a small hello-world latex document one can see on the terminal that the script tries to find the java files in  `C:\Program Files (x86)`:

~~~~~
     System call: java -classpath "C:/Program Files (x86)/MiKTeX 2.9/tex4ht/bin/tex4ht.jar" xtpipes -i "C:/Program Files (x86)/MiKTeX 2.9/tex4ht/xtpipes/" -o test-m2.4om test-m2.tmp
Fehler: Hauptklasse xtpipes konnte nicht gefunden oder geladen werden
~~~~~

and so mk4ht fails. With a local tex4ht.env with correct path the compilation works fine. 

`initexmf --report` gives 

~~~~
UserInstall: D:\MiKTeX2.9
UserData: C:\Users\USER\AppData\Local\MiKTeX\2.9
UserConfig: C:\Users\USER\AppData\Roaming\MiKTeX\2.9
CommonInstall: C:\Program Files (x86)\MiKTeX 2.9
CommonData: C:\ProgramData\MiKTeX\2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
~~~~

**Comment by edocevoli** [comment]
With the latest update: `%%~` is now a placeholder for the main MiKTeX installation directory. I think this fixes the issue.
