### ISSUE TITLE
Can't install on Fedora 30 (hunspell-related)

### ISSUE THREAD

**Issue by RAZORXKHARA33** [MiKTeX/miktex#301]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

After upgrading to Fedora 30 today, I have found that I can't install MiKTeX from the repository. It was working fine on Fedora 29. Here's the error I get from sudo dnf install miktex:

Error: 
Problem: conflicting requests
  - nothing provides libhunspell-1.6.so.0()(64bit) needed by miktex-2.9.6800-1.fc28.x86_64
  - nothing provides libhunspell-1.6.so.0()(64bit) needed by miktex-2.9.6840-1.fc28.x86_64
  - nothing provides libhunspell-1.6.so.0()(64bit) needed by miktex-2.9.6930-1.fc28.x86_64
  - nothing provides libhunspell-1.6.so.0()(64bit) needed by miktex-2.9.6980-1.fc28.x86_64
  - nothing provides libhunspell-1.6.so.0()(64bit) needed by miktex-2.9.7000-1.fc28.x86_64

Since Fedora 30 comes with hunspell 1.7, I can't downgrade to 1.6 to install MiKTeX (because apparently, a lot of things in F30 depend on hunspell 1.7). Is anyone else having this issue? Is more information needed?

**Comment by edocevoli** [comment]
I will provide a MiKTeX package for Fedora 30.

**Comment by RAZORXKHARA33** [comment]
Alright, thanks for the quick response. I will wait patiently, then.

**Comment by edocevoli** [comment]
A fc80 RPM is now available in the new repo:

```
sudo curl -L -o /etc/yum.repos.d/miktex.repo https://miktex.org/download/fedora/30/miktex.repo
```
