### ISSUE TITLE
\usepackage[ngerman]{babel} causes fatal error "TeX capacity exceeded"

### ISSUE THREAD

**Issue by GunnerMilligan** [MiKTeX/miktex#302]
Compiling the enclosed Example.tex with the \usepackage[ngerman]{babel} directive results in a TeX capacity exceeded error:
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7000 64-bit)
entering extended mode
(ExampleWithBabel.tex
LaTeX2e <2018-12-01>
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\article.cls
"
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\size11.clo"
))
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/generic/german\ngerman
.sty" v2.5e 1998-07-08)
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\babel.st
y"
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\switch.d
ef")
*************************************
* Local config file bblopts.cfg used
*

("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/latex/arabi\bblopts.cf
g")
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/latex/babel-german\nge
rman.ldf"
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/latex/babel-german\nge
rmanb.ldf"
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\babel.de
f"
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\txtbabel
.def"))
! TeX capacity exceeded, sorry [input stack size=5000].
\@ifundefined #1->\ifcsname #1
                              \endcsname \@ifundefin@d@i \else \@ifundefin@d...
l.45 ...Init\CurrentOption{captions\CurrentOption}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on ExampleWithBabel.log.

Removing the babel-directive results in the document being generated properly:

This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7000 64-bit)
entering extended mode
(ExampleNoBabel.tex
LaTeX2e <2018-12-01>
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\article.cls
"
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/latex/base\size11.clo"
))
("C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\tex/generic/german\ngerman
.sty" v2.5e 1998-07-08)
No file ExampleNoBabel.aux.
No file ExampleNoBabel.toc.
[1{C:/Users/user/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
(ExampleNoBabel.aux) )<C:/Users/user/AppData/Local/Programs/MiKTeX 2.9/fonts
/type1/public/amsfonts/cm/cmbx12.pfb><C:/Users/user/AppData/Local/Programs/M
iKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr10.pfb><C:/Users/user/AppData/Lo
cal/Programs/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr12.pfb><C:/Users/xgws
sih/AppData/Local/Programs/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr17.pfb>
Output written on ExampleNoBabel.pdf (1 page, 44179 bytes).
Transcript written on ExampleNoBabel.log.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

[ExampleNoBabel.log](https://github.com/MiKTeX/miktex/files/3137966/ExampleNoBabel.log)
[ExampleWithBabel.log](https://github.com/MiKTeX/miktex/files/3137967/ExampleWithBabel.log)

[2019-05-02 14-07-28_initexmf.txt](https://github.com/MiKTeX/miktex/files/3137946/2019-05-02.14-07-28_initexmf.txt)

[Example.zip](https://github.com/MiKTeX/miktex/files/3137949/Example.zip)

**Comment by u-fischer** [comment]
Don't use ` \usepackage{ngerman}`. It makes " active and  breaks lot of things.

**Comment by edocevoli** [comment]
Thank you for the report. I think this is not a MiKTeX specific bug. I would recommend that you implement the workaround (see previous comment).
