### ISSUE TITLE
why does Miktex Console stop working just with one click?

### ISSUE THREAD

**Issue by cecilialiu0803** [MiKTeX/miktex#303]
why does Miktex Console stop working just with one click?

\usepackage{listings} in Texworks couldn't work, so I was trying to install the listings package manually, but the console couldn't work, can anyone tell me what's going on?

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
