### ISSUE TITLE
disable writing of auxiliary / output files to external directories

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#305]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

As I discovered by looking at an issue, `--output-directory=DIR `  and `--aux-directory=DIR` allows e.g. pdflatex to write files (and even to create folders) outside the current folder (I created by accident a folder  `C:\aux-test`). 

Is there an environment variable to disable this? I prefer if the engines can only write to the current directory and its subfolders.

**Comment by edocevoli** [comment]
If the output directory does not exist, it will be created. You can prevent this by setting the configuration value `[TeXandFriends]CreateOutputDirectory` (documented [here](https://docs.miktex.org/manual/miktex.ini.html)):

```
initexmf --set-config-value=[TeXandFriends]CreateOutputDirectory=f
```

Setting the default value to `f` would be a breaking change.

Makes it sense to restrict output to the current directory and its sub-directories? I don't think so. This invocation should be perfectly legal:

```
pdflatex --output-directory-C:\aux-test ...
```

**Comment by u-fischer** [comment]
I don't think that the default value needs to be change. Using --output-directory is (like --shell-escape) a conscious decision of the user and should normally be accepted. Also texlive handles it in a similar way. 

But I'm running so many tests with various configurations that I would feel more confortable if I knew that a forgotten --output-directory in some dialog couldn't write files outside my test folder.

**Comment by edocevoli** [comment]
If I understand you correctly, you want MiKTeX to be "paranoid" when when opening output files, e.g.:

- disallow absolute path names (except output directory)
- disallow leaving the current directory (by means of `..` in the path name)

Sounds good to me.

**Comment by edocevoli** [comment]
It seems this has been implemented already: `\immediate\openout\tempfile=../xxx.tex` results in `! I can't write on file `../xxx.tex'.` Same for an absolute path name.

**Comment by u-fischer** [comment]
\openout is not the problem. The problem is `pdflatex --output-directory=C:/some/path file` which will write to `C:\some\path`.

**Comment by edocevoli** [comment]
Sorry, but I don't get it. You mean that

```
mkdir C:\some\path
pdflatex --output-directory=C:/some/path ...
```

should succeed. But

```
if exist C:\some\path rmdir /s /q C:\some\path
pdflatex --output-directory=C:/some/path ...
```

should fail?

**Comment by u-fischer** [comment]
No, I meant that --output-directory should work like \openout: It should only write to subfolders of the current folder and not to parent folders or absolute pathes.

**Comment by edocevoli** [comment]
Okay, now I understand.

**Comment by edocevoli** [comment]
IMHO it makes no sense to restrict output to the current directory and its sub-directories.
