### ISSUE TITLE
Unable to install: process terminated due to access violation (Windows 10)

### ISSUE THREAD

**Issue by priyadarshan** [MiKTeX/miktex#306]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I had MkTeX `basic-miktex-2.9.7031-x64.exe` properly installed on Windows 10, running perfectly.

I uninstalled it and tried to install it again, and got error message:

`Process terminated due to access violation.` (see screenshot)

<img width="374" alt="basic-miktex-2 9 7031-x64_8ojUgksJVv" src="https://user-images.githubusercontent.com/1652143/57158144-ec89c880-6de2-11e9-98f1-df9f00c17b9e.png">

Antivirus was off.

I tried again with "Run as Administrator", also tried local install vs global install, all with same results.

**Comment by edocevoli** [comment]
Thank you for the report. It seems that MiKTeX is not compatible with your Windows installation. This will hopefully be fixed in a future release.
