### ISSUE TITLE
replacement for MiKTeX SDK

### ISSUE THREAD

**Issue by mgieseki** [MiKTeX/miktex#308]
As the SDK has been deprecated, will there be some kind of replacement to access the file lookup functionality or is it gone for good?

**Comment by edocevoli** [comment]
The SDK was not really platform-independent and so I have removed it from CTAN. But the COM objects and interfaces for Windows are still valid and I plan to keep them as is.

**Comment by mgieseki** [comment]
That's great news, thanks for the quick reply.
Currently, the header and C files required to access the COM objects are only available as part of the source distribution. Would it be possible to provide a small, separate archive that just contains the configured, ready-to-use files? If that's too much work and not worth the trouble, I'd just keep using the files from the former SDK archive.
