### ISSUE TITLE
Installing Miktex from source on Centos 7

### ISSUE THREAD

**Issue by wpj01** [MiKTeX/miktex#309]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by wpj01** [comment]
I am having problems building miktex from source.  Running cmake  completes successfuly  but make all   fails with the message "miktex-2.9.7000/Libraries/MiKTeX/Util/StringUtil.cpp:25:19: fatal error: codecvt: No such file or directory"

**Comment by edocevoli** [comment]
It's not possible to build MiKTeX on CentOS 7 because we require C++14.

**Comment by edocevoli** [comment]
Btw, CentOS 8 will be out soon and we will then provide an RPM for it.
