### ISSUE TITLE
Bug using the update wizard in the admin MiKteK Package Manager

### ISSUE THREAD

**Issue by idefix33** [MiKTeX/miktex#31]
# Bug report

Windows 10, MiKTeK 2.9

## My check list

- [x] latest package versions are installed
- [ ] MiKTeX log files are attached
- [x] the bug can be reproduced by anybody

## What I tried to do

I use the MiKTeK Settings (**admin**) to launch the **Update wizard** 

[![enter image description here][4]][4]
 

## What I expected to happen

I expected to have the **admin** MiKTeK Update

[![enter image description here][1]][1]

[![enter image description here][2]][2]

## What happened instead
I got the **user** MiKTeK Update

[![enter image description here][3]][4]

And the **user** package manager tell me that I have **obsolete** packages, but they are not obolete. On the other hand  the four **.dll** are in two different folders  (with exactly the same version). The one of the *user* install 

> C:\Users\Dominique\AppData\Roaming\MiKTeX\2.9\miktex\bin\x64\MiKTeX209-harfbuzz.dll

and the one of the *admin* install

> C:\Program Files\MiKTeX 2.9\miktex\bin\x64\MiKTeX209-harfbuzz.dll

I removed them anyway as user MiKTeK package Update suggested.

  [1]: https://i.stack.imgur.com/JrGXm.png
  [2]: https://i.stack.imgur.com/dilex.png
  [3]: https://i.stack.imgur.com/Pdnvd.png
  [4]: https://i.stack.imgur.com/zv1ZA.png

**Comment by idefix33** [comment]
#

**Comment by edocevoli** [comment]
Thank you, this has been fixed. You can run the updater now.

**Comment by idefix33** [comment]
Thank You. It works fine
