### ISSUE TITLE
Documentation does not mention exit codes

### ISSUE THREAD

**Issue by DrTwonky** [MiKTeX/miktex#310]
MiKTeX programs return an error code. However, this error code is not mentioned in neither the manpages nor the usage help. For using the programs in scripts, a proper documentation of exit codes would be appreciated -- if there are any besides 0 on no error and 1 on error. If not: it would certainly help to have different error codes for different problems (no access, no connection etc).

Example mpm logfile:

    INFO  pdflatex - mpm: extracting files from ltablex.tar.lzma...
    FATAL pdflatex - The executed process did not succeed.
    FATAL pdflatex - Info: fileName="C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\initexmf.exe", arguments=" --mklinks --mkmaps", exitCode="1"
    FATAL pdflatex - Source: Libraries\MiKTeX\Core\Process\Process.cpp
    FATAL pdflatex - Line: 159

Manual Reference:
https://docs.miktex.org/manual/mpm.html

**Comment by edocevoli** [comment]
Thank you. Please note that MiKTeX programs do not use exit codes to signal specific errors. 0 means: success. Any other value (usually 1) means: failure. There are currently no plans to define different error codes.

**Comment by DrTwonky** [comment]
Thanks for replying. Nevertheless, it would be nice to let the manpages mention the exit code.
