### ISSUE TITLE
MiKTeX Setup Wizard ignores --user-install in Windows 10

### ISSUE THREAD

**Issue by mverouden** [MiKTeX/miktex#312]
I am trying to set up a MiKTeX installation for Multiple Users on the same PC (OS: Windows 10), where the user installed packages get installed into a shared directory. On [MiKTeX Documentation][1] there is a description stating that the options --user-install allows specification of the installation destination for packages installed by the user.

I have tried to install in the Command Prompt as Administrator using the following:`
basic-miktex-2.9.7031-x64.exe --shared --user-install="C:\ProgramData\texmf`

The "%PROGRAMDATA%\texmf" directory (expands to "C:\ProgramData\texmf" in Windows 10) is TDS compliant, but still after installation completion the default directory for user installed packages ends up in "%APPDATA%\MiKTeX\2.9" (this expands to "C:\Users\{username}\AppData\Roaming\MiKTeX\2.9" in W10). Which means that user installed packages are not shared, but that the same package will get installed multiple times (once per user).

I would expect it to be possible to have a shared location for user installed packages. How to fix this?

[1]: https://docs.miktex.org/manual/setupwiz.html

**Comment by edocevoli** [comment]
The `--user-install` option has no effect when installing MiKTeX system-wide. Maybe we can fix it in one of the next releases.

**Comment by edocevoli** [comment]
This has been fixed: `--user-install` can be used together with `--shared`.

**Comment by mverouden** [comment]
I have tested the --user-install together with --shared on a Windows 10 netwerk at my University and it works like a charm. @edocevoli Many thanks for the quick bugfix, I am sure many system administrator are happy with this option working!

**Comment by mverouden** [comment]
Dear Christian,

The issue described in #312 seems to have returned in your release basic-miktex-2.9.7386-x64.exe.

I have reused the setupwiz.opt file containing:
`--auto-install=yes ^
--package-set=basic ^
--shared ^
--user-install="C:\ProgramData\MiKTeX\2.9"`

After installation the user installed package again end up in "C:\Users{username}\AppData\Roaming\MiKTeX\2.9".

Could you have a look at it?

Kindest regards,

**Comment by edocevoli** [comment]
Indeed, can confirm the issue.

**Comment by edocevoli** [comment]
I think this has now been fixed.

**Comment by mverouden** [comment]
Hi Christian,

I have just remotely (also @home because of COVID-19) tested it on a Wageningen University & Research Windows 10 computer with basic-miktex-2.9.7417-x64.exe and previously mention setupwiz.opt file. All is working again as expected.

Thanks for fixing this so quickly!

Keep up the good work and most of all stay safe and healthy,

Kind regards,
Maikel

**Comment by mverouden** [comment]
Dear Christian,

It seems that a regression has occured. While preparing a new installation for Wageningen University & Research I took my `setupwiz.opt` file containing:
```
--auto-install=yes ^
--package-set=basic ^
--shared ^
--user-install="C:\ProgramData\MiKTeX"
```
and tried to use it with the latest `basic-miktex-22.10-x64.exe` installer. Unfortunately, that is where the installer stops by displaying "Usage: setupwiz [OPTIONS]" plus all possible options. Can you confirm this behavior?

By specifying `basic-miktex-22.10-x64.exe --autoinstall=yes --package-set=basic --shared --user-install="C:\ProgramData\MiKTeX"` in an adminstrator console I obtain the exact same result, which would mean that the setupwiz.opt file is read correctly. Could you point me in the right direction, in case I am missing something?

I require the use of the setupwiz.opt file to be able to package MiKTeX for distribution via the Software Center in use on WURclient computers.
