### ISSUE TITLE
How to configure MikTeX for using editor to edit errors? 

### ISSUE THREAD

**Issue by cat-paw** [MiKTeX/miktex#313]
How to configure MikTeX-2019 to jump to Winedt for error corrs? 

For previous version of MikTeX I have special ini-file---editors.ini---which contains following files:

[WinEdt55]
program=C:\Program Files (x86)\WinEdt Team\WinEdt\WinEdt.exe
arguments="[Open(|%f|);SelPar(%l,8)]"

in new version file (or its contents) were ignored?

**Comment by edocevoli** [comment]
`editors.ini` just contains definitions. The actual selection of an editor happens in Yap. Alternatively, you can, set the environment variable `MIKTEX_EDITOR`.
