### ISSUE TITLE
Running 'makeglossaries' corrupts MiKTeX on Windows 10

### ISSUE THREAD

**Issue by mpilgrem** [MiKTeX/miktex#32]
I am using MiKTeX Compiler Driver 2.9.6409 (MiKTeX 2.9.6500 64-bit) on Microsoft Windows Version 10.0.16299.19 - a fresh install of MikTeX from the web site and then getting all updates.

I was trying to learn to use 'glossaries' but each time I get to the run `makeglossaries` step, that command seems to have the side effect of corrupting MiKTeX. After running `makeglossaries`, `texify` starts to generate warning dialogs that certain `.dll` are corrupt or not for Windows. Then running MiKTeX Update (Admin) seems to try to repair something but itself fails with an API error when deregistering a `*.dll` - I think it was `MiKTeX209-core.dll`. I had to uninstall and reinstall MiKTeX to get a working set up again.

**Comment by edocevoli** [comment]
Cannot reproduce this. My test:

    C:> makeglossaries
    makeglossaries: Need exactly one file argument.
    Use `makeglossaries --help' for help.

No corruption of the MiKTeX setup.

**Comment by mpilgrem** [comment]
Apologies @edocevoli, I was genuinely experiencing this repeatedly last night but tonight I cannot reproduce it either. I can't explain it.
