### ISSUE TITLE
script path for dviasm.py is wrong

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#320]
- [x] I have read the [MiKTeX Contributing Guidelines]

According to scripts.ini dviasm.py is in pythontex:

~~~~
dviasm=scripts/pythontex/dviasm.py
~~~~

But actually it is in `scripts/dviasm/dviasm.py`, and so it isn't found by the wrapper.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
