### ISSUE TITLE
Broken download links

### ISSUE THREAD

**Issue by jeroen** [MiKTeX/miktex#321]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

The hyperlink to the basic installer on the [download page](https://miktex.org/download) is 404 because it hasn't been updated yet for the 7079 build. Also that download page is missing the link to the x64 installer.

Also I was wondering if there is a symlink or redirect to always get the latest version of the installer? I'm automatically downloading and installing miktex in an appveyor script, and it is a bit annoying the link breaks for every minor release.

**Comment by edocevoli** [comment]
Thank you! I have fixed it.

It should be possible to provide a URL to the latest basic installer. Have to investigate...

**Comment by jeroen** [comment]
Thanks. Once you have a `basic-miktex-latest.exe` url, you can use it yourself in the website so you don't have to update the website each time ;)

**Comment by edocevoli** [comment]
I have created the URL https://miktex.org/download/win/basic-miktex-x64.exe

The URL redirects (HTTP 302) to the latest installer available on CTAN.

**Comment by cmorty** [comment]
@edocevoli That was what I was looking for. You should also update https://miktex.org/download

**Comment by edocevoli** [comment]
These links are currently implemented:

- https://miktex.org/download/mac/miktex-x64.dmg
- https://miktex.org/download/win/basic-miktex-x64.exe
- https://miktex.org/download/win/miktex-portable-x86.exe
- https://miktex.org/download/win/miktexsetup-x64.zip
- https://miktex.org/download/win/setup-x64.exe

**Comment by jayvdb** [comment]
Any chance the release artifacts could also be uploaded to [GitHub releases](https://github.com/MiKTeX/miktex/releases), so it is easy to get pre-built versions of older releases?
