### ISSUE TITLE
(pdf)Latex Compile Problem based on last Miktex

### ISSUE THREAD

**Issue by abuech2s** [MiKTeX/miktex#323]
Hello,

Two years ago i wrote my master thesis in Latex. It worked perfectly. Now, i have reinstalled MikTex (and Texniccenter) and tried to build the pdf file (1) with Texniccenter and (2) based on the console. Both crashed and i dont know why. Usualy it was very simple to install Miktex and let it run.

Texniccenter says:
Sorry, but ...\pdflatex.exe did not succeed.
The log file hopefully contains the information to get MiKTex going again: C:\ ...log\pdflatex.log
I couln't open file name "Masterthesis.aux"

Then i tried to compile it on console.
I have added the output file from pdflatex (plotte into output.txt), the miktex-latex-log and the pdflatex-log.
[latex.log](https://github.com/MiKTeX/miktex/files/3231489/latex.log)
[output.txt](https://github.com/MiKTeX/miktex/files/3231485/output.txt)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/3231554/pdflatex.log)

latex.log / pdflatex.log have FATAL information based on a header files.
The output.txt says, that the png file is missing, but it is still in the same directory of the tex-file. 

I am completely wondering, why this happens, because i did not change anything compared to two years ago.

Thanks a lot
Alex

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
You haven't attached an [MWE](https://en.wikipedia.org/wiki/Minimal_working_example).

**Comment by abuech2s** [comment]
[example.zip](https://github.com/MiKTeX/miktex/files/3231957/example.zip)

Sorry, attached a minimal example. Just including a graphic.

**Comment by edocevoli** [comment]
Thank you. Running `pdflatex Masterthesis.tex` gives

```
! Illegal unit of measure (pt inserted).
<to be read again>
                   \relax
l.31   \includegraphics[width=1.0]{image.png}
```

Please fix your LateX document.

**Comment by abuech2s** [comment]
Mmmmh.. thats strange, because i will not get this message and even with [width=100pt] i will still get my old message, that the image was not found.


![screenshot](https://user-images.githubusercontent.com/44176089/58552692-52674580-8213-11e9-8685-ed1639ded435.png)

[example.zip](https://github.com/MiKTeX/miktex/files/3232142/example.zip)

**Comment by edocevoli** [comment]
That's not strange because your original version of `Masterthesis.tex` has line 31:

```
 \includegraphics[width=1.0]{image.png}
```

Running `pdflatex` on your latest version, I get a PDF. No problems detected.

[Masterthesis.pdf](https://github.com/MiKTeX/miktex/files/3232330/Masterthesis.pdf)
[Masterthesis.log](https://github.com/MiKTeX/miktex/files/3232334/Masterthesis.log)

**Comment by abuech2s** [comment]
Yeah, this is the point. Based on the screenshot, where i put width=100pt, i still get the same message (image was not found)

**Comment by abuech2s** [comment]
I think i found the problem: At the WIndows-Defender Security Options, the option "Controlled Folder Access" was activated. This blocked any writing operation from any program (Texniccenter, pdflatex, etc.). After i deactivate this, i reinstalled MikTex and Texniccenter and everything worked fine again.
