### ISSUE TITLE
MikTex-texworks crashs

### ISSUE THREAD

**Issue by abuech2s** [MiKTeX/miktex#324]
I opened TexWorks, tried to save just an empty file. The application closes itself, while clicking on "Save as" / "Speichern unter". Windows registered this crash based on miktex-texworks.exe or qwindows.dll

Attached you will find the entries of these events from windows.
[texworks.zip](https://github.com/MiKTeX/miktex/files/3232018/texworks.zip)

Best regards.
Alex

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you. I tried to reproduce this:

1. Start TeXworks
2. Press <kbd>Ctrl</kbd>+<kbd>N</kbd> to create a new document
3. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> and then <kbd>Enter</kbd> to save the file as `untitled-1.tex`

No problems observed.

**Comment by abuech2s** [comment]
While using the shortkeys, i see a Error information and the path to a log file. Both are attached.
![texworkserror](https://user-images.githubusercontent.com/44176089/58552903-d5889b80-8213-11e9-8a5e-ad36da0c4785.png)

[texworks.log](https://github.com/MiKTeX/miktex/files/3232154/texworks.log)

**Comment by edocevoli** [comment]
It seems that TeXworks is not allowed the `My Documents` folder.

**Comment by abuech2s** [comment]
Comment from #323 solves this problem for Texworks as well.
