### ISSUE TITLE
MikTeX installer kill PATH on Windows

### ISSUE THREAD

**Issue by spirritus** [MiKTeX/miktex#325]
The lates MiKTeX (downloaded 27.05.2019) kills the PATH variable on Windows (7).
MiKTeX was the only programm I installed. It added itself to the path (good) but deleted everything after itself (bad). 

Example
Path was before install:
PATH=dir1;miktexdir;dir2;dir3.... (it was a long path variable)

After install
PATH=dir1;miktexdir NOTHING

This is at least impolite of the installer ... took two ours to try to figure out why suddenly the system was beheaving differently. Please fix this.

**Comment by edocevoli** [comment]
I tried to reproduce the issue:

1. `wget https://miktex.org/download/win/basic-miktex-x64.exe`
1. `echo %PATH%> oldPATH.txt`
1. `basic-miktex-x64.exe`

After the installed exited, I opened a new command-prompt window:

1. `echo %PATH%> newPATH.txt`
1. `diff oldPATH.txt newPATH.txt`

The diff output looks okay.

**Comment by spirritus** [comment]
Yes, I did not have the same issue with other comuters.
However it did happen on one machine...
