### ISSUE TITLE
initexmf: access denied error

### ISSUE THREAD

**Issue by anapav** [MiKTeX/miktex#328]
I tried to download the current version (2.9(.7086)) of MiKTeX for Windows (64 bit). When I try to install it (no matter if only for one user or all, I tried both) it shows me the following error message:

    Windows API error 5: Access is denied. info: path="Software\MiKTeX.org\MiKTeX\2.9\Core"

The last part of the log looks as follows:

    56 [0x00003d78] INFO initexmf null - starting: MiKTeX Configuration Utility 2.9.7076 (MiKTeX 2.9.7050 64-bit)

    56 [0x00003d78] INFO initexmf null - Operating on the private (per-user) MiKTeX setup

    56 [0x00003d78] INFO initexmf null - starting with command line: initexmf "--user-install=C:\Users\anapa\AppData\Local\Programs\MiKTeX 2.9" "--common-install=C:\Program Files\MiKTeX 2.9" --set-config-value=[Core]SharedSetup=0 "--log-file=C:\Users\anapa\AppData\Local\Programs\MiKTeX 2.9\miktex/config\uninst.log" --disable-installer --verbose

    63 [0x00003d78] INFO initexmf null - Registering root directories...

    Registering root directories... 71 [0x00003d78] FATAL initexmf null - Windows API error 5: Access is denied.

    71 [0x00003d78] FATAL initexmf null - Info: path="Software\MiKTeX.org\MiKTeX\2.9\Core"

    71 [0x00003d78] FATAL initexmf null - Source: Libraries\MiKTeX\Core\win\winRegistry.cpp

    71 [0x00003d78] FATAL initexmf null - Line: 173

    Sorry, but "MiKTeX Configuration Utility" did not succeed.

    An error occurred: source file: Libraries\MiKTeX\Core\win\winRegistry.cpp source line: 173 message:    Windows API error 5: Access is denied. info: path="Software\MiKTeX.org\MiKTeX\2.9\Core" s <<< Cancel? Yes! >>>

I one had MiKTeX installed on my Laptop, unfortunately had to deinstall it after I stopped using it for a while. I did scan my Laptop for the word TeX aswell as MiK, as to delete all files from the previous installation.

I am the admin of this Laptop.

Does anyone know what the problem might be?

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Sorry, but it seems that your Windows system is not supported by the MiKTeX installer.

**Comment by anapav** [comment]
But I once previously (about half a year ago) had MiKTeX installed on this very Laptop. Same system. No changes to the Laptop or operating system were made.

**Comment by jlefeaux** [comment]
I'm having the exact same problem.  And I also previously had MikTeX installed on my machine (which is running Windows 10, a supported system for MikTeX per [https://miktex.org/kb/prerequisites](https://miktex.org/kb/prerequisites))

**Comment by anirudhjayaraman** [comment]
> I tried to download the current version (2.9(.7086)) of MiKTeX for Windows (64 bit). When I try to install it (no matter if only for one user or all, I tried both) it shows me the following error message:
> 
> ```
> Windows API error 5: Access is denied. info: path="Software\MiKTeX.org\MiKTeX\2.9\Core"
> ```
> 
> The last part of the log looks as follows:
> 
> ```
> 56 [0x00003d78] INFO initexmf null - starting: MiKTeX Configuration Utility 2.9.7076 (MiKTeX 2.9.7050 64-bit)
> 
> 56 [0x00003d78] INFO initexmf null - Operating on the private (per-user) MiKTeX setup
> 
> 56 [0x00003d78] INFO initexmf null - starting with command line: initexmf "--user-install=C:\Users\anapa\AppData\Local\Programs\MiKTeX 2.9" "--common-install=C:\Program Files\MiKTeX 2.9" --set-config-value=[Core]SharedSetup=0 "--log-file=C:\Users\anapa\AppData\Local\Programs\MiKTeX 2.9\miktex/config\uninst.log" --disable-installer --verbose
> 
> 63 [0x00003d78] INFO initexmf null - Registering root directories...
> 
> Registering root directories... 71 [0x00003d78] FATAL initexmf null - Windows API error 5: Access is denied.
> 
> 71 [0x00003d78] FATAL initexmf null - Info: path="Software\MiKTeX.org\MiKTeX\2.9\Core"
> 
> 71 [0x00003d78] FATAL initexmf null - Source: Libraries\MiKTeX\Core\win\winRegistry.cpp
> 
> 71 [0x00003d78] FATAL initexmf null - Line: 173
> 
> Sorry, but "MiKTeX Configuration Utility" did not succeed.
> 
> An error occurred: source file: Libraries\MiKTeX\Core\win\winRegistry.cpp source line: 173 message:    Windows API error 5: Access is denied. info: path="Software\MiKTeX.org\MiKTeX\2.9\Core" s <<< Cancel? Yes! >>>
> ```
> 
> I one had MiKTeX installed on my Laptop, unfortunately had to deinstall it after I stopped using it for a while. I did scan my Laptop for the word TeX aswell as MiK, as to delete all files from the previous installation.
> 
> I am the admin of this Laptop.
> 
> Does anyone know what the problem might be?
> 
> * [x]  I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Facing exactly the same issue.

**Comment by anirudhjayaraman** [comment]
> But I once previously (about half a year ago) had MiKTeX installed on this very Laptop. Same system. No changes to the Laptop or operating system were made.

Me too!

**Comment by edocevoli** [comment]
This has been fixed.

**Comment by anirudhjayaraman** [comment]
Thanks. Yes, no more issues!
