### ISSUE TITLE
metafont crash executing showit

### ISSUE THREAD

**Issue by ggrinton** [MiKTeX/miktex#33]
# Bug report

Environment: Windows 10, METAFONT, Version 2.7182818 (MiKTeX 2.9.6500 64-bit)

I invoke metafont with `mf --interaction=errorstopmode --screen`

When I use the simple command `drawdot (35,70); showit;` a blank (white) window is opened with the title "METAFONT Screen (768 x 1024)", but then I get a window to say that metafont has reported that "a problem caused the program to stop working correctly" and METAFONT terminates.

## My check list

- [X ] latest package versions are installed
- [ ] MiKTeX log files are attached
- [X] the bug can be reproduced by anybody (??)

## What I tried to do

Run a simple example from a METAFONT tutorial, using the command `drawdot (35,70); showit;`  to display in an interactive window.
The problem occurs regardless of whether the CMD window is invoked in user or administrative mode.

```
C:\Temp>mf --interaction=errorstopmode --screen
This is METAFONT, Version 2.7182818 (MiKTeX 2.9.6500 64-bit)
**\relax

*drawdot (35,70);showit;

C:\Temp>
```

## What I expected to happen

A METAFONT display screen showing one dot

## What happened instead

Blank window and a crash report. A file mfput.log is created but is empty.

Windows Application Event Log contains an error message:

> Faulting application name: mf.exe, version: 2.9.6363.0, time stamp: 0x59f5cf1c
> Faulting module name: ucrtbase.dll, version: 10.0.15063.674, time stamp: 0x8ac9f9d4
> Exception code: 0xc0000409
> Fault offset: 0x000000000007350e
> Faulting process ID: 0x3084
> Faulting application start time: 0x01d35790b7812fb2
> Faulting application path: C:\Program Files\MiKTeX 2.9\miktex\bin\x64\mf.exe
> Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
> Report ID: 2b6b8524-855c-4337-bcfb-35d2e1895ce6
> Faulting package full name: 
> Faulting package-relative application ID: 

Followed by an information message:

> Fault bucket 116472717637, type 5
> Event Name: BEX64
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: mf.exe
> P2: 2.9.6363.0
> P3: 59f5cf1c
> P4: ucrtbase.dll
> P5: 10.0.15063.674
> P6: 8ac9f9d4
> P7: 000000000007350e
> P8: c0000409
> P9: 0000000000000007
> P10:

**Comment by edocevoli** [comment]
Thank you. I can reproduce the bug.

**Comment by ggrinton** [comment]
Just digging down a level, I can see that the issue is triggered by the _openwindow_ command.  A command such as `openwindow 0 from (0,0) to (100,100) at (0,0);` will trigger the crash.

**Comment by ggrinton** [comment]
Sorry - did not mean to close!

**Comment by edocevoli** [comment]
Thank you, this has been fixed. You can run the updater now.
