### ISSUE TITLE
Error "MiKTeX cannot retrieve attributes for the directory 'C:\WINDOWS\system32\config\systemprofile'."

### ISSUE THREAD

**Issue by dnsnx** [MiKTeX/miktex#333]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I did a fresh single user install of the MiKTeX 2.9 (basic-miktex-2.9.7100-x64.exe) on my windows 10 professional system (build 1809).
When I run TeXWorks or use the commands for the console it all works fine. On the console there were in the beginning some issues with downloading packages. This I have solved by running the command multiple times. Then all required packages have been installed and in the end the PDF file has been generated successfully.

However, I need MiKTex or pdfLaTex to create PDF documents using software.
This is done using PHP, to be more precise using the "proc_open" command. With this procedure I get the following error message and don't know what to do to fix it:

> ERROR: Info: path="C:\WINDOWS\system32\config\systemprofile" ERROR: Source: Libraries\MiKTeX\Core\Directory\win\winDirectory.cpp ERROR: Line: 94
> 
> Sorry, but "D:\Program Files\MiKTeX 2.9\miktex\bin\x64\pdflatex.exe" did not succeed for the following reason:
> 
> MiKTeX cannot retrieve attributes for the directory 'C:\WINDOWS\system32\config\systemprofile'.

If I take the command to be executed and use it in the console, the generation of the PDF works without any problems.

System Information:
- PHP Version 7.0.0
- Webserver IIS 10.0
- PHP executing user: NTSYSTEM\IUSR;

Please let me know, if you need more information about the error!

**Comment by edocevoli** [comment]
This is not a MiKTeX issue.
