### ISSUE TITLE
MiKTeX install failing in future Debian 10 / buster 

### ISSUE THREAD

**Issue by nbehrnd** [MiKTeX/miktex#335]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Encouraged by the smooth installation of MiKTeX in Xubuntu 18.04.2, I attempted
an installation of MiXTeX in Debian 10, freshly installed ([weekly testing](https://cdimage.debian.org/images/unofficial/non-free/images-including-firmware/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-xfce+nonfree.iso), time stamp
2019-06-17) along the lines provided on MiKTeX's [own pages](https://miktex.org/download).  I fully acknowledge
attempting an installation in Debian 10 deliberately leaves the current scope of the
help pages which explicitly state to provide assistance for Debian 9, and not Debian 10
used by mine.  With the anticipated transition to Debian 10 / buster, however,  I think
an early indication about MiKTeX's installation difficulties there might be helpful for
its further development.

The problems rise while launching the installation of MiKTeX itself; possibly due to
the change of libraries in the repositories of Debian 10 renamed and listed below: 

```
|-------------+----------+-----------------+----------|
| requested   | status   | installed       |  version |
|-------------+----------+-----------------+----------|
| libcurl3    | renamed? | libcurl3_gnutls | 7.64.0-4 |
| libhunspell | present  | libhunspell     |  1.7.0-2 |
| libicu57    | renamed? | libicu63        |   63.1-6 |
| libmpfr4    | renamed? | libmpfr6        |  4.0.2-1 |
|-------------+----------+-----------------+----------|
```
To document my observations in additional detail, I enclose the output from the
terminal while attempting the failed installation.

md5sum about the .iso file of the Debain 10 installation used:
c97c5227a668f4fb25656fdeecfb3f29  debian-live-testing-amd64-xfce+nonfree.iso

[log_file.txt](https://github.com/MiKTeX/miktex/files/3319924/log_file.txt)

**Comment by edocevoli** [comment]
The MiKTeX package for Debian 10 has not been released yet.
