### ISSUE TITLE
Command line installation fails

### ISSUE THREAD

**Issue by Andre0376** [MiKTeX/miktex#336]
Hi everyone,

I try to create a local repository to deploy MikTex in an organisation.

I downloaded the commandline tool miktexsetup.exe, version 2.9.6942_x64.

The command line I used is:
--verbose --local-package-repository="Dir" --package-set=complete download

The error message is:
Couldn't connect to server
Data: code="7", url=https://api2.miktex.org/hello

On an different computer I also cannot reach the url.

How can I fix this error?

**Comment by edocevoli** [comment]
If you are behind a proxy, you have to tell `miktexsetup` about it. Setting the `http_proxy` environment variable should suffice:

```
http_proxy=http://your.proxy.server:port/
```

If this doesn't help: please provide more info (e.g., log files).

**Comment by Andre0376** [comment]
I'm sorry. It does not help. Error is the same.

I used http_proxy=http://[proxy-ip]:[proxy-port] and https_proxy=https://[proxy-ip]:[proxy-port] as system variables.

And if I click the link above the result is "Bad request."

All Log files I found got no content.

**Comment by edocevoli** [comment]
I have tried it on my Win10 system:

```
miktexsetup.exe --verbose --local-package-repository=C:\removeme --package-set=complete download
```

This is the beginning of the console output:

```
initializing setup service...
starting downloader...
starting download...
repository: https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/
download directory: C:\removeme
visiting repository https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/...
repository type: remote package repository
loading package repository manifest...
downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
0.19 MB, 6.36 Mbit/s
package repository digest: d5893be414fcfba0b32806acafa9b01d
going to download 3376341905 bytes
downloading package database...
downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
0.19 MB, 44.37 Mbit/s
downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma...
1.04 MB, 72.84 Mbit/s
downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/moreenum.tar.lzma (expecting 224746 bytes)...
0.22 MB, 40.86 Mbit/s
```

**Comment by Andre0376** [comment]
What version is your miktexsetup.exe?

My version is: 2.9.6942 MiKTeX Setup Utility (Standalone) 2.9.6942 (MiKTeX 2.9.6930 64-bit)

I attached two screen shots to show you the errors.

Von: Christian Schenk [mailto:notifications@github.com]
Gesendet: Dienstag, 2. Juli 2019 18:22
An: MiKTeX/miktex
Cc: Schüttel, André; Author
Betreff: Re: [MiKTeX/miktex] Command line installation fails (#336)


I have tried it on my Win10 system:

miktexsetup.exe --verbose --local-package-repository=C:\removeme --package-set=complete download

This is the beginning of the console output:

initializing setup service...

starting downloader...

starting download...

repository: https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/

download directory: C:\removeme

visiting repository https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/...

repository type: remote package repository

loading package repository manifest...

downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...

0.19 MB, 6.36 Mbit/s

package repository digest: d5893be414fcfba0b32806acafa9b01d

going to download 3376341905 bytes

downloading package database...

downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...

0.19 MB, 44.37 Mbit/s

downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma...

1.04 MB, 72.84 Mbit/s

downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/moreenum.tar.lzma (expecting 224746 bytes)...

0.22 MB, 40.86 Mbit/s

**Comment by Andre0376** [comment]
Dear Mr Schenk,

is there a solution?

With kind regards

André Schüttel
IT-Department
Deutsche Zentralbücherei für Blinde (DZB)
(German Central Library for the Blind)
Gustav-Adolf-Straße 7, 04105 Leipzig Saxonia
Tel: +49 341 7113-139, Fax: +49 341 7113-125
E-Mail: andre.schuettel@dzb.de
Internet: www.dzb.de
Facebook: facebook.com/dzb.de


Von: Schüttel, André
Gesendet: Mittwoch, 3. Juli 2019 15:59
An: MiKTeX/miktex
Betreff: AW: [MiKTeX/miktex] Command line installation fails (#336)

What version is your miktexsetup.exe?

My version is: 2.9.6942 MiKTeX Setup Utility (Standalone) 2.9.6942 (MiKTeX 2.9.6930 64-bit)

I attached two screen shots to show you the errors.

Von: Christian Schenk [mailto:notifications@github.com]
Gesendet: Dienstag, 2. Juli 2019 18:22
An: MiKTeX/miktex
Cc: Schüttel, André; Author
Betreff: Re: [MiKTeX/miktex] Command line installation fails (#336)


I have tried it on my Win10 system:

miktexsetup.exe --verbose --local-package-repository=C:\removeme --package-set=complete download

This is the beginning of the console output:

initializing setup service...

starting downloader...

starting download...

repository: https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/

download directory: C:\removeme

visiting repository https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/...

repository type: remote package repository

loading package repository manifest...

downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...

0.19 MB, 6.36 Mbit/s

package repository digest: d5893be414fcfba0b32806acafa9b01d

going to download 3376341905 bytes

downloading package database...

downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...

0.19 MB, 44.37 Mbit/s

downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/miktex-zzdb3-2.9.tar.lzma...

1.04 MB, 72.84 Mbit/s

downloading https://ctan.space-pro.be/tex-archive/systems/win32/miktex/tm/packages/moreenum.tar.lzma (expecting 224746 bytes)...

0.22 MB, 40.86 Mbit/s
