### ISSUE TITLE
MikTeX Console : direkt link to open package documentation

### ISSUE THREAD

**Issue by tsfg** [MiKTeX/miktex#338]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
The package Manager could have links to the documentation of the packages. 
It would give convenient way to access the documentation of each package. 
The Package section of miktex console is the central instrument to manage packages.
The context menu accessible packet Information knows the files containing each package and has a specialized section for the documentation. It would be very nice, to open the related PDF file direct from here. Optional to open the related documentation folder.
More handy would naturally be a function to open documentation directly from the context-menu.

**Comment by edocevoli** [comment]
This has been implemented in 21.8
