### ISSUE TITLE
epstopdf/mgs does not embed fonts within "all users" installations

### ISSUE THREAD

**Issue by ivankokan** [MiKTeX/miktex#339]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hi @edocevoli,

It seems that no one has been following the updates on the Issue #296 since it was closed. So I open the new one here starting from the scratch explaining the behavior within the *latest* MiKTeX on multiple freshly set up Win 10 32-bit and 64-bit VMs, using the respective Basic Installers
![image](https://user-images.githubusercontent.com/1058211/61182718-8b2e7300-a637-11e9-82c5-b61d0beba22b.png)
![image](https://user-images.githubusercontent.com/1058211/61182720-8ff32700-a637-11e9-9dc9-95cfa95cbf4b.png)

...but installing MiKTeX differently with respect to this option:
![image](https://user-images.githubusercontent.com/1058211/61182724-b31dd680-a637-11e9-8087-703372a10926.png)

(MiKTeX was installed immediately after the installation of Windows with no other software. Also, "on the fly" installation of missing packages was disabled immediately.)

I used this dummy EPS file (change its extension from `.pdf` to `.eps`) with Courier font exported from MATLAB, and I wanted to convert it to PDF with embedded fonts using epstopdf.
[dummy.pdf](https://github.com/MiKTeX/miktex/files/3389742/dummy.pdf)

The following commands were executed on all VMs:
```
epstopdf -n dummy.eps
where epstopdf
where mgs

```
...and these are respective outputs:

1) Win 10 32-bit / MiKTeX 32-bit / "only for me"
```
mgs.exe -q -sDEVICE=pdfwrite -dSAFER -dAutoRotatePages=/None -sOutputFile=.\dummy.pdf - -c quit
C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\epstopdf.exe
C:\Users\user\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\mgs.exe
```

2) Win 10 32-bit / MiKTeX 32-bit / "all users"
```
mgs.exe -q -sDEVICE=pdfwrite -dSAFER -dAutoRotatePages=/None -sOutputFile=.\dummy.pdf - -c quit
C:\Program Files\MiKTeX 2.9\miktex\bin\epstopdf.exe
C:\Program Files\MiKTeX 2.9\miktex\bin\mgs.exe
```

3) Win 10 64-bit / MiKTeX 64-bit / "only for me"
```
mgs.exe -q -sDEVICE=pdfwrite -dSAFER -dAutoRotatePages=/None -sOutputFile=.\dummy.pdf - -c quit
C:\Users\...\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\epstopdf.exe
C:\Users\...\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\mgs.exe
```

4) Win 10 64-bit / MiKTeX 64-bit / "all users"
```
mgs.exe -q -sDEVICE=pdfwrite -dSAFER -dAutoRotatePages=/None -sOutputFile=.\dummy.pdf - -c quit
C:\Program Files\MiKTeX 2.9\miktex\bin\x64\epstopdf.exe
C:\Program Files\MiKTeX 2.9\miktex\bin\x64\mgs.exe
```

Conversion by `epstopdf dummy.eps` produced PDFs with embedded fonts for 1 and 3
[dummy_32.pdf](https://github.com/MiKTeX/miktex/files/3389771/dummy_32.pdf)
...but it did not for 2 and 4.
[dummy_32_all.pdf](https://github.com/MiKTeX/miktex/files/3389772/dummy_32_all.pdf)

It seems that the root cause of #296 was not in 32-bit vs 64-bit version, but in installation scope. (And now, looking back at the closed Issue, I realize that was really the case.)

All MiKTeX installations on 1, 2, 3 and 4 have needed `courier` package installed by default (the Courier font package).

So, the behavior is definitely not consistent.

Many people are in favor of embedding fonts by default (e.g. when resolving the embedded fonts issue for graphics generated from MATLAB to be uploaded for IEEE). Can you investigate the root causes for not embedding them on 2 and 4?

If you need more logs and information, VMs are still alive. :) Kind regards, Ivan

**Comment by edocevoli** [comment]
This bug report is very complicated. I read it but I didn't understand the problem. Totally my fault. I will come back to this issue in the future.
