### ISSUE TITLE
Access to TrueType fonts broken after update : initexmf --mkmaps issue ?

### ISSUE THREAD

**Issue by bertrand-micaux** [MiKTeX/miktex#34]
# Bug report

I daily use TrueType fonts (i.e. MS Trebuchet) with pdflatex, which I installed in my local TeXMF tree on a MikTeX distrib.
Everything ran fine until I updated MikTeX from 2.9.6350 to 2.9.6500 today.

I am on two Win64 platforms running on Win10, one with MikTeX 2.9.6350 and the other with 2.9.6500.

Details about my font config :
- config file `updmap` has been edited by `initexmf --edit-config-file=updmap` and contains `map t1trebuc.map`
- `t1trebuc.map` file is in \<LocalTeXMF>\fonts\map and contains
```
rectrebuc TrebuchetMS <trebuc.ttf <T1-WGL4.enc
rectrebucbd TrebuchetMS-Bold <trebucbd.ttf <T1-WGL4.enc
rectrebucit TrebuchetMS-Italic <trebucit.ttf <T1-WGL4.enc
rectrebucbi Trebuchet-BoldItalic <trebucbi.ttf <T1-WGL4.enc
```
- These .ttf files are in \<LocalTexMF>\fonts\truetype, but also in C:\Windows\Fonts
- There are also .afm files in \<LocalTexMF>\afm (same for .tfm and .vf).

I ran the following test file both on 2.9.6350 and 2.9.6500 :
```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\renewcommand{\sfdefault}{trebuc}

\begin{document}
  \sffamily
  Blah
\end{document}
```

## Log files
[test_trebuc [2.9.6350].log](https://github.com/MiKTeX/miktex/files/1458021/test_trebuc.2.9.6350.log)
[test_trebuc [2.9.6500].log](https://github.com/MiKTeX/miktex/files/1458023/test_trebuc.2.9.6500.log)

Differences :
- 2.9.6350 links .ttf files to my local TeX tree `<C:/Google Drive/Config/LocalTeXMF/fonts/truetype/microsoft/trebuc/trebuc.ttf>` and the pdf output is ok ;
- 2.9.6500 looks up in the Windows font dir `<C:/WINDOWS/Fonts/trebuc.ttf>` and pdflatex complains about not finding the glyphs `B`, `l`, `a`, `h`. I get small boxes in the pdf file instead.

## What I tried to do
- Refreshing MikTeX FNDB
- Checking `updmap`
- Making maps again by running `initexmf --verbose --mkmaps`.

## What I expected to happen
... the problem to be solved !

## What happened instead
Nothing changed.
I noticed that `initexmf --verbose --mkmaps` is mute on 2.9.6500 whereas a list of paths is displayed on 2.9.6350.

**Comment by edocevoli** [comment]
Running `findtexmf --show-path=.ttf` shows that the Window font directory is searched first. I think this is not so good...

**Comment by bertrand-micaux** [comment]
Indeed. I don't understand why it is different on my two computers. Can it be configured ? How ?

[MikTeX 2.9.6350]
```
>>> findtexmf --show-path=.ttf
.;
C:\Users\Bertrand\AppData\Roaming\MiKTeX\2.9\fonts\truetype//;
C:\Users\Bertrand\AppData\Local\MiKTeX\2.9\fonts\truetype//;
C:\Google Drive\Config\LocalTeXMF\fonts\truetype//;
C:\Winux\MikTex\fonts\truetype//;
C:\ProgramData\MiKTeX\2.9\fonts\truetype//;
C:\Program Files\MiKTeX 2.9\fonts\truetype//;
C:\WINDOWS\Fonts;C:\Program Files (x86)\Adobe\Acrobat Reader DC\Resource\Font
```

[MikTeX 2.9.6500]
```
>>> findtexmf --show-path=.ttf
C:\WINDOWS\Fonts;C:\Program Files (x86)\Adobe\Acrobat Reader DC\Resource\Font;
.;
C:\Users\Bertrand\AppData\Roaming\MiKTeX\2.9\fonts/truetype//;
C:\Users\Bertrand\AppData\Local\MiKTeX\2.9\fonts/truetype//;
D:\Google Drive\Config\LocalTeXMF\fonts/truetype//;
C:\Winux\MiKTeX\fonts/truetype//;C:\ProgramData\MiKTeX\2.9\fonts/truetype//;
C:\Program Files\MiKTeX 2.9\fonts/truetype//
```

**Comment by bertrand-micaux** [comment]
Your remark gave me an idea to patch my installation :
- renaming all my .ttf files in my local tree, prefixing them with `ltx` (`trebuc.ttf` -> `ltxtrebuc.ttf`),
- modifying `trebuc.map` accordingly,
- refreshing FNDB and making maps again.

This solved my problem.

My conclusions :
- `initexmf --verbose --mkmaps` still works on 2.9.6500, though silently,
- there is still that path issue for .ttf fonts.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. You can run the updater now.
