### ISSUE TITLE
Texify run in a Windows API error 2 

### ISSUE THREAD

**Issue by BTk159** [MiKTeX/miktex#340]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

```
Date: 2019-07-14 12:58:16
MiKTeX: 2.9.7050
OS: Windows 10 Home, 64-bit, build 17134
SharedSetup: no
LinkTargetDirectory: C:\miktex-portable\texmfs\install\miktex\bin\x64
PathOkay: yes
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\miktex-portable\texmfs\config
Root1: C:\miktex-portable\texmfs\data
Root2: C:\miktex-portable\texmfs\install
UserInstall: C:\miktex-portable\texmfs\install
UserConfig: C:\miktex-portable\texmfs\config
UserData: C:\miktex-portable\texmfs\data
CommonInstall: C:\miktex-portable\texmfs\install
CommonConfig: C:\miktex-portable\texmfs\config
CommonData: C:\miktex-portable\texmfs\data
```

If i try to compile a document (even an emtpy one with just documentclass and begin/end) i get the console output **Sorry, but "MiKTeX Compiler Driver" did not succeed** and a notification to check the texify log. 
Texify.log:
```
2019-07-14 12:02:49,179+0200 INFO  texify - starting with command line: C:\miktex-portable\texmfs\install\miktex\bin\x64\texify.exe --pdf --synctex=1 --clean Masterthesis.tex
2019-07-14 12:03:27,837+0200 FATAL texify - Windows API error 2: Das System kann die angegebene Datei nicht finden.

2019-07-14 12:03:27,837+0200 FATAL texify - Info: existing="C:/Users/Admin/AppData/Local/Temp/mik73/_src\Masterthesis.pdf", path="C:/Users/Admin/Documents/Studium/Master\Masterthesis.pdf"
2019-07-14 12:03:27,837+0200 FATAL texify - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
2019-07-14 12:03:27,837+0200 FATAL texify - Line: 378

```
I tried all availible installing options with Windows (Basic, Net Install, portable) installing as Admin/User for all users, only for me and compatibility modus, allways cleaned the registry after every install on two different Pcs.
I tried running pdflatex from cmd and different locations for the .tex file.
An .aux is generated but commands like documentclass etc. are missing. 
I checked all permissions, to ervery folder (even appdata) and system, my user etc have full permissions. I checked my antivirus and systemalerts for any blocked interceptions or anything and im running out of ideas how to get MiKTeX running.

[miktex-pdftex.log](https://github.com/MiKTeX/miktex/files/3389775/miktex-pdftex.log)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/3389776/miktex-report.txt)
[mkfntmap.log](https://github.com/MiKTeX/miktex/files/3389777/mkfntmap.log)
[mpmcli.log](https://github.com/MiKTeX/miktex/files/3389778/mpmcli.log)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/3389779/pdflatex.log)
[texify.log](https://github.com/MiKTeX/miktex/files/3389780/texify.log)
[texworks.log](https://github.com/MiKTeX/miktex/files/3389781/texworks.log)
[initexmf.log](https://github.com/MiKTeX/miktex/files/3389782/initexmf.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/3389783/miktex-console.log)
[miktex-fc-cache.log](https://github.com/MiKTeX/miktex/files/3389784/miktex-fc-cache.log)
[miktex-makebase.log](https://github.com/MiKTeX/miktex/files/3389785/miktex-makebase.log)
[miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/3389786/miktex-makefmt.log)
[miktex-maketfm.log](https://github.com/MiKTeX/miktex/files/3389787/miktex-maketfm.log)
[miktex-mf.log](https://github.com/MiKTeX/miktex/files/3389788/miktex-mf.log)
[Masterthesis.log.txt](https://github.com/MiKTeX/miktex/files/3389764/Masterthesis.log.txt)
[Masterthesis.tex.txt](https://github.com/MiKTeX/miktex/files/3389765/Masterthesis.tex.txt)
[Masterthesis.aux.txt](https://github.com/MiKTeX/miktex/files/3389766/Masterthesis.aux.txt)

**Comment by edocevoli** [comment]
I was not able to reproduce the bug with the given information.
