### ISSUE TITLE
Automatic updating by MikTeX?

### ISSUE THREAD

**Issue by KeesZeelenberg** [MiKTeX/miktex#342]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
There is a discussion on the LyX-mailing list about problems when using of MikTeX from within LyX under Windows 10. Some people claim that such problems may occur because MikTeX updates packages by itself (https://www.mail-archive.com/lyx-users@lists.lyx.org/msg109470.html). I have never seen this automatic updating, have said so on the LyX mailing list, but this has been dismissed. 
So just to be sure, is there any automatic updating by MikTeX?

**Comment by edocevoli** [comment]
Yes. MiKTeX installs missing packages on-the-fly. Normally it asks for permission. But you can configure the auto-installer to always install packages (no question asked).

**Comment by KeesZeelenberg** [comment]
I think, but I'm not sure, that some people suppose that MikTeX automatically _updates_ itself and the installed packages. So not only installing missing packages on the fly (when configured), but also updating  packages and executables that have already been installed previously.

**Comment by edocevoli** [comment]
Such automatic updates are currently not implemented. Maybe in the future... At the moment, the user ha to manually start the updater.

**Comment by Saxomania** [comment]
Hi, has there been any improvement in implementing automatic updates?

Our usecase: 

We deploy Miktex for a lot of devices (installpath: c:\program files\miktex) but users have no admin rights and so they cant update  themself.
