### ISSUE TITLE
Installing error MiKteX

### ISSUE THREAD

**Issue by spizk** [MiKTeX/miktex#343]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
I downloaded the basic-miktex-2.97100-x64 from the MiKteX site. I am using:

Computer: Manufacturer, Acer and Model -Aspire A315-21
Processor: AMD A4-912e RADEON R3, 4 COMPUTE CORES 2C +2G, Operating System: Windows 10 home (version 1809),1.5 GHz
Installed Memory (RAM): 8 GB (7.46 GB Usable)
System type is 64-bit operating system, x64-based processor

I set the download function to 'open when finished'.  When the wizard opened I selected run as my name (no other users). Then
Preferred paper: A4
Install missing packages on the fly: as me first

The installation was was being sent to
C:\Users\myname\AppData\Local\Programs\MiKTeX 2.9

It seems to take a long time trying to install the last component “zerohyph”

Then I get the message that the installation was unsuccessful. The final part of the log error is:
Sorry, but "MiKTeX Configuration Utility" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\myname\AppData\Local\MiKTeX\2.9\miktex\log\initexmf.log

An error occurred:
  source file: Libraries\MiKTeX\Core\win\winRegistry.cpp
  source line: 183
  message: Windows API error 5: Access is denied.
  info: valueName="UserRoots"

Now, this is the second laptop that this problem has occured. 

I'm not a programmer, and need some help please.

**Comment by edocevoli** [comment]
Thank you. I was not able to reproduce the issue on my machine. So unfortunately, I cannot help you.
