### ISSUE TITLE
packages pstricks and svg incompatible

### ISSUE THREAD

**Issue by MarcusNemes** [MiKTeX/miktex#345]
Hello,

[error.zip](https://github.com/MiKTeX/miktex/files/3438354/error.zip)
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I installed basic-miktex-2.9.7100-x64.exe on a 64bit Win7 "for all users" and updated MiKTeX by following the MiKTeX console instructions. Files are compiled in the zip archive.
The directory miktex_log contains the installation log files.
The minimum working example e.tex shows a problem when both pstricks and svg packages are used. By compiling via pdfLaTeX an "undefined control sequence" error appears. By pressing 'Enter', the pdf is generated with strange contents. The order of the \usepackage sequence is not important, one has to comment out one of the \usepackage for error-free compilation.
The pdfLaTeX output & log is also provided as e.* in the zip file.

Regards,
Marcus

**Comment by edocevoli** [comment]
This is not a MiKTeX specific bug. Please contact the package authors.
