### ISSUE TITLE
Missing MSVCP140_CODECVT_IDS.dll after updated

### ISSUE THREAD

**Issue by AndreC75** [MiKTeX/miktex#346]
This bug is reported here:
https://tex.stackexchange.com/questions/501786/be-careful-with-latest-miktex-update

**Comment by AndreC75** [comment]
reported here too : https://tex.stackexchange.com/questions/501795/msvcp140-codecvt-ids-dll-was-not-found-miktex-2-9

**Comment by edocevoli** [comment]
Thank you, will take care of this.

**Comment by edocevoli** [comment]
Windows 10: the DLL exists: `C:\Windows\System32\msvcp140_codecvt_ids.dll`

So it seems that this a problem with Windows 7.

**Comment by u-fischer** [comment]
I get the error too. 

I'm on a Window 10 pro, 1903, installed a week ago.

The dll is not in my system32 folder:

![image](https://user-images.githubusercontent.com/4047173/62004965-8e902700-b12c-11e9-9e32-b668bc623182.png)

**Comment by edocevoli** [comment]
The DLL is relatively new:

```
06/20/2019  07:06 PM            27,624 msvcp140_codecvt_ids.dll
```

**Comment by edocevoli** [comment]
The latest runtime (`vc_redist.x64.exe` can be downloaded here:

(https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)[https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads]

This will install the missing DLL in the `system32` folder.

**Comment by rumschuettel** [comment]
Is there a chance to leave the package install open and just block full repo updates? I'm trying to make a paper deadline and the submission format requires certain packages. I understand you needing to block the downloads for the bits that require this dll, but this is a bit of a showstopper currently...

**Comment by u-fischer** [comment]
Installing vc_redist.x64.exe resolved the missing dll-error for me. pdflatex and lualatex now works for me. But xelatex complains:

![image](https://user-images.githubusercontent.com/4047173/62005352-54298880-b132-11e9-84d1-e4cf5117be49.png)

Is this related or should I better open a new issue?

**Comment by u-fischer** [comment]
@rumschuettel you can probably use a local repository to install whatever is missing see 
https://tex.stackexchange.com/a/462216/2388

**Comment by edocevoli** [comment]
Executables like `xlatex.exe` are broken if the update didn't succeed. Can be fixed by running:

```
initexmf --mklinks --verbose --force
```

**Comment by u-fischer** [comment]
Ah right, I called `--mklinks` but forgot the `--force`, with it xelatex behaves again.

**Comment by LiqSolar** [comment]
> 
> 
> @rumschuettel you can probably use a local repository to install whatever is missing see
> https://tex.stackexchange.com/a/462216/2388
I tried to install the beamer using a local repository, but Miktek reported an error message:
```
Error: The operation could not be completed because a required file failed verification.
Details: 
  package: beamer
  arhiveFile: E:/dev/miktek\beamer.tar.lzma
  expectedMD5: a361300cc2f500ccd9bc8c2039bd0007
  actualMD5: 8029e83a6040db4a4282c072b5bcba50
```
I think MD5 in the database is wrong, but I don't know how to solve it.

**Comment by u-fischer** [comment]
@LiqSolar  did you downloaded the databases along with beamer.tar.lzma from the same ctan mirror?

**Comment by LiqSolar** [comment]
@u-fischer 
Thanks for reminding
the beamer package on https://mirrors-wan.geekpie.club/CTAN/systems/win32/miktex/tm/packages/ may have problems
I changed the image and the problem was solved.
