### ISSUE TITLE
MiKTeX Console Updates Error: 503

### ISSUE THREAD

**Issue by HouariZegai** [MiKTeX/miktex#347]
Hello,
- I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I'm use MIKTeX in windows and i can not update the packages, when i press the **Check for updates** button, it return an error, here is :

My computer configuration:
```
MiKTeX: 2.9
OS: Windows 7 Ultimate, 64-bit, Service Pack 1, build 7601
SharedSetup: yes
PathOkay: yes
SystemAdmin: yes
RootPrivileges: yes
Root0: C:\Users\Houari\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Houari\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Houari\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Houari\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Houari\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: 
```
Error message:
```
The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.

More info: https://miktex.org/kb/fix-503

responseCode="503"
```
PS: I tried to reinstall MIKTeX but the problem not solve.

Thank you in advance!

**Comment by u-fischer** [comment]
As the message says, the server is currently offline. See also https://miktex.org/alert/update-problem-7147 and https://github.com/MiKTeX/miktex/issues/346.

**Comment by Kompootor** [comment]
Is there an estimate to when the server will be back up? If not within the next day, can the general package repository be made available while the miktex updates are taken down for now?
