### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by DuongDuyTrong** [MiKTeX/miktex#35]
I downloaded miktek from original website miktek.org, i started to install exactly, then I received "MikTek encountered an internal error". Here is my log file
[setup-2017-11-16-11-16.log](https://github.com/MiKTeX/miktex/files/1478493/setup-2017-11-16-11-16.log)
what should I do now?

**Comment by edocevoli** [comment]
I have never seen this error before: the setup fails to create an Internet shortcut.

**Comment by edocevoli** [comment]
I cannot provide a bug fix because I cannot reproduce this bug on my development machine.
