### ISSUE TITLE
exe files missing

### ISSUE THREAD

**Issue by JoergWausW** [MiKTeX/miktex#350]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

(I can't reproduce the problem anymore, sorry, but please read on, why. Also I don't have access to the MiKTeX console, that's part of the problem - I hope this issue can be dealt with anyway...)

I wanted to run a MiKTeX-Update on my desktop PC (Windows10, 64bit), but it didn't work. A lot of the links in the windows-start list currently don't work (anymore):
- Package Manager (with and without Admin)
- MiKTeX Settings (with and without)
- MiKTeX Update (with and without Admin)
They all have a generic icon and the linked .exe-files are all missing in miktex/bin. I didn't succeed to find those filenames in any MiKTeX directory.
Also (as a side note):
- Known Issues Link delivers an empty webspace (https://miktex.org/2.9/issues)

Deinstallation using windows' control panel doesn't work, because that exe-file is missing as well.
But I can still use TeXworks and pdfLaTeX. Missing packages are being installed on the fly.

What now?

I checked on my laptop (also Windows10, 64bit). The icons were fine. I ran an update.
After the successful Update my laptop has the same issues as my desktop PC.
More details of my actions last night:
- chose the Update Link accidentally without Admin
- some options were checked, I ran it unaltered anyway. Message "not successful".
- ran the still working Update Link with Admin rights
- all options were checked, I ran it. No failure message at the end.

Result: same missing files as on my desktop PC.

Extracts from update.log (ProgrammData directory) on my desktop PC. The update.log file on my laptop looks very likely (see end of post).

`2019-06-09 09:22:27,543+0200 INFO  Update - starting: Update Wizard 2.9.6236 (MiKTeX 2.9.6210 64-bit)`
`2019-06-09 09:23:19,574+0200 INFO  FileCopyPage - starting package maintenance...`
`2019-06-09 09:23:19,575+0200 INFO  FileCopyPage - installation directory: "C:\Program Files\MiKTeX 2.9"`
`2019-06-09 09:23:19,575+0200 INFO  FileCopyPage - package repository: ftp://ftp.fernuni-hagen.de/pub/mirrors/www.ctan.org/systems/win32/miktex/tm/packages/`
`2019-06-09 09:23:19,651+0200 INFO  FileCopyPage - lightweight database digest: 2615da676d94c9829a1e774c74c779ef`
`2019-06-09 09:23:19,654+0200 INFO  FileCopyPage - going to download 160681526 bytes`
`2019-06-09 09:23:19,654+0200 INFO  FileCopyPage - going to install 4412 file(s) (142 package(s))`
`2019-06-09 09:23:19,654+0200 INFO  FileCopyPage - going to remove 26 file(s) (7 package(s))`
`2019-06-09 09:23:19,660+0200 INFO  FileCopyPage - unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core-PS.dll`
`2019-06-09 09:23:19,668+0200 INFO  FileCopyPage - unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core.dll`
`2019-06-09 09:23:19,710+0200 INFO  FileCopyPage - unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-packagemanager-PS.dll`
`2019-06-09 09:23:19,715+0200 INFO  FileCopyPage - unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-packagemanager.dll`

If you need any of the downloading and extracting-lines, please let me know (there are no version numbers of the downloaded packages to be seen).

Here the last few lines of the update.log file from the ProgramData directory.
I wonder about line 4 from the top.

`2019-06-09 10:15:00,047+0200 INFO  FileCopyPage - removing package miktex-bibarts-bin...`
`2019-06-09 10:15:00,057+0200 INFO  FileCopyPage - removing package miktex-bibarts-bin-x64...`
`2019-06-09 10:15:00,064+0200 INFO  FileCopyPage - removing package miktex-biber-bin-x64...`
`2019-06-09 10:15:00,073+0200 INFO  FileCopyPage - removing package miktex-bin-x64-2.9...`
`2019-06-09 10:15:00,080+0200 INFO  FileCopyPage - removing package miktex-int-bin-x64-2.9...`
`2019-06-09 10:15:00,087+0200 INFO  FileCopyPage - removing package miktex-lua52-bin-x64-2.9...`
`2019-06-09 10:15:00,092+0200 INFO  FileCopyPage - removing package miktex-mpm-bin-x64-2.9...`
`2019-06-09 10:15:00,106+0200 INFO  FileCopyPage - running 'mpm --register-components --verbose --admin'`
`2019-06-09 10:15:00,257+0200 INFO  FileCopyPage - Operating on the shared (system-wide) MiKTeX setup`
`2019-06-09 10:15:00,266+0200 INFO  FileCopyPage - configuring fontconfig\config\fonts.conf`
`2019-06-09 10:15:00,272+0200 INFO  FileCopyPage - registering C:\Program Files\MiKTeX 2.9\miktex\bin\x64\MiKTeX209-core.dll`
`2019-06-09 10:15:00,277+0200 INFO  FileCopyPage - registering C:\Program Files\MiKTeX 2.9\miktex\bin\x64\MiKTeX209-core-PS.dll`
`2019-06-09 10:15:00,281+0200 INFO  FileCopyPage - registering C:\Program Files\MiKTeX 2.9\miktex\bin\x64\MiKTeX209-packagemanager.dll`
`2019-06-09 10:15:00,295+0200 INFO  FileCopyPage - registering C:\Program Files\MiKTeX 2.9\miktex\bin\x64\MiKTeX209-packagemanager-PS.dll`
`2019-06-09 10:15:00,302+0200 INFO  FileCopyPage - running 'initexmf --update-fndb --verbose --admin'`
`2019-06-09 10:15:00,514+0200 INFO  FileCopyPage - Creating fndb for common root directory (C:\ProgramData\MiKTeX\2.9)...`
`2019-06-09 10:15:04,626+0200 INFO  FileCopyPage - Creating fndb for common root directory ("C:\Program Files\MiKTeX 2.9")...`
`2019-06-09 10:15:04,633+0200 INFO  FileCopyPage - running 'initexmf --force --mklinks --verbose --admin'`
`2019-06-09 10:15:06,241+0200 INFO  FileCopyPage - Creating links in target directory C:\Program Files\MiKTeX 2.9\miktex\bin\x64...`
`2019-06-09 10:15:06,247+0200 INFO  FileCopyPage - running 'initexmf --mkmaps --mklangs --verbose --admin'`
`2019-06-09 10:15:07,881+0200 INFO  FileCopyPage - Creating language.dat, language.dat.lua and language.def...`

So, what is going on?
Next thing I'll try: re-install over it, unless someone has a better idea?

Desktop PC:

`C:\WINDOWS\system32>initexmf --report --admin`
`Date: 2019-08-08 12:55:52`
`MiKTeX: 2.9.7050`
`OS: Windows 10 Home, 64-bit, build 17763`
`SharedSetup: yes`
`LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64`
`PathOkay: yes`
`LastUpdateCheckAdmin: not yet`
`LastUpdateAdmin: not yet`
`SystemAdmin: yes`
`RootPrivileges: yes`
`AdminMode: yes`
`Root0: C:\ProgramData\MiKTeX\2.9`
`Root1: C:\Program Files\MiKTeX 2.9`
`CommonInstall: C:\Program Files\MiKTeX 2.9`
`CommonConfig: C:\ProgramData\MiKTeX\2.9`
`CommonData: C:\ProgramData\MiKTeX\2.9`

`Warning: the following problems were detected:`
`  1: Never checked for system-wide updates.`

Finally, the first lines from the laptop's update.log. The bottom lines that I don't copy here again are exactly the same as above (not date and time, of course), especially the "removing bin-Package" line 4 from above.

`2019-08-08 01:18:51,432+0200 INFO  Update - starting: Update Wizard 2.9.6389 (MiKTeX 2.9.6500 64-bit)`
`2019-08-08 01:19:23,409+0200 INFO  FileCopyPage - starting package maintenance...`
`2019-08-08 01:19:23,409+0200 INFO  FileCopyPage - installation directory: "C:\Program Files\MiKTeX 2.9"`
`2019-08-08 01:19:23,409+0200 INFO  FileCopyPage - package repository: https://mirror.kumi.systems/ctan/systems/win32/miktex/tm/packages/`
`2019-08-08 01:19:23,424+0200 INFO  FileCopyPage - visiting repository https://mirror.kumi.systems/ctan/systems/win32/miktex/tm/packages/...`
`2019-08-08 01:19:23,424+0200 INFO  FileCopyPage - repository type: remote package repository`
`2019-08-08 01:19:23,424+0200 INFO  FileCopyPage - loading lightweight database...`
`2019-08-08 01:19:23,424+0200 INFO  FileCopyPage - downloading https://mirror.kumi.systems/ctan/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...`
`2019-08-08 01:19:23,674+0200 INFO  FileCopyPage - 190261 bytes, 774.17 KB/Sec`
`2019-08-08 01:19:23,830+0200 INFO  FileCopyPage - lightweight database digest: 81b25bbb52e1ad3e583edb9b2f1206ce`
`2019-08-08 01:19:23,846+0200 INFO  FileCopyPage - going to download 108615411 bytes`
`2019-08-08 01:19:23,846+0200 INFO  FileCopyPage - going to install 3956 file(s) (129 package(s))`
`2019-08-08 01:19:23,846+0200 INFO  FileCopyPage - going to remove 25 file(s) (7 package(s))`
`2019-08-08 01:19:23,846+0200 INFO  FileCopyPage - unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core-PS.dll`
`2019-08-08 01:19:23,877+0200 INFO  FileCopyPage - unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core.dll`
`2019-08-08 01:19:23,955+0200 INFO  FileCopyPage - unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-packagemanager-PS.dll`
`2019-08-08 01:19:23,971+0200 INFO  FileCopyPage - unregistering C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-packagemanager.dll`

What did I do wrong?

**Comment by edocevoli** [comment]
Thank you. It seems that you are using an outdated MiKTeX version. The update wizard is not working anymore, i.e., it is not possible to update packages (via Internet).
