### ISSUE TITLE
Issues are closed too quicky - problem not solved - What can we expect of future update wizards?

### ISSUE THREAD

**Issue by JoergWausW** [MiKTeX/miktex#351]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am sorry that I have to re-issue here, but I think my previous issue was closed too soon. I didn't have a chance to react to the given answer 

Please read this issue to the end - maybe I don't make myself clear enough because of a lack of English skills, but I'm trying. Please ask.

Today I issued issue #350.
Obvious problem is that the updating tool destroyed my MiKTeX installation it belonged to.

Answer was:

> It seems that you are using an outdated MiKTeX version. The update wizard is not working anymore, i.e., it is not possible to update packages (via Internet)

The problem was not the updating of packages. The problem is updating  the MiKTeX Core.
And, second: I didn't use a new update wizard to update an old installation. I used the update wizard that was installed along with my version (2.9, by the way), so it should be impossible to not work anymore if the rest of the installation stays the same.

As I understand, the purpose of an update wizard (of any age and version) is to install the newer MiKTeX version. My current version is 2.9, shouldn't it work for all updates of version 2.9? I'd understand if the new version was 3.x, maybe if it was a version 2.10.

An update program should be allowed to delete old exe-files under the condition (shouldn't it be obvious?) that improved exe-files are installed. I have to assume that it would do nothing if there were no replacement files. That should be checked before deleting anything - especially if it is the main core-package.

But it obviously doesn't work like that. My update wizard is gone as well as other important .exe files, even the unistall file for the windows control panel is gone.

Now I need to know:
- how do I make a clean uninstall of my destroyed MiKTeX installation? (Remember the exe-file Windows wants to use is gone) Will a re-install, or over-install work? Or will the installer fail because of the old files?
- or (that was my implicitly asked issue, too): How can I fix it?

But my new, and from my point of view very important, question:
Will any new update wizard work stable in the future?

The implication of my current experience is this:
The only safe way of updating your MiKTeX core files is to deinstall completely in time, as long as the exe-file for that is still on your computer. Then make a new installation.

Or in different words: I request to remove any update wizard completely, because they might destroy your installation anytime instead of doing what their purpose actually is. So it seems to be a useless feature.

**Comment by edocevoli** [comment]
Sorry, here is some more info:

- the update wizard of an old MiKTeX installation cannot be used to update packages
- clean uninstall: remove all MiKTeX folders and registry settings

> But my new, and from my point of view very important, question:
> Will any new update wizard work stable in the future?

Such a warranty cannot be given.
