### ISSUE TITLE
last reaction to previous answers

### ISSUE THREAD

**Issue by JoergWausW** [MiKTeX/miktex#352]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Thank you for your answer to my last issue.

Since it is obviously not expected that someone might have another question about a given answer, I seem to have to keep creating new issues. Sorry.

1) clean uninstall:

> clean uninstall: remove all MiKTeX folders and registry settings

Where do I find a list with all registry settings my MiKTeX installation ever created? Is there a cleanup-tool that works in case of a missing unistaller?

2) does an update wizard even make sense?
(I can't believe that I am the only person with my reported issue after it happened on two of my computers)

I still have a problem with your logic.

You wrote:
> the update wizard of an old MiKTeX installation cannot be used to update packages

I heard you before. But actually, the update wizard did successfully update packages like KOMA-script, amsmath. But it deleted a lot of exe-files needed to maintain the installation in the future.

Do I understand correctly?
a) core files like mo.exe or miktex-update.exe, are considered packages themselves (according to my previously quoted log file (issue #350) and your answer)
b) Explicitly, even the update wizard is a package that cannot be updated by itself (according to a) and your answer)
c) There is no other package to update the update wizard of an old installation that would be run automatically first in case the update wizard is outdated (you would have pointed it out)
d) If there is a new MiKTeX installation issued on the servers, my local installation automatically  becomes an old MiKTeX installation by definition of new version.
e) An old update wizard cannot update any packages and cannot update itself.
f) Continue loop at c)

-> conclusion/paradox (the part I have a problem with your answer)
Old update wizards cannot update anything.  If they do anyway, your given answer is wrong. 
Otherwise your answer is right. Then it is a bug if the update wizard of an updateable installation performs any update.

Wouldn't it be reasonable to have a concept like this:
- update wizard checks if it is current.
- if there is a newer version, it stops and provides a link to an update-wizard-update.exe that has to be run to update the update-wizard.
- then you run the updated update wizard that knows what to do instead of going crazy and deleting files.

Please don't get me wrong. I appreciate all the work you put into the project very much and am very grateful for it. But I assumed you care to at least try to avoid similar situations in the future. I missed that tune in the last two answers.

**Comment by u-fischer** [comment]
Hm. Looking at your issues I think you were simply missing the links in the start menu. That can happen if you update from a miktex with the old system (update manager, package manager) to a newer miktex with a miktex console (I just saw it in a old miktex from 2016 that I had to update). 

In this case simply search in the miktex/bin folder for miktex-console.exe and miktex-console_admin.exe and then create new links in the start menu for them.

**Comment by edocevoli** [comment]
Sorry that the update wizard isn't working for you. But please understand that you now have a broken MiKTeX installation. Not your fault. Unfortunately, there is no tool available to fix it, i.e., you have to do it manually. If it were my computer, I would remove the current installation by hand. Then I would install a new TeX system (can be TeX Live).

Here are the uninstall instructions (assuming standard MiKTeX installation). Open a Command Prompt as administrator and enter five commands:

```
rmdir /S /Q "C:\Program Files\MiKTEX 2.9"
rmdir /S /Q "%APPDATA%\MiKTeX"
rmdir /S /Q "%LOCALAPPDATA%\MiKTeX"
reg delete HKLM\Software\MiKTeX.org
reg delete HKCU\Software\MiKTeX.org
```

That's it.
