### ISSUE TITLE
luatex 1.10.1 has a bug affecting font usage

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#353]
with the current luatex 1.10.1 in miktex fontspec no longer activates small caps correctly. 

After some digging a bug in luatex 1.10.1 has been identified as the core of the problem. The bug is already fixed in the experimental version 1.11.X.

The whole discussion is here https://github.com/u-fischer/luaotfload/issues/80.

I would suggest to revert the luatex in miktex to 1.10.0.

**Comment by JulianPrass** [comment]
I agree with @u-fischer , the issue persists and also affects other areas such as lining of numbers, as mentioned here: https://tex.stackexchange.com/questions/504285/option-numbers-lining-not-working-any-more-with-font-constantia-after-miktek-upd 

Thank you for fixing this.

**Comment by cluelessnessness** [comment]
Another area affected, beyond those mentioned above, is the ability to access [character variants](https://tex.stackexchange.com/questions/505260/).  Thank you in advance for fixing this.

**Comment by edocevoli** [comment]
I have reverted the 1.10.1 changes, i.e., the MiKTeX console updater downgrades to the 1.10.0 executable.

Little annoyance: MiKTeX Consoles, when offering updates, shows 1.10.1 as the source (to be installed) version. After installing the updates, `luatex --version` shows that 1.10.0 has been installed.

**Comment by JulianPrass** [comment]
Dear Christian Schenk,

it works perfectly, thank you very much!


Best regards,

Julian Praß





M. Sc.
Julian Praß



Institute for Factory Automation
and Production Systems

[FAPS Logo]

Prof. Dr.-Ing. Joerg Franke
Friedrich-Alexander-University of Erlangen-Nuremberg

Fuerther Str. 246b
D-90429 Nuremberg

Phone.:
Fax:

+49 911 5302-96259<tel:+49%20911%205302-96259>
+49 911 5302-9070

julian.prass@faps.fau.de<mailto:julian.prass@faps.fau.de>
www.faps.fau.eu<http://www.faps.fau.eu/>
https://www.faps.fau.eu/person/julian-pras/


Von: Christian Schenk <notifications@github.com>
Gesendet: Sonntag, 25. August 2019 11:57
An: MiKTeX/miktex <miktex@noreply.github.com>
Cc: Praß Julian <Julian.Prass@faps.fau.de>; Comment <comment@noreply.github.com>
Betreff: Re: [MiKTeX/miktex] luatex 1.10.1 has a bug affecting font usage (#353)


I have reverted the 1.10.1 changes, i.e., the MiKTeX console updater downgrades to the 1.10.0 executable.

Little annoyance: MiKTeX Consoles, when offering updates, shows 1.10.1 as the source (to be installed) version. After installing the updates, luatex --version shows that 1.10.0 has been installed.
