### ISSUE TITLE
MiKTeX Console, macOS, uninstalling?

### ISSUE THREAD

**Issue by gregoryZajac** [MiKTeX/miktex#356]
Hello
I have been trying to install MiKTeX current version on macos 10.14.6 Mojave. Miktex Console app window opens, I can choose two options:
1) Finish private setup, I got a message: Something went wrong while finishing the MikTeX setup - The executed process did not succeed.
2) Restart as administrator and finish setup, I got a message: Sorry but something went wrong - Administrator mode cannot be enabled (makes no sense) because this is not a shared MiKTeX setup.
How to fix this or uninstall MixteX completely so I can try clean install please?

**Comment by edocevoli** [comment]
It is possible to uninstall MiKTeX as follows:

- start MiKTeX console
- cleanup / reset the TeX installation to factory defaults
- close MiKTeX console
- open launchpad and move the MiKTEX Console icon to Trash

**Comment by gregoryZajac** [comment]
The problem is that I can not do the cleanup unfortunately, when I open the MikTeX I get to Welcome page, where I need to choose: Finish Private Setup or Restart as Admin...
All other options are gray and not active, whicever oprion I choose I got an error and MikTeX Console restarts to the same point again. I have tried removing the app and installing again, still the same issue. Any ideas please?

**Comment by edocevoli** [comment]
If you haven't finished the setup process, then you don't need to clean up. Just remove the the MiKTeX Console application to get rid of MiKTeX.

**Comment by gregoryZajac** [comment]
I have removed the MiTex and tried to install again. Still the same issue. I'm sorry I was not clear perhaps, I want to keep and use MiTeX but I can not get rid of the error, thought that reinstalling may help.

**Comment by edocevoli** [comment]
Have you browsed the MiKTeX log files for errors?

**Comment by gregoryZajac** [comment]
I can not find any log file in /var/log folder, I'm not able to check the MiTeX settings as I don't have access to settings tab because of the error. What is default path for logs please? MiKTeX on MacOs.

**Comment by edocevoli** [comment]
MIKTeX stores user related files under `/Users/USER/Library/Application Support/MiKTeX/`.

**Comment by gregoryZajac** [comment]
works! sorted, thank you so much for your patience and support, much appreciate

**Comment by drewyh999** [comment]
Same problem! But I can't find a directory named  Application Support under the ~/folder
