### ISSUE TITLE
Adding TEXMF root as limited user on W10

### ISSUE THREAD

**Issue by wer1976** [MiKTeX/miktex#358]
Adding a TEXMF root as a limited user on W10 gives the following error: Windows API error 5: Access is denied. path="Software\MiKTeX.org\MiKTeX\2.9\Core"

Seems that the MiKTeX Console cannot add the MiKTeX subtree to the registry anymore. The log file shows
2019-08-28 17:49:47,956+0200 ERROR mainwindow - Libraries\MiKTeX\Core\win\winRegistry.cpp:173: Windows API error 5: Access is denied.
(path="Software\MiKTeX.org\MiKTeX\2.9\Core")

**Comment by edocevoli** [comment]
Thank you for the report. Unfortunately, it is not possible to reproduce the issue with the given information.
