### ISSUE TITLE
Wrong MiKTeX Win32 Basic Installer

### ISSUE THREAD

**Issue by anonimowy1121** [MiKTeX/miktex#359]
When MiKTeX Win32 Basic Installer (Downloads/All downloads) is run on 32-bit Windows XP, there is a message like "This program is not a proper Win32 application". While run on 64-bit Windows 7, the wizzard starts and on its title bar there is a text about 32-bit version. So it looks as if program itself was 32-bit, but installer 64-bit and that's why it doesn't work on older computers. I would be very glad if you fixed it.

**Comment by edocevoli** [comment]
Please note that Windows XP is not a supported platform.
