### ISSUE TITLE
enhance support to install packages from a list file

### ISSUE THREAD

**Issue by donovaly** [MiKTeX/miktex#36]
# Request for enhancement

MiKTeX provides the very useful feature

mpm.exe --verbose --install-some=FILE

This feature is limited because if doesn't work if a package in the list is already installed.
I use the --install-some=FILE feature for the LyX Windows installer. LyX supports/needs about 200 packages more that installed by default with the MiKTeX installer. Therefore I install them with the installer right after MiKTeX was installed.

I realized some some users have already MiKTeX installed and have e.g. 50 of the 200 packages already installed. In this case

mpm.exe --verbose --install-some=FILE

stops telling me that package xxx is already installed. In this case no packages are installed. Instead mpm should document that package xxx was already installed and jump to the next package in the list.

Another issue is if a package name in the list is misspelled. E.g. if the list contains "znmetrics" instead of "zhmetrics" there are no packages installed. mpm doesn't tell you that it could not find a package. Instead it should tell the user that it could not find a package named "znmetrics" and then jump to the next package in the list to continue the installation.

**Comment by edocevoli** [comment]
`mpm` will learn a new option which can be used to install missing packages:

    mpm --require=a0poster

Install package `a0poster` if it is not yet installed.

    mpm --require=@names.txt

The package names are read from a text file (`names.txt`).

I will not change the behavior when package names are misspelled.

**Comment by donovaly** [comment]
Many thanks!

When you finished your work in this regard a new MiKTeX installer that I can bundle with the installer for LyX would help me a lot.

> I will not change the behavior when package names are misspelled.

OK. What would be nice is to output at least the info to the logfile that package xxx was not found or something so that developers like me understand that there is just a typo.

**Comment by edocevoli** [comment]
This will be fixed with [milestone 2.9.6800](https://github.com/MiKTeX/miktex/milestone/7).

**Comment by humanoidevolador** [comment]
> 
> # Request for enhancement
> 
> MiKTeX provides the very useful feature
> 
> mpm.exe --verbose --install-some=FILE
> 
> This feature is limited because if doesn't work if a package in the list is already installed.
> I use the --install-some=FILE feature for the LyX Windows installer. LyX supports/needs about 200 packages more that installed by default with the MiKTeX installer. Therefore I install them with the installer right after MiKTeX was installed.
> 
> I realized some some users have already MiKTeX installed and have e.g. 50 of the 200 packages already installed. In this case
> 
> mpm.exe --verbose --install-some=FILE
> 
> stops telling me that package xxx is already installed. In this case no packages are installed. Instead mpm should document that package xxx was already installed and jump to the next package in the list.
> 
> Another issue is if a package name in the list is misspelled. E.g. if the list contains "znmetrics" instead of "zhmetrics" there are no packages installed. mpm doesn't tell you that it could not find a package. Instead it should tell the user that it could not find a package named "znmetrics" and then jump to the next package in the list to continue the installation.

That's awesome buddy, I'm just trying to install packets LyX is missing, instead running a 'complete' install, which occupies as much as 7GB (we don't need that whole bunch btw). One more question, does the file need to provide the package's full path in the repository or just the name suffices? should I write the names in column, comma separated or something else? 
Thanks in advance, best regards.
