### ISSUE TITLE
Win32 installer - further questions

### ISSUE THREAD

**Issue by anonimowy1121** [MiKTeX/miktex#360]
Me: When MiKTeX Win32 Basic Installer (Downloads/All downloads) is run on 32-bit Windows XP, there is a message like "This program is not a proper Win32 application". While run on 64-bit Windows 7, the wizzard starts and on its title bar there is a text about 32-bit version. So it looks as if program itself was 32-bit, but installer 64-bit and that's why it doesn't work on older computers. I would be very glad if you fixed it.

edocevoli: Please note that Windows XP is not a supported platform.

Me: So what is sense in publishing 32-bit version which does not work on 32-bit system? Does it work on newer 32-bit systems?

**Comment by edocevoli** [comment]
See https://miktex.org/kb/prerequisites-2-9

Please note that this issue tracker is for bug reports.
