### ISSUE TITLE
Rollout installation and installation Folder

### ISSUE THREAD

**Issue by mamalukes** [MiKTeX/miktex#361]
When deploying like described here https://miktex.org/howto/deploy-miktex the files end up being under C:\Users\username\AppData\Local\Programs\MiKTeX 2.9\miktex

The variable --common-install=dir doesn't seem to work.

Tried:
\\Server\miktext\miktexsetup.exe --quiet --local-package-repository=\\Server\miktext\ --package-set=basic install  --common-install=C:\miktext\

Is there any possibility to change the installation Folder with this Method?

**Comment by edocevoli** [comment]
Please see https://docs.miktex.org/manual/miktexsetup.html
