### ISSUE TITLE
SyncTeX binaries?

### ISSUE THREAD

**Issue by ashthespy** [MiKTeX/miktex#363]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Is there a reason why SyncTeX binaries are not included in MiKTeX builds? I see there are some parts at [`Programs/TeXAndFriends/synctex`](https://github.com/MiKTeX/miktex/tree/master/Programs/TeXAndFriends/synctex/source) as well as another subset as a TexWorks module.

**Comment by edocevoli** [comment]
Synctex binaries are not needed.

**Comment by ashthespy** [comment]
@edocevoli could you elaborate on that? Is it the editors job to incorporate it support in the way Texworks does it? 
Because when using alternative editors (say based on Atom or VSCode) with MiKTeX, one has to manually grab the binaries from TeX Live and add it to path.

**Comment by edocevoli** [comment]
Good point. I think we should include the binaries in a future update.

**Comment by edocevoli** [comment]
I have added `miktex-synctex.exe` (`synctex.exe` links to it).

**Comment by ashthespy** [comment]
That was quick, thanks!

**Comment by scmartin** [comment]
Sorry to revive this thread, but how do I find these binaries for use in another editor?

**Comment by edocevoli** [comment]
They should be located in the MiKTeX bin directory, side-by-side with `pdflatex`, `lualatex`, ...
