### ISSUE TITLE
handling of files with CR line ending looks faulty in pdftex

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#364]
- [x] I have read the [MiKTeX Contributing Guidelines]

This is a stripped down example of a problem with a tikz plot.

When inputing a file with pdf

tex with one line of text (e.g. `0.5660 0.6968`) which has line ending format `CR` 

~~~~
\newread\myread
\openin\myread line.txt
[line.txt](https://github.com/MiKTeX/miktex/files/3594729/line.txt)
 %cr line ending
\read \myread to \temp
\read \myread to \temp
\show\temp

\bye
~~~~

miktex shows

~~~~
> \temp=macro:
->.
~~~~

With CRLF and LF ending (and with lualatex and xelatex, and in texlive for all cases) the output is 

~~~~
> \temp=macro:
->\par .
~~~~

**Comment by edocevoli** [comment]
This has been fixed.
