### ISSUE TITLE
Updating MiKTeX errors 

### ISSUE THREAD

**Issue by dtaillie4** [MiKTeX/miktex#366]
dtaillie4- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Here is my linitexmf.log info. 
[initexmf.log](https://github.com/MiKTeX/miktex/files/3601500/initexmf.log)
I have uninistalled and re-installed MiKTeX and am now having errors updating, adding packages, basically doing anything in the console. I think it has something to do with where it is installed on my computer but I can't figure it out. Any suggestions?

**Comment by edocevoli** [comment]
I was not able to reproduce the bug with the given information. Relevant log files are missing. Not possible to work on this issue effectively...
