### ISSUE TITLE
Re-submitting MiKTeX updating error 

### ISSUE THREAD

**Issue by dtaillie4** [MiKTeX/miktex#367]
dtaillie4 - [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have attached all logs, although I don't think they will be anymore helpful than the last time I submitted an issue. I think this is an issue that is local to my computer so may not be able to be recreated, I am just looking for some advice on troubleshooting this on my Mac.  
I have tried using homebrew to clear the old MiKTeX files from my computer but it doesn't seem to have changed anything.

Just looking for any suggestions or leads 

![image](https://user-images.githubusercontent.com/42780874/64714950-89ddc300-d48d-11e9-9fe1-1a7def8e04e0.png)
[initexmf.log](https://github.com/MiKTeX/miktex/files/3601711/initexmf.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/3601712/miktex-console.log)

This is in reference to this [closed] issue:
https://github.com/MiKTeX/miktex/issues/366#issue-492306698

**Comment by edocevoli** [comment]
Sorry, but I'm sure there are more that two files in the log folder.

**Comment by dtaillie4** [comment]
![image](https://user-images.githubusercontent.com/42780874/64719530-6d925400-d496-11e9-9315-46cb943952ad.png)
[initexmf.log](https://github.com/MiKTeX/miktex/files/3601964/initexmf.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/3601965/miktex-console.log)

These are the files that github wll let me upload. It will not accept the .out file as it does not support that file type:
![image](https://user-images.githubusercontent.com/42780874/64719626-a5010080-d496-11e9-9d53-61dbb72fe05a.png)

**Comment by edocevoli** [comment]
Thank you. This looks like a serious MiKTeX bug. Unfortunately, I have no remedies at the moment. Hopefully a future MiKTeX version works better for you. Alternatively, you should consider installing another TeX system.
