### ISSUE TITLE
MiKTeX Console Package Installation Error: 500

### ISSUE THREAD

**Issue by fmamitrotta** [MiKTeX/miktex#368]
Hi,

I think this is similar to issue #267 . I use MiKTeX on Windows and I would like to install the `forest` package. So I run the MiKTeX Console as admin and when I try to install the package the following error occurs:

GENERAL MIKTEX INFORMATION
Date: 2019-09-13 12:08:07
MiKTeX: 2.9.7140
OS: Windows 10 Home, 64-bit, build 18362
SharedSetup: no
LinkTargetDirectory: C:\Users\fmami\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2019-09-06 11:45:17
LastUpdate: 2019-09-06 11:45:44
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\fmami\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\fmami\AppData\Local\MiKTeX\2.9
Root2: C:\Users\fmami\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\fmami\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\fmami\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\fmami\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: non-existing/explorer

ERROR DETAILS
Program: C:\Users\fmami\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:485
Error: Error response from server: 500
Details: 
  responseCode: 500

Are the website and update servers currently down?

Thank you in advance.

**Comment by rsaggino** [comment]
It certainly looks that way: https://miktex.org/ 

> 
502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

**Comment by fmamitrotta** [comment]
I've managed to install the package through MiKTeX console, so I would guess that at least the update servers are back online.

**Comment by TiemenSch** [comment]
Servers have been offline since yesterday I believe, no idea why :(
