### ISSUE TITLE
luatex doesn't handle commands in the name of the main file correctly

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#369]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

luatex doesn't handle commands in the name of the main file correctly

~~~~
G:\Z-Test>lualatex 5\csname @percentchar\endcsname.tex
This is LuaTeX, Version 1.10.0 (MiKTeX 2.9.7140 NEXT)
 restricted system commands enabled.
! I can't find file `5/csname'.
<*> 5/csname
          @percentchar\endcsname.tex

~~~~

pdflatex works fine:

~~~~
G:\Z-Test>pdflatex 5\csname @percentchar\endcsname.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7140 NEXT)
entering extended mode
(5%.tex
LaTeX2e <2018-12-01>
(D:\MiKTeX2.9\tex/latex/base\article.cls
~~~~

**Comment by edocevoli** [comment]
`5\csname` looks like a valid Windows file name. Both engines should do the same with it. That said, it could be a pdfTeX issue.

**Comment by u-fischer** [comment]
yes, it looks like a valid file name. But texlive handles the \csname as a command. And aren't there possible conflicts with the support of things like \input and e.g. unc-pathes which start with \?
On the whole I think I would prefer if the command line handles files name like it handles them in a document - even it means that one has to exchange \ by /.

**Comment by edocevoli** [comment]
This has been fixed.
