### ISSUE TITLE
 line endings

### ISSUE THREAD

**Issue by edocevoli** [MiKTeX/miktex#370]
> I got the complaint from CTAN that my files do not have unix line
> endings. I could install, what they call, a good zip program and zip
> my packages using that, but I don't like that, and I will easily make
> the mistake of forgetting to use the program next time. So I converted
> my dtx to unix line endings, but my sty file still gets generated with
> windows style line endings. Is there any way to configure miktex to
> generate unix style line endings when writing to a file?

**Comment by u-fischer** [comment]
Perhaps of interest for the user who reported this: When a package is prepared by l3build for ctan upload line endings are normalised automatically.

**Comment by edocevoli** [comment]
This has been fixed.
