### ISSUE TITLE
"MiKTeX Console cannot be started"

### ISSUE THREAD

**Issue by ImperatorS79** [MiKTeX/miktex#372]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

The message "MiKTeX Console cannot be started" is displayed each time I try to launch miktex-update or miktex-console. I then tried to uninstall MiKTex and install again, but I had to remove the folders manually (in Program Files, ProgramData and AppData). In the end -> same problem.

Configuration report: [initexmf_report.txt](https://github.com/MiKTeX/miktex/files/3639538/initexmf_report.txt).

I did not find any log file about this but maybe there is a directory I do not know which contains them.

**Comment by edocevoli** [comment]
Please attach all log files (create a Zip archive) . Possible directories:

```
C:\Users\<user>\AppData\Local\MiKTeX\2.9\miktex\log
C:\ProgramData\MiKTeX\2.9\miktex\log
```

**Comment by ImperatorS79** [comment]
Those directories are empty after launching miktex-console.

**Comment by edocevoli** [comment]
A possible reason for the early failure might be that MiKTeX cannot create the lock file `miktex-console.lock` in the home directory. Have you set the environment variable `HOME`? What are the values of `HOMEDRIVE` and `HOMEPATH`?

**Comment by edocevoli** [comment]
Please start [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) prior to MiKTeX Console. This should give us some more info.

**Comment by ImperatorS79** [comment]
I got 
```
[3356] Invalid stoi argument
```

**Comment by edocevoli** [comment]
Does your home directory contains `miktex-cpnsole.lock`? If so, please post the content.

**Comment by ImperatorS79** [comment]
The content is unreadable. (Bunch of "NUL" in notepad++)

**Comment by ImperatorS79** [comment]
I deleted the .lock and now it works :thinking:.

**Comment by edocevoli** [comment]
I have improved the error message.
