### ISSUE TITLE
tftopl failed with large .tfm file

### ISSUE THREAD

**Issue by RuixiZhang42** [MiKTeX/miktex#373]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am trying to convert `mt2mit.tfm` in the MathTime Pro&nbsp;2 Lite package to a property list. This file is rather large (more than 30&nbsp;KB). This TeX Font Metric file is available on [CTAN](https://www.ctan.org/tex-archive/fonts/mtp2lite) as a part of free subset, but under commercial license.

Running `tftopl mt2mit.tfm mt2mit.pl` I got the message `The file is bigger than I can handle!` I&nbsp;am using MiKTeX&nbsp;2.9.6809 on Windows&nbsp;8.

This issue was first asked on TeX.SX: [How to increase `tfm_size` while running `tftopl`?](https://tex.stackexchange.com/q/509293) However, egreg and Ulrike Fischer commented that the `tftopl` shipped with TeX&nbsp;Live does work despite having the same default configuration: `@!tfm_size=30000; {maximum length of |tfm| data, in bytes}`

**Comment by edocevoli** [comment]
TeX Live allocates TFM memory dynamically, whereas MiKTeX uses a fixed size buffer. I have increased `tfm_size` to 100000.

**Comment by edocevoli** [comment]
This has been fixed.
