### ISSUE TITLE
miktex-texworks.exe constant CPU usage

### ISSUE THREAD

**Issue by Zapeth** [MiKTeX/miktex#374]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have noticed a constant ~5% CPU usage of miktex-texworks.exe when having a single .tex file open while being idle. This also seems to stack with multiple .tex files open, consuming ~12% and more of the CPU.

I tried changing various TeXworks settings and it seems that the "Syntax coloring" in the "Preferences->Editor defaults" section is the cause of this. After setting it from "LaTeX" to "None" and restarting miktex-texworks.exe, the monitored CPU usage reports 0% when being idle, as one would expect (also for multiple files).

Interestingly it still stays at 0% when I enable Syntax coloring for the current document via "Format->Syntax coloring". Not sure why this should behave differently but I guess I'll just have to manually set the syntax coloring for each .tex file for the time being.

I am using MiKTeX 2.9.6630 (unable to upgrade for the time being due to various reasons) on Win7 x64. I haven't seen an issue like this mentioned in the changelog fixes, so I figured I'd open an issue, maybe somebody with the latest version can verify if its still present.

**Comment by edocevoli** [comment]
Thank you. Please note that this is the wrong repository for general TeXworks issues.
