### ISSUE TITLE
Error installing MiKTeX Portable using installer basic-miktex-2.9.7152-x64.exe

### ISSUE THREAD

**Issue by wtrmute** [MiKTeX/miktex#375]
Hello,

I've downloaded the installer for MiKTeX v 2.9.7152 and renamed it to `miktex-portable.exe` in order to install the distribution as portable. However, the intallation failed; the log (attached) says:

>      initexmf --rmfndb --admin --log- file=C:\Users\tiago.rodrigues\MikTeX\texmfs/install\miktex/config\uninst.log --disable-installer --verbose:
>      Option --admin only makes sense for a shared MiKTeX setup.
>
>      Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:
>
>        Option --admin only makes sense for a shared MiKTeX setup.
>      Warning: The executed process did not succeed.
>      Warning: The executed process did not succeed.
>      mpm --register-components --admin --verbose:
>
>      Sorry, but "MiKTeX Package Manager" did not succeed for the following reason:
>
>        Option --admin only makes sense for a shared MiKTeX setup.

[setup-2019-09-23-10-35.log](https://github.com/MiKTeX/miktex/files/3642432/setup-2019-09-23-10-35.log)

Here's the result of running `initexmf.exe --report` using Git Bash:

>      $ MikTeX/texmfs/install/miktex/bin/x64/initexmf.exe --report
>      initexmf: warning: Option --admin should be specified when running this program with administrator privileges
>      Date: 2019-09-23 10:57:54
>      MiKTeX: 2.9.7140
>      OS: Windows 7 Professional, 64-bit, Service Pack 1, build 7601
>      SharedSetup: no
>      LinkTargetDirectory: C:\Users\tiago.rodrigues\MikTeX\texmfs\install\miktex\bin\x64
>      PathOkay: yes
>      SystemAdmin: yes
>      RootPrivileges: yes
>      AdminMode: no
>      Root0: C:\Users\tiago.rodrigues\MikTeX\texmfs\config
>      Root1: C:\Users\tiago.rodrigues\MikTeX\texmfs\data
>      Root2: C:\Users\tiago.rodrigues\MikTeX\texmfs\install
>      UserInstall: C:\Users\tiago.rodrigues\MikTeX\texmfs\install
>      UserConfig: C:\Users\tiago.rodrigues\MikTeX\texmfs\config
>      UserData: C:\Users\tiago.rodrigues\MikTeX\texmfs\data
>      CommonInstall: C:\Users\tiago.rodrigues\MikTeX\texmfs\install
>      CommonConfig: C:\Users\tiago.rodrigues\MikTeX\texmfs\config
>      CommonData: C:\Users\tiago.rodrigues\MikTeX\texmfs\data
>
>      Warning: the following problems were detected:
>        1: Never checked for updates.
>      $ MikTeX/texmfs/install/miktex/bin/x64/initexmf.exe --report --admin
>      Option --admin only makes sense for a shared MiKTeX setup.
>
>      Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:
>
>        Option --admin only makes sense for a shared MiKTeX setup.

Apparently, the installer emits the `--admin` flag for portable installs because I am a local administrator and `initexmf` complains about it.

I thank you in advance for your attention.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Have you tried to run the installer un-elevated?

Normally, a local administrator gains root permissions only on request (elevation). It seems that you have configured your Windows system to bypass the elevation prompt.

**Comment by mikeyww** [comment]
Yes, Windows is configured to bypass the elevation prompt. I recommend that MiKTeX be allowed to install without an error under such conditions.
