### ISSUE TITLE
Miktex Update removes essential packages

### ISSUE THREAD

**Issue by bilal-saleem** [MiKTeX/miktex#376]
I have a fairly fresh install of Miktex (last two weeks or so). I tried to update Miktex today, and it failed with error:

2019-09-26 10:51:02,624-0400 ERROR mainwindow - Libraries\MiKTeX\Core\Process\win\winProcess.cpp:292: Windows API error 2: The system cannot find the file specified.
(commandLine="mpm --register-components --verbose", fileName="C:\Users\my_username\AppData\Local\Programs\MiKTeX 2.9\miktex/bin/x64\mpm.exe")

After the failed update, xelatex no longer works. If i run "xelatex somedoc.tex", there will be no output, it will do nothing and no error message. I have attached some of the logs.
[miktex-report.log](https://github.com/MiKTeX/miktex/files/3658534/miktex-report.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/3658535/miktex-console.log)

**Comment by edocevoli** [comment]
The update wizard has removed 9852 files in 202 packages. That's a disaster. Can you explain what you did? To investigate this issue, I need all/complete log files.

**Comment by bilal-saleem** [comment]
All I did was "Check for Updates" and then "Update Now" in the Miktex console. Here are the rest of the logs.

[miktex_logs.zip](https://github.com/MiKTeX/miktex/files/3659600/miktex_logs.zip)

**Comment by edocevoli** [comment]
Thank you. When you "Check for Updates", you will be presented with a list of update-able  packages. Do you remember whether this list was short/long?

**Comment by bilal-saleem** [comment]
It was long, it was a couple of scrolls worth of updates. When I do "Check for Updates" at this time, no updates are found.

**Comment by edocevoli** [comment]
Thank you. This long list was actually a list removals. Only one package (namely `l3build`) was updated.

**Comment by edocevoli** [comment]
Please check if these files exist and attach them (if they exist):
- `C:\Program Files\MiKTeX 2.9\miktex\config\packages.ini`
- `%LOCALAPPDATA%\Programs\MiKTeX 2.9\miktex\packages.ini`

**Comment by bilal-saleem** [comment]
C:\Program Files\MiKTeX 2.9\miktex\config\packages.ini exists, the other one does not. 

I put it in a zip, as github doesn't like the .ini extension.

[packages.zip](https://github.com/MiKTeX/miktex/files/3662855/packages.zip)

**Comment by edocevoli** [comment]
`C:\Program Files\MiKTeX 2.9\miktex\config\packages.ini` should not exist because you have installed MiKTeX for your private use. Is this an leftover from an old MiKTeX installation?

**Comment by bilal-saleem** [comment]
I uninstalled Miktex prior to my fresh install a couple of weeks ago, although it is possible that the uninstaller did not delete everything.

**Comment by edocevoli** [comment]
Thank you. This has been fixed with the latest update: MiKTeX now ignores `C:\Program Files\MiKTeX 2.9\miktex\config\packages.ini` if this is a single-user installation.

**Comment by bilal-saleem** [comment]
Thanks, Christian! When should we expect to see the changes reflected in the windows installer on miktex.org? (I can't build it on my system unfortunately).

**Comment by edocevoli** [comment]
Thanks, the installer will be available soon.

**Comment by edocevoli** [comment]
The installer is now available.
