### ISSUE TITLE
pdfcrop: The script engine could not be found.

### ISSUE THREAD

**Issue by jpstotz** [MiKTeX/miktex#377]
When I try to execute `pdfcrop` I get the following error message:
```
pdfcrop: The script engine could not be found.
pdfcrop: Data: scriptEngine="perl.exe", scriptName="pdfcrop"
```

I noticed that MiKTeX does not include a `perl.exe` - instead in contains a `runperl.exe`.

My MikTeX installation is about two years old, completely updated recently. 
I already tried to deinstall and re-install pdfcrop, but it had no effect.

**Comment by jpstotz** [comment]
It looks like in the source code the error messages already have been improved some time ago:

https://github.com/MiKTeX/miktex/blob/6401bb03b0594960cc7ce7fa7aac353a0611640a/Libraries/MiKTeX/Core/Session/runperl.cpp#L78-L80

Seems that there wasn't included i the release in March 2019 or this part of MiKTeX is not updated automatically?

**Comment by edocevoli** [comment]
Thank you. I have improved the error message.

**Comment by nanakiksc** [comment]
I have the same error as @jpstotz but I have Perl installed and it is in my path.

**Comment by edocevoli** [comment]
So running `perl --version` in a command-prompt Window succeeds? And also `where perl.exe` succeeds?

**Comment by nanakiksc** [comment]
Thanks for your prompt response. Yes, both checks succeed.
I solved this by installing pdfcrop from the MiKTeX Console (it wasn't marked as installed). I saw it running and I assumed it was installed along MiKTeX but... I must had it installed already for some reason (maybe it came with Rstudio or something).
Probably because the perl instalation was later, this first pdfcrop could not see it. So yes, I now have two pdfcrops.

**Comment by danielludolf** [comment]
Hello, I am receiving a similar error message while using RMarkdown.

```
Sorry, but pdfcrop.exe did not succeed for the following reason:

  MiKTeX could not find the script engine 'perl.exe' which is required to execute 'pdfcrop'.

Remedy:

  Make sure 'perl.exe' is installed on your system.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\daniel\AppData\Local\MiKTeX\miktex\log\pdfcrop.log

For more information, visit: https://miktex.org/kb/fix-script-engine-not-found
```

I downloaded [Strawberry Perl ](https://strawberryperl.com/) as suggested by others, but I am still receiving the error message. I already had `pdfcrop` installed in MiKTeX, but the error message stays the same whether `pdfcrop` is installed or not. Running `perl --version` and `where perl.exe` both succeeded when I ran in the Command Prompt. I would appreciate any guidance on how to resolve this issue.

**Comment by Lion815** [comment]
Hi, I got the same problem as daniel did when using pdfcrop, I firstly thought there's sth wrong with perl, but after uninstall perl and install again, I found it still raised the same erro message. Looking forward to your reply, I will appreciate it if you can give me any help.

**Comment by danielludolf** [comment]
@Lion815 I was able to stop the error message by opening the MiKTeX console and going to the Settings tab. There is an option that says 'You can choose whether missing packages are to be installed automatically (on-the-fly)'. Make sure that this is set to 'Always' to allow the necessary style files to be installed.

https://stackoverflow.com/questions/66305985/rstudio-pdflatex-exe-did-not-succeed
