### ISSUE TITLE
OrnementsADF font not installed

### ISSUE THREAD

**Issue by ghiastas** [MiKTeX/miktex#379]
On a fresh install of MiKTeX x64 on Windows adforn package is not installing properly:
MWE: 
```
 \documentclass{standalone}
 \usepackage{adforn}
 \begin{document}
 \adfhalfleftarrow
 \end{document}
```

Produces in TeXWorks console:

> ("C:\Users\dsaaa\AppData\Local\Programs\MiKTeX 2.9\tex/latex/adforn\uornementsa
> df.fd")Running miktex-makemf.exe...
> 
> Sorry, but miktex-makemf did not succeed.
> 
> The log file hopefully contains the information to get MiKTeX going again:
> 
>   C:\Users\dsaaa\AppData\Local\MiKTeX\2.9\miktex\log\miktex-makemf.log
> 
> Running miktex-hbf2gf.exe...
> Couldn't open `OrnementsA.cfg'
> 
> hbf2gf (CJK ver. 4.8.4)
> 
> Sorry, but miktex-maketfm did not succeed.
> 
> The log file hopefully contains the information to get MiKTeX going again:
> 
>   C:\Users\dsaaa\AppData\Local\MiKTeX\2.9\miktex\log\miktex-maketfm.log
> 
> ! Font U/OrnementsADF/m/n/10=OrnementsADF at 10.0pt not loadable: Metric (TFM) 
> file not found.
> <to be read again> 
>                    relax 
> l.4 {\Pifont{OrnementsADF}
>                           }
> ? 

miktex-makemf.log says:
> 2019-10-04 12:41:51,501-0400 INFO  miktex-makemf - starting with command line: miktex-makemf.exe --miktex-enable-installer --miktex-disable-maintenance --verbose OrnementsADF
> 2019-10-04 12:41:51,512-0400 FATAL miktex-makemf - The OrnementsADF source file could not be found.
> 2019-10-04 12:41:51,512-0400 FATAL miktex-makemf - The OrnementsADF source file could not be found.
> 2019-10-04 12:41:51,512-0400 FATAL miktex-makemf - Info: 
> 2019-10-04 12:41:51,512-0400 FATAL miktex-makemf - Source: 
> 2019-10-04 12:41:51,512-0400 FATAL miktex-makemf - Line: 0

miktex-maketfm.log says:

> 2019-10-04 12:41:51,342-0400 INFO  miktex-maketfm - starting with command line: miktex-maketfm -v OrnementsADF
> 2019-10-04 12:41:51,374-0400 INFO  maketfm - Running miktex-makemf.exe...
> 2019-10-04 12:41:51,374-0400 INFO  maketfm - running: miktex-makemf.exe --miktex-enable-installer --miktex-disable-maintenance --verbose OrnementsADF
> 2019-10-04 12:41:51,546-0400 INFO  maketfm - Running miktex-hbf2gf.exe...
> 2019-10-04 12:41:51,546-0400 INFO  maketfm - running: miktex-hbf2gf.exe --miktex-enable-installer --miktex-disable-maintenance -g OrnementsADF 300
> 2019-10-04 12:41:51,677-0400 FATAL miktex-maketfm - No creation rule for font OrnementsADF.
> 2019-10-04 12:41:51,684-0400 FATAL miktex-maketfm - No creation rule for font OrnementsADF.
> 2019-10-04 12:41:51,684-0400 FATAL miktex-maketfm - Info: 
> 2019-10-04 12:41:51,684-0400 FATAL miktex-maketfm - Source: 
> 2019-10-04 12:41:51,684-0400 FATAL miktex-maketfm - Line: 0

initexmf report is:

> Date: 2019-10-04 12:42:24
> MiKTeX: 2.9.7200
> OS: Windows 10 Pro, 64-bit, build 18362
> SharedSetup: no
> LinkTargetDirectory: C:\Users\dsaaa\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
> PathOkay: yes
> LastUpdateCheck: 2019-10-04 12:41:22
> LastUpdate: 2019-10-04 12:40:53
> SystemAdmin: yes
> RootPrivileges: no
> AdminMode: no
> Root0: C:\Users\dsaaa\AppData\Roaming\MiKTeX\2.9
> Root1: C:\Users\dsaaa\AppData\Local\MiKTeX\2.9
> Root2: C:\Users\dsaaa\AppData\Local\Programs\MiKTeX 2.9
> Root3: C:\ProgramData\MiKTeX\2.9
> Root4: C:\Program Files\MiKTeX 2.9
> UserInstall: C:\Users\dsaaa\AppData\Local\Programs\MiKTeX 2.9
> UserConfig: C:\Users\dsaaa\AppData\Roaming\MiKTeX\2.9
> UserData: C:\Users\dsaaa\AppData\Local\MiKTeX\2.9
> CommonInstall: C:\Program Files\MiKTeX 2.9
> CommonConfig: C:\ProgramData\MiKTeX\2.9

On another computer with older install adforn package was working and the font install location was:

> MiKTeX 2.9\fonts\type1\arkandis\adforn\OrnementsADF.pfb
> MiKTeX 2.9\fonts\afm\arkandis\adforn\OrnementsADF.afm

On a fresh install the locations for these files are:
> MiKTeX 2.9\fonts\type1\public\adforn\OrnementsADF.pfb
> MiKTeX 2.9\fonts\afm\public\adforn\OrnementsADF.afm

This might be related to the problem or not.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
This is not the right issue tracker for these kinds of problems. Please visit https://miktex.org/help, for details.
