### ISSUE TITLE
First time compiling a file for viewing after installation

### ISSUE THREAD

**Issue by Sorthes** [MiKTeX/miktex#38]
## My check list

- [X] latest package versions are installed
- [X] MiKTeX log files are attached

![latex error](https://user-images.githubusercontent.com/28241592/33328963-b3dd58d4-d45b-11e7-97c6-b8d914d3ef4c.jpg)

- [X] the bug can be reproduced by anybody (necessary input files are attached)

## What I tried to do
I tried to compile my file (attached) while in my class so see how it would look

## What I expected to happen
I was hoping for the file to compile after a couple of seconds and show me how it would look in pdf format

## What happened instead
The program threw a ton of error lines and then exploded.

**Comment by edocevoli** [comment]
Thank you. Running your test case succeeds on  my system:

1. Run the update wizard to get latest packages
2. Run `pdflatex sample2e`

No errors seen and `sample2e.pdf` looks fine.
