### ISSUE TITLE
! Undefined control sequence in \graphics after the latest MikTeX update

### ISSUE THREAD

**Issue by S2728** [MiKTeX/miktex#380]
After October 5 2019 update of MikTeX binaries, Undefined control sequence error appears 
for all my files that used to work fine.

A standard line in all my latex files
\includegraphics{filename}
causes the following error:
! Undefined control sequence.
\Ginclude@graphics ...\Ginput@path \set@curr@file
                                                  {#1}\edef \uq@curr@file {\...

l.31 \includegraphics{filename}
filename is an existing graphics file (eps or png or any other format)

The same error appears if I compile any latex file with \includegraphics 
using either LaTeX or PDFLaTeX, or XeLaTeX, or LuaLaTeX  

MWE would be:
\documentclass{article}
\usepackage{graphicx}
\begin{document}
text is here 
\begin{figure}
\centering
\includegraphics[]{example-image-a.jpg}
\caption{Test figure}
\end{figure}
\end{document}

------------------------------
 initexmf --report
Date: 2019-10-05 11:08:41
MiKTeX: 2.9.7200
OS: Windows 10 Pro, 64-bit, build 18362
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2019-10-05 10:47:34
LastUpdateAdmin: 2019-10-05 10:09:37
SystemAdmin: yes
RootPrivileges: no
AdminMode: no

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
a) This is not the right issue tracker for these kinds of problems. Please visit https://miktex.org/help, for details.

b) This is not a MiKTeX-specific bug and so cannot be fixed by me.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).
