### ISSUE TITLE
miktexsetup.exe is not a valid Win32 application

### ISSUE THREAD

**Issue by Wymaxep2011** [MiKTeX/miktex#382]
Good evening!
I've downloaded miktexsetup.exe recently and extracted it from archive (exe md5 hash is
a4780e430de2318e1ec64a20b825d9d7) but it is not starting, the error is "not a valid Win32 application". Is it a x64 app or do you use any exotic .NET Framework or other **** that prevents it from starting?

Exactly, the problem is deeper. I use TeXworks 0.4.4 r.1003 (MiKTeX 2.9) for years. Unfortunately, few years ago the journal changed their template file so now it requires changepage package. TeXworks had user-friendly package auto-installation functionality, but now it does not work: 
ftp://ftp.cstug.cz/pub/CTAN/systems/win32/miktex/tm/packages/
is empty. The Package Manager shows me the list of packages, including the required one, but, unfortunately, somebody f***ed backwards compartibility and api.miktex.org is not resolving now.
Now I'm following the official instructions "Set up a local package repository" and trying to run miktexsetup, but it was compiled by somebody who is absolutely not familiar with software development.

P.S. If anybody knows any alternative public package directories?

**Comment by edocevoli** [comment]
If you used this download link:

![Capture](https://user-images.githubusercontent.com/20090840/66258421-66184f00-e7a5-11e9-8465-892b62923100.PNG)

Indeed, that's the 64-bit version.
