### ISSUE TITLE
Is there anyway to configure MiKTeX so that it locates script engine perl.exe?

### ISSUE THREAD

**Issue by AlkisPis** [MiKTeX/miktex#39]
I have installed MiKTeX 2.9.6520
I run latexmk.exe and received the following error (2 message lines):
  latexmk: The script engine could not be found.
  latexmk: Data: scriptEngine="perl.exe"

I did some research on the problem and I found out that latexmk.pl and latexmk.bat were needed. So I found them in the Web, downloaded latexmk 4.48, created  scripts/latexmk/perl folder and copied the 2 files in it. I also added in latexmk.bat the full path to the perl.exe command. 
latexmk.exe still  produces the same error. (I have also tried using the parent folder: scripts\latexmk. No luck! All the scripts are there. Where else is MiKTeX looking for the script engine?)

Note: The info "The script engine could not be found." is useless. They should also mention where latexmk.exe looks for this engine!  Big S/W flaw! 

# Request for enhancment

_please remove this section if this is not a request for enhancement_

**Comment by edocevoli** [comment]
You have to install a Perl interpreter (`perl.exe`) which MiKTeX can find via the `PATH` environment variable.

**Comment by AlkisPis** [comment]
Thank you. I used the 2nd leg of your reply, i.e. envirenment path.  The first leg is irrelevant, since I mentioned that I used the (already installed) full Perl path in the latexmk.bat file. 
It indeed works when Perl path is in the environmant path although this should not be needed, since in the latexmk.bat file it says "If not (Perl is in PATH), you should replace 'perl' by the full pathname of the perl executable, e.g., 'C:\perl\bin\perl.exe'. Which I did. And it doesn't work.
