### ISSUE TITLE
Unstalling Miktex 2.9 due to bugs following packages Updates

### ISSUE THREAD

**Issue by pzorba75** [MiKTeX/miktex#390]
I'm new on this site and not really fluent in english.
Yesterday I've started Miktex Pakages Update, it apparently had run completely. But now, TexMaker cannot compile nor update my Latex documents. Trying to start manually thru the windows menu, I've received 
- **no-admin.exe** shortcut missing with Miktex Settings;
- **copystart_admin.exe** shortcut missing withe Miktex Update;
- and **mpm_mfc-admin.exe** short cut missing  with Miktex package Manager.
So after google-ing a lot, I've decide to unstalle and re-installe a new version from the download page.
With Windows 10 Uninstalling program, it is impossible to unsinstall Miktex, attached files provide informations on the error message and variables environnement data.
![Miktex-Desinstallation-1-Erreur](https://user-images.githubusercontent.com/56509259/66753919-11f02780-ee95-11e9-869b-626907966388.png)
![Miktex-Variables-Environnement-14-Oct-2019](https://user-images.githubusercontent.com/56509259/66753920-11f02780-ee95-11e9-9459-2272c395695f.png)
![Miktex-Variables-User-14-Oct-2019](https://user-images.githubusercontent.com/56509259/66753921-11f02780-ee95-11e9-9d37-fefea8719785.png)
![Texmaker-Parametres-14-Oct-2019](https://user-images.githubusercontent.com/56509259/66753922-11f02780-ee95-11e9-8082-84a86fae8ddb.png)

So, my question: what to do to make this installable ready to run or to unstall it from my system befor installing a new one.
My PC runs with Windows 10, last update, Miktex was installed for several users, but really used only with my personal account.
Thanks for helping me.
Regards
Pierre

**Comment by edocevoli** [comment]
If I understand you correctly, you had/have a MiKTeX installation which hasn't been updated for a while and now you cannot remove the old/broken MiKTeX installation in order to install a fresh MiKTeX.

Please read [this FAQ](https://miktex.org/faq/uninstall-miktex-win-cli) to learn how to remove MiKTeX using the command line.

**Comment by pzorba75** [comment]
Following your answer, I've reinstalled the latest Miktex 2.9. Ti now works good, excepr that I'cannot found Yap.exe to display dvi files. is there a special to this application?
Regards
Pierre

**Comment by edocevoli** [comment]
Yap is still there. You can start it via the <kbd>Windows</kbd> <kbd>y</kbd> <kbd>a</kbd> <kbd>p</kbd>

**Comment by pzorba75** [comment]
Good, it works from the windows cmd when enterin yap. But I need to set the complete path to Texmaker Settings before viewing dvi files. Formerly, I've set up 
**"C:/Program Files/MiKTeX 2.9/miktex/bin/x64/yap.exe" %.dvi**
to display the dvi files from TexMaker.
