### ISSUE TITLE
On the fly package install crashes

### ISSUE THREAD

**Issue by spirritus** [MiKTeX/miktex#394]
Unhandled exception at 0x000007FEE0447DBA (MiKTeX209-packagemanager.dll) in pdflatex.exe: 0xC0000005: Access violation reading location 0x000007FEE10CB060.

Also:

Unhandled exception at 0x000007FEE1197DBA (MiKTeX209-packagemanager.dll) in miktex-ttf2pk.exe: 0xC0000005: Access violation reading location 0x000007FEDFBDB060.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
