### ISSUE TITLE
microtype

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex#396]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hello!
Is it possible to update the package microtype? The version in MiKTeX is 2.7b
(2019/02/28) but the version on CTAN is 2.7c (2019-10-10).
It was not announced on ctan-ann@ctan.org :-(
Thank you.
François

**Comment by edocevoli** [comment]
This is not the right issue tracker for these kinds of problems. Please visit https://miktex.org/help, for details.
