### ISSUE TITLE
On-the-fly package install crashes

### ISSUE THREAD

**Issue by spirritus** [MiKTeX/miktex#397]
[test.log](https://github.com/MiKTeX/miktex/files/3739674/test.log)
Hi there,

the miktex on-the-fly package install is broken on my system.
Steps to reproduce: 
1) Setup miktex to allways install packages
2) create a minimal example and use previously not installed packages, e.g.

\documentclass[a4paper]{article}
\usepackage{blindtext}
\usepackage{lettrine}
\usepackage{yfonts}
\begin{document}
Hello World!
\end{document}

In this example blintext is already installed on the system, lettrine and yfonts are not.
The install of lettrine crashes latex.
This has nothing to do with the actual packages. The miktex installer seems to not handle package installs without a crash in on-the-fly mode.
Substitue the packages with arbitrary other ones the same crash appears.
The packages install fine when using the miktex console (admin).

#info from visual studio debugger on the crash:
Unhandled exception at 0x000007FED1837DBA (MiKTeX209-packagemanager.dll) in pdflatex.exe: 0xC0000005: Access violation reading location 0x000007FEE761B060.

#initexmf --report
Date: 2019-10-17 15:40:20
MiKTeX: 2.9.7200
OS: Windows 7 Professional, 64-bit, Service Pack 1, build 7601
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2019-10-16 14:22:35
LastUpdateAdmin: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\schmidt\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\schmidt\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\schmidt\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\schmidt\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\schmidt\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

#screenshot of the crash in attachment
![crash](https://user-images.githubusercontent.com/1154316/67015665-2a5f7c80-f0f7-11e9-90f0-3221ca3ca0b6.png)

**Comment by edocevoli** [comment]
Thank you. Unfortunately it was not possible to reproduce the crash on my development machine. The information you provided allows no conclusion about the cause of the crash. That said, at the moment it is not possible to fix the issue with your MiKTeX installation.

**Comment by pgr-a** [comment]
I have the same issue. The install completes, pdflatex crashes, but on the next run everything works including the new package. So it's on the level of a disconcerting annoyance.
What information would you need to solve this?

**Comment by edocevoli** [comment]
@pgr-a : see here [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
