### ISSUE TITLE
`xdvipdfmx` with options supplied as `output-driver` to XeLaTeX results in `can't write on file` error

### ISSUE THREAD

**Issue by DigNative** [MiKTeX/miktex#4]
Hi,

since some years, my standard command line arguments supplied to XeLaTeX contain the following option:

    -output-driver="xdvipdfmx -V6 -C 0x0010"

I updated my MiKTeX installation some days ago and noticed that the compilation of any document aborts now with a `I can't write on file ...` error. Please consider the following MWE:

    \documentclass{article}

    \begin{document}
        Test
    \end{document}

Using any of these commands (all of them worked before updating)

    xelatex -output-driver="xdvipdfmx -V6 -C 0x0010" test.tex
    xelatex -output-driver="xdvipdfmx -V6" test.tex
    xelatex -output-driver="xdvipdfmx -C 0x0010" test.tex
    xelatex -output-driver="xdvipdfmx -V5" test.tex

I will obtain the following output:

    This is XeTeX, Version 3.14159265-2.6-0.99998 (MiKTeX 2.9.6400)
    entering extended mode
    (test.tex
    LaTeX2e <2017-04-15>
    Babel <3.9r> and hyphenation patterns for 76 language(s) loaded.
    (C:\apps\MiKTeX-2.9\tex\latex\base\article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (C:\apps\MiKTeX-2.9\tex\latex\base\size10.clo)) (test.aux) [1
    ! I can't write on file `test.pdf'.
    Please type another file name for output:

However, if being compiled with

    xelatex -output-driver="xdvipdfmx" test.tex

the document will be generated without any problems. It seems that any argument supplied to the `xdvipdfmx` executable within the `output-driver` option causes that problem.

I am not sure where this error comes from and hence whether this is the right place for the bug report.

Thank you very much for your efforts in advance.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. You can run the updater now.

**Comment by DigNative** [comment]
I can confirm that the bug is resolved with the newest version of the `miktex-xetex-bin-2.9` package. Thank you very much for your fast response and fix of the issue!
