### ISSUE TITLE
i found this error while compiling my file 

### ISSUE THREAD

**Issue by ridhima20759** [MiKTeX/miktex#403]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by ridhima20759** [comment]
i found this error while compiling my document 
file="C:\Program Files\MiKTeX 2.9\miktex/config\package-manifests.ini", line="188216", error="invalid value definition"
and line number 188216 is: pro/SourceSerifPro-ExtraLight-tosf-sc-ot1.tfm

how to deal with it please reply

**Comment by edocevoli** [comment]
Duplicate of #290
