### ISSUE TITLE
A malware in miktex distribution

### ISSUE THREAD

**Issue by vm1563** [MiKTeX/miktex#405]
When I installed MikTex that I downloaded from Univ of Illinois mirror I got the following threat detection notification from my anti virus:-

..\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\miktex-extconv.exe is infected with Gen:Variant.Fugrafa.8906 and was moved to quarantine

Please look into this issue.

dhiraj

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you. Will take a look.
