### ISSUE TITLE
miktex distribution issue (continued)

### ISSUE THREAD

**Issue by vm1563** [MiKTeX/miktex#406]
Hi, Just now noticed the same issue with 2 more files:-

..\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\miktex-bg5conv.exe 
..\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\miktex-sjisconv.exe

(I'm Sorry I didn't notice this earlier.)

Thank you. Will take a look.

_Originally posted by @edocevoli in https://github.com/MiKTeX/miktex/issues/405#issuecomment-547306770_

**Comment by edocevoli** [comment]
OK
