### ISSUE TITLE
Failure after update to latest MikTex version (run-time library, epstopdf)

### ISSUE THREAD

**Issue by deining** [MiKTeX/miktex#408]
Hi,

i just upgraded my MikTeX installation. As part of this, miktex-epstopdf-bin-x64-2.9 was upgraded to latest version, Do Okt. 17 22:11:41 2019.

After the upgrade, a document that I could compile without problems using lualatex does compile work any more. Relevant excerpt from the log file:

```
LaTeX Warning: File `./Abbildungen/VorbauVollausstattungUebersicht.eps' not foun
d on input line 784.

Package epstopdf Info: Source file: <"./Abbildungen/""VorbauVollausstattungUeber
sicht".eps>
(epstopdf)             Output file: <"./Abbildungen/""VorbauVollausstattungUeber
sicht"-eps-converted-to.pdf>
(epstopdf)             Command: <epstopdf --outfile="./Abbildungen/""VorbauVolla
usstattungUebersicht"-eps-converted-to.pdf "./Abbildungen/""VorbauVollausstattun
gUebersicht".eps>
(epstopdf)             \includegraphics on input line 784.
Package epstopdf Info: Output file is already uptodate.
! error:  (file "./Abbildungen/""VorbauVollausstattungUebersicht"-eps-converted-
to.pdf) (pdf backend): cannot find image file '"./Abbildungen/""VorbauVollaussta
ttungUebersicht"-eps-converted-to.pdf'
!  ==> Fatal error occurred, no output PDF file produced!
```

I can successfully run the following command on the command line (Windows 10)

```
> epstopdf --outfile="Abbildungen/AlmaProUebersicht-eps-converted-to.pdf" Abbildungen/AlmaProUebersicht.eps"
```

However, execution of the command given in the log file fails since quoting inside the arguments is wrong:

```
> epstopdf --outfile="./Abbildungen/""VorbauVollausstattungUebersicht"-eps-converted-to.pdf "./Abbildungen/""VorbauVollausstattungUebersicht".eps
```

*Note:* It might be that the error is due to the update of the MiKTeX run-time library files (miktex-runtime-bin-x64-2.9) to version dated So Okt 20 22:12:04 2019.

Can you please have a look at this issue? Thanks!

For the sake of completeness, this is the relevant part of the source file:

```
783 \begin{tikzpicture}
784 \node[anchor=south west,inner sep=0] (image) at (0,0)  {\includegraphics[width=\linewidth,keepaspectratio,center]{./Abbildungen/VorbauVollausstattungUebersicht.eps}};
...
794 \end{tikzpicture}
```

Thanks for providing MikTeX!

**Comment by edocevoli** [comment]
Please attach a test case (files to reproduce the issue).
