### ISSUE TITLE
xelatex calls miktex-mf on OT.mf (othello) with unicode-math package and STIX Two Math mathfont

### ISSUE THREAD

**Issue by tamas-ferenci** [MiKTeX/miktex#409]
Consider the following minimal reproducible example:

```
\documentclass{book}
\usepackage{unicode-math}
\setmathfont(Digits,Latin,Greek)[]{STIX Two Math}
\begin{document}
a
\end{document}
```

Something goes really wrong: `miktex-mf` is called with `OT` (othello) for some reason and an enormous number of errors is generated.

I pretty sure it is related to [this](https://github.com/MiKTeX/miktex/issues/161), although I don't understand the details.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by u-fischer** [comment]
your syntax is wrong. `\setmathfont[]{STIX Two Math}` works fine for me.

**Comment by tamas-ferenci** [comment]
Ahhh... thank you very much! It was clearly my mistake then (albeit it is perhaps not the most fortunate behavior as a response to a syntactical error).
