### ISSUE TITLE
MiKTeX Console: Manually set Remote repository URL

### ISSUE THREAD

**Issue by podsvirov** [MiKTeX/miktex#413]
Looks like it's not possible to manually set `Remote repository URL` without invoking the `miktex.org` site API in the `MiKTeX Console` GUI, like the path to local package repository.
I think that such feature may be useful in some use cases.

**Comment by edocevoli** [comment]
Only well-known remote repositories are are accepted by the package manager. Even if you bypass MiKTeX Console (by editing the configuration value in the registry), the repository will be validated later (when it is used).

**Comment by podsvirov** [comment]
Hmm, this means that we can create a local copy of the `CTAN` and freely and easily use packages from the local repository, but we cannot share packages on the local network using the web server. :-(
This seems like a bad user experience...
