### ISSUE TITLE
Fresh install of MikTeX 2.9.7200 can't install/update packages, error 401

### ISSUE THREAD

**Issue by etremel** [MiKTeX/miktex#414]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I've just installed MikTeX 2.9.7200 on Windows 10 Enterprise. I installed "for all users" (as an administrator), and now I'm attempting to install a new package using the Admin MikTex Console. First, though, I tried simply checking for updates, using the "check for updates" button on the Overview tab. This immediately failed, producing the error "Something went wrong while checking for updates." The detailed error report produced when I clicked "yes" was:

> Error response from server: 401
> responseCode="401"

I next tried changing my update settings (Updates tab -> Change...), thinking that the problem might be that the default-selected update server was offline. However, when I selected "Remote package repository (Internet)" and clicked "Next," I once again got an error message with the text "Error response from server: 401," and the list of remote package repository servers remained empty.

My computer does not use a proxy server to connect to the Internet, and I made an exception in Windows Firewall for the mitek-console_admin.exe process just in case that was the problem. I have also verified that the MikTeX repository API (https://miktex.org/pkg/repositories) is online.

What could be going wrong here? Why is a fresh installation already broken?

My MikTeX configuration report: [miktex-report.txt](https://github.com/MiKTeX/miktex/files/3825863/miktex-report.txt)
My MikTeX console error log: [miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/3825865/miktex-console_admin.log)

**Comment by edocevoli** [comment]
Try contacting the MiKTEX server at https://api2.miktex.org/

If you are behind a proxy, you must specify the proxy server address ("Connection Settings" on the first wizard page).
