### ISSUE TITLE
MiKTeX Server: api2.miktex.org/hello

### ISSUE THREAD

**Issue by hfhbd** [MiKTeX/miktex#415]
Hello, 

When searching for updates (and on-the-fly installing packages) miktex wants to connect to api2.miktex.org/hello. This request results in an error (code 7).

Used request:
- using miktex behind no proxy -> Answer: Code 7
- using miktex behind proxy -> Answer: Code 7
- requesting the url in the browser from the same PC (via GET) -> Answer: Bad Request
- requesting the url in the browser from mobile phone (GET) -> Answer: Bad Request

I don't know, if this issue is the right place for server issues...

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
This is the expected behaviour. This URL requires authentication.

**Comment by hfhbd** [comment]
Is https://api2.miktex.org GET / down? Normally, I used the base url to check the connection and there was a poem, to signal the available of api2.miktex.org. Now, I am getting always 404. 

2020-01-14 09:13:19,773+0100 INFO  mainwindow - checking for updates...
2020-01-14 09:13:19,796+0100 ERROR mainwindow - Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:266: Failure when receiving data from the peer(code="56", url="https://api2.miktex.org/hello")

**Comment by edocevoli** [comment]
Indeed, the GET on the domain root has been disabled a few days ago.
