### ISSUE TITLE
Miktext.org: 502

### ISSUE THREAD

**Issue by ankineri** [MiKTeX/miktex#418]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I've noticed that MikTex servers return 502 for the last ~30 minutes.
Could you please have a look?

Similar to #368 and #267 

_502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server._

**Comment by edocevoli** [comment]
Thank you. Usually this is a temporary issue.
