### ISSUE TITLE
download of cm-super is speed-limited

### ISSUE THREAD

**Issue by donovaly** [MiKTeX/miktex#42]
# Bug report

I got user complaint that downloading of the package cm-super is very low while all other packages can be downloaded fast. I therefore tested this and indeed, no matter what repository I use, downloading the cm-super package is speed-limited to 66kb/s. Other larger packages like e.g. cm-unicode are not speed-limited. I get download speeds of 800kb/s for cm-unicode with the same repository that delivers me cm-super only with 66kb/s. (tested with repositories ftp.fernuni-hagen.de, ftp.tu-chemnitz.de, mirror.ibcp.fr)

Since this happens with 3 different repositories, the speed-limit seems to be a setting from MiKTeX.

**Comment by edocevoli** [comment]
There is no speed limit implementation for `cm-super`.

**Comment by edocevoli** [comment]
This will be fixed with [milestone 2.9.6730](https://github.com/MiKTeX/miktex/milestone/6).
