### ISSUE TITLE
windows install fails due to detected Win32/Azden.A!cl trojan for basic-miktex-2.9.7255-x64.exe

### ISSUE THREAD

**Issue by dr-baem** [MiKTeX/miktex#421]
I tried to download and install Miktex from https://miktex.org/download for Windows10 (Version	10.0.18362) and Windows Defender is detecting a Trojan: Win32/Azden.A!cl within the provided basic-miktex-2.9.7255-x64.exe

This problem might be related to a false posive detection of the Windows Defender. For unexperienced users like me this is very irritating at first. 

I would suggest to provide some information on that on MikTex's FAQ page for example.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you. Unfortunately, it would not be legal to add a statement like you suggest to the FAQ page.

**Comment by dr-baem** [comment]
Thanks for the quick response. I am afraid that such kind of issues prevent some of the young researchers to use Miktex when writing Latex papers etc.  

I wonder if the community could help to unflag miktex from being a potential thread?

**Comment by ivankokan** [comment]
Report it as false positive: https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/developer-resources.

**Comment by antigran** [comment]
I do not think reporting it to Microsoft is possible: the installer is bigger in size than Microsoft allows. And in any case, it is probably better to address the root cause by identifying and addressing code that triggers Microsoft Defender false detection.
