### ISSUE TITLE
Suggested feature: Portable document archive

### ISSUE THREAD

**Issue by MrMasterplan** [MiKTeX/miktex#424]
The MS Word .docx format is actually a zip archive with xml files and folders for resources such as pictures. The idea here is to do the same for .tex sources. 
Call the archive something like .pta (portable Tex archive), and support creating,  opening editing and typesetting this file directly from MikTeX.

Proposed properties:

- a zip archive with all sources necessary to typeset a TeX document. 
- renamed to something other than .zip to discourage non-technical users from editing directly. Suggestion: .pta
- MikTeX support for working with this file directly. (like MS Word works with .docx archives) In particular guarantee that the archive can always be typeset again after moving and copying to another installation of MikTeX.
- Use a somewhat strict structure for names and locations inside the archive. This will simplify development of the feature. Unsupported  uses can always fall back to ordinary .tex source files.
- a “make-file” for standardized typesetting with one click - no setup required at all by users who only want to make minor changes to a document.
- archive can contain non-standard dependencies, i.e. packages, pictures, styles.
- archive can contain the typeset pdf document. Costs extra size file, but gains accessibility. This makes it very easy to write “viewer” applications for every conceivable system out there - they simply pull the pdf out of the archive.
 
Use cases:

- non-technical persons are comfortable with a document being one file. 
- file can be copied and moved around while maintaining a guarantee that it can be typeset when needed.
- this could greatly assist in spreading the use of latex outside of technical academic fields.

Aspects that need more thought:

- when editing creates typesetting errors, the archive could maintain a "last successfully typeset" pdf for the viewers, alternatively it could present a "corrupted" pdf file. Another approach could be to forbid saving to the archive format if the document cannot be typeset.

Feel free to use and share this idea however you want. I don’t have the time to develop this myself, but would love to use the feature at the engineering company where I work.

Best regards,
Simon

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by rpspringuel** [comment]
This sounds less like a MiKTeX (or TeXLive) feature and more like something for an IDE like TeXworks.

**Comment by hmenke** [comment]
There is also a thread about this on the TeX Live mailing list:
https://tug.org/pipermail/tex-live/2019-December/044601.html

**Comment by edocevoli** [comment]
Honestly, I have no idea if this is a useful feature. Nevertheless, I will investigate and see if it is possible (without to much effort) to implement an experimental (prototype) version for further evaluation.
