### ISSUE TITLE
MikTex proxy authentication documentation

### ISSUE THREAD

**Issue by AlonAmsel** [MiKTeX/miktex#427]
I'm trying to configure MikTeX package manager to load packages from the internet. It used to work, but we changed proxy servers and our IT security requests official documentation about the proxy authentication method before giving me a green light, given that the NTLM standard appears not to be supported (I found this information here: https://sourceforge.net/p/miktex/mailman/message/28077376/).

Could you point me to a(n official) MikTex technical documentation that states and/or describes the authentication method when loading packages through a proxy server? Don't think it matters, but I'm using MikTex portable version 2.9.6621

**Comment by edocevoli** [comment]
https://docs.miktex.org/2.9/manual/mpm.html:

###Environment

```
http_proxy
The proxy server to be used for HTTP.
```

```
FTP_PROXY
The proxy server to be used for .
```

```
ALL_PROXY
The proxy server to be used, if no protocol-specific proxy is set.
```
```
NO_PROXY
Comma-separated list of host names that should not go through any proxy.
```
