### ISSUE TITLE
Suggested feature: epstopdf - alert on missing font packages

### ISSUE THREAD

**Issue by ivankokan** [MiKTeX/miktex#429]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Motivated by [this issue](https://tex.stackexchange.com/questions/519027/error-while-using-epstopdf) and Andrey's expectations

> I expected, however, Miktex to install missing packages.

I was wondering whether it would be possible from MiKTeX to alert on missing packages in "install missing packages on-the-fly" fashion.

(Related to https://github.com/MiKTeX/miktex-packaging/issues/112.)

**Comment by ivankokan** [comment]
Hi @edocevoli.

This could be implemented this way:

1. If `epstopdf` fails, try to capture the font name with the following regex
```
Error:[[:space:]]*/invalidfont[[:space:]]*in[[:space:]]*/findfont[[:space:]]*Operand stack:[[:space:]]*([^[:space:]]+)
```

2. Find all font associations in `Fontmap.MiKTeX` for previously detected font. (`Fontmap.MiKTeX` might contain some non-unique associations, hence all should be considered.) If font in EPS is rare, or it does not have any association in `Fontmap.MiKTeX`, stop here ("nothing can be done", "submit an issue" etc.).

3. If "Always install missing packages on-the-fly" or "Ask me" are set, for each font association found in 2. (e.g. `a/b/c/d/e/f.pfb`) trigger or prompt for installing all packages that contain `f.pfb` (use filename only, ignore relative path). (Eventually this might not help due to incorrect association in  `Fontmap.MiKTeX`.)

Note: If multiple font resources are not installed, `epstopdf`/`mgs` reports only one at a time, and it is expected that steps 1. - 3. must be run several times.

What do you think?

**Comment by Abraham-dot** [comment]
MikTex has a wrong version of Ghostscript which produces errors by not recognizing fonts.
For example, it writes:

Error: /invalidfont in /findfont
Operand stack:
   --nostringval--   Helvetica-Oblique
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2015   1   3   %oparray_pop   2014   1   3   %oparray_pop   --nostringval--   1998   1   3   %oparray_pop   1884   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   1967   2   4   %oparray_pop
Dictionary stack:
   --dict:989/1684(ro)(G)--   --dict:0/20(G)--   --dict:111/200(L)--   --dict:35/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 69493
MiKTeX GPL Ghostscript 9.25: Unrecoverable error, exit code 1
xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object.
No output PDF file written.
Sorry, but xelatex did not succeed.
The log file hopefully contains the information to get MiKTeX going again:
  C:\Users\Abraham1\AppData\Local\MiKTeX\2.9\miktex\log\xelatex.log
Sorry, but "MiKTeX Compiler Driver" did not succeed.


Note the text above: "MiKTeX GPL Ghostscript 9.25: Unrecoverable error, exit code 1"
This error occurs when the input is an eps figure. It does not occur with this figure for a different version of Ghostscript. Please explain how I can change the version of Ghostscript which isI used with MikTex. (I use Xelatex in MikTex TexWorks.)

**Comment by ivankokan** [comment]
This issue is about `epstopdf`, not about `xdvipdfmx` which is your case.

Also, MiKTeX does not have "wrong version" of Ghostscript, only "not recent". But 9.25 works correctly considering the updates in few recent months.

Anyway, do you have `helvetic` package installed?

**Comment by ivankokan** [comment]
> This error occurs when the input is an eps figure. This error does not occur with this figure for a different version of Ghostscript.

I suggest you convert those EPS resources manually with `epstopdf` and include them as PDF resources in XeLaTeX. That will do.

> Please explain how I can change the version of Ghostscript which is used with MikTex. (I use Xelatex in MikTex TexWorks.)

I suggest maybe opening a new issue on this matter.

**Comment by ivankokan** [comment]
@Abraham-dot Have you tried?

**Comment by ClareBellingham** [comment]
Has this issue been resolved, or is there an easy step by step on where to install or point the fonts as I have this issue after updating Miktex and now cannot build by reports to include eps at all

**Comment by ivankokan** [comment]
@ClareBellingham https://github.com/MiKTeX/miktex-packaging/issues/112#issuecomment-577104722

> Or, the ultimate approach: use MiKTeX Console Packages view to filter the package list with *.pfb, and install all filtered packages.

**Comment by ivankokan** [comment]
Hi @edocevoli. I am keen to help with implementing this feature. Can you please instruct how to set up the dev environment?

**Comment by edocevoli** [comment]
Thank you, I am already working on it (not yet committed).

I think it is better (maybe easier) to scan the EPS file before running Ghostscript. So `/Helvetica-Oblique findfont` triggers the font look / installation before the Ghostscript invocation.

**Comment by ivankokan** [comment]
> Thank you, I am already working on it (not yet committed).
> 
> I think it is better (maybe easier) to scan the EPS file before running Ghostscript. So `/Helvetica-Oblique findfont` triggers the font look / installation before the Ghostscript invocation.

Great! Such pre-check approach is definitely more pragmatic than post-check. A quick look on the commit - looks good.

I urged on this request due to many related questions/issues on Stack Exchange lately.

**Comment by edocevoli** [comment]
This has now been implemented.

Re  MiKTeX/miktex-packaging#112: 
The levels are predefined. I can make `helvetic` a basic (`M`) package.

**Comment by ivankokan** [comment]
> This has now been implemented.
> 
> Re [MiKTeX/miktex-packaging#112](https://github.com/MiKTeX/miktex-packaging/issues/112):
> The levels are predefined. I can make `helvetic` a basic (`M`) package.

Excellent! Looking forward to test and verify it.

**Comment by ivankokan** [comment]
@edocevoli Tested. Verified.
