### ISSUE TITLE
MPM (admin) cannot be run if TeXworks is running

### ISSUE THREAD

**Issue by donovaly** [MiKTeX/miktex#43]
# Bug report

- log in on Windows as a user that has no admin permissions
- open TeXworks and keep it open
- start the MiKTeX Package Manager (Admin)

Windows will prompt you for the admin password  but the MPM cannot be started:
```
MiKTeX Problem Report
Message: Windows API error 87: Falscher Parameter.
Data: path="C:\ProgramData\MiKTeX\2.9\miktex/data/le\1756f6ade37d5f870f23c05a7f81e257.fndb"
Source: Libraries\MiKTeX\Core\MemoryMappedFile\win\winMemoryMappedFile.cpp
Line: 83
```
One can run the MPM (admin) version as non-admin if TeXworks is not running.

**Comment by edocevoli** [comment]
This has been fixed.
