### ISSUE TITLE
language patterns in the format can not be changed manually

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#435]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have a single user installation on windows 10. 

When I change something in the settings->language in the miktex console, e.g. exclude the ethiopic language my local languages.ini is adapted:

```
[ethiopic]
attributes=exclude
```

But after rebuilding the format this document

~~~~
\documentclass{article}
\usepackage[showlanguages,ngerman]{babel}
\begin{document}
abc
\end{document}
~~~~

still shows that the patterns have been used:

~~~
20	estonian	loadhyph-et.tex	
21	ethiopic	loadhyph-mul-ethi.tex	
21	amharic		
~~~

The language.dat in `...\AppData\Roaming\MiKTeX\2.9\tex\generic\config` is unchanged.

If I then run an update something does trigger also the update of language.dat and then the language pattern is gone in the format. But how to do this without an pending update?

**Comment by edocevoli** [comment]
MiKTeX Console should run `initexmf --mklangs` to refresh `language.dat`.

**Comment by u-fischer** [comment]
`--mklangs`  is not documented (and also doesn't show up in `initexmf --help`  (I tried to find such an option as I was quite sure that it something like this ;-)).

**Comment by edocevoli** [comment]
Yes, it seems to be undocumented. I can change it as well...

**Comment by edocevoli** [comment]
As of 2.9.7300, `language.dat` is automatically refreshed if `language.ini` is newer.
