### ISSUE TITLE
Problems with the oberdiek package

### ISSUE THREAD

**Issue by marklinne** [MiKTeX/miktex#436]
After updating MikTEX I am unable to typeset because the system wants to install \atbegshi.sty as part of the oberdiek package, but it fails. 

[miktex-report.zip](https://github.com/MiKTeX/miktex/files/3944069/miktex-report.zip)

**Comment by edocevoli** [comment]
Please also attach the log files in `%LOCALAPPDATA%\MiKTeX\2.9\miktex\log`.

**Comment by marklinne** [comment]
Done

**Comment by edocevoli** [comment]
No, I see no attached files. Please note that replying to GitHub emails does not work with attachments...

**Comment by marklinne** [comment]
[miktex-makepk.zip](https://github.com/MiKTeX/miktex/files/3944151/miktex-makepk.zip)
Hope that helps

**Comment by marklinne** [comment]
I guess I needed to hit "comment". Sorry.

**Comment by edocevoli** [comment]
Thanks.

This is a known MiKTeX limitation: when you have installed MiKTeX for all users, you have to be careful with updates. You have to run the update process twice:

1. start MiKTeX Console, switch to admin mode and check for updates
1. start MiKTeX Console, stay in user mode and check for updates

**Comment by marklinne** [comment]
Good to know. I would neve rhave guessed that. Thanks for yout time.

**Comment by marklinne** [comment]
It works, by the way.

**Comment by edocevoli** [comment]
Glad it works now.

**Comment by edocevoli** [comment]
As of 2.9.7300, MiKTeX shows a warning message when admin/user updates are out-of-sync.
