### ISSUE TITLE
Create "fc-cache.exe" as alias

### ISSUE THREAD

**Issue by Speravir** [MiKTeX/miktex#438]
Hello, for a lot of well-known program names in the TeX world you have created alias hard links, but one of them is missing: `fc-cache.exe`. There is only `miktex-fc-cache.exe` in the moment. I am quite sure this was different in the past: _fc-cache_ once must have been included, because [I used it without separate installation](https://tex.stackexchange.com/a/88424/9237) (link to TeX.StackExchange.com). I noticed this btw due to a [comment to this answer](https://tex.stackexchange.com/questions/88423/manual-font-installation#comment1183671_88424).

This is apparently for MiKTeX on Windows, I cannot say anything regarding the other OS versions.

**Comment by edocevoli** [comment]
The alias is now available.

**Comment by Speravir** [comment]
Is the alais created on a new installation? Because: On updating it is not! So, for me actuall this does not count as solved.

**Comment by edocevoli** [comment]
Yes, like all the other links it is created during installation.

**Comment by edocevoli** [comment]
`fc-cache.exe` is automatically created by MiKTeX Console if you update packages.
