### ISSUE TITLE
   miktexsetup.exe: Windows API error 3

### ISSUE THREAD

**Issue by markm2001** [MiKTeX/miktex#44]
# Bug report
 
i have installed miktex according to the following instructions: https://miktex.org/howto/deploy-miktex

Server: Windows 2012 R2 
Clients: Windows 10 1709 (clean Installation) 
- Firewall off, Defender off, UAC off, Logon User with local administrative rights, no GPOs from DC,  

After the start of the script on Client, miktexsetup.exe copies files (ca. 500MB) to local User Profile Folder (%tmp%). Then the following error message:

_```
miktexsetup.exe: Windows API error 3: The system cannot find the path specified. 
 miktexsetup.exe: Data: fileName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\initexmf.exe", commandLine="initexmf "--common-install=C:\Program Files\MiKTeX 2.9" 
 --set-config-value=[Core]SharedSetup=1 --admin "--log-file=C:\Program Files\MiKTeX 2.9\miktex/config\uninst.log" --verbose"
```_ 

in C:\Program Files\MiKTeX 2.9\ is only one Folder/subfolder with one file (.\miktex\config\uninst.log)

**Comment by edocevoli** [comment]
Thank you. I cannot reproduce this:

1. I have found no error message In the supplied log files.
2. Running your test case works on my machine.

**Comment by egorpugin** [comment]
Same for me.
1. error 126 when installing into `c:\program files\miktex 2.9`
2. error 3 with `--portable --shared=no`

There are ugly paths like `c:\something\more\miktex/bin/more\whatever.exe`. This inconsistency is very suspicious and probably the root issue.
