### ISSUE TITLE
Cannot build new format

### ISSUE THREAD

**Issue by gl-utah** [MiKTeX/miktex#441]
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/3970045/miktex-report.txt)

[initexmf.log](https://github.com/MiKTeX/miktex/files/3970047/initexmf.log)
[miktex-fc-cache.log](https://github.com/MiKTeX/miktex/files/3970048/miktex-fc-cache.log)
[mkfntmap.log](https://github.com/MiKTeX/miktex/files/3970049/mkfntmap.log)
[mpmcli.log](https://github.com/MiKTeX/miktex/files/3970050/mpmcli.log)
[LPLAIN.TEX.txt](https://github.com/MiKTeX/miktex/files/3970066/LPLAIN.TEX.txt)

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have a new installation of MiKTeX on a new computer, running Windows 10.  I tried to make a new format file by following the following steps:
MiKTeX Console -> Settings -> Formats -> +
	format key  ltznpdf
	format name ltznpdf
	compiler pdftex
	input file name lplain.tex
	output file name latex209PDF
	preloaded format (none)
	Description LaTeX 2.09 PDF
Clicked "Exclude this format when updating all format files."
Clicked "OK"
MiKTeX responded with: "Sorry, something went wrong.  Do you want to see the error details?"
I clicked Yes.
MiKTeX responded with: "MiKTeX encountered an internal error."

How can I build this format file?

The file lplain.tex is in a directory contained in the TEXINPUTS environment variable.  GitHub only allowed me to attach that file to this message after I changed its name by appending a .txt extension to it.  (The lplain.tex has local modifications; I didn't attach the local files which it inputs, but they are in the same subdirectory as lplain.tex, so they probably aren't the problem.)

**Comment by edocevoli** [comment]
Thank you. I was able to reproduce this bug. As a workaround, you can add the following lines to `formats.ini`:

```
[ltznpdf]
attributes = exclude
compiler = pdftex
description = LaTeX 2.09 PDF
input = lplain.tex
```

To open `formats.ini` in Notepad, run

```
initexmf --edit-config-file formats.ini
```

**Comment by gl-utah** [comment]
Thank you very much.  I was able to use the workaround successfully.

**Comment by edocevoli** [comment]
This has been fixed.
