### ISSUE TITLE
Autoinstall packages on the fly (without asking): give option to install for all users

### ISSUE THREAD

**Issue by alleluia20** [MiKTeX/miktex#445]
Hello,

I have just replaced Texlive with Miktex in Windows, and I am liking it. Nevertheless, I found a feature that is counter-intuitive, in my opinion. I chose to install Miktex for all users, and then I selected "yes" to "install missing packages on the fly". 

I then noticed that such packages are not installed for all users, but in the folder Appdata\Roaming of my personal directory. A number of problems arise from this: extra space may be used without need in case many users install on the fly repeated packages, those packages are not shown as installed in Miktex console, and I do not know whether they will update. Furthermore, **I think this is counter-intuitive, because I first selected to install Miktex for all users**.

To fix it, I had to switch to "ask me first" when installing missing packages on the fly, delete all Miktex folders in Appdata, and manually accept all prompts to install a new package, making sure that the package was going to be installed for all users. It was a bit tiring, because I had to accept many times on the first compilation of a Latex document.

I propose that, **when someone selects "yes" to "install missing packages on the fly", a new option should display, reading something like "install them for all users"**: you could choose whether or not select that second option. This should be done at the two places where the "install on the fly" option appears: **at the Miktex installer, and at the console**.

One might mention the problem that auto installing for all users will make Windows prompt for administrative rights, and it may confuse the user, but **there are several simple solutions for that**. For example, an advice about this happening can be written at the configuration dialogue of "install on the fly". Furthermore, if necessary, the package manager can pop up a window like "I need to install some missing packages, please grant administrative rights at the next prompt".

Regards.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
MiKTeX already honors the `[MPM]AutoAdmin` configuration setting. See [here](https://docs.miktex.org/manual/miktex.ini.html).

To turn on `[MPM]AutoAdmin` for yourself:

```
initexmf --set-config-value=[MPM]AutoAdmin=t
```

Or for all users:

```
initexmf  --admin --set-config-value=[MPM]AutoAdmin=t
```

I will add a UI for this setting.

**Comment by edocevoli** [comment]
You now have the option to automatically install packages for all users:

![Capture](https://user-images.githubusercontent.com/20090840/77342760-fd139c00-6d30-11ea-83a5-d4164d5f4d0e.PNG)
