### ISSUE TITLE
'File is empty' Issue when starting Miktex on Mac 10.15.2 Catalina

### ISSUE THREAD

**Issue by dejaraczo** [MiKTeX/miktex#447]
I was able to install Miktex and run it successfully.
However, when working with the packages and changing repository mirror application crashed with the error "File is empty".
Since that time, I'm not able to open it again, I tried to reinstall it couple of times with no effect.
The error message "File is empty" still appears when launching Miktex.
Screenshot attached.

<img width="471" alt="Zrzut ekranu 2020-01-6 o 12 38 01" src="https://user-images.githubusercontent.com/26306622/71816001-8811be00-3081-11ea-8874-4c7bed5c1431.png">

I couldn't find any info about the possible configuration files or directories to clean.
Any help with that matter would be very appreciated.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by kasadevall** [comment]
Exactly the same happened to me after installing it to my new MBP running v 10.15.2 Catalina. However, I had it installed in my old MBP, running the same version of Catalina and it had no problem. I have tried deleting and reinstalling, also deleting the miktex bin files... but it still shows the same error.

**Comment by edocevoli** [comment]
I was not yet able to reproduce the issue. If you have new information available (log files), we can reopen the issue.

**Comment by FiodarM** [comment]
I am experiencing the same issue on Macbook Air 2020 with macOS 10.15.4 installed.

**Comment by edocevoli** [comment]
Duplicate of #491
