### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by Durant35** [MiKTeX/miktex#45]
+ Ubuntu16.04 `apt-get install` follow [Install MiKTeX for Linux](https://miktex.org/howto/install-miktex-unx)
![image](https://user-images.githubusercontent.com/6770853/34369808-0dcae2a8-eafa-11e7-8f50-3abc5557ea37.png)

+ But got following results
```sh
...
initexmf: /usr/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/bin/../lib/../lib/libMiKTeX209-extractor.so.1)
initexmf: /usr/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/../lib/../lib/libMiKTeX209-extractor.so.1)
dpkg: error processing package miktex (--configure):
...
```

**Comment by gnw3** [comment]
I have Linux MInt 18.3 (64-bit), which is based on Ubuntu 16.04 and should have the same `libstdc++ libraries`.  This is a fresh install, and does not have `/usr/bin/../lib/libstdc++.so.6 ` (aka `/usr/lib/libstdc++.so.6`). It does have both 32-bit and 64-bit versions, in `/usr/lib/i386-linux-gnu` and `/usr/lib/x86_64-linux-gnu`, respectively.

I would expect `/usr/lib/libstdc++.so.6` to be a symbolic link to the actual library.   If you have upgraded from earlier version or installed 3rd party software, you can end up "dangliing links" or with older libraries in places where they don't belong.  See: [How do I find the package that provides a file?](https://askubuntu.com/questions/481/how-do-i-find-the-package-that-provides-a-file) and
[How to fix: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found](https://stackoverflow.com/questions/19386651/how-to-fix-usr-lib-libstdc-so-6-version-glibcxx-3-4-15-not-found) for an issue similar to yours.

If `/usr/lib/libstdc++.so.6` is a dangling link and is not claimed by any package, removing it should not break anything and may allow miktex to run.

If you are able to remove the offending package you can use the `ldd` command to see which libraries are being used by `initexmf`.

**Comment by Durant35** [comment]
It works. Thanks.
