### ISSUE TITLE
Taiwan is mistakenly regarded as a country

### ISSUE THREAD

**Issue by quancs** [MiKTeX/miktex#450]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

In the "Change Package Repo" page of MiKTeX Console, Taiwan is mistakenly regarded as a country. I'm a loyal fan of MiKTeX. I like it very much. But as a Chinese, I feel offended by MiKTeX listing Taiwan (one part of China) as a country. Please fix it by changing the column title "Country" to "Region", or just changing "Taiwan" to "Taiwan, China".

Thank you! Thank MiKTeX!

**Comment by edocevoli** [comment]
Country information is provided by a web service which delivers country names by ISO 3166 (see https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes). I think the UN conform name would be "Taiwan, Province of China". But as I said before, the information is provided by a web service not controlled by me.
