### ISSUE TITLE
Clicking Close button vs pressing Esc key upon finished package installation

### ISSUE THREAD

**Issue by ivankokan** [MiKTeX/miktex#451]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Once the package gets installed in Packages view in MiKTeX Console
![image](https://user-images.githubusercontent.com/1058211/72346311-00a5f980-36d6-11ea-98e8-61f898383fa4.png)
button changes caption from "Cancel" to "Close".

By clicking it user gets back to the updated package list (e.g. "Installed on" column for previously installed package shows the installation date).

On the other hand, by pressing Esc key user gets back to the package list which is not updated in this case.

Can we make pressing Esc key to behave the same way as clicking the button (when the installation is done)? (I have not thought about behavior during the installation, could be analyzed as well.)

**Comment by edocevoli** [comment]
Escaping the dialog now triggers a refresh of the list view.
