### ISSUE TITLE
MikTex Console Crashing When Creating Child Window: "No Qt window found"

### ISSUE THREAD

**Issue by max-desousa** [MiKTeX/miktex#452]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am at the office trying to write documents in tex. I have worked with colleagues on a number of computers trying to mimic an old install I had here a few years ago - all 5 of us are experiencing the issue. 

We work behind a proxy, and I used to be able to adjust for this in the settings tab, and then in the popup menu created by clicking "change" button under the general sub-tab. Now doing this causes the console to crash. I believe that I am also not able to download updates because I am unable to set the proxy ("could not resolve host").  

The source of the problem seems to be child windows of the MikTex Console

I found stack exchange  that suggested an additional log from Microsoft DbgView may be helpful. Here is something interesting I found where the DBgViewer cannot find a Qt window (last line).

sourced from:
`set MIKTEX_TRACE=error,config,lockfile,process`
`miktex-console`

`00000088	106.91595459	[22760] [MiKTeX] TRACE miktex-console.core - registering user TEXMF root: C:\Users\a150106\AppData\Roaming\MiKTeX\2.9`
`00000089	106.91606140	[22760] [MiKTeX] TRACE miktex-console.core - registering user TEXMF root: C:\Users\a150106\AppData\Local\MiKTeX\2.9 `
`00000090	106.91619110	[22760] [MiKTeX] TRACE miktex-console.core - registering user TEXMF root: C:\00-Max\98-ExtraPrograms`
`00000091	106.91627502	[22760] [MiKTeX] TRACE miktex-console.core - registering common TEXMF root: C:\ProgramData\MiKTeX\2.9` 	
`00000092	106.91638184	[22760] [MiKTeX] TRACE miktex-console.core - registering common TEXMF root: C:\Program Files\MiKTeX 2.9` 	
`00000093	106.91648102	[22760] [MiKTeX] TRACE miktex-console.core - registering user TEXMF root: \\MiKTeX\]MPM[` 	
`00000094	106.91658020	[22760] [MiKTeX] TRACE miktex-console.core - UserData: C:\Users\a150106\AppData\Local\MiKTeX\2.9` 	
`00000095	106.91669464	[22760] [MiKTeX] TRACE miktex-console.core - UserConfig: C:\Users\a150106\AppData\Roaming\MiKTeX\2.9 	`
`00000096	106.91680908	[22760] [MiKTeX] TRACE miktex-console.core - UserInstall: C:\00-Max\98-ExtraPrograms 	`
`00000097	106.91690826	[22760] [MiKTeX] TRACE miktex-console.core - CommonData: C:\ProgramData\MiKTeX\2.9 	`
`00000098	106.91700745	[22760] [MiKTeX] TRACE miktex-console.core - CommonConfig: C:\ProgramData\MiKTeX\2.9 	`
`00000099	106.91703033	[22760] [MiKTeX] TRACE miktex-console.core - CommonInstall: C:\Program Files\MiKTeX 2.9 	`
`00000100	106.91707611	[22760] [MiKTeX] TRACE miktex-console.core - application tags: miktex-console;miktex 	`
`00000101	106.91717529	[22760] [MiKTeX] TRACE miktex-console.core - setting env TEXSYSTEM=miktex 	`
`00000102	106.91721344	[22760] [MiKTeX] TRACE miktex-console.core - setting env GSC=mgs.exe 	`
`00000103	106.91724396	[22760] [MiKTeX] TRACE miktex-console.core - setting env MIKTEX_GS_LIB=C:\00-Max\98-ExtraPrograms\ghostscript\base;C:\00-Max\98-ExtraPrograms\fonts 	`
`00000104	106.91725922	[22760] [MiKTeX] TRACE miktex-console.core - setting env TEMPDIR=C:\Users\a150106\AppData\Local\Temp\ 	`
`00000105	106.91728210	[22760] [MiKTeX] TRACE miktex-console.core - setting env TMPDIR=C:\Users\a150106\AppData\Local\Temp\ 	`
`00000106	106.91729736	[22760] [MiKTeX] TRACE miktex-console.core - setting env HOME=C:\Users\a150106 	`
`00000107	106.91731262	[22760] [MiKTeX] TRACE miktex-console.core - setting env MIKTEX_CWDLIST= 	`
`00000108	106.91732788	[22760] [MiKTeX] TRACE miktex-console.core - admin mode: no 	`
`00000109	106.91735077	[22760] [MiKTeX] TRACE miktex-console.core - shared setup: no 	`
`00000110	106.91736603	[22760] [MiKTeX] TRACE miktex-console.core - session locale: "" 	`
`00000111	106.91738892	[22760] [MiKTeX] TRACE miktex-console.core - setting env MIKTEX_LOG_DIR=C:\Users\a150106\AppData\Local\MiKTeX\2.9\miktex\log 	`
`00000112	106.91740417	[22760] [MiKTeX] TRACE miktex-console.core - setting env MIKTEX_LOG_NAME=miktex-console 	`
`00000113	106.91752625	[22760] [MiKTeX] INFO  main - starting: MiKTeX Console 2.9.7206 (MiKTeX 2.9.7250 64-bit) 	`
`00000114	106.91916656	[22760] [MiKTeX] TRACE miktex-console.core - parsing: C:\00-Max\98-ExtraPrograms\miktex\config\packages.ini... 	`
`00000115	107.14004517	[22760] [MiKTeX] TRACE miktex-console.core - parsing: C:\Users\a150106\AppData\Roaming\MiKTeX\2.9\miktex/config\console.ini... 	`
`00000116	107.15261078	[22760] [MiKTeX] TRACE miktex-console.core - parsing: C:\00-Max\98-ExtraPrograms\miktex/config\package-manifests.ini... 	`
`00000117	107.57584381	[22760] [MiKTeX] TRACE miktex-console.core - parsing: C:\00-Max\98-ExtraPrograms\miktex\config\packages.ini... 	`
`00000118	108.03441620	[22760] [MiKTeX] TRACE miktex-console.core - parsing: C:\00-Max\98-ExtraPrograms\miktex/config\formats.ini... 	`
`00000119	108.03660583	[22760] [MiKTeX] TRACE miktex-console.core - parsing: C:\00-Max\98-ExtraPrograms\miktex/config\languages.ini... 	`
`00000120	114.84235382	[22760] QWindowsContext::windowsProc: No Qt Window found for event 0x46 (WM_WINDOWPOSCHANGING), hwnd=0x0x60d5c.	`

==============================================

As per guidelines:

I have not installed updates as I have not been able to.  I have attached
[miktex-console.log](https://github.com/MiKTeX/miktex/files/4059807/miktex-console.log)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/4059829/miktex-report.txt)

**Comment by edocevoli** [comment]
Thank you. It seems that MiKTeX is not compatible with your Windows setup. Since I cannot reproduce the issue on my computer, it is not possible at the moment to provide a fix.
