### ISSUE TITLE
ps2pdf error code 255

### ISSUE THREAD

**Issue by moremath18** [MiKTeX/miktex#453]
I am running Winedt 10.3 along with ghostscript 9.50. I updated all of the miktex 2.9 packages. I have installed the LaTeXify_102.  I can compile to dvi and then to ps, but when I try to use the ps2pdf command, I get the error code 255.

Here is the preamble of my code:

\documentclass[12pt]{article}
%
% Page length commands go here in the preamble
\setlength{\oddsidemargin}{-0.25in} % Left margin of 1 in + 0 in = 1 in
\setlength{\textwidth}{7in}   % Right margin of 8.5 in - 1 in - 6.5 in = 1 in
\setlength{\topmargin}{0in}  % Top margin of 2 in -0.75 in = 1 in
\setlength{\textheight}{9.2in}  % Lower margin of 11 in - 9 in - 1 in = 1 in
%
\renewcommand{\baselinestretch}{1.5} 
% 1.5 denotes double spacing. Changing it will change the spacing
%
\setlength{\parindent}{0in}
%
\begin{document}
\abstract{In response to an increase in blood glucose levels, insulin is released into the bloodstream by the pancreatic islets of Langerhans.  As a result of this influx of glucose, the islets start what are called bursting oscillations of the membrane potential and the intracellular calcium concentration.  Time delays of several seconds in the activity of distant cells in the islets have been observed, indicating the presence of traveling waves through the islets.}
\end{document}

Any assistance would be greatly appreciated.

Heather

[Test.log](https://github.com/MiKTeX/miktex/files/4078385/Test.log)

**Comment by edocevoli** [comment]
I works for me, i.e.,

```
latex test.tex
dvips test.tex
ps2pdf test.tex
```

Attached the resulting PDF.
[test.pdf](https://github.com/MiKTeX/miktex/files/4078897/test.pdf)

**Comment by moremath18** [comment]
So why will it not compile through Winedt?  There is clearly some sort of configuration error between Miktex and Winedt.  How can we diagnose the issue?HeatherSent from Samsung tablet
-------- Original message --------From: Christian Schenk <notifications@github.com> Date: 1/17/20  2:15 PM  (GMT-06:00) To: MiKTeX/miktex <miktex@noreply.github.com> Cc: moremath18 <heather.moreland@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MiKTeX/miktex] ps2pdf error code 255 (#453) I works for me, i.e.,
latex test.tex
dvips test.tex
ps2pdf test.tex

Attached the resulting PDF.
test.pdf

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MiKTeX/miktex/issues/453?email_source=notifications\u0026email_token=AOJ3ZS3FFD33QLE7REQCKCDQ6IGUXA5CNFSM4KIMIEV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJI25UY#issuecomment-575778515",
"url": "https://github.com/MiKTeX/miktex/issues/453?email_source=notifications\u0026email_token=AOJ3ZS3FFD33QLE7REQCKCDQ6IGUXA5CNFSM4KIMIEV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJI25UY#issuecomment-575778515",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by edocevoli** [comment]
Warning: your email-address is now visible to the world. I would recommend that you edit your comment here: https://github.com/MiKTeX/miktex/issues/453#issuecomment-575780476

I would recommend, that in the future you do not reply to the GitHub issue notifications.

**Comment by edocevoli** [comment]
> How can we diagnose the issue

Please read the contribution guidelines.

**Comment by moremath18** [comment]
I was told to post here since this seemed to be an issue with Miktex and Winedt execution modes.  I do not understand why this cannot be diagnosed.

**Comment by edocevoli** [comment]
It can be diagnosed on your computer only. So please collect all information (log files, screen shots).
