### ISSUE TITLE
MiKTeX fails to find input file with spaces in path

### ISSUE THREAD

**Issue by GHKovacs** [MiKTeX/miktex#455]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md

Dear deveolpers of MiKTeX,

I am using MiKTeX in combination with LyX for several projects. My operating system is Windows 10. Recently I updated MiKTeX to the latest version, but now my LaTeX files fail to compile. I have attached a small example in MiKTeX_bug_report.zip.

- Please unpack this archive to an arbitrary directory.

- Use "subst X: <your path>\MiKTeX_bug_report" to create drive X: pointing to the example.

- Navigate to "X:\Temp\MiKTeX 2.9.7250 64-bit" and try to run "pdflatex main_file.tex". This command fails, because MiKTeX does not find the input-file. With my previous version (in directory "X:\Temp\MiKTeX 2.9.6840 64-bit") everything worked fine. According to my analysis, the latest version of MikTeX has problems with the quotes in \def\input@path (line 3) and \input (line 11) with are, according to my knowledge, perfectly legal for file- and pathnames in Windows. Actually, for the previous version of MiKTeX these quotes were mandatory for file- and pathnames with spaces.
If I remove them (see "main_file_no_quotes.tex"), everything works fine again in the latest version. Unfotunately, the quotes in line 3 are automatically inserted by LyX and I cannot change this behaviour.

- I observed the same problem after a new installation of the the latest version of MiKTeX; so it is not a problem of an update from a previous version.

- I also included the log files of my installation in miktex_log.zip

I hope, you can fix this problem and find a solution compatible with previous version.

Best regards,
Günter Kovacs

[MiKTeX_bug_report.zip](https://github.com/MiKTeX/miktex/files/4087967/MiKTeX_bug_report.zip)
[miktex_log.zip](https://github.com/MiKTeX/miktex/files/4087968/miktex_log.zip)

**Comment by edocevoli** [comment]
Thank you. IMHO this is not a MiKTeX-specific issue. I cannot even say if this a bug or a feature. Please consider creating a LaTeX bug report: https://www.latex-project.org/bugs/
