### ISSUE TITLE
dvipng 1.16 with pk fonts error on Win32

### ISSUE THREAD

**Issue by aafin** [MiKTeX/miktex#459]
Command like "dvipng -v  --freetype1   q.idv -o q1x.png" is OK.

Command like "dvipng -v  --freetype0   q.idv -o q1x.png"  returns error with message:
------------ 
This is dvipng 1.16 Copyright 2002-2015, 2019 Jan-Ake Larsson
' TeX output 2020.01.29:1923' -> q1x.png
[1<G:\miktex\texmfs/data\fonts/pk/cx/public/cm/dpi400\cmr10.pk>
dvipng: Fatal error, PK file G:\miktex\texmfs/data\fonts/pk/cx/public/cm/dpi400\cmr10.pk ends prematurely
--------------
ps: maybe it was fixed in dvipng 1.17
http://git.savannah.nongnu.org/cgit/dvipng.git/commit/?id=f3ff241827a587e3d39eda477041fd3280f5b245

**Comment by edocevoli** [comment]
MiKTeX-dvipng 1.17 is now available.
