### ISSUE TITLE
Internal miktex error when calling TEXINDEX

### ISSUE THREAD

**Issue by jeroen** [MiKTeX/miktex#460]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hi, I maintain the Windows builds of the R programming language. 

Since the last release of miktex `basic-miktex-2.9.7269-x64.exe` end november our build script started failing on Windows. The bash line that calls texindex immediately exists:

```sh
export TEXINDEX=C:/rtools40/usr/bin/texindex.exe 
texify --pdf --texinfo="@set UseExternalXrefs " R-FAQ.texi
```
```
ERROR: MiKTeX encountered an internal error.
ERROR: Info:
ERROR: Source: Libraries\MiKTeX\Core\Session/SessionImpl.h
ERROR: Line: 640

Sorry, but "MiKTeX Compiler Driver" did not succeed.
```
This did not happen with the previous release `basic-miktex-2.9.7152-x64.exe`.

I suspect the problem is related to texify not properly invoking texindex.exe or `--texinfo` but I cannot debug any futher what is going wrong. I tried calling with `-V` but this doesn't give any extra output.

**Comment by edocevoli** [comment]
Thank you. Since `--texinfo` is an unknown option, the program terminates (unfortunately with a an internal error). So:

```
texify --pdf --covefe="asdasd" test.texi
```

would also trigger the internal error. The correct behaviour would be to terminate with better error message. I will fix this.

**Comment by jeroen** [comment]
Thank you. When did this option become unsupported? We used this script for many years and the option is described in the documentation: https://docs.miktex.org/manual/texify.html

**Comment by edocevoli** [comment]
Since `texindex` is not a part of the MiKTeX distribution, someone was under the impression that texinfo support has to be removed altogether. I will see if this can be reverted.

**Comment by jeroen** [comment]
OK, thank you, much appreciated :)

**Comment by gwd999** [comment]
Short note: I managed a successful build of [R] .pdf documentation with MiKTeX 2.9.7015. So this seems to be the last "functioning" version. But I am by no means a TeX/MiKTeX expert. Just letting you Pro's know.

**Comment by jeroen** [comment]
Thank you, let me know if there is something that needs testing.

By the way, what was the rationale for removing `texi2dvi` (texindex) from miktex (about 4 years ago)? We are currently using a mix of tools to build the `texi` manuals on Windows.

**Comment by gwd999** [comment]
R Manuals again build like a charm (under WIN) ... great work - thnx!
