### ISSUE TITLE
Texworks doesn't launch

### ISSUE THREAD

**Issue by lfmcmillan** [MiKTeX/miktex#461]
I am running Windows 10 Home and I have Miktex installed.

I have run Miktex in the past, but when I tried to run it today it launched successfully once, and then when I tried to open a different file (by double-clicking on the tex file) it didn't launch. Then I tried to launch the app by double-clicking on the taskbar icon, and by selecting the app in Windows search, and by navigating to the miktex\bin\ folder and double-clicking on Texworks.exe. Every one of these starts up a new process in Task Manager, but none of them launch the application window.

I tried restarting my computer. No effect. I tried uninstalling and reinstalling Miktex, no effect. I am now completely unable to run Miktex.

I cannot check the Miktex log because no \log folder exists within the \Miktex 2.9\miktex\ folder.

Please tell me what I can do to get MikTex TexWorks working again, thanks.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by lfmcmillan** [comment]
OK, it finally opened, but not for another 10 minutes.

**Comment by lfmcmillan** [comment]
Miktex is practically unusable on my Windows machine, because it takes 10 minutes for the application window to appear, another 10 minutes if I try to load another tex file at the same time, and >30 minutes to fail to load a 3rd tex file at the same time.

**Comment by edocevoli** [comment]
Thank you. Please zip the the log directories:

```
%PROGRAMDATA%\MiKTeX\2.9\miktex\logdir
%PROGRAMDATA%\MiKTeX\2.9\miktex\log
```

**Comment by lfmcmillan** [comment]
Hi, there isn't a \miktex\2.9\miktex\logdir directory, but I've attached the zipped \log directory. Thanks.
[log.zip](https://github.com/MiKTeX/miktex/files/4268752/log.zip)

**Comment by edocevoli** [comment]
Thanks. There is another log directory here:

```
%LOCALAPPDATA%\MiKTeX\2.9\miktex\log
```

I think this is more interesting because it contains the TeXworks log file.

**Comment by lfmcmillan** [comment]
OK, thanks, this is the LOCALAPPDATA log zip
[log.zip](https://github.com/MiKTeX/miktex/files/4269008/log.zip)

**Comment by edocevoli** [comment]
Thank you. What puzzles me:

```
2020-02-06 16:31:29,929+1300 INFO  texworks - starting: MiKTeX TeXworks 0.6.3 (MiKTeX 2.9.7300 64-bit)
2020-02-06 16:37:11,128+1300 INFO  texworks - starting: MiKTeX TeXworks 0.6.3 (MiKTeX 2.9.7250 64-bit)
```

That is, on Feb 06 16:31 you where running MiKTeX 2.9.7300. Then six minutes later: MiKTeX 2.9.7250. Did you reinstall MiKTeX?

**Comment by lfmcmillan** [comment]
Yes, since I was having problems I thought I'd start by installing the
latest version instead.

Oh, I see, the number changed *down*...

This is weird, because the actual installer file I downloaded and used on
6th Feb was called "basic-miktex-2.9.7269-x64.exe" which doesn't match
either of those numbers

**Comment by mattyj632** [comment]
I am having similar problems. TexWorks starts a process that rapidly consumes 25% of the CPU (according to task manager), and eventually (>10 minutes) opens a Window, This started a few weeks ago. I have tried uninstalling and reinstalling Miktex this has not helped. Console output:
2020-03-26 15:25:42,789Z INFO  texworks - starting: MiKTeX TeXworks 0.6.4 (MiKTeX 2.9.7350 64-bit)
2020-03-26 16:22:49,229Z INFO  texworks - starting: MiKTeX TeXworks 0.6.4 (MiKTeX 2.9.7350 64-bit)
File name of installer file was  basic-miktex-2.9.7386-x64.exe

I believe texWorks ceased to work properly when there was a network change associated with an open file on a network drive. Can there be a corrupt configuration file or orphaned (hidden) process?

**Comment by edocevoli** [comment]
On startup, TeXworks updates some files in the user home directory. It's possible to watch it:

1. start [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview)
1. open a command-prompt window and enter:
```
set MIKTEX_TRACE=texworks
miktex-texworks /path/to/your/document
```
1. save the debug trace

**Comment by mattyj632** [comment]
Thanks for the prompt reply. I have followed your instructions. Here is the resulting report. The long periods where start-up hangs are evident, but I cannot see any clues here as to their cause.
[DM-PHY-126.LOG](https://github.com/MiKTeX/miktex/files/4392758/DM-PHY-126.LOG)

I have manually edited the file path to remove some personal info.

At the end of the first long period a window was available (227.79342651) with "Not Responding" in the border.  At the end of the file, a viable window with markup is visible.

Typsetting with .pdf text is also very slow.

**Comment by mattyj632** [comment]
Sorry that should have been pdflatex

**Comment by edocevoli** [comment]
Thank you. Please try these work-arounds:

- delete registry `HKEY_CURRENT_USER\Software\TUG\TeXworks`
- disable the spell checker by adding this at the top of your input file:
```
%!TeX spellcheck=None
```

**Comment by mattyj632** [comment]
Thanks for those suggestions and sorry for the delayed response. It still doesn't work. Is a reset necessary after deleting the registry?

**Comment by edocevoli** [comment]
No, a reset is not necessary.

**Comment by lfmcmillan** [comment]
I'm still having this problem -- I've just installed Miktek 3rd August version on a brand new Windows 10 computer. When I try to run MikTex console, every time it just tells me "Miktex console is already running", even though there are no Miktex processes live in the Task manager. This issue is NOT fixed, and Miktex is still totally unusable for me.

**Comment by edocevoli** [comment]
Sorry to hear that MiKTeX still not works. At the moment, it is not possible to fix the issue because it is not reproducible in the lab and the provided information is not sufficient to draw conclusions. The only advise I can give at the moment: install a TeX distribution that works better for you.
