### ISSUE TITLE
METAFONT modes cannot be initialized because 'modes.mf' is missing at yap start

### ISSUE THREAD

**Issue by paultjevdh** [MiKTeX/miktex#462]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hi
Since about a week I get the following error when I start yap.
METAFONT modes cannot be initialized because 'modes.mf' is missing
This happened after a miktex update.

A reinstall of MikTeX with the current version (nov 29, 2019) solves the issue, as long as I _don't_ update.  After updating, yap won't start any more.
I would try updating everything except yap, if it weren't a required update. Thus the update cannot be deselected.

No input file is required, just start yap from the windows menu, after updating to the 5-2 version.
Best regards,

Paul

yap error report:
MiKTeX Problem Report
Message: METAFONT modes cannot be initialized because 'modes.mf' is missing.
Data: 
Source: Libraries\MiKTeX\Core\Session\mfmodes.cpp
Line: 52
MiKTeX: 2.9.7300
OS: Windows 10 Education, 64-bit, build 18363
Invokers: non-existing/explorer
SystemAdmin: no
Root0: C:\Users\Paul van der Hulst\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Paul van der Hulst\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Paul van der Hulst\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Paul van der Hulst\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Paul van der Hulst\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

C:\Users\Paul van der Hulst>initexmf --report
Date: 2020-02-06 21:30:02
MiKTeX: 2.9.7250
OS: Windows 10 Education, 64-bit, build 18363
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-02-06 21:24:13
LastUpdateAdmin: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\Paul van der Hulst\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Paul van der Hulst\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Paul van der Hulst\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Paul van der Hulst\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Paul van der Hulst\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

[log.zip](https://github.com/MiKTeX/miktex/files/4167647/log.zip)

**Comment by ivankokan** [comment]
This should have been fixed already. Check https://github.com/MiKTeX/miktex-packaging/issues/160.

**Comment by paultjevdh** [comment]
Well, on a clean install with all later updates, updated database, the modes package is not automatically installed for me.
Since the error is thrown even when I just open yap without a document, I do not know what a more minimal example would look like.
Building a LaTeX document installs a lot of other packages, but modes is not one of them.

I also tried it on my wife's computer, which was absolutely clean concerning miktex. No automatic install of modes there either. Manual install 'solves' the issue.
Paul

**Comment by edocevoli** [comment]
Seems that the file name database was not in-sync with the repository. If you want me to investigate:

- install latest MiKTeX updates as user and admin (if this is a system-wide installation)
- attach all log files
- create a configuration report (`initexmf --report`)

**Comment by paultjevdh** [comment]
Hi,
I don't know what you mean by database not in sync with the repository. I did write that I updated the database (through the console app). 
Anyway, all of this is no longer relevant, since the new miktex installer (febr 8) fixes the issue.
Paul

**Comment by edocevoli** [comment]
I don't know what you did. If you say you updated MiKTeX, there are these szenarios:

- you did update as MiKTeX user
- you did update as MiKTeX admin
- you did update as MiKTeX user and MiKTeX admin

When submitting an issue, I expect/recommend that:

- the submitter tells exactly, what she/he did
- the submitter attaches relevant log files
