### ISSUE TITLE
CentOS 8 Installation not working

### ISSUE THREAD

**Issue by gpereira--** [MiKTeX/miktex#464]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Together with the announcement of version 2.9.7300, a CentOS 8 release was also built. As I tried the same steps described in: [MiKTeX 2.9.7300](https://miktex.org/announcement/miktex-2-9-7300) and also already installed once in Fedora using these steps: [Linux Install](https://miktex.org/download), I know what to expect when installing MiKTeX. But as a used:

`sudo rpm --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD6BC243565B2087BC3F897C9277A7293F59E4889"`
`sudo curl -L -o /etc/yum.repos.d/miktex.repo https://miktex.org/download/centos/8/miktex.repo`
`sudo dnf update`
`sudo dnf install miktex`

I got this in return:

`Error:` 
 `Problem: cannot install the best candidate for the job`
`  - nothing provides liblog4cxx.so.10()(64bit) needed by miktex-2.9.7250-1.fc28.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)`

So, besides the error, it appears that the version in your repo is for Fedora 28, version 2.9.7250, and not the 2.9.7300. Any workaround known for this dependance?

**Comment by edocevoli** [comment]
Thank you. It seems that the 2.9.7300 package hasn't been uploaded to the repository. I will investigate this.
