### ISSUE TITLE
Yap slow after updates

### ISSUE THREAD

**Issue by philip-g-ratcliffe** [MiKTeX/miktex#466]
Yap has become very slow to load even simple files after the recent updates.

**Comment by edocevoli** [comment]
Can see no slow down (`latex sample2e && yap sample2e).
Please attach log files and the time of day (when you started Yap).

**Comment by philip-g-ratcliffe** [comment]
Sorry, should have got back sooner: it was very odd. Yap ran slowly (long
start-up) for a day or two (after an update) and then suddenly starting
running perfectly well.  Maybe it was some problem with my system ,,,,
 
Cheers,  Phil
