### ISSUE TITLE
METAFONT modes cannot be initialized (#462) 

### ISSUE THREAD

**Issue by paultjevdh** [MiKTeX/miktex#467]
Hi

Unfortunately, issue #462 was closed with 'not enough info' label, and a suggestion that I hadn't read the posting guidelines.  I find it peculiar that an issue is closed while at the same time it is decided that more info is needed.
I did not open the issue to get help with a bug or to complain, but to help you making MikTeX better. I took the time to write down as precise as I could what I did to reproduce the error. It is actually quite normal that a user has a different perspective than a developer on what's important to report. But remember that I try.

The closing prevented me from pointing out that complete logs were as far as I can make out posted in the original issue as a zipped log folder. 
Also, it's a bit strange that you need me to tell you whether I installed miktex as administrator or user. Apparently the logs are not sufficient to determine this? 

On the other hand, it doesn't matter since in both cases the error appears.
My normal installation is system-wide as administrator: MikTeX base and all additional packages required for a document (installation on-the-fly) are installed as administrator. MikTeX console is always run as administrator.
On your suggestion I also tried to install 'for this user only'. MikTeX console reports this as 'you have installed miktex for your private use'. The same issue happens: yap will not start, throwing the METAFONT error.

This is all true for the nov 2019 installer when updated to the current state.
The new installer of febr 8 solves it.

Best regards,
Paul
Quote:
 I don't know what you did. If you say you updated MiKTeX, there are these szenarios:

    you did update as MiKTeX user
    you did update as MiKTeX admin
    you did update as MiKTeX user and MiKTeX admin

When submitting an issue, I expect/recommend that:

    the submitter tells exactly, what she/he did
    the submitter attaches relevant log files

_Originally posted by @edocevoli in https://github.com/MiKTeX/miktex/issues/462#issuecomment-583781833_

**Comment by edocevoli** [comment]
Thank you for the information.
