### ISSUE TITLE
Can't compile any documents that aren't in the C: drive

### ISSUE THREAD

**Issue by ngocvo** [MiKTeX/miktex#469]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

After updating packages with MiKTeX Console (2020-02-10), I am no longer able to compile any `*.tex` files in any drive other than `C:`. For example, compiling this document saved as `H:\test\test.tex` fails:

```latex
\documentclass{article}

\begin{document}

test

\end{document}
```

...with the following output (and [log file](https://github.com/MiKTeX/miktex/files/4179078/test.log)):

```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 2.9.7300 64-bit)
entering extended mode

Sorry, but "C:\Users\ngoc\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\pdflatex.exe" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\ngoc\AppData\Local\MiKTeX\2.9\miktex\log\pdflatex.log
```

This is the contents of `pdflatex.log`:

```
2020-02-10 15:40:04,748+1030 INFO  pdflatex - starting with command line: "C:\Users\ngoc\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\pdflatex.exe" -interaction=nonstopmode test.tex
2020-02-10 15:40:04,761+1030 INFO  pdflatex - allowing known shell commands
2020-02-10 15:40:04,762+1030 INFO  pdflatex - enabling input (output) from (to) processes
2020-02-10 15:40:04,838+1030 FATAL pdflatex - Invalid argument: path="test.log", modeString="wb"
2020-02-10 15:40:04,838+1030 FATAL pdflatex - Info: path="test.log", modeString="wb"
2020-02-10 15:40:04,838+1030 FATAL pdflatex - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
2020-02-10 15:40:04,838+1030 FATAL pdflatex - Line: 555
2020-02-10 15:40:05,080+1030 INFO  pdflatex - finishing with exit code 1
```

# Further information

I work with several other typesetters and the documents we work on are located in network drives. Would this have anything to do with it?

# `initexmf` output

```console
> initexmf --report
Date: 2020-02-10 15:34:35
MiKTeX: 2.9.7300
OS: Windows 10 Pro, 64-bit, build 18363
SharedSetup: no
LinkTargetDirectory: C:\Users\ngoc\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2020-02-10 12:53:44
LastUpdate: 2020-02-10 12:55:53
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\ngoc\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\ngoc\AppData\Local\MiKTeX\2.9
Root2: C:\Users\ngoc\Documents\typesetting\style\texmf
Root3: C:\Users\ngoc\AppData\Local\Programs\MiKTeX 2.9
Root4: C:\ProgramData\MiKTeX\2.9
Root5: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\ngoc\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\ngoc\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\ngoc\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```

**Comment by edocevoli** [comment]
How are you starting `pdflatex`? This works for me:

```
mkdir C:\Trash\test
subst H: C:\Trash
cd /D H:\test
pdflatex test.tex
```

**Comment by ngocvo** [comment]
> How are you starting `pdflatex`?

In several ways:

- via `latexmk` using [VS Code](https://code.visualstudio.com/) with the [LaTeX Workshop extension](https://github.com/James-Yu/LaTeX-Workshop/)
- using [TeXStudio](https://www.texstudio.org/)
- on the command line

In all three cases, I get the same result when I try to compile something that isn't in `C:`.

---

I can confirm that your example also works for me. But I would like to point out that in my case, `H:` is a network drive. Would this be related to #50 by any chance?

**Comment by ngocvo** [comment]
I just tried compiling documents on the relevant network drives and it seems to be working again (?)

It probably was just an issue with our network drives that has resolved itself. Thank you for the response anyway!
