### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by michabel** [MiKTeX/miktex#47]
Setup log:
...
Skipping user root directory (C:\Users\cbm2mh\AppData\Roaming\MiKTeX\2.9)...
Skipping user root directory (C:\Users\cbm2mh\AppData\Local\MiKTeX\2.9)...
Creating fndb for common root directory (C:\ProgramData\MiKTeX\2.9)...
Creating fndb for common root directory ("C:\Program Files\MiKTeX 2.9")...
initexmf --register-shell-file-types --admin "--log-file=C:\Program Files\MiKTeX 2.9\miktex/config\uninst.log" --verbose:
initexmf --modify-path --admin "--log-file=C:\Program Files\MiKTeX 2.9\miktex/config\uninst.log" --verbose:

Sorry, but "MiKTeX Configuration Utility" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/ProgramData/MiKTeX/2.9/miktex/log/initexmf_admin.log

You may want to visit the MiKTeX project page, if you need help.

An error occurred:
  source file: Libraries\MiKTeX\Core\Process\Process.cpp
  source line: 156
  message: The executed process did not succeed.
  info: fileName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\initexmf.exe", exitCode="1"

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
initexmf_admin.log:
...
2018-01-01 09:46:05,470+0200 INFO  initexmf - Operating on the shared (system-wide) MiKTeX setup
2018-01-01 09:46:05,486+0200 FATAL initexmf - Windows API error 64: The specified network name is no longer available.

2018-01-01 09:46:05,486+0200 FATAL initexmf - Info: path="O:\Sysbat\pdftex.exe"
2018-01-01 09:46:05,486+0200 FATAL initexmf - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
2018-01-01 09:46:05,486+0200 FATAL initexmf - Line: 74
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Hi, could you help with this?
Thank you in advance,
Michael

**Comment by edocevoli** [comment]
Sorry, bit I don't cant help you. You can search the web for `ERROR_NETNAME_DELETED` (this is the error code name).
