### ISSUE TITLE
dvipdfmx errors when file name is three characters

### ISSUE THREAD

**Issue by PTW19** [MiKTeX/miktex#470]
This is about the dvipdfmx that comes with MikTex. It has suddenly started failing on items that it has worked on for years.

The log says "Conversion from UTF-8 byte sequence to wide character string did not succeed.".

After much experimentation I discovered that it only happens for files with 3-character names, such as (in my case) sla.dvi. If I copy my LaTeX file sla.tex to any 3-character file, such as abc.tex it fails at the dvipdfmx stage. If I copy it to either abcd.tex or ab.tex it works just fine.

**Comment by PTW19** [comment]
I forgot to say this is under Windows 10.

**Comment by edocevoli** [comment]
It works for me:

```
This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 2.9.7300 64-bit)
entering extended mode
(abc.tex
LaTeX2e <2020-02-02> patch level 1
L3 programming layer <2020-02-03>
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"))
("C:\Program Files\MiKTeX 2.9\tex/latex/l3backend\l3backend-xdvipdfmx.def")
No file abc.aux.
("C:\Program Files\MiKTeX 2.9\tex/latex/base\ts1cmr.fd") [1] (abc.aux) )
Output written on abc.pdf (1 page).
Transcript written on abc.log.
```

And `abc.pdf` looks fine.

**Comment by PTW19** [comment]
This is test.tex:
![Capture1](https://user-images.githubusercontent.com/60893841/74196245-b83a1700-4c54-11ea-98f7-543db28be7ae.PNG)

In the command window I type:
latex test.tex
dvipdfmx test
copy test.tex abc.tex
latex abc.tex
dvipdfmx abc

This is the log file:
![Capture2](https://user-images.githubusercontent.com/60893841/74196349-f0d9f080-4c54-11ea-97f6-33eb483ed56f.PNG)

**Comment by edocevoli** [comment]
Really, a screenshot of your input file? Is this a joke? Do you want me to fire a OCR tool in order to get to the input file? I am out.
