### ISSUE TITLE
BibTeX max_glob_strs = 10 or 20 much too small; could we have 100, please?

### ISSUE THREAD

**Issue by GuySteele** [MiKTeX/miktex#471]
I am working with ACM to revise ACM-Reference-Format.bst with some substantial new capabilities, including the processing of dates in ISO 8601 format.  To work with these complicated data structures, we need a substantial number of temporary string variables, declared using STRINGS { ... }.  This works fine with, say, TexLive, which has a version of BibTeX that can automatically adjust its allocation parameters.  However, authors working with MiKTeX tell us that the BibTeX that comes with MiKTeX has max_glob_strs set to either the original value of 10 or to a larger value of 20.  We need more like 40, and we would suggest that for today's computers a value of at least 100 would not be unreasonable going forward.  We have authors trying to prepare papers for publication with a deadline about four weeks from now.  Would it be possible to make available a MiKTeX-BibTeX with a higher value for max_glob_strs within that time frame?

Thanks,
Guy Steele
Co-chair, Fourth ACM SIGPLAN Conference on History of Programming Languages
guy.steele@oracle.com

**Comment by cbmoler** [comment]
I am one of the authors that Guy is talking about.  I am trying to use MikTeX to prepare a paper for the conference he is chairing and I am running into the BibTeX limit of 20 on the number of string globals.  He can successfully typeset my paper on his Unix machine.  But when I try with MikTeX, it won't even try to build an updated bibliography unless I remove the .aux or .bbl files he built for me.  If I do remove one of those files, then I get the "Sorry---you've exceeded BibTeX's number of string global-variables 20".  I will be happy to provide a .zip file of my entire project if that would help, but it's a lot of stuff.

Danke,
Cleve Moler
Chief Mathematician, MathWorks
moler@mathworks.com

**Comment by edocevoli** [comment]
If possible, I will increase `max_glob_strs`.

**Comment by GuySteele** [comment]
Thank you.  If this succeeds, please let us know when authors can obtain the updated version.

**Comment by GuySteele** [comment]
This appears to solve the problem, thank you.

**Comment by paulk-asert** [comment]
I still get:
```
This is BibTeX, Version 0.99d (MiKTeX 2.9.7300 64-bit)
The top-level auxiliary file: main.aux
The style file: ACM-HOPL-Reference-Format.bst
Sorry---you've exceeded BibTeX's single function space 100
(That was a fatal error)
```
