### ISSUE TITLE
dvipdfmx filename length mystery

### ISSUE THREAD

**Issue by PTW19** [MiKTeX/miktex#472]
I apologize for posting this as a new issue. The first time the conversation got marked as spam because I didn't present the information in the way the reviewer liked. The reason I used screenshots is that  I got "We don't support that file type" when I tried to upload the (.tex) file. And in any case the problem did not appear to depend on the exact contents of the test file.

I am using the latest version of MikTex on Windows 10.

Here is the story in plain text. This is my LaTeX file:

\documentclass[11pt,fleqn,twoside]{article}
\begin{document}
Test.
\end{document}

In a Windows command window I type the following:

latex test.tex
dvipdfmx test

It all works.

I then type:

copy test.tex abc.tex
latex abc.tex
dvipdfmx abc

It fails, and this is the log for the above two attempted DVI to PDF translations:

2020-02-11 08:07:23,841Z INFO  dvipdfmx - starting with command line: dvipdfmx test
2020-02-11 08:07:23,842Z WARN  dvipdfmx - running with elevated privileges
2020-02-11 08:07:23,953Z INFO  dvipdfmx - finishing with exit code 0
2020-02-11 08:08:03,304Z INFO  dvipdfmx - starting with command line: dvipdfmx abc
2020-02-11 08:08:03,305Z WARN  dvipdfmx - running with elevated privileges
2020-02-11 08:08:03,332Z FATAL dvipdfmx - Conversion from UTF-8 byte sequence to wide character string did not succeed.
2020-02-11 08:08:03,338Z INFO  dvipdfmx - finishing with exit code 1

It fails with any other three-character filename, but works when the filename is for example a.tex, ab.tex or abcd.tex.

This can't be happening to everyone because it would have been noticed. And it only started happening to me recently, on files that have worked for years if not decades. What additional tests can I perform?

**Comment by edocevoli** [comment]
Thank you, I was able to reproduce the issue.

**Comment by edocevoli** [comment]
It works for me if I say `dvipdfmx abc.dvi`.

**Comment by PTW19** [comment]
Well done. The workaround is actually very acceptable to me as I all I have had to do is edit my standard "LaTeX to PDF" script.

If the reason for the phenomenon emerges I will be very interested to know what sort of bug could have caused it. I did wonder if dvipdfmx is looking for hidden "magic" DVI file names that are 3-character, and tripping up there.

**Comment by edocevoli** [comment]
I think I have found the bug. Since this is not MiKTeX-specif, I have reported it to the dvipdfmx maintainers. Thank you for reporting the issue.

**Comment by edocevoli** [comment]
This has been fixed.
