### ISSUE TITLE
Chocolatey package broken

### ISSUE THREAD

**Issue by chrisoldwood** [MiKTeX/miktex#473]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
---
The current "latest" version of the [Windows Chocolatey package for MiKTeX](https://chocolatey.org/packages/miktex) appears to be broken. It produces the following error:

```
> choco install miktex -y
Chocolatey v0.10.15
...
Attempt to get headers for http://mirror.ox.ac.uk/sites/ctan.org/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.7269-x64.exe failed.
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://mirror.ox.ac.uk/sites/ctan.org/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.7269-x64.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
```
Presumably this is a side-effect of the new release on 8th Feb 2020 because if I substitute `2.9.7342` for `2.9.7269` in the URL above with `wget` it works.

Is there a reason why the previous release is removed from the mirrors when a new one is uploaded? It would really help if the previous releases were subject to a grace period while the Chocolatey package is being updated so that automated provisioning processes don't immediately break. The upgrade would then still be automatic once the new Chocolatey package was made available even if it lagged behind the formal release.

I appreciate that the Chocolatey package may not be under your control or high on your list of priorities, in which case can you advise on the best route (i.e. link) for downloading the "latest" binaries on a continual basis? Or alternatively do you archive older editions elsewhere that might provide a more stable link across new releases? Many thanks.

**Comment by edocevoli** [comment]
The error message says that the file is not trusted by the chocolatey package manager. What makes you think that this can be fixed by the MiKTeX maintainers?
