### ISSUE TITLE
Cannot compile xelatex after update

### ISSUE THREAD

**Issue by qiancy98** [MiKTeX/miktex#474]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I updated Miktex today and then cannot compile.
My minimal tex code is:

(File name: try.tex)

    \documentclass[a4paper,10pt]{article}
    \begin{document}
    \end{document}
My compile code is:

    latexmk.exe -xelatex try.tex

The Error says:

	Latexmk: This is Latexmk, John Collins, 26 Dec. 2019, version: 4.67.
	Latexmk: applying rule 'xelatex'...
	Rule 'xelatex': The following rules & subrules became out-of-date:
		  'xelatex'
	------------
	Run number 1 of rule 'xelatex'
	------------
	------------
	Running 'xelatex -no-pdf -recorder  "try.tex"'
	------------
	This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 2.9.7300 64-bit)

	Sorry, but xelatex did not succeed.

	The log file hopefully contains the information to get MiKTeX going again:

	  C:\Users\User Name\AppData\Local\MiKTeX\2.9\miktex\log\xelatex.log
	Latexmk: fls file doesn't appear to have been made.
	Latexmk: Errors, so I did not complete making targets
	Collected error summary (may duplicate other messages):
	  xelatex: Command for 'xelatex' gave return code 1
		  Refer to 'try.log' for details
	----------------------
	This message may duplicate earlier message.
	Latexmk: Failure in processing file 'try.tex':
	   (Pdf)LaTeX didn't generate the expected log file 'try.log'
	----------------------
	Latexmk: Use the -f option to force complete processing,
	 unless error was exceeding maximum runs, or warnings treated as errors.

The following file contains personal information and should only be downloaded by members of miktex team. (installation report included)

[log files downloaded and removed]

**Comment by edocevoli** [comment]
Starting `xelatex test.tex` on the command line works:

```
This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 2.9.7300 64-bit)
entering extended mode
(test.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"))
("C:\Program Files\MiKTeX 2.9\tex/latex/l3backend\l3backend-xdvipdfmx.def")
No file test.aux.
("C:\Program Files\MiKTeX 2.9\tex/latex/base\ts1cmr.fd") (test.aux) )
No pages of output.
Transcript written on test.log.
```

**Comment by edocevoli** [comment]
WIth this input:

```
\documentclass[a4paper,10pt]{article}
\begin{document}
hello
\end{document}
```

it works:

```
This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 2.9.7300 64-bit)
entering extended mode
(try.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"))
("C:\Program Files\MiKTeX 2.9\tex/latex/l3backend\l3backend-xdvipdfmx.def")
(try.aux) ("C:\Program Files\MiKTeX 2.9\tex/latex/base\ts1cmr.fd") [1] (try.aux
) )
Output written on try.pdf (1 page).
Transcript written on try.log.
```

(`latexmk` too)

**Comment by edocevoli** [comment]
I do not regard this a bug. If you rely on the old behaviour, I would recommend that you contact the xetex maintainers.

**Comment by qiancy98** [comment]
input:

	\documentclass[a4paper,10pt]{article}
	\begin{document}
	hello
	\end{document}

Code`xelatex try.tex`
gives

	This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 2.9.7300 64-bit)

	Sorry, but xelatex did not succeed.

	The log file hopefully contains the information to get MiKTeX going again:

	  C:\Users\User Name\AppData\Local\MiKTeX\2.9\miktex\log\xelatex.log

So you mean I should reinstall miktex?

**Comment by qiancy98** [comment]
UPD: I reinstalled miktex and the problem went.

**Comment by goyalyashpal** [comment]
@edocevoli be sure to delete the edit history of the description too, the confidential log.zip file is still visible in there
