### ISSUE TITLE
BibTeX single_fn_space = 100 is too small; could we have 1000, please?

### ISSUE THREAD

**Issue by GuySteele** [MiKTeX/miktex#475]
This is a follow-on to issue #471, now solved (thank you very much).

I am working with ACM to revise ACM-Reference-Format.bst with some substantial new capabilities, including the processing of dates in ISO 8601 format. To work with these complicated data structures, we have some fairly complicated functions, and some have more than 100 operations in them. We have authors trying to prepare papers for publication with a deadline about three weeks from now. Would it be possible to make available a MiKTeX-BibTeX with a higher value for single_fn_space within that time frame?  Raising it from 100 to 1000 would surely be sufficient.  It would also be a good idea to increase wiz_fn_space from 3000 to 30000 or so.  I estimate that these changes together would increase the working size of BibTeX by about 120 kilobytes.

Thanks,
Guy Steele
Co-chair, Fourth ACM SIGPLAN Conference on History of Programming Languages
guy.steele@oracle.com

**Comment by paulk-asert** [comment]
Currently I get:
```
This is BibTeX, Version 0.99d (MiKTeX 2.9.7300 64-bit)
The top-level auxiliary file: main.aux
The style file: ACM-HOPL-Reference-Format.bst
Sorry---you've exceeded BibTeX's single function space 100
(That was a fatal error)
```

**Comment by edocevoli** [comment]
`wiz_fn_space` already is at 1000000.

**Comment by edocevoli** [comment]
New values will be:

```
wiz_fn_space_max=30000
single_fn_space=1000
```

**Comment by edocevoli** [comment]
MiKTeX-BiBTeX now allocates memory as needed.

**Comment by GuySteele** [comment]
Hooray!  Thank you, thank you.

—Guy
