### ISSUE TITLE
Miktex not rendering inline Cap Greek Symbols

### ISSUE THREAD

**Issue by JETouma** [MiKTeX/miktex#477]
Hello,
I am using the latest miktex on Win10 Home and symbols like \Delta and \Omega & \Gamma are not rendered inline but \delta, \omega, & \gamma are. However, the cap Greek letters are rendered in \\[ \\] mode. 
Has anyone experienced this problem and if so what was the workaround? 

Thanks,
JET

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you, but I don't believe this is a MiKTeX specific issue.
