### ISSUE TITLE
Issue using the acro package

### ISSUE THREAD

**Issue by nullpunktTUD** [MiKTeX/miktex#478]
I am having an issue with MiKTeX when using the acro package. I (apparently wrongly) reported the issue in the packaging issue tracker: https://github.com/MiKTeX/miktex-packaging/issues/166#issue-568568013

I am quite sure that its related to MiKTeX and not acro, because the exact same file compiles without a hitch on my work PC. Please help or at least point me towards a place where I might find help, if you can.

**Comment by edocevoli** [comment]
I don't believe that this is a MiKTeX specific issue. Please contact the package author.

**Comment by edocevoli** [comment]
Duplicate of MiKTeX/miktex-packaging#166
