### ISSUE TITLE
MikTex working but MikTex Console doesn't open

### ISSUE THREAD

**Issue by cowlaku** [MiKTeX/miktex#479]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am working on Windows 10 version 1903. 
I modified the security settings of the MikTex 2.9 folder to give users the permission to modify (Proterties->Security->Edit->Users->Allow modify).  An error occurred when the change was applied.  Since then, I could not open the MikTex Console anymore though it could be launched.  Nor did it open when the setting was changed back.  Opening it in admin mode has the same problem.    
I manually removed Miktex and reinstalled it (version 2.9.7351).  (It updated automatically after the installation.)  The problem persists while all other functions are working.  Whenever the console is launched only an icon can be seen on the task bar with whole white preview screen as shown in the screenshot.  Is there any way I can fix it?  
Thank you. 
<img width="960" alt="MikTexQ" src="https://user-images.githubusercontent.com/10103193/75087317-81d18700-54f3-11ea-8b3a-699899511717.png">

**Comment by edocevoli** [comment]
Sorry, but without more information about your system it is not possible to help you. Please read the contribution guidelines before submitting an issue to this tracker.

**Comment by BeerStud** [comment]
What do you mean by "manually removed" MikTex? Didn't you go to <START> <SETTINGS> <Apps & Features> and remove it from there? After removing it, did you then manually remove the installation directories? They are usually left in place with, unfortunately; usually with configuration files contained in them too. Ty removing MikTex again, then removing any directories it leaves behind. I had to sign in as an 'administrator' in order to get those directories removed.

Reboot the machine and then try installing MikTeX again. Get a fresh download so you are sure to have the latest version and updates.

**Comment by cowlaku** [comment]
Thank you for your reply.  I am not sure which information about the system should be provided for this issue.  Below are the miktex-console and initexmf log file.  I could not find the miktex-console_admin.log.  No error shows up from the windows event viewer when launching the console.  Please let me know if other information is needed.  

[miktex-console.log](https://github.com/MiKTeX/miktex/files/4239605/miktex-console.log)
[initexmf.log](https://github.com/MiKTeX/miktex/files/4239606/initexmf.log)

Also following the suggestion in #239 the DbgView captures the following:

00000020	22.64212036	[19216] [MiKTeX] TRACE miktex-console.core - registering user TEXMF root: C:\Users\jialu\AppData\Roaming\MiKTeX\2.9 	
00000021	22.64222145	[19216] [MiKTeX] TRACE miktex-console.core - registering user TEXMF root: C:\Users\jialu\AppData\Local\MiKTeX\2.9 	
00000022	22.64231110	[19216] [MiKTeX] TRACE miktex-console.core - registering common TEXMF root: C:\ProgramData\MiKTeX\2.9 	
00000023	22.64240837	[19216] [MiKTeX] TRACE miktex-console.core - registering common TEXMF root: C:\Program Files\MiKTeX 2.9 	
00000024	22.64249992	[19216] [MiKTeX] TRACE miktex-console.core - registering user TEXMF root: \\MiKTeX\]MPM[ 	
00000025	22.64258385	[19216] [MiKTeX] TRACE miktex-console.core - UserData: C:\Users\jialu\AppData\Local\MiKTeX\2.9 	
00000026	22.64267731	[19216] [MiKTeX] TRACE miktex-console.core - UserConfig: C:\Users\jialu\AppData\Roaming\MiKTeX\2.9 	
00000027	22.64276505	[19216] [MiKTeX] TRACE miktex-console.core - UserInstall: C:\Users\jialu\AppData\Roaming\MiKTeX\2.9 	
00000028	22.64285660	[19216] [MiKTeX] TRACE miktex-console.core - CommonData: C:\ProgramData\MiKTeX\2.9 	
00000029	22.64294815	[19216] [MiKTeX] TRACE miktex-console.core - CommonConfig: C:\ProgramData\MiKTeX\2.9 	
00000030	22.64302444	[19216] [MiKTeX] TRACE miktex-console.core - CommonInstall: C:\Program Files\MiKTeX 2.9 	
00000031	22.64309502	[19216] [MiKTeX] TRACE miktex-console.core - application tags: miktex-console;miktex 	
00000032	22.64310455	[19216] [MiKTeX] TRACE miktex-console.core - setting env TEXSYSTEM=miktex 	
00000033	22.64312744	[19216] [MiKTeX] TRACE miktex-console.core - setting env GSC=mgs.exe 	
00000034	22.64314651	[19216] [MiKTeX] TRACE miktex-console.core - setting env MIKTEX_GS_LIB=C:\Program Files\MiKTeX 2.9\ghostscript\base;C:\Program Files\MiKTeX 2.9\fonts 	
00000035	22.64316559	[19216] [MiKTeX] TRACE miktex-console.core - setting env TEMPDIR=C:\Users\jialu\AppData\Local\Temp\ 	
00000036	22.64318466	[19216] [MiKTeX] TRACE miktex-console.core - setting env TMPDIR=C:\Users\jialu\AppData\Local\Temp\ 	
00000037	22.64319992	[19216] [MiKTeX] TRACE miktex-console.core - setting env HOME=C:\Users\jialu 	
00000038	22.64321709	[19216] [MiKTeX] TRACE miktex-console.core - setting env MIKTEX_CWDLIST= 	
00000039	22.64323425	[19216] [MiKTeX] TRACE miktex-console.core - admin mode: no 	
00000040	22.64325142	[19216] [MiKTeX] TRACE miktex-console.core - shared setup: yes 	
00000041	22.64326668	[19216] [MiKTeX] TRACE miktex-console.core - session locale: "" 	
00000042	22.64328575	[19216] [MiKTeX] TRACE miktex-console.core - setting env MIKTEX_LOG_DIR=C:\Users\jialu\AppData\Local\MiKTeX\2.9\miktex\log 	
00000043	22.64330292	[19216] [MiKTeX] TRACE miktex-console.core - setting env MIKTEX_LOG_NAME=miktex-console 	
00000044	22.64344406	[19216] [MiKTeX] INFO  main - starting: MiKTeX Console 2.9.7347 (MiKTeX 2.9.7300 64-bit) 	
00000045	22.64532471	[19216] [MiKTeX] TRACE miktex-console.core - parsing: C:\Program Files\MiKTeX 2.9\miktex\config\packages.ini... 	
00000046	22.65151215	[19216] [MiKTeX] TRACE miktex-console.core - RegCreateKeyExW (FFFFFFFF80000001, "Software\MiKTeX.org\MiKTeX\2.9\Setup") 	
00000047	23.05401802	[19216] [MiKTeX] TRACE miktex-console.core - parsing: C:\Users\jialu\AppData\Roaming\MiKTeX\2.9\miktex/config\console.ini... 	
00000048	23.07477188	[19216] [MiKTeX] TRACE miktex-console.core - parsing: C:\Users\jialu\AppData\Roaming\MiKTeX\2.9\miktex/config\package-manifests.ini... 	
00000049	23.08450317	[19216] [MiKTeX] TRACE miktex-console.core - parsing: C:\Program Files\MiKTeX 2.9\miktex/config\package-manifests.ini... 	
00000050	23.55800056	[10788] Lizard Mode: Unprivileged process	
00000051	23.55801392	[10788] Lizard Mode: Restoring app mapping	
00000052	23.62463379	[19216] [MiKTeX] TRACE miktex-console.core - parsing: C:\Program Files\MiKTeX 2.9\miktex\config\packages.ini... 	
00000053	23.71348572	[11252] [22/02/20 08:17:07.024 | tid:16516 | SCREMOTE | warning]: screenovate::HandsfreeProfile::doEndCallsProcessing() calls processing not started 	
00000054	24.21485901	[19216] [MiKTeX] TRACE miktex-console.core - parsing: C:\Program Files\MiKTeX 2.9\miktex/config\formats.ini... 	
00000055	24.21724319	[19216] [MiKTeX] TRACE miktex-console.core - parsing: C:\Program Files\MiKTeX 2.9\miktex/config\languages.ini...

**Comment by cowlaku** [comment]
> What do you mean by "manually removed" MikTex? Didn't you go to <Apps & Features> and remove it from there? After removing it, did you then manually remove the installation directories? They are usually left in place with, unfortunately; usually with configuration files contained in them too. Ty removing MikTex again, then removing any directories it leaves behind. I had to sign in as an 'administrator' in order to get those directories removed.
> 
> Reboot the machine and then try installing MikTeX again. Get a fresh download so you are sure to have the latest version and updates.

To BeerStud, 
Because the console did not work, I could not uninstall MikTex through <Apps & Features>.  I manually removed the installed Miktex 2.9 folder and User\AppData\Local\miktex folder, and cleaned the registry related to it in HKEY_CURRENT_USER and HKEY_LOCAL_MACHINE and through CCleaner registry cleaner.  I rebooted the computer and installed the latest published version.  So far the problem persists.  I am not sure if I left something in the computer when I removed it.

**Comment by TaihuLight** [comment]
```
2020-04-13 12:37:26,070+0800 INFO  main - starting: MiKTeX Console 2.9.7405 (MiKTeX 2.9.7400 NEXT 64-bit)
2020-04-13 12:37:26,158+0800 FATAL main - Configuration error: no conversion from type 0 to boolean.
2020-04-13 12:37:26,158+0800 FATAL main - finishing with exit code 1
```
Miktex cannot start but miktex working. How to fix it?
