### ISSUE TITLE
N: Skipping acquire of configured file 'universe/binary-i386/Packages' as repository 'http://miktex.org/download/ubuntu xenial InRelease' doesn't support architecture 'i386'

### ISSUE THREAD

**Issue by CSEKU160212** [MiKTeX/miktex#48]
When I run "sudo apt-get update" on ubuntu 16.04, then it shows that issue.... How can I solve this problem!!!

**Comment by edocevoli** [comment]
MiKTeX for Linux does not support the i386 architecture.

You have the option to compile MiKTeX for i386. This is not too hard.

**Comment by ndabAP** [comment]
The problem is that this occurs on a 64 bit machine. I can confirm it.

**Comment by imtav** [comment]
I experience this issue as well on 64bit.  tried adding [arch=amd64] but it just skips it now

**Comment by imtav** [comment]
On 64 bit machine, I was getting same issue.  I solved it by replacing contents of miktek.list with the following line:
deb [arch=amd64] http://miktex.org/download/ubuntu xenial universe

You can find this file in /etc/apt/sources.list.d/

**Comment by huckl3b3rry87** [comment]
For me (on 18.04) this enables the update then breaks:
```
hfebbo@ ~$  sudo apt-get install miktex
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 miktex : Depends: libcurl3 (>= 7.16.2) but it is not going to be installed
          Depends: libhunspell-1.3-0 (>= 1.3.3) but it is not installable
          Depends: libicu55 (>= 55.1-1~) but it is not installable
          Depends: libmpfr4 (>= 3.1.3) but it is not installable
          Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
E: Unable to correct problems, you have held broken packages.
hfebbo@ ~$  
```

**Comment by huckl3b3rry87** [comment]
https://github.com/MiKTeX/miktex/issues/120

not fixed...
