### ISSUE TITLE
Error to create a local repository

### ISSUE THREAD

**Issue by RicEncinas** [MiKTeX/miktex#481]
Dear people,

I need to create  a local repository for MikTex.
The development department I have been worked has developed a system to be installed on a server, in a customer. This server has no connection to the internet. Then I thought the way to deal with this situation is having a local repository, in another server which has connection to the internet.
I have tried to create a local repository in my machine to make sure it works appropriately.
Initially, I had problems to establish connection. So, I installed MikTex on my machine and configured the correct proxy settings.
Then, I could download the Basic and Essential MikTex packages. It worked all right.
The features I have used need the complete installation.
The complete download started Ok.
Unfortunately, I received the error 403 (Forbidden: Acess is denied).
I tried many times and always get the same error, even if I try other Remote Package Repositories.

Could someone, please, help?
- I would like to tell miktexsetup to use my proxy settings, without having MikTex installed;
- Download the complete MikTex package.

The command line I have used is the following:
\tmp\miktex\miktexsetup --verbose --local-package-repository=C:\MikTex_Repository_Complete --package-set=complete download

I had downloaded miktexsetup previously in the folder \tmp\miktex\

The error:
downloading http://linorg.usp.br/CTAN/systems/win32/miktex/tm/packages/calxxxx-yyyy.tar.lzma (expecting 384600 bytes)...
miktexsetup: Error response from server: 403
miktexsetup: Data: responseCode="403"

Waiting for your special response.

Kind regards.
Ricardo Encinas

**Comment by edocevoli** [comment]
`miktexsetup` respects environment variable `https_proxy`. Example:

```
set https_proxy=https://proxy.server.com:8123
```

**Comment by RicEncinas** [comment]
Hello. Thanks for your reply.
Should I use a secure connection? Only https? Or can I use http?

**Comment by edocevoli** [comment]
The scheme of the proxy server is not important, i.e., you can just say

```
set https_proxy=http://proxy.server.com:8123
```

If the proxy requires authorization, you can say

```
set https_proxy=http://username:password@proxy.server.com:8123
```

If you manually choose an HTTP MiKTeX repository (`--remote-package-repository=http://...`), you have to set `http_proxy` as well. And `ftp_proxy`, if you choose an FTP server.

**Comment by RicEncinas** [comment]
Hi. Thanks for the information.
I configured the environment variable for the system, and then restarted windows system.
And tried again now to have the complete download.
Unfortunately, I got the same error, when it is started the download of the same file.
I keep looking forward to solve this problem.
I would really appreciate if you could help again.
Thanks a lot!

**Comment by edocevoli** [comment]
Can you show the environment variables:

```
echo %https_proxy%
```

**Comment by edocevoli** [comment]
In order to get a more detailed trace:

1. Start DebugView - https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
1. Specify this option when invoking `miktexsetup`: `--trace=curl,mpm,error`
1. Save the DebugVIew log file and and attach it to this ticket
