### ISSUE TITLE
pdflatex: major issue: So far, no MiKTeX administrator has checked for updates

### ISSUE THREAD

**Issue by pjrandewijk** [MiKTeX/miktex#482]
In the Messages box of TeXstudio, I get the following output:

Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "my latex file".tex

pdflatex: major issue: So far, no MiKTeX administrator has checked for updates.

Process exited normally

I ran miktex-console_admin, clicked "Check for updates" and updated the packages, but this annoying "pdflatex: major issue: ..." message does not go away.

Somewhere, something does not get updated properly to indicate the the system was indeed updated.

The only way to get rid of it, is to run pdflatex with the added "-quiet" option, but then one will probably never get this "major issue warning".

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
The message will go away as soon as you check for updates as MiKTeX administrator. If you need more help, zip/attach the log directories:

```
%PROGRAMDATA%\MiKTeX\2.9\miktex\log
%LOCALAPPDATA%\MiKTeX\2.9\miktex\log
```

**Comment by edocevoli** [comment]
Please provide the requested info (log files).

**Comment by pjrandewijk** [comment]
Please find log data below.
[LocalAppData_log.zip](https://github.com/MiKTeX/miktex/files/4271129/LocalAppData_log.zip)
[ProgramData_log.zip](https://github.com/MiKTeX/miktex/files/4271130/ProgramData_log.zip)

**Comment by edocevoli** [comment]
Thank you. Can you please run

```
initexmf --report
```

**Comment by pjrandewijk** [comment]
Thanks, that solved the problem.
