### ISSUE TITLE
Adding a TEXMF root directory in user mode results in an error

### ISSUE THREAD

**Issue by pmeier** [MiKTeX/miktex#484]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

 # Setup

- MiKTex installation on a clean Ubuntu 18.04.4 LTS
- Two users: one admin user and one normal user (here `ann-christin`)

# Reproduction

1. Log in as a normal user (here `ann-christin`)
2. Open `miktex-console` in user mode
3. Try to add a new TEXMF root directory

# Additional information

Doing the same on the admin user works fine, although in user mode he also does not have write permissions for the file:

```bash
-rw-r--r-- 1 root root 108 Feb 29 10:06 miktexstartup.ini
```

# Error report

```
GENERAL MIKTEX INFORMATION
Date: 2020-02-29 10:46:52
MiKTeX: 2.9.7300
OS: Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64
SharedSetup: yes
LinkTargetDirectory: /usr/local/bin
PathOkay: yes
LastUpdateCheckAdmin: 2020-02-29 10:32:04
LastUpdateAdmin: 2020-02-27 17:10:54
LastUpdateDbAdmin: 2020-02-29 10:32:04
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: /home/ann-christin/.miktex/texmfs/config
Root1: /home/ann-christin/.miktex/texmfs/data
Root2: /home/ann-christin/.texmf-home
Root3: /home/ann-christin/.miktex/texmfs/install
Root4: /var/lib/miktex-texmf
Root5: /var/cache/miktex-texmf
Root6: /usr/local/share/miktex-texmf
UserInstall: /home/ann-christin/.miktex/texmfs/install
UserConfig: /home/ann-christin/.miktex/texmfs/config
UserData: /home/ann-christin/.miktex/texmfs/data
CommonInstall: /usr/local/share/miktex-texmf
CommonConfig: /var/lib/miktex-texmf
CommonData: /var/cache/miktex-texmf
Invokers: .../gdm-x-session/gnome-session-b/gnome-shell

ERROR DETAILS
Program: miktex-console
Source: Libraries/MiKTeX/Core/File/File.cpp:167
Error: Keine Berechtigung: path="/var/lib/miktex-texmf/miktex/config/miktexstartup.ini"
Details: 
  path: /var/lib/miktex-texmf/miktex/config/miktexstartup.ini
```

**Comment by pmeier** [comment]
I've tried to "fix" this by giving everyone write permissions

```
-rw-rw-rw- 1 root root 114 Mär  1 11:23 miktexstartup.ini
```

This does not fix the error but the error message changes to:

```
GENERAL MIKTEX INFORMATION
Date: 2020-03-01 11:23:12
MiKTeX: 2.9.7300
OS: Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64
SharedSetup: yes
LinkTargetDirectory: /usr/local/bin
PathOkay: yes
LastUpdateCheckAdmin: 2020-02-29 10:32:04
LastUpdateAdmin: 2020-02-27 17:10:54
LastUpdateDbAdmin: 2020-02-29 10:32:04
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: /home/ann-christin/.miktex/texmfs/config
Root1: /home/ann-christin/.miktex/texmfs/data
Root2: /home/ann-christin/.texmf-home
Root3: /home/ann-christin/.miktex/texmfs/install
Root4: /var/lib/miktex-texmf
Root5: /var/cache/miktex-texmf
Root6: /usr/local/share/miktex-texmf
UserInstall: /home/ann-christin/.miktex/texmfs/install
UserConfig: /home/ann-christin/.miktex/texmfs/config
UserData: /home/ann-christin/.miktex/texmfs/data
CommonInstall: /usr/local/share/miktex-texmf
CommonConfig: /var/lib/miktex-texmf
CommonData: /var/cache/miktex-texmf
Invokers: .../gdm-x-session/gnome-session-b/gnome-shell

ERROR DETAILS
Program: miktex-console
Source: Libraries/MiKTeX/Core/File/unx/unxFile.cpp:236
Error: Vorgang nicht zulässig: path="/var/lib/miktex-texmf/miktex/config/miktexstartup.ini"
Details: 
  path: /var/lib/miktex-texmf/miktex/config/miktexstartup.ini
```

**Comment by edocevoli** [comment]
If a TEXMF directory is added by a user, the information should be written to `~/.miktex/texmfs/config/miktex/config/miktexstartup.ini`.

**Comment by edocevoli** [comment]
I was not yet able to reproduce the problem. Please attach the log files and the various `miktexstartup.ini` files.

**Comment by pmeier** [comment]
1. Where can I find the log files?
2. Just to be clear: You want the global `miktexstartup.ini`from `/var/lib/miktex-texmf/miktex/config` as well as from `~/.miktex/texmfs/config/miktex/config`, correct?

**Comment by edocevoli** [comment]
There are two log directories: one for the MiKTeX administrator, one for the user `ann-christin`:

```
/var/cache/miktex-texmf/miktex/log
/home/ann-christin/.miktex/texmfs/data/miktex/log
```

I would recommend, that you zip both directories.

The `miktexstartup.ini` files are located here:

```
/var/lib/miktex-texmf/miktex/config/miktexstartup.ini
/home/ann-christin/.miktex/texmfs/config/miktex/config/miktexstartup.ini
```

**Comment by pmeier** [comment]
Here you go:

[miktex.zip](https://github.com/MiKTeX/miktex/files/4289079/miktex.zip)

```
.
miktex
├── admin_user
│   ├── log.zip
│   └── miktexstartup.ini
├── common
│   └── miktexstartup.ini
└── normal_user
    └── log.zip
```

The file `/home/ann-christin/.miktex/texmfs/config/miktex/config/miktexstartup.ini` as well as the directory `/var/cache/miktex-texmf/miktex/log` do not exist.

**Comment by pmeier** [comment]
Simply copying `miktexstartup.ini` from the admin user to `/home/ann-christin/.miktex/texmfs/config/miktex/config/miktexstartup.ini` solves this. I don't know why it wasn't there in the first place. 

---

Thanks for your swift support. I leave this open for now in case you want to debug this further. If that is not the case feel free to close this issue.

**Comment by pmeier** [comment]
Closing this as no further questions arose. Feel free to reopen this if you need additional logs or config files in order to debug this further.
