### ISSUE TITLE
ps2pdf not working anymore on Windows

### ISSUE THREAD

**Issue by pjrandewijk** [MiKTeX/miktex#485]
After upgrading to the latest version of MikTeX, ps2pdf is not working anymore.

No error messages, and no PDF output either.

In TeXstudio at least it says:

Process started: ps2pdf.exe "Example_0".ps

ps2pdf: major issue: So far, no MiKTeX administrator has checked for updates.

Process exited with error(s)

So, I know there is an error somewhere.

In the %LOCALAPPDATA log file ps2pdf.log, I can see that the last time I ran it with the old version of MikTeX 2.9 (more than six months ago), it "finished with exit code 0", but now with "exit code 255".

2019-06-19 07:02:11,617+0200 INFO  ps2pdf - starting with command line: ps2pdf.exe 62782-S19-LAB-II.ps
2019-06-19 07:02:14,850+0200 INFO  ps2pdf - finishing with exit code 0
2020-02-29 23:31:55,644+0100 INFO  ps2pdf - starting with command line: ps2pdf Example_0.ps
2020-02-29 23:31:55,755+0100 INFO  ps2pdf - finishing with exit code 255
2020-02-29 23:31:55,756+0100 FATAL ps2pdf - major issue: So far, no MiKTeX administrator has checked for updates.

I Googled and got to this page, https://sourceforge.net/p/miktex/discussion/33790/thread/77f76248/

I assumed that it not the "space" in the "MikTeX 2.9" path that is problem, but tried to run,

gswin64c -sDEVICE=pdfwrite -o Example_0.pdf Example_0.ps

and it works.

So not sure what the problem is with ps2pdf.exe, but here is the log file.

[ps2pdf.log](https://github.com/MiKTeX/miktex/files/4271158/ps2pdf.log)

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
I cannot reproduce this. What I have done:

```
latex sample2e
dvips sample2e
ps2pdf sample2e.ps
```

Works.

**Comment by pjrandewijk** [comment]
Hmmm, wonder what could be wrong?
epstopdf are working at least...
