### ISSUE TITLE
[MacOS] Error missing divpng/dvisvgm 

### ISSUE THREAD

**Issue by andrewcrook** [MiKTeX/miktex#488]
I keep getting the error missing divpdf/dvisvgm when rendering 
a simple equation to test the setup in Anki

[$]\frac{1}{2}[/$]

<img width="957" alt="Screenshot 2020-03-07 at 11 17 25" src="https://user-images.githubusercontent.com/803618/76142406-47282c80-6065-11ea-8518-f9680e06f6dd.png">

- MikTex doesn't seem to auto install these packages 
-  I have tried updating the packages and package list
-  tried upgrading to the basic install
- tried looking in Tex repository to manually install and I cannot see them
- Perhaps these are a separate dependancies?
In which case, having installed via brew casks, I would have thought would have been included?

could you please confirm? 

[initexmf.log](https://github.com/MiKTeX/miktex/files/4301727/initexmf.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/4301728/miktex-console.log)
[miktex-fc-cache.log](https://github.com/MiKTeX/miktex/files/4301729/miktex-fc-cache.log)
[miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/4301730/miktex-makefmt.log)
[miktex-pdftex.log](https://github.com/MiKTeX/miktex/files/4301731/miktex-pdftex.log)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/4301732/miktex-report.txt)
[mkfntmap.log](https://github.com/MiKTeX/miktex/files/4301733/mkfntmap.log)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/4301735/pdflatex.log)
[texify.log](https://github.com/MiKTeX/miktex/files/4301736/texify.log)
[texworks.log](https://github.com/MiKTeX/miktex/files/4301737/texworks.log)

**Comment by edocevoli** [comment]
Please check the [installation tutorial](https://miktex.org/howto/install-miktex-mac)

**Comment by andrewcrook** [comment]
@edocevoli  got it thanks misunderstood what the brew package did. Thanks
