### ISSUE TITLE
Please include new version of xdvipdfmx

### ISSUE THREAD

**Issue by mehrt** [MiKTeX/miktex#489]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

The current xdvipdfmx version installed by MiKTeX (2020-01-16) contains a bug that occurs when ocgx2 is used with XeLaTeX.
It's already fixed in the source. Please include the fixed version.

Reference:
[tex.stackexchange.com](https://tex.stackexchange.com/q/530386/4888)
[tug.org](https://tug.org/pipermail/tex-live/2020-February/044855.html)

**Comment by edocevoli** [comment]
MiKTEX-dvipdfmx 20200315 is now available.
