### ISSUE TITLE
All remote package repository are 'outdated'

### ISSUE THREAD

**Issue by AbdullahXO** [MiKTeX/miktex#49]
# Bug report

All remote package repository are 'outdated'.

## My check list

- [Yes] latest package versions are installed
- [No] MiKTeX log files are attached
- [Yes] the bug can be reproduced by anybody (necessary input files are attached)

## What I tried to do

Select a remote package repository from: 
MiKTex Package Manager >> Repository >> Change Package Repository 

## What I expected to happen

I expect no error message.

## What happened instead

Error message:
"The remote package repository is outdated. You have to choose another repository."
Same for any selected remote repository from the list.

**Comment by AbdullahXO** [comment]
I installed the latest version of MiKTex 2.9.6520 on Windows 10 64bit.

**Comment by boyiguo1** [comment]
Experiencing the same bug.

MiKTeX Problem Report
Message: The remote package repository is outdated. You have to choose another repository.
Data: url="https://www.pirbot.com/mirrors/ctan/systems/win32/miktex/tm/packages/"
Source: Libraries\MiKTeX\PackageManager\RestRemoteService.cpp
MiKTeX: 2.9
OS: Windows 10 Pro, 64-bit, build 15063

**Comment by Chrislan07** [comment]
I've got the same issue today. Tried several repositories already.

**Comment by edocevoli** [comment]
Thank you for the report.

This is a temporary issue. The repository list will be updated tomorrow.

More info:

Last night (CET) the server was updated with Meltdown/Spectre hot fixes. The downtime was during the nightly repository sync, i.e., CTAN didn't get the latest package updates. Most of the repositories are now behind the master repository, i.e., they are outdated.

**Comment by kiravi** [comment]
Thanks for the update edocevoli

**Comment by Chrislan07** [comment]
have Just updated MikTeX, everything is back in order, to day. Thanks a lot, for your friendly support yesterday.

**Comment by archgroove** [comment]
I have this same issue today.

**Comment by motib** [comment]
I uninstalled and re-installed the latest version 6813 32-bit for windows but this did not solve the problem.

**Comment by jasonrobwebster** [comment]
I'm getting the same error today.

**Comment by viivgit** [comment]
Same issue, tried reinstalling to no avail, and the registry tricks did not work, the issue is still here. All repositories date are Sept. 30

**Comment by swaroop-nath** [comment]
I am having this same issue. It started this morning
