### ISSUE TITLE
RStudio bibliography no longer works with MikTex 

### ISSUE THREAD

**Issue by davebernie89** [MiKTeX/miktex#492]
I am currently using the most up-to-date RStudio (Version 1.2.5033) with MikTex 2.9 and everything works, except for the Bibliography.  I am using these packages: 

\usepackage{amssymb,amsmath,amsthm}
\usepackage{graphicx}
\usepackage{hyperref,harvard}

The strange thing is that when I run the file in MikTex, I have no issues.  

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
