### ISSUE TITLE
RStudio not working with MikTex 

### ISSUE THREAD

**Issue by davebernie89** [MiKTeX/miktex#493]
I am currently using the most up-to-date RStudio (Version 1.2.5033) with MikTex 2.9 and everything works, except for the Bibliography.  When I run the file in MikTex, I have no issues, but I also use knitr occasionally, so I need my RStudio to work.

Instructions:
1. Run pdfLatex in RStudio on test.tex 

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
[test.pdf](https://github.com/MiKTeX/miktex/files/4369825/test.pdf)
[test.log](https://github.com/MiKTeX/miktex/files/4369826/test.log)
[test.synctex.gz](https://github.com/MiKTeX/miktex/files/4369827/test.synctex.gz)
[test.zip](https://github.com/MiKTeX/miktex/files/4369838/test.zip)

Here is the log file: 

This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 2.9.7300 64-bit) (preloaded format=pdflatex 2020.3.22)  23 MAR 2020 10:10
entering extended mode
**./test.tex
(test.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06>
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size12.clo"
File: size12.clo 2019/12/20 v1.4l Standard LaTeX file (size option)
)
\c@part=\count167
\c@section=\count168
\c@subsection=\count169
\c@subsubsection=\count170
\c@paragraph=\count171
\c@subparagraph=\count172
\c@figure=\count173
\c@table=\count174
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen134
)
("C:\Program Files\MiKTeX 2.9\tex/latex/hyperref\hyperref.sty"
Package: hyperref 2020/01/14 v7.00d Hypertext links for LaTeX

(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/ltxcmds\ltxcmds.sty
Package: ltxcmds 2019/12/15 v1.24 LaTeX kernel commands for general use (HO)
)
("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\iftex.sty"
Package: iftex 2020/03/06 v1.0d TeX engine tests
)
("C:\Program Files\MiKTeX 2.9\tex/latex/pdftexcmds\pdftexcmds.sty"
Package: pdftexcmds 2019/11/24 v0.31 Utility functions of pdfTeX for LuaTeX (HO
)

(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/infwarerr\infwarerr.sty
Package: infwarerr 2019/12/03 v1.5 Providing info/warning/error messages (HO)
)
Package pdftexcmds Info: \pdf@primitive is available.
Package pdftexcmds Info: \pdf@ifprimitive is available.
Package pdftexcmds Info: \pdfdraftmode found.
) ("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\keyval.sty"
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks15
)
(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/kvsetkeys\kvsetkeys.sty
Package: kvsetkeys 2019/12/15 v1.18 Key value parser (HO)
)
(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/kvdefinekeys\kvdefinekey
s.sty
Package: kvdefinekeys 2019-12-19 v1.6 Define keys (HO)
)
(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/pdfescape\pdfescape.sty
Package: pdfescape 2019/12/09 v1.15 Implements pdfTeX's escape features (HO)
) (C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/latex/hycolor\hycolor.sty
Package: hycolor 2020-01-27 v1.10 Color options for hyperref/bookmark (HO)
)
(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/latex/letltxmacro\letltxmacro.st
y
Package: letltxmacro 2019/12/03 v1.6 Let assignment for LaTeX macros (HO)
) (C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/latex/auxhook\auxhook.sty
Package: auxhook 2019-12-17 v1.6 Hooks for auxiliary files (HO)
)
(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/latex/kvoptions\kvoptions.sty
Package: kvoptions 2019/11/29 v3.13 Key value format for package options (HO)
)
\@linkdim=\dimen135
\Hy@linkcounter=\count175
\Hy@pagecounter=\count176

("C:\Program Files\MiKTeX 2.9\tex/latex/hyperref\pd1enc.def"
File: pd1enc.def 2020/01/14 v7.00d Hyperref: PDFDocEncoding definition (HO)
Now handling font encoding PD1 ...
... no UTF-8 mapping file for font encoding PD1
)
(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/intcalc\intcalc.sty
Package: intcalc 2019/12/15 v1.3 Expandable calculations with integers (HO)
)
(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/etexcmds\etexcmds.sty
Package: etexcmds 2019/12/15 v1.7 Avoid name clashes with e-TeX commands (HO)
)
\Hy@SavedSpaceFactor=\count177
Package hyperref Info: Hyper figures OFF on input line 4547.
Package hyperref Info: Link nesting OFF on input line 4552.
Package hyperref Info: Hyper index ON on input line 4555.
Package hyperref Info: Plain pages OFF on input line 4562.
Package hyperref Info: Backreferencing OFF on input line 4567.
Package hyperref Info: Implicit mode ON; LaTeX internals redefined.
Package hyperref Info: Bookmarks ON on input line 4800.
\c@Hy@tempcnt=\count178

("C:\Program Files\MiKTeX 2.9\tex/latex/url\url.sty"
\Urlmuskip=\muskip16
Package: url 2013/09/16  ver 3.4  Verb mode for urls, etc.
)
LaTeX Info: Redefining \url on input line 5159.
\XeTeXLinkMargin=\dimen136

(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/bitset\bitset.sty
Package: bitset 2019/12/09 v1.3 Handle bit-vector datatype (HO)

(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/bigintcalc\bigintcalc.st
y
Package: bigintcalc 2019/12/15 v1.5 Expandable calculations on big integers (HO
)
))
\Fld@menulength=\count179
\Field@Width=\dimen137
\Fld@charsize=\dimen138
Package hyperref Info: Hyper figures OFF on input line 6430.
Package hyperref Info: Link nesting OFF on input line 6435.
Package hyperref Info: Hyper index ON on input line 6438.
Package hyperref Info: backreferencing OFF on input line 6445.
Package hyperref Info: Link coloring OFF on input line 6450.
Package hyperref Info: Link coloring with OCG OFF on input line 6455.
Package hyperref Info: PDF/A mode OFF on input line 6460.
LaTeX Info: Redefining \ref on input line 6500.
LaTeX Info: Redefining \pageref on input line 6504.

(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/atbegshi\atbegshi.sty
Package: atbegshi 2019/12/05 v1.19 At begin shipout hook (HO)
)
\Hy@abspage=\count180
\c@Item=\count181
\c@Hfootnote=\count182
)
Package hyperref Info: Driver (autodetected): hpdftex.

("C:\Program Files\MiKTeX 2.9\tex/latex/hyperref\hpdftex.def"
File: hpdftex.def 2020/01/14 v7.00d Hyperref driver for pdfTeX

(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/latex/atveryend\atveryend.sty
Package: atveryend 2019-12-11 v1.11 Hooks at the very end of document (HO)
Package atveryend Info: \enddocument detected (standard20110627).
)
\Fld@listcount=\count183
\c@bookmark@seq@number=\count184

(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/latex/rerunfilecheck\rerunfilech
eck.sty
Package: rerunfilecheck 2019/12/05 v1.9 Rerun checks for auxiliary files (HO)

(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/uniquecounter\uniquecoun
ter.sty
Package: uniquecounter 2019/12/15 v1.4 Provide unlimited unique counter (HO)
)
Package uniquecounter Info: New unique counter `rerunfilecheck' on input line 2
86.
)
\Hy@SectionHShift=\skip49
)
(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/latex/harvard\harvard.sty
Package: harvard 

("C:\Program Files\MiKTeX 2.9\tex/latex/base\ifthen.sty"
Package: ifthen 2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
))
("C:\Program Files\MiKTeX 2.9\tex/latex/l3backend\l3backend-pdfmode.def"
File: l3backend-pdfmode.def 2020-03-12 L3 backend support: PDF mode
\l__kernel_color_stack_int=\count185
\l__pdf_internal_box=\box45
)
No file test.aux.
\openout1 = `test.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
LaTeX Font Info:    Checking defaults for PD1/pdf/m/n on input line 6.
LaTeX Font Info:    ... okay on input line 6.
\AtBeginShipoutBox=\box46
Package hyperref Info: Link coloring OFF on input line 6.
("C:\Program Files\MiKTeX 2.9\tex/latex/hyperref\nameref.sty"
Package: nameref 2019/09/16 v2.46 Cross-referencing by name of section

(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/latex/refcount\refcount.sty
Package: refcount 2019/12/15 v3.6 Data extraction from label references (HO)
)
(C:\Users\david\AppData\Roaming\MiKTeX\2.9\tex/generic/gettitlestring\gettitles
tring.sty
Package: gettitlestring 2019/12/15 v1.6 Cleanup title references (HO)
)
\c@section@level=\count186
)
LaTeX Info: Redefining \ref on input line 6.
LaTeX Info: Redefining \pageref on input line 6.
LaTeX Info: Redefining \nameref on input line 6.
\@outlinefile=\write3
\openout3 = `test.out'.

LaTeX Warning: Citation 'CHARNIGO_ETAL:2011' on page 1 undefined on input line 
26.

No file test.bbl.
Package atveryend Info: Empty hook `BeforeClearDocument' on input line 34.
[1

{C:/Users/david/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
Package atveryend Info: Empty hook `AfterLastShipout' on input line 34.
 (test.aux)
Package atveryend Info: Executing hook `AtVeryEndDocument' on input line 34.
Package atveryend Info: Executing hook `AtEndAfterFileList' on input line 34.

Package rerunfilecheck Warning: File `test.out' has changed.
(rerunfilecheck)                Rerun to get outlines right
(rerunfilecheck)                or use package `bookmark'.

Package rerunfilecheck Info: Checksums for `test.out':
(rerunfilecheck)             Before: <no file>
(rerunfilecheck)             After:  A02D95553E30B97FF125B1AA17CF9044;47.
Package atveryend Info: Empty hook `AtVeryVeryEnd' on input line 34.
 ) 
Here is how much of TeX's memory you used:
 4549 strings out of 480934
 71969 string characters out of 2909682
 329039 words of memory out of 3000000
 20379 multiletter control sequences out of 15000+200000
 534802 words of font info for 32 fonts, out of 3000000 for 9000
 1141 hyphenation exceptions out of 8191
 34i,4n,29p,194b,309s stack positions out of 5000i,500n,10000p,200000b,50000s
<C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmbx12.pfb><C:/Pr
ogram Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmcsc10.pfb><C:/Program F
iles/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr12.pfb><C:/Program Files/MiKT
eX 2.9/fonts/type1/public/amsfonts/cm/cmti12.pfb>
Output written on test.pdf (1 page, 44086 bytes).
PDF statistics:
 28 PDF objects out of 1000 (max. 8388607)
 3 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

**Comment by edocevoli** [comment]
Thank you. If I understand you correctly, you need LaTeX support. Please note that this is not the right place to ask LaTeX related questions. This tracker is solely for MiKTeX-specific issues.
