### ISSUE TITLE
BibTeX `max_strings` has been made too small (4000) by a recent commit.

### ISSUE THREAD

**Issue by GeeLaw** [MiKTeX/miktex#494]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

## Reproduction

1. Obtain cryptobib from https://github.com/cryptobib/export.
2. Write `\bibdata{abbrev3}` in `main.aux`.
3. Run `bibtex main`.

**Expected result** BibTeX complains `I found no \citation commands---while reading file main.aux`, and processes the string definitions. It ends up with `(There was 1 error message)`.

**Actual result** BibTeX aborts when processing the string definitions:

```text
I found no \citation commands---while reading file main.aux
Sorry---you've exceeded BibTeX's number of strings 4000
Aborted at line 2232 of file abbrev3.bib
(That was a fatal error)
```

## Configuration

```text
Date: 2020-03-23 14:37:45
MiKTeX: 2.9.7350
GitInfo: 99f9351 / 2020-03-22 08:34:12
OS: Windows 10 Education, 64-bit, build 18363
SharedSetup: no
LinkTargetDirectory: C:\Users\GL\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2020-03-23 14:27:51
LastUpdate: 2020-03-23 14:05:14
LastUpdateDb: 2020-03-23 14:27:50
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: C:\Users\GL\AppData\Local\MiKTeX\Config
Root1: C:\Users\GL\AppData\Local\MiKTeX\Data
Root2: C:\Users\GL\AppData\Local\Programs\MiKTeX
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\GL\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\GL\AppData\Local\MiKTeX\Config
UserData: C:\Users\GL\AppData\Local\MiKTeX\Data
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```

## Investigation

The `bibtex-x.ini` file I have is modified on ‎Friday, ‎March ‎20, ‎2020, ‏‎11:06:56 AM, which has `max_strings = 35307` in `TeXandFriends.bibtex-x`, but it doesn't seem to affect the behavior of `bibtex.exe`. I've searched the MiKTeX folder, and it seems this limit is hardcoded in the binary after compilation.

Before a recent update, BibTeX distributed by MiKTeX could process files as large as those from cryptobib:

- By tracking back along the history, it seems that the issue is introduced in commit `1065f6525e23fb4538f4e874a38c4bec3305c45b` (`Squashed commit of the following: ...`). See line 154 (removed) of this [diff](https://github.com/MiKTeX/miktex/commit/1065f6525e23fb4538f4e874a38c4bec3305c45b#diff-4f8fc8694f792b4a7b9cf5b722529bb6).
- Tracing back again, the part of the squash commit comes from commit `d76452b9531d78c04d1176f300bafd497d70db6c` (`BibTeX memory`), where in `bibtex-miktex.ch`, the increased value `35000` of `max_strings` is discarded. See this [diff](https://github.com/MiKTeX/miktex/commit/d76452b9531d78c04d1176f300bafd497d70db6c#diff-4f8fc8694f792b4a7b9cf5b722529bb6L162).

Please increase `max_strings` to 35000 (or more) again.

## Question

In the meanwhile, I wonder how I could install an old version of a specific package. The documentation for `mpm` doesn't seem to mention that ability.

**Comment by edocevoli** [comment]
`bibtex-x.ini` is a configuration file for `bibtex8`. To increase `max_strings`, you can run

```
initexmf --set-config-value [BibTeX]max_strings=35000
```

I will increase the default value in a future MiKTeX version.

**Comment by edocevoli** [comment]
With the latest update: `max_strings` has been increased to 200000.
