### ISSUE TITLE
How to specify default CTAN mirror in Miktex?

### ISSUE THREAD

**Issue by jeroen** [MiKTeX/miktex#495]
I have a CI script for Windows that does the following many times per day:

 1. Download `https://miktex.org/download/win/basic-miktex-x64.exe`
 2. `basic-miktex-x64.exe --unattended --auto-install=yes --shared --package-set=basic`
 3. Install run this to install some extra packages:
```
  mpm --admin --update
  mpm --admin --install=fancyvrb
  mpm --admin --install=inconsolata 
  mpm --admin --install=epsf
  mpm --admin --install=preprint
```

Unfortunately step 2 and 3 randomly fail a lot with networks errors, probably because of bad CTAN mirrors. Is there some way I can set the default CTAN repository in step 2 and/or 3 to make this more robust

The same as one would do on linux with:
```
  tlmgr option repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
```

**Comment by edocevoli** [comment]
Yes, you can. Please read the documentation. At a mimimum you should have tried `mpm --help`.

**Comment by jeroen** [comment]
`mpm --help` shows a `--repository` parameter, but can I set the global default like with `tlmgr`?

**Comment by edocevoli** [comment]
You can use `initexmf` to set configuration values. I cannot recall the exact syntax at the moment.

**Comment by edocevoli** [comment]
Running `mthelp initexmf` gives some help.

**Comment by edocevoli** [comment]
And by the way, `mpm --help` shows you `--set-repository`. I am out now. RTFM.
