### ISSUE TITLE
Typo in MikTex Console

### ISSUE THREAD

**Issue by pmeier** [MiKTeX/miktex#496]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

![miktex_console](https://user-images.githubusercontent.com/6849766/78217860-1f3db480-74bd-11ea-8a52-1d60322cd9cb.png)

**Comment by edocevoli** [comment]
Fixed
