### ISSUE TITLE
Font size in MikTeX console is too small

### ISSUE THREAD

**Issue by kia999** [MiKTeX/miktex#497]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
Font size in MikTeX Console is too small for me and the size does not scale up with the size used by Windows for menus by default (in Windows 10: Parameters > Display > Increase text size).

**Comment by edocevoli** [comment]
Please make a screenshot.

**Comment by kia999** [comment]
Hello Christian ,

here is screenshot.

Igor A. Kotelnikov
igor.kotelnikov@gmail.com


пт, 3 апр. 2020 г. в 15:13, Christian Schenk <notifications@github.com>:

**Comment by edocevoli** [comment]
No, you haven't attached the screenshot. Please do not reply to the E-Mail notification (Btw: the world now knows your E-Mail address), Instead, visit the issue page:
https://github.com/MiKTeX/miktex/issues/497

**Comment by kia999** [comment]
Sorry

Igor A. Kotelnikov
igor.kotelnikov@gmail.com



пт, 3 апр. 2020 г. в 16:49, Christian Schenk <notifications@github.com>:

**Comment by edocevoli** [comment]
I am out.
