### ISSUE TITLE
Looking for archived MikTeX installers

### ISSUE THREAD

**Issue by RochaStratovan** [MiKTeX/miktex#498]
- [y] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have an old windows 8 machine with MikTex 2.9.6350 64-bit installed. I can successfully generate PDF documentation using pdflatex.

I am working on deploying a new windows 10 machine (new deploy, not an upgrade of the old machine), and I have MikTex 2.9.7380 64-bit installed. However it won't work. It exits with an obscure error (well, to me.. I'm not really a MikTex user)

```
[54]) (namespace_encircle_1_1_i_o.tex [55] [56]
Underfull \hbox (badness 1360) in paragraph at lines 142--145
\T1/phv/m/n/10 &filename[]Token[]Output, int n[]Expires[]In[]This[]Many[]Second
s, std[]::string &str[]Error[]Msg, const std[]::string &str[]
[57]
("C:\Users\build\AppData\Local\Programs\MiKTeX 2.9\tex/latex/psnfss\t1pcr.fd")
! Missing } inserted.
<inserted text>
                }
l.191 \end{DoxyEnumFields}

?
```

I want to install the old MikTex deployment and see if the error goes away. If it does, we'd just use the old version.

How can I find the old version. The oldest I can find on MikTex.org is from 2019, whereas 2.9.6350 is from 2017.

**Comment by edocevoli** [comment]
Sorry, but we don't keep old installers.
