### ISSUE TITLE
Yap crashes with eps files embedded in dvi when default rendermethod is pk

### ISSUE THREAD

**Issue by MikeHg** [MiKTeX/miktex#499]
I installed the latest miktex version on a brand new Windows 10 installation.
After successfully compiling a tex-file to dvi I tried to open the dvi file using yap with default rendermethod "pk".

However, yap crashed. In windows event log I found the following:
Application: yap.exe, Version: 2.9.6914.0, 
Name of the problematic modul: ucrtbase.dll, Version: 10.0.18362.387
Exception code: 0xc0000409

I could also reproduce that this happens due to inclusion of eps-files. Text only dvi files can be opened. Setting the default rendermethod to "dvips" fixes the problem, i.e. the document can be opened this way.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
