### ISSUE TITLE
Package manager "Miktex encountered an internal error"

### ISSUE THREAD

**Issue by raffam** [MiKTeX/miktex#5]
When you open the Package Manager and click on Task->Update Wizard you get an error message 
"Miktex encountered an internal error"

This is a common error. See for example [here](https://tex.stackexchange.com/questions/343703/cannot-start-yap-anymore-on-windows-10-miktex-encountered-an-internal-error) and [here](https://tex.stackexchange.com/questions/321659/miktex-2-9-package-manager-internal-error-trying-update-wizard)

The solution in the first link (Run Miktex settings (Admin). Under General/Maintenance you have to refresh FNDB and update formats.) did not work for me

Here is the information from "Copy to clipboard" button

> MiKTeX Problem Report
> Message: MiKTeX encountered an internal error.
> Data: 
> Source: Programs\MiKTeX\PackageManager\MFC\MpmView.cpp
> Line: 913
> MiKTeX: 2.9
> OS: Windows 10 Education, 64-bit, build 15063
> Invokers: explorer
> SystemAdmin: no
> PowerUser: no
> Root0: C:\Users\raffa\AppData\Roaming\MiKTeX\2.9
> Root1: C:\Users\raffa\AppData\Local\MiKTeX\2.9
> Root2: C:\ProgramData\MiKTeX\2.9
> Root3: C:\stata_latex
> Root4: C:\Program Files\MiKTeX 2.9
> UserInstall: C:\Users\raffa\AppData\Roaming\MiKTeX\2.9
> UserConfig: C:\Users\raffa\AppData\Roaming\MiKTeX\2.9
> UserData: C:\Users\raffa\AppData\Local\MiKTeX\2.9
> CommonInstall: C:\Program Files\MiKTeX 2.9
> CommonConfig: C:\ProgramData\MiKTeX\2.9
> CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by edocevoli** [comment]
Thank you, this has been fixed. You can run the updater now.
