### ISSUE TITLE
Console no longer starts after update

### ISSUE THREAD

**Issue by projekter** [MiKTeX/miktex#500]
After the most recent update just now, the MikTeX console no longer starts (admin or user mode doesn't matter). The following error message appears (here a protocol of the the console log):
```
2020-04-15 10:46:11,357+0200 INFO  main - starting: MiKTeX Console 2.9.7408 (MiKTeX 2.9.7400 NEXT 64-bit)
2020-04-15 10:46:11,412+0200 FATAL miktex-console.core - Configuration error: no conversion from type {type} to boolean.
2020-04-15 10:46:11,412+0200 FATAL miktex-console.core - Data: type="0"
2020-04-15 10:46:11,412+0200 FATAL miktex-console.core - Source: Libraries\MiKTeX\Core\Session\config.cpp:635
2020-04-15 10:46:11,472+0200 FATAL main - Configuration error: no conversion from type 0 to boolean.
2020-04-15 10:46:11,472+0200 FATAL main - finishing with exit code 1
```

Sadly, it does not say which configuration file or key is the issue.

`initexmf --report`:
```
Date: 2020-04-15 11:04:05
MiKTeX: 2.9.7400 NEXT
GitInfo: 223c52e / 2020-04-13 14:56:55
OS: Windows 10 Pro, 64-bit, build 18363
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-04-15 10:33:10
LastUpdateAdmin: 2020-04-15 10:37:36
LastUpdateDbAdmin: 2020-04-15 10:33:08
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: D:\Dokumente\TeX
Root2: C:\Program Files\MiKTeX 2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

Sorry, but "MiKTeX Configuration Utility" did not succeed.
```
The `initexmf` log shows precisely the same error as the console.

While after the update, the TeX programs still work fine, maybe still something went wrong during the update. Comparing the timestamps in the console and initexmf log, the error first occured during the update process, though no message was shown there. It is also interesting that the update shows some access denied messages, though no other MikTeX program was running during the update. However, the relevant error appeared in the log even before the first access denied.
[miktex-console_admin-today.log](https://github.com/MiKTeX/miktex/files/4480157/miktex-console_admin-today.log) 
[initexmf_admin-today.log](https://github.com/MiKTeX/miktex/files/4480160/initexmf_admin-today.log)

Btw., this issue also seems to have risen [here](https://github.com/MiKTeX/miktex/issues/479#issuecomment-612751899) two days ago.
And I also tried to locate the problematic key or file with Process Monitor, but there are just too many things the console does to filter out the relevant entry.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you. Please note that you are using the experimental version of MiKTeX.

**Comment by edocevoli** [comment]
That said, the bug will be fixed in a future release.

**Comment by edocevoli** [comment]
As a workaround, you can set an environment variable before running MiKTeX programs:

```
set MIKTEX_CORE_NOREGISTRY=t
initexmf --report
miktex-console
```
