### ISSUE TITLE
Missing file: xcolor.sty  - also why is it using miktex instead of texlive?

### ISSUE THREAD

**Issue by ORESoftware** [MiKTeX/miktex#501]
I am running this command:

```shell
pandoc ./test.html  --pdf-engine=pdflatex -t latex  -o  ./test.pdf  
```

I am getting this error:

```shell
Error producing PDF.
! LaTeX Error: File `xcolor.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.35 \IfFileExists

```

I installed miktex using these steps (I am on Ubuntu 19):

```shell
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889

 echo "deb http://miktex.org/download/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/miktex.list

 sudo apt-get update
```

1. what can I do to source the  xcolor.sty dependency for my program? 

2. AND.. Why is my command using miktex btw? I thought it was supposed to be using texlive...

**Comment by ORESoftware** [comment]
If it helps solve the mystery - this command worked:

```shell
pandoc ./test-2.html  --pdf-engine=xelatex -t latex  -o  ./test.pdf
```

and it didn't require the xcolor.sty file

**Comment by ORESoftware** [comment]
@edocevoli  can you answer the 2nd question 

> Why is my command using miktex?

**Comment by edocevoli** [comment]
> AND.. Why is my command using miktex btw? I thought it was supposed to be using texlive...

I suppose because MiKTeX comes first in the `PATH`. To check this:

```
which -a pdflatex
```
