### ISSUE TITLE
MiKTeX package sets

### ISSUE THREAD

**Issue by muv1** [MiKTeX/miktex#502]
I see that MiKTeX has 3 package sets:

    --package-set=SET
    Set the package set (one of: essential, basic, complete).

However I could not find a list of what is included with these. I tried this
with no luck:

    $ miktexsetup --print-info-only download
    initializing setup service...
    setup task: download
    local package repository: "D:\Desktop\MiKTeX Download Files"
    package set: complete
    remote package repository: http://ctan.math.washington.edu/tex-archive/systems/
    win32/miktex/tm/packages/

**Comment by muv1** [comment]
Run this command instead, and just cancel after few seconds:

    $ miktexsetup --verbose download
    initializing setup service...
    starting downloader...
    starting download...
    repository: https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/
    download directory: "D:\Desktop\MiKTeX Download Files"
    visiting repository https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/
    packages/...
    repository type: remote package repository
    loading package repository manifest...
    downloading https://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/
    miktex-zzdb1-2.9.tar.lzma...

The last line is a link to an archive, containing the manifest file `mpm.ini`.
Here is a section:

    [12many]
    CabMD5=78e41f641a1a0b49c79e94b6421e1988
    CabSize=383872
    Level=L
    MD5=1c74ba5c710b75403c69a7446690c919
    TimePackaged=1310767635
    Type=TarLzma
    Version=0.3

The important part is `Level=L`. Full list:

    $ grep Level mpm.ini | sort | uniq -c
    3555 Level=L
      83 Level=M
     193 Level=S
      62 Level=T

This was confusing to me, as the help lists 3 levels, not 4. So what is the last
level? I found the answer here:

    MIKTEX_ASSERT(
    PackageLevel::None < PackageLevel::Essential
    && PackageLevel::Essential < PackageLevel::Basic
    && PackageLevel::Basic < PackageLevel::Advanced
    && PackageLevel::Advanced < PackageLevel::Complete);

<https://github.com/MiKTeX/miktex/blob/a4a7a810/Libraries/MiKTeX/PackageManager/PackageInstallerImpl.cpp#L97-L101>

after some testing, this is my finding:

~~~
Level=S: essential
Level=M: basic
Level=T: advanced
Level=L: complete
~~~

**Comment by edocevoli** [comment]
Indeed, these are the four package sets. Thank you.

**Comment by muv1** [comment]
Does the `T` stand for anything? Total? Test?

**Comment by edocevoli** [comment]
Sorry. yes. `T` means "total" and includes each and every package. The ordering is

`S` < `M` < `L` < `T`

where

`S`: essential
`M`: basic
`L`: advanced
`T`: complete
