### ISSUE TITLE
misspeled words not underlined in the editor (en-US)

### ISSUE THREAD

**Issue by PlamenToby** [MiKTeX/miktex#505]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

This option is enabled in the Preferences. 

Here is the report. In the log folder, I also have the following files: miktex-console_admin.log, miktex-console_admin.log, initexmf_admin.log, miktex-fc-cache_admin.log, mkfntmap_admin.log, mpmcli_admin.log.

=============
Date: 2020-04-19 17:48:30
MiKTeX: 2.9.7380
GitInfo: 1cd259c / 2020-04-04 13:37:26
OS: Windows 10 Education, 64-bit, build 18363
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-04-18 12:14:21
LastUpdateAdmin: 2020-04-18 12:14:37
LastUpdateDbAdmin: 2020-04-18 12:14:19
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files\MiKTeX 2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by edocevoli** [comment]
Please update your MiKTeX installation and try again. If the issue is still there: please create a Zip archive containing all log files.

**Comment by PlamenToby** [comment]
Thank you. I was not sure if I should upload the file there somehow or send it to you directly. I am attaching it to this email. 
I did update the installation before that, the issue is still here.
Plamen
    On Monday, April 20, 2020, 03:05:06 AM EDT, Christian Schenk <notifications@github.com> wrote:  
 
 


Please update your MiKTeX installation and try again. If the issue is still there: please create a Zip archive containing all log files.
