### ISSUE TITLE
No MiKTeX console Window after upgrading to 2.9.7414 on Win10

### ISSUE THREAD

**Issue by WDGroll** [MiKTeX/miktex#508]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Since upgrading MiKTeX from 2.9.7300 to 2.9.7400 this morning, miktex-console doesn't bring up the main window anymore. The main process is active and listed as a background process in the Task-Manager.
OS: Windows 10 Pro 1909
[initexmf.log](https://github.com/MiKTeX/miktex/files/4516629/initexmf.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/4516645/miktex-console.log)

**Comment by edocevoli** [comment]
If the window is hidden, you can restore it by double-clicking the MiKTeX Console tray icon.
