### ISSUE TITLE
Command line options --shell-escape, --no-shell-escape, --file-line-error et --no-file-line-error

### ISSUE THREAD

**Issue by vincentb1** [MiKTeX/miktex#509]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

To reproduce the issue just type:
```
latex --help
```
I did not attach the configuration report, as I doubt that it is of any importance.

**Comment by edocevoli** [comment]
Is this a bug report or a question? Please write a few more sentences.

**Comment by vincentb1** [comment]
It is a bug report, sorry I realize it was not so clear. These command line options are supported, but they are not mentioned in the usage message produced by passing the option `--help`.
So the fix is quite simple, just add them to the usage string.

**Comment by edocevoli** [comment]
These options are not documented because MiKTeX, historically, has other option names (.eg., `-c-style-errors`). At the moment I do not intend to officially support the newer options.

**Comment by vincentb1** [comment]
@edocevoli Thank you for the feedback, FYI the bug report was triggered by this discussion on the LaTeX unofficial reference manual: https://tug.org/pipermail/latexrefman/2020q2/000557.html
