### ISSUE TITLE
miktex installation in citrix environment

### ISSUE THREAD

**Issue by adesai10** [MiKTeX/miktex#51]
# Bug report

_please remove this section if this is not a bug report_

## My check list

- [ x] latest package versions are installed
- [ ] MiKTeX log files are attached
- [ ] the bug can be reproduced by anybody (necessary input files are attached)

## What I tried to do
> I have tried a few times to do the installation (network side) and
> failed. I have a citrix xenserver environment and after installation
> of verision 2.9 and run a virtual session – I get a grey screen.

## What happened instead

# Request for enhancment

_please remove this section if this is not a request for enhancement_

**Comment by edocevoli** [comment]
Thank you. I just ran the installer and found no issues.

**Comment by adesai10** [comment]
In a Citrix vda? Then open up a virtual session?

Ankur Desai | AIR

On Jan 22, 2018, at 3:41 PM, Christian Schenk <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you. I just ran the installer and found no issues.
