### ISSUE TITLE
Long file name support

### ISSUE THREAD

**Issue by edocevoli** [MiKTeX/miktex#510]
MiKTeX does not support long file names. To reproduce:

Create a directory with an extended-length path name:

```
mkdir \\?\C:\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789
```

(The `\\?\` prefix might not be necessary on a modern Windows 10 system.)

Copy `sample2e.tex` (or any other LaTeX source) into the directory. Then start a TeX engine:

```
xelatex C:\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\abcdefghijklmnopqrstuvwxyz\0123456789\sample2e.tex
```

**Comment by e-io** [comment]
Thank you @edocevoli . I found this problem first and  spent a lot of time to check workarounds. If you needs more information about issue, contact me. I will try to check how it works with TeX live

**Comment by e-io** [comment]
I Checked Tex Live. Error is identically the same with MiKTeX.

"This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex) restricted \write18 enabled. 
entering extended mode 
! I can't find file "identify_conic_sections_written_in_rectangular_coordinates _by_eccentricity_and_write_the_equation_of_the_conic_1.tex". <*> ...y_and_write_the_equation_of_the_conic_1.tex 

Please type another input file name:"

**Comment by edocevoli** [comment]
The above use-case now works, i.e., you can specify extra-long file names. This works on all supported Windows platforms out of the box, i.e., you don't have to set the Registry value `HKLM\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled`.
