### ISSUE TITLE
How to build in Debian 10?

### ISSUE THREAD

**Issue by whereistimbo** [MiKTeX/miktex#511]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

The master branch has already supported Debian 10, however I am unable to start the build using either CMake or make. Would anyone please give instruction on how to build under Debian 10?

**Comment by edocevoli** [comment]
We use a Docker container to build MiKTeX for Debian 10. You can inspect the Dockerfile (see here: https://github.com/MiKTeX/docker-miktex-build-debian/blob/buster/Dockerfile). Or just run the container as explained in the Readme: https://github.com/MiKTeX/docker-miktex-build-debian/tree/buster

**Comment by whereistimbo** [comment]
Thanks! Works very well
