### ISSUE TITLE
File miktexsetup.exe in bin folder seems to be corrupted

### ISSUE THREAD

**Issue by RochevIP** [MiKTeX/miktex#512]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

After recent update the file miktexsetup.exe located in miktex/bin/x64 folder seems to be corrupted. If I try running it (to update my local repository) it says
> miktexsetup.exe: MiKTeX encountered an internal error.

This file is taken from `miktex-mo-bin-x64-2.9` package and its size is approximately 260 KB. For comparison: the same file downloaded from [https://miktex.org/download](url) is 6.8 MB.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
