### ISSUE TITLE
Kerberos Proxy support

### ISSUE THREAD

**Issue by christophvw** [MiKTeX/miktex#514]
I cannot connect to any repository because MiKTeX lacks support for kerberos-proxy authentication -
our corporate proxy supports Kerberos authentication only.

Please add kerberos authentication to the Console.

**Comment by christophvw** [comment]
maybe set

curl_easy_setopt(curl, CURLOPT_PROXYAUTH, CURLAUTH_ANYSAFE);

when proxy authentication is set but username/password is empty?
This should allow Negotiate (Kerberos), NTLM and NTLM with winbind.

**Comment by christophvw** [comment]
Changing the following code in CurlWebSession::Initialize() works fine.
TODO: don't ask for a username/password everytime




          if (proxySettings.user.empty())
	  {
		  SetOption(CURLOPT_PROXYUSERNAME, "");
		  SetOption(CURLOPT_PROXYPASSWORD, "");
		  SetOption(CURLOPT_PROXYAUTH, CURLAUTH_GSSNEGOTIATE);
	  }
	  else
	  {
		  SetOption(CURLOPT_PROXYAUTH, CURLAUTH_ANY);
		  userPassword = proxySettings.user;
		  userPassword += ':';
		  userPassword += proxySettings.password;
		  SetOption(CURLOPT_PROXYUSERPWD, userPassword.c_str());
	  }

**Comment by christophvw** [comment]
Maybe CurlWebSession should check if Kerberos is supported and then don't ask for the password anymore...


    long auth;
    res = curl_easy_getinfo(curlMsg->easy_handle, CURLINFO_PROXYAUTH_AVAIL, &auth);
    if ((!res) && (auth))
    {
        if (auth & CURLAUTH_NEGOTIATE)
        {
            /* Kerberos supported */
        }

    }

**Comment by edocevoli** [comment]
You will not  be asked for username/password if leave `Authentication required` unchecked:

![Capture](https://user-images.githubusercontent.com/20090840/81183746-cf687680-8faf-11ea-9788-f39caf8ac8dd.PNG)

**Comment by christophvw** [comment]
Maybe it would be helpful to add a checkbox to use the windows proxy settings and set this as default. Then the endusers won't have to configure anything at all in most cases.

This should do the trick:
https://docs.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpgetdefaultproxyconfiguration


Grüße aus Spandau

**Comment by christophvw** [comment]
Ok, forget about that. This read the proxy from the HTTP config, which is not the same as what IE will use.

The static proxy configuration can be read from registry, but that will not cover automatic configuration with a PAC file. 
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings

**Comment by christophvw** [comment]
Microsoft seems to have sample code released how to get the proxy settings (MIT license)
https://github.com/microsoft/Windows-classic-
samples/blob/master/Samples/WinhttpProxy/cpp/GetProxy.cpp

**Comment by edocevoli** [comment]
Thank you, but MiKTeX doesn't use the  WinHTTP  API.

We now let Curl pick the right authentication method. This should fix the issue.

**Comment by christophvw** [comment]
I don't think your change will be enough.

I could only get negotiate/kerberos to work when I set these as well:
SetOption(CURLOPT_PROXYUSERNAME, "");
SetOption(CURLOPT_PROXYPASSWORD, "");

And about the WinHTTP API -  I didn't ment to replace curl. But it could be a nice addition (for the windows build) to automatically get the correct proxy settings.

**Comment by edocevoli** [comment]
Okay, so then you have to enter empty credentials in order to make it work.

**Comment by christophvw** [comment]
Yes, I just gave it a try. The following code works fine:


```
    SetOption(CURLOPT_PROXYAUTH, CURLAUTH_ANY);
    if (proxySettings.authenticationRequired)
    {
      ...
    }
    else
    {
        SetOption(CURLOPT_PROXYUSERNAME, "");
        SetOption(CURLOPT_PROXYPASSWORD, "");
    }
```


But when you don't pass empty credentials you will get an error message.

**Comment by edocevoli** [comment]
No, we will not set empty credentials since this might break basic authentication. Instead, the user, when prompted for credentials, has to provide empty credentials.

**Comment by christophvw** [comment]
That's a bad idea. How should users know the proxy needs empty credentials? They will enter their Windows Credentials and it will fail.

**Comment by christophvw** [comment]
Then you should use curl_easy_getinfo with CURLINFO_PROXYAUTH_AVAIL and pass empty credentials when CURLAUTH_NEGOTIATE is available. (And don't ask anymore in this case!)

**Comment by edocevoli** [comment]
Curl honors the standard proxy variables variable. For example:

```
http_proxy=http://:@10.103.33.1:1080/
```

uses empty credentials. You have to uncheck `Use a proxy server` in the connection settings dialog.

`SetOption(CURLOPT_PROXYAUTH, CURLAUTH_ANY);` must always be executed.

**Comment by christophvw** [comment]
These variables will cause a lot of trouble as you can't set any exceptions. We cannot use them.

i,e. this will break local REST API debugging as Postman will try to send all requests to the proxy as well then.

**Comment by christophvw** [comment]
How should the change from my previous comment break basic auth?

I only set empty username and password when proxySettings.authenticationRequired is false...
This should not affect basic auth at all.

**Comment by edocevoli** [comment]
What makes you 100% sure that it does not break basic authentication? I don't want to start a code review of Curl. And since I cannot easily test it, I will stay on the safe side. Sorry.

**Comment by christophvw** [comment]
Basic auth without password? How should this work at all?
Or do you mean proxy without authentication?

**Comment by christophvw** [comment]
I made some tests with this patch and McAfee WebGateway proxy:
```
   SetOption(CURLOPT_PROXYAUTH, CURLAUTH_ANY);
    if (proxySettings.authenticationRequired)
    {
      ...
    }
    else
    {
        SetOption(CURLOPT_PROXYUSERNAME, "");
        SetOption(CURLOPT_PROXYPASSWORD, "");
    }
```

**"Authentication required" checked:**
Basic
```
[2020-05-12 08:37:56.416 +02:00] [3635] NTLM (141642121, 10.116.16.16) URL: https://api2.miktex.org
[2020-05-12 08:37:56.416 +02:00] [3635] NTLM (141642121, 10.116.16.16) Incoming credentials: Basic
[2020-05-12 08:37:56.421 +02:00] [3646] NTLM (141642121, 10.116.16.16) Authenticated: 1
```

Kerberos (expected to fail with credentials)
```
[2020-05-12 08:32:58.201 +02:00] [3612] Kerberos (141635302, 10.116.16.16) URL: https://api2.miktex.org
[2020-05-12 08:32:58.201 +02:00] [3612] Kerberos (141635302, 10.116.16.16) Added authentication method: Negotiate
[2020-05-12 08:32:58.201 +02:00] [3612] Kerberos (141635302, 10.116.16.16) Authentication didn't return values, failure ID: 4, authentication failed: 0
```



**"Authentication required" not checked:**
NTLM
```
[2020-05-12 08:34:02.688 +02:00] [3626] NTLM (141637906, 10.116.16.16) URL: https://api2.miktex.org
[2020-05-12 08:34:02.688 +02:00] [3626] NTLM (141637906, 10.116.16.16) Incoming credentials: NTLM
[2020-05-12 08:34:02.697 +02:00] [3609] NTLM (141637906, 10.116.16.16) Authenticated: 1
```

Kerberos
```
[2020-05-12 08:31:17.464 +02:00] [3635] Kerberos (141631438, 10.116.16.16) URL: https://api2.miktex.org
[2020-05-12 08:31:17.464 +02:00] [3635] Kerberos (141631438, 10.116.16.16) Incoming credentials: Negotiate 
[2020-05-12 08:31:17.465 +02:00] [3635] Kerberos (141631438, 10.116.16.16) Authenticated: 1
```

**Comment by edocevoli** [comment]
Thank you. I will consider your patch for a future release. The current release is almost out and it should fix the issue with the caveat that the user has to enter empty credentials.

**Comment by edocevoli** [comment]
Haven't tried it, but it should be possible to configure empty credentials:

![Capture](https://user-images.githubusercontent.com/20090840/81716254-74d08e00-9479-11ea-91d6-cee8e7bab9b6.PNG)

**Comment by christophvw** [comment]
Configuring empty credentials with :@fqdn does not work. Currently the user has to enable the "Requires Authentication" and click "OK" everytime on the window asking for credentials.

This is annoying...
