### ISSUE TITLE
Compatibility of intexmf with texdist

### ISSUE THREAD

**Issue by vincentb1** [MiKTeX/miktex#516]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am using MACTeX, and it is relying on [texdist](http://www.tug.org/~koch/TeXDist.html) to be able to have several distributions on the same machine. So I am trying to have both TeXLive and MiKTeX on my MAC.

So I created rather manually all the abstraction folder to make MiKTeX selectable as a texdist distribution. Everying is working fine exception for initexmf.

Here is how it works:

1. in my path I have only `/Library/TeX/texbin/`
2. `/Library/TeX/texbin` is a symlink to `Distributions/Programs/texbin`, so it points at `/Library/TeX/Distributions/Programs/texbin` 
3. `/Library/TeX/Distributions/Programs/texbin` is a symlink pointing at `../.DefaultTeX/Contents/Programs/texbin`
4. `/Library/TeX/Distributions/.DefaultTeX/Contents` is the symlink that allows one to switch between distributions, so just changing this symlink changes the current distribution. When MiKTeX is the active distribution, `/Library/TeX/Distributions/.DefaultTeX/Contents` points at `../MiKTeX.texdist/Contents`
5. Now `/Library/TeX/Distributions/MiKTeX.texdist/Contents` is a symlink that points at `../.FactoryDefaults/MiKTeX/Contents`
6. `/Library/TeX/Distributions/.FactoryDefaults/MiKTeX/Contents` is the directory that contains all the MiKTeX distribution TeXDist abstraction. Notably it has a `/Library/TeX/Distributions/.FactoryDefaults/MiKTeX/Contents/Programs/localbin` directory where I have moved all the MiKTeX symlinks that were under `usr/local/bin` after installation. And I have a symlink `/Library/TeX/Distributions/.FactoryDefaults/MiKTeX/Contents/Programs/texbin` that points at `../../../../../../../Library/TeX/Distributions/.FactoryDefaults/MiKTeX/Contents/Programs/localbin`

With all these indirections `pdflatex`, `bibtex`, `latexmk`, for those which are used are all working fine.

However if I type `initexmf --version` I get the error:

```bash
bash: /usr/local/bin/initexmf: No such file or directory
```
as it internally there were some place where `initexmf` relies on some static path. Probably some call to `truename` or someting like that is missing under the hood.

**Comment by edocevoli** [comment]
Please note that the `initexmf` target is in the `Contents/MacOS` folder of the MiKTeX disk image.
