### ISSUE TITLE
Allow non admin users to install system wide packages

### ISSUE THREAD

**Issue by christophvw** [MiKTeX/miktex#517]
We have users working on Windows terminal Servers who should be able to install packages system wide but we do not want to give them admin rights.

A better approach would be to let the MiKTeX installer create a local security group like "MiKTeX Admins" for users who should be able to install packages and give this group write access to the system wide package directory.

**Comment by edocevoli** [comment]
I don't get it. Why should this be done by the installer when a system admin can do it with standard tools:

- create group `MiKTeX addmins`
- give that group write access to the system-wide MiKTeX installation directory
- add users to the group
