### ISSUE TITLE
Allow local http mirrors

### ISSUE THREAD

**Issue by christophvw** [MiKTeX/miktex#519]
Please support local http mirrors (instead of file based ones). This would have some advantages in bigger networks.

-not restricted to a windows domain (SMB Clients need to be in the same domain, or you will need a trust between domains - or you will need a mirror for each domain)
-could be integrated into Nexus Repository OSS for easier handling (no need for a custom sync job) and better security/visibility (can perform license and security checks of packages downloaded by the users)

**Comment by gwd666** [comment]
This sounds like a really cool feature! Until then - is it maybe possible to somewhere configure that "random package repository from the internet" so that it looks at a "fixed" local http address? 

![image](https://user-images.githubusercontent.com/57595487/80726839-3b0c9880-8b05-11ea-953b-e5195dc90d87.png)

**Comment by edocevoli** [comment]
The remote package repository must be "well known". All CTAN repositories will work. But not your own server.

**Comment by gwd666** [comment]
> The remote package repository must be "well known". All CTAN repositories will work. But not your own server.

Thanks for the swift repsonse ... awesome piece of SW you build there! 

Still I am sking myself - if this "condition" cannot be relaxed somehow? 
How would my MiKTeX installation know what is "well-known" if I am eg stuck behind a firewall? I guess somewhere in the PackageRepositoryDataStore.cpp or by changing RemoteService_7400 I can maybe relax that constraint?

**Comment by s1qza** [comment]
Hi, I see that there was a plan to implement the above discussed feature with the 2.9.7450 release. 
Later on, it was removed though. Is there any change it will be implemented in the near future?
