### ISSUE TITLE
MikTeX Update Wizard break with API 3 Error

### ISSUE THREAD

**Issue by Matthiasss** [MiKTeX/miktex#52]
# Bug report

The last update Installation breaks with Windows (10) API 3 Error. Image attached. The error is, that Miktex will start mpm from the path F:\MiKTeX\miktex/bin/x64\mpm.exe.
But the real path is F:\MiKTeX\texmf\bin\x64\mpm.exe. 
I have nothing changed in installation before update and the path is unchanged written in Windows PATH.
Now MiKteX doesnt start started from WinEdt.

![miktex-snap](https://user-images.githubusercontent.com/35965191/35573735-35640ff8-05d8-11e8-8996-51ba935ef2d8.jpg)

[update.log](https://github.com/MiKTeX/miktex/files/1678306/update.log)

Matthias

**Comment by edocevoli** [comment]
How did you start the update wizard? From the Windows start menu?

I am asking because you mentioned WinEdt.

**Comment by Matthiasss** [comment]
Yes, I started it from start menu as Admin.

**Comment by Matthiasss** [comment]
Oh sorry, this was a mistake: I didn't know what "Close and comment" means ... I'm still waiting for help.

**Comment by edocevoli** [comment]
I will try to create an installation like yours in order to reproduce the bug. Can you guide me how to do it? I think the main installation directory will be `F:\MiKTeX\texmf`. Anything else I have to consider?

**Comment by edocevoli** [comment]
What I don't yet understand: you say the `mpm` executable can be found in `F:\MiKTeX\texmf\bin\x64\mpm.exe`. But if if `F:\MiKTeX\texmf` is your main installation directory, then the path should be `F:\MiKTeX\texmf\miktex\bin\x64\mpm.exe`. I think you have done something special. Can you show the output of `initexmf --report`?

**Comment by Matthiasss** [comment]
You are right: F:\MiKTeX\texmf\miktex\bin\x64\mpm.exe

[initexmf --report.txt](https://github.com/MiKTeX/miktex/files/1679184/initexmf.--report.txt)

**Comment by edocevoli** [comment]
Thank you. I was able to reproduce the bug and will make a fix available later this week.

As a workaround: you can start the update wizard directly:

    F:\MiKTeX\texmf\miktex\bin\x64\internal\miktex-update_admin.exe

The bug only occurs if MiKTeX is installed in a path ending with `\texmf`.

**Comment by Matthiasss** [comment]
Thank you for help.

**Comment by edocevoli** [comment]
I think this has been fixed. The new updater finish with out an error message.
