### ISSUE TITLE
Make MiKTeX Console usable for keyboard only users

### ISSUE THREAD

**Issue by lukaszgo1** [MiKTeX/miktex#520]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

It is not possible to use MiKteX Console with only a keyboard at least under Windows. This make it very difficult to configure MiKTeX for blind users like myself for whom keyboard is a basic method of accessing the computer.
To reproduce:
1. Start MiKteX console
2. Switch to administrator mode -  note that up to this point the UI can be navigated with tab and arrows.
3. Try to choose one of the radio buttons such as settings, packages etc. without using mouse.

I recall this worked back in 2018 when UI was not written in the QT.
I would appreciate this being fixed mainly because since switch  to the QT the Console UI has a lot of accessibility issues when used with a screen reader however reporting them is quite difficult when keyboard navigation is not possible.

**Comment by edocevoli** [comment]
It should now be possible to navigate with the Tab key.
