### ISSUE TITLE
Cannot install on Fedora 32

### ISSUE THREAD

**Issue by RAZORXKHARA33** [MiKTeX/miktex#521]
I followed the usual process for installing MikTeX on Fedora, which works for 30 and 31. However, it does not work for 32. Here's what I get after running `sudo dnf install miktex`...
` - nothing provides libmpfr.so.4()(64bit) needed by miktex-2.9.7350-1.fc30.x86_64`
But I have mpfr installed. Is this just a matter of MikTeX needing to be rebuilt for Fedora 32?

**Comment by kaepora** [comment]
@RAZORXKHARA33 I ran into the same issue, here's how I solved it (temporary workaround):

```bash
sudo ln -s /usr/lib64/libmpfr.so.6 /usr/lib64/libmpfr.so.4
wget "https://miktex.org/download/fedora/30/miktex-2.9.7400-1.fc30.x86_64.rpm"
sudo rpm -i --nodeps miktex-2.9.7400-1.fc30.x86_64.rpm
```

Works perfectly.

**Comment by edocevoli** [comment]
Fedora 32 is not yet supported. There will be a new build/repository in the near future.

**Comment by edocevoli** [comment]
The fc32 repository is now online and can be registered as follows:

```
sudo curl -L -o /etc/yum.repos.d/miktex.repo https://miktex.org/download/fedora/32/miktex.repo
```

**Comment by jpcmborges** [comment]
I followed the usual process for installing MikTeX on Fedora 32.
When I run "sudo dnf install miktex" I get the error:
"the file /usr/share/man/man5/updmap.cfg.5.gz from installation of miktek-20.6.29-1.fc32.x86_64  is in conflict with the file from package texlive-tetex-7:20190410-12.fc32.noarch"
Can anybody help me?

**Comment by jpcmborges** [comment]
[jborges @ joaoborges ~] $ sudo ln -s /usr/lib64/libmpfr.so.6 /usr/lib64/libmpfr.so.4
[sudo] password for jborges:
ln: failed to create symbolic link '/usr/lib64/libmpfr.so.4': The file exists
[jborges @ joaoborges ~] $ sudo rpm --import "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD6BC243565B2087BC3F897C9277A7293F59E4889"
[jborges @ joaoborges ~] $ wget "https://miktex.org/download/fedora/30/miktex-2.9.7400-1.fc30.x86_64.rpm"
--2020-09-10 19: 22: 26-- https://miktex.org/download/fedora/30/miktex-2.9.7400-1.fc30.x86_64.rpm
Resolving miktex.org (miktex.org) ... 5.175.24.104
Calling miktex.org (miktex.org) | 5.175.24.104 |: 443 ... connected.
HTTP request sent, waiting for response ... 302 Found
Location: https://ftp.eq.uc.pt/software/TeX/systems/win32/miktex/setup/rpm/fedora/30/miktex-2.9.7400-1.fc30.x86_64.rpm [below]
--2020-09-10 19: 22: 26-- https://ftp.eq.uc.pt/software/TeX/systems/win32/miktex/setup/rpm/fedora/30/miktex-2.9.7400- 1.fc30.x86_64.rpm
To resolve ftp.eq.uc.pt (ftp.eq.uc.pt) ... 193.137.214.36
Connecting to ftp.eq.uc.pt (ftp.eq.uc.pt) | 193.137.214.36 |: 443 ... connected.
HTTP request sent, waiting for response ... 200 OK
Size: 20811036 (20M) [application / x-redhat-package-manager]
Recording at: "miktex-2.9.7400-1.fc30.x86_64.rpm"

miktex-2.9.7400-1.fc30.x 100% [=================================>] 19 , 85M 12.7MB / s in 1.6s

2020-09-10 19:22:28 (12.7 MB / s) - "miktex-2.9.7400-1.fc30.x86_64.rpm" recorded [20811036/20811036]

[jborges @ joaoborges ~] $ sudo rpm -i --nodeps miktex-2.9.7400-1.fc30.x86_64.rpm
the /usr/share/man/man5/updmap.cfg.5.gz file from the miktex-2.9.7400-1.fc30.x86_64 installation conflicts with the texlive-tetex-7: 20190410-12 package file. fc32.noarch
