### ISSUE TITLE
Error "MiKTeX cannot retrieve attributes for the directory 'C:\WINDOWS\system32\config\systemprofile'.

### ISSUE THREAD

**Issue by alexbk66** [MiKTeX/miktex#522]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have the same issue as @dnsnx in #333 - which is closed by @edocevoli with the following comment: 

> This is not a MiKTeX issue

But it is!  
Why does it need to access 'C:\WINDOWS\system32\config\systemprofile'?  
Why does it fail if it doesn't have permissions for this folder?
How do I fix the problem?

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

Please inspect all relevant log files. You should find them in

    %LOCALAPPDATA%\MiKTeX\2.9\miktex\log

and

    %PROGRAMDATA%\MiKTeX 2.9\miktex\log

**Comment by alexbk66** [comment]
Nothing in the logs. Here's whole output:

> E:\MiKTeX.2.9\miktex\bin\pdflatex.exe -aux-directory="e:\TEMP\Reports\a0epytsc" -output-directory="e:\TEMP\Reports\a0epytsc" "e:\TEMP\Reports\a0epytsc\a0epytsc.tex"
> 
> ERROR:
> pdflatex.exe: Windows API error 5: Access is denied.pdflatex.exe: Data: path="C:\Windows\system32\config\systemprofile"
> 
> Sorry, but E:\MiKTeX.2.9\miktex\bin\pdflatex.exe did not succeed for the following reason:
> 
>   MiKTeX cannot retrieve attributes for the directory 'C:\Windows\system32\config\systemprofile'.
>

**Comment by alexbk66** [comment]
And error from EventViewer:

> Faulting application name: pdflatex.exe, version: 2.9.7338.0, time stamp: 0x5e9c2951
> Faulting module name: ucrtbase.DLL, version: 10.0.17763.132, time stamp: 0xc3ae1887
> Exception code: 0xc0000409
> Fault offset: 0x000a5d0b
> Faulting process id: 0xf08
> Faulting application start time: 0x01d61f1832512bd4
> Faulting application path: E:\MiKTeX.2.9\miktex\bin\pdflatex.exe
> Faulting module path: E:\MiKTeX.2.9\miktex\bin\ucrtbase.DLL
> Report Id: 70156d40-8b0b-11ea-817c-005056a0034d
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by alexbk66** [comment]
@edocevoli - you can't just close the issue, especially that other people reported exactly the same problem!

**Comment by alexbk66** [comment]
What's the %LOCALAPPDATA% when executing from ASP.NET (IIS)?

**Comment by edocevoli** [comment]
Sorry, but without the log files it is not possible to work on this issue. I am out.
