### ISSUE TITLE
Under IIS: "MiKTeX Configuration Utility" did not succeed.

### ISSUE THREAD

**Issue by alexbk66** [MiKTeX/miktex#525]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Installed basic-miktex-2.9.6361 on Windows Server 2012 running IIS (ASP.NET app)
Execute:

`C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\pdflatex.exe -aux-directory="e:\TEMP\Reports\o7owuq32" -output-directory="e:\TEMP\Reports\o7owuq32" "e:\TEMP\Reports\o7owuq32\o7owuq32.tex"`

```
Sorry, but "MiKTeX Configuration Utility" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/ProgramData/MiKTeX/2.9/miktex/log/initexmf.log

You may want to visit the MiKTeX project page, if you need help.

Sorry, but "C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\pdflatex.exe" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/ProgramData/MiKTeX/2.9/miktex/log/pdflatex.log
```

**C:/ProgramData/MiKTeX/2.9/miktex/log/initexmf.log**

```
2020-05-02 01:15:47,338+1000 INFO  initexmf - starting: MiKTeX Configuration Utility 2.9.6354 (MiKTeX 2.9.6350)
2020-05-02 01:15:47,344+1000 INFO  initexmf - Skipping common root directory (C:\ProgramData\MiKTeX\2.9)...
2020-05-02 01:15:47,344+1000 INFO  initexmf - Skipping common root directory ("C:\Program Files (x86)\MiKTeX 2.9")...
2020-05-02 01:15:50,704+1000 FATAL initexmf - Windows API error 5: Access is denied.

2020-05-02 01:15:50,704+1000 FATAL initexmf - Info: path="Software\MiKTeX.org\MiKTeX\2.9\Core"
2020-05-02 01:15:50,704+1000 FATAL initexmf - Source: Libraries\MiKTeX\Core\win\winRegistry.cpp
2020-05-02 01:15:50,704+1000 FATAL initexmf - Line: 186
```

**C:/ProgramData/MiKTeX/2.9/miktex/log/pdflatex.log**

```
2020-05-02 01:15:47,215+1000 INFO  pdflatex - starting with command line: "C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\pdflatex.exe" -aux-directory=e:\TEMP\Reports\o7owuq32 -output-directory=e:\TEMP\Reports\o7owuq32 e:\TEMP\Reports\o7owuq32\o7owuq32.tex
2020-05-02 01:15:47,222+1000 INFO  pdflatex - running 'initexmf --quiet --update-fndb' to refresh the file name database
2020-05-02 01:15:50,724+1000 FATAL pdflatex - The executed process did not succeed.
2020-05-02 01:15:50,724+1000 FATAL pdflatex - Info: fileName="C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\initexmf.exe", arguments="--quiet --update-fndb", exitCode="1"
2020-05-02 01:15:50,724+1000 FATAL pdflatex - Source: Libraries\MiKTeX\Core\Process\Process.cpp
2020-05-02 01:15:50,724+1000 FATAL pdflatex - Line: 159
```

**Comment by edocevoli** [comment]
I am afraid this MiKTeX version is not supported. Please install the latest updates. If the issue then still occurs: please create a Zip archive containg **all** log files.

**Comment by alexbk66** [comment]
@edocevoli - as I said in #522 - after installing the latest `basic-miktex-2.9.7417-x64` and executing pdflatex from IIS (ASP.NET) - I get the error below.

And as I said before - there's no logs created!  

```
pdflatex.exe: Windows API error 5: Access is denied.

pdflatex.exe: Data: path="C:\Windows\system32\config\systemprofile"

Sorry, but "C:\Program Files\MiKTeX 2.9\miktex\bin\x64\pdflatex.exe" did not succeed for the following reason:

  MiKTeX cannot retrieve attributes for the directory 'C:\Windows\system32\config\systemprofile'.
```

`basic-miktex-2.9.6361` gives different errors - same result. But there are logs (see abowe).

**Comment by alexbk66** [comment]
**miktex-report.txt**

```
Date: 2020-05-03 02:30:51
MiKTeX: 2.9.7400
GitInfo: 8386fcd / 2020-04-21 21:22:55
OS: Windows Server 2012 R2 Server Standard, 64-bit, build 9600
SharedSetup: yes
LinkTargetDirectory: C:\Program Files (x86)\MiKTeX 2.9\miktex\bin
PathOkay: yes
LastUpdateCheckAdmin: 2020-05-03 02:30:24
LastUpdateAdmin: not yet
LastUpdateDbAdmin: 2020-05-03 02:30:23
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files (x86)\MiKTeX 2.9
CommonInstall: C:\Program Files (x86)\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

```

**Comment by edocevoli** [comment]
Yes, that's right. The log cannot be created because MiKTeX has no write permission. It would be possible to see a live trace by running DebugView.

If you need to run MiKTeX as a service with restricted permissions, you must make sure that the service "home" directory is writable. You can specify user directories during installation. See https://docs.miktex.org/2.9/manual/setupwiz.html and and https://docs.miktex.org/manual/miktexsetup.html.

**Comment by alexbk66** [comment]
Thank you, I spent a few days trying to get this working.

Can you please elaborate on "home" directory?  For example, the docs say
```
--user-data=dir
Set the location of the data directory for the current user.
```
But it is for "current user" - i.e. the user who installs MiKTex (myself)? 
How do I set the "home" directory for the user which the service (IIS app pool) is running under?
Do I have to install MiKTex as this user - not myself?

**Comment by alexbk66** [comment]
I downloaded https://docs.microsoft.com/en-us/sysinternals/downloads/debugview - but it doesn't capture anything.  Do I have to build debug version from source myself?

**Comment by edocevoli** [comment]
No, you just need the latest executables. Anyway, we already know what's going wrong (see my last comment). So there is no need to investigate further.

**Comment by alexbk66** [comment]
@edocevoli can you please be more specific.  I spent already 5 days on this.
I used this command line:
`miktexsetup.exe  --package-set=complete --shared=yes --user-config=C:\MiKTex\cfg --user-data=C:\MiKTex\data --user-install=C:\MiKTex\inst --user-roots=C:\MiKTex\root --verbose --package-set=complete  --modify-path=yes install`

Same result.  How do I set "home" directory when executing pdflatex from IIS?

**Comment by alexbk66** [comment]
I checked, when executing from IIS - the environment vars:
```
USERPROFILE: C:\Windows\system32\config\systemprofile
APPDATA: C:\Windows\system32\config\systemprofile\AppData\Roaming
```
Which explains the problem, but how do I fix it?

**Comment by edocevoli** [comment]
The above command line looks good. It sets the three user TEXMF roots. But `miktexsetup` is quite old on CTAN. I should provide a newer version.

**Comment by edocevoli** [comment]
The three user TEXMF roots can be changed in the registry:

- registry key: `HKLM\Software\MiKTeX.org\MiKTeX\2.9\Core`
- values: `UserConfig`, `UserData`, `UserInstall`

For example:

```
reg add HKLM\Software\MiKTeX.org\MiKTeX\2.9\Core /v UserConfig /d C:\MiKTeX\cfg
reg add HKLM\Software\MiKTeX.org\MiKTeX\2.9\Core /v UserData /d C:\MiKTeX\data
reg add HKLM\Software\MiKTeX.org\MiKTeX\2.9\Core /v UserInstall /d C:\MiKTeX\inst
```

**Comment by edocevoli** [comment]
A new version of `miktexsetup` is now available.
