### ISSUE TITLE
I have gotten the following exception while building

### ISSUE THREAD

**Issue by pinkynrg** [MiKTeX/miktex#527]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

- downloaded miktex-2.9.7400
- trying to build for linux 
- got the attached exception while building at approximately 60% completion. 

![Screen Shot 2020-05-02 at 10 53 31 AM](https://user-images.githubusercontent.com/1474127/80859753-673e2b80-8c63-11ea-841e-fb7bd8cf4b5f.png)

**Comment by edocevoli** [comment]
Seems your Linux distribution is not yet supported.

**Comment by pinkynrg** [comment]
What would be the last debian version is's been built on? stretch?
