### ISSUE TITLE
Build from source with VS 2017 fails due to compiler bug

### ISSUE THREAD

**Issue by christophvw** [MiKTeX/miktex#531]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Building MiKTeX from source with VS2017 and QT 5.14.2 fails due to a compiler bug in VS2017:
https://bugreports.qt.io/browse/QTBUG-72073

Adding the following definition to "target_compile_definitions(${ui_qt_dll_name}" in "Libraries\MiKTeX\UI\Qt\CMakeLists.txt" seems to fix this.

-DQT_NO_FLOAT16_OPERATORS

**Comment by gwd999** [comment]
Hi @christophvw  - had some similar issues moving to VS 2019 seems to fix a lot (see https://github.com/MiKTeX/miktex/issues/524#issuecomment-622995686 and https://github.com/MiKTeX/miktex/issues/529#issuecomment-623132270)
