### ISSUE TITLE
Calling external commands with quotes in path via shell on Windows

### ISSUE THREAD

**Issue by mrpiggi** [MiKTeX/miktex#532]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hi,
some context first. I am the developer of the LaTeX package [`svg`](https://github.com/mrpiggi/svg). I am currently facing the problem that with _Inkscape v1.0_ the CLI has been changed without backward compatibility. I would like to implement a function to detect the current Inkscape version in order to adapt the automatic call to the respective CLI. 

If you need more information feel free to ask for but the main issue is that calling _Inkscape_ with its absolute path in quotes with either `\@@input|"'C:/Program Files/Inkscape1/bin/inkscape' -V" ` or `\ShellEscape{"C:/Program Files/Inkscape1/bin/inkscape" -V}` does not work with MiKTeX contrary to TeX Live. The latter returns with error message `...quotation error in system command.` in the log file of the LaTeX document.

A possible workaround would be to prepend **`call`** to the actual call. With this approach `\ShellEscape{call "C:/Program Files/Inkscape1/bin/inkscape" -V}` gives the expected result while `\@@input|call "'C:/Program Files/Inkscape1/bin/inkscape' -V" ` still does not work. Here is an example which shows all different approaches, the results with TeX Live and MiKTeX are shown afterwards:
```tex
\documentclass{minimal}
\usepackage[T1]{fontenc}
\usepackage{shellesc}[2019/11/08]
\begin{document}
\pdftexbanner\endgraf
\ifnum\pdfshellescape=1\relax
  \begingroup%
    \makeatletter
    \@makeother\"%
    \@makeother\|%
    \endlinechar=\m@ne%
    \everyeof{\noexpand}%
    \edef\svg@tempa{\@@input|"inkscape -V" }%
    \meaning\svg@tempa\endgraf%
    \edef\svg@tempa{\@@input|"'C:/Program Files/Inkscape1/bin/inkscape' -V" }%
    \meaning\svg@tempa\endgraf%
    \xdef\svgworkaround{%
      \@@input|"call 'C:/Program Files/Inkscape1/bin/inkscape' -V" %
    }%
  \endgroup%
  \ShellEscape{"inkscape" -V > svg.ink.ver.aux}%
  File content: \input svg.ink.ver.aux \endgraf
  \ShellEscape{echo ??? > svg.ink.ver.aux}%
  \ShellEscape{"C:/Program Files/Inkscape1/bin/inkscape" -V > svg.ink.ver.aux}%
  File content: \input svg.ink.ver.aux \endgraf
  \ShellEscape{echo ??? > svg.ink.ver.aux}%

  \bigskip
  \texttt{call "C:/Program Files/Inkscape1/bin/inkscape" -V}\endgraf
  \meaning\svgworkaround\endgraf%
  \ShellEscape{%
    call "C:/Program Files/Inkscape1/bin/inkscape" -V > svg.ink.ver.aux%
  }%
  File content: \input svg.ink.ver.aux \endgraf
  \ShellEscape{echo ??? > svg.ink.ver.aux}%
\else%
  Enable \texttt{-shell-escape}\endgraf
\fi
Done!
\end{document}
```

[TeXLive.pdf](https://github.com/MiKTeX/miktex/files/4589847/TeXLive.pdf)
[MiKTeX.pdf](https://github.com/MiKTeX/miktex/files/4589848/MiKTeX.pdf)

This issue is not urgent for me as there is a workaround but it seems to me that this is a very general one. And it is not only related to the call of Inkscape, just try:
```tex
\documentclass{minimal}
\usepackage[T1]{fontenc}
\usepackage{shellesc}[2019/11/08]
\begin{document}
\begingroup%
  \makeatletter
  \endlinechar=44%
%  \endlinechar=\m@ne%
  \everyeof{\noexpand}%
  \edef\@tempa{\@@input|"dir 'C:/Program Files/' /D /B" }%
  \meaning\@tempa\endgraf%
\endgroup
\end{document}
```

**Comment by edocevoli** [comment]
`'` is not a valid quoting character on Windows, i.e., running
```
dir 'C:/Program Files/' /D /B
```
in a command-prompt window does not work. At the moment I am reluctant to adopt the TeX Live hack.

**Comment by mrpiggi** [comment]
So there is (and will be) no way to use paths with spaces for shell-escape or pipes in MiKTeX?! I mean `\ShellEscape{"C:/Program Files/Inkscape1/bin/inkscape" -V > svg.ink.ver.aux}` doesn't work either although it is right regarding syntax on windows.

**Comment by edocevoli** [comment]
Indeed

```
\ShellEscape{"C:/Program Files/Inkscape1/bin/inkscape" -V > svg.ink.ver.aux}
```

should not give a quotation error.

**Comment by mrpiggi** [comment]
Thanks a lot!

> So there is (and will be) no way to use paths with spaces for invoking commands on [...] pipes at all in MiKTeX?!

`\edef\svg@tempa{\@@input|"'C:/Program Files/Inkscape1/bin/inkscape' -V" }%`

Do you stick with your decision regarding the single quotes for pipes or do you have an approach/idea how the problem could be solved?

**Comment by edocevoli** [comment]
This should work:

```tex
\input{|"C:/Program Files/Inkscape1/bin/inkscape" -V}
```

**Comment by edocevoli** [comment]
I see this cannot work because the quotes are eliminated. The TeX Live hack makes sense...

**Comment by mrpiggi** [comment]
Again, thank you a lot

**Comment by mrpiggi** [comment]
Another problem occurred: https://github.com/mrpiggi/svg/issues/31

Depending on the format used (pdflatex, lualatex, xelatex) the following MWE gives different results, whereas lualatex und xelatex seem to be faulty:
```tex
\listfiles
\documentclass{minimal}
\usepackage[T1]{fontenc}
\begin{document}
\begingroup
  \makeatletter
  \@makeother\|%
  \@makeother\&%
  \catcode\endlinechar=10%
  \everyeof{\noexpand}%
  \edef\parseversion{%
    \xdef\noexpand\pipestdout{\noexpand\@@input|"inkscape\space-V\space2>&1" }%
    \xdef\noexpand\pipenormal{\noexpand\@@input|"inkscape\space-V" }%
  }%
\texttt{\meaning\parseversion}
\parseversion
\endgroup

\texttt{pipestdout}: \pipestdout

\texttt{pipenormal}: \pipenormal
\end{document}
```
Results for `\pipenormal` and `\pipestdout`:
+ pdflatex: ´`Inkscape 1.0.1 (3bc2e813f5, 2020-09-07) Pango version: 1.46.1` for both cases
+ lualatex: `kscape 1.0.1 (3bc2e813f5, 2020-09-07) Pango version: 1.46.1` [sic] for redirected pipe `\pipestdout`
+ xelatex: `Pango version: 1.46.1` only for both cases

**Comment by edocevoli** [comment]
One bug, one issue. Please do not comment/reopen closed issues. You can submit a new issue. Please follow the contribution guidelines when doing so:
- no links to external web pages
- step-by-step reproduction instructions
