### ISSUE TITLE
include patgen in repo

### ISSUE THREAD

**Issue by christophvw** [MiKTeX/miktex#534]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

patgen seems to be missing in the MiKTeX repos:
https://ctan.org/pkg/patgen?lang=de

And the only binary version I found for windows didn't run because of missing DLLs.

**Comment by edocevoli** [comment]
Thank you for the suggestion. This program is now available.
