### ISSUE TITLE
MiKTeX setup does not download miktex-zzdb2-2.9.tar.lzma

### ISSUE THREAD

**Issue by christophvw** [MiKTeX/miktex#536]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

When I run
"miktexsetup.exe --verbose --local-package-repository=D:\MiKTeX\repo --package-set=complete"

it downloads a lot of files and finishes without any error (see attached output).

But when I try to set the directory as a local mirror it fails because miktex-zzdb2-2.9.tar.lzma is missing.

The log shows no attempt to download this file.

[output.txt](https://github.com/MiKTeX/miktex/files/4613712/output.txt)

**Comment by edocevoli** [comment]
This file is now obsolete and not needed.
