### ISSUE TITLE
Download packages in Parallel

### ISSUE THREAD

**Issue by ArthurHNL** [MiKTeX/miktex#537]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

On a fresh MiKTeX installation, when installing packages on-the-fly, it appears that all packages required for building a document are downloaded and extracted sequentially. A significant improvement would be to download and extract these packages in parallel.

**Comment by edocevoli** [comment]
- LaTeX loads packages sequentially (not in parallel)
- the package manager does not load in advance, which packages will be loaded by LaTeX

That said, the feature cannot be implemented on the MiKTeX/package manager level.
