### ISSUE TITLE
MACOS, mthelp calls firefox instead of open

### ISSUE THREAD

**Issue by vincentb1** [MiKTeX/miktex#538]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have installed MiKTeX on MACOS, if I type `mthelp fixme` (it could be another package than `fixme`), then I get the following error message:

```
/bin/sh: firefox: command not found
```

Please note that I have made some hacks in order to have MiKTeX one the distributions selectable through the TeXDist symlinks.

**Comment by edocevoli** [comment]
This has been fixed.
