### ISSUE TITLE
Installing MiKTeX on AWS Elastic Beanstalk (EC2) Linux 

### ISSUE THREAD

**Issue by CodePlexaMania** [MiKTeX/miktex#54]
## What I tried to do
Install MiKTeX on AWS Elastic Beanstalk (EC2) 64bit Amazon Linux 2017.09 
Navigated to Linux tab in downloads on miktex.org

## What I expected to happen
Expected to be able to install MiKTeX

## What happened instead
Linux on AWS uses 'yum' instead of 'apt-get'

## Question
Could a workaround be provided using 'yum' to both "register" and install the MiKTeX installation package?

**Comment by edocevoli** [comment]
Please note that only Ubuntu is supported at the moment. Other Linux distros may be supported in a future release. Please watch the [roadmap](https://miktex.org/kb/roadmap).
