### ISSUE TITLE
Windows 10: "MiKTeX Configuration Utility" did not succeed 

### ISSUE THREAD

**Issue by 1kastner** [MiKTeX/miktex#540]
Hello there,

I installed MiKTeX as an administrator today. Now it shows me some files but e.g. not the logs. Since I am fighting with it, that is quite a hindrance. In specific, I am talking about the initexmf.log file:

```
log4cxx: setFile(C:\Users\XXXXXXX\AppData\Local\MiKTeX\2.9\miktex\log/initexmf.log,true) call failed.
log4cxx: IO Exception : status code = 720005
log4cxx: No output stream or file set for the appender named [RollingLogFile].

Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:

  MiKTeX cannot retrieve attributes for the directory 'C:\Users\XXXXXXX\AppData\Local\MiKTeX\2.9\miktex\log'.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\XXXXXXX\AppData\Local\MiKTeX\2.9\miktex\log\initexmf.log
```

I even started Notepad++ in administrator mode and still it did not allow me to peek into the file. Why is it so strictly protected?

**Comment by edocevoli** [comment]
> Why is it so strictly protected?

When a file is created, it gets the default permissions depending on the permissions of the current user. I don't know why these permissions are so strict. Sorry, but that issue cannot be solved remotely.

**Comment by 1kastner** [comment]
@edocevoli what I did was just installing MiKTeX in administration mode with my normal user. I am not aware of any unusual configurations at my computer. All other software on my computer works as intended. It is an up-to-date W10 installation.

**Comment by edocevoli** [comment]
If you are an administrator then you know how to inspect/change file permissions. As I said before, I cannot help you on this.

**Comment by 1kastner** [comment]
While yesterday I restarted the computer several times, yet another restart this morning allowed me to enter the folder. Windows did not allow me even with administrator rights before... However, now it seems solved.
