### ISSUE TITLE
Silent deployment

### ISSUE THREAD

**Issue by Bummibaer** [MiKTeX/miktex#542]
I'm trying to prepare a deployment according to
https://miktex.org/howto/deploy-miktex

Preparation:
`miktexsetup --verbose --local-package-repository=C:\temp\miktex --package-set=complete download`

Rollout:
`%SW_DIR%\miktexsetup.exe  --local-package-repository=%REPO_DIR% --package-set=basic install`

Afterwards, I get in the MiKTex-Console the message:

> major issue: So far, no MiKTeX administrator has checked for updates.

I don't want to see for the user.

Now I appended the following commands to the script:
`mpm --admin --upgrade --repository=%REPO_DIR% --package-level=complete`
`mpm  --set-repository=%REPO_DIR% --admin`
Same result.
What's wrong?
Can I switch off the update-messages completely for the user?

**Comment by edocevoli** [comment]
> Can I switch off the update-messages completely for the user?

Instead of `--upgrade` you can say `--update`. This is a dummy operation (because you have just installed from that repo) but it will prevent the major issue message.

**Comment by Bummibaer** [comment]
Thanks a lot for your fast answer. 
It seems to work now.
