### ISSUE TITLE
makeindex cannot deal with spaces in MiKTeX path

### ISSUE THREAD

**Issue by DeadRabbits307** [MiKTeX/miktex#543]
OS: Windows 10
MiKTeX Console: 2.9.7429 
makeindex: 2.12

If you install MiKTeX into the default directory which is given during the installation (`C:\Program Files\MiKTeX 2.9\` --> 2 spaces in it) `makeindex `cannot find `nomencl.ist` running

` makeindex.exe mytexfile.nlo -s nomencl.ist -o mytexfile.nls`

If you install MiKTeX in another directory like `C:\MiKTeX2.9\` or you copy `nomencl.ist` into the LaTeX project directory everything works fine.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
