### ISSUE TITLE
Just a Great experience using MikTex 2.9

### ISSUE THREAD

**Issue by xekom12622** [MiKTeX/miktex#544]
Hello.

I just want to share excellent experiense using MikTex. I used spend about 12 hours to trying make its work and I cant. In that time I used Google, Miktex help,  stackexchange and nothing helps me.

Th be honest, I can to create pdf document now, so it is not compleatly brocken. But thats not worr also.

My system is Windows 7 x64,  Intel i7, 16Gb Ram.

I had Miketex version on my PC, but I had problems with make4ht:

https://tex.stackexchange.com/questions/544260/help-me-to-install-tex4ht-on-windows

I decide to delete miktex, clear system and install MikTex again.

Using miktex-console_admin I delete previous version. Using regedit I clear Windows from MikTex keys (it was in two different derictoryes in HKEY_CURRENT_USER\Software\MiKTeX.org and HKEY_LOCAL_MACHINE\Software\MiKTeX.org). I download new installer from official site:
https://miktex.org/download
 of MikTex and install it.

While installation I choose "install for anyone who uses that computer". Next I check for upgrades and found 93 upgrades. I press "Upgrade now" but it ends with an error 127:

GENERAL MIKTEX INFORMATION
Date: 2020-05-16 02:48:47
MiKTeX: 2.9.7400
GitInfo: 8386fcd / 2020-04-21 21:22:55
OS: Windows 7 Professional, 64-bit, Service Pack 1, build 7601
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-05-16 02:47:21
LastUpdateAdmin: 2020-05-16 02:48:42
LastUpdateDbAdmin: 2020-05-16 02:47:20
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files\MiKTeX 2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: non-existing/explorer

ERROR DETAILS
Program: C:\Program Files\MiKTeX 2.9\miktex\bin\x64\miktex-console_admin.exe
Source: Libraries\MiKTeX\Core\win\DllProc.cpp:63
Error: Windows API error 127: The specified procedure could not be found.
Details: 
  dllName: C:\Program Files\MiKTeX 2.9\miktex/bin/x64\MiKTeX209-core.dll

I tryed to reinstall MikTex a few times and ewery time I get that error. I tryed that:

mpm --update
initexmf --admin --update-fndb
initexmf --admin --mklinks --force

I am trying to change backslashes to slashes in "PATH", 

before upgades, but nothing helped, I allways got that error.

That error not blocking MikTex working, so, I go ahead.
Next I try to compile my tex files. I cant due pdfLaTex error. And than that helps:

initexmf --admin --update-fndb
initexmf --admin --mklinks --force

After apply it, pdfLaTex starts, but it can't download packages. Problem was with requesting Admin mode from windows. It is when screen stay a little bit darcker and Windows ask does I agree to launch that program as Administrator.
So, that not happened. pdfLaTex did not ask about admin privileges and cant install packeges. So, I must in install in manyally from miktex-console_admin.

I had no patience to install every package by my hands, I delete MikTex and download portable version. Cleaning does not delete all files from Program Files, ProgramData and AppData folders, so I must to do in myself.

I want to use latex to create HTML files and I need to launch make4ht.

According manual I tryed: make4ht myfile.tex.

thats ends with error code 1.

According manual I launch it with additional keys:

make4ht -a debug myfile.tex.

That tell me that it cant found my tex file (E:\myTexFolder\MyTexFile.tex) and ask me to give any else file.
I change slashes (E:/myTexFolder/MyTexFile.tex) and it found my file. 
It start compilation: [1] [2] [3] [4]....
But next it cant found pictures in my file:
(N:\miktex-portable\texmfs\install\tex/generic/tex4ht\html4-math.4ht)
(N:\miktex-portable\texmfs\install\tex/generic/tex4ht\html5.4ht))

LaTeX Warning: Unused global option(s):
    [twodise].

(MyTexFile.aux)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
[1] [2] [3] [1] [2] [3] [4]

LaTeX Warning: File `_SDC6250.jpg' not found on input line 119.

l.119 --- TeX4ht warning --- File `"_SDC6250.xbb"' not found ---
l.119 --- TeX4ht warning --- Cannot determine size of graphic in "_SDC6250.xbb"
 (no BoundingBox) ---
[5] [6]

LaTeX Warning: File `_SDC6250.jpg' not found on input line 119.

l.119 --- TeX4ht warning --- File `"_SDC6250.xbb"' not found ---
l.119 --- TeX4ht warning --- Cannot determine size of graphic in "_SDC6250.xbb"
 (no BoundingBox) ---
! Undefined control sequence.
<recently read> \@undefined

l.119 \pic
          {_SDC6260}
?

I do not know how to make that works.

I hope I described the problem in sufficient detail, I'm sorry that I violated all the rules of the bug report. I am too tired now. 

If you have any suggestions for help, write to this topic, I will wait. 

https://tex.stackexchange.com/questions/544288/miktex-upgrade-issue-error-127-and-something-else

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Sorry that MiKTeX does not work on your system. This is certainly a system-dependent MiKTeX bug. At the moment, I have not enough information to work on it effectively. I would recommend that you remove MiKTeX and try another TeX distribution.
