### ISSUE TITLE
No console output from BibTeX if everything goes well

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex#547]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Since this morning BibTeX does not seem to produce any console log output any more if everything goes well.

Consider the following example file
```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}

\begin{document}
\cite{incollection-full}
\bibliography{xampl}
\bibliographystyle{plain}
\end{document}
```

The BibTeX run produces the `.bbl` file as desired and writes a complete log to the `.blg`, but the terminal output is empty

![consolebibtex](https://user-images.githubusercontent.com/6755835/82410266-d0011280-9a6f-11ea-89b2-ed48e2a62e39.PNG)

---

If I change the example to deliberately cause a BibTeX error
```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}

\begin{document}
\cite{incollection-full}
\bibliography{xampl}
\bibliographystyle{filethatisnotpresent}
\end{document}
```
BibTeX again produces console output, but only the warning messages (no version banner etc.).

---

Ideally I would have liked to see
```
This is BibTeX, Version 0.99d (MiKTeX 2.9.7440 64-bit)
The top-level auxiliary file: consolebibtex.aux
The style file: plain.bst
Database file #1: xampl.bib
```
which is what TeX live 2020 shows on Ubuntu.

**Comment by edocevoli** [comment]
Thank you, this has been fixed.
