### ISSUE TITLE
Do not invoke the package installer when locating file (with kpsewhich)

### ISSUE THREAD

**Issue by stenwessel** [MiKTeX/miktex#548]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hi there!

When trying to locate package files with `kpsewhich`, the current behavior is that the package installer is invoked automatically when searching for a package that is not installed locally on the system. For example, the invocation `kpsewhich alg.sty` (but also `kpsewhich -all alg.sty`) with the `alg` package not installed gives
![image](https://user-images.githubusercontent.com/11046840/82448812-897cd980-9aaa-11ea-83ca-79c8cd088315.png)

Sometimes I want to check whether the file exists locally without attempting an install of the package. A typical use case would be resolving `\usepackage{...}` references in a LaTeX IDE. When using `kpsewhich` to resolve the reference, the current behavior would trigger package install popups (or even automatically install the package) by merely opening/parsing the file.

From a quick inspection of the `SessionImpl::FindFileInternal` implementation in [findfile.cpp](https://github.com/MiKTeX/miktex/blob/f24bf0273b5f1dc3490140e42f5d1f4e4d781b3b/Libraries/MiKTeX/Core/Session/findfile.cpp), I believe it is not possible to tell kpsewhich _not_ to perform a package install when a file cannot be found. I think it would be a immensely useful addition if there was a way to do so, or if there would be an alternative way of locating locally installed package files.

**Comment by edocevoli** [comment]
This behavior is by design. But since most MiKTeX programs support `--miktex-disable-installer`, you can:

```
miktex-kpsewhich --miktex-disable-installer alg.sty
```
