### ISSUE TITLE
Can not create Packages with mpc 

### ISSUE THREAD

**Issue by 8ear** [MiKTeX/miktex#55]
# Bug report

## My check list

- [ x ] latest package versions are installed
- [ ] MiKTeX log files are attached
- [ ] the bug can be reproduced by anybody (necessary input files are attached)

My System:
Docker Container with ubuntu:xenial and installed miktex from Repository. Container Fully upgraded.

## What I tried to do
mpc --create-package --repository=. --staging-dir=../tmpmiktex/ --verbose

## What I expected to happen
Create a new package for a local Repository File.

## What happened instead
Error Message:
/usr/bin/lzma d ./miktex-zzdb1-2.9.tar.lzma -so | tar --force-local --to-stdout -xf - mpm.ini > /tmp/mik6D9dxS:
/usr/bin/lzma: invalid option -- 's'
tar: This does not look like a tar archive
tar: mpm.ini: Not found in archive
tar: Exiting with failure status due to previous errors

mpc: A system command failed.

## Enhancement
The Problem is in file:
https://github.com/MiKTeX/miktex/blob/master/BuildUtilities/mpc/mpc.cpp
On line: 1355-1358

On line 1356: change "d" to "-dc"
Why only "d"?

On line 1358: change "-so" to " "
For what is -so? The current linux lzma Tool (lzma 9.22) does not have this options?
For Standard Output "-c"

**Comment by edocevoli** [comment]
Thank you for the info. `mpc` is not yet supported. I will remove it from the distribution.

**Comment by 8ear** [comment]
Hi, how i can than create a miktex Package is their any howto?
I found only this:
http://docs.miktex.org/packaging/#id507636
and this need the mpc tool.

Thanks kind regards

**Comment by edocevoli** [comment]
If I understand you correctly, you want to add you own package to the MiKTeX repository.
I will take a look at this. It should not so difficult to create a working `mpc` for non-Windows platform.

**Comment by edocevoli** [comment]
`mpc` currently relies on the old `lzma_standalone` utility which supports the `-so` option.

**Comment by 8ear** [comment]
I've send a pull request to fix the bug.

**Comment by hmenke** [comment]
Still important to me.  Does `mpc` work on Linux now?
