### ISSUE TITLE
texdoc does not open the HTML for KOMA-Script

### ISSUE THREAD

**Issue by schtandard** [MiKTeX/miktex#551]
Calling `texdoc scrartcl` tries to open the URL `c:\Program Files\MiKTeX 2.9\doc/latex/koma-script\scrartcl.html` in my browser which fails due to the absence of the prefix `file:///`. This only happens for KOMA-Script, not for other packages.

Steps to reproduce:
- Type `texdoc scrartcl` in a command line and press enter.

`initexmf` report:
```latex
Date: 2020-05-25 23:42:48
MiKTeX: 2.9.7440
GitInfo: af89c1b / 2020-05-20 09:20:28
OS: Windows 10 Pro, 64-bit, build 18363
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-05-25 23:37:53
LastUpdateAdmin: 2020-05-25 23:39:04
LastUpdateDbAdmin: 2020-05-25 23:37:50
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\Benedikt Wilde\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Benedikt Wilde\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\local_texmf
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Benedikt Wilde\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Benedikt Wilde\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Benedikt Wilde\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```

**Comment by edocevoli** [comment]
It works for me (Windows 10. Chrome).

**Comment by schtandard** [comment]
I should have specified, sorry: I'm using Firefox.

You are right that Chrome doesn't care. Opera automatically adds `file:///` in front of the path. Firefox doesn't, though. Depending on its configuration, it either does a websearch for the path or shows an error message.
