### ISSUE TITLE
LuaLaTex fails on special characters in the windows user account path

### ISSUE THREAD

**Issue by 5inf** [MiKTeX/miktex#552]
It seems that Windows (10) user accounts based on Microsoft Accounts can have special characters in the pathname of the user folder. If this is the case then lualatex fails. All other (tested) "latexes" work.

FATAL lualatex - UTF-8 conversion failed; func=miktex_utf8__stat64i32 

**Steps to reproduce**

1. Have a Windows account containing non ASCII Characters e.g. ö and ß
2. Install a recent Miktex (here 2.9.7440)
3. Complie any latex file in any location on the harddrive e.g. c:\a.tex
4. It fails

**Output of initexmf --report**

```
Date: 2020-05-26 09:41:33
MiKTeX: 2.9.7440
GitInfo: af89c1b / 2020-05-20 09:20:28
OS: Windows 10 Pro, 64-bit, build 18363
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-05-26 09:07:37
LastUpdateAdmin: 2020-05-26 09:07:56
LastUpdateDbAdmin: 2020-05-26 09:07:19
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\<redacted>\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\<redacted>\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX
UserInstall: C:\Users\<redacted>\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\<redacted>\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\<redacted>\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
```

The redacted part contains German umlauts and special characters, ö and ß, which the console output of initexmf --report displays as "├╢├ƒ". The logfiles produced by Miktex print the special characters correctly.

**Example call and resulting output**

```
PS C:\Report2020> lualatex.exe .\a.tex
This is LuaHBTeX, Version 1.12.0 (MiKTeX 2.9.7440 64-bit)
 restricted system commands enabled.
(./a.tex
LaTeX2e <2020-02-02> patch level 5
```

After the LaTeX2e line the output hangs "forever". In the TaskManager a process LuaHBTeX consumes CPU and an ever increasing ammount of memory.

**Entry in lualatex.log**

```
2020-05-25 15:34:49,853+0200 INFO  lualatex - this process (9536) started by 'texstudio' with command line: lualatex.exe -synctex=1 -interaction=nonstopmode a.tex
2020-05-25 15:34:51,610+0200 FATAL lualatex - UTF-8 conversion failed; func=miktex_utf8__stat64i32, utf8="C:\Users\<redacted>/."
```

or

```
2020-05-26 09:49:42,305+0200 INFO  lualatex - this process (13748) started by 'pwsh' with command line: "C:\Program Files\MiKTeX\miktex\bin\x64\lualatex.exe" .\a.tex
2020-05-26 09:49:47,575+0200 FATAL lualatex - UTF-8 conversion failed; func=miktex_utf8__stat64i32, utf8="C:\Users\<redacted>/."
```

Both times (25.05.2020 and 26.05.2020) Miktex was updated right before the commands were run.

This bug must have been introduced between February 2019 and today (yes, a long time span, I know), because the same command with (about) the same file on the same machine and the same user and folder names succeeded about one year ago. Unfortunately I do not know the old Miktex version.

```
2019-02-18 21:47:01,332+0100 INFO  lualatex - starting with command line: lualatex.exe -synctex=1 -interaction=nonstopmode "a.tex"
2019-02-18 21:47:10,480+0100 INFO  lualatex - finishing with exit code 0
```

**Minmal working example (a.tex)**

Github does not recognize .tex files as attachable, but I assume this one is small enough to be included here. Basically any tex input works.

```
\documentclass{article}
\begin{document}
    test
\end{document}
```

Further reading: https://tex.stackexchange.com/questions/521982/lualatex-produces-no-output-miktex (yes, this is a link to Stackexchange, but only to show that someone else has (had) the same problem)

I hope the above is complete enough to reproduce. If not feel free to contact me for more details.

**Comment by edocevoli** [comment]
This can also reproduced as follows:

```
set HOME=C:\DümmerÜser
lualatex sample2e
```

Notice to myself: I think it has to do with LuaTeX's obscure manipulation of the environment (function `find_env` in `loslibext.c`).

**Comment by edocevoli** [comment]
Thank you. This has been fixed now.

**Comment by 5inf** [comment]
This is indeed fixed. Thanks!
