### ISSUE TITLE
[Win] Installed version identification and cmdline updating?

### ISSUE THREAD

**Issue by teknowledgist** [MiKTeX/miktex#553]
Once a specific version of MiKTeX is downloaded and run, how can I identify which version it is?  The Programs and Features control panel reports v2.9, but v2.9.x has been around for years.  The "About MiKTeX Console" doesn't report the version downloaded and installed.  (I downloaded v2.9.7442, but the "About" windows says v2.9.7429 and that isn't even a version on the news page.)  I'd really like a cmdline method for identifying the current version.

Also, if I use the MiKTeXsetup utility to create a local repository, the instructions explain how to install/deploy a workstation on the command line and how to update the local repository on the command line.  I see no mention of the proper procedure for updating a workstation from the local repository on the command line?  The only option identified for the setup utility are "download", "install", and "uninstall".  

If I install one version of MiKTeX and months/years later update it (through any means short of direct download and install overtop), does it then have all the same files and is the same version as if I did download and install it on a clean system?

Thanks.

**Comment by edocevoli** [comment]
There is no single MiKTeX version number. Each MiKTeX component has its own version number. The version you see in "About MiKTeX Console" is the version number of MiKTeX Console. 2.9.7442 is the version number of the installer.

There is a milestone (e.g., 2.9.7440) which you can see when you run `initexmf --report`:

```
MiKTeX: 2.9.7440
```

You can compare a milestone to the TeX Live "year" release number.

> I see no mention of the proper procedure for updating a workstation from the local repository on the command line?

There is command-line version of the package manager: `mpm`.

**Comment by teknowledgist** [comment]
Thanks for the information.  A couple follow-up questions:

- Is there documentation on `mpm`?
- If I use the console (or `mpm`) to update, will `initexmf --report` return the new milestone, or the installed milestone?

Thanks.

**Comment by edocevoli** [comment]
- the `mpm` man page should be available on the Internet; please search for "mpm man page"
- `initexmf --report` displays the milestone of the installed MiKTeX core run-time library, i.e., the new milestone if you installed the latest updates
