### ISSUE TITLE
MiKTeX release versioning

### ISSUE THREAD

**Issue by edocevoli** [MiKTeX/miktex#554]
The current release number scheme (2.9.dddd) is obsolete:

- the major/minor release number is fixed; it is not expected that there will be 3.0 release in the future
- the 4 digit patch/build number ("days since January 1, 2000") is not very user friendly

A new versioning scheme should be implemented, which:

- is easy to understand
- supports frequent updates
- is date-based

The recommended new release number format is YY.M[.D]. For example:

```
MiKTeX 20.6
```

In the rare case when there are multiple releases within a month, subsequent release version numbers will include the day. For example:

- first release in June: `MiKTeX 20.6`
- second release in June: `MiKTeX 20.6.21`
- third release in June: `MiKTeX 20.6.28`
```

**Comment by sssu123456** [comment]
讚

**Comment by jeroen** [comment]
Has this been reverted? The website now shows a download link to `basic-miktex-2.9.7442-x64.exe` ?
