### ISSUE TITLE
empty file on mac 

### ISSUE THREAD

**Issue by rickkss** [MiKTeX/miktex#555]
Hi, I'm very new to the computer world and I'm seeking help.

I've started writing an article using texstudio and MiKTeX. 
when I try to run my code to get a preview of the document, MikTex doesn't open and I receive an error message saying empty file : path="/Users/hq/Library/Application Support/MiKTeX/texmfs/data/miktex/data/le/671bf71b01ed2082fc381eb7f091e5b0.fndb-5"

and on texstudio i get a : Process started: pdflatex -synctex=1 -interaction=nonstopmode "texStudio ficher 1".tex

pdflatex: File is empty. pdflatex: Data: path="/Users/hq/Library/Application Support/MiKTeX/texmfs/data/m

iktex/data/le/671bf71b01ed2082fc381eb7f091e5b0.fndb-5" Sorry, but /usr/local/bin/pdflatex did not succeed. libc++abi.dylib: terminating with uncaught exception of type MiKTeX::Core::MiKTeXException: MiKTeX encountered an internal error.

Error: Command crashed: pdflatex -synctex=1 -interaction=nonstopmode "texStudio ficher 1".tex

Process exited with error(s)

thank you in advance.

**Comment by edocevoli** [comment]
Please give more information about your MiKTeX setup and:
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by rickkss** [comment]
hi edocevoli, thank you for your rapid responses, 

when I open the MiKTeX console I directly get this message.

<img width="592" alt="Screen Shot 2020-05-31 at 12 20 08 PM" src="https://user-images.githubusercontent.com/66212103/83357249-3a9c3300-a339-11ea-84d9-5571a6c66f72.png">
 
I cannot see the setup you mention.

**Comment by rickkss** [comment]
<img width="455" alt="Screen Shot 2020-05-31 at 12 20 14 PM" src="https://user-images.githubusercontent.com/66212103/83357261-5ef80f80-a339-11ea-9990-9b0a39059901.png">

**Comment by edocevoli** [comment]
The MiKTeX version you use is... ?

**Comment by rickkss** [comment]
miktex-2.9.7445-1-darwin-x86_64.dmg ,

**Comment by edocevoli** [comment]
It is safe to remove this empty file:

```
rm "$HOME/Application Support/MiKTeX/texmfs/data/miktex/data/le/671bf71b01ed2082fc381eb7f091e5b0.fndb-5"
```

Then you refresh the file name database:

```
initexmf -u
```

**Comment by rickkss** [comment]
I'm very sorry, you gonna have to be very patient with me.  I'm not really used to the computer lingo yet but can you direct me step-by-step with exactly what u mean  ?? I would really appreciate it. :)

**Comment by edocevoli** [comment]
1. open a Terminal window (via Launchpad)
1. enter `rm "$HOME/Application Support/MiKTeX/texmfs/data/miktex/data/le/671bf71b01ed2082fc381eb7f091e5b0.fndb-5"`
1. press the enter key
1. enter `initexmf -u`
1. press the enter key

You should now be able to open use MiKTeX again.

**Comment by rickkss** [comment]
<img width="626" alt="Screen Shot 2020-05-31 at 1 02 10 PM" src="https://user-images.githubusercontent.com/66212103/83358080-fc097700-a33e-11ea-82b0-876826c422da.png">


it did not work :\

**Comment by edocevoli** [comment]
I have updated the instructions. Please try again.

**Comment by rickkss** [comment]
great wonderful it worked, so now I have Miktex up and running. 
however, MikTeX is not interacting with Texstudio. when I run the code its not interacting. could u help with this issue or should I try texstudio directly ??



<img width="1222" alt="Screen Shot 2020-05-31 at 7 29 53 PM" src="https://user-images.githubusercontent.com/66212103/83365453-2b87a600-a376-11ea-9084-be83ea88ad53.png">

**Comment by edocevoli** [comment]
Please, can you inspect the log file (mentioned at the end of texstudio's output window).

**Comment by rickkss** [comment]
perfect everything works, I've got everything set up. I really appreciate it.
