### ISSUE TITLE
TeX capacity exceeded, sorry [main memory size=3000000]

### ISSUE THREAD

**Issue by sephill27** [MiKTeX/miktex#558]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have tries unsuccessfully to increase the memory using code I found at MiKTeX site. Below is the error I receive from the log when I try to run pdflatex. I just updated MiKTeX to the latest version and still get this error message. I work on a iMac and would appreciate any help.
Thank you,
Sharon

! TeX capacity exceeded, sorry [main memory size=3000000].
 ->\leavevmode \nobreak \ 
                          
l.3901 \end{verbatim}
                     
If you really absolutely need more capacity,
you can ask a wizard to enlarge me.

 
Here is how much of TeX's memory you used:
 7391 strings out of 482835
 114663 string characters out of 2949669
 2999999 words of memory out of 3000000
 22858 multiletter control sequences out of 15000+200000
 540219 words of font info for 53 fonts, out of 3000000 for 9000
 14 hyphenation exceptions out of 8191
 34i,7n,34p,248b,313s stack positions out of 5000i,500n,10000p,200000b,50000s
!  ==> Fatal error occurred, no output PDF file produced!

**Comment by edocevoli** [comment]
This can happen. I would recommend that you review your input file.

**Comment by AndreasFMueller** [comment]
I suggest MiKTeX distributes its product with a larger default. This error happens all the time. The participants in my seminar always have to change the settings first. 3000000 really is to small for modern TeX projects.

**Comment by Li-Ndibe** [comment]
> I suggest MiKTeX distributes its product with a larger default. This error happens all the time. The participants in my seminar always have to change the settings first. 3000000 really is to small for modern TeX projects.

Please where do I change the setting?
