### ISSUE TITLE
Bug when installing MiKTeX on Windows 10

### ISSUE THREAD

**Issue by SGalmes** [MiKTeX/miktex#559]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Could anybody help to solve this bug (see attached log file)?
Thank you very much!
Sebastià Galmés.
[setup-2020-06-05-21-49.log](https://github.com/MiKTeX/miktex/files/4738333/setup-2020-06-05-21-49.log)

**Comment by edocevoli** [comment]
Seems that you do not have permissions for `C:\Program Files`. Choose a per-user installation.

**Comment by SGalmes** [comment]
> 
> 
> Seems that you do not have permissions for `C:\Program Files`. Choose a per-user installation.

Thnak you very much, though it seems the reason was that Program Files already contained an old MiKTeK 2.9 folder.
