### ISSUE TITLE
Undo history erased when using Google Drive File Stream

### ISSUE THREAD

**Issue by TheCarlWinslow** [MiKTeX/miktex#560]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

How to reproduce:
1. Create new file from template -> Basic LaTeX documents -> article.tex
2. Save it somewhere on your Google Drive File Stream
3. Make any edit and then typeset.

The ability to undo disappears completely after typesetting completes. (Redo also disappears if there was something prior to typesetting.) 

This used to not be the case, so I imagine some way of handling undo/redo history has been altered somewhat recently. (I updated for the first time in months just yesterday.) Completely disrupts the workflow I've been using for years and makes MiKTeX unusable from a practical point of view. Undo/redo history is maintained when saved to a normal drive. 

There are no errors reported in any log files.

Date: 2020-06-10 01:11:37
MiKTeX: 2.9.7440
GitInfo: af89c1b / 2020-05-20 09:20:28
OS: Windows 10 Pro, 64-bit, build 18363
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-06-10 01:09:07
LastUpdateAdmin: 2020-06-10 01:02:33
LastUpdateDbAdmin: 2020-06-10 01:09:06
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Program Files\MiKTeX 2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by edocevoli** [comment]
I do not use Google Drive, so I am currently not able to reproduce/fix the problem. I guess you are using TeXworks? Please consider contacting the TeXworks developers. Maybe they have an idea.
