### ISSUE TITLE
include upmendex in repository

### ISSUE THREAD

**Issue by Youra-P** [MiKTeX/miktex#561]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Please add to the **upmendex** repository (https://www.ctan.org/pkg/upmendex). The package is a multilingual index processor with supports UTF-8 and support Cyrillic.

**Upmendex** is included in the TeX live 2019 assembly, but it is not in MikTeX 2.9.

Thank you in advance.

**Comment by edocevoli** [comment]
Thank you for the suggestion. This program is now available.

**Comment by Youra-P** [comment]
Thanks

вс, 28 июня 2020 г. в 16:45, Christian Schenk <notifications@github.com>:
