### ISSUE TITLE
unable to update bibliography. I am trying to 

### ISSUE THREAD

**Issue by makeabhishek** [MiKTeX/miktex#562]
I am writing my thesis and try to Run my latex code in my computer but bibliography citations are not updating. It is giving error "I couldn't find auxiliary files". Earlier I used the same setup to run in a different computer and it was working fine. But this time I am running this in a newly installed computer and it is giving such error.

Sometimes it also give error "Sorry, but "MiKTeX Compiler Driver" did not succeed."

**Comment by edocevoli** [comment]
Please review this check list:

1. you have installed the latest MiKTeX updates
1. step-by-step reproduction instructions
1. configuration report (`initexmf --report`) attached
1. input files attached
1. log files attached

### How to write a good bug report

Make sure that others will be able to reproduce the bug by providing:

1. **step-by-step reproduction instructions**:
  describe the exact steps which reproduce the problem in as many details
  as possible
2. **input files which are necessary to reproduce the bug**: aka a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example)
3. **your observations**: command output, screenshots

**Most importantly**: include information about your MiKTeX setup:

1. **installation report**: let MiKTeX Console create
  an installation report (on the `Diagnose` page)
2. **contents of the MiKTeX log directory**: MiKTeX Console tells
  you the location of log directory on the `Diagnose` page
