### ISSUE TITLE
Missing packages in distributions

### ISSUE THREAD

**Issue by albert-github** [MiKTeX/miktex#564]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Is there a reason why the languages like Korean and Chinese are not present in the (recent) LaTeX distributions for MikTex.

(cross posting from: https://github.com/latex3/babel/issues/77)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
