### ISSUE TITLE
pls help -Miktex installation fails 

### ISSUE THREAD

**Issue by DocNyr** [MiKTeX/miktex#565]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I tried to install the miktex software and it bombs... I am a newb and do not understand any thing about admin rights, etc...
Please help me...   THANK YOU...

below is the log file. ... 

initializing setup service...
starting installer...
Loading package database...
starting package maintenance...
installation directory: "C:\Program Files\MiKTeX 2.9"
package repository: C:\Users\nan2\AppData\Local\Temp\mik26778
visiting repository C:\Users\nan2\AppData\Local\Temp\mik26778...
repository type: local package repository
loading package repository manifest...
package repository digest: 9e03dbfaaa6640e639f104fe7a616428
going to install 16564 file(s) (189 package(s))
extracting files from amsfonts.tar.lzma...
extracting files from amsmath.tar.lzma...
extracting files from arabi.tar.lzma...
extracting files from avantgar.cab...
extracting files from babel.tar.lzma...
extracting files from babel-english.tar.lzma...
extracting files from biber-windows-x64.tar.lzma...
extracting files from biblatex.tar.lzma...
extracting files from bibtex.tar.lzma...
extracting files from blindtext.tar.lzma...
extracting files from bookman.cab...
extracting files from cbcoptic.tar.lzma...
extracting files from cm.tar.lzma...
extracting files from courier.tar.lzma...
extracting files from csfonts.tar.lzma...
extracting files from csplain.tar.lzma...
extracting files from dehyph.tar.lzma...
extracting files from dvipdfmx.tar.lzma...
extracting files from dvips.tar.lzma...
extracting files from ec.tar.lzma...
extracting files from elhyphen.tar.lzma...
extracting files from enctex.tar.lzma...
extracting files from environ.tar.lzma...
extracting files from epstopdf-pkg.tar.lzma...
extracting files from etoolbox.tar.lzma...
extracting files from fontconfig.tar.lzma...
extracting files from fontspec.tar.lzma...
extracting files from ghostscript.tar.lzma...
extracting files from graphics.tar.lzma...
extracting files from graphics-cfg.tar.lzma...
extracting files from graphics-def.tar.lzma...
extracting files from helvetic.cab...
extracting files from hyperref.tar.lzma...
extracting files from hyph-utf8.tar.lzma...
extracting files from iftex.tar.lzma...
extracting files from knuth-lib.tar.lzma...
extracting files from l3backend.tar.lzma...
extracting files from l3kernel.tar.lzma...
extracting files from l3packages.tar.lzma...
extracting files from latex-fonts.tar.lzma...
extracting files from listings.tar.lzma...
extracting files from lm.tar.lzma...
extracting files from ltxbase.tar.lzma...
extracting files from lualibs.tar.lzma...
extracting files from luaotfload.tar.lzma...
extracting files from luatex85.tar.lzma...
extracting files from make4ht.tar.lzma...
extracting files from metafont.tar.lzma...
extracting files from metapost.tar.lzma...
extracting files from miktex-arctrl-bin-x64-2.9.tar.lzma...
extracting files from miktex-asymptote-bin-x64-2.9.tar.lzma...
extracting files from miktex-autosp-bin-x64-2.9.tar.lzma...
extracting files from miktex-axohelp-bin-x64-2.9.tar.lzma...
extracting files from miktex-bibarts-bin-x64-2.9.tar.lzma...
extracting files from miktex-bibtex-bin-x64-2.9.tar.lzma...
extracting files from miktex-bibtex8bit-bin-x64-2.9.tar.lzma...
extracting files from miktex-bzip2-bin-x64-2.9.tar.lzma...
extracting files from miktex-cairo-bin-x64-2.9.tar.lzma...
extracting files from miktex-chktex-bin-x64-2.9.tar.lzma...
extracting files from miktex-cjkutils-bin-x64-2.9.tar.lzma...
extracting files from miktex-config-2.9.tar.lzma...
extracting files from miktex-console-bin-x64-2.9.tar.lzma...
extracting files from miktex-curl-bin-x64-2.9.tar.lzma...
extracting files from miktex-cweb-bin-x64-2.9.tar.lzma...
extracting files from miktex-devnag-bin-x64-2.9.tar.lzma...
extracting files from miktex-dict-british.tar.lzma...
extracting files from miktex-dict-english.tar.lzma...
extracting files from miktex-dict-french.tar.lzma...
extracting files from miktex-dict-german.tar.lzma...
extracting files from miktex-doc-2.9.tar.lzma...
extracting files from miktex-dvicopy-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvipdfmx.tar.lzma...
extracting files from miktex-dvipdfmx-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvipng-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvips.tar.lzma...
extracting files from miktex-dvips-bin-x64-2.9.tar.lzma...
extracting files from miktex-dvisvgm-bin-x64-2.9.tar.lzma...
extracting files from miktex-epstopdf-bin-x64-2.9.tar.lzma...
extracting files from miktex-expat-bin-x64-2.9.tar.lzma...
extracting files from miktex-findtexmf-bin-x64-2.9.tar.lzma...
extracting files from miktex-fmt-bin-x64-2.9.tar.lzma...
extracting files from miktex-fontconfig.tar.lzma...
extracting files from miktex-fontconfig-bin-x64-2.9.tar.lzma...
extracting files from miktex-fonts-bin-x64-2.9.tar.lzma...
extracting files from miktex-freeglut-bin-x64-2.9.tar.lzma...
extracting files from miktex-freetype2-bin-x64-2.9.tar.lzma...
extracting files from miktex-fribidixetex-bin-x64-2.9.tar.lzma...
extracting files from miktex-gd-bin-x64-2.9.tar.lzma...
extracting files from miktex-ghostscript-bin-x64.tar.lzma...
extracting files from miktex-graphite2-bin-x64-2.9.tar.lzma...
extracting files from miktex-gregorio-bin-x64-2.9.tar.lzma...
extracting files from miktex-gsf2pk-bin-x64-2.9.tar.lzma...
extracting files from miktex-harfbuzz-bin-x64-2.9.tar.lzma...
extracting files from miktex-hunspell-bin-x64-2.9.tar.lzma...
extracting files from miktex-icu-bin-x64.tar.lzma...
extracting files from miktex-jpeg-bin-x64-2.9.tar.lzma...
extracting files from miktex-kpathsea-bin-x64-2.9.tar.lzma...
extracting files from miktex-lacheck-bin-x64-2.9.tar.lzma...
extracting files from miktex-latex.tar.lzma...
extracting files from miktex-lcdf-typetools-bin-x64-2.9.tar.lzma...
extracting files from miktex-libressl-bin-x64-2.9.tar.lzma...
extracting files from miktex-log4cxx-bin-x64-2.9.tar.lzma...
extracting files from miktex-lua53-bin-x64-2.9.tar.lzma...
extracting files from miktex-luatex.tar.lzma...
extracting files from miktex-luatex-bin-x64-2.9.tar.lzma...
extracting files from miktex-lzma-bin-x64-2.9.tar.lzma...
extracting files from miktex-m-tx-bin-x64-2.9.tar.lzma...
extracting files from miktex-makeindex-bin-x64-2.9.tar.lzma...
extracting files from miktex-md5-bin-x64-2.9.tar.lzma...
extracting files from miktex-metafont.tar.lzma...
extracting files from miktex-metafont-bin-x64-2.9.tar.lzma...
extracting files from miktex-metapost-bin-x64-2.9.tar.lzma...
extracting files from miktex-mfware-bin-x64-2.9.tar.lzma...
extracting files from miktex-misc.tar.lzma...
extracting files from miktex-mkfntmap-bin-x64-2.9.tar.lzma...
extracting files from miktex-mktex-bin-x64-2.9.tar.lzma...
extracting files from miktex-mo-bin-x64-2.9.tar.lzma...
extracting files from miktex-mpfr-bin-x64-2.9.tar.lzma...
extracting files from miktex-mpmcli-bin-x64-2.9.tar.lzma...
extracting files from miktex-mspack-bin-x64-2.9.tar.lzma...
extracting files from miktex-mthelp-bin-x64-2.9.tar.lzma...
extracting files from miktex-mtprint-bin-x64-2.9.tar.lzma...
extracting files from miktex-omegaware-bin-x64-2.9.tar.lzma...
extracting files from miktex-pdftex.tar.lzma...
extracting files from miktex-pdftex-bin-x64-2.9.tar.lzma...
extracting files from miktex-pixman-bin-x64-2.9.tar.lzma...
extracting files from miktex-pmx-bin-x64-2.9.tar.lzma...
extracting files from miktex-png-bin-x64-2.9.tar.lzma...
extracting files from miktex-poppler-bin-x64-2.9.tar.lzma...
extracting files from miktex-popt-bin-x64-2.9.tar.lzma...
extracting files from miktex-posix-bin-x64-2.9.tar.lzma...
extracting files from miktex-ps2pk-bin-x64-2.9.tar.lzma...
extracting files from miktex-psutils-bin-x64-2.9.tar.lzma...
extracting files from miktex-qt5-bin-x64.tar.lzma...
extracting files from miktex-runtime-bin-x64-2.9.tar.lzma...
extracting files from miktex-synctex-bin-x64-2.9.tar.lzma...
extracting files from miktex-tdsutil-bin-x64-2.9.tar.lzma...
extracting files from miktex-teckit-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex.tar.lzma...
extracting files from miktex-tex-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex2xindy-bin-x64-2.9.tar.lzma...
extracting files from miktex-tex4ht.tar.lzma...
extracting files from miktex-tex4ht-bin-x64-2.9.tar.lzma...
extracting files from miktex-texify-bin-x64-2.9.tar.lzma...
extracting files from miktex-texware-bin-x64-2.9.tar.lzma...
extracting files from miktex-texworks-bin-x64-2.9.tar.lzma...
extracting files from miktex-ttf2pk2-bin-x64-2.9.tar.lzma...
extracting files from miktex-ucrt-bin-x64.tar.lzma...
extracting files from miktex-uriparser-bin-x64-2.9.tar.lzma...
extracting files from miktex-vc140-bin-x64.tar.lzma...
extracting files from miktex-web-bin-x64-2.9.tar.lzma...
extracting files from miktex-xetex.tar.lzma...
extracting files from miktex-xetex-bin-x64-2.9.tar.lzma...
extracting files from miktex-xindy-bin-x64.tar.lzma...
extracting files from miktex-yap-bin-x64-2.9.tar.lzma...
extracting files from miktex-zip-bin-x64.tar.lzma...
extracting files from miktex-zlib-bin-x64-2.9.tar.lzma...
extracting files from miktex-zzip-bin-x64-2.9.tar.lzma...
extracting files from modes.tar.lzma...
extracting files from mptopdf.tar.lzma...
extracting files from ms.tar.lzma...
extracting files from ncntrsbk.cab...
extracting files from oberdiek.tar.lzma...
extracting files from palatino.cab...
extracting files from pdftex.tar.lzma...
extracting files from pdftexcmds.tar.lzma...
extracting files from pgf.tar.lzma...
extracting files from pgfplots.tar.lzma...
extracting files from plain.tar.lzma...
extracting files from ragged2e.tar.lzma...
extracting files from rsfs.tar.lzma...
extracting files from ruhyphen.tar.lzma...
extracting files from standalone.tar.lzma...
extracting files from symbol.cab...
extracting files from tcolorbox.tar.lzma...
extracting files from tetex.tar.lzma...
extracting files from tex-ini-files.tar.lzma...
extracting files from tex4ht.tar.lzma...
extracting files from times.cab...
extracting files from tools.tar.lzma...
extracting files from trimspaces.tar.lzma...
extracting files from ukrhyph.tar.lzma...
extracting files from unicode-data.tar.lzma...
extracting files from url.tar.lzma...
extracting files from xcolor.tar.lzma...
extracting files from xetex.tar.lzma...
extracting files from xkeyval.tar.lzma...
extracting files from zapfchan.cab...
extracting files from zapfding.cab...
updating package manifests ("C:\Program Files\MiKTeX 2.9\miktex/config\package-manifests.ini")...
installed 3759 package manifests
visiting repository C:\Users\nan2\AppData\Local\Temp\mik26778...
repository type: local package repository
loading package repository manifest...
initexmf "--common-install=C:\Program Files\MiKTeX 2.9" --set-config-value=[Core]SharedSetup=1 --admin "--log-file=C:\Program Files\MiKTeX 2.9\miktex/config\uninst.log" --disable-installer --verbose:
Option --admin only makes sense for a shared MiKTeX setup.

Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:

  Option --admin only makes sense for a shared MiKTeX setup.

An error occurred:
  source file: 
  source line: 0
  message: The executed process did not succeed.
  info: fileName="C:\Program Files\MiKTeX 2.9\miktex\bin\x64\initexmf.exe", exitCode="1"

<<<Cancel? Yes!>>>

**Comment by edocevoli** [comment]
I would recommend that you wipe old MiKTeX files and registry settings:

```
rmdir /S /Q "%PROGRAMFILES%\MiKTeX 2.9"
rmdir /S /Q "%PROGRAMFILES(x86)%\MiKTeX 2.9"
rmdir /S /Q "%PROGRAMDATA%\MiKTeX"
rmdir /S /Q "%APPDATA%\MiKTeX"
rmdir /S /Q "%LOCALAPPDATA%\MiKTeX"
rmdir /S /Q "%LOCALAPPDATA%\Programs\MiKTeX 2.9"
rmdir /S /Q "%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\MiKTeX 2.9"
rmdir /S /Q "%APPDATA%\Microsoft\Windows\Start Menu\Programs\MiKTeX 2.9"
reg delete HKCU\Software\MiKTeX.org
reg delete HKLM\SOFTWARE\MiKTeX.org
```

Then it should be possible to install MiKTeX.
