### ISSUE TITLE
Restart requirement post-installation in Windows

### ISSUE THREAD

**Issue by SivamPillai** [MiKTeX/miktex#566]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

The local installation process of MikTex is straightforward. However, post-installation the package is not detected by other applications until a system restart is performed. 

For example, I faced this issue recently while installing MiKTeX for use with nbcovert. nbconvert kept complaining about missing xelatex file which as per MikTex was actually installed and available.

_The issue was simply that the system needed restart after which things worked just fine. This may result in people trying to debug a non-error._

Is it possible to recommend a system restart on completion of MikTex installation (or even force the user to restart to use the application)?

**Comment by edocevoli** [comment]
IMO this is not a MiKTeX issue.

**Comment by SivamPillai** [comment]
Not an expert, but clearly this seems to occur as the files or path variables are not set until a manual restart. Shouldn't this be addressed during the installation of MikTex? (Or at the least the user alerted in the final screen of installation, that a restart may be required for completion of the setup process)

**Comment by edocevoli** [comment]
The path variable is set and Windows is notified about this. That is, after the installation you can open a command-prompt window and run `pdflatex`.

**Comment by SivamPillai** [comment]
OK, thanks! I have no idea what happened during the restart that made it work soon after. I spent more than half-hour wondering what went wrong prior to restart. And a restart did it. So that was the only concern.
