### ISSUE TITLE
Updating MikTeX to 20.6 on Ubuntu

### ISSUE THREAD

**Issue by thymaro** [MiKTeX/miktex#567]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I have installed MikTeX on Ubuntu focal fossa some time ago, now. Recently, I tried updating to the date based new version with

`sudo apt update`

and get

`N: Skipping acquire of configured file 'universe/binary-i386/Packages' as repository 'http://miktex.org/download/ubuntu focal InRelease' doesn't support architecture 'i386'`

```bash
initexmf --report
Date: 2020-06-29 07:41:52
MiKTeX: 2.9.7445
GitInfo: 93ed470 / 2020-05-20 15:01:06
OS: Linux 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64
SharedSetup: no
LinkTargetDirectory: /home/thymaro/bin
PathOkay: yes
LastUpdateCheck: 2020-06-29 07:01:27
LastUpdate: 2020-06-29 07:00:07
LastUpdateDb: 2020-06-29 07:01:27
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: /home/thymaro/.miktex/texmfs/config
Root1: /home/thymaro/.miktex/texmfs/data
Root2: /home/thymaro/.miktex/texmfs/install
Root3: /var/lib/miktex-texmf
Root4: /var/cache/miktex-texmf
Root5: /usr/local/share/miktex-texmf
UserInstall: /home/thymaro/.miktex/texmfs/install
UserConfig: /home/thymaro/.miktex/texmfs/config
UserData: /home/thymaro/.miktex/texmfs/data
CommonInstall: /usr/local/share/miktex-texmf
CommonConfig: /var/lib/miktex-texmf
CommonData: /var/cache/miktex-texmf
```

**Comment by edocevoli** [comment]
Just to note:

- MiKTeX does not provide 32-bit packages
- you are running 64-bit Linux

**Comment by edocevoli** [comment]
If you run

```
dpkg --print-foreign-architectures
```

does it return `i386`?

**Comment by edocevoli** [comment]
Hope this fixes the issue: Pleas reconfigure the repository as follows

```
echo "deb [arch=amd64] http://miktex.org/download/ubuntu focal universe" | sudo tee /etc/apt/sources.list.d/miktex.list
```

**Comment by thymaro** [comment]
Thanks for the suggestions. I will try that tonight and report back.

**Comment by thymaro** [comment]
@edocevoli perfect, that did the trick. In the GUI, when I go to 'help' the version number is `4.0`, but `initexmf --report` returns `20.6`. Not a problem per se, but I wonder if these numbers shouldn't be the same.

**Comment by thymaro** [comment]
> `dpkg --print-foreign-architectures`

btw, yes.

**Comment by thymaro** [comment]
> If you run
> 
> ```
> dpkg --print-foreign-architectures
> ```
> 
> does it return `i386`?

btw, yes,

**Comment by SanderWitteAus** [comment]
Thank you it worked: 
echo "deb [arch=amd64] http://miktex.org/download/ubuntu focal universe" | sudo tee /etc/apt/sources.list.d/miktex.list
