### ISSUE TITLE
Problem with short paths in windows

### ISSUE THREAD

**Issue by urigrupel** [MiKTeX/miktex#573]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
Hi,

My problem is when running latex.exe from the command line doesn't work with short paths. For example, if run `latex "C:\Users\URIGRU~1\AppData\Local\Temp\test.tex"`, it won't work and in the log file I see
```
Emergency stop.
<to be read again> 
                   \protect 
<*> C:/Users/URIGRU~
```
However, if I replace URIGRU~ with the full name it works without a problem. This came up when using the Thunderbird extension [LatexIt](https://github.com/protz/LatexIt/issues/56). There I don't have control over the way the path is written. Since the extension used to work, I believe this might be related to an update in MiKTeX.

I am running Windows 10 (1803) with MiKTeX 20.6.

**Comment by edocevoli** [comment]
Short paths are not supported, sorry.

**Comment by sphh** [comment]
Sorry for resurrecting this issue: It is easy to follow the argument regarding the DOS 8.3 short paths. But what will happen, if I want to latex the file `tmp~tmp.tex`, which is a legal file name? Is it possible to use such filenames at all?
