### ISSUE TITLE
package repository temporarily offline

### ISSUE THREAD

**Issue by edocevoli** [MiKTeX/miktex#574]
The latest update has some issues and the MiKTeX package repository has been taken offline to prevent further distribution of the broken update.

The repository will reopen tomorrow morning 10:00 a.m. CET.

**Comment by edocevoli** [comment]
The repository is online again.

**Comment by pertinsam** [comment]
Buenas tengo este error 

```! LaTeX Error: File `pdftexcmds.sty' not found.```
``` ```
```Type X to quit or <RETURN> to proceed,.```
```or enter new name. (Default extension: sty).```
``` ```
```Enter file name: .```
```! Emergency stop..```
```<read *> .```
```         ```
```l.108 \RequirePackage{pdftexcmds}[2009/04/10].```

y no se como solucionarlo, ¿podrías ayudarme?
