### ISSUE TITLE
Net Installer Crashing

### ISSUE THREAD

**Issue by hugopy** [MiKTeX/miktex#576]
I'm trying to install MikTek through net install on Windows 10 (x64). I downloaded all the LaTeX packages, and the installer worked normally in the download part. However, when I click "Install" after choosing "Install from a directory on your computer", the installer simply closes. This happens, as I said, after checking "Install from a dir. on your computer" and then clicking next. Clicking next freezed and crashes the installer.

I've already tried disabling my antivirus, rebooting my computer, downloading the installer again, but nothing works. May someone help me, please? Thanks

**Comment by edocevoli** [comment]
It works for me.

**Comment by MathuserNik** [comment]
I'm seeing the same behavior.

The net installer version "4.0.0.0" exits silently when choosing the "install" option. Left behind in C:\User\AppData\local\temp is temp file with the contents:
```



An error occurred:
  source file: Libraries\MiKTeX\Setup\SetupService.cpp
  source line: 740
  message: no local package directory found
  info: 

```

It appears that, if the setup file is executed in a folder that contains a downloaded package set (specifically, it looks like it's searching for a README.txt first), then it works fine. However, if the setup.exe is run outside of a folder containing package set, it crashes as above.

**Comment by edocevoli** [comment]
There is an installer in the local package directory. So the obvious workaround: click the installer which resides in the local package directory.

**Comment by m0rphed** [comment]
I was not able to download any kind of installer from [official site](https://miktex.org/download).
![image](https://user-images.githubusercontent.com/35064145/88387542-582acd80-cdbb-11ea-89f6-8ab88b35e527.png)
I was unable to download the installer on either Linux or Windows machine. 
Is FTP server is temporary offline or this is some kind of wired DNS issue? (downloading from Russia)

**Comment by edocevoli** [comment]
@m0rphed this is unrelated there for I will delete your comment

**Comment by edocevoli** [comment]
This has been fixed. The new installer (version 4.1) will be available tomorrow.
