### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ivankokan** [MiKTeX/miktex#579]
https://github.com/MiKTeX/miktex/blob/73a110dc4a034b1325121324954e2b0249bcfdd4/Programs/MiKTeX/Console/Qt/mainwindow.cpp#L2749

`QMessageBox::information(this, tr("MiKTeX Console"), tr("MiKTeX Console needs to be closed."));`

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
