### ISSUE TITLE
kpse.lookup in LuaTeX

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex#58]
See https://github.com/latex3/l3build/issues/52 for context.

There seems to be a difference between MikTeX and TeX live when calling `kpse.lookup` with arguments in LuaTeX.

The following MWE
```
\documentclass{article}
\usepackage{luacode}

\begin{document}
\begin{luacode}
kpse.set_program_name("kpsewhich")
build_kpse_path = string.match(kpse.lookup("l3build.lua"),"(.*[/])")

local function build_require(s)
  tex.print( kpse.lookup("l3build-"..s..".lua", { path = build_kpse_path } ) )
end

build_require("help")
\end{luacode}
\end{document}
```
is expected to output the path of `l3build-help.lua` (assuming it is installed). Instead I get an error.

Using the older (?) syntax `{ ["-path"] = build_kpse_path }` to supply the path argument works. But `{ path = build_kpse_path }` is expected to work as well.

System info: MikTeX 2.9 (fully udpated) on Windows 10. LuaTeX version 1.07.0 (MikTeX 2.9.6600).

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by moewew** [comment]
Thank you very much. I can confirm that the document above compiles as expected with the update from this morning.
