### ISSUE TITLE
Update check: "Configuration error: no conversion from undefined configuration value to string."

### ISSUE THREAD

**Issue by wmb356** [MiKTeX/miktex#580]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Obs: I have read issue #571, but the suggested temporary solution do not work on my system.
I have attached a zipfile with logs.

miktex-report:
ReportDate: 2020-07-05 09:55:09
CurrentVersion: 20.6
SetupDate: 2011-07-04 20:07:00
SetupVersion: 2.9
Configuration: Regular
GitInfo: 9cfc87b / 2020-06-29 20:05:02
OS: Windows 10 Home, 64-bit, build 18362
SharedSetup: yes
LinkTargetDirectory: C:\Program Files (x86)\MiKTeX 2.9\miktex\bin
PathOkay: yes
LastUpdateCheckAdmin: 2020-06-30 08:13:39
LastUpdateAdmin: 2020-06-30 08:15:40
LastUpdateDbAdmin: 2020-06-30 08:12:47
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX\2.9
Root1: C:\Local Tex Files
Root2: C:\Program Files (x86)\MiKTeX 2.9
CommonInstall: C:\Program Files (x86)\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

Error:
2020-07-05 09:54:46,971+0200 INFO  main - starting: MiKTeX Console 4.0 (MiKTeX 20.6 32-bit)
2020-07-05 09:54:56,369+0200 INFO  mainwindow - checking for updates...
2020-07-05 09:54:56,381+0200 INFO  miktex-console.packagemanager - searching for updateable packages
2020-07-05 09:54:56,388+0200 FATAL miktex-console.core - Configuration error: no conversion from undefined configuration value to string.
2020-07-05 09:54:56,388+0200 FATAL miktex-console.core - Data: 
2020-07-05 09:54:56,388+0200 FATAL miktex-console.core - Source: Libraries\MiKTeX\Core\Session\config.cpp:516
2020-07-05 09:54:56,390+0200 ERROR mainwindow - Libraries\MiKTeX\Core\Session\config.cpp:516: Configuration error: no conversion from undefined configuration value to string.()

[log.zip](https://github.com/MiKTeX/miktex/files/4874581/log.zip)

**Comment by edocevoli** [comment]
The workaround in #571 is for 64-bit MiKTeX.

**Comment by edocevoli** [comment]
Please try this workaround instead:

```
set MIKTEX_REMOTESERVICEYWRHF=https://api2.miktex.org/
miktex-console
```

**Comment by wmb356** [comment]
The different flag (MIKTEX_REMOTESERVICEYWRHF) worked !
Thank you !

**Comment by edocevoli** [comment]
Thanks

**Comment by AChangM** [comment]
> Please try this workaround instead:
> 
> ```
> set MIKTEX_REMOTESERVICEYWRHF=https://api2.miktex.org/
> miktex-console
> ```

Hi, Edocevoli thanks for giving us the solution... Could you please clarify exactly in what part of MiKTeX Console I must set: "MIKTEX_REMOTESERVICEYWRHF=https://api2.miktex.org/". Thanks in advance.

**Comment by AChangM** [comment]
> The different flag (MIKTEX_REMOTESERVICEYWRHF) worked !
> Thank you !

Hello friend.  Where do you put or set this?

**Comment by wmb356** [comment]
What OS do you use (Linux / Mac OS / Windows) ?
In Windows you:
a) open a terminal (command window)
b) execute the command:
       set MIKTEX_REMOTESERVICEYWRHF=https://api2.miktex.org/
c) and then you execute the command (as USER):
       miktex-console
OR you execute the command (as ADMIN):
       miktex-console_admin
d) Then you click the update button in the Miktex console/interface.

**Comment by AChangM** [comment]
Thanks Bro! (Wmb356).
I guess I was executing in bad way the command. 
Now I did it patiently and now it worked!
Thanks!
