### ISSUE TITLE
pdflatex fails with "invalid argument in putc"

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#581]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

The following document fails for me on windows 10 with pdftex 
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.6.29) 

~~~~
\documentclass[10pt,a4paper]{article}
\sloppy
\textwidth=15.6cm
\begin{document}
test


  \fontsize{9}{9}\selectfont
   \noindent \copyright{}
   { 2020} by the authors.
   Submitted to not specified for %
   possible open access publication %
   under the terms and conditions of the Creative Commons Attribution %
   (CC BY) license %
    http://creativecommons.org/licenses/by/4.0/.
\end{document}
~~~~

miktex doesn't succeed.  The log file of the document ends with 

~~~~
Underfull \hbox (badness 6396) in paragraph at lines 20--27
\TS1/cmr/m/n/9
~~~~

pdflatex.log from miktex says:

~~~~
2020-07-06 22:54:37,592+0200 INFO  pdflatex - allowing known shell commands
2020-07-06 22:54:37,592+0200 INFO  pdflatex - enabling input (output) from (to) processes
2020-07-06 22:54:38,047+0200 FATAL pdflatex.core - Invalid argument
2020-07-06 22:54:38,048+0200 FATAL pdflatex.core - Function: putc
2020-07-06 22:54:38,048+0200 FATAL pdflatex.core - Result: 22
2020-07-06 22:54:38,048+0200 FATAL pdflatex.core - Data: <no data>
2020-07-06 22:54:38,048+0200 FATAL pdflatex.core - Source: Libraries\MiKTeX\TeXAndFriends\c4pstart.cpp:285
2020-07-06 22:54:38,049+0200 FATAL pdflatex - Invalid argument
2020-07-06 22:54:38,049+0200 FATAL pdflatex - Info: 
2020-07-06 22:54:38,049+0200 FATAL pdflatex - Source: Libraries\MiKTeX\TeXAndFriends\c4pstart.cpp
2020-07-06 22:54:38,049+0200 FATAL pdflatex - Line: 285
2020-07-06 22:54:38,050+0200 INFO  pdflatex - this process (9352) finishes with exit code 1
2020-07-06 22:54:38,053+0200 ERROR pdflatex - minor issue: The PATH variable does not include the MiKTeX executables.
2020-07-06 22:54:38,053+0200 WARN  miktex.core - still open: test-utf8.tex
2020-07-06 22:54:38,053+0200 WARN  miktex.core - still open: test-utf8.aux
2020-07-06 22:54:38,054+0200 WARN  miktex.core - still open: test-utf8.log
~~~~

Small changes to the document (removing \sloppy, changing the textwidth, removing a word) allows the compilation to succeed.

In texlive the document compiles without problems.

**Comment by edocevoli** [comment]
It seems to me that `\copyright{}` uses the 1252 code page. MiKTeX expects UTF8-8 console output and so it stumbles upon the invalid UTF-8 sequence.

**Comment by u-fischer** [comment]
Yes, in the log of texlive there is a copyright symbol: \TS1/cmr/m/n/9 ©  \OT1/cmr/m/n/9 2020. But it is invisible in the console,
there I see only `\TS1/cmr/m/n/9   \OT1/cmr/m/n/9 2020`. 

In miktex I can force the failure also by showing lost chars on the terminal:

~~~~
\documentclass{article}
\tracinglostchars=2
\begin{document}
   \char169
\end{document}
~~~~

**Comment by edocevoli** [comment]
So, to "fix" the issue, MiKTeX should ignore invalid character sequences.

**Comment by u-fischer** [comment]
It is a possibility (which seems to be what texlive do but I don't know the details). It would be okay for me. It could also replace them by "invalid char ignored" or "invalid byte XXX" or something else.

**Comment by T-F-S** [comment]
I have another document which also fails with the same error messages Ulrike Fischer already described.

```latex
\documentclass{article}
\usepackage[T1]{fontenc}

\begin{document}
    Divorced=geschieden,
    Partnership=au\ss{}erehelich verbunden,
    Floruit=bl\"uhte,
\end{document}
```

I compiled with `pdflatex` with versioning
`This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.6.29)`

I cannot see an invalid character inside the document. 

It compiles,
- if `fontenc` is removed
- or if ONE (any) of the three input lines is removed. 

Otherwise, it fails with the reported error.

**Comment by u-fischer** [comment]
@T-F-S  It is the same problem. As soon as pdflatex tries to write non-ascii to the terminal it breaks. Until this is fixed the best work-around imho is to call pdflatex with `--interaction=batchmode`, then it doesn't try to write to the terminal. 

In your case you can then see in the log (which is 8-bit encoded):

~~~~
Overfull \hbox (1.61346pt too wide) in paragraph at lines 23--26
[]\T1/cmr/m/n/10 Divorced=geschieden, Part-ner-ship=auÿerehelich ver-bun-den, F
loruit=blühte, 
~~~~

**Comment by T-F-S** [comment]
@u-fischer Thank you for the explanation and also for the workaround. I lost a lot of time searching for an error with my files until I found your issue post.

I am a happy and thankful user of MiKTeX since many, many years, but today I was on the very brink of installing texlive instead, because I could not go on with my documents. With `--interaction=batchmode` I can live until the problem is fixed :-)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
