### ISSUE TITLE
[Feature request] Installing/Upgrading MikTeX without TeXworks

### ISSUE THREAD

**Issue by faramir** [MiKTeX/miktex#582]
As far as I'm aware, it is not possible to install/upgrade MikTeX without TeXworks.
Why the TeXworks package is required?
Please make the package not required or check when upgrading that the package was uninstalled.

I'm using other tex editor for LaTeX and I think that I don't need the TeXworks. I can uninstall TeXworks using the MikTeX console, but when upgrading the package _miktex-texworks-bin-x64-2.9_ (version 0.6.5) is selected to be installed and with _required_ state without possibility to unselect the package.

**Comment by ivankokan** [comment]
> As far as I'm aware, it is not possible to install/upgrade MikTeX without TeXworks.
> Why the TeXworks package is required?
> Please make the package not required or check when upgrading that the package was uninstalled.
> 
> I'm using other tex editor for LaTeX and I think that I don't need the TeXworks. I can uninstall TeXworks using the MikTeX console, but when upgrading the package _miktex-texworks-bin-x64-2.9_ (version 0.6.5) is selected to be installed and with _required_ state without possibility to unselect the package.

Hi @faramir. I guess you are not using so many other binaries available in MiKTeX as well. How does TeXworks differ from them (for which you do not ask to be non-required)?

**Comment by faramir** [comment]
@ivankokan the TeXworks size is much larger (for downloading and storing) and is not necessary for MikTeX - uninstalling don't brake anything.
Moreover it produces problem with file associations. However, currently, after upgrading MikTeX, I'm uninstalling the TeXworks package and don't face the much problem, but I have to remember to unsintall it.

If there are other not required packages to correclty working with LaTeX (XeLaTeX,PDFLaTeX,LuaLaTeX), why they are marked as _required_?

**Comment by ivankokan** [comment]
I would say that TeXworks belong to MiKTeX's essential set (`Level=S`) due to pragmatic reasons, i.e. having LaTeX novices ready to typeset with some guaranteed editor/IDE. Looking at tex.stackexchange.com, one can tell that a very large number of people (not necessarily novices) do not realize the difference between editor/IDE and compiler and other things, so having something pre-installed probably helps much more than not having it.

Assuming that level declarations are static, it is the expected behavior that MiKTeX always checks whether everything from essential set is installed or not.

File associations are a different story, and one should know how to set them if they are not as wanted. (But I understood your point about it.)

These are just my thoughts on this matter.

**Comment by faramir** [comment]
Is it possible to locally set the package level? So novices can use the essential set as usual, but other people, that don't need TeXworks could change _something_ and MikTeX would not install the package again.
...or maybe there is someplace for storing information about the installed version that I could modify, so MikTeX would not install/upgrade it, I would not have to manually process the package?

**Comment by BeerStud** [comment]
On Fri, 10 Jul 2020 00:37:42 -0700
Ivan Kokan <notifications@github.com> wrote:

> I would say that TeXworks belong to MiKTeX's essential set
> (`Level=S`) due to pragmatic reasons, i.e. having LaTeX novices ready
> to typeset with some guaranteed editor/IDE. Looking at
> tex.stackexchange.com, one can tell that a very large number of
> people (not necessarily novices) do not realize the difference
> between editor/IDE and compiler and other things, so having something
> pre-installed probably helps much more than not having it.
> 
> Assuming that level declarations are static, it is the expected
> behavior that MiKTeX always checks whether everything from essential
> set is installed or not.
> 
> File associations are a different story, and one should know how to
> set them if they are not as wanted. (But I understood your point
> about it.)
> 
> These are just my thoughts on this matter.

Personally, I would like to see an option to install either TeXworks or
TeXstudio. Obviously, the end user may have an editor that they prefer
over either of the two mentioned. In that case an option not to
install an editor should be made available.

Just my 2¢.

-- 
Gerard

**Comment by gnw3** [comment]
It could be useful to be able to create site-specific packages for MiKTeX.   Large organizations have proprietary formats which include official or proprietary logos and styles that should not be distributed outside the organization.  Currently these as well as commercial fonts are installed to a "user-managed" TEXMF root directory.   Keeping those directories up-to-date creates extra work for IT. The ability to create 3rd party packages could also be used to create a "dummy" package that end users could install to satisfy a dependency on a standard package such as TeXworks.   This use of dummy packages is common for linux distros where the distro TeX packages are outdated, for example: [texlive dummy RPM package for EL7.](https://ctan.org/pkg/texlive-dummy-enterprise-linux-7?lang=en)   After installing a current TeX Live (or MiKTeX) the distro packages are removed and a dummy package installed so requirements by other packages are satisfied.

**Comment by crxyz0** [comment]
Any updates? This would be nice since I prefer TeXstudio over TeXworks.

**Comment by anissbenthami** [comment]
How can I uninstall TeXworks?
