### ISSUE TITLE
upon rebuilding all formats: invalid value definition in mltex.ini

### ISSUE THREAD

**Issue by ComFreek** [MiKTeX/miktex#584]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

When rebuilding all formats in the Miktex Console (admin mode), I get `invalid value definition` referencing `mltex.ini` (shown below) in line 18 (last line).

Is `xd` actually valid syntax or should I delete it?

```

;;; Written in 2019 by Christian Schenk
;;;
;;; To the extent possible under law, the author(s) have dedicated all
;;; copyright and related and neighboring rights to this file to the
;;; public domain worldwide.  This file is distributed without any
;;; warranty.  You should have received a copy of the CC0 Public
;;; Domain Dedication along with this file.  If not, see
;;; http://creativecommons.org/publicdomain/zero/1.0/.

[Core.FileTypes.tex]

	!clear Paths[]
	Paths[] = .
	Paths[] = %R/tex/plain//
	Paths[] = %R/tex/generic//
	Paths[] = %R/tex/latex//
	Paths[] = %R/tex//
xd
```

**Comment by edocevoli** [comment]
Thank you. Indeed, the last line is garbage.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
