### ISSUE TITLE
PdfLaTeX fails to compile any saved .tex file, "I can't write on file `filename.pdf'. \begin{document}" error

### ISSUE THREAD

**Issue by PolDag** [MiKTeX/miktex#585]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am using MiKTeX 2.9 with TeXstudio on Windows 10 and compiling with PdfLaTeX. Everything worked fine until last week, then I stopped working on the project and when I started again yesterday it couldn't compile any .tex file when saved in any folder, even a simple HelloWorld code. If I create a new .tex file, it works fine as long as I don't save it, but upon saving and recompiling the error "I can't write on file 'filename.pdf'. \begin{document}" or "I can't write on file 'filename.pdf'. \end{document}" pops up again. More specifically, this is the error log:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.6.29) (preloaded format=pdflatex 2020.7.14)  14 JUL 2020 13:14
entering extended mode
**./prova.tex
(prova.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-06-18>
("C:\Program Files\MiKTeX\tex/latex/base\book.cls"
Document Class: book 2019/12/20 v1.4l Standard LaTeX document class
("C:\Program Files\MiKTeX\tex/latex/base\bk10.clo"
File: bk10.clo 2019/12/20 v1.4l Standard LaTeX file (size option)
)
\c@part=\count167
\c@chapter=\count168
\c@section=\count169
\c@subsection=\count170
\c@subsubsection=\count171
\c@paragraph=\count172
\c@subparagraph=\count173
\c@figure=\count174
\c@table=\count175
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen134
)
("C:\Program Files\MiKTeX\tex/latex/l3backend\l3backend-pdfmode.def"
File: l3backend-pdfmode.def 2020-06-29 L3 backend support: PDF mode
\l__kernel_color_stack_int=\count176
\l__pdf_internal_box=\box45
)
(prova.aux)
\openout1 = `prova.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.

! I can't write on file `prova.pdf'.
Please type another file name for output
! Emergency stop.
<to be read again> 
                   \endgroup \set@typeset@protect 
l.4 \end{document}
                  
*** (job aborted, file error in nonstop mode)

Here is how much of TeX's memory you used:
 382 strings out of 480790
 6340 string characters out of 2907055
 238890 words of memory out of 3000000
 16479 multiletter control sequences out of 15000+200000
 532691 words of font info for 25 fonts, out of 3000000 for 9000
 1141 hyphenation exceptions out of 8191
 25i,4n,19p,140b,133s stack positions out of 5000i,500n,10000p,200000b,50000s
!  ==> Fatal error occurred, no output PDF file produced!
```

I tried reinstalling both MiKTeX 2.9 and TeXstudio, deleting all files except for .tex files, checking for updates in both admin and user modes, but nothing seems to work. I also want to point out that the pdf is not open in any other program like Adobe, because I use TeXstudio's internal pdf viewer. I will attach the installation report and all the log files. Any kind of help would be greatly appreciated, please bear with me because I'm very new to coding and I'm learning on the run.

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/4918407/miktex-report.txt)
[mkfntmap_admin.log](https://github.com/MiKTeX/miktex/files/4918408/mkfntmap_admin.log)
[mpmcli_admin.log](https://github.com/MiKTeX/miktex/files/4918409/mpmcli_admin.log)
[pdftex_admin.log](https://github.com/MiKTeX/miktex/files/4918410/pdftex_admin.log)
[initexmf_admin.log](https://github.com/MiKTeX/miktex/files/4918411/initexmf_admin.log)
[miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/4918412/miktex-console_admin.log)
[miktex-fc-cache_admin.log](https://github.com/MiKTeX/miktex/files/4918413/miktex-fc-cache_admin.log)

**Comment by edocevoli** [comment]
You have attached the log admin-mode log files. Please also attach the user-mode log files (search under `%LOCALAPPDATA%\MiKTeX`).

**Comment by PolDag** [comment]
@edocevoli Sorry I didn't know they were different. Here we go:

[bibtex.log](https://github.com/MiKTeX/miktex/files/4918694/bibtex.log)
[initexmf.log](https://github.com/MiKTeX/miktex/files/4918695/initexmf.log)
[kpsewhich.log](https://github.com/MiKTeX/miktex/files/4918696/kpsewhich.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/4918698/miktex-console.log)
[miktex-fc-cache.log](https://github.com/MiKTeX/miktex/files/4918699/miktex-fc-cache.log)
[miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/4918700/miktex-makefmt.log)
[miktex-pdftex.log](https://github.com/MiKTeX/miktex/files/4918701/miktex-pdftex.log)
[mkfntmap.log](https://github.com/MiKTeX/miktex/files/4918702/mkfntmap.log)
[mpmcli.log](https://github.com/MiKTeX/miktex/files/4918703/mpmcli.log)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/4918704/pdflatex.log)
[pdftex.log](https://github.com/MiKTeX/miktex/files/4918705/pdftex.log)

**Comment by edocevoli** [comment]
It is a little bit odd that texstudio execeutes `pdflatex` installed in `%LOCALAPPDATA%l\Programs\MiKTeX 2.9\miktex\bin\x64`. I would recommend that you empty this folder. Then recreate the links by running (as administrator):

```
initexmf --admin --mklinks --force
```

**Comment by PolDag** [comment]
@edocevoli First of all thanks a lot for your answer! Second, I found the folder but I don't know where should I run that code, in the command prompt? (sorry for my ignorance, I'm really new to this)

**Comment by edocevoli** [comment]
If you have found the folder, then you should delete it:

1. in Windows start menu, search/open `Command Prompt`
1. enter: `rmdir /S /Q %LOCALAPPDATA%l\Programs\MiKTeX 2.9`

You now have removed leftovers from an old MiKTeX installation.

This should be enough to fix the issue.

**Comment by PolDag** [comment]
@edocevoli Unfortunately it doesn't work. I tried what you said but nothing changed, so I uninstalled again miktex making sure that any related folder in AppData and ProgramFiles were deleted as well, then I reinstalled it but the issue still persists

**Comment by u-fischer** [comment]
What do you get if you run on a command line 

 where pdflatex

?

**Comment by PolDag** [comment]
@u-fischer I get the directory C:\Users\Paolo\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\ for both commands

**Comment by u-fischer** [comment]
and what do you get from `initexmf --report` and `initexmf --admin --report`?

**Comment by PolDag** [comment]
@u-fischer This is the first:

```
C:\Users\Paolo\Desktop\PoliMi\tesimagistrale\tesi\tesi>initexmf --report
185 [0x0000264c] INFO initexmf null - this is MiKTeX Configuration Utility 4.0 (MiKTeX 20.6.29)
185 [0x0000264c] INFO initexmf null - this process (8896) started by 'cmd' with command line: initexmf --report
187 [0x0000264c] DEBUG initexmf null - changed console output code page from 850 to 65001
187 [0x0000264c] INFO initexmf null - Operating on the private (per-user) MiKTeX setup
ReportDate: 2020-07-14 17:51:27
CurrentVersion: 20.6.29
SetupDate: not yet
SetupVersion: 20.6.29
Configuration: Regular
GitInfo: 4164370 / 2020-06-30 20:16:39
OS: Windows 10 Home, 64-bit, build 18363
SharedSetup: no
LinkTargetDirectory: C:\Users\Paolo\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\Paolo\AppData\Roaming\MiKTeX
Root1: C:\Users\Paolo\AppData\Local\MiKTeX
Root2: C:\Users\Paolo\AppData\Local\Programs\MiKTeX
Root3: C:\ProgramData\MiKTeX
Root4: C:\Program Files\MiKTeX
UserInstall: C:\Users\Paolo\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\Paolo\AppData\Roaming\MiKTeX
UserData: C:\Users\Paolo\AppData\Local\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
269 [0x0000264c] INFO initexmf null - this process (8896) finishes with exit code 0
```
and this is the second:

```
C:\Users\Paolo\Desktop\PoliMi\tesimagistrale\tesi\tesi>initexmf --admin --report
Option --admin only makes sense for a shared MiKTeX setup.

Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:

  Option --admin only makes sense for a shared MiKTeX setup.
```

but this is surely because I reinstalled it only for my user as administrator. Moreover I managed to somehow make it worse because now it doesn't compile at all and says that the file miktex/config/win\log4cxx.win.xml part of the package miktex-config-2.9 is missing, but it won't let me intall it.
I believe that **completely** remove MiKTeX and a fresh installation (or a factory reset) is the only way now, but I don't know how

**Comment by u-fischer** [comment]
Well you seem to have single user installation (now). The only obvious difference to my system is that you are in a admin account. Do you have some protection system (virus etc) that could kick in and prevent the writing of a pdf? Can you save an arbitrary file in the folder as "test.pdf"?

**Comment by PolDag** [comment]
@u-fischer thank you thank you thank you
Yes, it was the antivirus's fault! Avast's new update somehow interfered with TeXstudio's ability to download some required package, but after deactivating Avast it was able to compile again, and now it works perfectly even with the antivirus on.
I really can't thank you enough, you saved me A LOT of trouble

**Comment by caoimhinoc** [comment]
I had a similar issue and thanks to this thread was able to solve it by adding TexWorks to Avast's list of allowed apps.
