### ISSUE TITLE
MikTex installation Error on Win 10

### ISSUE THREAD

**Issue by Kamhamea** [MiKTeX/miktex#588]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
Details:fileName="C:\Program Files\MiKTeX\miktex\bin\x64\mpm.exe", exitCode="1"

I started the installation file as admin, but the log seems to say that error is because of missing admin privileges

[setup-2020-07-15-12-21.log](https://github.com/MiKTeX/miktex/files/4924828/setup-2020-07-15-12-21.log)

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue.
