### ISSUE TITLE
Error while installing Miktex Win 10

### ISSUE THREAD

**Issue by YuvalLarom** [MiKTeX/miktex#59]
I uninstalled MikTex on my computer a few days ago, and I'm trying to install it again. The problem is that I'm getting error right after I open the installation file 
![xyj6w](https://user-images.githubusercontent.com/36202732/35872661-12147e14-0b70-11e8-81fb-9ad5ffda2416.jpg)

**Comment by edocevoli** [comment]
Unfortunately I cannot reproduce the issue with the given information.
