### ISSUE TITLE
env. variable - local addition file not found

### ISSUE THREAD

**Issue by petergasparovic** [MiKTeX/miktex#590]
In Miktex 2.9.6942 I have had my local additions (*.sty, *.bst, *.csf) in directory
c:\Users\pegas\AppData\Roaming\MiKTeX\pegas\
and I have written the same to system variables
BSTINPUTS
TEXINPUTS
TEXINDEXSTYLE
https://docs.miktex.org/manual/envvars.html

However, when I did the same in miktex-20.6.29-x64,
I have received these messages:
pdflatex >
LaTeX Error: File ...sty not found
bibtex8 > 
Error: cannot open CS file ...
I couldn't open ... file ...bst

I experimented with the various locations:
c:\pegas\ is OK
c:\Users\pegas\AppData\pegas\ is OK
c:\Users\pegas\AppData\Roaming\pegas\ is OK
c:\Users\pegas\AppData\Roaming\pegas123456789\ is OK
c:\Users\pegas\AppData\Roaming\MiKTeX\pegas\ is ERROR
c:\Users\pegas\AppData\Roaming\a123456789\pegas\ is OK

I don't understand, why nesting under MiKTeX directory gives error.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/4943712/miktex-report.txt)
)

**Comment by edocevoli** [comment]
`c:\Users\pegas\AppData\Roaming\MiKTeX\pegas` is under a MiKTeX root directory and that could be a problem. I would recommend that you choose a location not managed by MiKTeX to store your input files.
