### ISSUE TITLE
Conflict between Inverse-search function and "pdfpages" package

### ISSUE THREAD

**Issue by Yinifer** [MiKTeX/miktex#591]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am using the latest Miktex with the most updated packages on Win10 platform. No matter I use Texstudio or Texwork, if I call "pdfpages" at the very beginning (even if I don't actually use any function of this package in my main body), the inverse search function failed. It always points to some codes actually corresponding to somewhere in the next page.

To trigger it you just simply create any document with "usepackages{pdfpages}", at least in my case. I have another laptop running 2016 version latex and it doesn't have this problem. So I guess the problem may be associated with the new release of either the package or the Latex system. I have contacted the maintainer of the package and he thought this may not be a bug of the package.

It is strange since the inverse-search works well on the right side (5-10 columns) of the pdf file, but doesn't work on the left side. So if I make the margin of the file to be very large on both sides (for example > 2.5 inch) the problem gone. Of course if I simply disable pdfpages, everything back to normal.

**Comment by edocevoli** [comment]
This is not a MiKTeX-specific bug and so cannot be fixed by me.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).
