### ISSUE TITLE
set package-installation-from-source in an unattended deployment

### ISSUE THREAD

**Issue by phreeze83** [MiKTeX/miktex#593]
the installer gives us some very nice configuration settings, to use the local appdata instead of roaming profile for users.
Is there a possibility to set the "Package installed from" from the default "random internet package" to a local share e.g "\\server\packages" if a new user starts miktex ? the remote-package-location does not set it

**Comment by edocevoli** [comment]
Seems you are looking for the `----install-from-local-repository`. See here: https://docs.miktex.org/manual/setupwiz.html

**Comment by phreeze83** [comment]
> Seems you are looking for the `----install-from-local-repository`. See here: https://docs.miktex.org/manual/setupwiz.html

it is not this setting. still has random package repository on the internet set
my settings so far are:
basic-miktex.exe
--unattended
--local-package-repository="//server/folder"
--user-install="<LOCALAPPDATA>\Miktex\2.9"
--user-config="<LOCALAPPDATA>\Miktex\2.9"
--user-data="<LOCALAPPDATA>\Miktex\2.9"
--remopte-package-repository="//server/folder"
--install-from-local-repository
--package-set=basic
install

**Comment by edocevoli** [comment]
If you want to install packages from a local package repository, then you can set `[MPM]LocalRepository=\\server\share` (see [here](https://docs.miktex.org/manual/miktex.ini.html)):

```
initexmf --set-config-value=\\server\share
```
