### ISSUE TITLE
New binaries do not start on Vista x86

### ISSUE THREAD

**Issue by gja822** [MiKTeX/miktex#594]
I had MikTeX installation, then I tried to upgrade it from MikTeX Console, it finished without error, but next time I try to start it I get an error "SetCurrentProcessExplicitAppUserModeID entry point not found in DLL SHELL32.dll" (translation from Russian localization).
I tried to make a new install, but the same error not allow me to run MikTeX any more.
No sign of trouble seen when I downloaded updates or new install. No warnings when updated! But my old Vista x86 is now without MikTeX, it's a pitty since I need a LaTeX processor. Any chance to at least find and install a last supported version?

**Comment by gja822** [comment]
ReportDate: 2020-08-01 11:34:25
CurrentVersion: 20.6.29
SetupDate: 2020-08-01 11:15:00
SetupVersion: 20.6.29
Configuration: Regular
GitInfo: 4164370 / 2020-06-30 20:16:39
OS: Windows Vista Home Premium, 32-bit, Service Pack 2, build 6002
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX 2.9\miktex\bin
PathOkay: yes
LastUpdateCheckAdmin: 2020-08-01 10:50:21
LastUpdateAdmin: 2020-08-01 10:42:29
LastUpdateDbAdmin: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\Yury\AppData\Roaming\MiKTeX
Root1: C:\Users\Yury\AppData\Local\MiKTeX
Root2: C:\ProgramData\MiKTeX
Root3: C:\Program Files\MiKTeX
UserInstall: C:\Users\Yury\AppData\Roaming\MiKTeX
UserConfig: C:\Users\Yury\AppData\Roaming\MiKTeX
UserData: C:\Users\Yury\AppData\Local\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX

**Comment by gja822** [comment]
I even unable to deinstall malfunctioning MikTeX due to the same error

**Comment by edocevoli** [comment]
Windows Vista is not a supported platform (see [here](https://miktex.org/kb/prerequisites)).

IIRC, the FAQ has a recipe for removing MiKTeX by hand.
