### ISSUE TITLE
pdftexcmds.sty behavior

### ISSUE THREAD

**Issue by eplain** [MiKTeX/miktex#595]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Since updating MiKTeX July 30, 2020
Using pdftex and eplain, at some point in the processing I have the message:

C:\Users\jlewis\AppData\Roaming\MiKTeX\2.9\tex/generic/pdftexcmds\pdftexcmds.s
ty
pdftexcmds.sty: 2020-06-27 v0.33 Utility functions of pdfTeX for LuaTeX (HO)

! Missing = inserted for \ifnum.
<to be read again>
                   -
<argument> 2020-
                06-27 v0.33 Utility functions of pdfTeX for LuaTeX (HO)
\@parse@version #1/#2/#3#4#5\@nil ->#1
                                      #2#3#4
\@ifl@t@r ...andafter \@parse@version #1//00\@nil
                                                  <\expandafter \@parse@vers...

\eplain@pr@videpackage ...fl@t@r {#2}\usepkg@date
                                                  {}{\message {Warning: you ...

\x #1#2[#3]->\endgroup #2[{#3}]
                               \ifx #1\@undefined \xdef #1{#3}\fi \ifx #1\re...
l.108 ...lity functions of pdfTeX for LuaTeX (HO)]
                                                  %
?
After <enter> processing proceeds normally.

...

**Comment by edocevoli** [comment]
This is not a MiKTeX-specific bug and so cannot be fixed by me.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).
