### ISSUE TITLE
Silent uninstall in Windows

### ISSUE THREAD

**Issue by MaartenKUL** [MiKTeX/miktex#596]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I'm running into issues with the miktexsetup.exe [from the website](https://miktex.org/download) for silent uninstallation.
I use this command: `miktexsetup --verbose --shared=yes uninstall` found in the documentation and get error code 1: `miktexsetup: Unknown/unsupported setup task: uninstall`

Issue looks similar to issue #94

**Comment by edocevoli** [comment]
To run the uninstall task, you must use the `miktexsetup` variant of your MiKTeX installation. The standalone installer (website) cannot be used for this task.

**Comment by ub-jk** [comment]
I have tried the miktexsetup variant and this does not work.  It is appears that the uninstall option is missing from the command now (as indicated in #639).  Can someone please take a look at this issue and not just close the ticket?

**Comment by edocevoli** [comment]
For me, this option is not missing:

```bash
$ miktexsetup --help
Usage: miktexsetup.exe cleanup|download|uninstall
      --common-config=DIR                    Set the location of the common configuration directory. This option requires administrator privileges.
      --common-data=DIR                      Set the location of the common data directory. This option requires administrator privileges.
      --common-install=DIR                   Set the location of the common installation directory. This option requires administrator privileges.
      --common-link-target-directory=DIR     Set the system-wide directory in which to create symbolic links to MiKTeX executables.
      --common-roots=DIRS                    Register additional directories for all users. DIRS must be a semicolon-separated list of fully qualified path names. This option requires
                                             administrator privileges.
      --list-repositories                    Download the list of known package repository URLs from the MiKTeX project server, then print the list.
      --local-package-repository=DIR         Download into (install from) the specified directory.
      --modify-path[=yes|no]                 Add MiKTeX to the PATH variable (--modify-path=yes). With --modify-path=no, the modification of PATH will be prevented.
      --package-set=SET                      Set the package set (one of: essential, basic, complete).
      --portable=DIR                         Set up MiKTeX Portable.
      --print-info-only                      Print information about what would be done and exit.
      --print-program-version                Print the program version number and exit.
      --print-miktex-version                 Print the MiKTeX version number and exit.
      --program-folder=FOLDER                Add shortcuts to the specified program folder.
      --quiet                                Suppress all output (except errors).
      --remote-package-repository=URL        Download from the specified URL. Use --list-repositories to download an up-to-date list of package repositories.
      --shared[=yes|no]                      Operate in admin mode (--shared=yes) or in user mode (--shared=no).
      --trace[=TRACESTREAMS]                 Turn on tracing.  TRACESTREAMS, if specified, is a comma-separated list of trace stream names (see the MiKTeX manual).
      --use-registry[=yes|no]                Write configuration settings into the Windows Registry (--use-registry=yes) or into configuration files (--use-registry=no).
      --user-config=DIR                      Set the location of the user configuration directory.
      --user-data=DIR                        Set the location of the user data directory.
      --user-install=DIR                     Set the location of the user installation directory.
      --user-link-target-directory=DIR       Set the per-user directory in which to create symbolic links to MiKTeX executables.
      --user-roots=DIRS                      Register additional directories for the current user. DIRS must be a semicolon-separated list of fully qualified path names.
      --verbose                              Turn on verbose output mode.
      --version                              Print version information and exit.

Help options:
  -?, --help                                 Show this help message
      --usage                                Display brief usage message

```

**Comment by ub-jk** [comment]
Thank you.  I downloaded the latest version of the setup utility from:
https://miktex.org/download (dated 6/29/2020)

I get the following using that command (i am running command prompt as administrator to make sure) and get the following:

Usage: miktexsetup.exe download|install
      --common-config=DIR                    Set the location of the common configuration directory. This option
                                             requires administrator privileges.
      --common-data=DIR                      Set the location of the common data directory. This option requires
                                             administrator privileges.
      --common-install=DIR                   Set the location of the common installation directory. This option
                                             requires administrator privileges.
      --common-link-target-directory=DIR     Set the system-wide directory in which to create symbolic links to MiKTeX
                                             executables.
      --common-roots=DIRS                    Register additional directories for all users. DIRS must be a
                                             semicolon-separated list of fully qualified path names. This option
                                             requires administrator privileges.
      --list-repositories                    Download the list of known package repository URLs from the MiKTeX project
                                             server, then print the list.
      --local-package-repository=DIR         Download into (install from) the specified directory.
      --modify-path[=yes|no]                 Add MiKTeX to the PATH variable (--modify-path=yes). With
                                             --modify-path=no, the modification of PATH will be prevented.
      --package-set=SET                      Set the package set (one of: essential, basic, complete).
      --portable=DIR                         Set up MiKTeX Portable.
      --print-info-only                      Print information about what would be done and exit.
      --print-program-version                Print the program version number and exit.
      --print-miktex-version                 Print the MiKTeX version number and exit.
      --program-folder=FOLDER                Add shortcuts to the specified program folder.
      --quiet                                Suppress all output (except errors).
      --remote-package-repository=URL        Download from the specified URL. Use --list-repositories to download an
                                             up-to-date list of package repositories.
      --shared[=yes|no]                      Operate in admin mode (--shared=yes) or in user mode (--shared=no).
      --trace[=TRACESTREAMS]                 Turn on tracing.  TRACESTREAMS, if specified, is a comma-separated list of
                                             trace stream names (see the MiKTeX manual).
      --use-registry[=yes|no]                Write configuration settings into the Windows Registry
                                             (--use-registry=yes) or into configuration files (--use-registry=no).
      --user-config=DIR                      Set the location of the user configuration directory.
      --user-data=DIR                        Set the location of the user data directory.
      --user-install=DIR                     Set the location of the user installation directory.
      --user-link-target-directory=DIR       Set the per-user directory in which to create symbolic links to MiKTeX
                                             executables.
      --user-roots=DIRS                      Register additional directories for the current user. DIRS must be a
                                             semicolon-separated list of fully qualified path names.
      --verbose                              Turn on verbose output mode.
      --version                              Print version information and exit.

Help options:
  -?, --help                                 Show this help message
      --usage                                Display brief usage message


As you see, the uninstall is missing.

**Comment by edocevoli** [comment]
Have you read my August 7 comment?

> To run the uninstall task, you must use the miktexsetup variant of your MiKTeX installation. The standalone installer (website) cannot be used for this task.

**Comment by ub-jk** [comment]
Correct me if i am wrong but the only miktextsetup variant I can find is under the downloads under the category of "MiKTeX Setup Utility" (which is a separate download from the net and basic installers).

This has always worked in the past using that exact one.  If this isn't the case can you please provide more detailed instructions on this piece?

**Comment by edocevoli** [comment]
Running `where miktexsetup.exe` gives me:

```
C:\Users\USER\AppData\Local\Programs\MiKTeX\miktex\bin\x64\miktexsetup.exe
```

This is the variant which can be used to remove MiKTeX.

**Comment by ub-jk** [comment]
As this is a system install (not user), i have tried running that under the path C:\Program Files\MiKTeX\miktex\bin\x64 (the file is verified that it is there) but it does nothing when running:  
miktexsetup.exe --shared=yes uninstall 
or without --shared

Am I am missing something as that should work?

**Comment by ub-jk** [comment]
Just curious if you have had a chance to look further into the system uninstall not working?

**Comment by edocevoli** [comment]
Running `miktexsetup uninstall` worked for me.

**Comment by ub-jk** [comment]
OK - was this for the "All Users" version of the install (not the just me install).  If so was that the exact command that you used?

**Comment by akalali** [comment]
I don't know why this is closed. No solution was provided and the problem still persists.
But maybe I misunderstood what the uninstall should do. My output is:

```
C:\Program Files\MiKTeX 20.12\miktex\bin\x64>miktexsetup --verbose --shared=yes uninstall
this is MiKTeX Setup Service 4.1 (MiKTeX 20.12)
loading C:\Program Files\MiKTeX\miktex\config\uninst.log...
removing links...
initexmf: security risk: running with elevated privileges
Collecting linked executables in target directory "C:\Program Files\MiKTeX 20.12\miktex/bin/x64"...
initexmf: warning: The lualatex executable could not be found.
cleaning system PATH...
removing root directories...
removing registry settings...
removing 0 registry values...
removing log files...
```

Is that all that the uninstall is supposed to do? Can I now safely delete the `C:\Program Files\MiKTeX 20.12` directory?

And btw.: Is there any other way to unistall MiKTex? I doubt that anyone without command-line experience is able to do this. My `miktex\bin\x64\internal` directory does not contain any uninstall executable.

**Comment by BeerStud** [comment]
On Fri, 23 Apr 2021 02:13:11 -0700, Amir Kalali stated:
>I don't know why this is closed. No solution was provided and the
>problem still persists. But maybe I misunderstood what the uninstall
>should do. My output is:
>
>```
>C:\Program Files\MiKTeX 20.12\miktex\bin\x64>miktexsetup --verbose
>--shared=yes uninstall this is MiKTeX Setup Service 4.1 (MiKTeX 20.12)
>loading C:\Program Files\MiKTeX\miktex\config\uninst.log...
>removing links...
>initexmf: security risk: running with elevated privileges
>Collecting linked executables in target directory "C:\Program
>Files\MiKTeX 20.12\miktex/bin/x64"... initexmf: warning: The lualatex
>executable could not be found. cleaning system PATH...
>removing root directories...
>removing registry settings...
>removing 0 registry values...
>removing log files...
>```
>
>Is that all that the uninstall is supposed to do? Can I now safely
>delete the `C:\Program Files\MiKTeX 20.12` directory?
>
>And btw.: Is there any other way to unistall MiKTex? I doubt that
>anyone without command-line experience is able to do this. My
>`miktex\bin\x64\internal` directory does not contain any uninstall
>executable.

Get a copy of "Revo Uninstaller" <https://www.revouninstaller.com/>. it
works best if used to install the actual program; however, it is able
to analyze and remove virtually all traces of a prior installation
process. It has fixed problems for me in the post.

-- 
Gerard

**Comment by akalali** [comment]
Thank you, but I prefer to not use any third party software for uninstalling a simple program.

**Comment by ub-jk** [comment]
> Thank you, but I prefer to not use any third party software for uninstalling a simple program.

It turns out this is easier than you think (sorry for responding earlier).  What we do is as follows:

We have an install bat file that runs the following:
start /b /wait "" "basic-miktex-21.2-x64.exe" --shared --auto-install=yes --paper-size=Letter --unattended

We also have an uninstall bat file that runs the following:
start /b /wait "" "C:\Program Files\MiKTeX\miktex\bin\x64\miktexsetup.exe" uninstall

It has been a few weeks since I last updated though so the last version I used it on is the 21.2 that is noted above.  Hopefully it works for you.  It took a bit of deciphering to figure this out with help from one of the maintainers and hopefully this helps you as well.
