### ISSUE TITLE
Installing anyway when hitting "back" on windows

### ISSUE THREAD

**Issue by MaPePeR** [MiKTeX/miktex#598]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

#337 is still reproducable for me on Windows 10.

I just downloaded the installer and tried to go "Back" after selecting my favorite paper size. The installer acted as if i had clicked the "Start" Button.

* Open Installer
* Select "All users"  `[Next]`
* Select install location `[Next]`
* Select papersize and install preferences `[Next]`
* Review Settings and find something you would like to change:
```
Install basic packages to 
	E:\Program Files\MiKTeX

Install MiKTeX for all users

Preferred paper size is A4

Packages will be installed after confirmation by user

```
* Press `[Back]`
 * Installer starts as if you clicked `[Start]`

**Comment by edocevoli** [comment]
This has been fixed with MiKTeX 20.10.
