### ISSUE TITLE
how to update Miktex in Ubuntu

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#6]
as i install the miktex in ubuntu step by step and it works perfectly ,but i found no panel alias in windows ,and i found the version 6361 has bug with the fontspec pacakge ,so in windows it is easy to update the miktex just select the miktex update, but in windows i just found no tool and use the mpm command ,but how to update the miktex.and whole pacakge?

**Comment by edocevoli** [comment]
I am planning to release a new deb package in a couple of weeks.
