### ISSUE TITLE
SSL connect error - MikTex .6520-x64

### ISSUE THREAD

**Issue by Norminux** [MiKTeX/miktex#60]
Hello everybody !

First of all, I'm sorry for the mispelling or gramatical error, english is not my mother tongue, but I do my best !

My problem is that I can't update miktex package. I still got the error SSL connect error.

I install basic-miktex-2.9.6520-x64.exe on windows 7 pro. It's  a professional computer. I have a configuration script (.pac) to choose the good proxy. For all standard net this script don't return any proxy, it just return a rox for intranet page. When I'm at home I don't have proxy neither.

I follow the bug tracks 2548 on sourceforge [https://sourceforge.net/p/miktex/bugs/2548/?page=0](url) 

I creat both environemnent variables
I don't have certification error when I go to the web site miktex api [https://api2.miktex.org/](url) I can see a short story ... the unique odd thing is the name of galaxy Ööç I don't know if it's for testing caracters or if there is a problem.

BUT I still have the SSL connect error.

I try install for one user or for all user that's don't change the error message

I follow the step to create a log with dbgview. It's the file joined : [MIKTEX_TRACE.LOG](https://github.com/MiKTeX/miktex/files/1700263/MIKTEX_TRACE.LOG)

Can anyone please help me.

Thank you very much in advance.

**Comment by edocevoli** [comment]
It seems that the MiKTeX doesn't play well with your proxy. I would recommend that you disable the proxy if you need MiKTeX updates. Alternatively, you can set up a local MiKTeX package repository (a mirror of https://ctan.org/tex-archive/systems/win32/miktex/tm/packages) and get your updates from there.
