### ISSUE TITLE
MikTex installation for WSL1 / Ubuntu 20.04 Windows 1909

### ISSUE THREAD

**Issue by pirpyn** [MiKTeX/miktex#603]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

The installation guidelines are incomplete for this system.  Several problem occurs.
- Problem 1: The default GPG program can't add the key
```bash
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
Executing: /tmp/apt-key-gpghome.BQhxPXtnDf/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.BQhxPXtnDf/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr
```
- Solution: Using https://stackoverflow.com/a/61692849, uninstall gpg and install gnupg1
```bash
$ sudo apt remove gpg -y && sudo apt install gnupg1 -y
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
```
Then continue installation for Ubuntu as intended.

- Problem 2: libQt5core is not found when launching the executable
```bash
$ latexmk
latexmk: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

```
- Solution: Using https://superuser.com/a/1348051, strip the library
```bash
$ sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

**Comment by edocevoli** [comment]
Thank you for the info.
