### ISSUE TITLE
Problem with MikTeX installation.

### ISSUE THREAD

**Issue by PatRidley** [MiKTeX/miktex#604]
I have a problem installing MikTeX on a Windows 10 system and I hope someone can help. I have a message saying that MikTeX console cannot run and I should remove the file c:\Users\parid\miktex-console.lock. However my system won't let me delete it. File Explorer hangs when I right-click on it. I cannot uninstall MikTeX for the same reason so cannot re-install. Any help would be much appreciated.

**Comment by edocevoli** [comment]
If the file exists, it means that MiKTeX Console is running. Probably minimized (task bar icon).

**Comment by PatRidley** [comment]
Thanks for the suggestion. I can't see any sign of it on the taskbar. Earlier, in attempt to solve the problem I found a MikTeX process and stopped it using Task Manager, but it didn't help.

**Comment by PatRidley** [comment]
Ah...found it with the help of a google search and Process Explorer. The file was locked by the Carbonite backup system! Stopped that, deleted the file and all seems to be well now. Thanks for pointing me in the right direction.
