### ISSUE TITLE
No hyphenation patterns were loaded

### ISSUE THREAD

**Issue by intractabilis** [MiKTeX/miktex#605]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hyphenation doesn't work. **All languages on the Language tab in the MiKTeX console are checked.**

Ubuntu 20.4, MiKTeX 20.6.29-focal1, private setup, updates checked and installed.

Way to reproduce. Clean install via `sudo apt install miktex`, from `https://ctan.math.illinois.edu/systems/win32/miktex/setup/deb` repo, finish as private setup, download all updates. Run
```
latexmk -xelatex -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error brief.tex
```
with the following file:
```LaTeX
%!TeX encoding = UTF-8 Unicode
\documentclass[12pt, twocolumn]{scrartcl}

\usepackage{polyglossia}
\usepackage{fontspec}

\PolyglossiaSetup{russian}{hyphenmins = {2, 2}}

\setdefaultlanguage{russian}

\setmainfont{FreeSerif}
\newfontfamily{\cyrillicfont}{FreeSerif}

\begin{document}
Все счастливые семьи похожи друг на друга, каждая несчастливая семья несчастлива по-своему.

Все смешалось в доме Облонских. Жена узнала, что муж был в связи с бывшею в их доме
француженкою-гувернанткой, и объявила мужу, что не может жить с ним в одном доме. Положение это
продолжалось уже третий день и мучительно чувствовалось и самими супругами, и всеми членами семьи, и
домочадцами. Все члены семьи и домочадцы чувствовали, что нет смысла в их сожительстве и что на
каждом постоялом дворе случайно сошедшиеся люди более связаны между собой, чем они, члены семьи и
домочадцы Облонских. Жена не выходила из своих комнат, мужа третий день не было дома. Дети бегали по
всему дому, как потерянные; англичанка поссорилась с экономкой и написала записку приятельнице,
прося приискать ей новое место; повар ушел вчера со двора, во время самого обеда; черная кухарка и
кучер просили расчета.
\end{document}
```

You will see on the screen
```
Package polyglossia Warning: No hyphenation patterns were loaded for `latex'
(polyglossia)                I will use \language=\l@nohyphenation instead on i
nput line 8.

))

Package polyglossia Warning: No hyphenation patterns were loaded for `russian'
(polyglossia)                I will use \language=\l@nohyphenation instead on i
nput line 7.

(/home/ave/.miktex/texmfs/install/tex/latex/polyglossia/gloss-russian.ldf
(/home/ave/.miktex/texmfs/install/tex/latex/polyglossia/xpg-cyrillicnumbers.sty
)

Package polyglossia Warning: No hyphenation patterns were loaded for `russian'
(polyglossia)                I will use \language=\l@nohyphenation instead on i
nput line 17.
```

```
$ initexmf --report
ReportDate: 2020-08-21 22:32:59
CurrentVersion: 20.6.29
SetupDate: 2020-08-21 22:18:00
SetupVersion: 20.6.29
Configuration: Regular
GitInfo: 4164370 / 2020-06-30 20:16:39
OS: Linux 5.7.12 #1 SMP Sat Aug 1 16:00:39 PDT 2020 x86_64
SharedSetup: no
LinkTargetDirectory: /home/user/.local/bin
PathOkay: yes
LastUpdateCheck: 2020-08-21 22:20:30
LastUpdate: 2020-08-21 22:19:39
LastUpdateDb: 2020-08-21 22:20:30
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: /home/user/.miktex/texmfs/config
Root1: /home/user/.miktex/texmfs/data
Root2: /home/user/.miktex/texmfs/install
Root3: /var/lib/miktex-texmf
Root4: /var/cache/miktex-texmf
Root5: /usr/local/share/miktex-texmf
UserInstall: /home/user/.miktex/texmfs/install
UserConfig: /home/user/.miktex/texmfs/config
UserData: /home/user/.miktex/texmfs/data
CommonInstall: /usr/local/share/miktex-texmf
CommonConfig: /var/lib/miktex-texmf
CommonData: /var/cache/miktex-texmf
```
[brief.log](https://github.com/MiKTeX/miktex/files/5111999/brief.log)

**Comment by intractabilis** [comment]
> It means: create `xelatex.fmt` by running `initexmf --dump=xelatex`.

Ok, I have the same result. Was it supposed to fix something?
Btw, using lualatex makes no difference.

**Comment by intractabilis** [comment]
I tried yet another Linux distribution. Clean install of the distro, clean built of the latest MiKTeX from the repo, finish local install and downloaded the latest updates via  MiKTeX Console. All languages on the Language tab in the MiKTeX console are checked.

I still see the same error `I will use \language=\l@nohyphenation` and hyphenation doesn't work.

I am not sure what else I can do. I can reproduce this on any system in any circumstances.

In what configuration **"it works for you"**?

**Comment by intractabilis** [comment]
— Doctor, everyone ignores me.
— Next!

**Comment by yordiak** [comment]
did you check whether your mwe works in a system with texlive installed instead of miktex?

**Comment by intractabilis** [comment]
Of course. I use TexLive ever since, because MikTeX is not functional.

**Comment by intractabilis** [comment]
Alright. Closing the bug, because MiKTeX has no future and I am better off with TexLive.

I started looking at the source code of MiKTeX, how it is organized and what it is doing. I concluded that MiKTeX is a powerful machine gun to shot yourself clean of all your ten spare legs along with the pair of the functional one, and shot what is higher as well. No wonder this bug had no traction for two months. Good luck to the users who are using MiKTeX. However, I would suggest to think twice and say “no” to MiKTeX.

**Comment by mancolric** [comment]
> Alright. Closing the bug, because MiKTeX has no future and I am better off with TexLive.
> 
> I started looking at the source code of MiKTeX, how it is organized and what it is doing. I concluded that MiKTeX is a powerful machine gun to shot yourself clean of all your ten spare legs along with the pair of the functional one, and shot what is higher as well. No wonder this bug had no traction for two months. Good luck to the users who are using MiKTeX. However, I would suggest to think twice and say “no” to MiKTeX.

I am facing the same problem with hyphenations. I've spent all the afternoon trying to fix it and it seems impossible. Everything is up to date and still does not work. It is frustrating. Perhaps I also give a try to TexLive.
