### ISSUE TITLE
MiKTeX 20.6.29 64 bit installation bug

### ISSUE THREAD

**Issue by Randomcash55** [MiKTeX/miktex#607]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I was recently trying to download MiKTeX as it is a requirement for another project I am working on. When running the installer I get the following error. 

"The operation could not be completed for the following reason: MiKTeX cannot retrieve attributes for the file 'C:\Users\username\AppData\Local\Microsoft\WindowsApps\python.exe\pdftex.exe'."

![MikTexError](https://user-images.githubusercontent.com/25042201/90987922-c7334780-e55c-11ea-9c89-cda334d848d5.PNG)

I am running a Windows 10 64 bit PC. After downloading the basic installer from the download website, I ran the installation wizard with both normal and admin privileges, selected yes to "download missing files on the fly", then let the installation run to the very end when this error was produced.

**Comment by edocevoli** [comment]
Please create a Zip archive with the log files in it. You should find log files in

    %LOCALAPPDATA%\MiKTeX\miktex\log

and

    %PROGRAMDATA%\MiKTeX\miktex\log

**Comment by Randomcash55** [comment]
[MiKTeX Logs.zip](https://github.com/MiKTeX/miktex/files/5115126/MiKTeX.Logs.zip)

I've separated them by folder

**Comment by edocevoli** [comment]
Thank you. The `PATH` variable is not correctly set and MiKTeX cannot cope with this. As a workaround, you can repair `PATH` to make sure that it only contains directory entries (not paths to binaries like `python.exe`).

**Comment by edocevoli** [comment]
This has been fixed with MiKTeX 20.10. The installer is now tolerant of misspelled `PATH` entries.
