### ISSUE TITLE
HELP ERROR IN THE MIKTEX DEBIAN 9 INSTALLATION PROCESS 

### ISSUE THREAD

**Issue by JairConstantino** [MiKTeX/miktex#608]
Good Day
Of your support for the following problem in MikTex installation in Debian 9. When entering the processes indicated in the official page, it marks the following error, without having success in the solution for its installation. The following error is the one that shows during the installation process.

 
![Error Miktex](https://user-images.githubusercontent.com/70589671/91866085-ba3ae600-ec37-11ea-83fe-3df209e99253.png)

I kindly request your support for a prompt solution.
Regards.

**Comment by edocevoli** [comment]
Sorry, but I do not understand the error messages in the screenshot. Seems you have a problem installing the MiKTeX package. Without more information (context! context! context!) it is not possible for me to help you.

**Comment by JairConstantino** [comment]
The error that marks me is that it cannot find the miktex package when installing it

**Comment by edocevoli** [comment]
Maybe you haven't added the MiKTeX deb repository.

**Comment by JairConstantino** [comment]
The problem is that the installers for debian are not available

**Comment by edocevoli** [comment]
MiKTeX for Linux is distributed as a RPM/DEB package. There are no installers. You use the system package manager to install MiKTeX packages. Maybe you are looking for TeX Live? They have an installer. Hope this helps.
