### ISSUE TITLE
 HELP TO IDENTIFY WHICH PACKAGE IS INTERFERING WITH MIKTEX

### ISSUE THREAD

**Issue by Dmiranda0** [MiKTeX/miktex#611]
Good day
Can you please help me in how I can identify which package is interfering at the time of perform the miktex installation on Debian 9 as it is one of the errors that mark when wanting to install it, without having success in the solution for its installation.

I kindly request your support for a quick solution.
Regards.

**Comment by edocevoli** [comment]
Sorry, that's not possible without more information.
