### ISSUE TITLE
MikTeX on Fedora 32.  Installation conflict. 

### ISSUE THREAD

**Issue by jpcmborges** [MiKTeX/miktex#615]
I followed the usual process for installing MikTeX on Fedora 32.
When I run "sudo dnf install miktex" I get the error:
"the file /usr/share/man/man5/updmap.cfg.5.gz from installation of miktek-20.6.29-1.fc32.x86_64 is in conflict with the file from package texlive-tetex-7:20190410-12.fc32.noarch"
What should I do to solve this problem?
My best regards,
João Paulo Borges

**Comment by edocevoli** [comment]
The only workaround (at the moment) is to remove the conflicting packages.

**Comment by jpcmborges** [comment]
I think I didn't explain well the situation.

Here is:

[root @ joaoborges /] # sudo dnf install miktex
Last metadata expiration check: 0:07:43 on thu 10 sep 2020 18:47:15.
Dependencies resolved.
================================================== ================================================== =========================================
 Package Architecture Version Repository Size
================================================== ================================================== =========================================
Installing:
 miktex x86_64 20.6.29-1.fc32 miktex-fedora-32 18 M
Installing dependencies:
 cmake-filesystem x86_64 3.17.4-1.fc32 updates 15 k
 log4cxx x86_64 0.10.0-30.fc32 fedora 528 k
 uriparser x86_64 0.9.4-1.fc32 updates 61 k

Transaction Summary
================================================== ================================================== =========================================
Install 4 Packages

Total size: 18 M
Installed size: 68 M
This is ok [y / N]: y
Downloading packages:
[SKIPPED] cmake-filesystem-3.17.4-1.fc32.x86_64.rpm: Already downloaded
[SKIPPED] uriparser-0.9.4-1.fc32.x86_64.rpm: Already downloaded
[SKIPPED] log4cxx-0.10.0-30.fc32.x86_64.rpm: Already downloaded
[SKIPPED] miktex-20.6.29-1.fc32.x86_64.rpm: Already downloaded
Performing transaction verification
The transaction verification was successful.
Running the transaction test
The downloaded packages were cached until the next successful transaction.
You can remove cached packages by running 'dnf clean packages'.
Error: Transaction test error:
  the /usr/share/man/man5/updmap.cfg.5.gz file from the miktex-20.6.29-1.fc32.x86_64 installation conflicts with the texlive-tetex-7: 20190410-12 package file. fc32.noarch

Would you like to help me?

Thanks a lot for your attention,
João Paulo Borges

**Comment by edocevoli** [comment]
I can only repeat myself: the only workaround is to remove the conflicting package: `texlive-tetex-7: 20190410-12`

**Comment by jpcmborges** [comment]
Good evening,
Would you like to send me an email with the commands in order to delete the
file "texlive-tetex-7: 20190410-12"?
Thank you very much,
João Paulo Borges

Christian Schenk <notifications@github.com> escreveu no dia quinta,
10/09/2020 à(s) 20:11:
