### ISSUE TITLE
MikTeX on Windows 7

### ISSUE THREAD

**Issue by IloveJesusmyKing** [MiKTeX/miktex#617]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am wanting to install MikTex on a Windows 7 machine but notice that Windows 8 or 10 are [prerequisites](https://miktex.org/kb/prerequisites). Is there any way I can work around this?

**Comment by edocevoli** [comment]
Sorry, but there is not workaround. Windows 7 is not supported.
