### ISSUE TITLE
Miktex on MacOS 10.13.6,Installtion error

### ISSUE THREAD

**Issue by Jimmy-C-Git** [MiKTeX/miktex#618]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
After click the "Finish private setup" button, I've met a setup issue.
<img width="775" alt="miktex-installation-bug" src="https://user-images.githubusercontent.com/18464016/93092661-4d612a80-f6d2-11ea-9dd8-0414588bb508.png">
And the remediation to update miktex  is also not successful.
<img width="693" alt="update" src="https://user-images.githubusercontent.com/18464016/93093096-dc6e4280-f6d2-11ea-91c8-98a8076dcc5b.png">

[log.zip](https://github.com/MiKTeX/miktex/files/5218890/log.zip)

According to the log file, after google the "dyld: Symbol not found: ____chkstk_darwin", the problem might happen because of  the dynamic lib in the MacOS 10.13.6?
What should I do to solve this problem?

**Comment by pcorpet** [comment]
Hi @Jimmy-C-Git , I have the same issue how did you solve it?

It seems that the Mac OS build on miktex.org is only compatible with macOS 10.15 (Catalina) nowadays

**Comment by Jimmy-C-Git** [comment]
> Hi @Jimmy-C-Git , I have the same issue how did you solve it?
> 
> It seems that the Mac OS build on miktex.org is only compatible with macOS 10.15 (Catalina) nowadays

I don't want upgrade my macOS, so I just replace miktex with MacTex, and It's working well.
