### ISSUE TITLE
MikTeX 20.6.29-x32.exe: unable to select the repository where to download the packages

### ISSUE THREAD

**Issue by SSebastiano** [MiKTeX/miktex#619]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
At least for six months, after an old updated, I would to know the reason because the MikTeX console doesn't give me the possibility to choose the server where to download the packages both in user and administrator mode: 

- I click on **Install from: a random package repository on the internet**. Clicking on **Connection Settings**, as I have always done, I find the window below - **use a proxy server**.

The link of my question on TeX.SE with the images is:
https://tex.stackexchange.com/questions/562540/unable-to-select-the-repository-where-to-download-the-packages

I use OS W7 32-bit and actually MikTeX works correctly. My problem is only the absence of Next button (see the screenshots) to choose my remote package repository.
I hope that to receive an answer and to fix my simple problem.
Thank you very much and my best regards.

Sebastiano

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
