### ISSUE TITLE
problem with the biblatex package after MikTeX update ("! Math formula deleted: Insufficient symbol fonts.")

### ISSUE THREAD

**Issue by Magger** [MiKTeX/miktex#62]
I have recently updated my MikTeX 2.9 installation (64 bit) under Windows 10 (64 bit) using the admin update and user update programs. Everything runs fine, except that I cannot use the biblatex package anymore. Loading it via the usepackage command in a LaTeX document and compiling with pdflatex produces the following error in the log file:

```
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.3776   australian,newzealand}
                               
You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

! Math formula deleted: Insufficient symbol fonts.
\expandafter ->american|
                        
l.3776   australian,newzealand}
                               
Sorry, but I can't typeset math unless \textfont 2
and \scriptfont 2 and \scriptscriptfont 2 have all
the \fontdimen values needed in math symbol fonts.
```

This errors happens about a hundred times, then pdflatex stops. The error happens while processing the biblatex.sty, which is the following version:
```
% Set up the version strings here
\def\abx@date{2017/12/19}
\def\abx@version{3.10}
```

**Comment by u-fischer** [comment]
This is due to a bug in etoolbox which has been already repaired. The corrected version is on ctan and in texlive and will reach miktex soon too. A work around is here:

https://tex.stackexchange.com/a/413899/2388

**Comment by Magger** [comment]
Thanks for the quick help, this is very much appreciated.

**Comment by u-fischer** [comment]
A warning: etoolbox v2.5c contains another bug (a work around isn't known yet), so 2.5d will have to appear soon.
