### ISSUE TITLE
Completely silent installation

### ISSUE THREAD

**Issue by pahmd** [MiKTeX/miktex#620]
I am trying to install MiKTeX 20.6.29 in ProgramData using my script below.
basic-miktex-20.6.29-x64.exe --user-install=C:\ProgramData\MiKTeX --unattended
I have my installation working all good but is there a way i can completely silent the progress of installation? I have this below progress window and i'd like to complete silent it.
![Screenshot](https://user-images.githubusercontent.com/71073476/93175572-1de10b00-f730-11ea-9a8b-421a4a73c317.jpg)

**Comment by edocevoli** [comment]
You want to use the command-line installer.
