### ISSUE TITLE
miktex console can report package versions that do not match the build process (Appdata vs Program Files)

### ISSUE THREAD

**Issue by nicfreeman1209** [MiKTeX/miktex#622]
Miktex had (at presumably different points in time) downloaded two different versions of etoolbox:
(1) a version from 2018 in C:\Users\nicfr\AppData\Roaming\MiKTeX\2.9\tex\latex\etoolbox
(2) the latest version from 2020 in C:\Program Files\MiKTeX 2.9\tex\latex\etoolbox
When pdflatex was run, it used version (1), and said so in the logfile. However the miktex console reports only version (2) and incorrectly gives the impression that the package is up to date.

Deleting version (1) manually fixed the problem. However, I think the behaviour of the package manager within miktex console here is (essentially) a bug.

A guess: the underlying cause is related to having only user level privileges when packages are downloaded on the fly, versus having admin level privileges when packages are downloaded/updated in the miktex console.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
This is by design. User directories have higher precedence than system-wide directories.

**Comment by nicfreeman1209** [comment]
Of course I know that - my bug report is that the package manager GUI incorrectly reports which version _will_ be used.

**Comment by edocevoli** [comment]
So you agree that if you run MiKTeX Console in admin mode, then you do not see the contents of any user directories (there can be multiple MiKTeX users)? That's what admin mode is for: separation of admin/user tasks.

**Comment by nicfreeman1209** [comment]
> So you agree that if you run MiKTeX Console in admin mode, then you do not see the contents of any user directories (there can be multiple MiKTeX users)? 

Yes

>That's what admin mode is for: separation of admin/user tasks.

I simply expected "administrator" access to be a complete picture of what was going on; that is not so unusual.
