### ISSUE TITLE
Problem downloading files with miktex-setup for a local package repository

### ISSUE THREAD

**Issue by christophvw** [MiKTeX/miktex#625]
I try to create a local package repository with the latest miktex-setup.exe

cmd-line:
miktexsetup.exe --verbose --local-package-repository=D:\MiKTeX\repo --package-set=complete download > D:\MiKTeX\sync.log

The command seems to complete successfully and downloads 864 files.
But many packages available online (like beamer) are not downloaded at all.

When I download the beamer package manually and put it into my local repo folder it will be recognized on the next sync as up to date.

How do I get miktex-setup.exe to download all available packages?

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Just executed the command and it has downloaded more than 3980 files.

**Comment by christophvw** [comment]
Our proxy blocked the download of a file because of a too high compression ratio.

BUT: miktex-setup should log an error when it fails to download a package!

**Comment by edocevoli** [comment]
Have you checked the exit code?
