### ISSUE TITLE
miktexsetup.exe --local-package-repository does not log errors

### ISSUE THREAD

**Issue by christophvw** [MiKTeX/miktex#627]
Running miktexsetup.exe --verbose --local-package-repository does not log erros when it fails to download files (i.e. download blocked by proxy).

Download stopped after downloading ~360 files without any error here. The problem is: everything looked OK in the log - and I only noticed that the sync failed when users complained because updating packages do not work.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you. Which variant of `miktexsetup` is in use?

a) the standalone version
b) the one that is installed

If a): there should be a log file named `download-...` in the local repository.

In any case, the `miktexsetup` exit code can be inspected to find if anything went wrong.

**Comment by edocevoli** [comment]
I was not able to reproduce the issue: I get an error message:

```
downloading https://ctan.mirror.norbert-ruehl.de/systems/win32/miktex/tm/packages/arara.tar.lzma (expecting 16121073 bytes)...
miktexsetup.exe: Failure when receiving data from the peer
miktexsetup.exe: Data: code="56", url="https://ctan.mirror.norbert-ruehl.de/systems/win32/miktex/tm/packages/arara.tar.lzma"
```

The exit code is: 1
