### ISSUE TITLE
Cannot update MiKTeX: code 56

### ISSUE THREAD

**Issue by becodified** [MiKTeX/miktex#628]
Hi,

I have downloaded and installed the latest release 7/3/2020 and cannot check for updates neither using remote package repository in the miktex console nor local package respository via commandline utility miktexsetup. Always getting error `code="56", url="https://api2.miktex.org/hello"`.

Can someone help me out?

My setup:
- Windows 10
- MiKTeX 7/3/2020, https://miktex.org/download, Windows Installer

Thank you,
Bea

**Comment by edocevoli** [comment]
Please give us some more context. It would be nice if you collect the log files.
Have you read the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)?

**Comment by becodified** [comment]
Ok, thank you!

Please find the files attached and more context below:

1s approach via remote repository:
- downloaded MiKTeX Windows installer 7/3/2020 from https://miktex.org/download
- executed installer in admin mode
- opened MiKTeX console and switsched to administrator mode 
- run "check for updates" via Overview section
- got error code="6", url="https://api2.miktex.org/hello"
- added company proxy (always the proxies which are getting ones into trouble) via Updates section > Change > Connection Settings
- run "Check for updates" via Updates section
- got error code="56", url="https://api2.miktex.org/hello"

2nd approch via local repository:
- created folder C:\Users\bea\Documents\repos\miktex
- opened command line in admin mode
- run command `miktexsetup --verbose --local-package-repository=C:\Users\bea\Documents\repos\miktex --package-set=complete download`
- got error
`this is MiKTeX Setup Service 4.0 (MiKTeX 20.6.29)
miktexsetup: Failure when receiving data from the peer
miktexsetup: Data: code="56", url="https://api2.miktex.org/hello"`

Other observations:
- installed MiKTeX on computer which is not behind a corporate proxy: installation and update is working like a charm
- called GET on https://api2.miktex.org/hello with browser, got HTTP status code 400 (no matter if am on a pc with or without the company proxy)

Unfortunately I am forced to use MiKTeX behind the company proxy :(
What might cause the code 56?


[miktex-report.txt](https://github.com/MiKTeX/miktex/files/5269106/miktex-report.txt)
[log.zip](https://github.com/MiKTeX/miktex/files/5269105/log.zip)

**Comment by edocevoli** [comment]
Thank you. What are your proxy settings? Is authentication required?

**Comment by aaron-michaux** [comment]
Have the same problem. Cannot figure out how to set the corporate proxy for MikTex.

**Comment by layalachu** [comment]
> Thank you. What are your proxy settings? Is authentication required?

yes.I have the same problem .please help
