### ISSUE TITLE
I cannot install any packages due to error fileName="C:\Program Files\MiKTeX\miktex\bin\x64\miktex-fc-cache.exe", exitCode="1

### ISSUE THREAD

**Issue by limatwo** [MiKTeX/miktex#629]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
Hello
I have googled the error 
I keep getting this error 
fileName="C:\Program Files\MiKTeX\miktex\bin\x64\miktex-fc-cache.exe", exitCode="1" 
I have uninstalled and reinstalled Miktex
I have removed all Latex related programs ( Texstudio and adobe) 

GENERAL MIKTEX INFORMATION
ReportDate: 2020-09-23 16:38:21
CurrentVersion: 20.6.29
SetupDate: 2020-09-23 16:30:00
SetupVersion: 20.6.29
Configuration: Regular
GitInfo: 4164370 / 2020-06-30 20:16:39
OS: Windows 10 Education, 64-bit, build 19041
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-09-23 16:30:50
LastUpdateAdmin: not yet
LastUpdateDbAdmin: 2020-09-23 16:30:45
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX
Root1: C:\Program Files\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
Invokers: non-existing/cmd

ERROR DETAILS
Program: miktex-fc-cache.exe
Error: The executed process did not succeed.
Details: 
  fileName: C:\Program Files\MiKTeX\miktex\bin\x64\miktex-fc-cache.exe
  exitCode: 1

I have attached all the files from the log
[initexmf_admin.log](https://github.com/MiKTeX/miktex/files/5271783/initexmf_admin.log)
[miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/5271785/miktex-console_admin.log)
[miktex-fc-cache_admin.log](https://github.com/MiKTeX/miktex/files/5271786/miktex-fc-cache_admin.log)
[mkfntmap_admin.log](https://github.com/MiKTeX/miktex/files/5271787/mkfntmap_admin.log)
[mpmcli_admin.log](https://github.com/MiKTeX/miktex/files/5271788/mpmcli_admin.log)

**Comment by edocevoli** [comment]
Thank you for the report. Please open a command-prompt as administrator and run `fc-cache` as follows:

```
miktex-fc-cache --miktex-admin --miktex-disable-maintenance --miktex-disable-diagnose --verbose
```

**Comment by limatwo** [comment]
Hello 
Thank you for your message, I have went through with the drastic solution and reset my computer unfortunately. Now Miktex is running like a charm

**Comment by edocevoli** [comment]
Oh, sorry for the hassle. But good to hear that it works now.

**Comment by zomborid** [comment]
@edocevoli I have the same issue, and run the command:
```
PS C:\WINDOWS\system32> miktex-fc-cache --miktex-admin --miktex-disable-maintenance --miktex-disable-diagnose --verbose
Fontconfig error: Cannot load default config file
C:\Program Files\MiKTeX\miktex\bin\x64\miktex-fc-cache.exe: Can't initialize font config library
```
I hope this helps.
