### ISSUE TITLE
Cannot start or run due to incompatibility with 64-bit version of Windows (Win 10 v2004)

### ISSUE THREAD

**Issue by Z-Lun** [MiKTeX/miktex#630]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Recently, I upgraded my OS Win 10 from version v1903 to v2004. Then I failed to run the latex.exe through TexStudio (it worked well before the Win 10 upgrade). The error is shown as

"The program or feature "??\C:....\MiKTex 2.9\miktex\bin\x64\pdflatex.exe" cannot start or run due to incompatibility with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available. "

I tried to install the latex MiKTex but an error "Windows API error 216." paused the installation. I also tried to uninstall the current MiKTex, but an error prompted "This app can't run on your PC. To find a version for your PC, check with the software publisher.".

Is there anyone know the solution for this issue? Thanks a lot.

**Comment by edocevoli** [comment]
Seems you are running MiKTeX 32-bit. I would recommend that you install the 64-bit version of MiKTeX 64-bit.

**Comment by Z-Lun** [comment]
I tried to install "basic-miktex-20.6.29-x64.exe" but it failed. I always used the 64-bit version before I upgraded my OS. Is there any other reason for the failure?

**Comment by Z-Lun** [comment]
> Seems you are running MiKTeX 32-bit. I would recommend that you install the 64-bit version of MiKTeX 64-bit.

I tried to install "basic-miktex-20.6.29-x64.exe" but it failed. I always used the 64-bit version before I upgraded my OS. Is there any other reason for the failure?

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
