### ISSUE TITLE
[basic-miktex-20.6.29-x64] Installation Error: Windows API error 216

### ISSUE THREAD

**Issue by Z-Lun** [MiKTeX/miktex#631]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I encountered an error while install the latest MiKTex [basic-miktex-20.6.29-x64.exe] for OS : Win 10 Home 64-bit v2004. Error message: Windows API error 216.

Any solution is appreciated. Thank you very much.

![image](https://user-images.githubusercontent.com/71942455/94349579-8bc3e700-fffa-11ea-8a21-f819492758e3.png)

**Comment by edocevoli** [comment]
Thank you. It seems that MiKTeX executables cannot run on your system.
