### ISSUE TITLE
make4ht odt compilations on miktex systems fail

### ISSUE THREAD

**Issue by Eng-BIRD** [MiKTeX/miktex#635]
Using make4ht.exe in miktex binaries fails to compile even the most basic tex files when the odt option is selected using `--format odt`. Using `--format XXX` works fine for each html5, tei, xhtml, and docbook. I used the `odt` and `odt+template` options for make4ht compilations for a few years in 2016-2018, but sometime between 2018-2020 (I think) the compilation began to fail.

To reproduce:  Save the following **MWE** to MWEodt.tex in a folder in simple folder tree such as `C:\Home\TexExample\`
`
\documentclass{article}
\begin{document}
	Test
\end{document}
`
navigate a cmd prompt console to the root directory of the MWE and compile it from the command line `make4ht.exe --format "odt" "MWEodt.tex"` (this example assumes the bin directory of miktex is in your environment variables). This process appears to work fine on TexLive, but I've only been able to test TexLive from my linux computer.

The error thrown seems to indicate that miktex is trying to treat the executing directory as a networked or server (UNC) location. The windows computer in question has no networked drives and I've tested this with the miktex installation, source tex files, and executing bat files (or command line prompts from the source directory) all on the same hard drive / partition.  No matter the combination the compilation slows down and the console displays an error message that looks like: `'\\?\C:\Home\TexExample' CMD.EXE was started with the above path as the current directory. UNC paths are not supported.  Defaulting to Windows directory. The system cannot find the file specified. [STATUS]  make4ht: Conversion finished`.  I've also tested a temporary tweak of a registry entry to disable a UNC check.  The compilation still fails with a reduced version of the error although it doesn't slow down.

I keep my miktex fully updated at all times, and while I prefer to run my miktex in portable mode, I have also tested and reproduced this error with a  _installer wizard facilitated extraction and installation_ to the same effect. I have only tested on miktex on windows 7. The sample command line argument above is an example but I have tried a full slew of variations modifying quotes, limiting special characters in paths, and using environment variables vs absolute paths to access the make4ht program, the format options that work, work consistently, and the odt (or odt+template) is the only format that seems to trigger the UNC error.

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/5315880/miktex-report.txt)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket:

**Comment by edocevoli** [comment]
Thank you. I was able to reproduce the bug.

**Comment by edocevoli** [comment]
This has been fixed with MiKTeX 20.10.
