### ISSUE TITLE
miktexsetup.exe 4.0 uninstall not working anymore

### ISSUE THREAD

**Issue by NickETH** [MiKTeX/miktex#639]
Hi Developers,
with version 4.0 of miktexsetup.exe on Windows, the uninstall command is not working anymore.
Return message: miktexsetup.exe: Unknown/unsupported setup task: uninstall

Please fix this ASAP, without it, it is not possible, to automate the packaging for our deployment system.

Thank you.

BR, Nick

**Comment by edocevoli** [comment]
Duplicate of #596
