### ISSUE TITLE
MikTeX repositories list is missing some repositories again

### ISSUE THREAD

**Issue by wdscxsj** [MiKTeX/miktex#64]
Like #40, the Update Wizard includes no Chinese mirrors as of now. Actually the official [MiKTeX Package Repositories](https://miktex.org/pkg/repositories) doesn't, either.

A couple of days ago when testing #53, I'm sure the [SHU mirror](http://mirrors.shu.edu.cn/CTAN/) was automatically selected by the Update Wizard. My experience is that Chinese mirrors have been added and removed intermittently.

The current [CTAN sites page](https://ctan.org/mirrors?lang=en) covers 6 Chinese mirrors. My personal suggestion is to keep at least the [USTC mirror](http://mirrors.ustc.edu.cn/CTAN/) and the [TUNA mirror](https://mirrors.tuna.tsinghua.edu.cn/CTAN/), which are popular and resilient for quite a long time. Thanks.

**Comment by edocevoli** [comment]
```
C:\> wget http://mirrors.shu.edu.cn/CTAN/systems/win32/miktex/tm/packages/pr.ini
--2018-02-11 09:28:28--  http://mirrors.shu.edu.cn/CTAN/systems/win32/miktex/tm/packages/pr.ini
Resolving mirrors.shu.edu.cn (mirrors.shu.edu.cn)... 202.121.199.235
Connecting to mirrors.shu.edu.cn (mirrors.shu.edu.cn)|202.121.199.235|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-11 09:28:29 ERROR 404: Not Found.
```

**Comment by edocevoli** [comment]
If you can access `http://mirrors.shu.edu.cn` in your country, it doesn't mean that other users (from other countries) can access it too. If a mirror cannot be checked, than it will not be available for MiKTeX updates.

**Comment by wdscxsj** [comment]
Hello, that's exactly why I suggested the USTC mirror and the TUNA mirror. Please take the time to check them. Thanks.

```
C:\Tmp\tmp>wget http://mirrors.ustc.edu.cn/CTAN/systems/win32/miktex/tm/packages/pr.ini
--2018-02-11 16:37:15--  http://mirrors.ustc.edu.cn/CTAN/systems/win32/miktex/tm/packages/pr.ini
Resolving mirrors.ustc.edu.cn (mirrors.ustc.edu.cn)... 218.104.71.170, 202.141.176.110
Connecting to mirrors.ustc.edu.cn (mirrors.ustc.edu.cn)|218.104.71.170|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 467 [application/octet-stream]
Saving to: 'pr.ini'

pr.ini                 100%[==========================>]     467  --.-KB/s    in 0s

2018-02-11 16:37:15 (6.11 MB/s) - 'pr.ini' saved [467/467]


C:\Tmp\tmp>wget https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/pr.ini
--2018-02-11 16:37:19--  https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/pr.ini
Resolving mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)... 101.6.6.178
Connecting to mirrors.tuna.tsinghua.edu.cn (mirrors.tuna.tsinghua.edu.cn)|101.6.6.178|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 467 [application/octet-stream]
Saving to: 'pr.ini.1'

pr.ini.1               100%[==========================>]     467  --.-KB/s    in 0s

2018-02-11 16:37:19 (1.04 MB/s) - 'pr.ini.1' saved [467/467]
```

**Comment by edocevoli** [comment]
Mirrors are checked once a day. If `mirrors.ustc.edu.cn` and `mirrors.tuna.tsinghua.edu.cn` are reachable, they will be included in the list. If they are not reachable, they will not be available.

**Comment by wdscxsj** [comment]
Thanks, it's very nice to know how the official repo list has been generated. But there are 6 `.edu.cn` mirrors listed on [CTAN](https://ctan.org/mirrors?lang=en), and none for MiKTeX? Isn't this quite unusual? I often go to [Down For Everyone Or Just Me](http://downforeveryoneorjustme.com/) to get a fair call...

**Comment by edocevoli** [comment]
The `.edu.cn` mirrors have delay, and so are removed from the list:

```
C:\> wget -qO - http://mirrors.ustc.edu.cn/CTAN/systems/win32/miktex/tm/packages/pr.ini | grep version
version=6614
```

The version must be 6615:

```
C:\> wget -qO - http://ftp.leg.uct.ac.za/pub/packages/ctan/systems/win32/miktex/tm/packages/pr.ini | grep version
version=6615
```

**Comment by wdscxsj** [comment]
Thanks for your explanation. I'll try to contact the mirror maintainers to improve this situation.

**Comment by wdscxsj** [comment]
Hello Christian, I sent you an email via https://miktex.org/email involving some technical details about the USTC mirror. Could you have a look and give some advice, please? Thanks.

**Comment by wdscxsj** [comment]
Hello, anything we could do to improve the Chinese mirrors' user experience, please?
