### ISSUE TITLE
Problem entering admin mode on miktex console after update, uninstall not possible

### ISSUE THREAD

**Issue by NNicksen** [MiKTeX/miktex#640]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hello community,

I recently discovered issues using miktex and currently I'm a little bit lost.
My current installation on a Windows 7 PC is based on the installer "basic-miktex-20.6.29-x64.exe". To this point I cannot say, if the first installation was completely sucessful, because I never tried to compile any tex-file. 
For some reason, I did an update yesterday. It ended with an error message which I didn't save. Please be patient with me. After starting the Miktex-console in user mode, I can see that there are no more updates to get. Hence, I thought everything is ok. But when I try to enter the administrator mode, I get this:
![image](https://user-images.githubusercontent.com/72922844/96123431-15c4e880-0ef3-11eb-960e-0ce5384b691c.png)
and further:
![image](https://user-images.githubusercontent.com/72922844/96123472-24ab9b00-0ef3-11eb-943e-8808fb8ff3f4.png)

I tried to compile a dummy tex-file using pdflatex and it worked fine.
But here is the problem:
I have to enter the administrator mode (my main account on this PC has no admin privileges) and after typing the password and stuff I got the same errors again and again.
When I try to uninstall the complete miktex distribution in order to reinstall a clean version of it, I end up with exactly the same error reports. By the way, I used the Windows tool (Control panel) for install and uninstall.

Short summary:
I had a miktex distribution which was updated recently. Now, I got error messages when trying to enter admin mode in the miktex-console. Uninstall is not possible from the Win7-Menu. 

I really hope, that someone can help me to get a clean miktex distribution. Please let me know, what further information or log-files you need to solve this issue. I will stop my activities for now, in order not to make things worse.

Thank you in advance. I appreciate any help.
best regards Nick

the reports from the diagnose page are attached
[miktex-console.log](https://github.com/MiKTeX/miktex/files/5384863/miktex-console.log)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/5384859/miktex-report.txt)

**Comment by edocevoli** [comment]
Please attach the log files which were created in admin mode. You should find them under `%PROGRAMDATA%\MiKTeX`.

**Comment by NNicksen** [comment]
Hello again,

thank you for the information. Here are the log files.
[miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/5389355/miktex-console_admin.log)
[miktex-fc-cache_admin.log](https://github.com/MiKTeX/miktex/files/5389356/miktex-fc-cache_admin.log)
[mkfntmap_admin.log](https://github.com/MiKTeX/miktex/files/5389358/mkfntmap_admin.log)
[mpmcli_admin.log](https://github.com/MiKTeX/miktex/files/5389359/mpmcli_admin.log)

**Comment by edocevoli** [comment]
Thank you. It seems that MiKTeX Console is not allowed to delete files, and so the installation/update fails. For example:

```
2020-10-14 16:03:56,020+0200 ERROR miktex-console.core - Zugriff verweigert

2020-10-14 16:03:56,020+0200 ERROR miktex-console.core - Function: DeleteFileW
2020-10-14 16:03:56,020+0200 ERROR miktex-console.core - Result: 5
2020-10-14 16:03:56,020+0200 ERROR miktex-console.core - Data: path="C:\Program Files\MiKTeX\miktex\bin\x64\MiKTeX200629-core.dll"
2020-10-14 16:03:56,020+0200 ERROR miktex-console.core - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp:326
```

You can try to fix this by disabling AV programs.
