### ISSUE TITLE
Miktex Console fails during Update Processing - Partial File Transfer

### ISSUE THREAD

**Issue by K4Werri** [MiKTeX/miktex#643]
I'm using ther Miktex Console to update the miktex system. It fails with an error saying a partial file was transferred. See deailed information below.

Reproduction is straightforward.
1. open the console
2. select option to enter admin mode
3. check for updates
4. update

[mpmcli_admin.log](https://github.com/MiKTeX/miktex/files/5389770/mpmcli_admin.log)

[mkfntmap_admin.log](https://github.com/MiKTeX/miktex/files/5389768/mkfntmap_admin.log)

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/5389766/miktex-report.txt)

[miktex-fc-cache_admin.log](https://github.com/MiKTeX/miktex/files/5389762/miktex-fc-cache_admin.log)

[miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/5389757/miktex-console_admin.log)

[initexmf_admin.log](https://github.com/MiKTeX/miktex/files/5389748/initexmf_admin.log)

GENERAL MIKTEX INFORMATION
ReportDate: 2020-10-16 17:49:14
CurrentVersion: 20.7
SetupDate: 2020-08-28 17:50:00
SetupVersion: 20.6.29
Configuration: Regular
GitInfo: d26133b / 2020-07-31 18:20:50
OS: Windows 10 Home, 64-bit, build 19041
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-10-16 17:40:25
LastUpdateAdmin: 2020-08-28 17:51:38
LastUpdateDbAdmin: 2020-10-16 17:39:50
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX
Root1: C:\Program Files\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
Invokers: 

ERROR DETAILS
Program: C:\Program Files\MiKTeX\miktex\bin\x64\miktex-console_admin.exe
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:247
Error: Transferred a partial file
Details: 
  code: 18
  url: http://mirror.yongbok.net/ctan/systems/win32/miktex/tm/packages/biber-windows-x64.tar.lzma

**Comment by edocevoli** [comment]
Thank you. This is the complete description of error 18:

> A file transfer was shorter or larger than expected. This happens when the
server first reports an expected transfer size, and then delivers data that
doesn't match the previously given size.

I would recommend that you
- choose another server
- disable potential troublemakers (AV software, proxies)
