### ISSUE TITLE
TeX4ht

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex#644]
Hello!
There is a problem with tex4ht. When I try to start it, I have the error message :

"Impossible d'exécuter le code, car MiKTeX209-app.dll introuvable. La réinstallation du programme peut corriger ce problème."

Best regards

François

**Comment by edocevoli** [comment]
Thank you. It works for me:

```
tex4ht
----------------------------
tex4ht.c (2018-07-03-10:36 Windows MiKTeX)
```

**Comment by petiard** [comment]
OK. It was a path's problem.
Sorry for the noise.
