### ISSUE TITLE
GetUserProfileDirectory with umlauts

### ISSUE THREAD

**Issue by ElCbo** [MiKTeX/miktex#647]
I installed MiKTeX as portable version in D:\MiKTeX

Error is Libraries/MiKTeX/Core/Session/miktex.cpp : 278
Home directory C:\Users\MÃ¼ller does not exist.

The username is Müller

**Comment by edocevoli** [comment]
Please respect the contribution guidelines:

> Make sure that others will be able to reproduce the bug by providing:
> - step-by-step reproduction instructions: describe the exact steps which reproduce the problem in as many details as possible
> - your observations: command output, screenshots
>
> Most importantly: include information about your MiKTeX setup:
> - installation report: let MiKTeX Console create an installation report (on the Diagnose page)
> - contents of the MiKTeX log directory: MiKTeX Console tells you the location of log directory on the Diagnose page
