### ISSUE TITLE
lualatex/xelatex: handling of `stderr` when using pipes

### ISSUE THREAD

**Issue by mrpiggi** [MiKTeX/miktex#648]
Hi,
some context first. I am the developer of the LaTeX package `svg` which uses Inkscape CLI for automated conversion and import of SVG graphics into LaTeX documents. As Inkscape changed it's CLI from 0.9x to 1.0 I was encouraged to build an automatic version detection. Therefore I call `inkscape -V` during a LaTeX run through a pipe in order to read the returned string.

I recently discovered a problem reading from a pipe when both `stdout` and `stderr` are involved. This issue actually emerged as Inkscape v1.0.1 CLI currently uses `stdout` and `stderr` when returning `inkscape -V`. I already reported this issue.

However, I wanted to remark that MiKTeX has problems with handling `stderr` when reading pipes. First the MWE
```tex
\listfiles
\documentclass{minimal}
\usepackage[T1]{fontenc}
\begin{document}
\makeatletter
\@makeother\|%
\@makeother\&%
\everyeof{\noexpand}%

\edef\pipenormal{\@@input|"echo STDOUT && echo STDERR >&2 " }%
normal: \texttt{\pipenormal}

\edef\piperedirect{\@@input|"echo STDOUT && 2>&1 echo STDERR >&2 " }%
redirect: \texttt{\piperedirect}

\end{document}
```
The macro `\pipenormal` reads through a pipe and should expand to the message of `stdout` whereas `\piperedirect` redirects `stderr` to `stdout` and should expand to both messages. I checked this with TeX Live and it works as intended with all different formats (pdflatex, lualatex, xelatex). By contrast, MiKTeX generates different results for all three formats. Those are:
|  | normal | redirected |
|-|-|-|
| expected | STDOUT | STDOUT STDERR |
| pdflatex | STDOUT STDERR | STDOUT STDERR |
| lualatex | STDOUT STDERR | DOUT DERR |
| xelatex | STDERR | STDERR |

**Comment by edocevoli** [comment]
I would recommend that you fix your expectations. Because `echo STDOUT && echo STDERR >&2`, on Windows, outputs:

```
STDOUT
STDERR
```

So the table must look like this:

|  | normal | redirected |
|-|-|-|
| expected | STDOUT STDERR | STDOUT STDERR |
| pdflatex | STDOUT STDERR | STDOUT STDERR |
| lualatex | STDOUT STDERR | STDOUT STDERR |
| xelatex | STDERR | STDERR |

**Comment by mrpiggi** [comment]
> `echo STDOUT && echo STDERR >&2`, on Windows, outputs:
> 
> ```
> STDOUT
> STDERR
> ```
> 
As well es Linux does. My expectations came from the behavior of TeX Live where `stderr` is suppressed/gobbled. But I'm totally fine with your call. Many thanks in avdance.

**Comment by mrpiggi** [comment]
Many thanks!

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.

**Comment by mrpiggi** [comment]
Works like expected. Thanks again!
