### ISSUE TITLE
Compilation get's stuck when using input pipes with inputs larger than 4KB

### ISSUE THREAD

**Issue by svonohr** [MiKTeX/miktex#650]
See the following example which runs an external perl script to generate some input:
input_test.tex:
```
\documentclass{article}
\begin{document}
\input{|perl test.pl}
\end{document}
```
test.pl:
```
my @i = (1..257); # 1..256 works
for (@i){
    print("0123456789ABCDEF");
}
```
When building this document using `pdflatex -enable-pipes -enable-write18 input_test.tex` the process gets stuck and never finishes. The task manager shows pdflatex and perl running with 0% CPU usage. Reducing the loop count to 256 in the perl script makes it work again. I also installed the older MiKTeX 20.6 version which works without problems.

I assume something concerning the buffering is going wrong here, since the buffer size used for pipes is exactly 4KB: https://github.com/MiKTeX/miktex/blob/584abb8925dd739001c0cf23ca100554f67ad4b9/Libraries/MiKTeX/Core/Session/files.cpp#L57

Configuration report:
```
ReportDate: 2020-10-30 12:40:53
CurrentVersion: 20.10
SetupDate: 2020-10-30 12:21:00
SetupVersion: 20.6.29
Configuration: Regular
GitInfo: bebca6e / 2020-10-09 08:52:08
OS: Windows 10 Pro, 64-bit, build 18363
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2020-10-28 12:18:42
LastUpdateAdmin: 2020-10-28 12:18:55
LastUpdateDbAdmin: 2020-10-28 12:18:40
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\svonohr\AppData\Roaming\MiKTeX
Root1: C:\Users\svonohr\AppData\Local\MiKTeX
Root2: C:\ProgramData\MiKTeX
Root3: D:\Temp\MiKTeX
UserInstall: C:\Users\svonohr\AppData\Roaming\MiKTeX
UserConfig: C:\Users\svonohr\AppData\Roaming\MiKTeX
UserData: C:\Users\svonohr\AppData\Local\MiKTeX
CommonInstall: D:\Temp\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
```

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
