### ISSUE TITLE
miktexsetup.exe: MiKTeX encountered an internal error.

### ISSUE THREAD

**Issue by Bummibaer** [MiKTeX/miktex#652]
I've downloaded the version 4.0 of miktexsetup.exe on Win 10 Enterprise.
I ran:
`miktexsetup.exe download--package-set basic --local-package-repository=.\Repository  --verbose`
Runs O.K.
`miktexsetup.exe install --package-set basic --local-package-repository=.\Repository  --verbose`
Gives:
`this is MiKTeX Setup Service 4.0 (MiKTeX 20.6)`
`miktexsetup.exe: MiKTeX encountered an internal error.`
I've found so far: [https://github.com/MiKTeX/miktex/issues/420](url) and tried it with DebugView and --trace. 
Nothing found.

Any help appreciated.

OS Name                 :                            Microsoft Windows 10 Enterprise
OS Version               :                         10.0.18363 Nicht zutreffend Build 18363
System type:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1792 MHz
Language                 :                           de;Deutsch (Deutschland)

Download:
miktexsetup-4.0-x64.zip

**Comment by edocevoli** [comment]
You cannot use the integrated `miktexsetup` to install MiKTeX. For more info, see #596

**Comment by Bummibaer** [comment]
Hi,
I want to install. I see in the topic only question for uninstall.
I use the exe from Download:
miktexsetup --version
MiKTeX Setup Utility (Standalone) 4.0 (MiKTeX 20.6)
miktexsetup.exe --help --verbose

Usage: miktexsetup-4.0-x64\miktexsetup.exe download|install
...

I've downloaded from the website:File name:
miktexsetup-4.0-x64.zip
Size:	2.4 MB
SHA-256:	9be965a35dc917dd6c901b816452bbf41ab4c88e24d90ac1de245f6edea2aa20

I see one difference (MiKTeX 20.6) on mine to (MiKTeX 20.10) on yours.

**Comment by edocevoli** [comment]
Sorry, so you use the standalone variant. What is the issue you are reporting? Please provide as much information as possible.

**Comment by Bummibaer** [comment]
Wow, I've found something. Can it be, thats the command don't read relative Pathes?
I take now:
_miktexsetup.exe install --package-set basic --local-package-repository=**C:Temp\MikTex\Repository** --verbose_
and it works!

The errror comes with the install task:
_miktexsetup.exe install --package-set basic --local-package-repository=**.\Repository** --verbose_
Gives:
this is MiKTeX Setup Service 4.0 (MiKTeX 20.6)
**miktexsetup.exe: MiKTeX encountered an internal error.**

With --trace gives the same.
On an other PC ( Windows Server 2016 ) the same.

I'm not sure about the version, I've downloaded (MiKTex 20.6 vs. 20.10).
_dir miktexsetup-4.0-x64
04.11.2020  09:34         7.413.760 miktexsetup.exe_

Thank you so much.

**Comment by edocevoli** [comment]
Relative path names are now supported.

**Comment by AntonioFasano** [comment]
It seems that for the `--portable` option the *absolute path* is still needed. In my case the setup fails if using:

    .\miktexsetup_standalone --local-package-repository=relative-path --portable=relative-path install 

while it works with

    .\miktexsetup_standalone --local-package-repository=relative-path --portable=absolute-path install
