### ISSUE TITLE
Copy of #522

### ISSUE THREAD

**Issue by fo454684** [MiKTeX/miktex#655]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Because the original relevant bug report was closed without any attempt to solve it and current Miktex is broken on Windows, is it possible to downgrade and/or somehow download ~3/4 year old version?

Original and still present bug: https://github.com/MiKTeX/miktex/issues/522

**Comment by edocevoli** [comment]
Sorry, but only the latest version is officially available.
