### ISSUE TITLE
Check for directory that executable doesn't have permissions for causes crash

### ISSUE THREAD

**Issue by tadgerb** [MiKTeX/miktex#659]
The check for `Directory::Exists` referenced below doesn't check the paths in the PATH environment variable safely, e.g. if any of the paths exist but cannot be accessed for permissions reasons, the call throws an exception; probably rightly so?; causing the `FixProgramSearchPath` to crash out. Ideally, it would instead catch those exceptions and carry on, as it doesn't need to include any paths it doesn't have access to.

https://github.com/MiKTeX/miktex/blob/e4b8ca4fc9f68b5643d18b3d3ffa877351ddd32a/Libraries/MiKTeX/Core/Utils/Utils.cpp#L888

**Comment by Moving-Electrons** [comment]
When working on this bug, please keep in mind that some of us need to install MiKTeX in portable mode because access to windows system folders is not allowed. Thanks!.

**Comment by edocevoli** [comment]
This has been fixed.
