### ISSUE TITLE
Unable to update using terminal

### ISSUE THREAD

**Issue by bedlamzd** [MiKTeX/miktex#661]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Hello!

I am trying to automatize build process with github actions. The issue is I can't find a way to update miktex using terminal only.

I successfully install miktex with instructions from site. But when I try to compile my file I get `major issue: So far, you have not checked for MiKTeX updates.` (as expected, I guess).

You can check history up to [this](https://github.com/mt-lab/MT.Guide/commit/f79c0d45eef958baa71a19147b6c8003a50ab964) commit of what I've tried.

**Comment by edocevoli** [comment]
https://lmgtfy.app/?q=miktex+update+command-line

**Comment by bedlamzd** [comment]
Well, that was of great help.

Are you thinking I have not googled it? Most of the time I find your GUI console solution. I think solution is to use initexmf, but I have tried it and it did not work.

**Comment by bedlamzd** [comment]
As I understand all I have been able to do so far is to update packages and not the actual miktex itself. Anyway the error persists no matter what I have tried.

So could you be kind enough to at least point me at the right page?

Last thing I have tried is to replicate last steps of building from source.

**Comment by edocevoli** [comment]
> Anyway the error persists no matter what I have tried.

You haven't provided a concrete error description, so it is not possible for me to help you with your issue. Please acknowledge the contribution guidelines the next time you submit an issue.
