### ISSUE TITLE
Remove TextLabel label before package installation/uninstallation

### ISSUE THREAD

**Issue by ivankokan** [MiKTeX/miktex#664]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

`TextLabel` shortly appears before the packages get downloaded and installed (or uninstalled):
![image](https://user-images.githubusercontent.com/1058211/100491517-69e2ff80-3124-11eb-957d-25581622136c.png)

**Comment by edocevoli** [comment]
Thank you, this has been fixed.
