### ISSUE TITLE
the new miktex update not compiling my work

### ISSUE THREAD

**Issue by villeantropist** [MiKTeX/miktex#665]
Hi, this is what i frequently get while trying to compile my work since i installed the latest version of miktex in my windows.

**This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.11)

Sorry, but "C:\Program Files\MiKTeX\miktex\bin\x64\miktex-pdftex.exe" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\Ville Joseph\AppData\Local\MiKTeX\miktex\log\miktex-pdftex.log**

below is the pdftex.log

**[miktex-pdftex.log](https://github.com/MiKTeX/miktex/files/5644644/miktex-pdftex.log)**

below is the intexmf.log 
**[initexmf.log](https://github.com/MiKTeX/miktex/files/5644650/initexmf.log)**

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
