### ISSUE TITLE
miktex (lualatex.exe) fails to run from flask subprocess

### ISSUE THREAD

**Issue by tanj** [MiKTeX/miktex#666]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

I am trying to build a latex file using a subprocess call in a flask web-app. 

```python
    def pdf(self, ixTestsheet):
        build_dir = mkdtemp(prefix="testsheet_")
        tsfile = NamedTemporaryFile(dir=build_dir, suffix=".tex", delete=False)
        tsfile.write(self.latex(ixTestsheet, _print_type).encode("utf-8"))
        old_dir = os.getcwd()
        # os.chdir(build_dir)
        latexname = os.path.basename(tsfile.name)
        tsfile.close()

        # added this to check user of subprocess
        dirout = subprocess.run(
            ["whoami.exe"], cwd=build_dir, check=True, capture_output=True
        )
        current_app.logger.info(dirout)
        try:
            subprocess.run(
                [
                    current_app.config["LUALATEX_EXE"],
                    "--interaction=nonstopmode",
                    latexname,
                ],
                cwd=build_dir,
                check=True,
            )
            # call a second time to get a full build with page numbers etc.
            subprocess.run(
                [
                    current_app.config["LUALATEX_EXE"],
                    "--interaction=nonstopmode",
                    latexname,
                ],
                cwd=build_dir,
                check=True,
            )
        except subprocess.CalledProcessError as e:
            current_app.logger.error(build_dir)
            current_app.logger.error(e)
```

If I run the process from the flask app it fails with the following error. If I run the command from an interactive python session it completes.

```
[2020-12-04 11:51:13,512] INFO in testsheets: CompletedProcess(args=['whoami.exe'], returncode=0, stdout=b'<DOMAINNAME>\\<USERNAME>\r\n', stderr=b'')
lualatex.exe: No suitable temporary directory found.

Sorry, but "c:/Program Files/MiKTeX 2.9/miktex/bin/x64/lualatex.exe" did not succeed.
FATAL: No suitable temporary directory found.
FATAL: Data:
FATAL: Source: Libraries\MiKTeX\Core\Session\miktex.cpp:79
[2020-12-04 11:51:13,745] ERROR in testsheets: C:\Users\USERNA~1\AppData\Local\Temp\testsheet_oreb8wg5
[2020-12-04 11:51:13,745] ERROR in testsheets: Command '['c:/Program Files/MiKTeX 2.9/miktex/bin/x64/lualatex.exe', '--interaction=nonstopmode', 'tmpfk6un0c7.tex']' returned non-zero exit status 1.
```

I'm trying to figure out why MiKTeX is not able to find a temporary directory when run from flask, but can when run from an interactive session.

From what I can see:

 1. The user running the command from the flask app is the same as the user running the command from the interactive session.
 2. MiKTeX has all the packages it needs to build the latex file
 3. The subprocess command isn't the problem
 4. Permissions on the temporary directory seem to be fine

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/5645421/miktex-report.txt)

ProcMon on failed subprocess call from flask application
![image](https://user-images.githubusercontent.com/90219/101214352-c10b3780-3630-11eb-8ece-d12b11b8e225.png)

ProcMon on successful subprocess call from interactive python session
![image](https://user-images.githubusercontent.com/90219/101214570-15161c00-3631-11eb-9dca-d3315a4f04bf.png)

I can send the procmon output files to someone, but I don't want to post them with the bug report.

**Comment by edocevoli** [comment]
Seems that `TMP` or `TEMP` are not correctly set when you run MiKTeX. To fix this:
please make sure that the directory specified by `TMP` or `TEMP` exists.

**Comment by tanj** [comment]
`TEMP` env var is set properly in the environment, but `TMP` is somehow being set to an empty string. I'm guessing then that you are checking for the `TMP` or `TEMP` var to exist and just using that? Would `TMP` have to be `unset` to make it use `TEMP`?

I'll set `TMP` = `TEMP` when I run the command. Thanks for your help.

**Comment by edocevoli** [comment]
We use `GetTempPathW` to find the directory. The documentation says:

> The GetTempPath function checks for the existence of environment variables in the following order and uses the first path found:
> 
> 1. The path specified by the TMP environment variable.
> 2. The path specified by the TEMP environment variable.
> 3. The path specified by the USERPROFILE environment variable.
> 4. The Windows directory.

Seems that `TMP` is the preferred environment variable.

**Comment by edocevoli** [comment]
This has to be fixed in some way...

**Comment by edocevoli** [comment]
MiKTeX now checks to see whether `TMP` is correctly set.
