### ISSUE TITLE
testing if pipes are enabled. 

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#669]
Is there a way to test (in all engines) if  pipes are enabled? The following document tries to read the extractbb version to a variable by using a pipe. This works fine in a current miktex  with the default but errors if `--disable-pipes` is used with 

      ! I can't find file `"|extractbb --version"'.

~~~~
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\sys_get_shell:nnNTF {extractbb~--version }{}\l_tmpa_str{}{}
\show\l_tmpa_str
\ExplSyntaxOff
\end{document}
~~~~ 

Can we somehow test for the setting to catch the error?

**Comment by edocevoli** [comment]
That's not possible at the moment. Piped input/output requires that shell escapes are enabled. So to test the feature, I could imagine a shell escape like `miktex config get ...` to test if the feature is enabled. Of course, a TeXdistro-independent utility would be better. But that would have to be coordinated with the TeX live project.

**Comment by u-fischer** [comment]
As far as I can see pipes can not be activated/deactivated independently from shell escape in texlive, so if \pdfshellescape > 0 it works there.

**Comment by edocevoli** [comment]
I don't see that `miktex-luatex` supports the pipe options. So I think it would be best to remove (or noop) these options in `miktex-pdftex` and `miktex-xetex`.

**Comment by edocevoli** [comment]
`--disable-pipes` is now a  no-op, i.e., it has no effect.
