### ISSUE TITLE
Broken MiKTeX after update in Ubuntu 16.04

### ISSUE THREAD

**Issue by ealmuina** [MiKTeX/miktex#67]
Most recent MiKTeX update requires running an additional configuration step after installing it (at least from the package manager). The website now says users have to run `miktexsetup finish` to actually conclude the installation. Now, when I execute that command I'm getting the following error:

```
219548 [.libmpm]: initializing MPM library version 2.9.6584
219716 [.setup]:   Report
219746 [.setup]: 
219906 [.setup]: Date: Wednesday, February 14, 2018
219931 [.setup]: Time: 01:14:06
219991 [.setup]: OS version: Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64
220012 [.setup]: SharedSetup: false
220030 [.setup]: UserRoots: <none specified>
220051 [.setup]: UserData: <none specified>
220071 [.setup]: UserConfig: <none specified>
220092 [.setup]: CommonRoots: <none specified>
220113 [.setup]: CommonData: <none specified>
220137 [.setup]: CommonConfig: <none specified>
220163 [.setup]: Installation: /home/eddy/.miktex/texmfs/install
220192 [.setup]: initexmf --create-config-file=miktex/config/miktex.ini --set-config-value=[Core]SharedSetup=0 --disable-installer --verbose:
243632 [.core]: forking...
245195 [.core]: start reading the pipe
278935 [.core]: read 283 bytes from the pipe
279021 [.core]: waiting for process 16833
279082 [.core]: process 16833 exited with status 0
279163 [.setup]: initexmf --update-fndb --disable-installer --verbose:
279230 [.core]: forking...
280565 [.core]: start reading the pipe
281062 [.core]: read 776 bytes from the pipe
281121 [.core]: waiting for process 16837
281187 [.core]: process 16837 exited with status 0
281287 [.setup]: initexmf --force --mklinks --disable-installer --verbose:
281370 [.core]: forking...
282634 [.core]: start reading the pipe
282811 [.core]: read 210 bytes from the pipe
282890 [.core]: waiting for process 16838
282981 [.core]: process 16838 exited with status 0
283100 [.setup]: initexmf --mkmaps --mklangs --disable-installer --verbose:
283193 [.core]: forking...
284642 [.core]: start reading the pipe
285097 [.core]: read 537 bytes from the pipe
285162 [.core]: waiting for process 16839
285234 [.core]: process 16839 exited with status 1
285421 [.core]: The executed process did not succeed.
285459 [.core]: Data: exitCode="1", fileName="/usr/bin/initexmf"
285482 [.core]: Source: Libraries/MiKTeX/Core/Process/Process.cpp:166
miktexsetup: The executed process did not succeed.
miktexsetup: Data: exitCode="1", fileName="/usr/bin/initexmf"
```

It was working just fine in my computer with the previous version.
(Also posted in Stack Exchange: https://tex.stackexchange.com/questions/415241/broken-miktex-after-update-in-ubuntu-16-04)

**Comment by edocevoli** [comment]
Please inspect all relevant log files. You should find them in

    ~/.miktex/texmfs/data/miktex/log/

and

    /var/log/miktex/

**Comment by ealmuina** [comment]
[home.tar.gz](https://github.com/MiKTeX/miktex/files/1726466/home.tar.gz)
[var.tar.gz](https://github.com/MiKTeX/miktex/files/1726467/var.tar.gz)

**Comment by edocevoli** [comment]
Some of the MiKTeX [TEXMF directories](https://miktex.org/kb/texmf-roots) are not in a healthy state. For example, it seems that you now need root privileges in order to access to some files under `~/.miktex`.

I would recommend that you cleanup your MiKTeX installation with a sledge-hammer:

```
sudo initexmf --admin --remove-links
sudo initexmf --remove-links
sudo rm -fr ~/.miktex
sudo rm -fr /var/lib/miktex-texmf
sudo rm -fr /var/cache/miktex-texmf
sudo rm -fr /usr/local/share/miktex-texmf
```

Please note that this also "uninstalls" all packages.

It then should be possible to run

```
miktexsetup finish
```

to reconfigure MiKTeX for a private setup.

**Comment by haluk** [comment]
latexmk -xelatex example_talk.tex

======================================================================
starting package maintenance...
installation directory: /home/hd/.miktex/texmfs/install
package repository: http://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/
visiting repository http://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/...
repository type: remote package repository
loading lightweight database...
downloading http://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
174767 bytes, 23853.38 KB/Sec
lightweight database digest: f49300489395cbdf36dadaccb39fc1aa
going to download 342754 bytes
going to install 25 file(s) (1 package(s))
downloading http://mirrors.rit.edu/CTAN/systems/win32/miktex/tm/packages/latexmk.tar.lzma...
342754 bytes, 24711.75 KB/Sec
extracting files from latexmk.tar.lzma...
======================================================================
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Latexmk: applying rule 'xelatex'...
Rule 'xelatex': File changes, etc:
   Non-existent destination files:
      'example_talk.xdv'
------------
Run number 1 of rule 'xelatex'
------------
------------
Running 'xelatex -no-pdf  -recorder  "example_talk.tex"'
------------
This is XeTeX, Version 3.14159265-2.6-0.99999 (MiKTeX 2.9.6600)

Sorry, but xelatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  /home/hd/.miktex/texmfs/data/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  xelatex: (Pdf)LaTeX failed to generate the expected log file 'example_talk.log'
Latexmk: Did not finish processing file 'example_talk.tex':
   (Pdf)LaTeX failed to generate the expected log file 'example_talk.log'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Makefile:10: recipe for target 'example_talk.pdf' failed
make: *** [example_talk.pdf] Error 12
[initexmf.log](https://github.com/MiKTeX/miktex/files/1728722/initexmf.log)
[xelatex.log](https://github.com/MiKTeX/miktex/files/1728723/xelatex.log)
