### ISSUE TITLE
Option for MiKTeX to avoid overwriting file associations

### ISSUE THREAD

**Issue by darrylyong** [MiKTeX/miktex#671]
I have read this thread https://github.com/MiKTeX/miktex/issues/582 about why TeXworks is a core part of MiKTeX and am at peace with that decision. However, it would be really helpful to not force people who don't want to use TeXworks to do so. I have my own IDE set up and don't want to use TeXworks. During (some/all?) updates, MiKTeX will rewrite my Windows file associations so that .tex files (and others) automatically launch TeXworks again. That forces me to have to reset those file associations or to just skip updating MiKTeX.

At the least, if TeXWorks needs to be installed, please give users the option of retaining control over file associations during the install process and during updates. This seems to me pretty standard procedure to ask the user about creating file associations rather than just creating them without any user agency. 

BTW, this decision to reset file associations on updates seems to be a more recent change as I don't recall in the past having to reset my file associations so frequently, only once after the initial install.

Thanks for considering the request!

**Comment by edocevoli** [comment]
The installer will not override any file associations. That is, it will add TeXworks to a handle `.tex` files. But any existing associations will not be affected. That's the theory. I will check it tomorrow.

**Comment by darrylyong** [comment]
I'd appreciate you checking. That is not my experience. I have to regularly change my file associations to get them to work the way I want.

**Comment by edocevoli** [comment]
I was not able to reproduce your issue. What I did:

1. associate `.tex` with Visual Studio Code:
<img width="377" alt="Capture1" src="https://user-images.githubusercontent.com/20090840/101764096-f2c44880-3adf-11eb-96de-d1354a5cae16.PNG">
2. update MiKTeX
3. click on a `.tex` file => opens Visual Studio Code

**Comment by darrylyong** [comment]
I swear I am not making this up.

It could be that perhaps not every update triggers the file (re-)association, but only when texworks itself is updated.  Since I've recently updated MiKTeX and the texworks is up-to-date, I can't test this out myself.  I can confirm, however, that uninstalling and installing the texworks package using the console causes the file re-association.

I will also note that there are lots of different ways of establishing file associations in Windows explorer. I need to establish my .tex file associations via a different mechanism (using the registry) than the one edocevli showed, since I need to add command line options to the program invoked.

**Comment by edocevoli** [comment]
How do you modify the file association?
Can you dump the relevant registry settings before and after the update?

**Comment by darrylyong** [comment]
I will try to do that. At the moment, MiKTeX is up to date, so I will need to wait until I notice a change of file associations and make a note of what might have caused it.

Also, I need to retract what I said earlier about uninstalling and reinstalling the texworks package--I can't get that to cause a file re-association.  I'm not sure what I did earlier that caused the re-association of .tex files to texworks.

**Comment by darrylyong** [comment]
After a few years of not observing this behavior, I just started seeing it again.  To be specific, the behavior is that updating MiKTeX causes file associations to switch to TeXWorks instead of remaining as I currently have them set to.

I now have evidence of it happening. I used Process Monitor to look for registry changes during the update process and found that it was indeed changing my registry so as to reassociate files with TeXWorks.

![capture](https://user-images.githubusercontent.com/5227867/197041463-afc2bd80-ba6b-41c4-974f-01525991935d.png)
[registrychanges.CSV](https://github.com/MiKTeX/miktex/files/9833398/registrychanges.CSV)

As mentioned above, this behavior causes me to have to reset those file associations whenever I update MiKTeX. Please don't change these file associations during updates, or at least give users an option to preserve file associations.
