### ISSUE TITLE
The package corresponding to ConTEXt does not appear in the package list.

### ISSUE THREAD

**Issue by Atreyu-94** [MiKTeX/miktex#674]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)
Is it a problem that you do not support ConTEXt? Maybe compatibility issues or I'm not looking for the package name right. Some help?

**Comment by edocevoli** [comment]
ConTeXt is not supported by MiKTeX.

A few years ago, I tried to incorporate it into the MiKTeX distribution. But there were too many pitfalls (e.g. Ruby) and TeX Live dependencies (e.g., `texmf.cnf`). So I gave up.

**Comment by Atreyu-94** [comment]
Thank you very much for your prompt response! In the latest specifications there is no dependency on Ruby anymore, I don't know specifically about TexLive
