### ISSUE TITLE
What differences from TeX Live?

### ISSUE THREAD

**Issue by blakemcbride** [MiKTeX/miktex#675]
Greetings,

I would think this would be on your FAQ but it's not.  What is the difference between MiKTeX and TeX Live (mainly from a Linux user's perspective)?

Thank you.

Blake McBride

**Comment by edocevoli** [comment]
Thank you for your question. Unfortunately, I do not know TeX Live very well, i.e., I have no idea how to answer this question accurately.

**Comment by blakemcbride** [comment]
I believe TeX was written in some form of Pascal.  It is typically converted to C.  Do you have your own Pascal->C or do you use the same one as TeX Live?

**Comment by edocevoli** [comment]
MiKTeX uses its own Pascal-to-C++ converter.

**Comment by blakemcbride** [comment]
Thanks!  (BTW, I am a MiKTeX versions 1.1, 1.1A, 2.0, 3.0, 3.1 licensee.  Thanks for a really great system!)
