### ISSUE TITLE
MiKTeX freshly installed: gives major issue error and does not work

### ISSUE THREAD

**Issue by lgmventura** [MiKTeX/miktex#677]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Freshly installed MiKTeX on Linux Ubuntu 20.04 with `sudo apt install miktex`.

Using it gives the following error:
```
latex: major issue: So far, no MiKTeX administrator has checked for updates.
```

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
