### ISSUE TITLE
MiKTeX console single mode?

### ISSUE THREAD

**Issue by jibnew** [MiKTeX/miktex#682]
I have MiKTeX all for myself on my laptop, and don't need at all the administrator/user dichotomy in the MiKTeX console.
In fact several times I became confused by offered choice, receiving messages that the two are out of sync, so had to spend time researching what to do, update the two branches separately, etc.
The only thing I need is a local texmf tree for my stuff, and it can be anywhere - in my user directory or anywhere else, I don't care, just tell me where to put it.
So, is there a way to have MiKTeX console never ask me do I want to use it as an administrator or as a user? I want to use it as an user that has full access to everything, whatever this be called.
Million thanks for MiKTeX, by the way! I surely cannot exist without it.

**Comment by edocevoli** [comment]
Thank you. Please note that this is not a support forum. Unless you have to report a bug, this is the wrong place to look for help.
