### ISSUE TITLE
Can't access https://api2.miktex.org/

### ISSUE THREAD

**Issue by hannibal90** [MiKTeX/miktex#685]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hi, I have tried on several different devices (and I am not behind a proxy) to access https://api2.miktex.org/ but I am unable to connect. I have tried updating from the Console, and also visiting the site directly.

**Comment by edocevoli** [comment]
It works for me.

Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
