### ISSUE TITLE
Provide an easy way to install MikTeX on non-Ubuntu Linux

### ISSUE THREAD

**Issue by skrrgh** [MiKTeX/miktex#69]
Hi! Thank you for your product! I really enjoy MiKTeX on Windows, but I can not install MiKTeX on Linux since I use Manjaro and not Ubuntu. Could you please provide an distro independent package via Snapcraft / Flatpak / AppImage? :)

**Comment by RoyiAvital** [comment]
FlatPak and AppImage would be great.

There is a [FlatPak for TeXStudio](https://github.com/flathub/org.texstudio.TeXstudio).
It comes bundled with TeXLive. It would be great to have a [MiKTeX flavor of it](https://github.com/flathub/org.texstudio.TeXstudio/issues/3#issuecomment-392288855).
