### ISSUE TITLE
Windows API error 5: Access is denied error

### ISSUE THREAD

**Issue by TeX-saravanan** [MiKTeX/miktex#690]
Recently I have added a new font in my local texmf tree, after updating "miktex-console_admin" I got the below error:

![MikTeX-Error](https://user-images.githubusercontent.com/77610411/104890779-0b086c80-5996-11eb-8449-e3a034a2c464.png)

 Any one please suggest what I did as wrong....

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
