### ISSUE TITLE
changes in yap | interaction with WinEdt

### ISSUE THREAD

**Issue by cooch17** [MiKTeX/miktex#692]
Not sure this is a 'bug report' as much as it is an 'information request'.  But...something changed with the latest update to yap that seems to break the ability to spawn yap using WinEdt (I'm bringing this up because the number of MikTeX users who use WinEdt as their editor for .tex formatting is *very* large). 

Basically, clicking the menu buttons to invoke yap as the DVI previewer doesn't work since the latest updates to MikTeX. I normally use WinEdt 8.2, but even 'tests' using newer releases of WinEdt have the same issue. I confirmed that the problem arises from a change in yap, by reverting my MikTeX install to the previous version. Once reverted, worked fine using WinEdt 8.2.

So, its clear that something has changed with yap that 'breaks' the association in WinEdt. yap itself is fine. If I double-click any .dvi file, new yap opens it up just fine. The only thing that no longer works is invoking yap by clicking the menu button in WinEdt.

I sent much this same report to the WinEdt folks, but they're likely to ask what has changed with yap. Beyond the superficiaal observation that latest yap is 'bigger', I'd like to be able to provide some more informed feedback.

**Comment by cooch17** [comment]
Just received the following from the WinEdt developer -- seems to point to a real bug in yap. 

_Yes, I can confirm that Yap with the latest MiKTeX Update doesn't work properly when started from the command line:_

_Yap -1 doc.dvi_

_This does not work unless and instance of Yap with the same document opened is already running. The same for inverse search. This affects WinEdt's ability to launch YAP but it is not WinEdt-specific as the same problem happens from the command prompt._

_Double-clicking on .dvi file works because by default YAP uses DDE to perform the shell open action._

_It would be best to make a MiKTeX problem report and wait for the fix which will have to come from MiKTeX developers. I will not get involved as WinEdt has nothing to do with it and I don't use dvi format for anything._

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
