### ISSUE TITLE
TexWorks does not open

### ISSUE THREAD

**Issue by Theo-de** [MiKTeX/miktex#693]
When trying to start TexWorks as user in Win10, no window opens, but I can see Texworks running as background process in the task manager.
I can open TexWorks, however, with Admin rights and then it works. So my question is: How can I make TexWorks launch again in user mode?
I used TexWorks for about a year in User mode and it worked fine, until I imported some tex-files into another subdirectory and tried to open them there with TexWorks. Although I reinstalled MikTex, I don't succeed to launch TexWorks as regular user.
I hope, you have some hints for me, how to get rid of this problem.

[log-MikTex.zip](https://github.com/MiKTeX/miktex/files/5856733/log-MikTex.zip)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/5856735/miktex-report.txt)
[log-pgmdata.zip](https://github.com/MiKTeX/miktex/files/5856737/log-pgmdata.zip)

**Comment by edocevoli** [comment]
How do you start TeXworks?

**Comment by Theo-de** [comment]
Thank you for the quick response.
Starting TexWorks from the app bar or double-clicking on a tex document in user mode doesn't open Texworks.
Staring TexWorks from the app bar with administrator privilies opens TexWorks.

**Comment by Theo-de** [comment]
I updated the log-files. Using MikTex Console, the report files differ, depending on using the console as admin or as user.
[log-pgmdata.zip](https://github.com/MiKTeX/miktex/files/5858570/log-pgmdata.zip)
[log-MikTex.zip](https://github.com/MiKTeX/miktex/files/5858575/log-MikTex.zip)
[miktex-report-admin.txt](https://github.com/MiKTeX/miktex/files/5858577/miktex-report-admin.txt)
[miktex-report-user.txt](https://github.com/MiKTeX/miktex/files/5858580/miktex-report-user.txt)

**Comment by Theo-de** [comment]
Additional information: In user mode the windows opens after 10 minutes (it usually took 3 seconds before). But when opening my tex file, the programm does not respond - c.f. screen shots.
![TexWorks-Scr-01](https://user-images.githubusercontent.com/77845572/105571360-a9f2e700-5d4f-11eb-996f-95e11d5e8ca1.JPG)
![TexWorks-Scr-02](https://user-images.githubusercontent.com/77845572/105571366-af503180-5d4f-11eb-8845-96a0ac7bd375.JPG)

**Comment by edocevoli** [comment]
This looks like a duplicate of #TeXworks/texworks/issues/904

**Comment by Theo-de** [comment]
Indeed! Thanks for the hint Christian! I will try out the proposals posted under issue #904 and see, what happens.

**Comment by Theo-de** [comment]
Ha - perfect reference, from edocevoli - that's it!! You guys are doing a great job!
Unter issue #904 I tried out stloeffler's advice: "Could someone (who experiences this issue) try with just deleting the **recentFiles** key?"
After having done this, TexWorks starts again quickly  in user mode (3-4 seconds) and can open (and run) tex-files again.
So I'm a happy camper again.

**Comment by Theo-de** [comment]
Attached find the log files from LOCALAPPDATA plus Debug log files for the successful run in user mode (if needed/ of interest)
[Locapp-log-success.zip](https://github.com/MiKTeX/miktex/files/5860123/Locapp-log-success.zip)
[LAPTOP-SQ0Q0JFJ.LOG](https://github.com/MiKTeX/miktex/files/5860124/LAPTOP-SQ0Q0JFJ.LOG)

**Comment by Theo-de** [comment]
Since this issue is resolved, I close this issue. Thanks again to edocevoli!
