### ISSUE TITLE
MikTeX incorrectly displays symbols

### ISSUE THREAD

**Issue by Avifaramalash** [MiKTeX/miktex#694]
Latest version of MikTex
Just started working
Symbols displaying incorrectly
![Issue](https://user-images.githubusercontent.com/77883442/105577743-3ed00180-5d9d-11eb-8448-e0f6bf8e2f04.jpg)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
