### ISSUE TITLE
LuaLatex unable to locate symbols in package 'bbding'

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex#706]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

When using the following example, LuaLatex is unable to find the symbols in 'bbding'. Nothing is printed out.

\documentclass[10pt,letterpaper,final]{article}
\usepackage{amsmath}
\usepackage{bbding}
\usepackage{fontspec}
\usepackage{graphicx}
\usepackage[width=8.50in, height=11.00in, left=0.50in, right=0.50in, top=1.00in, bottom=1.00in]{geometry}
\listfiles
\begin{document}

\Square

\Phone
\end{document}

I am using TexStudio 3.0.4 on a Windows 10 PRO machine. I have included all of the requested files and the log file from TexStudio. I have posted this question on other forums, and the consensus seems to be that it works with TexLive. I am at a loss here as to what my problem is. By the way, if I substitute 'fontawesome' for 'bbding', everything works.

[MiKTeX.zip](https://github.com/MiKTeX/miktex/files/5937202/MiKTeX.zip)
[LuaLatex-log.zip](https://github.com/MiKTeX/miktex/files/5937206/LuaLatex-log.zip)

Gerard

**Comment by edocevoli** [comment]
Thank you, I was able to reproduce it.

**Comment by edocevoli** [comment]
I could resolve the issue by updating the font map files.

**Comment by BeerStud** [comment]
> I could resolve the issue by updating the font map files.

I have tried updating the font map file both as a MiKTeX user and as an Administrator. In both case, while no error message is displayed, the end is still the same. there is no output from the script. I tried adding some dummy information, and that did print out correctly. This is the same error message via the log file from Texstudio while using LuaLatex.

LaTeX Font Info:    Trying to load font information for U+ding on input line 8.

("C:/Program Files/MiKTeX/tex/latex/bbding/uding.fd"
File: Uding.fd 1996/02/01 v1.0 BBding font definitions
)
luaotfload | cache : Lookup cache loaded from C:/Users/gerar/AppData/Local/MiKTe
X/luatex-cache/generic/names/luaotfload-lookup-cache.luc.
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: Font "bbding1
0" not found.
luaotfload | resolve : sequence of 3 lookups yielded nothing appropriate.
luaotfload | resolve : sequence of 3 lookups yielded nothing appropriate. [1

{C:/Users/gerar/AppData/Local/MiKTeX/pdftex/config/pdftex.map}
Missing character: There is no f (U+0066) in font bbding10!
Missing character: There is no  (U+0008) in font bbding10!
] (./texstudio_FpxSZK.aux))

I am thinking of doing a complete uninstall and reinstall of MiKTeX. Do you have a better suggestion? By the way, exactly how are you updating the 'map files'?

-- 
Gerard

**Comment by edocevoli** [comment]
I updated the font map files by running

    initexmf --mkmaps

Then `lualatex` was able to find the Type 1 font:

```
....
<//?/c:/program files/miktex/fonts/opentype/public/lm/lmroman10-regular.otf><C:
/Program Files/MiKTeX/fonts/type1/public/niceframe-type1/bbding10.pfb>
Output written on test.pdf (1 page, 10859 bytes).
Transcript written on test.log.```

This is the PDF output:

<img width="108" alt="Capture" src="https://user-images.githubusercontent.com/20090840/107128476-4ecc0300-68be-11eb-97c9-c9af0795d811.PNG">
