### ISSUE TITLE
MikTex installer download link only shows 403 forbidden nginx!?

### ISSUE THREAD

**Issue by PhotonNikko** [MiKTeX/miktex#709]
This is originally on the discussions but I'm gonna put this here too.
![WWdjfBcFxV](https://user-images.githubusercontent.com/69907559/107144570-98742680-696e-11eb-91c5-6f686bcd41a0.png)

I've been trying to do this for a while. This link https://mirror.yongbok.net/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-21.1-x64.exe only shows 403 Forbidden nginx.

I theninstalled the miktex console with protext and tried too check for updates
GENERAL MIKTEX INFORMATION
Date: 2021-02-07 17:51:07
MiKTeX: 2.9.7380
GitInfo: a0fc650 / 2020-03-26 20:04:43
OS: Windows 10 Pro, 64-bit, build 18363
SharedSetup: no
LinkTargetDirectory: C:\Users\asus\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
LastUpdateDb: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\asus\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\asus\AppData\Local\MiKTeX\2.9
Root2: C:\Users\asus\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\asus\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\asus\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\asus\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
Invokers: non-existing/explorer

The following issues were detected:
1: major issue: So far, you have not checked for MiKTeX updates.

ERROR DETAILS
Program: C:\Users\asus\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\miktex-console.exe
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:485
Error: Error response from server: 403
Details:
responseCode: 403

I also tried to install a package
![sGMo6PaxFB](https://user-images.githubusercontent.com/69907559/107144648-1801f580-696f-11eb-976c-be0983f7754e.png)

why is this happening?? Please solve this issue

**Comment by edocevoli** [comment]
It works for me. Maybe your IP address is blocked by mirror.yongbok.net? Sorry, but this issue cannot be solved by the MiKTeX maintainers. I would recommend that you choose another mirror.
