### ISSUE TITLE
MikTex console already running

### ISSUE THREAD

**Issue by yiqiangjizhang** [MiKTeX/miktex#711]
I am using VS Code with Miktex and I want to update my Miktex distribution or packages. However, I cannot open the Miktex Console since I get the following message:

![image](https://user-images.githubusercontent.com/68460056/107346893-83f67200-6ac5-11eb-99fa-2a9b285523eb.png)

I tried to search Miketx in my Task Manager to end it and open it again but it does not appear. How can I update it or open the console?

**Comment by yiqiangjizhang** [comment]
I tried uninstalling it via Control Panel but I get the same message, and I cannot even uninstall it

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
