### ISSUE TITLE
Restore/add mirrors.tuna.tsinghua.edu.cn and opentuna.cn in package repositories

### ISSUE THREAD

**Issue by Harry-Chen** [MiKTeX/miktex#712]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I am from @tuna, and we maintain some open sources mirror sites in China including:

* https://mirrors.tuna.tsinghua.edu.cn/
* https://mirrors.bfsu.edu.cn/
* https://opentuna.cn/

All of these sites mirror `CTAN` and thus is a MikTeX package repository. Previously (maybe several years ago?) mirrors.tuna.tsinghua.edu.cn was listed on <https://miktex.org/repositories>. But currently out of the three mirrors we maintained, only BFSU is listed.

It will be good to restore (or add) our mirrors in the list, so that Chinese users can have better experience when using MikTeX.

**Comment by edocevoli** [comment]
> https://mirrors.tuna.tsinghua.edu.cn/

is outdated (one day delay) and thus is avoided

> https://mirrors.bfsu.edu.cn/

is good

> https://opentuna.cn/

is unknown; you should contact CTAN maintainers so that they add it to `CTAN.sites`

**Comment by Harry-Chen** [comment]
Hi @edocevoli, thanks for your reply!

> https://mirrors.tuna.tsinghua.edu.cn/ is outdated (one day delay) and thus is avoided.

We have observed mirrors.tuna.tsinghua.edu.cn on [https://ctan.org/mirrors/mirmon] for several days and have not noticed any delay longer than 12 hours. Also, we synchronize every 12 hours from CTAN and almost succeeds each time. Could you explain why it is considered outdated and how is the delay calculated?

**Comment by edocevoli** [comment]
The delay is calculated by comparing the version numbers (see file: `pr.ini`). The check is done around 7 a.m. (CET).
