### ISSUE TITLE
pstricks example not showing figure in pdf output..

### ISSUE THREAD

**Issue by janpop2017** [MiKTeX/miktex#717]
- [ x ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report) in zip-file.
Is this a MikTex Ghostscript issue ?
Remark: I have a laptop with MikTex from 2019 that produce the correct pdf-output.
See attached tex-source and pdf-output.
[tmp.zip](https://github.com/MiKTeX/miktex/files/5977562/tmp.zip)
regards Jan

**Comment by edocevoli** [comment]
Thank you for the report. I was not able to reproduce the issue. Running `xelatex` on your document produces this PDF:
[PStricks-Graphs.pdf](https://github.com/MiKTeX/miktex/files/5977598/PStricks-Graphs.pdf)
