### ISSUE TITLE
defect pdf output without error in case of parallel compling same tex file.

### ISSUE THREAD

**Issue by geraldholzinger** [MiKTeX/miktex#72]
how to reproduce the bug:
1. create two ident .bat-files:
   miktex-lualatex --output-directory "$path" "$Filename.tex"
2. start the first bat file, start the second bat file while first file is runnig

result:
the pdf is defect while the log produces no error message.

what did I expect:
* bat2 sould wait, untill bat1 is ready then run bat2 (would by nice in case of page numbers i.e. page 1 of 4 pages)

or
* bat1 sould be stopped by bat2, then compile bat2

or
* error in bat2 (has to wait for free $Filename.log)

(windows 7 MikTec 2.9.65 64bit)

**Comment by edocevoli** [comment]
Most likely this is not a MiKTeX-specific problem, i.e., it should be possible to reproduce the defect with other TeX implementations.

I would recommend that you report the issue to the developers of the software component.
