### ISSUE TITLE
I can't update Miktex, it shows: The remote package repository is outdated

### ISSUE THREAD

**Issue by asmwarrior** [MiKTeX/miktex#720]
I download the latest Miktex, and after install, when try to update, I got the message:

~~~~
The remote package repository is outdated. You have to choose another repository.
~~~~

I tried several repositories, and all get the same error message.

I guess it is the same or similar issue as #49 ?

**Comment by edocevoli** [comment]
Yes, the mirrors are behind the master repository. This is usually self-healing, i.e., it should be okay tomorrow.

**Comment by jchen42703** [comment]
I got the same issue when I tried to run `pdfLatex -v` and looked at the `pdflatex.log` file after a fresh install of MikTex for the user on Windows 8.

**Comment by asmwarrior** [comment]
I think when Miktex pops up the Error Message box, it should tell people that it's the synchronization error or some similar things, and ask them to wait for one day or two. Otherwise people will get confused, maybe they thought Miktex is broken, and just uninstall it.
