### ISSUE TITLE
kpsewhich reports 'major issue: So far, no MiKTeX administrator has checked for updates.

### ISSUE THREAD

**Issue by Traap** [MiKTeX/miktex#723]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I have installed MiKTeX 21.1 into Ubuntu 20.04 running on Windows Subsystem for Linux 2 (WSL2).  This installation does not allow for Xwindows (that is another story).

I have attached the following:

1. check-latex.txt (really .tex) is the actual LaTeX code.   Self-contained.  95 lines.
2. check-latex.pdf to show the actual generated document.  1 page.   3 sections, namely: Greeting, Commands & Environment, and Installation Steps & Side-effects
3. miktex-report.tex

[check-article.txt](https://github.com/MiKTeX/miktex/files/6031894/check-article.txt)
[check-article.pdf](https://github.com/MiKTeX/miktex/files/6031896/check-article.pdf)
[miktex-reprot.txt](https://github.com/MiKTeX/miktex/files/6031897/miktex-reprot.txt)

It is clear from *miktex-report.txt* updates and checks have not been done.  How is this resolved with a miktex-console?

I am able to rebuild my entire environment within 30 minutes.  Any suggestions are welcomed.  I will report my finding.

**Comment by edocevoli** [comment]
>  So far, no MiKTeX administrator has checked for updates

I would suggest that you follow the recommendation: check for updates.
