### ISSUE TITLE
kpsewhich reports 'major issue: So far, no MiKTeX administrator has checked for updates

### ISSUE THREAD

**Issue by Traap** [MiKTeX/miktex#724]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I have posted this issue again because 723 has been closed without any opportunity for discussion.

> So far, no MiKTeX administrator has checked for updates
>I would suggest that you follow the recommendation: check for updates.

The above statement does little to help me.  *As stated in the documents  and examples provided, miktex-console is not available when using Ubuntu on Windows Subsystem for Windows (WSL2).*   I only have access to a *terminal shell*.

This next question was a typo.  It is corrected.  *How is this resolved without a miktex-console?*

The following do not solve the problem:

sudo mpm --admin --update
mpm udpate

I notice Libraries/MiTeX/Setup/SetupService.cpp checks:
```
      else if (!IsValidTimeT(commonInstallation.lastUpdateCheck))
      {
        result.push_back({
          IssueType::AdminUpdateCheckOverdue,
          IssueSeverity::Major,
          T_("So far, no MiKTeX administrator has checked for updates."),
          T_("Switch to MiKTeX administrator mode and check for updates.")
        });
      }

        if (!IsValidTimeT(userInstallation.lastUpdateCheck))
        {
          result.push_back({
            IssueType::UserUpdateCheckOverdue,
            IssueSeverity::Major,
            T_("So far, you have not checked for updates as a MiKTeX user."),
            T_("Stay in MiKTeX user mode and check for updates.")
          });
        }
```

I ask again.  How do you make the necessary check *without* the miktex console?

To be very clear.  I do not have any issues using MiKTeX on a Windoz computer.  The challenge is using WSL2, micro kernel, Ubuntu 20.04 without a console, and MiKTeX.

**Comment by Traap** [comment]
Should this topic be moved to the 'Discussions' tab?

**Comment by edocevoli** [comment]
Thank you for the info. You have to run `mpm` multiple to times. For example

```sh
sudo mpm --admin --update
mpm --update
sudo mpm --admin --update
mpm --update
```

This should fix it.

**Comment by Magnus-Lauritsen** [comment]
sudo mpm --admin
mpm

and click "check for updates"

will do it.
--update has been deprecated

**Comment by koppor** [comment]
Note that `--update` is replaced by `mitkex packages update` (which is also a CLI)

```
miktex packages update-package-database
miktex packages update
```

See https://docs.miktex.org/manual/miktex-packages.html for more command line hints.
