### ISSUE TITLE
Missing scalefnt.sty does not trigger installing carlisle

### ISSUE THREAD

**Issue by koppor** [MiKTeX/miktex#726]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

```
! LaTeX Error: File `scalefnt.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
```

Package documentation: https://ctan.org/pkg/scalefnt?lang=de --> It should be in `carlisle` package.

Thus, I ask for some auto installation tweak.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
