### ISSUE TITLE
Missing binhex.tex should trigger installation of binhex

### ISSUE THREAD

**Issue by koppor** [MiKTeX/miktex#727]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

```
! LaTeX Error: File `binhex.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)

Enter file name:
```

The auto installer is active and works for .sty files. However, for `bintex.tex` it does not work.

(Package: https://www.ctan.org/pkg/binhex)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
