### ISSUE TITLE
Missing listingsutf8.sty should trigger installation of listingsutf8

### ISSUE THREAD

**Issue by koppor** [MiKTeX/miktex#728]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

```
! LaTeX Error: File `listingsutf8.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
```

Other auto installations work fine.

Note: I am "just" trying to compile https://github.com/latextemplates/scientific-thesis-template  --> `main-german.tex?` from a fresh MiKTeX installation.

Similar request for `fvextra.sty` --> fvextra, `newfloat.sty` --> newfloat

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
