### ISSUE TITLE
texify --clean has trouble with .aux files using luatex engine

### ISSUE THREAD

**Issue by scmartin** [MiKTeX/miktex#732]
[x] I have read and acknowledged this HOWTO article:  
I have a project which is divided into chapters. To mimic the problem I have a MWE structured as follows:
- _MainDir_
  -  _main.tex_
  -  _Chapter1_
      - _ch1.tex_

I use _\include{Chapter1/ch1.tex}_ in _main.tex_ to pull in chapter 1. Compiling with
`texify.exe --pdf --engine=luatex --synctex=1 --clean thesis-ku.tex`
gives me the response
>  ! I can't write on file `Chapter1/Introduction.aux'.
> \\@include ...mmediate \openout \\@partaux "#1.aux"
>                                                   \immediate \write \\@partau...
> 
> l.17 \include{Chapter1/Introduction}
> 
> Please type another output file name:
while `texify.exe --pdf --engine=xetex --synctex=1 --clean thesis-ku.tex` works fine as does using pdftex. I tried different combinations of options, and it only occurs when using the `--clean` option.

As a further test, if I compile directly with miktex-luahbtex, it runs fine.

I don't know what the cleanup process is, but for some reason it is not playing nice with the LuaTeX engine.

Here is my MikTeX report.
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6091848/miktex-report.txt)

**Comment by edocevoli** [comment]
This has been fixed.
