### ISSUE TITLE
Could not start build and view: pdflatex:

### ISSUE THREAD

**Issue by ShorSagaR** [MiKTeX/miktex#739]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Sorry, but pdflatex.exe did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\Sai\AppData\Local\MiKTeX\miktex\log\pdflatex.log
Process exited with error(s)

**Comment by edocevoli** [comment]
> - [x] I have read and acknowledged this HOWTO article:  
>  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

No, you haven't.
