### ISSUE TITLE
texdoc and mthelp command not found 

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#74]
I install the miktex .dmg on macos , and it is very excellent app , and my terminal shell is zsh  and 
when I check the documentation using texdoc or mthelp command:
`zsh: command not found: mthelp`
How to add it to my path?

and my miktex path is/usr/local/bin as system-wide

**Comment by edocevoli** [comment]
This has been fixed with MiKTeX 2.9.6650.
