### ISSUE TITLE
Asymptote fails to startup

### ISSUE THREAD

**Issue by tstrohm** [MiKTeX/miktex#740]
### 1. Producing the error

The issue occurs in the following way (Windows 10, MiKTeX 2.9, just updated): I take a simple asy file test.asy:

> draw(box((0,0),(1cm,1cm)));

Then I compile it, voilà:

> foo>"C:\Program Files\MikTeX 2.9\miktex\bin\x64\asy" -noV test.asy
>   real clock=a[4];
>   ^
> C:\Program Files\MikTeX 2.9/asymptote/plain.asy: 263.3: reading array of length 4 with out-of-bounds index 4

### 2. Reason for the error

In line 261 of plain.asy, it says

>  real [] a=_cputime();
  
The function _cputime() seems to return too less parameters. If I check, it indeed returns an array of length 4 (instead of 5). If I change line 263 in plain.asy to

>  real clock=0;
  
everything works fine.

So the problem should be a wrong definition of _cputime() in asy.exe.

### 3. Attachments

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6120985/miktex-report.txt)

- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
This has been fixed.
