### ISSUE TITLE
DviDraw error in Windows-10

### ISSUE THREAD

**Issue by anctop** [MiKTeX/miktex#745]
I am writing to report a MiKTeX error happened in Windows-10 platform since last week.
The error exists in MiKTeX versions 20.11 & 21.2.

Here are the steps to produce the error :
1. compile a .tex file with "latex" to produce the .dvi file;
2. open the .dvi file with "yap";
3. click "File -> Print" to print the .dvi file;
4. an error box appears with title "MiKTeX Problem Report" and message "MiKTeX encountered an internal error";
5. the "Copy Info" button contains the following lines
>MiKTeX Problem Report
>Message: MiKTeX encountered an internal error.
>Data:
>Source: Programs\MiKTeX\Yap\MFC\DviDraw.cpp
>Line: 349
>MiKTeX: 20.11
>OS: Windows 10 Enterprise, 64-bit, build 19042
>Invokers: non-existing/explorer/cmd
>SystemAdmin: no
>Root0: C:\Users\test\AppData\Roaming\MiKTeX
>Root1: C:\Users\test\AppData\Local\MiKTeX
>Root2: C:\Software\TeX
>Root3: C:\ProgramData\MiKTeX
>Root4: C:\Program Files\MiKTeX
>UserInstall: C:\Software\TeX
>UserConfig: C:\Users\test\AppData\Roaming\MiKTeX
>UserData: C:\Users\test\AppData\Local\MiKTeX
>CommonInstall: C:\Program Files\MiKTeX
>CommonConfig: C:\ProgramData\MiKTeX
>CommonData: C:\ProgramData\MiKTeX
6. the "dvipdfm" command fails to produce the corresponding .pdf file;
7. the "dvipdfmx" command can produce the correct .pdf file.

Reports of the error were first received last week.

**Comment by edocevoli** [comment]
I cannot reproduce the issue with the given info.

Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
