### ISSUE TITLE
Can't install properly/update MiKTeX 21.2 on Windows 10

### ISSUE THREAD

**Issue by lfmvit** [MiKTeX/miktex#748]
Installer :  basic-miktex-21.2-x64.exe on Windows 10 Home x64 (Build 19042.867(

What I Did/Tried/Know

-Reinstalled with all the possible combinations of options available ,running the set up as admin
-I did not renamed the setup file, except when I tried to intall the portable version, sames problems occured
-Selected a installation folder without spaces or weird characters
-My user name it's just "User"
-Turned off antivirus and closed others Tex related processes during the installation
-Lost 5 hours of my life searching the net for a solution, similar issues seems to be existing for quite a while without a precise remedy

I found this in a thread: "try to run this command ......"
this my output:

- C:\Users\Utente>miktex-fc-cache --miktex-admin --miktex-disable-maintenance --miktex-disable-diagnose --verbose
log4cxx: setFile(C:\ProgramData\MiKTeX\miktex\log/miktex-fc-cache_admin.log,true) call failed.
log4cxx: IO Exception : status code = 720005
Fontconfig error: Cannot load default config file
miktex-fc-cache: Can't initialize font config library

following  a quick list of the issues related rows during the last setup (same as the other setups) :

1)  C:\ProgramData\MiKTeX\miktex\log\initexmf_admin.log
Warning: The executed process did not succeed.
Setting config value: [MPM]AutoInstall=2

2) 48 [0x00005268] INFO initexmf null - this is MiKTeX Configuration Utility 4.3 (MiKTeX 21.2) 50 [0x00005268] INFO initexmf null - this process (7204) started by 'basic-miktex-21.2-x64' with command line: initexmf --principal=setup --common-install=C:\diocane --set-config-value=[Core]SharedSetup=1 --admin --log-file=C:\pleasego\miktex/config\uninst.log --disable-installer --verbose 50 [0x00005268] INFO trace.initexmf.core null - turning on administrator mode 50 [0x00005268] INFO initexmf null - Operating on the shared (system-wide) MiKTeX setup 52 [0x00005268] INFO initexmf null - Registering root directories... Registering root directories...
54 [0x00005268] INFO trace.initexmf.core null - saving startup configuration; setupVersion=21.2 64 [0x00005268] INFO initexmf null - Setting config value: [Core]SharedSetup=1 Setting config value: [Core]SharedSetup=1
66 [0x00005268] INFO initexmf null - this process (7204) finishes with exit code 0 Operating on the shared (system-wide) MiKTeX setup
configuring fontconfig\config\fonts.conf

 3) Collecting linked executables in target directory C:\pleasego\miktex/bin/x64...
initexmf: warning: The lualatex executable could not be found.
Creating language.dat, language.dat.lua and language.def...

Sorry, but "MiKTeX Configuration Utility" did not succeed.

4)( During the update) fileName="C:\pleasego\miktex\bin\x64\miktex-fc-cache.exe", exitCode="1"

Here it is the report:
ReportDate: 2021-03-16 02:36:46
CurrentVersion: 21.2
SetupDate: 2021-03-16 02:23:00
SetupVersion: 21.2
Configuration: Regular
GitInfo: 7a7e645 / 2021-02-20 10:38:14
OS: Windows 10 Home, 64-bit, build 19042
SharedSetup: yes
LinkTargetDirectory: C:\diocane\miktex\bin\x64
PathOkay: no
LastUpdateCheckAdmin: 2021-03-16 02:23:53
LastUpdateAdmin: 2021-03-16 02:34:49
LastUpdateDbAdmin: 2021-03-16 02:23:51
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX
Root1: C:\pleasego
CommonInstall: C:\pleasego
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX

I hope I attached a sufficient amount of infos in order to identify the problem. Thanks in Advance

lfmvit

[initexmf_admin.log](https://github.com/MiKTeX/miktex/files/6145474/initexmf_admin.log)
[miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/6145475/miktex-console_admin.log)
[miktex-fc-cache_admin.log](https://github.com/MiKTeX/miktex/files/6145476/miktex-fc-cache_admin.log)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6145477/miktex-report.txt)
[mkfntmap_admin.log](https://github.com/MiKTeX/miktex/files/6145478/mkfntmap_admin.log)
[mpmcli_admin.log](https://github.com/MiKTeX/miktex/files/6145479/mpmcli_admin.log)

**Comment by edocevoli** [comment]
Thank you. At the moment I cannot reproduce the issue. It seems that your Windows system is not compatible with MiKTeX.
