### ISSUE TITLE
No log file in Texmaker after Miktex last update (2.9.6615 version)

### ISSUE THREAD

**Issue by anaruizar** [MiKTeX/miktex#75]
After the Miktex's last update (2.9.6615 version), when compiling my .tex file in Texmaker I don't get the PDF file. It drops a windows saying that the program doesn't find the log file. I have tried to uninstall both miktex and texmaker and then install them again (firstly miktex and then texmaker).

Before the last update of Miktex I hadn't had any problem and now I have it. That's why I guess it's because of the new version. I can't find the solution, hope there's somebody that could help me.

I have linux, by the way.

Thank you in advance!

**Comment by edocevoli** [comment]
You should provide more info. At the moment I don't understand the problem description.
