### ISSUE TITLE
yap: cannot print

### ISSUE THREAD

**Issue by anctop** [MiKTeX/miktex#751]
I am writing to report a MiKTeX error happened in Windows-10 platform.

The error is reproducible in MiKTeX versions 21.3 & 20.11 (see attachments).

[21-3.zip](https://github.com/MiKTeX/miktex/files/6154260/21-3.zip)
[20-11.zip](https://github.com/MiKTeX/miktex/files/6154261/20-11.zip)

Each of the attached .zip files contains:
the installation report "miktex-report.txt",
files in the directory "%LOCALAPPDATA%\MiKTeX\miktex\log",
a number of screen captures.

Here are the steps to produce the error :

1. compile a .tex file with "latex" to produce the .dvi file (see images 01.png in attachments);
2. open the .dvi file with "yap";
    click "File -> Print" to print the .dvi file (see images 02.png in attachments);
    for MiKTeX 20.11, the "Copy Info" button contains debugging information (see file 02.txt in the attachment);
3. the "dvipdfm" command fails to produce the corresponding .pdf file (see images 03.png in attachments);
4. the "dvipdfmx" command can produce the correct .pdf file (see images 04.png in attachments).

The same results are observed on different computers (all running Windows-10).

**Comment by Schlurchi** [comment]
I can confirm the above error. It didn't show up to March 9 but occurred from March 12 onwards. There is a coincidence with an automatic Microsoft update to my system (Windows 10 Home version 2004). I'm using MiKTeX 2.9 installed October 2020, not changed or updated since.

**Comment by edocevoli** [comment]
Please remember: one bug per issue. I have created a new ticket for the dvipdfm failure: #752
