### ISSUE TITLE
xelatex and xelatex-dev formats can not be created

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#753]
After todays update neither the xelatex nor xelatex-dev format can be created. The log ends with a capacity exceeded message when reading hypenation patterns:

~~~~
(C:\Users\Nililand2020\AppData\Local\Programs\MiKTeX 2.9\tex/generic/hyph-utf8/
loadhyph\loadhyph-en-gb.tex ASCII Hyphenation patterns for British English
(C:\Users\Nililand2020\AppData\Local\Programs\MiKTeX 2.9\tex/generic/hyph-utf8/
patterns/tex\hyph-en-gb.tex
! TeX capacity exceeded, sorry [pattern memory=700000].
l.8295 v3ure
~~~~

pdflatex works fine.

**Comment by edocevoli** [comment]
TeX Live has increased trie_size from 700000 to 1000000. Seems that MiKTeX has to follow.

**Comment by KeesZeelenberg** [comment]
For now, it seems that compiling the format with less languages, e.g. 4, succeeds.

**Comment by edocevoli** [comment]
I have increased the capacity. It should work now.

**Comment by u-fischer** [comment]
It works for me.
