### ISSUE TITLE
search path of automatic format creation

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#754]
miktex quite often triggers a format creation when a document is compiled. The search path then includes the current directory. 
Depending on the files in the directory this can have many side effects on the format. One example (that is a real world example sent to me):

Create a file `hyphen.tex` with the content

~~~~
\RequirePackage{expl3}
\documentclass[12pt]{scrartcl}
\begin{document}
some hyphenation tests  ...
\end{document}
~~~~

Delete the existing format (I used here xelatex as it is currently broken). Then the format creation will fail and the log will show that the hyphen.tex has been included and the format creation fails very badly (and only with the rather vage error that something did go wrong):

~~~~
# UnicodeData-13.0.0.txt
# Modified 2020-03-12 11:00:00 GMT [JAW]
)
===========================================
Local configuration file hyphen.cfg used
===========================================

(C:\Users\Nililand2020\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\hyph
en.cfg
File: hyphen.cfg 2021/03/03 3.55 Babel hyphens

(C:\Users\Nililand2020\AppData\Local\Programs\MiKTeX 2.9\tex/generic/babel\xeba
bel.def)
\l@english=\language0
 (C:\Users\Nililand2020\Documents\Tests\hyphen.tex
(C:\Users\Nililand2020\AppData\Local\Programs\MiKTeX 2.9\tex/latex/l3kernel\exp
l3.sty
~~~~

Imho it would be safer if the current directory would be excluded from the search path during the format creation.

**Comment by edocevoli** [comment]
Thank you, this has been fixed with v21.6.
