### ISSUE TITLE
ctex package installaton error

### ISSUE THREAD

**Issue by kiravi** [MiKTeX/miktex#755]
GENERAL MIKTEX INFORMATION
ReportDate: 2021-03-19 21:14:01
CurrentVersion: 21.3
SetupDate: 2020-11-25 16:24:00
SetupVersion: 20.11
Configuration: Regular
GitInfo: ab8ebca / 2021-03-19 10:22:46
OS: Windows 10 Home, 64-bit, build 19042
SharedSetup: yes
LinkTargetDirectory: C:\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2021-03-19 21:11:17
LastUpdateAdmin: 2021-03-19 21:08:21
LastUpdateDbAdmin: 2021-03-19 21:11:16
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX
Root1: C:\MiKTeX
CommonInstall: C:\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
Invokers: non-existing/explorer

ERROR DETAILS
Program: C:\MiKTeX\miktex\bin\x64\miktex-console_admin.exe
Source: Libraries\MiKTeX\Core\File\win\winFile.cpp:567
Error: Permission denied: path="C:\MiKTeX\tex/generic/ctex/zhmap", modeString="wb"
Details: 
  path: C:\MiKTeX\tex/generic/ctex/zhmap
  modeString: wb

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
