### ISSUE TITLE
MiKTeX 21.2: "MiKTeX Console is already running"

### ISSUE THREAD

**Issue by binyangiss** [MiKTeX/miktex#757]
I have just installed MiKTeX 21.2 on a Windows 10 computer. As I started for the first time MiKTeX Console, I got the message "MiKTeX Console is already running". So I could not start the Console.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
