### ISSUE TITLE
cannot calling tex engine in linux mint 18.3

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#76]
I use linux mint 18.3 to test  the new update miktex app , and when i input tex command in terminal or in texstudio ,there outputs:

```
log4cxx: setFile(/home/lotus/.miktex/texmfs/data/miktex/log/tex.log,true) call failed.
log4cxx: IO Exception : status code = 13
log4cxx: No output stream or file set for the appender named [RollingLogFile].

Sorry, but tex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  /home/lotus/.miktex/texmfs/data/miktex/log/tex.log

```
[initexmf.log](https://github.com/MiKTeX/miktex/files/1747990/initexmf.log)

it seems its not calling the tex or xelatex engine. and I  use the MiKTeX console as private user , the 

windows cannot close , even I  force close,.strangely, as a system-wide, the MiKTeX console(admin) can quit normally
![window](https://user-images.githubusercontent.com/13781719/36540961-491278e0-1817-11e8-98ad-ed02a6715a4d.png)

**Comment by edocevoli** [comment]
You should finish the setup (either in MiKteX Console or on the command-line) before you call a TeX engine. Your current setup seems to be in the bad state. I would recommend that you follow these steps to reset the setup:

```
sudo initexmf --admin --remove-links
sudo initexmf --remove-links
sudo rm -fr ~/.miktex
sudo rm -fr /var/lib/miktex-texmf
sudo rm -fr /var/cache/miktex-texmf
sudo rm -fr /usr/local/share/miktex-texmf
```

It then should be possible to run

```
miktexsetup finish
```

to reconfigure MiKTeX for a private setup.

**Comment by qiuzhu** [comment]
thank you very much ,and it works! I remember that I use the MiKteX Console to finish the setup , and it occurs the window cannot be closed. I seems the command-line works perfectly in linux
