### ISSUE TITLE
Miktex on Kali Linux 2021

### ISSUE THREAD

**Issue by CuriousUser** [MiKTeX/miktex#761]
Greetings, when I try to install Miktex on Kali using the apt command, I get dependency error and here is the list of the dependencies needed:
Depends: libboost-locale1.62.0 but it is not installable
Depends: libcurl3 (>= 7.16.2) but it is not installable
Depends: libhunspell-1.4-0 but it is not installable
Depends: libicu57 (>= 57.1-1~) but it is not installable
Depends: liblog4cxx10v5 but it is not installable
Depends: libmpfr4 (>= 3.1.3) but it is not installable

Now I was told this issue cannot be resolved without making other software unstable, is there a way?
Please help.

Kind regards, and thank you.

-CuriosUser

**Comment by edocevoli** [comment]
Sorry, but this Linux distribution is currently not supported.
