### ISSUE TITLE
MiKTeX Update directly after Installation makes it not usable

### ISSUE THREAD

**Issue by user56986327** [MiKTeX/miktex#771]
Hello,

as the title says, the update that MiKTeX want to do directly after installation makes it unusable.

1. I want to install MiKTeX on my Windows 10 that is in a DOM of my company.
2. Link for installation: https://miktex.org/download
3. The installation is just on the local user.
4. Installation works fine.
5. If I force MiKTeX not to do the Updates, I can compile a standard .tex-Document without problems. But only one package for each compilation process is installed. So I had to start the compiling about 5 times to have the basic-packages.
6. If I do the 102 Updates that MiKTeX recommends directly after installation (or later after trying step 5), I get an error message. The installation seems to run completely through, but nevertheless the error is appearing: 
![Bild01](https://user-images.githubusercontent.com/81571949/112845489-3352cc80-90a5-11eb-95f8-597b54f51a20.png)

7. If I click on yes I get this message: `The executed procress did not succeed.` and `fileName="C:\Users\xxxxxx\AppData\Local\Programs\MiKTeX\miktex\bin\x64\miktex-fc-cache.exe", exitCode="1"`
![Bild02](https://user-images.githubusercontent.com/81571949/112845624-57aea900-90a5-11eb-9694-73d71f2df155.png)

8. The Copy Info gives me the follwing text:
```
GENERAL MIKTEX INFORMATION
ReportDate: 2021-03-29 14:04:13
CurrentVersion: 21.2
SetupDate: 2021-03-29 14:02:00
SetupVersion: 21.2
Configuration: Regular
GitInfo: 7a7e645 / 2021-02-20 10:38:14
OS: Windows 10 Education, 64-bit, build 18363
SharedSetup: no
LinkTargetDirectory: C:\Users\xxxxxx\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: no
LastUpdateCheck: 2021-03-29 14:02:53
LastUpdate: 2021-03-29 14:03:35
LastUpdateDb: 2021-03-29 14:02:51
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: C:\Users\xxxxxx\AppData\Roaming\MiKTeX
Root1: C:\Users\xxxxxx\AppData\Local\MiKTeX
Root2: C:\Users\xxxxxx\AppData\Local\Programs\MiKTeX
Root3: C:\ProgramData\MiKTeX
Root4: C:\Program Files\MiKTeX
UserInstall: C:\Users\xxxxxx\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\xxxxxx\AppData\Roaming\MiKTeX
UserData: C:\Users\xxxxxx\AppData\Local\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
Invokers: non-existing/cmd

ERROR DETAILS
Program: miktex-fc-cache.exe
Error: The executed process did not succeed.
Details: 
  fileName: C:\Users\xxxxxx\AppData\Local\Programs\MiKTeX\miktex\bin\x64\miktex-fc-cache.exe
  exitCode: 1
```

9. After this failed update, MiKTeX will no longer show any updates or so. It just says: "No new Updates availabe".
10. But if I now try to compile any LaTeX-document (e.g. in TeXMaker or TeXworks), I get this error message: `Die` Ausführung des Codes kann nicht fortgesetzt werden, da MiKTeX210200-png.dll nicht gefunden wurde. Durch eine Neuinstallation des Programms kann das Problem möglicherweise behoben werden.` or `The execution of the code cannot continue because MiKTeX210200-png.dll was not found. Reinstalling the program may fix the problem.` _(translated to English)_
![Bild03](https://user-images.githubusercontent.com/81571949/112845814-95133680-90a5-11eb-8b8e-cbdf7a0b3e41.png)

11. I could get a kind of log-file out of this problem with "TeXworks". Is says the following:
```
2021-03-29 15:04:02,156+0200 INFO  texify - this process (18644) started by 'miktex-texworks' with command line: C:\Users\xxxxxx\AppData\Local\Programs\MiKTeX\miktex\bin\x64\texify.exe --pdf --synctex=1 --clean Beispiel.tex
2021-03-29 15:04:02,204+0200 INFO  texify.core - start process: pdflatex --synctex=1 C:/Users/xxxxxx/Downloads\Beispiel.tex
2021-03-29 15:04:02,248+0200 ERROR texify.core - Das System kann die angegebene Datei nicht finden.

2021-03-29 15:04:02,248+0200 ERROR texify.core - Function: CopyFileW
2021-03-29 15:04:02,248+0200 ERROR texify.core - Result: 2
2021-03-29 15:04:02,248+0200 ERROR texify.core - Data: existing="Beispiel.log", path="C:/Users/xxxxxx/Downloads\Beispiel.log"
2021-03-29 15:04:02,248+0200 ERROR texify.core - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp:390
2021-03-29 15:04:02,248+0200 FATAL texify.core - TeX engine failed for some reason.
2021-03-29 15:04:02,248+0200 FATAL texify.core - Data: 
2021-03-29 15:04:02,248+0200 FATAL texify.core - Source: Programs\MiKTeX\texify\mcd.cpp:1529
2021-03-29 15:04:02,248+0200 FATAL texify - TeX engine failed for some reason.
2021-03-29 15:04:02,248+0200 FATAL texify - Info: 
2021-03-29 15:04:02,248+0200 FATAL texify - Source: Programs\MiKTeX\texify\mcd.cpp
2021-03-29 15:04:02,248+0200 FATAL texify - Line: 1529
```

12. I reinstalled the MiKTeX several times. And tired also:
* Installing as local admin
* Installing with the option, that new packages will install without asking

So. Has somebody an idea? After a couple of hours I could not solve the problem, and am now a bit desperate. I also could not find the solution in the www so far. Thank you very much in advance!

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

 - I could not do this command in the Windows command line: `initexmf --report> miktex-report.txt`. I tried the command line in windows (cmd).

 - In the folder `C:\Users\xxxxxx\AppData\Local\MiKTeX\miktex\log` i have many files. Which one is the wanted log-file?
1. initexmf.log
2. miktex-console.log
3.  miktex-fc-cache.log
4.  mkfntmap.log
5.  mkfntmap_2021-03-29-155138.out
6.  mkfntmap_2021-03-29-155317.out
7.  mpmcli.log

**Comment by edocevoli** [comment]
Please create a Zip containing the log files.

**Comment by user56986327** [comment]
Thank you for the (obvious) solution.
Here the logfiles:
[MiKTeX_Logfiles.zip](https://github.com/MiKTeX/miktex/files/6228189/MiKTeX_Logfiles.zip)

**Comment by ShramanJain** [comment]
I am facing the same issue

**Comment by ShramanJain** [comment]
[New Text Document (2).txt](https://github.com/MiKTeX/miktex/files/6299783/New.Text.Document.2.txt)
[log.zip](https://github.com/MiKTeX/miktex/files/6299787/log.zip)

**Comment by edocevoli** [comment]
@user56986327 I was not able to reproduce the problem. It seems that some files cannot be deleted during the update. I would recommend that you disable any virus scanners and try again.
