### ISSUE TITLE
Unable to use MikTeX Setup Service 4.2 (miktex 21.2) -- required updates fail

### ISSUE THREAD

**Issue by virsto** [MiKTeX/miktex#772]
- [yes ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Here is the report requested:

   [miktex-report.txt](https://github.com/MiKTeX/miktex/files/6239184/miktex-report.txt)

Here is a screen clip of the window just before I start the updates:

   ![Capture](https://user-images.githubusercontent.com/1046843/113206228-7bbde600-926f-11eb-95af-ff05c45d6925.PNG)

Everything goes ok until ...

   ![Capture2](https://user-images.githubusercontent.com/1046843/113206572-e8d17b80-926f-11eb-8d8f-eaec2845baa5.PNG)

Note, the task manager shows that MikTeX Console is suspended. I have never managed to get past this update. I am unable to close this window and unable to interrupt the suspension. The only way that I was able to continue was to use task manager to end this task.

And finally here is the last log file after I ended the task (MikTeX Console) when the suspension occurred:

   [miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/6239345/miktex-console_admin.log)

If anymore information is needed I will be glad to try to provide it. Meanwhile, I would like to reinstall MikTeX Console 4.1 if possible. I have some unfinished LaTeX documents that need MikTeX. 

I have been using MikTeX for many years and have never had a problem with it -- an excellent app. One lesson I know, but often forget is "Never update a working app unless it is really necessary!"

**Comment by edocevoli** [comment]
During the update operation, MiKTeX was not allowed to remove/overwrite files. Maybe a virus scanner is in the way. That said: MiKTeX is not compatible with your current Windows setup. I would recommend that try another TeX distribution.

**Comment by virsto** [comment]
Thanks edocevoli,
I executed the update with administration privledges so I suspect your first sentence was not the problem. And I have  used Norton 360 to do a virus scan -- nothing found. On your last sentence, **what TeX distribution do you suggest?** Note, I have not changed anything on my system that could be related to MikTeX between the previous 4.1 and my attempt to upgrade to 4.2 -- this is a fact! **What TeX distribution do you suggest?** Finally, please tell me **how I can reinstall 4.1 (unanswered request in my original comment)?**

**Comment by virsto** [comment]
Thanks for your prompt reply docveoli, 

On your first suggestion -- I did try running the update 4.2 with administrative privledges so IMHO this was not the cause of installation failure. On your second suggestion -- I used Norton 360 to run a virus scan on my entire system and no threats found. On your third remark -- please expand on this incompatibilty -- I did download the latest update for Windows 10 and did read (rather carefully) the tutorial on this -- **what is the incompatibility?**  Also, I would like to reinstall 4.1 since it was working fine -- **how can I reinstall 4.1?** (unanswered request in my original comment). Finally,  please expand on your recommendation for another TeX distribution -- **what distribution(s) should I try? ** Finally, why did you close this issue? Is it common for an issue to be closed before it is resolved?

**Comment by edocevoli** [comment]
I'm afraid that tools like Norton 360 doesn't care if you are an admin. It monitors activity. And if a program does "strange things", it will intervene. You cannot use MiKTeX (because it does "strange things") while Norton 360 is active.

> Is it common for an issue to be closed before it is resolved

It is not a MiKTeX bug. It is an issue with your Windows setup.
