### ISSUE TITLE
doesnt support architecture i386

### ISSUE THREAD

**Issue by rubstudent** [MiKTeX/miktex#775]
Hello together,
this might be a stupid issue/question so please forgive me

I used windows almost all the time and now im trying to switch to linux. I used Miktex with Texworks under windows and was really happy with that setup especially sind missing packages were downloaded automatically if i wanted to. Now im Using Ubuntu 20.04.2 LTS x86_64 and have trouble setting it up the same way.

I added the PGP key, added the source to the sources file and updated apt. Still when i try to install mitex i get the error:

`Skipping acquire of configured file 'universe/binary-i386/Packages' as repository 'http://miktex.org/download/ubuntu focal InRelease' doesn't support architecture 'i386'`

i couldnt find out yet how to fix this issue and it does not seem like it is intentional behaviour. So i think it is something that should be fixed as i assume that this issue is not on my side but on the way the repo works. Id be glad about help and making it easier for others with the same issue to resolve it. 

If it actually is an issue on a certain kind of architectures that cant be fixed id be happy about an information on the installation page.

**Comment by edocevoli** [comment]
MiKTeX hasn't been build of 32-bit Linux. It should not too difficult to build MiKTeX on 32-bit Linux. That said, I would recommend that you get the source code and try to build MiKTeX on 32-bit Linux. Please understand that we cannot provide more help.
