### ISSUE TITLE
MiKTeX 21.3 fails to display anki flashcards

### ISSUE THREAD

**Issue by nhyro** [MiKTeX/miktex#776]
- [yes ] I have read and acknowledged this HOWTO article:  

Each time I use Anki and try to use MiKTeX, I recieve this message :

> This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.3)
entering extended mode
(tmp.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2020-09-24>
Sorry, but latex did not succeed.
The log file hopefully contains the information to get MiKTeX going again: C:\Users\vincent\AppData\Local\MiKTeX\miktex\log\latex.log

I updated MiKTeX at the user level and at the admin level. I upadated Win10. However MiKTeX still fails to display what I wrote. 
Here are the files that may help you to understand my setup  : 

[log.zip](https://github.com/MiKTeX/miktex/files/6252291/log.zip)
[latex.log](https://github.com/MiKTeX/miktex/files/6252298/latex.log)

Do you have any idea how I can bypass this problem ?
Thank you

I'm a newbie to GitHub, feel free to correct how I submitted my issue.

**Comment by edocevoli** [comment]
It works for me:

```
pdflatex tmp.tex
```

The resulting PDF file looks okay.

**Comment by edocevoli** [comment]
Please note that we usually close issues which cannot be reproduced. If you cannot fix your setup: make sure you can provide necessary reproduction steps.
