### ISSUE TITLE
MiKTeX TeXworks PATH management and arara

### ISSUE THREAD

**Issue by gnw3** [MiKTeX/miktex#777]
] [X ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Adding `arara.exe` to the list of "Processing executables" results in a message that java is not found.  Adding  `pwrsh.exe` in Preferences as a "Processing executable" reveals that the `PATH` environment variable has been reduced to just the MiKTeX binaries directory, so including a path for a `java.exe` in the Preferences "Paths for TeX and related programs" has no effect.   A workaround is to use `pwrsh.exe` to run a simple `arara.ps1` script:

```
Write-Output "starting PATH:"
$env:PATH
$env:PATH = "<JRE_PATH>\bin;" + $env:PATH
Write-Output "new PATH:"
$env:PATH
arara.exe $args[0] $args[1] $args[2]
```
TeX Live 2021 (also using TeXworks 0.6.6) does not need the workaround, but I can certainly understand the advantages of trimming the PATH for MiKTeX, but it doesn't make sense to keep the Preferences section: "Paths for TeX and related programs".
Maybe TeXworks should adopt an option to use or ignore the extra paths.   I have not investigated whether `arara.exe` has (or could have) a way to specify the path for `java.exe` other than from the `PATH` environment variable.

**Comment by edocevoli** [comment]
Sorry, I don't understand what you have done and what you want to achieve. If you want to investigate the issue, you have to provide step by step repro instructions.

**Comment by gnw3** [comment]
First, I have documents that use lualatex and and biber (not bibtex) so arara is more useful than texify.

To reproduce the problem:

1. open the sample latex article
2. replace the first line with:
```
% arara: lualatex
% arara: biber
% arara: lualatex
% arara: lualatex
```
3.  add 2 lines to the preamble customizations
```
%%% biblatex  BIBLIOGRAPHY
\usepackage[style=authoryear,backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}
```
4. add section with some citations just before `\end{document}`:
```

\section{Citations}

\LaTeX\ \autocite{companion} supports structural markup for
mathematical documents, and is based on \TeX\
\autocite{knuth:ct:c,knuth:ct:b,knuth:ct:d}. 

\printbibliography
```
Add "Arara" (`arara.exe`) to the list of programs, select Arara and attempt to format the document.
For me this fails with a message indicating that Java was not found (for reasons given above):
```
Sorry, but arara.exe did not succeed for the following reason:

  MiKTeX could not find the script engine 'java.exe' which is required to execute 'arara'.

Remedy:

  Make sure 'java.exe' is installed on your system.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\gwhite\AppData\Local\MiKTeX\miktex\log\arara.log

For more information, visit: https://miktex.org/kb/fix-script-engine-not-found
```
Java.exe is installed:
```
C:\WINDOWS\system32>where java.exe
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
C:\ProgramData\Oracle\Java\javapath\java.exe
```` 
`arara.exe` works in the command shell started from the MiKTeX console:
```

D:\TeX\Testing\arara>arara arara_test.tex
  __ _ _ __ __ _ _ __ __ _
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing "arara_test.tex" (size: 3.0 kB, last modified:
04/03/2021 19:24:52), please wait.

(LuaLaTeX) LuaLaTeX engine .............................. SUCCESS
(Biber) The Biber reference management software ......... SUCCESS
(LuaLaTeX) LuaLaTeX engine .............................. SUCCESS
(LuaLaTeX) LuaLaTeX engine .............................. SUCCESS

Total: 146.40 seconds
```

[arara_test.tex.gz](https://github.com/MiKTeX/miktex/files/6253742/arara_test.tex.gz)

The `java.exe` program is not found because TeXshell provides a path that only contains the MiKtex bin directory. 

My workaround allows me to format the document in TeXworks.  I don't need the workaround with
TeXworks (same version number) in TeX Live.

**Comment by edocevoli** [comment]
It works for me.

What makes you think:

> The java.exe program is not found because TeXshell provides a path that only contains the MiKtex bin directory.

On my system, the path looks like this:

<img width="641" alt="Capture" src="https://user-images.githubusercontent.com/20090840/113503605-3cbfb700-9533-11eb-84f3-6c5f8aef0b2c.PNG">

You see that Java is in the path. Running arara on your test document:

<img width="297" alt="Capture" src="https://user-images.githubusercontent.com/20090840/113503656-96c07c80-9533-11eb-8bab-8aafddbbe4cd.PNG">

**Comment by gnw3** [comment]
On my personal system, the list of paths in the Preferences panel is similar to yours, but only one entry for the MiKTeX bin.   I use a non-admin installation because most of my colleagues use Enterprise systems don't allow users to have admin privileges.  When arara didn't file Java, I added pwsh.exe as a program.  Running that allowed me to inspect the PATH:
<img width="686" alt="TeXworksPreferencesTypesetting" src="https://user-images.githubusercontent.com/23052471/113507680-66bcad80-9522-11eb-8773-243eaaa4b0fe.png">

Running the pwsh.exe Program from TeXworks and printing the PATH:
<img width="476" alt="TeXworksPowerShellPATH" src="https://user-images.githubusercontent.com/23052471/113507881-68d33c00-9523-11eb-9aa2-616fff8fc383.png">

This system is a "preview" release:
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
```
I will try arara on an "Enterprise Windows 10" system (also a non-admin install) and report the results.

**Comment by gnw3** [comment]
I created the same test document on a "Widows Enterprise System": Microsoft Windows [Version 10.0.18363.1256] and arara also fails.   PowerShell is an older version, but adding `C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe` to the list of programs and running it from TeXworks the console outout gives:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\WhiteG\Documents\Testing\MiKTeX> $env:PATH
$env:PATH
C:\Users\WhiteG\AppData\Local\Programs\MiKTeX\miktex\bin\x64\
PS C:\Users\WhiteG\Documents\Testing\MiKTeX> 
```
The workaround (using PowerShell to run an `arara.ps1` script that adds the Java path) works for me.
It is curious that TeXworks in TeX Live 2021 behaves properly.

**Comment by gnw3** [comment]
Further observations:

When MiKTeX TeXworks is run directly as opposed to using either the TeXworks icon or from the MiKTeX terminal (command-line) icon in MiKTeX Console, Arara works normally.
