### ISSUE TITLE
slow search for tfm-files

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#778]
- [x] I have read and acknowledged this HOWTO article:  

lualatex/luaotfload knows an "anonymous" way to setup a font, which first looks for a tfm, then for file name and at last tries to find the font by font name. This lookup is clearly not very effective and I already opened an issue for fontspec to avoid it if possible. But while investigating this I also saw that miktex is much slower than texlive if this lookup is involved.

With the following document I got 0.0298 seconds for miktex for the problematic lookup, while texlive needed 0.0016 seconds.
It is possible to change the lookup-sequence in luaotfload.conf and removing the tfm-lookup resolved the problem, so it is clearly this search which is the bottleneck.

In a document using the mathastext package, which calls such font definitions at every math, this leads to a very noticible slow down. 

~~~~
% !TEX lualatex
\documentclass{article}
\usepackage{l3benchmark}
\begin{document}

\ExplSyntaxOn
%first tfm, then path, then name
\benchmark:n{\font\test=LatinModernRoman:mode=node;}

\benchmark:n{\font\test=name:LatinModernRoman:mode=node;}

\benchmark:n{\font\test=cmr10}

\ExplSyntaxOff
text
\end{document}

miktex
0.0298 seconds (1.21e5 ops)
2.39e-4 seconds (944 ops)
0.00258 seconds (1.04e4 ops)

texlive 21
0.0016 seconds (7.25e3 ops)
4.84e-4 seconds (2.21e3 ops)
6.59e-4 seconds (2.98e3 ops)

texlive 20
0.0057 seconds (2.56e4 ops)
4.86e-4 seconds (2.22e3 ops)
0.0015 seconds (6.98e3 ops)
~~~~

**Comment by edocevoli** [comment]
Is this still an issue? If so, we can reopen this ticket. But I think the performance issue has been "fixed" in the course of development.
