### ISSUE TITLE
No updated PDF file with Miktex's new update

### ISSUE THREAD

**Issue by anaruizar** [MiKTeX/miktex#78]
I have linux Mint 18.3 Cinnamon (64 bits). After the Miktex's last update (2.9.6615 version), when compiling my .tex (let's call it A.tex) file in Texmaker I don't get the updated PDF file. I made a new .tex file (B.tex for example) and then texmaker showed a window saying that the program doesn't find the .log file, without any error. I have tried to uninstall both miktex and texmaker and then install them again (firstly miktex and then texmaker), the problem remained.

Also I have installed Texlive, since a read a suggestion of one of you, and then texwork as editor. I tried again to compile the B.tex and it worked well, however, with my old A.tex it drops and error:

LaTeX Error: File `Classes/PhDThesisPSnPDF.cls' not found

It seems that the program doesn't find the place where the class of the A.tex is defined, but I don't know why. Before the last update of Miktex I hadn't had any problem and now I have it. That's why I guess it's because of the new version. I can't find the solution, hope there's somebody that could help me.

Thank you in advance!

**Comment by edocevoli** [comment]
Please try the workaround presented in #76.

**Comment by anaruizar** [comment]
Thank you so much, it worked!! When compiling in Texmaker it started a dialogue to install some more packages, that's the only thing I had to do after the instructions in the linked post :)
