### ISSUE TITLE
[MikTeX Portable] Can't remove local texmf directory

### ISSUE THREAD

**Issue by egorpugin** [MiKTeX/miktex#780]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

---

Hi,

I'd like to override some old .sty file in my local texmf dir.
I've added it in console, but can't change any priorities here (see pic.) Button are not active. I can't even remove added dir.
Is it supported?

References:
Previous issue with local texmf dir https://github.com/MiKTeX/miktex/issues/66

---

![image](https://user-images.githubusercontent.com/4325333/114285655-80e61680-9a61-11eb-9fe9-f84ad723a7fd.png)

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6290832/miktex-report.txt)

**Comment by edocevoli** [comment]
This is by design. Custom root directories cannot have a higher priority than managed root directories.

**Comment by egorpugin** [comment]
What about of inability to remove added root dir?

**Comment by edocevoli** [comment]
Sorry, overlooked it.

**Comment by edocevoli** [comment]
Thank you, this has been fixed with v21.6.
