### ISSUE TITLE
Installing updates to portable edition from the command line

### ISSUE THREAD

**Issue by AntonioFasano** [MiKTeX/miktex#781]
I have installed a portable MiKTeX, with ` miktexsetup_standalone` 4.1, using the `--portable=dir` option.   
Despite running 

    mpm.exe --update

when I run TeX  binaries, e.g. `pdflatex` I get 

    pdflatex: major issue: So far, you have not checked for MiKTeX updates.

The only solution I found is to open a GUI app, such as the `miktex-console.exe` (simply open). That's simple, but the procedure is not scriptable, which is what I need.  I have searched the issue and often these problems are fixed using the  `--admin` switch. However, it does not apply here, being this a portable installation.

Any help?

I reproduced the problem in a fresh standard Windows 10 virtual machine.    

    initexmf --report
    ReportDate: 2021-04-11 18:14:52
    CurrentVersion: 21.3
    SetupDate: 2021-04-10 15:51:00
    SetupVersion: 21.3
    Configuration: Portable
    GitInfo: ab8ebca / 2021-03-19 10:22:46
    OS: Windows 10 , 64-bit, build 17763
    SharedSetup: on
    LinkTargetDirectory: C:\Users\***\Desktop\latex\texmfs\install\miktex\bin\x64
    PathOkay: yes
    SystemAdmin: yes
    RootPrivileges: no
    AdminMode: no
    Root0: C:\Users\***\Desktop\latex\texmfs\config
    Root1: C:\Users\***\Desktop\latex\texmfs\data
    Root2: C:\Users\***\Desktop\latex\texmfs\install
    UserInstall: C:\Users\***\Desktop\latex\texmfs\install
    UserConfig: C:\Users\***\Desktop\latex\texmfs\config
    UserData: C:\Users\***\Desktop\latex\texmfs\data
    CommonInstall: C:\Users\***\Desktop\latex\texmfs\install
    CommonConfig: C:\Users\***\Desktop\latex\texmfs\config
    CommonData: C:\Users\***\Desktop\latex\texmfs\data

**Comment by edocevoli** [comment]
Running `initexmf --report` right after `mpm --update` should eliminate the message.

**Comment by AntonioFasano** [comment]
Thank you!
