### ISSUE TITLE
'UnicodeData.txt' not found 

### ISSUE THREAD

**Issue by IJustMeAgainI** [MiKTeX/miktex#783]
This is my first time using LaTex. I installed the basic-miktex-20.11-x64 and the basic-miktex-21.2-x64(latest version), in both cases I got the same error. I tried with two different editors and the error was the same. In the \MiKTeX\miktex\log\makefmt\pdflatex this what I found:

`! LaTeX3 Error: File 'UnicodeData.txt' not found.

For immediate help type H <return>.
 ...                                              
                                                  
l.28153   }
           
!  ==> Fatal error occurred, no output PDF file produced!`

I tried to update the package database of the unicode-data but I got the error: Transferred a partial file. 
I deleted and installed the package again but it did not work.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
