### ISSUE TITLE
Problem with updating MiKTeX 21.2

### ISSUE THREAD

**Issue by bellsm74** [MiKTeX/miktex#784]
I installed MixTex 21.2 on Windows 10 and used it without updating the packages. I managed to use it successfull to run latex files. However when I checked for updates and started to update MikteX with the new updates. I obtained at error message at the end of the update process which is as given below. 

After that I couldn't compile my files in TexStudio. The error message is what I found below. Have tried uninstalling and installing MikTeX, to no avail. Please help.

Belinda.

fileName="C:\Users\bells\AppData\Local\Programs\MiKTeX\miktex\bin\x64\miktex-fc-cache.exe", exitCode="1"

GENERAL MIKTEX INFORMATION
ReportDate: 2021-04-15 16:46:35
CurrentVersion: 21.2
SetupDate: 2021-04-15 16:37:00
SetupVersion: 21.2
Configuration: Regular
GitInfo: 7a7e645 / 2021-02-20 10:38:14
OS: Windows 10 Home, 64-bit, build 19042
SharedSetup: no
LinkTargetDirectory: C:\Users\bells\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: no
LastUpdateCheck: 2021-04-15 16:37:59
LastUpdate: 2021-04-15 16:46:08
LastUpdateDb: 2021-04-15 16:37:58
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\bells\AppData\Roaming\MiKTeX
Root1: C:\Users\bells\AppData\Local\MiKTeX
Root2: C:\Users\bells\AppData\Local\Programs\MiKTeX
Root3: C:\ProgramData\MiKTeX
Root4: C:\Program Files\MiKTeX
UserInstall: C:\Users\bells\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\bells\AppData\Roaming\MiKTeX
UserData: C:\Users\bells\AppData\Local\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
Invokers: non-existing/cmd

ERROR DETAILS
Program: miktex-fc-cache.exe
Error: The executed process did not succeed.
Details: 
  fileName: C:\Users\bells\AppData\Local\Programs\MiKTeX\miktex\bin\x64\miktex-fc-cache.exe
  exitCode: 1

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by u-fischer** [comment]
@edocevoli I have seen in the last two days two other reports which have problems with `fc-cache`. It looks as if miktex installations based on the basic installer have problems with the dll. The messages said something like `The code execution cannot proceed because MiKTEX210200-core.dll was not found.`., see e.g. https://tex.stackexchange.com/questions/592863/miktex-updates-fail-right-after-install?noredirect=1#comment1487405_592863

**Comment by edocevoli** [comment]
`MiKTEX210200-core.dll` is an old DLL. So presumably the last update did not succeed. Recreating the links should fix the issue.
