### ISSUE TITLE
Path problems in write18-call  after miktex-update

### ISSUE THREAD

**Issue by NorbertKlingen** [MiKTeX/miktex#786]
- [ x ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

After updating miktex on 2021/04/18 I realized a changed behaviour when using
write18-calls from within TeX.

In one of my source files I have the line

> \immediate\write18{ skizze.bat  1 mp }

and with the newly installed executable

> pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.3) (preloaded format=pdflatex 2021.4.20)

I got the error-message (on the console)

> Der Befehl "skizze.bat" ist entweder falsch geschrieben oder konnte nicht gefunden werden.

Within the TeX-logfile one reads 

> runsystem(skizze.bat 1 mp)...executed.

 which shows that write18 is enabled.

The batch-file 'skizze.bat' lies in 'd:\batch' and this directory is part of my
(global) path. Apparently in the new installation the write18-command does not
know this system-path. With a minimal example I found that in the shell called
by write18 one only has  "PATH=d:\TeX\MiKTeX2.9\miktex\bin\x64".

However with my old executable

> pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 2.9.7380 64-bit) (preloaded format=pdflatex 2020.4.18)

all went well.

In the moment I have an ad-hoc (bad) sideway to this problem, but I would very
much appreciate when the old behaviour could be restalled since I have the
source-files of my pictures within (lots of) TeX-files, export them during a
TeX-run (with an old D.E.Knuth trick) and then use the write18-call to
generate the pictures on-the-fly and embedding them immediately into the output.

Best regards, Norbert Klingen

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by edocevoli** [comment]
It works for me:

```
@echo off
setlocal
if exist C:\abrakadabra\nul rmdir /q /s C:\abrakadabra
mkdir C:\abrakadabra
echo @echo off>C:\abrakadabra\test.bat
echo echo hello, world!>>C:\abrakadabra\test.bat
set PATH=%PATH%;C:\abrakadabra
echo \immediate\write18{ test.bat }\bye> test.tex
pdftex --enable-write18 test.tex
endlocal
```

Output:

```
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.3)
entering extended mode
(test.texhello, world!
 )
No pages of output.
Transcript written on test.log.
```
