### ISSUE TITLE
Miktex console miss the initexmf  --mkmaps and initexmf  --update-fndb function in Windows

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#79]
I just install some new font , take newtx package for example, and complie with mpfont error, so I use the MiKTeX console in windows menu , the 'task' ->refresh font map files and refresh file name database  as admin , but it did not word , so I turn to cmd , just like 'initexmf  --mkmaps' , it compiles ok . I don't know why the gui fails. I also test in linux mint , it works without error

PS，I wish the APP can auto initexmf --mkmaps and initexmf --update-fndb after install new package

**Comment by edocevoli** [comment]
I cannot reproduce this. FNDB files have a new timestamp after running the task in MiKTeX console. Same for the font maps.
