### ISSUE TITLE
CURLCode 56 - error receiving network data

### ISSUE THREAD

**Issue by temcdrm** [MiKTeX/miktex#793]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I have the same problem reported here: #628, which was closed automatically. My logs are attached.  In addition:

- An SSL certificate is required and installed for our proxy server. `https_proxy` and `http_proxy` are set. This works for GitHub.
- I have tried setting and unsetting the `authentication required` check box in MiKTeX Console
- If I simply paste the url `https://api2.miktex.org/hello` into my browser, it comes back with `bye`

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6373401/miktex-report.txt)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/6373403/miktex-console.log)

**Comment by edocevoli** [comment]
Thank you. It seems that MiKTeX is not compatible with your network setup. At the moment, I have not enough info to work on this effectively.

**Comment by temcdrm** [comment]
I'm back to using Overleaf.  That would be my suggestion to anyone who encounters the same issue.

**Comment by xxthunder** [comment]
I would really like to solve this issue as it is a showstopper for MiKTeX in my company's network, too. I tried to create a local repository:

`miktexsetup --verbose --local-package-repository=C:\D\miktex-repo --package-set=complete download

this is MiKTeX Setup Service 5.0 (MiKTeX 22.3)
miktexsetup: Timeout was reached
miktexsetup: Data: code="28", url="https://api2.miktex.org/hello"
PS C:\Users\GuentherK> miktexsetup --verbose --local-package-repository=C:\D\miktex-repo --package-set=complete download

this is MiKTeX Setup Service 5.0 (MiKTeX 22.3)
starting downloader...
starting download...
repository: https://www.texlive.info/CTAN/systems/win32/miktex/tm/packages/
download directory: C:\D\miktex-repo
visiting repository https://www.texlive.info/CTAN/systems/win32/miktex/tm/packages/...
repository type: remote package repository
loading package repository manifest...
downloading https://www.texlive.info/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
miktexsetup: Failure when receiving data from the peer
miktexsetup: Data: code="56", url="https://www.texlive.info/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma"`

If I try to download the same package using curl, it works:

`curl https://www.texlive.info/CTAN/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma --output c:\d\test.lzma
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  271k  100  271k    0     0   243k      0  0:00:01  0:00:01 --:--:--  243k`

Question: does miktex-setup.exe using a different curl implementation?

**Comment by artemonster** [comment]
Hi @edocevoli I would say handling such major issues with "cant reproduce, no problem, k bye, issue closed" is not very effective.
I have the same issue with being behind corporate proxy and MiKTeX refuses to work unless you do updates, i.e. "latexmk: major issue: So far, you have not checked for MiKTeX updates." 
And you cannot do an update because the corporate proxy is so strict, curl doesnt work properly. 
Also trying "local repository" method above yields:
```
C:\redacted\miktex\texmfs\install>miktexsetup --verbose --local-package-repository=C:\redacted\miktex\repo --package-set=complete download
this is MiKTeX Setup Service 5.5 (MiKTeX 23.10)
miktexsetup: Failure when receiving data from the peer
miktexsetup: Data: code="56", url="https://api2.miktex.org/hello"
```
Can you maybe suggest a workaround ? For example provide an option how to use MiKTeX without need for update (i.e. manually fetching an archive and setting somewhere "updated flag" or turning off the mandatory check for update completely? Thank you.

**Comment by artemonster** [comment]
@xxthunder  thanks for your reply! yes, it was my initial idea too, IF you are allowed to stick an USB stick into your corporate network... unfortunately its not the case.
