### ISSUE TITLE
The following signatures were invalid: EXPKEYSIG 277A7293F59E4889 MiKTeX Packager <packager@miktex.org>

### ISSUE THREAD

**Issue by brymer-meneses** [MiKTeX/miktex#798]
When I tried to run `sudo apt update`, I got this error.

- [ x ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
Duplicate of #MiKTeX/miktex-packaging#241
