### ISSUE TITLE
Some PostScript specials could not be rendered.

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [MiKTeX/miktex#8]
When I run LaTeX on the attached sample file, I get some errors, but a .dvi file is generated.  When I subsequently open that .dvi file, the following error message is displayed: "Some PostScript specials could not be rendered."  The message is not terribly informative.  Is it possible to get a message that specifies the cause of the problem and recommends a remedy?
[intro.zip](https://github.com/MiKTeX/miktex/files/1305286/intro.zip)

**Comment by edocevoli** [comment]
Detailed error information can usually be found in the log files. You can attach them (or snippets). (Btw: your test case is not yet complete because the figure is missing).
