### ISSUE TITLE
pdf page sizes problem with xelatex

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#813]
If I compile this document with xelatex

~~~
\RequirePackage{expl3}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff
\documentclass{article}
\begin{document}
\pdfpagewidth=5cm
\pdfpageheight=10cm
page


\newpage
\pdfpagewidth=10cm
\pdfpageheight=10cm

text
\end{document}
~~~~

I get in texlive a pdf with two different page size, in miktex both have the size of the first page. 

The difference can be seen in the pdf:

## texlive 
~~~~
3 0 obj
<</Resources 7 0 R/Type/Page/Parent 11 0 R/Contents[6 0 R]>>
endobj
8 0 obj
<</Resources 10 0 R/Type/Page/Parent 11 0 R/MediaBox[0 0 283.46 283.46]/Contents[9 0 R]>>
endobj
~~~~

## miktex
~~~~
3 0 obj
<</Resources 7 0 R/Type/Page/Parent 11 0 R/Contents[6 0 R]>>
endobj
8 0 obj
<</Resources 10 0 R/Type/Page/Parent 11 0 R/Contents[9 0 R]>>
endobj
~~~~

in miktex the second page is missing a MediaBox. 

The problem seems to lie in xdvipdfmx, as `xelatex --no-pdf` from miktex +  `xdvipdfmx` from texlive works fine. 
My xdvipdfmx version on texlive is 

~~~~
This is xdvipdfmx Version 20210318 by the DVIPDFMx project team,
~~~~

**Comment by edocevoli** [comment]
Seems to be a xdvipdfmx regression. I will update to the latest available version. Hope this then fixes the issue.
