### ISSUE TITLE
Help to possibly reduce setup size

### ISSUE THREAD

**Issue by AntonioFasano** [MiKTeX/miktex#819]
The "essential" package set, which is the lightest one, is some 700 MB once it is expanded and used to build a sample LaTeX file such as:

    \documentclass{article}
    \begin{document}
    Hello World
    \end{document}

This size suggests that the essential set includes some packages that some users might not  need.

I tried to remove some random packages with `mpm` and  I still  was able to build the simple document above. In fact, there are several low footprint distros, which can build barebone documents, staying below 100 MB. 

So I wonder if you can give us some guidance to _which packages we need to build a plain LaTeX document_, like above.  If more components were needed for specific categories of users, the  "Just Enough TeX" feature would automatically integrate missing packages, that is, once a user has built their first document, they have a customised installation, based on the features they actually need.

**Comment by edocevoli** [comment]
The "essential" package set only contains executables and some support files, so I don't know what you mean when you say

> is some 700 MB once it is expanded and used to build a sample LaTeX file

Please give more info about your setup and how you ran your test.

**Comment by AntonioFasano** [comment]
I use:

    .\miktexsetup_standalone --local-package-repository .\essnt-repo --package-set=essential download
    .\miktexsetup_standalone --local-package-repository .\essnt-repo --package-set=essential --portable "$(Resolve-Path.)\essnt-tex" install
    (dir -Recurse .\essnt-tex | Measure-Object -Sum length).Sum / 1MB

The last command gives an `essnt-tex` program folder of  660 MB. However, this configuration is unable to build a plain LaTeX file, such as:

    \documentclass{article}
    \begin{document}
    Hello World
    \end{document}


Activating the autoinstall packages feature and building the file above:

    .\essnt-tex\texmfs\install\miktex\bin\x64\initexmf.exe --set-config-value=[MPM]AutoInstall=yes
    $env:Path+=";$(Resolve-Path .\essnt-tex\texmfs\install\miktex\bin\x64\)"
    pdflatex.exe foo


gives an `essnt-tex` program folder of 722MB. That is without, updating with `mpm`, which slightly increase the folder (to 736MB).

**Comment by edocevoli** [comment]
Nice, thank you. Will try to reproduce/resolve this. The essential setup should be much smaller.

**Comment by edocevoli** [comment]
By the way, you should not use Windows Explorer to calculate disk usage, because this tool does not understands hard links. The "real" disk size is much smaller, provided your file system is NTFS.

I have followed your instructions above. `du` (Sysinternals) reports:

```
Files:        2018
Directories:  337
Size:         334,695,232 bytes
Size on disk: 341,082,112 bytes
```

Let me know, if you are think that there is ballast we can rid of. We can then reopen this issue.

**Comment by AntonioFasano** [comment]
I didn't know the portable version used hard links. This implies the portable flash drive should be formatted as NTFS and the portable folder cannot be copied elsewhere, without destroying hard links and  affecting size, unless a tool such as  [ln.exe](https://schinagl.priv.at/nt/ln/ln.html) is used, which can preserve hard links. 

As regards the packages, I am not very knowledgeable about LaTeX packages. All I can think of is to remove packages until a plain LaTeX file builds. So, given `foo.tex` in `foo` dir:

    \documentclass{article}
    \begin{document}
    Hello World
    \end{document}

I run:

    $env:Path+=";$(Resolve-Path .\essnt-tex\texmfs\install\miktex\bin\x64\)"
    initexmf.exe --set-config-value=[MPM]AutoInstall=yes
    cd foo
    pdflatex.exe foo
     
    $paks2remove = @("biber-windows-x64", "miktex-arctrl-bin-x64-2.9", "miktex-asymptote-bin-x64-2.9", "miktex-autosp-bin-x64-2.9", "miktex-axohelp-bin-x64-2.9", "miktex-bibarts-bin-x64-2.9", "miktex-bibtex-bin-x64-2.9", "miktex-bibtex8bit-bin-x64-2.9", "miktex-cairo-bin-x64-2.9", "miktex-chktex-bin-x64-2.9", "miktex-cjkutils-bin-x64-2.9", "miktex-console-bin-x64-2.9", "miktex-cweb-bin-x64-2.9", "miktex-devnag-bin-x64-2.9", "miktex-dvicopy-bin-x64-2.9", "miktex-dvipdfmx-bin-x64-2.9", "miktex-dvipng-bin-x64-2.9", "miktex-dvips", "miktex-dvips-bin-x64-2.9", "miktex-dvisvgm-bin-x64-2.9", "miktex-epstopdf-bin-x64-2.9", "miktex-findtexmf-bin-x64-2.9", "miktex-fontconfig-bin-x64-2.9", "miktex-fonts-bin-x64-2.9", "miktex-freeglut-bin-x64-2.9", "miktex-freetype2-bin-x64-2.9", "miktex-fribidixetex-bin-x64-2.9", "miktex-gd-bin-x64-2.9", "miktex-ghostscript-bin-x64", "miktex-graphite2-bin-x64-2.9", "miktex-gregorio-bin-x64-2.9", "miktex-gsf2pk-bin-x64-2.9", "miktex-harfbuzz-bin-x64-2.9", "miktex-hunspell-bin-x64-2.9", "miktex-icu-bin-x64", "miktex-jpeg-bin-x64-2.9", "miktex-kpathsea-bin-x64-2.9", "miktex-lacheck-bin-x64-2.9", "miktex-lcdf-typetools-bin-x64-2.9", "miktex-lua53-bin-x64-2.9", "miktex-luatex-bin-x64-2.9", "miktex-m-tx-bin-x64-2.9", "miktex-makeindex-bin-x64-2.9", "miktex-metafont-bin-x64-2.9", "miktex-metapost-bin-x64-2.9", "miktex-mfware-bin-x64-2.9", "miktex-mkfntmap-bin-x64-2.9", "miktex-mo-bin-x64-2.9", "miktex-mpfr-bin-x64-2.9", "miktex-mthelp-bin-x64-2.9", "miktex-mtprint-bin-x64-2.9", "miktex-omegaware-bin-x64-2.9", "miktex-patgen-bin-x64", "miktex-pixman-bin-x64-2.9", "miktex-pmx-bin-x64-2.9", "miktex-poppler-bin-x64-2.9", "miktex-ps2pk-bin-x64-2.9", "miktex-psutils-bin-x64-2.9", "miktex-synctex-bin-x64-2.9", "miktex-tdsutil-bin-x64", "miktex-teckit-bin-x64-2.9", "miktex-tex2xindy-bin-x64-2.9", "miktex-tex4ht-bin-x64-2.9", "miktex-texify-bin-x64-2.9", "miktex-texware-bin-x64-2.9", "miktex-texworks-bin-x64-2.9", "miktex-ttf2pk2-bin-x64-2.9", "miktex-ucrt-bin-x64", "miktex-web-bin-x64-2.9", "miktex-xetex-bin-x64-2.9", "miktex-xindy-bin-x64", "miktex-xml2pmx-bin-x64", "miktex-yap-bin-x64-2.9", "miktex-zip-bin-x64", "miktex-zzip-bin-x64-2.9", "tetex", "unicode-data")
     
    mpm --uninstall=$paks2remove


I don't know if the 77 packages in `$paks2remove` are actually removed, as `mpm` reports some errors. However, querying installed packages:

    mpm.exe --list  | Select-String "^i" 

reports only the following installed packages:

    i 00313   31552419 ltxbase
    i 00002     105192 miktex-bzip2-bin-x64-2.9
    i 00065      50004 miktex-config-2.9
    i 00002     568937 miktex-curl-bin-x64-2.9
    i 00002     176545 miktex-expat-bin-x64-2.9
    i 00002     266998 miktex-fmt-bin-x64-2.9
    i 00003      10349 miktex-fontconfig
    i 00004       2056 miktex-latex
    i 00002    1997723 miktex-libressl-bin-x64-2.9
    i 00004    2396037 miktex-log4cxx-bin-x64-2.9
    i 00002     216782 miktex-lzma-bin-x64-2.9
    i 00002      40692 miktex-md5-bin-x64-2.9
    i 00027     118662 miktex-misc
    i 00006     993718 miktex-mktex-bin-x64-2.9
    i 00002     320262 miktex-mpmcli-bin-x64-2.9
    i 00002     117547 miktex-mspack-bin-x64-2.9
    i 00006       2800 miktex-pdftex
    i 00004    4288818 miktex-pdftex-bin-x64-2.9
    i 00002     259424 miktex-png-bin-x64-2.9
    i 00002      81801 miktex-popt-bin-x64-2.9
    i 00003     142157 miktex-posix-bin-x64-2.9
    i 00015   31084062 miktex-qt5-bin-x64
    i 00025    8140030 miktex-runtime-bin-x64-2.9
    i 00002     610509 miktex-tex-bin-x64-2.9
    i 00002     216786 miktex-upmendex-bin-x64
    i 00002     127887 miktex-uriparser-bin-x64-2.9
    i 00023   13685886 miktex-vc140-bin-x64
    i 00002     128423 miktex-zlib-bin-x64-2.9

and 

    pdflatex.exe foo

succeeds.
