### ISSUE TITLE
pdflatex fails with in config.cpp Line: 966

### ISSUE THREAD

**Issue by donovaly** [MiKTeX/miktex#82]
- install MiKTeX using the "basic-miktex-2.9.6520.exe" (explicitly not the latest 2.9.6615 installer)
- update MiKTeX using the command line:
`mpm.exe --admin --update`

This succeeds.

Now try to run pdflatex over this simple TeX file:
`\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[latin9]{inputenc}
\begin{document}
test
\end{document}`

I get an error:

2018-03-02 19:33:14,417+0100 INFO  pdflatex - starting with command line: pdflatex testa
2018-03-02 19:33:14,417+0100 INFO  pdflatex - allowing known shell commands
2018-03-02 19:33:14,417+0100 INFO  pdflatex - enabling input (output) from (to) processes
2018-03-02 19:33:14,417+0100 FATAL pdflatex - MiKTeX encountered an internal error.
2018-03-02 19:33:14,417+0100 FATAL pdflatex - Info: 
2018-03-02 19:33:14,417+0100 FATAL pdflatex - Source: Libraries\MiKTeX\Core\Session\config.cpp
2018-03-02 19:33:14,417+0100 FATAL pdflatex - Line: 966
2018-03-02 19:33:14,433+0100 INFO  pdflatex - finishing with exit code 1

**Comment by edocevoli** [comment]
Seems it doesn't work to update 2.9.6520 via `mpm --update`. It is not possible to fix this 😧

**Comment by donovaly** [comment]
> It is not possible to fix this anguished

OK, but what can I do?:
- my users installed the last LyX  version in October last year and want now install the new LyX version
- most users have therefore a MiKTeX with the last updates from October
- in the LyX installer I update mpm to assure that the users get the latest MiKTeX including the new package installation mechanism
- afterwards the installer can use the new package handling to install LaTeX packages required by LyX

This is how I found this bug (several users reported this). So with my current method 100% of LyX users will get an unusable MiKTeX. I don't know what to do if this bug cannot be fixed.

**Comment by edocevoli** [comment]
`mpm` which is distributed with 2.9.6520 is buggy (as you have found out). The error message indicates that the MiKTeX core library is not up-to-date after the `mpm --update` run because line 966 does not match a suitable code line (`config.cpp`). Unless you provide more info (log files), I don't know how to implement a workaround.

**Comment by donovaly** [comment]
> Unless you provide more info (log files), I don't know how to implement a workaround.

I will provide everything you need. I posted already the content of the pdflatex.log file in my initial commit. What other log files do you need?

I have an idea: when installing  2.9.6520 and running mpm in graphical mode, I see that only 2 packages are selected. After this update run I can run mpm again in graphical mode and update the rest. So this two-stage update works. So maybe mpm --update can/should do the same?

**Comment by edocevoli** [comment]
Yes, `mpm --update` should do the same. But a fix for the old version cannot be made available.

**Comment by donovaly** [comment]
Thank you. After thinking a while about this issue I see no other solution for LyX than to announce that those users who cannot compile a PDF after installing LyX have to uninstall MiKTeX and reinstall it together with the installer for LyX.
Could you maybe provide a new basic-miktex installer that I can provide with LyX? That would be helpful because of bug #71 you already fixed.

**Comment by donovaly** [comment]
The final solution I published now is to force 2 graphical MPM runs. All my tests show that this is of course inconvenient for the users but it is the only method that will work, no matter if the users use a 2 year old MiKTeX or an up to date one.
A new basic-miktex installer would still help me nevertheless.

**Comment by edocevoli** [comment]
A new basic installer will be available soon. In the meantime, I will try to find a workaround for this issue.

**Comment by edocevoli** [comment]
A possible workaround: recreate the links after running `mpm --update`:

```
initexmf --admin --mklinks --force
```

**Comment by donovaly** [comment]
Many thanks!!! This fixes the problem for all my test cases.

**Comment by donovaly** [comment]
> A new basic installer will be available soon. 

I see that you uploaded new install media but not yet a new basic-miktex installer. Do you have a plan when you will do this? I am asking becasue if it takes more time, I would announce the LyX installer right now otherwise I would wait and build a new installer that includes a new basic-miktex installer.
