### ISSUE TITLE
Kindly suggest to solve this problem in miktex " Could not start the command. pdflatex -synctex=1 -interaction=nonstopmode %.tex" 

### ISSUE THREAD

**Issue by nayankrsarkar** [MiKTeX/miktex#820]
I am new to miktex. I have installed latest version of miktex and texmaker as editor. When I compile a code I got the message like " Could not start the command. pdflatex -synctex=1 -interaction=nonstopmode %.tex" .  I searched in internet and somebody suggested to install TexLive, I tried for TexLive too but not working.. could you please suggest me how to solve the problem, how to compile a  piece of code without error or to solve the mentioned problem

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
