### ISSUE TITLE
wrong initexmf --admin warning

### ISSUE THREAD

**Issue by donovaly** [MiKTeX/miktex#83]
- install MiKTeX using the latest "basic-miktex-2.9.6615.exe"
- update MiKTeX using the command line:
`mpm.exe --admin --update`
- now run pdflatex 

I get a wrong warning:

--------------
d:\Download>mpm --admin --update
10 packages have been successfully updated.

d:\Download>pdflatex testa
initexmf: warning: Option --admin should be specified when running this program
with administrative privileges
initexmf: warning: Option --admin should be specified when running this program
with administrative privileges
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6600)
entering extended mode
(testa.tex
LaTeX2e <2017-04-15>
...

--------------

As you can see I have admin permissions since mpm -- admin succeeded. Therefore the --admin warning of initexmf seems to be wrong.

**Comment by edocevoli** [comment]
No, the warning is correct. You are running `initexmf` with elevated privileges and so you should specify `--admin` if you intend to make system-wide changes. The warning is just a reminder that you are doing something special.

**Comment by donovaly** [comment]
> You are running initexmf with elevated privileges

The point is that I don't run initexmf but pdflatex. Therefore I cannot specify any option to initexmf because pdflatex invokes the initexmf call.

Therefore I think as pdflatex calls initexmf it is the duty of pdflatex to assure that initexmf is called correctly.

**Comment by edocevoli** [comment]
The special thing is that, in your use case, `pdflatex` (which executes `initexmf`) runs with elevated privileges. I will add an additional warning in `pdflatex` which makes it clearer to the user.

**Comment by donovaly** [comment]
> I will add an additional warning in pdflatex which makes it clearer to the user.

Thank you.
But how can a user who is admin prevent to see these warnings? I mean he cannot do more than calling pdflatex, he cannot pass the --admin option to initexmf because pdflatex would not forward it.

**Comment by edocevoli** [comment]
You can cause `pdflatex` to operate on the system-side installation by using the option `--miktex-admin`:

```
pdflatex --miktex-admin sample2e
```

This will prevent the warning.

**Comment by donovaly** [comment]
Thank you for this info.

**Comment by burgealex** [comment]
@edocevoli  Sorry to bump an old post, but is the --miktex-admin flag documented somewhere?  I have been having this same issue with a number of other programs in the miktex distribution.  I've also been experiencing file contention issues that seem to be related.

It seems like a number of the programs might be accepting the flag, but none of them seem to reference it.

**Comment by edocevoli** [comment]
See #212

**Comment by HerbM** [comment]
What is the logic behind this warning which is (mostl) specific to MikTex? 

It there something extra special dangerous happening with MixTex programs?

**Comment by edocevoli** [comment]
The warning tells you that you are doing something wrong: newly written files (e.g. file name caches) will will be owned by administrators and non-admin users will not be able to delete/modify them. So this is usually a road to disaster:

1. open a `cmd` window as administrator
2. run `initexmf -u`
3. open a `cmd` windows (not as administrator)
4. run `initexmf -u`

Step 4. usually fails because you are not allowed to overwrite the file name database files.

Unless you are a professional user (system admin, developer, ...) you should not install MiKTeX with elevated privileges.
