### ISSUE TITLE
Suspicious behavior when downloading MikTex from website!

### ISSUE THREAD

**Issue by AbdullahXO** [MiKTeX/miktex#831]
I couldn't download MikTex from website: https://miktex.org/download via my university network. 

After contacting IT, it seems the .exe file is malicious! They provided me with the following analysis link: 
removed link

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
