### ISSUE TITLE
Package downloader chooses insecure random mirrors

### ISSUE THREAD

**Issue by liwalter** [MiKTeX/miktex#833]
The Miktex console allows to choose a mirror manually from a list which contains HTTPS but also HTTP and FTP mirrors. The default configuration however is to request a random mirror, which is used for updating and installing packages. I tested the random mirror function and got both HTTPS and HTTP mirrors, which shows, that no – or only limited - additional filtering of the mirrors regarding their communication method is done.
As already mentioned in a previous issue (#24), using HTTP or FTP for package downloading is insecure and vulnerable to MITM attacks. Since then, CTAN has added many HTTPS mirrors to its official mirror list and, as of April 2021, only automatically redirects to mirrors using HTTPS.
To avoid unnecessary security risks for users using the default “Random Mirror” option, the Miktex downloader should choose from HTTPS mirrors exclusively, when this option is enabled.

**Comment by edocevoli** [comment]
Thank you for the report. I have made an experimental server-side change: only `https` repositories will be returned to MiKTeX Console.

**Comment by edocevoli** [comment]
Thank you, this has been fixed with v21.6. That said, the package downloaded now chooses a secure mirror.
