### ISSUE TITLE
No authentication of packages

### ISSUE THREAD

**Issue by liwalter** [MiKTeX/miktex#834]
As implied in „Security improvements in TeXLive“ [1] the compromisation of CTAN mirrors is possible and would remain largely undetected. This would allow an attacker to manipulate files on the mirror, which would then be distributed to clients if the mirror is accessed directly or via a Tex-Distro as Miktex.
To counteract this scenario, Texlive has employed package authentication methods since 2017: A file containing the SHA-512 checksums of every package. This file is signed with the Texlive maintainers key. [1]

As already mentioned in issue #24, Miktex does not provide any authentication mechanisms, as far as I can judge from the source code. The MD5 hashes contained in mpm.ini and package-maninfests.ini are, as far as I understand, only used to check if the packages were downloaded correctly from the mirror and to search for updates and not to verify if the mirror contains manipulated files. Even if, this would be to no avail since both .ini files are downloaded from a mirror (often the same as used for package installation) and can hence also be manipulated.

To detect manipulated packages, (at least) the mpm.ini should be signed with a cryptographic key, as it is currently done by Texlive. Whenever mpm.ini is downloaded or updated, its signature must be checked by the Miktex updater to authenticate the contained package hashes. To do this Miktex has to contain the matching public key. When a package is downloaded from a mirror, the package installer can use the matching hash from mpm.ini to verify the integrity of the downloaded package. 
To avoid attacks, where the package is manipulated in a way, that the MD5 hash still matches the one in mpm.ini (MD5 is not collision-resistant), the checksums should be calculated using a secure hash algorithm like SHA-256 as proposed by the BSI in BSI TR-02102-1 [2].

[1] „Security improvements in TeXLive“ (https://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/231761)
[2] " Cryptographic Mechanisms" (https://www.bsi.bund.de/EN/Service-Navi/Publications/TechnicalGuidelines/tr02102/tr02102_node.html)

**Comment by edocevoli** [comment]
> To detect manipulated packages, (at least) the mpm.ini should be signed with a cryptographic key...

It seems you have overlooked the signature at the end of `mpm.ini`. It currently looks as follows:

```ini
;;;;This configuration file is signed by a MiKTeX maintainer. The signature follows.
;;;;-----BEGIN MIKTEX SIGNATURE-----
;;;; signature/miktex: AFZ4scjdJYPIN2yS8i4Ucw/H1Qj4w00OlBw2P3JOiFIfRqcqIu+WSlFg465mpjeHkT/qKBbvcaEKxkHNUcjWZ7JjUYYSvUkMiCEq4q2/dqiFoDaVmxl1dFljwy1SpNo4zC1Zu7lcMNGe5sgZsOgq0Xn9KHgz1TQJAHTc2xN/ihqibVNQ39Z2SNlrD+yYMFZbpcZ342K7BHyCo0rgeenOACIYfguT9BJNw/yNJ6oeImbj35ybfKmFiG+zdB7C8ol4AHdFLZ6tuPzGHQugxhNie1vshSSm4axDdMsdDsDPlMoBjqMo1zQL3O7XT2jiLGcixMk2Oa85p1OQ66cFWs/Q1g==
;;;;-----END MIKTEX SIGNATURE-----
```
