### ISSUE TITLE
makemf fails with the ugmr fonts

### ISSUE THREAD

**Issue by donovaly** [MiKTeX/miktex#84]
With a fresh MiKTeX installation and all available updates I get:

Sorry, but miktex-makemf did not succeed for the following reason:
The ugmr8r source file could not be found.
The log file hopefully contains the information to get MiKTeX going again:
hbf2gf (CJK ver. 4.8.4)
Couldn't open `ugmr.cfg'
...

Here are the 2 log files:
[miktex-makemf.log](https://github.com/MiKTeX/miktex/files/1778724/miktex-makemf.log)
and
[miktex-maketfm.log](https://github.com/MiKTeX/miktex/files/1778725/miktex-maketfm.log)

I am not sure if this is a bug in MiKTeX or in the font package.

**Comment by edocevoli** [comment]
Have you installed the `mathdesign` package?

**Comment by donovaly** [comment]
> Have you installed the mathdesign package?

Yes: 
![mathdesign-installed](https://user-images.githubusercontent.com/1828501/36949066-b06c3e4e-1fe3-11e8-8aa7-eb2f349251c7.jpg)

**Comment by edocevoli** [comment]
Please provide a minimal test case.

**Comment by donovaly** [comment]
All I do is to
- open a console
- execute there the command
`miktex-makemf.exe --verbose zgmr8r`

result: 
Sorry, but miktex-makemf did not succeed for the following reason:
  The zgmr8r source file could not be found.
The log file hopefully contains the information to get MiKTeX going again:
  C:/Users/User/AppData/Local/MiKTeX/2.9/miktex/log/miktex-makemf.log
You may want to visit the MiKTeX project page, if you need help.

I attached the logfile in my initial comment.

**Comment by edocevoli** [comment]
If I run `miktex-makemf.exe --verbose blablabla` I get same error message. I don't think that this is bug.

**Comment by edocevoli** [comment]
There is a CTAN package named `garamondx` which contains a `zgmr8r` map file entry. Installing this package manually should fix the problem.

This package is non-free and therefore not included in the distribution.

**Comment by donovaly** [comment]
> If I run miktex-makemf.exe --verbose blablabla I get same error message. I don't think that this is bug.

Yes, because "blablabla" is not a valid font name. It works with other existing fonts.

> a CTAN package named garamondx which contains a zgmr8r map file entry. 

Thanks for this info. So I can ignore these kind of errors in future.
