### ISSUE TITLE
When a package have been uninstalled, its directories are not removed

### ISSUE THREAD

**Issue by waynon** [MiKTeX/miktex#841]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

When a package have been uninstalled, its directories are not removed, leaving a lot of empty directories on my computer.

The empty directories are:

- `<MiKTeX Installation Location>`/doc/`<package path>`
- `<MiKTeX Installation Location>`/source/`<package path>`

The rubbish directories are annoying, and I think they should be deleted when a package is uninstalled.

**Comment by BeerStud** [comment]
On Fri, 04 Jun 2021 21:37:47 -0700, waynon stated:
>- [x] I have read and acknowledged this HOWTO article:  
>  [Submitting a MiKTeX problem
> report](https://miktex.org/howto/bug-report)
>
>When a package have been uninstalled, its directories are not removed,
>leaving a lot of empty directories on my computer.
>
>The empty directories are:
>
>- <MiKTeX Installation Location>/doc/<package path>
>- <MiKTeX Installation Location>/source/<package path>
>
>The rubbish directories are annoying, and I think they should be
>deleted when a package is uninstalled.

That happens with a multitude of software applications. To circumvent
that problem, I use "Revo Uninstaller Pro"
<https://www.revouninstaller.com/>. It will usually remove all of the
remnants of a program; however, if you start it before installing an
application, it will create a log file that it uses to remove 100% of
the crud and left over registry entries.

-- 
gerard

**Comment by edocevoli** [comment]
This has been fixed.
