### ISSUE TITLE
Unable to download the windows installer from the official website 

### ISSUE THREAD

**Issue by basildoesstuff** [MiKTeX/miktex#842]
The download of the miktex windows installer crashes at around 99 mb/244 mb .
Mirror : https://mirror.yongbok.net/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-21.2-x64.exe

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
