### ISSUE TITLE
\usepackage{fontspec} is ignored on Windows.

### ISSUE THREAD

**Issue by ytrezq** [MiKTeX/miktex#843]
I installed all Miktex packages. but as soon as I use

    \usepackage{fontspec}
    \setmainfont[Mapping=tex-text]{Helvetica Neue}
where Helvetica Neue ttf file is installed system‑wide on Windows, the font being output in the pdf is LMroman whereas if I compile the same tex file with TexLive on Linux, the generated pdf is written using the expected font.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
