### ISSUE TITLE
Documentation not found

### ISSUE THREAD

**Issue by edocevoli** [MiKTeX/miktex#844]
Reported by a MiKTeX user via e-Mail:

I have some problem with MiKTeX  (updated one minute ago). I am not able to find the documentation of 
many packages; for example: babel, amsart, lualatex, luatex, etc.
I tried both with texdoc and mthelp without result. The distribution works without problem also using babel,
but its file .doc is it not to find. The terminal answers: Documentation for babel could not be found.

**Comment by edocevoli** [comment]
Please note that the basic installer currently only contains the run-time package. Do you suggest, that it should also include the `__doc` packages?

**Comment by moewew** [comment]
I guess so, but not only that.

Currently on-the-fly installation only gives you the run-time. To get the docs, you have to *manually* install it afterwards. This is tedious and prone to errors (i.e. forgetting which packages were installed). It would be great if the run-time package would automatically also install the `__doc` package. (Of course what holds for on-the-fly installation also holds for manual installation though there it could be argued more easily that people can just select the `__doc` package if they want it.)

**Comment by edocevoli** [comment]
Calling `mthelp babel` should now trigger the installation of `babel__doc`.

**Comment by moewew** [comment]
That is better. There seems to be a slight issue if the manual does not have the same name as the package, though.
Neither `texdoc --view scrguide` nor `texdoc --view circuitikzmanual` trigger the installation of the appropriate `__doc` package (`koma-script__doc` and `circuitikz__doc`, respectively).


But there is still the issue that the documentation and the actual package may be out of sync if the documentation is installed later than the package proper. So I still think it would be useful to have an option to install (and update) the package and its documentation at the same time.
