### ISSUE TITLE
"Unknown file archive size." when installing tools

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex#845]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

On trying to install the package `tools`, I get the error "Unknown file archive size." The error report and installation report are attached.
[error-report.txt](https://github.com/MiKTeX/miktex/files/6610963/error-report.txt)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6610965/miktex-report.txt)

**Comment by edocevoli** [comment]
`tools` has been renamed to `latex-tools`. Please update the data bases.
