### ISSUE TITLE
pdflatex fails to create PDF file (pdflatex.core - Permission denied: path="test.pdf", modeString="wb")

### ISSUE THREAD

**Issue by miguel-latre** [MiKTeX/miktex#848]
After updating MiKTex from an older version (not sure which) to  MiKTeX 21.6, pdflatex fails to create the PDF file.

`pdflatex` output states: ``! I can't write on file `test.pdf'.``
`test.pdf` file does not exist, so it is not locked by any other application.

`pdflatex.log` records some permission problem when opening for writing the PDF file:

```
2021-06-17 12:40:25,495+0200 FATAL pdflatex.core - Permission denied: path="test.pdf", modeString="wb"
2021-06-17 12:40:25,495+0200 FATAL pdflatex.core - Function: _wopen
2021-06-17 12:40:25,495+0200 FATAL pdflatex.core - Result: 13
2021-06-17 12:40:25,496+0200 FATAL pdflatex.core - Data: path="test.pdf", modeString="wb"
2021-06-17 12:40:25,496+0200 FATAL pdflatex.core - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp:567
```

Previous to the update I made on 15-6-2021, this problem did not occur. I do not know the version of MiKTeX that was updated, but was one of the 2.9 versions.

I still having the same problem after reinstalling MiKTeX 21.6, both as regurlar user and admin.

I am using Windows 10 (version 2004, build 19041.1052).

I am attaching MiKTeX logs, the `miktex-report.txt`, a minimal working example (that includes the `.aux` and `.log` files generated) and the output produced to the console. 

[log-app-data.zip](https://github.com/MiKTeX/miktex/files/6669719/log-app-data.zip)
[log-program-data.zip](https://github.com/MiKTeX/miktex/files/6669720/log-program-data.zip)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6669721/miktex-report.txt)
[mwe.zip](https://github.com/MiKTeX/miktex/files/6669722/mwe.zip)
[output.txt](https://github.com/MiKTeX/miktex/files/6669723/output.txt)

This issue might be related to #568, despite it was posted a year ago and it was fixed.

- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
Thank you. Unfortunately this bug is not reproducible. That is, it cannot be fixed. Maybe a third party (e.g., maleware, virus scanner) is preventing MiKTeX from writing the PDF file.

**Comment by miguel-latre** [comment]
Thank you. Indeed, it was the antivirus scanner. It was blocking `pdflatex` without throwing any message.
