### ISSUE TITLE
How-to do a comprehensive update in Linux terminal

### ISSUE THREAD

**Issue by TiemenSch** [MiKTeX/miktex#849]
So I installed MiKTeX according to the user-installation instructions on a Debian system (Docker image).

I can't for the life of me figure out how to get rid of the ``latexmk: major issue: So far, you have not checked for MiKTeX updates.``

Here is the corresponding Dockerfile snippet:
```Dockerfile
# Add MiKTeX key and list and install typesetting dependencies.
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends gnupg && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889 && \
    echo "deb http://miktex.org/download/debian buster universe" | sudo tee /etc/apt/sources.list.d/miktex.list && \
    apt-get update && \
    apt-get install -qy --no-install-recommends \
    miktex \
    pandoc \
    && \
    apt-get purge gnupg -y && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Finalize for user (must be done in home directory!)
USER ${USER}
WORKDIR ${HOME}
RUN miktexsetup finish && \
    initexmf --set-config-value [MPM]AutoInstall=1 && \
    mpm --update-db && \
    mpm --upgrade --package-level=basic && \
    mpm --update && \
    initexmf --mkmaps && \
    initexmf --update-fndb
```

Which leaves me with the following ``initexmf --report``:
```shell
ReportDate: 2021-06-18 11:47:04
CurrentVersion: 21.6
SetupDate: 2021-06-18 11:28:00
SetupVersion: 21.6
Configuration: Regular
GitInfo: 1dd0ae5 / 2021-06-06 11:29:06
OS: Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64
SharedSetup: no
LinkTargetDirectory: /home/ratio/bin
PathOkay: yes
LastUpdateCheck: 2021-06-18 11:28:49
LastUpdate: not yet
LastUpdateDb: 2021-06-18 11:28:49
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: /home/ratio/.miktex/texmfs/config
Root1: /home/ratio/.miktex/texmfs/data
Root2: /home/ratio/.miktex/texmfs/install
Root3: /var/lib/miktex-texmf
Root4: /var/cache/miktex-texmf
Root5: /usr/local/share/miktex-texmf
UserInstall: /home/ratio/.miktex/texmfs/install
UserConfig: /home/ratio/.miktex/texmfs/config
UserData: /home/ratio/.miktex/texmfs/data
CommonInstall: /usr/local/share/miktex-texmf
CommonConfig: /var/lib/miktex-texmf
CommonData: /var/cache/miktex-texmf
```

Perhaps, since it's a fresh install and there's nothing to update but it thinks it always should update something?
``LastUpdate: not yet`` seems to be weirdly off, too.

This leads me to the following question:

What should be the comprehensive command (sequence) to just get rid of any update related issue? Whenever MiKTeX thinks anything is out of date, I would just like to be able to run ``mpm --update-all`` and be done with it.

I wouldn't mind including a custom shell script for this, but it seems as if the sequence of things is of importance. 

Any help?

**Comment by edocevoli** [comment]
Since `mpm` has nothing to update, it does not set `lastUpdate`.

When `LastUpdateCheck` is set, tools like `latexmk` do (should) not issue a warning.

**Comment by TiemenSch** [comment]
OK, so I fooled around a bit:

If I let latexmk be auto-installed, it will complain when used right away.

But if I run ``initexmf --report`` afterwards, ``latexmk`` won't complain thereafter.
