### ISSUE TITLE
Multiple problems when installing MiKTeX on Ubuntu 17.10

### ISSUE THREAD

**Issue by Vakerrian** [MiKTeX/miktex#85]
I am currently getting an installation error when trying to install MiKTeX on Ubuntu 17.10. 
First error came up when it cam to the step `sudo apt update`:

> N: Skipping acquire of configured file 'universe/binary-i386/Packages' as repository 'http://miktex.org/download/ubuntu xenial InRelease' doesn't support architecture 'i386'

I then add `[arch=amd64]` to the `miktex.list` in `sources.list.d` which removes this error. However, when I `sudo apt install miktex` (note that I've tried doing this with and without the modifications in `miktex.list` and get the same error):

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies.
>  miktex : Depends: libhunspell-1.3-0 (>= 1.3.3) but it is not installable
>           Depends: libicu55 (>= 55.1-1~) but it is not installable
>           Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
> E: Unable to correct problems, you have held broken packages.

I've tried cleanning, installing the libs `-f` with the install but no success whatsoever. Any clue what should I do? Thanks!

**Comment by edocevoli** [comment]
Ubuntu 17.10 is not yet supported.

**Comment by Vakerrian** [comment]
@edocevoli Any planned dates?

**Comment by edocevoli** [comment]
This year, I hope.

**Comment by Vakerrian** [comment]
@edocevoli Great! Do you think this a 17.10 specific error? Also is 18.04 in the short-term scope as it's LTS?

**Comment by edocevoli** [comment]
The next LTS Ubuntu (18.04) will be supported.
