### ISSUE TITLE
Hope MiKTeX can support upTeX series (upTeX/upLaTeX/eupTex...) engine

### ISSUE THREAD

**Issue by ostaith** [MiKTeX/miktex#858]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I like MiKTeX "Just enough TeX" concept very much, and upTeX is the best vertical Japanese/Chinese typesetting engine in Windows currently.
But MiKTeX can't support upTeX engine still. It's very not convenient that I must install huge TeX Live to do the vertical typesetting.
I hope MiKTeX can support upTeX series engine.

**Comment by edocevoli** [comment]
MiKTeX now includes the requested engines. Please open another issue, if you find issues with `uplatex` and friends.
