### ISSUE TITLE
xelatex won't compile on new installation

### ISSUE THREAD

**Issue by cristin216** [MiKTeX/miktex#861]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I just installed MiKTeX on Windows 10 and tried compiling a basic hello world file:

```
\documentclass{article}
\begin{document}
Hello World
\end{document}
```

I compiled it without problems using pdflatex, but when trying to compile with xelatex it's not successful. I have tried reinstalling miktex and immediately installing all package updates, seemingly without issue. So far I have uninstalled and reinstalled miktex, turned off my antivirus software, and verified that package installation is done on the fly.

Texworks console output:
```
This is XeTeX, Version 3.141592653-2.6-0.999993 (MiKTeX 21.6.28)
entering extended mode
(untitled-1.tex
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-06-18>
(C:\Users\crist\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2021/02/12 v1.4n Standard LaTeX document class
(C:\Users\crist\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo))
(C:\Users\crist\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-xet
ex.def
Sorry, but C:\Users\crist\AppData\Local\Programs\MiKTeX\miktex\bin\x64\miktex-xetex.exe did not succeed.
The log file hopefully contains the information to get MiKTeX going again:
C:\Users\crist\AppData\Local\MiKTeX\miktex\log\miktex-xetex.log

```

The referenced log file is attached. There is no miktex log in the program data file as referenced in the submitting a miktex problem instructions.

[miktex-report.zip](https://github.com/MiKTeX/miktex/files/6741691/miktex-report.zip)

**Comment by edocevoli** [comment]
It works for me:

```sh
This is XeTeX, Version 3.141592653-2.6-0.999993 (MiKTeX 21.6.28)
entering extended mode
(test.tex
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-06-18>
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2021/02/12 v1.4n Standard LaTeX document class
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo))
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-xetex.
def ())
No file test.aux.
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/base\ts1cmr.fd) [1]
(test.aux) )
Output written on test.pdf (1 page).
Transcript written on test.log.
```

**Comment by edocevoli** [comment]
The log file indicates that `cmd.exe` could not be found. Hope this info helps you to investigate the issue.
