### ISSUE TITLE
Auto-Install package__doc by file name

### ISSUE THREAD

**Issue by edocevoli** [MiKTeX/miktex#863]
This issue separated from #844:

There seems to be a slight issue if the manual does not have the same name as the package, though.
Neither texdoc --view scrguide nor texdoc --view circuitikzmanual trigger the installation of the appropriate __doc package (koma-script__doc and circuitikz__doc, respectively).

**Comment by ryhan1200** [comment]
زمینه مطالعاتی: صنعت طیور سالیان گذشته پیشرفت قابل توجهی داشته و هزینه تامین مواد خوراکی، عمده هزینه این صنعت را به خود اختصاص داده است. در چنین شرایطی، ارزیابی منابع جدید و گوناگون مواد خوراکی، ضروری به نظر می¬رسد. هدف: این پژوهش با هدف بررسی اثرات افزودن پودرهسته¬خرما با و بدون آنزیم روابیو بر عملکرد رشد، صفات لاشه و فراسنجه¬های بیوشیمیایی سرم خون انجام شد. روش کار: آزمايش با استفاده از 160 قطعه جوجه گوشتی یک روزه سویه راس 308  در قالب طرح کاملا تصادفی با 4 تیمار و 4 تکرار و تعداد 10 قطعه جوجه در هر تکرار انجام گرفت. تیمارهاي آزمايشي شامل دو سطح آنزیم (صفر و 05/0 درصد) و 2 سطح هسته خرما (صفر، 5 درصد) بودند. جیره هاي¬غذایی در فاصله زمانی 1-21روزگی و  42-22 روزگی بر اساس احتیاجات توصیه ¬شده تنظیم شد. صفات عملکردی شامل افزایش وزن، خوراک مصرفی و ضریب تبدیل خوراک به صورت هفتگی اندازه گیری شدند. در پايان دوره آزمايشي، تعداد 2 پرنده از هر تكرار انتخاب و براي تجزيه لاشه كشتار شد. همچنين تعداد 2 پرنده از هر تكرار انتخاب و از سياهرگ گردني خونگيري و متابولیت¬های خونی توسط کیت¬های بیوشیمیایی اندازه¬گیری شدند. نتایج: نتایج نشان داد که پودر هسته خرمای مورد آزمایش دارای 21/6 درصد پروتئین خام و 4/19 درصد فیبر خام بودند.  جیره حاوی هسته خرما تاثیری بر عملکرد رشد جوجه های گوشتی در دوره آغازین نشان نداد ولی در دوره رشد سبب کاهش افزایش وزن شد (05/0>p). همچنین در کل دوره پرورش جوجه های تغذیه شده با جیره حاوی5 درصد پودر هسته خرما  مصرف خوراک پایین و از رشد کمتری نسبت به شاهد برخوردار بودند (05/0>p) و افزایش ضریب تبدیل خوراک آنها تمایل به معنی داری نشان داد (065/0=p). افزودن آنزیم به جیره غذایی تاثیر معنی داری بر صفات عملکردی نشان نداد اما موجب بهبود درصد وزنی لاشه شد (05/0>p). وزن سنگدان، پیش معده و قلب در جوجه¬های تغذیه شده با جیره حاوی پودر هسته خرما بیشتر از مقدار مربوط به گروه شاهد بود.  کلسترول، آلبومین، پروتئین کل، گلوکز، تری گلیسیرید سرم خون تحت تاثیر جیره های آزمایشی قرار نگرفت. نتیجه گیری نهایی: استفاده از پودر هسته خرما به میزان 5 درصد جیره غذایی سبب کاهش عملکرد جوجه های گوشتی می شود و  افزودن آنزیم تجاری روابیو سبب بهبود اثر منفی هسته خرما بر عملکرد رشد جوجه های گوشتی نشد.

**Comment by ryhan1200** [comment]
زمینه مطالعاتی: صنعت طیور سالیان گذشته پیشرفت قابل توجهی داشته و هزینه تامین مواد خوراکی، عمده هزینه این صنعت را به خود اختصاص داده است. در چنین شرایطی، ارزیابی منابع جدید و گوناگون مواد خوراکی، ضروری به نظر می¬رسد. هدف: این پژوهش با هدف بررسی اثرات افزودن پودرهسته¬خرما با و بدون آنزیم روابیو بر عملکرد رشد، صفات لاشه و فراسنجه¬های بیوشیمیایی سرم خون انجام شد. روش کار: آزمايش با استفاده از 160 قطعه جوجه گوشتی یک روزه سویه راس 308  در قالب طرح کاملا تصادفی با 4 تیمار و 4 تکرار و تعداد 10 قطعه جوجه در هر تکرار انجام گرفت. تیمارهاي آزمايشي شامل دو سطح آنزیم (صفر و 05/0 درصد) و 2 سطح هسته خرما (صفر، 5 درصد) بودند. جیره هاي¬غذایی در فاصله زمانی 1-21روزگی و  42-22 روزگی بر اساس احتیاجات توصیه ¬شده تنظیم شد. صفات عملکردی شامل افزایش وزن، خوراک مصرفی و ضریب تبدیل خوراک به صورت هفتگی اندازه گیری شدند. در پايان دوره آزمايشي، تعداد 2 پرنده از هر تكرار انتخاب و براي تجزيه لاشه كشتار شد. همچنين تعداد 2 پرنده از هر تكرار انتخاب و از سياهرگ گردني خونگيري و متابولیت¬های خونی توسط کیت¬های بیوشیمیایی اندازه¬گیری شدند. نتایج: نتایج نشان داد که پودر هسته خرمای مورد آزمایش دارای 21/6 درصد پروتئین خام و 4/19 درصد فیبر خام بودند.  جیره حاوی هسته خرما تاثیری بر عملکرد رشد جوجه های گوشتی در دوره آغازین نشان نداد ولی در دوره رشد سبب کاهش افزایش وزن شد (05/0>p). همچنین در کل دوره پرورش جوجه های تغذیه شده با جیره حاوی5 درصد پودر هسته خرما  مصرف خوراک پایین و از رشد کمتری نسبت به شاهد برخوردار بودند (05/0>p) و افزایش ضریب تبدیل خوراک آنها تمایل به معنی داری نشان داد (065/0=p). افزودن آنزیم به جیره غذایی تاثیر معنی داری بر صفات عملکردی نشان نداد اما موجب بهبود درصد وزنی لاشه شد (05/0>p). وزن سنگدان، پیش معده و قلب در جوجه¬های تغذیه شده با جیره حاوی پودر هسته خرما بیشتر از مقدار مربوط به گروه شاهد بود.  کلسترول، آلبومین، پروتئین کل، گلوکز، تری گلیسیرید سرم خون تحت تاثیر جیره های آزمایشی قرار نگرفت. نتیجه گیری نهایی: استفاده از پودر هسته خرما به میزان 5 درصد جیره غذایی سبب کاهش عملکرد جوجه های گوشتی می شود و  افزودن آنزیم تجاری روابیو سبب بهبود اثر منفی هسته خرما بر عملکرد رشد جوجه های گوشتی نشد.

**Comment by edocevoli** [comment]
This has been fixed in 21.7.
