### ISSUE TITLE
MiXTeK Silent Installation

### ISSUE THREAD

**Issue by PhilippeBIOT** [MiKTeX/miktex#876]
Hi , 
I try to install MiKteK with Silent Installation (without any windows or popup) , but i don't find the argument in line command.

Here my command 👍 
 .\setup-4.2-x64.exe --install-from-local-repository --local-package-repository="C:\Users\X489615\Desktop\MikTex\MiKTeX_loval_Repository\" --user-install="C:\Program Files\MiKTeX" --unattended.

Thx.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by edocevoli** [comment]
See https://docs.miktex.org/manual/miktexsetup.html
