### ISSUE TITLE
Please make MikTeX suitable for execution on Debian 10

### ISSUE THREAD

**Issue by dcremonini** [MiKTeX/miktex#878]
This is a feature request.

The procedure
https://miktex.org/howto/install-miktex-unx

`# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
`
stops immediately with the error message:

E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation

**Comment by edocevoli** [comment]
This is not MiKTeX related. Seems you need to install gpg.
