### ISSUE TITLE
how to update Miktex version in Mac or Linux 

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#88]
it seems on windows , the main Miktex app version can update just simply apply the update option. but on Mac or linux , the main Miktex version is far lag behind than the windows version, How can I update and keep abreast with the latest version .

**Comment by edocevoli** [comment]
New MiKTeX binaries for Mac and Linux will be made available from time to time (say, 6 times a year).

#### Mac

If a new disk image (`.dmg`) is available, you can use it to reinstall the executables. Your MiKTeX configuration will not be affected.

#### Linux

You get new MiKTeX executables via your package management system. Either automatically, or manually:

```
sudo apt-get update
sudo apt-get upgrade miktex
```
