### ISSUE TITLE
MikTeX and pdfx generate error after update

### ISSUE THREAD

**Issue by Baspla** [MiKTeX/miktex#883]
Hi,

I'm creating this Issue out of the discussion linked at the end, because I also came across it and couldn't find a solution here or anywhere else.
Im using MikTeX updated to the newest version (21.6.28), TexStudio and Windows 10 Pro, 64-bit, Build: 19042.1110, Version 20H2.
Documents that compiled before the update now produce the error:

Missing \begin{document}. \includexmp{\xmp@template} in line 2855 of pdfx.sty 

consistently.
This is also described by Nocm in the referenced discussion.
I have checked the files for non UTF-8 characters that seem to be known to produce this problem, but to no avail.

I have attached no logs yet, as the error seems to be easily reproducable and theres some personal information in there, however i can provide them if needed.

Thanks in advance!

### Discussed in https://github.com/MiKTeX/miktex/discussions/875

<div type='discussions-op-text'>

<sup>Originally posted by **nocm** July 17, 2021</sup>
Hi,

after an update to the latest version of MikTeX I can't generate an correct PDF/A with MikTeX, Xetex and pdfx. I'm getting the following error
`Missing \begin{document}. \includexmp{\xmp@template}`

Here is a minimal example which does not work and produced the error at my side

<pre>
\documentclass[a4paper, 12pt]{article}

\usepackage[a-1b]{pdfx}

\begin{document}
Hello, World!
\end{document}
</pre>

And the output, which will be normally generated into the file pdfa.xmpi is generated into the pdf file. I attached the pdf and log file.

[Namenlos-1.log](https://github.com/MiKTeX/miktex/files/6835064/Namenlos-1.log)
[Namenlos-1.pdf](https://github.com/MiKTeX/miktex/files/6835065/Namenlos-1.pdf)

Current Version MikTeX: 21.6.28
OS: Windows 7 Professional, 64-bit, Service Pack 1, build 7601

Thanks</div>

**Comment by edocevoli** [comment]
Thank you. This seems to is a LaTeX package issue. This issue tracker covers MiKTeX source code bugs. That is, there's nothing we can do to fix the issue.
