### ISSUE TITLE
Standalone install : Database Locked

### ISSUE THREAD

**Issue by PhilippeBIOT** [MiKTeX/miktex#884]
Hello,
I made a standalone install with this commande Line =>
 .\miktexsetup_standalone.exe install  --local-package-repository="MiKTeX_loval_Repository" --user-install="C:\Program Files\MiKTeX"
After Installation i launch the MiKteX Console. i've got this Error ==> https://prnt.sc/1h3qjpv

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by edocevoli** [comment]
The message indicates that another MiKTeX program is active. Just wait a little bit and try again later.
