### ISSUE TITLE
latexmk Can't spawn cmd.exe

### ISSUE THREAD

**Issue by SGrosse-Holz** [MiKTeX/miktex#885]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

On a fresh install of MiKTeX (on Windows 10), calling latexmk with the -pv option to start a previewer aborts with the error message 'Can't spawn "cmd.exe"'.

This is caused by a system() call in line 10032 of latexmk.pl. The issue seems to be that MiKTeX's latexmk.exe calls that script with PATH set to just the miktex/bin/x64 folder, such that obviously it cannot find cmd.exe in C:\Windows\system32. I confirmed this by printing the PATH from the latexmk.pl script.

I'm attaching a screenshot showing latexmk -pv throwing this error when called via MiKTeX's executable, but working fine when calling the .pl script directly (in which case PATH is inherited from the calling shell, i.e. includes system32).

The problem is resolved by adding the line
```(pl)
$ENV{PATH} .= ";C:/WINDOWS/system32";
```
to latexmk.pl, but this seems like a suboptimal solution to me.

Since I suspect that many other people would have this issue if it was generic, I would be happy to accept that something is wrong with my setup, but as mentioned it is a fresh install (since that was the first thing I tried), and the latexmk script itself is working fine, as shown on the screenshot.

Would be very happy if someone could figure out what's going wrong here. As mentioned I could resolve the actual problem, but only by editing the original script, so this shouldn't be the final solution.

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6899962/miktex-report.txt)
![Screenshot](https://user-images.githubusercontent.com/38474456/127479702-f7da2b6f-6e33-4420-9347-4531edfdfef8.png)

GitHub won't accept .tex files, but the test.tex used in the screenshot contains just the following:
```(tex)
\documentclass{article}
\begin{document}
Test
\end{document}
```

**Comment by edocevoli** [comment]
It works for me:

```
> latexmk -pdf -pv test.tex
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 29 May 2021, version: 4.74b.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'test.tex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "test.tex"'
------------
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.7)
entering extended mode
(test.tex
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-07-12>
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2021/02/12 v1.4n Standard LaTeX document class
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo))
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-pdftex
.def) (test.aux) [1{C:/Users/cs/AppData/Local/MiKTeX/pdftex/config/pdftex.map}]
 (test.aux) )<C:/Users/cs/AppData/Local/Programs/MiKTeX/fonts/type1/public/amsf
onts/cm/cmr10.pfb>
Output written on test.pdf (1 page, 12104 bytes).
Transcript written on test.log.
Latexmk: Examining 'test.log'
=== TeX engine is 'pdfTeX'
Latexmk: Log file says output to 'test.pdf'
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'test.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "test.tex"'
------------
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.7)
entering extended mode
(test.tex
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-07-12>
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/base\article.cls
Document Class: article 2021/02/12 v1.4n Standard LaTeX document class
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo))
(C:\Users\cs\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-pdftex
.def) (test.aux) [1{C:/Users/cs/AppData/Local/MiKTeX/pdftex/config/pdftex.map}]
 (test.aux) )<C:/Users/cs/AppData/Local/Programs/MiKTeX/fonts/type1/public/amsf
onts/cm/cmr10.pfb>
Output written on test.pdf (1 page, 12104 bytes).
Transcript written on test.log.
Latexmk: Examining 'test.log'
=== TeX engine is 'pdfTeX'
Latexmk: Log file says output to 'test.pdf'
Latexmk: All targets (test.pdf) are up-to-date
------------
Running 'start start  "test.pdf"'
------------

```

**Comment by edocevoli** [comment]
> The issue seems to be that MiKTeX's latexmk.exe calls that script with PATH set to just the miktex/bin/x64 folder

That's not true.
