### ISSUE TITLE
Setup issue with root directories

### ISSUE THREAD

**Issue by edskev** [MiKTeX/miktex#896]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Today I am installing MikTex on a new work computer via windows 'Software Center'. After I install it, I am told that I should install updates, so I switch to administrator mode and update, after which I am told to close the application, which I do. I then restart the computer (this step makes no difference it turns out), and open MikTex again, at which point I am presented with the following error:
'A MikTex Setup issue has been detected. Root directory #4 covers root directory #2.'
I have tried uninstalling and reinstalling, the same thing happens each time.

LocalAppData:

[findtexmf.log](https://github.com/MiKTeX/miktex/files/6953940/findtexmf.log)
[initexmf.log](https://github.com/MiKTeX/miktex/files/6953941/initexmf.log)
[latex.log](https://github.com/MiKTeX/miktex/files/6953942/latex.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/6953943/miktex-console.log)
[miktex-fc-cache.log](https://github.com/MiKTeX/miktex/files/6953944/miktex-fc-cache.log)
[miktex-makebase.log](https://github.com/MiKTeX/miktex/files/6953945/miktex-makebase.log)
[miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/6953946/miktex-makefmt.log)
[miktex-makemf.log](https://github.com/MiKTeX/miktex/files/6953947/miktex-makemf.log)
[miktex-makepk.log](https://github.com/MiKTeX/miktex/files/6953948/miktex-makepk.log)
[miktex-maketfm.log](https://github.com/MiKTeX/miktex/files/6953949/miktex-maketfm.log)
[miktex-mf.log](https://github.com/MiKTeX/miktex/files/6953950/miktex-mf.log)
[miktex-pdftex.log](https://github.com/MiKTeX/miktex/files/6953951/miktex-pdftex.log)
[miktex-ttf2pk.log](https://github.com/MiKTeX/miktex/files/6953952/miktex-ttf2pk.log)
[mkfntmap.log](https://github.com/MiKTeX/miktex/files/6953953/mkfntmap.log)
[mpmcli.log](https://github.com/MiKTeX/miktex/files/6953954/mpmcli.log)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/6953955/pdflatex.log)

ProgramData:

[initexmf_admin.log](https://github.com/MiKTeX/miktex/files/6953965/initexmf_admin.log)
[miktex-console_admin.log](https://github.com/MiKTeX/miktex/files/6953966/miktex-console_admin.log)
[miktex-fc-cache_admin.log](https://github.com/MiKTeX/miktex/files/6953967/miktex-fc-cache_admin.log)
[mkfntmap_admin.log](https://github.com/MiKTeX/miktex/files/6953968/mkfntmap_admin.log)
[mpmcli_admin.log](https://github.com/MiKTeX/miktex/files/6953969/mpmcli_admin.log)

**Comment by edocevoli** [comment]
Seems that one of the root directories is a sub-directory of another root directory. This is not supported.

**Comment by edskev** [comment]
I'm glad that you know what is wrong, it should make it easy to fix the issue. Would it be possible for you to help fix it? Note that this was not a consequence of my actions, but how MikTex was configured on install. I attach a screenshot of the directories file.
![Screenshot for MikTex](https://user-images.githubusercontent.com/86958095/128707599-786504a8-a426-4146-b712-b43da940cc63.gif)

**Comment by edocevoli** [comment]
You are running in admin mode. Please check while running in non-admin mode.

**Comment by edskev** [comment]
Here's a screenshot in non-admin mode. There are 5 items in the table, to see them all I've placed the extras at the bottom.


![Screenshot for MikTex](https://user-images.githubusercontent.com/86958095/128710073-2684a74c-24b4-47b9-a126-e868160a01e7.gif)

**Comment by edskev** [comment]
Is the the third one and the fifth which are having the conflict?

**Comment by edskev** [comment]
Managed to get help from the University ICT support. Thanks for your help diagnosing the problem!

**Comment by edocevoli** [comment]
> Is the the third one and the fifth which are having the conflict?

Exactly 😃
