### ISSUE TITLE
Texify: Getting version leads to internal error

### ISSUE THREAD

**Issue by estudm** [MiKTeX/miktex#899]
- [ x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I'm using `miktexsetup` on Win10 to create an installation folder, which afterwards gets packed and used on different machines.  

To get the current miktex version I use `texify --version` and parse the output.  

Since some weeks this no longer works, texify exits with an  error. The output is:
```
texify: .....\miktex\windows\build\source\Libraries\MiKTeX\Core\Utils\Utils.cpp:490: internal error
```` 

Last time it worked on 17.07.2021. Since the 20.07.2021 it no longer works.

The mentioned source line got changed lately with 277bf2a5e24410170a17e4bb79cfb9083635e3d8.

**Comment by kalibera** [comment]
I can reproduce the problem with 21.8, with the following stacktrace (which is similar to #931 and #933 and #921):

```
00 0000006b`4ebfb200 00007fff`b361fabd MiKTeX210800_loc!MiKTeX::Locale::Translator::Translator+0xf756
01 0000006b`4ebfb230 00007fff`b3620c25 MiKTeX210800_app!MiKTeX::App::Application::LogWarn+0x1d005
*** WARNING: Unable to verify checksum for C:\Users\tomas\AppData\Local\Programs\MiKTeX\miktex\bin\x64\texify.exe
02 0000006b`4ebfb590 00007ff7`944cf998 MiKTeX210800_app!MiKTeX::App::Application::LogWarn+0x1e16d
03 0000006b`4ebfb6f0 00007fff`b0291080 texify+0x2f998
04 0000006b`4ebfb730 00007fff`b02926b5 VCRUNTIME140_1!_CallSettingFrame_LookupContinuationIndex+0x20 [d:\agent\_work\1\s\src\vctools\crt\vcruntime\src\eh\amd64\handlers.asm @ 98] 
05 0000006b`4ebfb760 00007fff`ba531456 VCRUNTIME140_1!__FrameHandler4::CxxCallCatchBlock+0x115 [d:\agent\_work\1\s\src\vctools\crt\vcruntime\src\eh\frame.cpp @ 1367] 
06 0000006b`4ebfb840 00007ff7`944c7370 ntdll!RcConsolidateFrames+0x6
07 0000006b`4ebff7f0 00007ff7`944c84c4 texify+0x27370
08 0000006b`4ebffe70 00007fff`b9f77034 texify+0x284c4
09 0000006b`4ebffeb0 00007fff`ba4e2651 KERNEL32!BaseThreadInitThunk+0x14
0a 0000006b`4ebffee0 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
