### ISSUE TITLE
Another internal error when trying to install fresh 6466

### ISSUE THREAD

**Issue by awson** [MiKTeX/miktex#9]
In the very end of installation process setup fails with (relevant part of log):
```
extracting files from zhmetrics.tar.lzma...

An error occurred:
  source file: Libraries\MiKTeX\Core\Fndb\FileNameDatabase.cpp
  source line: 276
  message: MiKTeX encountered an internal error.
  info: 
```
`zhmetrics.tar.lzma` itself is good, looks like some metadata are wrong.

**Comment by edocevoli** [comment]
Please describe what you did, i.e., make it possible for us (and future you) to reproduce the bug.

**Comment by awson** [comment]
I've downloaded `setup-2.9.6300-x64.exe` and entire Miktex 6466 from `http://mirrors.mi.ras.ru/CTAN/systems/win32/miktex/tm/packages`, then have started `setup-2.9.6300-x64.exe`, and issued "complete" setup from the local repository. It almost (99%+) completed but finally delivered the error I've reported above.

**Comment by edocevoli** [comment]
I think this is fixed now. Please use the latest installer (`setup-2.9.6406-x64.exe`).

**Comment by awson** [comment]
Thanks!

**Comment by bearpaw** [comment]
Same problem here. May I know where to find the latest installer (`setup-2.9.6406-x64.exe`)?

**Comment by awson** [comment]
Usually you can find it under the `setup` directory in a MikTex mirror. E.g., in the above case it is `http://mirrors.mi.ras.ru/CTAN/systems/win32/miktex/setup/setup-2.9.6406-x64.exe`.

**Comment by bearpaw** [comment]
@awson Thanks very much!
