### ISSUE TITLE
latexmk.exe: The script engine could not be found when compile with texstudio

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/miktex#90]
I just test the latexmk  on miktex , and write a latexmkrc for the compilation . and when I just use the command-line to run latexmk , everything is ok , but when I change my compile engine to latexmk in texstudio , error occurs:
`latexmk.exe: The script engine could not be found. latexmk.exe: Data: scriptEngine="perl.exe"`
I don't install Perl on windows, but command-line can run without complaint.

Ps :latexmk aslo can not work in MaC command-line

**Comment by edocevoli** [comment]
There is no way around it: `latexmk` requires Perl. I don't know what you mean when you say 

>  I just use the command-line to run latexmk , everything is ok 

If `perl.exe` is not available, the MiKTeX version of `latexmk.exe` cannot succeed.

**Comment by qiuzhu** [comment]
I check my perl installation , and find the git include the core perl. It seems the texstudio do not find the path
