### ISSUE TITLE
LaTeX3 Error: File 'UnicodeData.txt' not found.

### ISSUE THREAD

**Issue by masabeslin** [MiKTeX/miktex#901]
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

1. Freshly installed Windows 10 Home
2. Install full MiKTeX, Net Installer, latest version, 21.8
3. Create empty tex file(or with some very basic content, the behavior is always the same)
4. invoke pdflatex on the created file

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6986256/miktex-report.txt)
[Logs.zip](https://github.com/MiKTeX/miktex/files/6986263/Logs.zip)

**Comment by edocevoli** [comment]
Running your test case works for me. Sorry, but at the moment I have not enough info (facts) to work on this issue.

**Comment by masabeslin** [comment]
Do You at least have any sort of advice? I can see this error occasionally appearing online, with no fix proposed. I find it extremely odd that clean Windows 10 installation and clean Miktex installation don´t work out of the box.

**Comment by edocevoli** [comment]
Yes, that's odd. Sorry, I currently have no idea why it is not working for you ☹️
