### ISSUE TITLE
Restore/add mirrors.ustc.edu.cn in package repositories

### ISSUE THREAD

**Issue by taoky** [MiKTeX/miktex#903]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Related issues:
- https://github.com/MiKTeX/miktex/issues/712
- https://github.com/MiKTeX/miktex/issues/859

Hello MiKTeX staff,

I'm from @ustclug, the maintainer of <https://mirrors.ustc.edu.cn>. I have been a user of MiKTeX recently and I find that as an official mirror of CTAN, mirrors.ustc.edu.cn is always not in the list of remote repositories.

Our mirror syncs from `rsync://rsync.dante.ctan.org/CTAN/` every 12 hours (7:58 and 19:58 UTC, for your reference). I have checked the syncing log on server, and I'm sure that all CTAN syncing tasks recently are successful and finished within several minutes. So, I believe that we should not be excluded as an outdated remote when checking (at 6:00 UTC).

I have consulted @Harry-Chen (who submitted issue #712) about this problem and he also doesn't know why <https://mirrors.tuna.tsinghua.edu.cn> was not on MiKTeX list at that time.

It's very appreciated if you can reply this issue, as it could help users in USTC campus and China to get better experience when using MiKTeX. Thank you.

**Comment by edocevoli** [comment]
The last mirror check was at 6:53:33 AM CEST. At that time, mirrors.ustc.edu.cn was one day behind the master repository.

**Comment by taoky** [comment]
> The last mirror check was at 6:53:33 AM CEST. At that time, mirrors.ustc.edu.cn was one day behind the master repository.

OK, I will check that tomorrow (at about 8/19 5:00 UTC), and may consider adjusting the syncing schedule if confirmed.

**Comment by edocevoli** [comment]
I have rescheduled the mirror checks. The new CRON schedule:

```
H 5 * * *
H 7 * * *
H 10 * * *
H 15 * * *
```

Times are CEST. H is a random value.

**Comment by taoky** [comment]
Thank you for the information about mirror checks. I have changed our syncing schedule to `47 8,15,20 * * *` (UTC +8).
