### ISSUE TITLE
MikTeX creates file MIKTEX-UPDATE.TMP which is caught by AppLocker

### ISSUE THREAD

**Issue by TobiBS** [MiKTeX/miktex#91]
I have a problem with MikTeX in correlation with AppLocker. MikTeX is creating a file called C:\USERS\%USERNAME%\APPDATA\LOCAL\TEMP\MIKTEX-UPDATE.TMP during installation and this is caught by AppLocker as an executable at an unsafe location.

This behaviour is discouraged by our IT and hence I have to comply with it. Do you have any ideas, how to overcome this issue?

**Comment by edocevoli** [comment]
It is recommended that you use MiKTeX Console to install updates.

**Comment by edocevoli** [comment]
`miktex-update.tmp` is created by running the MiKTeX update wizard. If you don't run the wizard, the file will not be created.

**Comment by TobiBS** [comment]
Thanks for your reply! Do the command line tools also create the miktex-update.tmp? Because we are not using any GUI tool at all, but only the command line tools miktexsetup and initexmf which are called by PowerShell scripts. But I have to admit that we are still on a version from 2017, so my follow up question is: Does it help to update to the miktexsetup-2.9.6637-x64.zip version in regards to the miktex-update.tmp file?

**Comment by edocevoli** [comment]
The `miktex-update.tmp` is only created when you run the MiKTeX Update Wizard. Usually by clicking the `MiKTeX Update` shortcut in the Windows start menu. The shortcut targets this command:

```
...\copystart ...\miktex-update.exe
```

`copystart` copies `miktex-update.exe` to `miktex-update.tmp` and then starts `miktex-update.tmp`.

**Comment by TobiBS** [comment]
Thanks for the clarification. I had another talk with IT today and indeed it was the Update shortcut, which created the issue. This was not clear to me initially.
