### ISSUE TITLE
Messed up Aux files

### ISSUE THREAD

**Issue by K4rl-M4rx** [MiKTeX/miktex#914]
1. A short checklist
1.1. MiKTeX is up-to-date
Yes, my MiKTeX is newly installed and updated. Current version is 

> miktex is already the newest version (21.6-focal1).

1.2. This is not a known bug

Messed up aux files behaviour. When I am using latexmk with -aux-directory=DIR, the *.fls files are still be considered as an output file not a auxfile. I have noticed in #634, this bug is fixed. But in my case it is not working. 

1.3. MiKTeX installation report

> ReportDate: 2021-08-31 19:40:08
CurrentVersion: 21.6
SetupDate: 2021-08-31 15:43:00
SetupVersion: 21.6
Configuration: Regular
GitInfo: 1dd0ae5 / 2021-06-06 11:29:06
OS: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64
SharedSetup: yes
LinkTargetDirectory: /usr/local/bin
PathOkay: yes
LastUpdateCheckAdmin: 2021-08-31 17:20:33
LastUpdateAdmin: 2021-08-31 17:08:14
LastUpdateDbAdmin: 2021-08-31 17:20:33
LastUpdateCheck: 2021-08-31 17:21:02
LastUpdate: 2021-08-31 17:16:57
LastUpdateDb: 2021-08-31 17:21:02
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: /home/m4rx/.miktex/texmfs/config
Root1: /home/m4rx/.miktex/texmfs/data
Root2: /home/m4rx/.miktex/texmfs/install
Root3: /var/lib/miktex-texmf
Root4: /var/cache/miktex-texmf
Root5: /usr/local/share/miktex-texmf
UserInstall: /home/m4rx/.miktex/texmfs/install
UserConfig: /home/m4rx/.miktex/texmfs/config
UserData: /home/m4rx/.miktex/texmfs/data
CommonInstall: /usr/local/share/miktex-texmf
CommonConfig: /var/lib/miktex-texmf
CommonData: /var/cache/miktex-texmf

1.4. MiKTeX history
I don't know where are the log files in ubuntu(WSL2). 

Besides, my MWE is simple

> \documentclass{article}
\usepackage{amsmath}
\begin{document}
    Hello, world!
\end{document}

**Comment by edocevoli** [comment]
I was not able to reproduce this, i.e., running your MWE shows that Aux files are not messed up.

**Comment by K4rl-M4rx** [comment]
Maybe more info can help?

I put above MWE(test.tex) in ~/test/ folder. And I do this 

>  latexmk -auxdir=./temp -outdir=./out test.tex

Then in the ~/test/out/ folder there is test.fls.

And the info in my terminal says

```
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 29 May 2021, version: 4.74b.
Latexmk: making output directory './out'
Latexmk: making auxiliary directory './temp'
Latexmk: applying rule 'latex'...
Rule 'latex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'test.tex'
------------
Run number 1 of rule 'latex'
------------
------------
Running 'latex  -recorder -output-directory="out" -aux-directory="temp"  "test.tex"'
------------
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.6)
entering extended mode
(test.tex
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-08-27>
(/home/m4rx/.miktex/texmfs/install/tex/latex/base/article.cls
Document Class: article 2021/02/12 v1.4n Standard LaTeX document class
(/home/m4rx/.miktex/texmfs/install/tex/latex/base/size10.clo))
(/home/m4rx/.miktex/texmfs/install/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/home/m4rx/.miktex/texmfs/install/tex/latex/amsmath/amstext.sty
(/home/m4rx/.miktex/texmfs/install/tex/latex/amsmath/amsgen.sty))
(/home/m4rx/.miktex/texmfs/install/tex/latex/amsmath/amsbsy.sty)
(/home/m4rx/.miktex/texmfs/install/tex/latex/amsmath/amsopn.sty))
(/home/m4rx/.miktex/texmfs/install/tex/latex/l3backend/l3backend-dvips.def)
(/home/test/temp/test.aux) [1] (/home/test/temp/test.aux) )
Output written on /home/test/out/test.dvi (1 page, 264 bytes).
Transcript written on /home/test/temp/test.log.
Latexmk: Moving 'temp/test.fls' to 'out/test.fls'
Latexmk: Examining 'temp/test.log'
=== TeX engine is 'pdfTeX'
Latexmk: Log file says output to 'out/test.dvi'
Latexmk: All targets (out/test.dvi) are up-to-date
```

You can see clearly, latexmk move the test.fls from 'temp/test.fls' to 'out/test.fls' in this line:

> Latexmk: Moving 'temp/test.fls' to 'out/test.fls'

So maybe fls file is indeed be considered as an aux file, but eventually be moved to output folder.

**Comment by muzimuzhi** [comment]
@K4rl-M4rx What you encountered was actually a `latexmk` issue (or bug).

I saw your issue when trying to provide some help in texstudio-org/texstudio#2824. Then on 2023-01-05 I reported this issue to `latexmk` maintainer John Collins and on 2023-01-07 John released `latexmk` v4.79 which ships with a fix for default location of fls file:

> Configurably change default location of fls file to aux directory, to match
behavior of recent versions of MiKTeX.
> https://ctan.org/ctan-ann/id/mailman.3001.1673200304.3715.ctan-ann@ctan.org

Now after `latexmk -auxdir=./temp -outdir=./out test.tex`, you will find `test.fls` in aux directory `./temp`.

**Comment by Enivex** [comment]
> Then on 2023-01-05 I reported this issue to `latexmk` maintainer John Collins and on 2023-01-07 John released `latexmk` v4.79 which ships with a fix for default location of fls file:

I'm still only seeing version 4.78 in MiKTeX

**Comment by muzimuzhi** [comment]
@Enivex This time it's indeed a MiKTeX issue. :)

TeX Live has distributed `latexmk` 4.79 two months ago, see https://www.tug.org/svn/texlive?view=revision&revision=65483, while MiKTeX does still distribute 4.78 https://miktex.org/packages/latexmk.  Sorry I was using TeX Live when writing previous comments.

**Comment by Enivex** [comment]
@muzimuzhi I ended up just manually replacing the .pl-file from CTAN, which didn't require much effort, but it's strange that MiKTeX is so far behind.
