### ISSUE TITLE
MikTex Portable doesn't work via CIFS / SAMBA

### ISSUE THREAD

**Issue by grossmaul** [MiKTeX/miktex#916]
I'm trying to make MikTex Portable run on a network share which is a CIFS network drive (more precise: NCP Protocol).

But somehow it mixes "\\" and "/" gives me an error:
`Windows API error 1: illegal function.` (German: `Windows API error 1: Unzulässige Funktion.`)

Details:
`path="\\DRIVE\DATA\Software\miktex-portable\texmfs/config\miktex/data/le\"`

But on the local drive it works like a charm!

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
