### ISSUE TITLE
Build fails: cweb/initcommon.c:1110:13: error: format not a string literal and no format arguments

### ISSUE THREAD

**Issue by PHPirates** [MiKTeX/miktex#917]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I'm trying to install MiKTeX 21.8-1 on Arch from the [AUR](https://aur.archlinux.org/packages/miktex/), but compilation fails:

```
[ 19%] Built target miktex-chktex
[ 19%] Building CXX object Libraries/MiKTeX/Web2CEmulation/CMakeFiles/miktex-web2c.dir/w2cemu.cpp.o
[ 19%] Linking CXX shared library ../../../sandbox/miktex/bin/linux-x86_64/libmiktex-web2c.so
[ 19%] Built target miktex-web2c
[ 19%] Building CXX object BuildUtilities/cweb/CMakeFiles/initctangle.dir/initcommon.c.o
/home/thomas/.cache/yay/miktex/src/miktex-21.8/BuildUtilities/cweb/initcommon.c: In function ‘void fatal(const char*, const char*)’:
/home/thomas/.cache/yay/miktex/src/miktex-21.8/BuildUtilities/cweb/initcommon.c:1110:13: error: format not a string literal and no format arguments [-Werror=format-security]
 1110 | if(*s)printf(s);
      |       ~~~~~~^~~
cc1plus: some warnings being treated as errors
make[2]: *** [BuildUtilities/cweb/CMakeFiles/initctangle.dir/build.make:76: BuildUtilities/cweb/CMakeFiles/initctangle.dir/initcommon.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5062: BuildUtilities/cweb/CMakeFiles/initctangle.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: miktex
```

The reason I'm trying to update is because my current installation is broken as well:
`pdflatex: symbol lookup error: /opt/miktex/bin/../lib/libmiktex-app.so.6: undefined symbol: _ZTIN7log4cxx7helpers13ObjectPtrBaseE`  which is caused by an update of some other package, but I don't know which one.

**Comment by edocevoli** [comment]
Thank you. This is not a supported Linux platform, atm. Please consider submitting a PR if you want to get it fixed.

**Comment by Erim24** [comment]
I tried to compile it too on Manjaro (using AUR) and am having the same issue. 
Until recently (MiKTeX 21.3) it was possible to compile and run it. I can't say though if the standard compile flags on Manjaro/Arch were changed afterwards, but it started with the following release of MiKTeX)

I'm aware that Manjaro is not a supported platform either, but I want to share my observations anyways just in case it might help someone to find a fix..

**Comment by PHPirates** [comment]
But where is it compiled with that flag? I cannot find it in the [pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=miktex) nor in this repo (except in harfbuzz `hb.hh` but I doubt that it's that one).

If it's just extra picky on unsafe code, maybe we can try to actually fix these errors.

**Comment by Erim24** [comment]
As far as I know the compile flags are set globally in `/etc/makepkg.conf`. 
I'm using `pamac` to install content from AUR and so far I haven't found a way to overwrite compile flags or set some temporarily. (Besides, since I don't exactly know what implications changing that flag has, so I'm not very eager to change it, especially not globally)
I'll maybe have a further look into the `pkgbuild` syntax to see if there is a way to set it only for MiKTeX on the weekend.

**Comment by Erim24** [comment]
Alright, so I manage to compile MiKTeX by adding `options=('!buildflags')` which technically turns off all compile flags. It seems like a bad workaround, but at least it can be installed.
Hopefully MiKTeX will fix that in the long run as it seems that it becomes a common compile flag for several distributions

**Comment by PHPirates** [comment]
That works for me as well, thanks!

**Comment by PHPirates** [comment]
@Erim24 I emailed the maintainers of the AUR package and they promptly updated the pkgbuild with that change, so now it can be installed again.

**Comment by Erim24** [comment]
Thank you!
I noticed the change in the AUR

**Comment by loh-tar** [comment]
> Thank you. This is not a supported Linux platform, atm. Please consider submitting a PR if you want to get it fixed.

Well, some kind of PR. 
With this patch I got it compile on Arch, without the workaround in the latest PKGBUILD there.

`
--- miktex-21.12/BuildUtilities/cweb/initcommon.c
+++ miktex-21.12/BuildUtilities/cweb/initcommon.c
@@ -1107,7 +1107,7 @@
  fatal(const char*s,const char*t)

 {
+if(*s)puts(s);
-if(*s)printf(s);
 err_print(t);
 history= fatal_message;exit(wrap_up());
 }


--- miktex-21.12/BuildUtilities/cweb/source/common.w
+++ miktex-21.12/BuildUtilities/cweb/source/common.w
@@ -1180,7 +1180,7 @@
 fatal(s,t)
   char *s,*t;
 {
+  if (*s) puts(s);
-  if (*s) printf(s);
   err_print(t);
   history=fatal_message; exit(wrap_up());
 }


--- miktex-21.12/Programs/TeXAndFriends/omega/otps/source/outocp.c
+++ miktex-21.12/Programs/TeXAndFriends/omega/otps/source/outocp.c
@@ -90,7 +90,7 @@
 void
 ctp_abort P1C(string, s)
 {
+  fputs(stderr, s);
-  fprintf(stderr, s);
   exit(EXIT_FAILURE);
 }


--- miktex-21.12/BuildUtilities/cweb/source/cweave.w
+++ miktex-21.12/BuildUtilities/cweb/source/cweave.w
@@ -1784,7 +1784,7 @@
 print_cat(c) /* symbolic printout of a category */
 eight_bits c;
 {
+  puts(cat_name[c]);
-  printf(cat_name[c]);
 }

 @ The token lists for translated \TEX/ output contain some special control
`
What puzzled me is that _../cweb/initcommon.c_ seems to be a configured version of _../cweb/source/common.w_ but it isn't configured at compile time(?)

**Comment by PHPirates** [comment]
If that works, could be helpful if you would submit that as an actual PR.

**Comment by loh-tar** [comment]
Let's see what @edocevoli  says. 
I had hoped I could avoid to go the long way by fork/checkout/patch/commit/push/fill-PR
