### ISSUE TITLE
Xelatex and pstricks generate no output in Linux Mint

### ISSUE THREAD

**Issue by nocm** [MiKTeX/miktex#92]
<h1>Steps to reproduce</h1>

1. Create a document which uses ps-tricks

<pre><code>\documentclass[10pt,a4paper]{article}
\usepackage{pst-barcode}
\begin{document}
    \begin{pspicture}[showgrid=false](0,0)
        \psbarcode{BCD}{}{qrcode}
        \psframe[linewidth=1pt,%
        framearc=0.2,%
        fillstyle=none]%
        (0,0)(2.8,2.8)
    \end{pspicture}
\end{document}</code></pre>

2. Create the document using Xelatex with Linux and Windows version of MiKTeX

<h2>Expected Result</h2>

Both versions creating the same document.

<h2>Actual Result</h2>

Windows version of Xelatex creates a document with a QRCode and a frame, the Linux version creates only an empty document.

<h2>Version</h2>

<b>Linux version</b>

<pre><code>MiKTeX-XeTeX 2.9.6609 (0.99999) (MiKTeX 2.9.6600)
(C) 1994-2008 by SIL International, (C) 2009-2012 by Jonathan Kew, (C) 2010-2012 by Han The Thanh, (C) 2012-2013 by Khaled Hosny
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.47.0; using libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3
compiled with expat version 2.1; using expat_2.1.0
compiled with fontconfig version 2.11.94; using 2.11.94
compiled with freetype2 version 2.6.1; using 2.6.1
compiled with graphite2 version 1.3.10; using 1.3.10
compiled with harfbuzz version 1.6.3; using 1.6.3
compiled with icu version 55.1; using 55.1
compiled with jpeg version 80.0
compiled with liblzma version 50010000; using 50010000
compiled with libpng version 1.2.54; using 1.2.54
compiled with MiKTeX Application Framework version 2.6592; using 2.6592
compiled with MiKTeX Core version 5.6612; using 5.6612
compiled with MiKTeX Archive Extractor version 1.6300; using 1.6300
compiled with MiKTeX Package Manager version 1.6584; using 1.6584
compiled with openssl version OpenSSL 1.0.2g  1 Mar 2016; using OpenSSL 1.0.2g  1 Mar 2016
compiled with poppler version 0.60.1
using teckit version 2.4
compiled with uriparser version 0.8.4
compiled with zlib version 1.2.8; using 1.2.8
</code></pre>

<b>Windows version</b>
<pre><code>MiKTeX-XeTeX 2.9.6634 (0.99999) (MiKTeX 2.9.6630 64-bit)
(C) 1994-2008 by SIL International, (C) 2009-2012 by Jonathan Kew, (C) 2010-2012 by Han The Thanh, (C) 2012-2013 by Khaled Hosny
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.56.1; using libcurl/7.56.1 WinSSL
compiled with expat version 2.2; using expat_2.2.0
compiled with fontconfig version 2.12.6; using 2.12.6
compiled with freetype2 version 2.8.1; using 2.8.1
compiled with graphite2 version 1.3.10; using 1.3.10
compiled with harfbuzz version 1.6.3; using 1.6.3
compiled with icu version 60.1; using 60.1
compiled with jpeg version 9.2
compiled with liblzma version 50020032; using 50020032
compiled with libpng version 1.6.34; using 1.6.34
compiled with libressl version LibreSSL 2.5.3; using LibreSSL 2.5.3
compiled with MiKTeX Application Framework version 2.6636; using 2.6636
compiled with MiKTeX Core version 5.6636; using 5.6636
compiled with MiKTeX Archive Extractor version 1.6300; using 1.6300
compiled with MiKTeX Package Manager version 1.6584; using 1.6584
compiled with poppler version 0.60.1
using teckit version 2.4
compiled with uriparser version 0.8.4
compiled with zlib version 1.2.11; using 1.2.11</code></pre>

<b>OS</b>

- Windows 7
- Linux Mint 18.3

**Comment by edocevoli** [comment]
Thank you, this has been fixed, Please upgrade to MiKTeX 2.9.6650.
