### ISSUE TITLE
Remove unsafe uses of format functions

### ISSUE THREAD

**Issue by Erim24** [MiKTeX/miktex#922]
Compiling MiKTeX fails when using the compile flag `-Werror=format-security`.
This is due to an unsafe use of format functions as `printf()`.
By a relatively save refactor of `printf(foo);` into `printf("%s", foo);` a whole class of security issues can be avoided. (See [fedora wiki](https://fedoraproject.org/wiki/Format-Security-FAQ))

Therefore, I suggest to add a refactor to the roadmap to eliminate these potential security issues.

**Comment by edocevoli** [comment]
Thank you. This seems to be an upstream issue. Please report it to the cweb maintainers.
