### ISSUE TITLE
Handle competing fontconfig installation

### ISSUE THREAD

**Issue by zomborid** [MiKTeX/miktex#923]
Issue #629 mentioned MiKTeX failing to open fontconfig on Windows.
The error stated `Fontconfig error: Cannot load default config file`.
Reinstall of MiKTeX did not resolve it.

I found a strange env variable: `FONTCONFIG_FILE="C:\Windows\fonts.conf"`
Since the file did not exist I tried to delete the env variable, and magically latex works now.

The **probable cause is** that I installed **MiniTool MovieMaker** and **OBS Studio**, and one of them created the erroneous variable.

(Since comments on the original issue are not allowed, I opened a new one to document my finds. This issue can be closed I think.)

**Comment by edocevoli** [comment]
Thank you for the info. Maybe this should be logged.
