### ISSUE TITLE
Unsafe uses of format functions

### ISSUE THREAD

**Issue by Erim24** [MiKTeX/miktex#924]
Thank you. This seems to be an upstream issue. Please report it to the cweb maintainers.

_Originally posted by @edocevoli in https://github.com/MiKTeX/miktex/issues/922#issuecomment-917717396_

I checked with [cweb](https://github.com/ascherer/cweb) and there no file called `initcommon.c` is present.
Furthermore, `initcommon.c` does not state the authors, nor any license, nor does it say that it's part of CWEB as the other files in CWEB do. Therefore, it seems to me as if it is either part of MiKTeX or some other project.
CWEB (at least the versions from 4.0 upwards) seem to use the safe way of invoking `printf`-functions.
Therefore, it seems to me as if it might be an issue within MiKTeX.

I also could find unsafe uses of these functions in the file `miktex/Programs/TeXAndFriends/omega/otps/source/outocp.c`. According to the file it's part of the web2c project, I checked with the [upstream sources](https://www.tug.org/web2c/). There, it seems that the line that causes the compilation to fail, has been removed a while ago with [revision 1594](https://www.tug.org/svn/texlive/trunk/Build/source/texk/web2c/otps/outocp.c?r1=1485&r2=1594).
So it seems to me that it has been fixed upstream but not in MiKTeX yet.
(If I checked with the wrong upstream please correct me)

PS: I'm sorry to open a new issue, unfortunately, the previous one was locked so that I couldn't answer there.
PPS: edited the post to correctly include the links

**Comment by edocevoli** [comment]
Thank you. As I said before, cweb is not maintained by me. Because it works for my builds, I am not going to fix this issue. Please feel free to submit a pull request with your modifications.

**Comment by Erim24** [comment]
Just two more things:

1. initcommon.c seems not to be part of CWEB but a wrapper of MiKTeX. However, I will have a look and try to file a pull request.
2. It seems that the updates of the upstream `miktex/Programs/TeXAndFriends/omega/otps/` were last fetched in 2006 and since then upstream included quite some changes which are missing here. So I was wondering which upstream base you use and which version is included in MiKTeX?
