### ISSUE TITLE
PATH instead of Path (Windows)

### ISSUE THREAD

**Issue by bach-c** [MiKTeX/miktex#925]
On Windows somehow the environment PATH is created, but nowadays Windows 10 has here some new case sensitivity feature and PATH overwrites the Path variable of the system. For example it is not possible to use minted.

**Comment by edocevoli** [comment]
Sorry, this does not seem to be a valid bug report.
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by bach-c** [comment]
I thought a report would be helpful for you, but I can just use an older version, thank you. :)

**Comment by edocevoli** [comment]
> I thought a report would be helpful for you

No, this report was no helpful. In the future, if you write a bug report:

- say what you did
- say what you expected
- say what instead happened

It's a simple recipe. Try to get familiar with it.
