### ISSUE TITLE
PATH instead of Path

### ISSUE THREAD

**Issue by bach-c** [MiKTeX/miktex#926]
On Windows somehow the environment variable PATH is created, but nowadays Windows 10 has here some new case sensitivity feature and PATH overwrites the Path variable of the system. For example it is not possible to use minted.

Steps to reproduce: 
1. I did use MikTex 21.6
2. I expected to have an correct Path in my Enviorment
3. The Path is broken because of an additional PATH variable introduced by MikTex (see test code below)
4. I switched back to an older version and it works fine again.

Test Latex File
```
\documentclass[]{article}
\begin{document}
Output lands in test.txt
\input "|set>test.txt"
\end{document}
```

To compile this file you have to call pdflatex with the shell-escape flag.
Now look into test.txt. There should be Path= once and no PATH=.

**Comment by edocevoli** [comment]
Environment variable names are not case sensitive (on Windows). So I don't see a problem here.

**Comment by bach-c** [comment]
The reason for me reporting this is that with this behavior it is not possible to run any tools on the Path. Here is a example code that tries to start cmd.exe:

Test Latex File that does not work:
```
\documentclass[]{article}
\begin{document}
Output lands in test.txt
\input "|start cmd.exe"
\end{document}
```

Test Latex File that works:
```
\documentclass[]{article}
\begin{document}
Output lands in test.txt
\input "|start %ComSpec%"
\end{document}
```

My goal is to generate Latex code with a script.

**Comment by ghertlei** [comment]
Why is this closed ?
#1089 has a detailed code analysis of the bug. It should be reopened.

**Comment by bach-c** [comment]
I don't know. I have still this problem and it is very annoying.

**Comment by ThorbenKaufmann** [comment]
Yes, it is in deed!
I mean, really... if there is a problem with the installation you can't simply kick it!
Have the same issue here.
And even if this was a problem generated by Windows (thanks to the gods there is more out there than f*** Windows!), you deploy a SW for a platform and not the other way round.
