### ISSUE TITLE
Can't check installed milestone via elevated script for current-user install

### ISSUE THREAD

**Issue by teknowledgist** [MiKTeX/miktex#927]
- [x ] I have read and acknowledged this HOWTO article:  

I have a script that must run elevated and needs to check the MiKTeX installed milestone for a `--shared=no` installation.  The problem is, it cannot do that because:

    initexmf.exe --admin --report

fails with: `Option --admin only makes sense for a shared MiKTeX setup`. However:

    initexmf.exe --report

fails with: `initexmf: security risk: Running with elevated privileges`

So, I seem to be stuck.  What are my options?  Can this be fixed?

**Comment by edocevoli** [comment]
The warning is written to `stderr`. So this works on Windows:

```
initexmf --report 2>nul
```
