### ISSUE TITLE
Run MiKTeX portable from a CIFS network drive not possible

### ISSUE THREAD

**Issue by grossmaul** [MiKTeX/miktex#928]
Hi there,
I'm trying to run MiKTeX portable from a CIFS location in the network and get the following error:

```
Windows API error 1: Illegal function.

path="\\SHARE\miktex-portable\texmfs/config\miktex/data/le\"
```
Or in german (thats the current language here)
```
Windows API error 1: Unzulässige Funktion.

path="\\SHARE\miktex-portable\texmfs/config\miktex/data/le\"
```
It seems like its mixing up the `/`s and `\`s. I also need to mention that the CIFS path is located on a Linux machine.

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

#### Checklist:
- [x] Current version of MiKTeX (MiKTeX Console 4.4)
- [x] Not a known bug (couldn't find anything online)
- [x] No MiKTeX installation report possible due to not being able to run it in that location. Error output:
```
initexmf: security risk: running with elevated privileges
Unzulässige Funktion.

Function: ReadDirectoryChangesW
Result: 1
Data: path="\\SHARE\miktex-portable\texmfs/config\miktex/data/le\"
Source: Libraries\MiKTeX\Core\FileSystemWatcher\win\winFileSystemWatcher.cpp:150
Windows API error 1: Unzulässige Funktion.

Info: path="\\SHARE\miktex-portable\texmfs/config\miktex/data/le\"
Source: Libraries\MiKTeX\Core\FileSystemWatcher\win\winFileSystemWatcher.cpp
Line: 150

Sorry, but "MiKTeX Configuration Utility" did not succeed.
log4cxx: No appender could be found for logger (initexmf).
log4cxx: Please initialize the log4cxx system properly.
```
- [x] No MiKTeX history present

**Comment by edocevoli** [comment]
Thank you. Seems that your setup is not compatible with MiKTeX requirements. I will check to see if I can update the documentation (system requirements). Something like: MiKTeX requires that the data directory is on a Windows drive.

**Comment by grossmaul** [comment]
What a nice way to say "It's not a bug, its a feature" :D
