### ISSUE TITLE
autosp binary corrupt?

### ISSUE THREAD

**Issue by rdtennent** [MiKTeX/miktex#929]
Applying autosp to C:\Program Files\MiKTeX\doc\support\autosp\quod2.aspc
generates quod2.tex that has \input musixplt replaced by \input musixjt  for some reason.  This doesn't happen on TeXLive.

**Comment by edocevoli** [comment]
I was not able to reproduce this. This is the beginning of `quod2.tex`:

```tex
%  Generated by autosp (2021-01-07).
\input musixtex
\input musixplt
\input soul.sty
\sodef{\so}{}{0.15em}{0.5em}{0.5em}
\input musixsty
\input musixps
``
