### ISSUE TITLE
xelatex: xdvipdfmx fails when \setmainfont{CMU Serif} is used

### ISSUE THREAD

**Issue by alllexx88** [MiKTeX/miktex#93]
`xelatex` currently fails to create a pdf file when `xdvipdfmx` tries to load a Type 1 font and meets "seac" command for accented characters.

`xdvipdfmx` log tail:
```
$ xdvipdfmx -E -vv draft.xdv
...
(CID:D:/Full_TeX/texmf/fonts/type1/public/cm-unicode/cmunrm.pfb[UEVQCQ+CMUSerif-Roman][CIDFontType0]
xdvipdfmx:warning: Obsolete four arguments of "endchar" will be used for Type 1 "seac" operator.
xdvipdfmx:fatal: This font using the "seac" command for accented characters...

Output file removed.
```

An MWE:
```
\documentclass{article}
\usepackage{fontspec}

\setmainfont{CMU Serif}

\begin{document}
Ð
\end{document}
```

As a suggested workaround (taken from [here](https://cygwin.com/ml/cygwin/2016-06/msg00208.html)), one can comment out type1 font dirs from `fontconfig/config/localfonts.conf` and rebuild fontconfig cache with `miktex-fc-cache  -sv`. This gets the MWE built fine.

Also, here's `xetex` devs reply on this issue (from https://sourceforge.net/p/xetex/bugs/131/):

> Type1 fonts as native fonts are almost useless.
> They can be used only in cases with very simple
> encodings. Please hide them from fontconfig.

Regards,
Alex

**Comment by edocevoli** [comment]
I cannot reproduce the issue. Running your minimal test case gives me:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
!
! The font "CMU Serif" cannot be found.
!
! See the fontspec documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.4 \setmainfont{CMU Serif}

?
```

**Comment by edocevoli** [comment]
I have installed the missing font and it now works, i.e., I can compile your test case without any problems.
[93.pdf](https://github.com/MiKTeX/miktex/files/1800461/93.pdf)

**Comment by alllexx88** [comment]
Sorry, I accidentally posted a wrong MWE. Here's the correct one:
```
\documentclass{article}

\usepackage{fontspec}

\setmainfont{CMU Serif}

\begin{document}
Україна
\end{document} 
```

Here's WinEdt log as a proof: https://pastebin.com/tmn9teKi

And here's full xdvipdfmx log: https://pastebin.com/pW1PJ9JA

**Comment by alllexx88** [comment]
@edocevoli I've managed to narrow down the test case to a single-symbol `document` contents:
```
\documentclass{article}

\usepackage{fontspec}

\setmainfont{CMU Serif}

\begin{document}
а
\end{document}
```

`xdvipdfmx` seems to choke on Cyrillic `а`. The logs are basically the same as from above.

**Comment by u-fischer** [comment]
I get the error too.  Adding `\XeTeXtracingfonts=1`, and using `xelatex --no-pdf` and `xdvipdfmx -vv` for the compilation one can see that the source of the problem is that xetex and xdvipdfmx is using the type1 version of the font:

         /MiKTeX/fonts/type1/public/cm-unicode/cmunrm.pfb

Loading the font by file name with `\setmainfont{cmunrm.otf}` works fine.

I do have a localfont2.conf with a rejectfont statement. But it seems that xelatex doesn't honor it (anymore?).

~~~~~
<?xml version="1.0"?>
<fontconfig>
<selectfont>
    <rejectfont>
      <glob>C:/Users/XXXX/MikTeX/fonts/type1/*</glob>
    </rejectfont>
  </selectfont>
<!-- REMOVE THIS LINE
<dir>Your font directory here</dir>
<dir>Your font directory here</dir>
<dir>Your font directory here</dir>
     REMOVE THIS LINE -->
</fontconfig>
~~~~~

**Comment by alllexx88** [comment]
@u-fischer Thanks a lot for `rejectfont` hint! It actually works, you just need to recache the fonts with `miktex-fc-cache -sv` command, after editing `localfont2.conf`. Your workaround survives MiKTeX updates, which is great.

Another thing I noticed: it looks vital to use, as you did, direct slashes (`/`), and not backslashes (`\`) in the path patterns.

**Comment by u-fischer** [comment]
After deleting all my old cache files and rebuilding from scratch the rejectfont works again for me too.

**Comment by alllexx88** [comment]
Thought I would share another workaround, specifically for `CMU` fonts. Let's say you want to be sure your file builds on any MiKTeX setup, and you want to use `CMU` for main, sans and mono fonts. In this case, as @u-fischer noticed, you can use font file names, instead of the font name. However, in this case you'll have to also manually list file names for `Bold`, `Italic` and `BoldItalic` fonts. For some fonts it's easy, e.g., for `XITS` font files are named `xits-regular.otf`, `xits-bold.otf` etc., but it's not the case with `CMU`.

Instead of using font names like this
```
\documentclass{article}

\usepackage{fontspec}

\setmainfont{CMU Serif}
\setsansfont{CMU Sans Serif}
\setmonofont{CMU Typewriter Text}

% needed if you use cyrillic symbols
\newfontfamily\cyrillicfont{CMU Serif}
\newfontfamily\cyrillicfontsf{CMU Sans Serif}
\newfontfamily\cyrillicfonttt{CMU Typewriter Text}

\begin{document}
а \textsf{а} \texttt{а}
\end{document}
```

Which fails without the `<rejectfont>` workaround from above, use font file names like this

```
\documentclass{article}

\usepackage{fontspec}

\setmainfont[
    BoldFont={cmunbx.otf},
    ItalicFont={cmunti.otf},
    BoldItalicFont={cmunbi.otf}
]{cmunrm.otf} % {CMU Serif}
\setsansfont[
    BoldFont={cmunsx.otf},
    ItalicFont={cmunso.otf},
    BoldItalicFont={cmunsi.otf}
]{cmunss.otf} % {CMU Sans Serif}
\setmonofont[
    BoldFont={cmuntb.otf},
    ItalicFont={cmunit.otf},
    BoldItalicFont={cmuntx.otf}
]{cmuntt.otf} % {CMU Typewriter Text}

% needed if you use cyrillic symbols
\newfontfamily\cyrillicfont[
    BoldFont={cmunbx.otf},
    ItalicFont={cmunti.otf},
    BoldItalicFont={cmunbi.otf}
]{cmunrm.otf}   % {CMU Serif}
\newfontfamily\cyrillicfontsf[
    BoldFont={cmunsx.otf},
    ItalicFont={cmunso.otf},
    BoldItalicFont={cmunsi.otf}
]{cmunss.otf} % {CMU Sans Serif}
\newfontfamily\cyrillicfonttt[
  BoldFont={cmuntb.otf},
  ItalicFont={cmunit.otf},
  BoldItalicFont={cmuntx.otf}
]{cmuntt.otf} % {CMU Typewriter Text}

\begin{document}
а \textsf{а} \texttt{а}
% some text
\end{document} 
```
Which should work on any MiKTeX setup.
