### ISSUE TITLE
pplrc8r.tfm not found

### ISSUE THREAD

**Issue by rdtennent** [MiKTeX/miktex#930]
When processing a file like 

C:\Program Files\MiKTeX\doc\support\autosp\barsant2.aspc

with musixtex,  the file pplrc8r isn't found.  But kpsewhich reports that it is installed at

C:/Program Files/MiKTeX/fonts/tfm/adobe/palatino

so I think there's an issue with the font map files.

**Comment by edocevoli** [comment]
"... of your stupid restrictions."

Bye
