### ISSUE TITLE
SSL Peer Certificate Error

### ISSUE THREAD

**Issue by marc-chevalier** [MiKTeX/miktex#936]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I ran into the same error as many people, for instance: #935. I quick fixed it by adding the certificate manually, but unlike what it's said in this other issue, I think it's a problem that can (and should) be fixed from Miktex side. It appeared on Ubuntu after an update of ca-certficate. The certificate chain looks like:
```
0 s:CN = api2.miktex.org
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```
but in [the changelog](http://changelogs.ubuntu.com/changelogs/pool/main/c/ca-certificates/ca-certificates_20210119~18.04.2/changelog) we can see
> blacklist expired "DST Root CA X3". 

[Here](https://bugs.launchpad.net/ubuntu/+source/ca-certificates/+bug/1944481) is the reasoning. In particular:
> It seems that some older LetsEncrypt clients have still recently been issuing valid certificates signed by the DST Root CA X3 root

And that might by your problem. Anyway, using a expired (or not trusted) certificate is something that can and should be fixed from Miktex side. A standard certificate chain using Letsencrypt should look like
```
0 s:CN = api2.miktex.org
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

And here, everything is fine since ISRG Root X1 is trusted.

Short, what I suspect you should do: update your letsencrypt client, generate new certificate, enjoy.

**Comment by edocevoli** [comment]
Yes, some root certificates can expire. Please make sure that that your OS is always up-to-date.
