### ISSUE TITLE
Universal installer URL no longer works

### ISSUE THREAD

**Issue by jeroen** [MiKTeX/miktex#942]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

For the past 2 years we have been using this URL [as described here](https://github.com/MiKTeX/miktex/issues/321#issuecomment-496286866) in CI to get the latest miktex:

```
https://miktex.org/download/win/basic-miktex-x64.exe
```

However it is now 404. I can update the download scripts to use `basic-miktex-21.6-x64.exe` but of course that will mean the script will break again some time in the future.

**Comment by edocevoli** [comment]
Well, it works for me:

```
$ curl -Ls https://miktex.org/download/win/basic-miktex-x64.exe | sha256sum
299f2eb278409c672ba38941388c9d9e70182b7b1ba61319bc7128bbb9051a6d *-
```

**Comment by jeroen** [comment]
Ah maybe the problem is just the expired https root cert.

**Comment by jeroen** [comment]
Currently miktex.org does not work on clients on somewhat older operating systems, because there is an expired CA cert included with the cert chain on the miktex.org webserver: https://www.ssllabs.com/ssltest/analyze.html?d=miktex.org&latest

Simply removing that cert form the chain might fix the problem, because most operating systems actually have the current version of that CA cert. However because your webserver includes the expired one, many clients will only look at that one.

**Comment by edocevoli** [comment]
Thank you. I have renewed the certificate. This should eliminate the expired chain. Please try again.

**Comment by jeroen** [comment]
Thanks it works now.
