### ISSUE TITLE
Add option to install a specific (older) version of MiKTeX using miktexsetup

### ISSUE THREAD

**Issue by kalibera** [MiKTeX/miktex#943]
Could there be a  way to install a specific older version of MiKTeX using the miktexsetup installer on Windows?

*Why I need an older version*. Currently I would like to install version 21.6, because version 21.8 has that issue with `texify --version` crashing, which is a problem for R.

*Why using miktexsetup installer*. Because I need an unattended install which would also work in a Windows docker container, ideally the servercore image. I can do an unattended install of an older version using the setup wizard, but it does not work in a docker container servercore image because it needs features that are missing there (OLEDLG.DLL, WINSPOOL.DRV MSIMG32.DLL WININET.DLL). It is still possible to use the setup wizard in docker, but one needs the full server image.

Thanks!
Tomas

**Comment by edocevoli** [comment]
Sorry, but that's not possible. It would be necessary to keep old stuff on CTAN and implementing the suggested option certainly is troublesome. Not worth the effort, I think.
