### ISSUE TITLE
Fragile miktex installation in Continuous Integration (CI)

### ISSUE THREAD

**Issue by dginev** [MiKTeX/miktex#946]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hello! We have been happy to successfully use miktex in continuous integration under Windows for our builds of the latexml project.

Recently we've encountered some fragility (intermittent, but I think worth reporting) where certain builds would fail in miktex installation. The report encountered is the one from your closed issue #855 , and you can examine one specific failed case at this github actions run:

https://github.com/brucemiller/LaTeXML/runs/3809584120#step:6:1324

Rerunning that set of tests a day later succeeds fully, so I suspect this is a bit harder to diagnose and resolve, as it may be happening only in some specific contexts. But I wanted to report we encountered the problem, and also ask if there is a better recommendation for using miktex in continuous integration settings? 

Our current installation recipe can be examined [here](https://github.com/brucemiller/LaTeXML/blob/8d69a963faee77acb6bab33cf116973f0fad1eb3/.github/workflows/windows.yml)

**Comment by edocevoli** [comment]
Thank you for the report. But without more info, I cannot work on this effectively.
