### ISSUE TITLE
After update, console cannot make format files

### ISSUE THREAD

**Issue by gl-utah** [MiKTeX/miktex#952]
- [X] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report

I ran an update using the MiKTeX Console.  Then I ran update again, and got a message something like "needs repair" for, I think, a MiKTeX executable; I did not document this.  Now PDFLaTeX crashes on every file, immediately, producing no output:

     C:\Users\Daddy\Documents\UTILS\moveinst.all>pdflatex Econometrics2toWord
     This is pdfTeX, Version 3.141592653-2.6-1.40.23 (MiKTeX 21.10)
     Sorry, but pdflatex did not succeed.
     The log file hopefully contains the information to get MiKTeX going again:
     C:\Users\Daddy\AppData\Local\MiKTeX\2.9\miktex\log\pdflatex.log
     C:\Users\Daddy\Documents\UTILS\moveinst.all>pdflatex Econometrics2toWord

PDFLaTeX.log reports "the memory dump file could not be found."  I cannot find any .fmt files on my computer.  Rebooting the computer did not help.  I'm running Windows 8.1.

So I opened the MiKTeX Console to manually build the format file.  That failed with:

     GENERAL MIKTEX INFORMATION
     ReportDate: 2021-10-19 13:11:20
     CurrentVersion: 21.10
     SetupDate: 2018-04-03 14:06:00
     SetupVersion: 2.9
     Configuration: Regular
     GitInfo: e92cba5 / 2021-10-04 14:58:03
     OS: Windows 8.1 Pro, 64-bit, build 9600
     SharedSetup: no
     LinkTargetDirectory: C:\Users\Daddy\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
     PathOkay: yes
     LastUpdateCheck: 2021-10-19 11:52:07
     LastUpdate: 2021-10-19 11:48:14
     LastUpdateDb: 2021-10-19 11:52:06
     SystemAdmin: no
     RootPrivileges: no
     AdminMode: no
     Root0: C:\Users\Daddy\AppData\Roaming\MiKTeX\2.9
     Root1: C:\Users\Daddy\AppData\Local\MiKTeX\2.9
     Root2: C:\Users\Daddy\AppData\Local\Programs\MiKTeX 2.9
     UserInstall: C:\Users\Daddy\AppData\Local\Programs\MiKTeX 2.9
     UserConfig: C:\Users\Daddy\AppData\Roaming\MiKTeX\2.9
     UserData: C:\Users\Daddy\AppData\Local\MiKTeX\2.9
     Invokers: explorer

     ERROR DETAILS
     Program: miktex-console
     Source: Programs\MiKTeX\Console\Qt\mainwindow.cpp:1064
     Error: The MiKTeX configuration utility failed for some reason. The output has been saved to a file.
     Details: 

I noticed that line 648 of miktex-console.log uses both slashes and backslashes when it reports the filename ("...\miktex/bin/x64\initexmf.exe"); could that be a problem?  That line is:
2021-10-19 13:02:05,303-0600 FATAL miktex-console.core - Data: fileName="C:\Users\Daddy\AppData\Local\Programs\MiKTeX 2.9\miktex/bin/x64\initexmf.exe", exitCode="1", savedOutput="C:\Users\Daddy\AppData\Local\MiKTeX\2.9\miktex\log\initexmf_2021-10-19-130205.out"

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/7376318/miktex-report.txt)

[miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/7376326/miktex-makefmt.log)
[initexmf.log](https://github.com/MiKTeX/miktex/files/7376327/initexmf.log)

[pdflatex.log](https://github.com/MiKTeX/miktex/files/7376369/pdflatex.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/7376374/miktex-console.log)

[2021-10-19-11-50-58.log](https://github.com/MiKTeX/miktex/files/7378083/2021-10-19-11-50-58.log)

**Comment by edocevoli** [comment]
Thank you. I was not able to reproduce the problem with the given information. You haven't provided essential log files (like `miktex-pdftex.log`, `*.out`) which makes it impossible to find the root cause. 
That said, it's not possible to work on this issue effectively.

You can add further information later, if you wish.

**Comment by gl-utah** [comment]
Thank you very much for letting me know what important information was missing from my submission.  I have uploaded miktex-pdftex.log and some .out files with this message.  I had to change the extension of the .out files in order to upload them to GitHub.  There are more .out files; I uploaded the earlier ones showing the problem, but I can upload later ones if it would be helpful.  I have also included a list of all the files less than one day old in C:\Users\Daddy\AppData\Local\MiKTeX\2.9\miktex\log and in all of its subdirectories, called "RecentLogFiles.txt"; if uploading any of them would be helpful, I would be happy to do it.

[miktex-pdftex.log](https://github.com/MiKTeX/miktex/files/7381402/miktex-pdftex.log
[miktex-makefmt_2021-10-19-115059.out.txt](https://github.com/MiKTeX/miktex/files/7381421/miktex-makefmt_2021-10-19-115059.out.txt)
)
[miktex-makefmt_2021-10-19-115135.out.txt](https://github.com/MiKTeX/miktex/files/7381423/miktex-makefmt_2021-10-19-115135.out.txt)
[miktex-makefmt_2021-10-19-115542.out.txt](https://github.com/MiKTeX/miktex/files/7381438/miktex-makefmt_2021-10-19-115542.out.txt)

[miktex-makefmt_2021-10-19-115601.out.txt](https://github.com/MiKTeX/miktex/files/7381442/miktex-makefmt_2021-10-19-115601.out.txt)
[miktex-pdftex.log](https://github.com/MiKTeX/miktex/files/7381450/miktex-pdftex.log)
[RecentLogFiles.txt](https://github.com/MiKTeX/miktex/files/7381537/RecentLogFiles.txt)
