### ISSUE TITLE
All the repositories give an outdated error

### ISSUE THREAD

**Issue by karishnu** [MiKTeX/miktex#96]
MiKTeX Problem Report
Message: The remote package repository is outdated. You have to choose another repository.
Data: url="https://mirrors.sorengard.com/ctan/systems/win32/miktex/tm/packages/"
Source: Libraries/MiKTeX/PackageManager/RestRemoteService.cpp
Line: 275
MiKTeX: 2.9
OS: Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Invokers: .../?/launchd/osascript
SystemAdmin: yes
Root0: /Users/karishnu/Library/Application Support/MiKTeX/texmfs/config
Root1: /Users/karishnu/Library/Application Support/MiKTeX/texmfs/data
Root2: /Users/karishnu/Library/Application Support/MiKTeX/texmfs/install
Root3: /Library/Application Support/MiKTeX/texmfs/config
Root4: /Library/Application Support/MiKTeX/texmfs/data
Root5: /Library/Application Support/MiKTeX/texmfs/install
UserInstall: /Users/karishnu/Library/Application Support/MiKTeX/texmfs/install
UserConfig: /Users/karishnu/Library/Application Support/MiKTeX/texmfs/config
UserData: /Users/karishnu/Library/Application Support/MiKTeX/texmfs/data
CommonInstall: /Library/Application Support/MiKTeX/texmfs/install
CommonConfig: /Library/Application Support/MiKTeX/texmfs/config
CommonData: /Library/Application Support/MiKTeX/texmfs/data

I tried changing the repository but it did not help.

**Comment by edocevoli** [comment]
Works for me... Please try it again.

**Comment by karishnu** [comment]
Working now :)
