### ISSUE TITLE
verbatimbox incompatibility?

### ISSUE THREAD

**Issue by dan1982code** [MiKTeX/miktex#967]
This is reproduced on several Windows systems with completely up to date MikTeX and packages... MWE:

```
\documentclass{article}
\usepackage{verbatimbox}
\begin{document}

\addvbuffer[4pt]{A test}
\end{document}
```

The error is

```
! Undefined control sequence.
\\addvbuffer [#1]#2->\getargsC
                               {#1}\setlength \boxtop@sep {\argi }\if 1\narg...
l.5 \addvbuffer[4pt]{A test}
```

Thank you!

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

**Comment by edocevoli** [comment]
This is not a MiKTeX-specific bug and so cannot be fixed by me.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).
