### ISSUE TITLE
Not able to compile TeX document and errors in MiKTeX Console

### ISSUE THREAD

**Issue by SimMan0815** [MiKTeX/miktex#968]
I use TeXStudio (4.0.4) together with MiKTeX (4.4) which used to work just fine. Without doing major changes or updates it stopped working. I cannot compile the document in TeXStudio anymore.
Console Error: "Befehl konnte nicht gestartet werden: "C:/Users/[username]/AppData/Local/Programs/MiKTeX/miktex/bin/x64/bibtex.exe" "[document]"    (translation: Command could not be started: "C:/....")

I tried to resolve the issue by looking into the MiKTeX Console but keep getting errors by startup and every other button I press (searching for updates etc.)

Error report when searching for updates: C:\jenkins\workspace\miktex\windows\build\source\Libraries\MiKTeX\Core\Session\papersize.cpp:243: internal error

Error report which is showing up just some time after starting MiKTeX:
File is locked: {0} --> Details: path="C:\Users\[username]\AppData\Roaming\MiKTeX\2.9\miktex/lock\package-manager.lock"

I tried to re-install MiKTeX and also did a local cleanup without any success.

If I have to provide further information please let me know (first error report)

Thanks a lot for your help!

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
