### ISSUE TITLE
Automatic installation fails due to 

### ISSUE THREAD

**Issue by jgsuess** [MiKTeX/miktex#969]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I have installed purged and reinstalled miktex on Ubuntu 20.04 latest patch.

I see an error with a package manager lock that I cannot address. As a result of  this error, automatic package installation fails. Short of incremental manual install or installing the whole distribution, the system is not usable for me.

Below is the error:

```
2021-11-12 21:27:46,214+1000 FATAL pdflatex.core - Permission denied: path="/usr/local/share/miktex-texmf/miktex/lock"
```

I have rebooted the machine to ensure all file handles would be released.

I have looked in all expected locations using key terms.

I believe this must be something fairly straightforward. Hence I am only offering the log and shell information on the session.

Given the installation is new and purged, it it unlikely to be some prior state.

I have also changed permission to make them more lenient. This leads to further permission issues, involving `mikex.ini`.

It feels like the initial installation has not set the permissions correctly to allow user-side on-the-fly install. I have ensured that this setting is correct.

```bash

This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.6)
entering extended mode
(sn-article.tex
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-10-18> (sn-jnl.cls
Document Class: sn-jnl 2019/11/18 v0.1: An authoring template for Springer Jour
nal articles
(/usr/local/share/miktex-texmf/tex/latex/base/article.cls
Document Class: article 2021/02/12 v1.4n Standard LaTeX document class
(/usr/local/share/miktex-texmf/tex/latex/base/fleqn.clo)
...
======================================================================
starting package maintenance...
installation directory: /usr/local/share/miktex-texmf
package repository: https://mirror.aarnet.edu.au/pub/CTAN/systems/win32/miktex/tm/packages/

Unfortunately, the package booktabs could not be installed.
Please check the log file:
/home/jg/.miktex/texmfs/data/miktex/log/pdflatex.log
======================================================================


! LaTeX Error: File `booktabs.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

```

[pdflatex.log](https://github.com/MiKTeX/miktex/files/7527210/pdflatex.log)

**Comment by jgsuess** [comment]
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/7527313/miktex-report.txt)

**Comment by jgsuess** [comment]
```

**Comment by edocevoli** [comment]
Please create the lock directory manually by running

```sh
mkdir /usr/local/share/miktex-texmf/miktex/lock"
```

This should fix the issue.

**Comment by jgsuess** [comment]
```
jg@jg-OptiPlex-9020-AIO:~$ sudo mkdir /usr/local/share/miktex-texmf/miktex/lock
[sudo] password for jg: 
mkdir: cannot create directory ‘/usr/local/share/miktex-texmf/miktex/lock’: File exists
```

**Comment by jgsuess** [comment]
Please reopen. Fix does not apply or work.

**Comment by edocevoli** [comment]
If the directory exists, then remove it and recreate it:

```sh
rmdir /usr/local/share/miktex-texmf/miktex/lock
mkdir /usr/local/share/miktex-texmf/miktex/lock
```

Please note that this is a system-dependent issue, i.e., I cannot fix it because I do not have access to your system. If you need further help, I would suggest that you ask the person which manages your system.

**Comment by jgsuess** [comment]
I _am_ the person that manages my system. Which means I have to give up on Miktex, as out of people to ask. I would supply any data required for analysis though. If I receive something like the below from a package installed without modifications, I wonder how much of a system-dependent issue this actually is. How and where does Miktex capture a fault stack like this? `'miktex-repo` clearly is not containing anything like this, and the log also is not enough.

```
root@jg-OptiPlex-9020-AIO:/home/jg# miktexsetup --shared=yes --package-set=basic  download
miktexsetup: MiKTeX encountered an internal error.
```

**Comment by edocevoli** [comment]
If you are the administrator of your system, then you should have the right tools to find out why the lock directory is not writable. Maybe some 3rd party (antivirus, malware, ...) is the blocking point.
Good luck

**Comment by jgsuess** [comment]
Please see below. The directory is world writable. This does not address the issue.

```
jg@jg-OptiPlex-9020-AIO:~$ sudo chmod ugo+rwx /usr/local/share/miktex-texmf/miktex/lock
jg@jg-OptiPlex-9020-AIO:~$ ls -alg /usr/local/share/miktex-texmf/miktex/lock
total 8
drwxrwxrwx 2 root 4096 Nov 15 12:05 .
drwxr-xr-x 4 root 4096 Nov 15 08:32 ..
jg@jg-OptiPlex-9020-AIO:~$ sudo miktexsetup --shared=yes --package-set=basic --verbose download
miktexsetup: MiKTeX encountered an internal error.
```

**Comment by jgsuess** [comment]
Installation works when build is run with `sudo`. Seems administrator mode delegation is not working properly.
```
OK, entering \batchmodejg@jg-OptiPlex-9020-AIO:~/git/616e4151d0395a7efe4fd615$ pdflatex sn-article
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.6)
entering extended mode
(sn-article.tex
LaTeX2e <2021-11-15>
L3 programming layer <2021-11-12> (sn-jnl.cls
Document Class: sn-jnl 2019/11/18 v0.1: An authoring template for Springer Jour
nal articles

======================================================================
starting package maintenance...
installation directory: /usr/local/share/miktex-texmf
package repository: https://mirror.aarnet.edu.au/pub/CTAN/systems/win32/miktex/tm/packages/

Unfortunately, the package crop could not be installed.
Please check the log file:
/home/jg/.miktex/texmfs/data/miktex/log/pdflatex.log
```
