### ISSUE TITLE
I cannot uninstall MiKTeX

### ISSUE THREAD

**Issue by JacquesCremer** [MiKTeX/miktex#97]
When I try to uninstall MiKTeX I get the following error message: 
**************
MiKTeX Problem Report
Message: Invalid argument: path="C:\Users\Jacques\AppData\Local\MiKTeX\2.9\miktex/data/le\df2c24cb21984fa85003c1ecc818ff83.fndb"
Data: path="C:\Users\Jacques\AppData\Local\MiKTeX\2.9\miktex/data/le\df2c24cb21984fa85003c1ecc818ff83.fndb"
Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
Line: 507
MiKTeX: 2.9
OS: Windows 10 Pro, 64-bit, build 16299
Invokers: non-existing/explorer
SystemAdmin: no
PowerUser: no
Root0: C:\Users\Jacques\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Jacques\AppData\Local\MiKTeX\2.9
Root2: C:\Users\Jacques\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Users\Jacques\Dropbox\Jacques\LaTeX\Root
Root5: C:\BaKoMa TeX\TEXMF
Root6: C:\Program Files (x86)\MiKTeX 2.9
UserInstall: C:\Users\Jacques\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\Jacques\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Jacques\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files (x86)\MiKTeX 2.9

CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9
***********
But the file "C:\Users\Jacques\AppData\Local\MiKTeX\2.9\miktex\data\le\df2c24cb21984fa85003c1ecc818ff83.fndb" does exist on my computer.

**Comment by edocevoli** [comment]
Seems that the file cannot  be deleted because it is in use. Please close other applications before uninstalling MiKTeX.

**Comment by JacquesCremer** [comment]
Thank you. Indeed it worked. And I have reinstalled MiKTeX (I kept running in the same type of problems when upgrading).
