### ISSUE TITLE
The repository 'http://miktex.org/download/ubuntu focal Release' does not have a Release file

### ISSUE THREAD

**Issue by stilren** [MiKTeX/miktex#970]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Following the install instructions for ubuntu yields the following error at ```sudo apt-get update```

Reading package lists... Done
E: The repository 'http://miktex.org/download/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
