### ISSUE TITLE
Unable to check for updates or install packages - SSL connection?

### ISSUE THREAD

**Issue by nickvinn** [MiKTeX/miktex#971]
Hello! I just installed 21.8 on 64-bit Windows 7. At the first launch I get the message that I did not check for updates. Pressing the button 'Check for updates' results in error. If I try to install some packages (like newtx, for example), I get 'SSL connect error'. These are some temporary issues with Internet repository?
Here is the error report:

GENERAL MIKTEX INFORMATION
ReportDate: 2021-11-17 17:12:12
CurrentVersion: 21.8
SetupDate: 2021-11-17 17:08:00
SetupVersion: 21.8
Configuration: Regular
GitInfo: 30e6b49 / 2021-08-06 15:45:04
OS: Windows 7 Ultimate, 64-bit, Service Pack 1, build 7601
SharedSetup: no
LinkTargetDirectory: C:\Users\predbannik\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
LastUpdateDb: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\predbannik\AppData\Roaming\MiKTeX
Root1: C:\Users\predbannik\AppData\Local\MiKTeX
Root2: C:\Users\predbannik\AppData\Local\Programs\MiKTeX
UserInstall: C:\Users\predbannik\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\predbannik\AppData\Roaming\MiKTeX
UserData: C:\Users\predbannik\AppData\Local\MiKTeX
Invokers: explorer

The following issues were detected:
  1: major issue: So far, you have not checked for MiKTeX updates.

ERROR DETAILS
Program: miktex-console
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:247
Error: SSL connect error
Details: 
  code: 35
  url: https://api2.miktex.org/hello

**Comment by edocevoli** [comment]
Sorry, but it's hard to answer this question. And since you provided no further information (log files, screen shots, (have you read the contribution guidelines?)), I would say that this might be a temporary issue. Please wait a day or two and try again.
