### ISSUE TITLE
kpsewhich --var-value case sensitive?

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#974]
I have an enviroment variable TEXMFHOME which points to a folder where I want l3build to install files. If I query with kpsewhich for it I get different results with TeXlive and MiKTeX. In texlive the casing doesn't matter, the environment variable is always returned. In MiKTeX I get the list of local roots if I use uppercase:

## TeXLive

~~~~
TEXMFHOME=C:\Users\Nililand-Surface\Documents\gitinstalltexmf

C:\test>kpsewhich --var-value=texmfhome
C:/Users/Nililand-Surface/Documents/gitinstalltexmf

C:\test>kpsewhich --var-value=TEXMFHOME
C:/Users/Nililand-Surface/Documents/gitinstalltexmf
~~~~

## MiKTeX

C:\test>kpsewhich --var-value=texmfhome
C:\Users\Nililand-Surface\Documents\gitinstalltexmf

C:\test>kpsewhich --var-value=TEXMFHOME
{C:/Users/Nililand-Surface/tex/mtpro2lite,C:/Users/Nililand-Surface/tex/UFlocaltexmf, ... more texmf trees}

As l3build uses the uppercase variant in its code the installation breaks in miktex.

**Comment by edocevoli** [comment]
MiKTeX has no notion of a TEXMF home directory and so `kpsewhich --var-value=TEXMFHOME` just returns a list of unmanaged user roots.

You can duplicate this "bug" with TeX Live by editing setting `TEXMFHOME` (in `texmf.cnf` or as an
environment variable):

```sh
TEXMFHOME=/abra:/ka:/dabra
```

The TL documentation says:

```
% Per-user texmf tree(s) -- organized per the TDS, as usual.  To define
% more than one per-user tree, set this to a list of directories in
% braces, as described above.  (This used to be HOMETEXMF.)  ~ expands
% to %USERPROFILE% on Windows, $HOME otherwise.
```

**Comment by u-fischer** [comment]
I didn't wonder about the list format but why miktex returns a different value for `texmfhome`  and `TEXMFHOME`.

I have an environment variable TEXMFHOME set, and in texlive such an environment variable takes precedence over the setting in texmf.cnf and texlive returns it in both cases.  But miktex returns it only if I query "texmfhome" but ignores it for TEXMFHOME.   (we can work around it, l3build could check the environment and not use kpsewhich instead), but imho it is a bit odd that miktex is here case sensitive.

**Comment by edocevoli** [comment]
> but why miktex returns a different value for texmfhome and TEXMFHOME.

`texmfhome` and `TEXMFHOME` are two different variables. This is on Cygwin:

```sh
export texmfhome=tralala
kpsewhich --var-value=texmfhome
kpsewhich --var-value=TEXMFHOME
```

Output:

```
tralala
/cygdrive/c/Users/USERNAME/.local/share/texmf
```

I think your observation (`texmfhome` and `TEXMFHOME` are the same) is Windows-specific.

**Comment by edocevoli** [comment]
> But miktex returns it only if I query "texmfhome" but ignores it for TEXMFHOME

MiKTeX is not TeX Live, and so `miktex-kpsewhich` is a fake. MiKTeX's fake implementation ignores the environment.

**Comment by u-fischer** [comment]
OK, so basically better don't rely on texmfhome. We will adapt the l3build setup to get a more reliable result. Hopefully it will then work on miktex too at some time.
