### ISSUE TITLE
21.8: Package installation failure

### ISSUE THREAD

**Issue by nickvinn** [MiKTeX/miktex#975]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

Hello!
I installed 21.8 on Windows 7 Ultimate x64 SP1. When I try to install extra package (newtx) using Packages in MiKTeX Console, I get (screenshot is attached):
Error: SSL connect error
Details: 
  code: 35
  url: https://api2.miktex.org/hello

Pressing "Check for updates" button in Overview results in the same error. The problem persists for more than a week. Logs are attached. If you need more information, please let me know.

GENERAL MIKTEX INFORMATION
ReportDate: 2021-11-26 19:34:49
CurrentVersion: 21.8
SetupDate: 2021-11-17 17:08:00
SetupVersion: 21.8
Configuration: Regular
GitInfo: 30e6b49 / 2021-08-06 15:45:04
OS: Windows 7 Ultimate, 64-bit, Service Pack 1, build 7601
SharedSetup: no
LinkTargetDirectory: C:\Users\predbannik\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: not yet
LastUpdate: not yet
LastUpdateDb: not yet
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\predbannik\AppData\Roaming\MiKTeX
Root1: C:\Users\predbannik\AppData\Local\MiKTeX
Root2: C:\Users\predbannik\AppData\Local\Programs\MiKTeX
UserInstall: C:\Users\predbannik\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\predbannik\AppData\Roaming\MiKTeX
UserData: C:\Users\predbannik\AppData\Local\MiKTeX
Invokers: explorer

The following issues were detected:
  1: major issue: So far, you have not checked for MiKTeX updates.

ERROR DETAILS
Program: miktex-console
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:247
Error: SSL connect error
Details: 
  code: 35
 url: https://api2.miktex.org/hello

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/7609955/miktex-report.txt)
[mkfntmap.log](https://github.com/MiKTeX/miktex/files/7609956/mkfntmap.log)
[mpmcli.log](https://github.com/MiKTeX/miktex/files/7609957/mpmcli.log)
![PackageInstallationFailure](https://user-images.githubusercontent.com/94544908/143611133-cc0331d7-ab9f-4778-8196-d94c6974cdb1.jpg)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/7609958/pdflatex.log)
[texify.log](https://github.com/MiKTeX/miktex/files/7609959/texify.log)
[texworks.log](https://github.com/MiKTeX/miktex/files/7609960/texworks.log)
[initexmf.log](https://github.com/MiKTeX/miktex/files/7609961/initexmf.log)
[miktex-console.log](https://github.com/MiKTeX/miktex/files/7609962/miktex-console.log)
[miktex-fc-cache.log](https://github.com/MiKTeX/miktex/files/7609963/miktex-fc-cache.log)
[miktex-makefmt.log](https://github.com/MiKTeX/miktex/files/7609964/miktex-makefmt.log)
[miktex-pdftex.log](https://github.com/MiKTeX/miktex/files/7609965/miktex-pdftex.log)

**Comment by edocevoli** [comment]
Thank you. This is a known issue. You can find possible workaround by searching open/closed issues.
