### ISSUE TITLE
FATAL miktex-epstopdf - Input file name not allowed in restricted mode

### ISSUE THREAD

**Issue by LukeOwlclaw** [MiKTeX/miktex#978]
Having ``\epsfig{file=../bilder/012.eps, width=9cm}`` causes 

    FATAL miktex-epstopdf - Input file name not allowed in restricted mode: ../bilder/028.eps

It seems that relative paths with `..` cause this problem. How to avoid?

https://docs.miktex.org/manual/miktex.ini.html mentions `AllowUnsafeInputFiles = true` but how to enable this setting?

### Discussed in https://github.com/MiKTeX/miktex/discussions/760

<div type='discussions-op-text'>

<sup>Originally posted by **grosenberg** March 22, 2021</sup>
Trying to generate a Pdf from markdown source using Pandoc/MikTex (Windows 7 & basic-miktex-21.2-x64). The markdown includes a latex block to include an EPS-encoded graphic file.

The problem is, miktex-epstopdf is failing with the error "Input file name not allowed in restricted mode". Any insights on what is going on and how to fix/workaround the problem would be greatly appreciated.

The actual latex used to include the EPS-encoded graphic file is:

```
    \begin{figure}[htp]
         \begin{center}
               \graphicspath{{C:/Users/me/AppData/Local/Temp/liveview/pdf-0626/}}
               \includegraphics[width=0.8\\textwidth]{fluent-64543343.eps}
         \end{center}
    \end{figure}
```

The file is verified to exist, is readable by all, and contains the correct content. Note that the file is exists under my Windows standard temporary folder root.

The exact error is:

```
2021-03-21 22:24:08,141-0700 INFO  miktex-epstopdf - this process (9680) started by 'cmd' with command line: miktex-epstopdf --outfile=C:/Users/me/AppData/Local/Temp/liveview/pdf-0626/fluent-64543343-eps-converted-to.pdf C:/Users/me/AppData/Local/Temp/liveview/pdf-0626/fluent-64543343.eps
2021-03-21 22:24:08,150-0700 WARN  miktex-epstopdf - security risk: running with elevated privileges
2021-03-21 22:24:08,290-0700 FATAL miktex-epstopdf - Input file name not allowed in restricted mode: C:/Users/me/AppData/Local/Temp/liveview/pdf-0626/fluent-64543343.eps
2021-03-21 22:24:08,290-0700 FATAL miktex-epstopdf - Input file name not allowed in restricted mode: C:/Users/me/AppData/Local/Temp/liveview/pdf-0626/fluent-64543343.eps
```

ReportDate: 2021-03-21 23:10:25
CurrentVersion: 21.3
SetupDate: 2021-03-21 20:52:00
SetupVersion: 21.2
Configuration: Regular
GitInfo: ab8ebca / 2021-03-19 10:22:46
OS: Windows 7 Home Premium, 64-bit, Service Pack 1, build 7601
SharedSetup: yes
LinkTargetDirectory: C:\Program Files\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheckAdmin: 2021-03-21 20:55:20
LastUpdateAdmin: 2021-03-21 20:53:53
LastUpdateDbAdmin: 2021-03-21 20:55:19
SystemAdmin: yes
RootPrivileges: yes
AdminMode: yes
Root0: C:\ProgramData\MiKTeX
Root1: C:\Program Files\MiKTeX
CommonInstall: C:\Program Files\MiKTeX
CommonConfig: C:\ProgramData\MiKTeX
CommonData: C:\ProgramData\MiKTeX
</div>

**Comment by edocevoli** [comment]
The unrestricted variant is named `miktex-epstopdf-unrestricted`.

**Comment by LukeOwlclaw** [comment]
Thanks, but how can I tell miktex to use that version? I see that ``miktex-epstopdf`` and the unrestricted version are identical. So just renaming will not help.

I am calling:

    lualatex.exe -synctex=1 -interaction=nonstopmode "buch".tex

(using TeXStudio)

and I found no documentation telling me how I can tell it to use the unrestricted version of epstopdf.

**Comment by LukeOwlclaw** [comment]
I found a [solution](https://tex.stackexchange.com/questions/129339/epstopdf-conversion-problem): Change the TeXStudio options for the ``lualatex`` call and add ``-shell-escape``:

    lualatex.exe -synctex=1 -interaction=nonstopmode -shell-escape %.tex

**Comment by edocevoli** [comment]
You have to use the "unsafe/unrestricted" variant of LuaTeX: `--enable-write18`. You must not running it as administrator.

**Comment by JesseKaczmarski** [comment]
> I found a [solution](https://tex.stackexchange.com/questions/129339/epstopdf-conversion-problem): Change the TeXStudio options for the `lualatex` call and add `-shell-escape`:
> 
> ```
> lualatex.exe -synctex=1 -interaction=nonstopmode -shell-escape %.tex
> ```

Thank you for this. I don't understand why this was needed. All I did was replace my eps files with a new version (same name and everything), and it broke. Adding -shell-escape to the pdflatex command fixed it.
