### ISSUE TITLE
Having difficulty in updating Miktex

### ISSUE THREAD

**Issue by PeteArm** [MiKTeX/miktex#98]
Downloaded and installed latest Miktex version. Found out that Miktex Console now handles the updating and installation of  packages. My difficulty is that I am unable to do this, due to the following error report:

MiKTeX Problem Report
Message: Invalid argument: path="C:\Users\Peter Robertson\AppData\Local\MiKTeX\2.9\miktex/data/le\df2c24cb21984fa85003c1ecc818ff83.fndb"
Data: path="C:\Users\Peter Robertson\AppData\Local\MiKTeX\2.9\miktex/data/le\df2c24cb21984fa85003c1ecc818ff83.fndb"
Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
Line: 507
MiKTeX: 2.9
OS: Windows 10 Home, 64-bit, build 16299
Invokers: non-existing/explorer
SystemAdmin: no
PowerUser: no
Root0: C:\Users\Peter Robertson\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Peter Robertson\AppData\Local\MiKTeX\2.9
Root2: C:\ProgramData\MiKTeX\2.9
Root3: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Peter Robertson\AppData\Roaming\MiKTeX\2.9
UserConfig: C:\Users\Peter Robertson\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Peter Robertson\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

What is going on?

**Comment by edocevoli** [comment]
You should close all MiKTeX applications before installing the updates.

**Comment by frederico-klein** [comment]
Maybe the error message can say this?
