### ISSUE TITLE
dvisvgm: unexpected error in conjunction with raw SVG elements

### ISSUE THREAD

**Issue by mgieseki** [MiKTeX/miktex#983]
The following issue currently occurs only with the MiKTeX build of dvisvgm. Unfortunately, I can't reproduce it with my local Windows or Linux builds and am therefore unable to track down the cause of the issue. Since I don't have the resources to set up a complete MiKTeX build environment required to debug the MiKTeX binaries, it would be great if someone could help to isolate the bug.

Small example:
```tex
% rawtest.tex
\documentclass{article}
\begin{document}
x
\special{dvisvgm:raw <!-- a comment -->}
\end{document}
```
Run LaTeX and dvisvgm on the `.tex` and `.dvi` file, respectively:
```
latex rawtest
dvisvgm rawtest
```
The latter leads to an unexpected error message:
```
ERROR: error in special: expected '-->' at end of comment
```
The corresponding code is located in file [`DvisvgmSpecialHandler.cpp`](https://github.com/mgieseki/dvisvgm/blob/c68da43328c96f915e727b70a6c09fc1df5cf425/src/DvisvgmSpecialHandler.cpp#L469).

**Comment by mgieseki** [comment]
Thank you for the immediate fix! I'll replace the cumbersome `std::ptr_fun` construction  with a similar expression in the dvisvgm sources as well.

**Comment by edocevoli** [comment]
This has been fixed.
