### ISSUE TITLE
reaching the format and language dialog

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex#99]
The entry `miktex settings` in my start menu no longer calls `mo.exe` but to the console with `--start-page settings`. This makes is bit difficult to reach the dialogs regarding formats (definition and building) and the language settings.  Could the links be added again until the console contains also these maintenance tools?

**Comment by edocevoli** [comment]
Thank you, I have added the missing tabs (Formats, Languages) to the Settings page (MiKTeX Console).

A preview is available via  MiKTeX NEXT.
