### ISSUE TITLE
pdffonts shows all the fonts name to none

### ISSUE THREAD

**Issue by Jenaloe** [MiKTeX/miktex#993]
- [ ] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
I'm trying to complile my tex file with pdflatex and embed all the fonts used, but have problem with the fonts name. From pdffonts I got the names to be [none] and also the Acrobat shows the font name to be something like F1, F23, F101, no real name is there. Could anyone help with this?

MiKTeX-pdfTeX 4.10 (MiKTeX 21.12)
© 1982 D. E. Knuth, © 1996-2021 Hàn Thế Thành
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.8, 13-Jul-2019
compiled with curl version 7.72.0; using libcurl/7.72.0 Schannel
compiled with expat version 2.2.10; using expat_2.2.10
compiled with jpeg version 9.4
compiled with liblzma version 50020052; using 50020052
compiled with libpng version 1.6.37; using 1.6.37
compiled with libressl version LibreSSL 3.1.4; using LibreSSL 3.1.4
compiled with MiKTeX Application Framework version 4.2.1; using 4.2.1
compiled with MiKTeX Core version 4.10; using 4.10
compiled with MiKTeX Archive Extractor version 4.0; using 4.0
compiled with MiKTeX Package Manager version 4.5; using 4.5
compiled with uriparser version 0.9.4
compiled with xpdf version 4.02
compiled with zlib version 1.2.11; using 1.2.11
![fonts issue](https://user-images.githubusercontent.com/95860670/145398941-696233ed-c88f-4e0a-a8b0-aef8610dee51.png)

**Comment by edocevoli** [comment]
I don't think this is a MiKTeX issue.
